install/README.md
Added some pre-requisites to more clearly delineate the requirements for an OCI DNS zone.
=> Oci dns readme addition

uninstall/uninstall-steps/0-uninstall-applications.sh, uninstall/uninstall-steps/1-uninstall-istio.sh, uninstall/uninstall-steps/2-uninstall-system-components.sh, uninstall/uninstall-steps/3-uninstall-verrazzano.sh, uninstall/uninstall-steps/4-uninstall-keycloak.sh, uninstall/uninstall-verrazzano.sh
Goals to fix:
- Rancher namespace grep was grabbing too many items
- delete finalizers created by rancher in all namespace deletions
- delete rancher within API before deleting resources
=> Update Rancher grep to be more namespace specific

install/3-install-verrazzano.sh, install/chart/templates/01-verrazzano-operator.yaml, install/chart/values.yaml
https://jira.oraclecorp.com/jira/browse/VZ-1187
=> remove sslVerify

install/chart/values.yaml
This pull request updates the verrazzano-operator image version to v0.0.94-eed5952-1
=> Move verrazzano-operator to v0.0.94-eed5952-1

install/3-install-verrazzano.sh, install/chart/templates/01-verrazzano-operator.yaml, install/chart/templates/02-verrazzano-cluster-operator.yaml, install/chart/templates/03-verrazzano-monitoring-operator.yaml, install/chart/templates/04-verrazzano-admission-controller.yaml, install/chart/values.yaml, install/logging.sh
Update the Verrazzano Helm chart to pull infrastructure images from ghrc.io
=> Pull infrastructure images from ghcr.io

install/chart/templates/03-verrazzano-monitoring-operator.yaml, install/chart/values.yaml
Transition some more images to ghcr.io
- ghcr.io/verrazzano/elasticsearch
- ghcr.io/verrazzano/prometheus-pushgateway
- ghcr.io/verrazzano/kibana
- ghcr.io/verrazzano/configmap-reload
=> Transition some more images to ghcr.io

.github/workflows/pagerduty.yml, examples/sock-shop/sock-shop-binding.yaml, examples/sock-shop/sock-shop-model.yaml, ignore_copyright_check.txt, install/4-install-keycloak.sh, install/common.sh, keycloak-oracle-theme/Jenkinsfile
Publish keycloak-oracle-theme images to ghcr.io
Fix some copyright notices
=> Publish keycloak-oracle-theme images to ghcr.io

install/common.sh
Update install to pull keycloak-oracle-theme image from ghcr.io
=> Update install to pull keycloak-oracle-theme image from ghcr.io

examples/bobs-books/README.md
Added a section to the README of the Bob's Books sample application that describes how to test the application after it is installed.  This change is being done in response to one of our users asking how to test Bob's books.
=> Update Bob's Books readme with instructions on how to test the application

install/chart/values.yaml
Build:  https://build.verrazzano.io/job/verrazzano/job/jmaron%252FVZ-1395/
=> Promote verrazzano operator v.0.0.102-24f5934-2

examples/bobs-books/README.md, examples/hello-helidon/README.md, examples/sock-shop/README.md
Reviewed and edited the example applications' READMEs to bring them into alignment with each other, style guidelines, and Verrazzano terminology.
=> edit READMEs

examples/bobs-books/README.md
The numbering restarted after step 2. I tried further indenting the bulleted items. The preview looks good. Fingers crossed.
=> fix formatting

install/chart/crds/verrazzano.io_verrazzanomodels_crd.yaml, install/chart/values.yaml
This pull request includes a new version of verrazzano-operator, verrazzano-admission-controller, and verrrazzano model crd to support generic components.
=> Update installer to include generic component feature 

.verrazzano-development-version, keycloak-oracle-theme/Dockerfile, keycloak-oracle-theme/Jenkinsfile
change keycloak-oracle-theme image tag formatting: "${VERRAZZANO_DEV_VERSION}-${SHORT_COMMIT_HASH}-${BUILD_NUMBER}"
=> Consistent Docker Image Tag Formatting

install/chart/crds/verrazzano.io_verrazzanomodels_crd.yaml, install/chart/values.yaml
Uptake changes to verrazzano-operator for VZ-1351: Logs from generic comp sent to elasticsearch
=> VZ-1351: Logs from generic comp sent to elasticsearch

install/README.md, install/install-olcne.md
Mostly minor edits upon second review. @mark-au Please verify (or comment on) the change in the following sentence, "These load balancers will route HTTP/HTTPS traffic from the Internet to the private subnet."
=> second review and edit

install/chart/values.yaml
Update  Verrazzano Operator image version in helm chart for VZ-1384 build.
=> Update Verrazzano Operator image version in helm chart for VZ-1384

install/1-install-istio.sh
Remove call to undefined function named `dump-jobs`
=> Remove call to undefined function named dump_jobs

.github/workflows/pagerduty.yml
* use curl directly instead of restricted action
* changed source field
=> JIRA:VZ-1601 modify workflow to use curl directly

README.md
* Update README.md to add Helm install instructions on Cloud Shell
=> update readme for Cloud Shell with Helm install instructions

install/chart/templates/01-verrazzano-operator.yaml, install/chart/templates/02-verrazzano-cluster-operator.yaml, install/chart/templates/03-verrazzano-monitoring-operator.yaml, install/chart/templates/04-verrazzano-admission-controller.yaml, install/chart/values.yaml
uptake micro-operators structured logging
=>  VZ-1315 uptake micro-operators structured logging

README.md
Removed the extra instructions for CloudShell that are no longer needed
=> Fix README for CloudShell use

install/3-install-verrazzano.sh
This fixes an issue with the VZ-1736 change when the INSTALL_PROFILE is not set in the env.
=> Fix default for INSTALL_PROFILE, -u is being used for scripts

install/chart/templates/01-verrazzano-operator.yaml, install/chart/templates/03-verrazzano-monitoring-operator.yaml, install/chart/values.dev.yaml, install/chart/values.prod.yaml, install/chart/values.yaml
Update installer and values files to use new settings for dev/prod profiles.
Depends on
https://github.com/verrazzano/verrazzano-operator/pull/205
https://github.com/verrazzano/verrazzano-monitoring-operator/pull/49
=> VZ-1741.  Adopt new profiles implementation in script installer

controllers/verrazzano_controller.go
This pull request refactors the Reconcile function by breaking out the function into other functions.
=> Refactor the Reconcile function

install/create_oci_config_secret.sh
Realized that the script was reading the OCI config file to obtain each property so modified the script to read the OCI config file once and obtain all section properties.
=> JIRA:VZ-1771 optimize the script performance

Jenkinsfile, Makefile, operator/README.md, operator/deploy/operator.yaml
Reverts verrazzano/verrazzano#391
=> Revert "Update platform-operator image in operator.yaml"

operator/Dockerfile, operator/scripts/install/chart/values.yaml, operator/scripts/install/config/mysql-values-template.yaml
Pull Oracle Linux images from GHCR instead of OCR
=> Get Oracle Linux images from GHCR

Jenkinsfile, Makefile, operator/README.md, operator/deploy/operator.yaml
This pull request adds a Jenkins stage to update operator.yaml with a newly built image.  This happens only with the develop and master branches.  The commit for updating operator.yaml is authored by the verrazzanobot user.  Also, we are using the Jenkins Ignore Committer Strategy plugin to ignore commits from the verrazzanobot user to avoid another build running.
=> Update operator.yaml with built image

operator/internal/util/log/log_test.go
=> Fix code coverage regression

install.md, operator/README.md
Fix some incorrect file paths in the readme documents
=> Fix some incorrect file paths in the readme documents

examples/hello-helidon/README.md, examples/hello-helidon/hello-world-model.yaml
Remove instructions for creating an OCR secret.  They are not required anymore.
=> Remove instructions for ocr secret

operator/scripts/install/3-install-verrazzano.sh, operator/scripts/install/chart/templates/01-verrazzano-operator.yaml, operator/scripts/install/chart/templates/02-verrazzano-cluster-operator.yaml, operator/scripts/install/chart/values.yaml
=> update cluster- and verrazzano-operator to support in-cluster connection to rancher

.verrazzano-development-version, operator/scripts/install/chart/Chart.yaml
Updating development version from 0.7.0 to 0.8.0
=> Updating development version from 0.7.0 to 0.8.0

operator/scripts/install/1-install-istio.sh, operator/scripts/install/chart/values.yaml, operator/scripts/install/common.sh
Update remaining OCR image references to use ghcr.io
=> Update remaining OCR image references to use ghcr.io

operator/deploy/operator.yaml
Update the operator.yaml with the correct image
=> update the operator.yaml with the correct image

Makefile
The pull requests fixes the Makefile manifests target.  It was generating a bad operator.yaml file
=> Fix make manifests

operator/api/verrazzano/v1alpha1/verrazzano_webhook.go, operator/main.go
This pull request fixes the formatting of log messages.
=> Fix formatting of log messages

operator/deploy/operator.yaml
startup probe added to operator which monitors the webhook listening port to discern when that listener is up and ready to process incoming requests.
=> JIRA:VZ-1911 create startup probe for verrazzano operator

operator/config/scripts/run.sh, operator/internal/util/helm/helmcli.go
Remove creating kubeconfig for platform operator in run.sh.  Also remove setting kubeconfig ENV var from helmcli.go, since it is not needed.
=> Remove creating kubeconfig for platform operator

operator/scripts/install/chart/values.yaml, operator/scripts/install/common.sh
=> Use 0.8.0 component images

examples/bobs-books/bobs-books-model.yaml
=> update image tags

CONTRIBUTING.md, README.md
Add CONTRIBUTING.md
Updates to README to largely delegate to other docs for content
=> README Updates

Makefile
Update copyright and handle changed behaviour with ineffassign
=> Update copyright and handle changed behaviour with ineffassign

operator/scripts/install/chart/values.dev.yaml, operator/scripts/install/chart/values.yaml
Make "shared VMI" the default for all profiles.
=> VZ-1852: Default Behavior to Use Shared VMI

operator/config/samples/install-dev.yaml
Just to make it a little easier for users to install using the dev profile.
=> Sample install yaml that uses the dev profile

Jenkinsfile
Jenkins pipeline makes a git commit at the end of the build & if there were subsequent commits since the build started git push fails.  To make this failure less likely move the git commit to beginning of Jenkinsfile.  In the event the commit fails, uses the groovy postbuild plugin to update build description to describe why it failed.
=> Jenkins Pipeline Git Commimt

.gitignore, operator/Makefile
This pull request fixes a couple of Makefile regressions.
=> Fix Makefile regressions from OAM merge

Jenkinsfile
Remove unused region code from the Jenkins build pipeline
=> Remove unused region code from the Jenkins build pipeline

operator/scripts/install/components/coherence-values.yaml, operator/scripts/install/components/weblogic-values.yaml
WebLogic & Coherence operator images from GHCR
=> Images from GHCR

oam-application-operator/deploy/verrazzano.yaml_template, operator/thirdparty/charts/oam-application-operator/templates/verrazzano-application-operator.yaml
Add startup probe to the oam-application-operator container to ensure webhooks are ready.
=> Add startup probe to the oam-application-operator container

.verrazzano-development-version, operator/scripts/install/chart/Chart.yaml
Updating development version from 0.8.0 to 0.9.0
=> Updating development version from 0.8.0 to 0.9.0

platform-operator/Dockerfile, platform-operator/config/scripts/run.sh
=> Fix incorrect paths in dockerfile for platform operator

operator/scripts/install/chart/Chart.yaml, platform-operator/scripts/install/chart/Chart.yaml
=> Fix incorrect update from 0.8.0 release process

platform-operator/scripts/install/chart/values.yaml
Use  ghcr.io/oracle/weblogic-kubernetes-operator:3.1.0
=> use WLS Operator image from ghcr.io/oracle

platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml
Update application operator Chart dev version to 0.9.0
=> Update app operator Chart version

platform-operator/helm_config/overrides/keycloak-values.yaml, platform-operator/scripts/install/chart/values.yaml
Update development image versions to 0.9.0
=> Update dev image tags

Jenkinsfile
This PR changes the default behavior to run the AT's unless user opts out with `skip-at` in the commit message, or using Jenkins parameter.
=> Run AT's by default, unless skipped by commit message

application-operator/deploy/application-operator.txt, application-operator/examples/todo/install-todo.sh
Adds some resiliency to todo install such as retry on failure to apply todo application.
This is required for the todo acceptance tests.
=> Changes to todo install script needed for VZ-1915

application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/loggingscope/wls.go, application-operator/controllers/loggingscope/wls_test.go
- helidon/wls index name:  oam-namespace-applicationconfigurationname-componentname
- additional fields in wls/helidon log record
> oam.applicationconfiguration.name
> oam.applicationconfiguration.namespace 
> oam.component.namespace  
> oam.component.name
=> fully qualified elasticsearch index name

application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
Coverage for the new Coherence workload controller is now > 80%.
```
ok  	github.com/verrazzano/verrazzano/application-operator/controllers/cohworkload	0.484s	coverage: 84.1% of statements
```
=> More Coherence workload unit tests to boost coverage

platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh, platform-operator/scripts/uninstall/uninstall-steps/1-uninstall-istio.sh, platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh, platform-operator/scripts/uninstall/uninstall-steps/4-uninstall-keycloak.sh
https://jira.oraclecorp.com/jira/browse/VZ-2078
=> attempt to fix rancher uninstall

tools/scripts/k8s-dump-cluster.sh
Add helm info back to capture, add config map info, add api-resource info
=> Add helm info back to capture, add confgmap and api-resources to capture

application-operator/Makefile, application-operator/hack/add-crd-header.sh, application-operator/hack/add-yml-header.sh, application-operator/hack/boilerplate.go.txt, application-operator/hack/boilerplate.yaml.txt
- Update copyright boilerplate
- Fix copyright header scripts to distinguish existing files from new files and add the correct headers
=> Fix boilerplate copyright headers

application-operator/test/templates/coherence_workload_statefulset.yaml
=> Remove reference

Jenkinsfile
=> remove defunct parameters from Jenkinsfile

platform-operator/THIRD_PARTY_LICENSES.txt, platform-operator/controllers/verrazzanomanagedcluster/verrazzanomanagedcluster_controller.go, platform-operator/controllers/verrazzanomanagedcluster/verrazzanomanagedcluster_controller_test.go, platform-operator/go.mod, platform-operator/main.go, platform-operator/test/integ/integ_test.go, platform-operator/test/integ/testdata/vmc_sample.yaml, platform-operator/test/integ/util/exec.go
The initial set of a controller and reconciler for VerrazzanoManagedCluster resources.  The reconciler does not do any real work yet.
Added integration tests for testing the creating and deletion of VerrazzanoManagedCluster resources.
Added unit tests for the new controller.
=> Initial setup of controller and reconciler for VerrazzanoManagedCluster objects

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.9.0 to 0.10.0
=> Updating development version from 0.9.0 to 0.10.0

application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/loggingscope/loggingscope_controller.go, application-operator/controllers/loggingscope/wls.go, application-operator/controllers/loggingscope/wls_test.go, application-operator/controllers/webhooks/appconfig_defaulter.go, application-operator/mocks/logging_scope_handler_mock.go, application-operator/test/integ/integ_test.go, application-operator/test/integ/k8s/resource.go, application-operator/test/integ/testdata/hello-app-v0.yaml, application-operator/test/integ/testdata/hello-app-v1.yaml, application-operator/test/integ/testdata/hello-comp.yaml, application-operator/test/integ/testdata/loggingscope.yaml
fix appconfig UPDATE operation by requeue the loggingscope.reconcile event
=> fix appconfig UPDATE operation

examples/hello-helidon/README.md
Changes to Readme of hello-helidon example based on comments from @rosemarymarano on https://github.com/verrazzano/verrazzano/pull/588
=> Changes to Readme of hello-helidon example

examples/hello-helidon/README.md
Edited README to clean up style issues and to match other examples
=> cleanup style

examples/sock-shop/README_OAM.md, examples/springboot-app/README.md, examples/todo-list/README.md
Clean up wording and style in OAM examples except Hello World Helidon (because @bhatpmk has a pending PR on it).
=> doc cleanup

examples/hello-helidon/README.md, examples/sock-shop/README_OAM.md, examples/springboot-app/README.md, examples/todo-list/README.md
Further edits to the example READMEs.
=> more edits

examples/todo-list/README.md
Need to include a prerequisite item for accepting the license agreement, otherwise the image pull fails. I also formatted the section with bullets to make it easier to read.
N/A just a README change.
=> Add prerequisite for accepting example image license agreement

application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/clusters/multiclustercomponent/multiclustercomponent_controller.go, application-operator/controllers/clusters/multiclustercomponent/multiclustercomponent_controller_test.go, application-operator/controllers/clusters/multiclustercomponent/testdata/hello-multiclustercomponent.yaml, application-operator/controllers/clusters/multiclustercomponent/testdata/hello-oam-comp-existing.yaml, application-operator/controllers/clusters/multiclustersecret/multiclustersecret_controller.go, application-operator/controllers/clusters/multiclustersecret/multiclustersecret_controller_test.go, application-operator/main.go, application-operator/test/integ/k8s/resource.go, application-operator/test/integ/multi_cluster_test.go, platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclustercomponents.yaml
Created a controller for MultiClusterComponent and did some refactoring to share code between this and previously created MultiClusterSecret controller. Added unit and integration tests.
Part of VZ-2063
Provide details about how you tested this changed, if necessary
provide instructions to reproduce the testing.
=> Create MultiClusterComponent Controller

application-operator/controllers/wlsworkload/weblogicworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
PR includes:
- Add support for delete in VerrazzanoWebLogicWorkload
- Additional unit tests to boost coverage to > 80%
- Small refactoring to make some strings constants/shared
=> VZ-2047: Add support for delete in VerrazzanoWebLogicWorkload

platform-operator/test/integ/integ_test.go
Integration test needs to wait until webhook is ready before submitting a request, otherwise webhook will fail.
=> Integration test needs to wait until webhook is ready

tests/e2e/pkg/web.go
resolve xip.io ourselves in the acceptance test.
=> resolve xip.io ourselves in the acceptance test

platform-operator/helm_config/charts/verrazzano/templates/01-verrazzano-operator.yaml
Add cluster role objects for project-specific roles.
=> Add project roles to platform operator helm template

platform-operator/Dockerfile
Update kubectl version in platform-operator Docker image
=> Update kubectl version in platform-operator Docker image

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_appconfig.go, application-operator/mcagent/mcagent_appconfig_test.go, application-operator/mcagent/mcagent_common.go, application-operator/mcagent/mcagent_component.go, application-operator/mcagent/mcagent_component_test.go, application-operator/mcagent/mcagent_configmap.go, application-operator/mcagent/mcagent_configmap_test.go, application-operator/mcagent/mcagent_loggingscope.go, application-operator/mcagent/mcagent_loggingscope_test.go, application-operator/mcagent/mcagent_secret.go, application-operator/mcagent/mcagent_secret_test.go
Refactor some of the cluster agent code based on review feedback of earlier PR's for VZ-2065.
=> Refactor some cluster agent code based on review feedback

ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster, ci/uninstall/Jenkinsfile
This PR adds the missing configuration to checkout the source from the current branch. Also it fixes the condition to trigger PagerDuty alert.
=> Check-out the source from current branch and fix the condition to trigger PagerDuty  

application-operator/apis/clusters/v1alpha1/multiclustersecret_types.go, application-operator/apis/clusters/v1alpha1/verrazzanoproject_types.go, application-operator/config/crd/bases/clusters.verrazzano.io_multiclustersecrets.yaml, application-operator/config/crd/bases/clusters.verrazzano.io_verrazzanoprojects.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_verrazzanoprojects.yaml
Add plurals for MultiClusterSecret and VerrazzanoProject CRDs
=> Add plurals for MultiClusterSecret and VerrazzanoProject CRDs

application-operator/constants/constants.go, application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller_test.go, application-operator/controllers/clusters/multiclustercomponent/multiclustercomponent_controller_test.go, application-operator/controllers/clusters/multiclusterconfigmap/multiclusterconfigmap_controller_test.go, application-operator/controllers/clusters/multiclusterloggingscope/multiclusterloggingscope_controller_test.go, application-operator/controllers/clusters/multiclustersecret/multiclustersecret_controller_test.go, application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go, application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go, application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_appconfig.go, application-operator/mcagent/mcagent_appconfig_test.go, application-operator/mcagent/mcagent_component.go, application-operator/mcagent/mcagent_component_test.go, application-operator/mcagent/mcagent_configmap.go, application-operator/mcagent/mcagent_configmap_test.go, application-operator/mcagent/mcagent_loggingscope.go, application-operator/mcagent/mcagent_loggingscope_test.go, application-operator/mcagent/mcagent_project.go, application-operator/mcagent/mcagent_project_test.go, application-operator/mcagent/mcagent_secret.go, application-operator/mcagent/mcagent_secret_test.go, application-operator/mcagent/testdata/verrazzanoproject.yaml, platform-operator/controllers/clusters/vmc_controller_test.go
=> create namespaces specified in a VerazzanoProject in managed cluster.

application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go, application-operator/main.go, application-operator/mcagent/mcagent_appconfig.go, application-operator/mcagent/mcagent_component.go, application-operator/mcagent/mcagent_configmap.go, application-operator/mcagent/mcagent_loggingscope.go, application-operator/mcagent/mcagent_project.go, application-operator/mcagent/mcagent_secret.go
fix syncer logging; add vp controller
=> fix VerrazzanoProject syncer

platform-operator/helm_config/charts/verrazzano/values.yaml
Use v0.10.0 images for verrazzano monitoring instance api & eswait 
=> Update verrazzano monitoring operator and instance API code to 0.10.0

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/helm_config/overrides/keycloak-values.yaml
Updating development version from 0.10.0 to 0.11.0
=> Updating development version from 0.10.0 to 0.11.0

application-operator/controllers/loggingscope/helidon_test.go
Add missing mocker.Finish() calls to helidon_test.go and removed spurious expectations
=> add mocker.Finish() calls to helidon_test.go

examples/README.md
Added a README for the Example Applications in the main repo. @gilbode If you want me to add more descriptive introductory information, such as what each of the example apps demonstrate, please provide the text.
Fixes VZ-9999
=> add README for example apps

application-operator/apis/oam/v1alpha1/loggingscope_types.go, application-operator/config/crd/bases/clusters.verrazzano.io_multiclusterloggingscopes.yaml, application-operator/config/crd/bases/oam.verrazzano.io_loggingscopes.yaml, application-operator/constants/constants.go, application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/clusters/multiclusterloggingscope/controller_test.go, application-operator/controllers/clusters/multiclusterloggingscope/testdata/loggingscope-existing.yaml, application-operator/controllers/clusters/multiclusterloggingscope/testdata/sample-multiclusterloggingscope.yaml, application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/loggingscope/fluentd.go, application-operator/controllers/loggingscope/fluentd_test.go, application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/loggingscope/loggingscope_controller_test.go, application-operator/controllers/loggingscope/wls.go, application-operator/controllers/webhooks/logging_scope_defaulter.go, application-operator/controllers/webhooks/logging_scope_defaulter_test.go, application-operator/mcagent/mcagent_loggingscope_test.go, application-operator/mcagent/testdata/multicluster-loggingscope-update.yaml, application-operator/mcagent/testdata/multicluster-loggingscope.yaml, application-operator/test/integ/testdata/loggingscope.yaml, application-operator/test/integ/testdata/multi-cluster/multicluster_loggingscope_sample.yaml, examples/bobs-books/bobs-books-logging-scope.yaml, examples/todo-list/todo-list-logging-scope.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclusterloggingscopes.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_loggingscopes.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/templates/_validate-inputs.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml
Fluentd honors the ElasticSearchPort in loggingscope.
For VZ-2237
=> loggingscope enhancement for cross-cluster logging

application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/cohworkload/coherenceworkload_controller_test.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, application-operator/controllers/loggingscope/fluentd.go, application-operator/controllers/loggingscope/fluentd_test.go, application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, application-operator/test/integ/integ_test.go, application-operator/test/integ/testdata/loggingscope.yaml
Change logging scope secret behavior to work for managed clusters in WLS and Helidon cases.
Partially Fixes: 2237
=> Change logging scope secret behavior to work for managed clusters

application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/cohworkload/coherenceworkload_controller_test.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, application-operator/controllers/loggingscope/fluentd.go, application-operator/controllers/loggingscope/fluentd_test.go, application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/loggingscope/wls.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, tests/e2e/examples/bobs-books/bobs_books_test.go
=> add verrazzano.cluster.name to log record

application-operator/constants/constants.go, application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/loggingscope/fluentd.go, application-operator/controllers/loggingscope/fluentd_test.go, application-operator/controllers/loggingscope/helidon.go, application-operator/controllers/loggingscope/helidon_test.go, application-operator/controllers/webhooks/logging_scope_defaulter_test.go
Move ES URL to verrazzano-cluster-elasticsearch secret
Fixes VZ-2296
=> Move ES URL to verrazzano-cluster-elasticsearch secret

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.11.0 to 0.12.0
=> Updating development version from 0.11.0 to 0.12.0

Jenkinsfile, application-operator/Dockerfile, platform-operator/Dockerfile
This PR removes the "RUN_EXAMPLES_TESTS" parameter and replaces it with the option to run either just the "merge" or "fast" tests, or all of the tests, including the "slow" ones.
This also introduces a fix/workaround for the YUM issue seen in builds today.
=> Introduce parameter to control running fast/slow tests

Jenkinsfile, ci/kind/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/rolebased/Jenkinsfile
Remove calls to kind load image - OCR issue with containerd is resolved.
=> Remove calls to kind load image

application-operator/Dockerfile, platform-operator/Dockerfile
Adapt our Dockerfiles now that yesterday's YUM/OCI issue seems to have been resolved upstream. 
=> update after yum repo fix went live

tests/testdata/istio/authz/bar/istio-securitytest-app.yaml, tests/testdata/istio/authz/foo/istio-securitytest-app.yaml, tests/testdata/istio/authz/noistio/istio-securitytest-app.yaml
Fixes VZ-9999
AT updates captured in VZ2137 once the infrastructure is in
=> Update Auth Policy AT to use correct Springboot metrics scrape target

examples/bobs-books/bobs-books-comp.yaml
This PR picks up a new version of the roberts-coherence image which has some updated dependencies.
=> Pick up new roberts-coherence image in Bob's Books example

Jenkinsfile, ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, tests/e2e/config/scripts/process_operator_yaml.sh
No longer make git commit of operator.yaml, push to object storage instead
=> Use object storage for operator.yaml

tests/e2e/pkg/kubernetes.go
Implementing review comment from https://github.com/verrazzano/verrazzano/pull/694#discussion_r584740071
=> fix typo in info message

ci/kind/Jenkinsfile
This PR corrects paths in the Jenkinsfile for the "new kind AT's."
=> Ffix paths in new-kind-at jenkinsfile

examples/bobs-books/README.md, examples/hello-helidon/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md
=> minor edits

tests/e2e/istio/authz/authpolicy_test.go, tests/e2e/pkg/kubernetes.go
=> Add Acceptance Test to verify https scrape targets

platform-operator/config/samples/install-default.yaml, platform-operator/config/samples/install-dev.yaml, platform-operator/config/samples/install-managed-cluster.yaml, platform-operator/config/samples/install-oci.yaml, platform-operator/config/samples/install-olcne.yaml
Adds an example managed-cluster install profile example and updates the comments in the other samples.
Fixes VZ-2117.
=> Add a managed-cluster install sample 

platform-operator/helm_config/charts/verrazzano/templates/03-verrazzano-monitoring-operator.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/scripts/install/config/keycloak.json, tests/e2e/pkg/common.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/pkg/vmi.go, tests/e2e/pkg/vmi/elastic.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/vmi/vmi_test.go
* Config keycloak with VMI SSO/login redirect
* Uptake new VMO with OIDC proxy enabled
* Change corresponding e2e tests.
Fixes VZ-2298
=> vmi oidc authN

ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster
This PR fixes the issue with Jenkinsfile, which creates the OKE cluster for uninstall and loop tests. Along with that, minor changes were made other CI pipeline scripts
=> Fix the CI pipeline, which creates an OKE cluster

Jenkinsfile, examples/bobs-books/bobs-books-comp.yaml
This PR picks up a new bobs-books-order-manager image which has some updated dependencies.
=> Pick up new image

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.12.0 to 0.13.0
=> Updating development version from 0.12.0 to 0.13.0

examples/bobs-books/bobs-books-comp.yaml
This PR just picks up a newer sample image which updates some dependencies.
=> pcik up new image with updated dependencies

platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/helm_config/overrides/keycloak-values.yaml
Update development image versions to 0.13.0
Fixes VZ-2253
=> Update dev image tags to 0.13.0

platform-operator/helm_config/charts/verrazzano/values.yaml
uptake VO that supports cluster-name in system logs
=> uptake VO that supports cluster-name in system logs

platform-operator/helm_config/charts/verrazzano/values.yaml
update VMO image tag built for verrazzano-monitoring-operator/pull/65 (VZ-2300)
=> update VMO image tag built for verrazzano-monitoring-operator/pull/65

ci/multicluster/Jenkinsfile
Finish up support in MC AT pipeline for OKE clusters
- Fix OCI DNS install setup, add OKE MagicDNS configuration stage
- Fix conditionals on KinD and OKE/MagicDNS stages
- Consolidate installer configuration into a common function
- Cleanup and refactor large script blocks to separate functions
- Fix up cluster configuration stage names, comment helper fns
- Handle special cases around envName for xip.io vs OCI DNS
Fixes VZ-2390.
=> VZ-2390.  MC Test Suite - Perform managed cluster and admin cluster install on OKE

.golangci.yaml, Jenkinsfile, Makefile, application-operator/Makefile, application-operator/test/integ/integ_test.go, build/coverage.sh, make/quality.mk, platform-operator/test/integ/integ_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/pkg/common.go, tests/e2e/pkg/metrics.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/restapi/keycloak_url_test.go, tests/e2e/verify-infra/restapi/vmi_urls_test.go, tests/e2e/verify-infra/vmi/vmi_test.go, tests/e2e/verify-install/web/web_test.go
This PR:
- removes an unused make target, adds a new clean target, 
- improves accuracy of coverage calculation
- replaces fmt, vet, lint and ineffassign with golintci (much faster, more configurable, etc.)
- fixes some lint issues
- includes some small improvements to test code to try to increase stability of some tests that make repeated attempts to call a web resource.
Contributes to VZ-2371
=> Small incremental build improvements

ci/looping-test/Jenkinsfile, ci/uninstall/Jenkinsfile
This change captures the cluster dump on test failure. This PR also contains additional changes to get more information to help debug the issues.
=> Archive cluster dump on failures in uninstall pipeline

ci/kind/Jenkinsfile
This is a very small PR that just updates the descriptions on the automatically run downstream AT's with the commit hash and the version, to make it a bit easier to find the one you are looking for in the list. 
Contributes to VZ-2371
=> Label CI jobs

application-operator/controllers/clusters/cluster_utils.go, application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go, application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go, application-operator/main.go, application-operator/test/integ/k8s/resource.go, application-operator/test/integ/multi_cluster_test.go, application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_invalid_namespace.yaml, application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_default_labels.yaml, application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_override_labels.yaml
A simple status section for per-cluster and overall status for VerrazzanoProject
Fixes VZ-2377
=> PR to add status to VerrazzanoProject

examples/bobs-books/bobs-books-comp.yaml
This small PR just picks up an updated image with some dependency updates.
=> Pick up image with updated dependencies

platform-operator/helm_config/charts/verrazzano/values.yaml
Another update to the VMO image tag built by verrazzano-monitoring-operator/job/master/85/
=> Pick up vmo image tag from build #85

ci/rolebased/Jenkinsfile
This PR has the fix to install the KIND cluster and the required change to the test path.
=> Fix the Jenkins script for Verrazzano role based tests

ci/multicluster/Jenkinsfile, tests/e2e/config/scripts/register_managed_cluster.sh, tests/e2e/multicluster/verify-register/verify_register_suite_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go
acceptance test that verifies the registration of a managed cluster
Fixes VZ-2337
=> acceptance test that verifies the registration of a managed cluster

examples/README.md, examples/hello-helidon/README.md, examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md
Updated the Examples README to include the Multicluster Examples.
=> update examples README

examples/bobs-books/README.md, examples/bobs-books/bobs-books-comp.yaml, tests/e2e/examples/bobsbooks/bobs_books_test.go
Update Bob's book example to use VerrazzanoHelidonworkload instead of ContainerizedWorkload
Fixes VZ-2379
=> Update to use VerrazzanoHelidonworkload

tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/kubernetes.go, tests/testdata/multicluster/verrazzanoproject-managed1.yaml, tests/testdata/multicluster/verrazzanoproject-managed2.yaml
more tests in verify register
Fixes VZ-2337
=> more tests in verify register

application-operator/hack/add-crd-header.sh
=> Remove -verbose rom add-crd-header.sh in application operator.

examples/bobs-books/README.md, examples/bobs-books/bobs-books-comp.yaml, tests/e2e/examples/bobsbooks/bobs_books_test.go
Reverts verrazzano/verrazzano#865
=> Revert "Update to use VerrazzanoHelidonworkload"

tools/fix-copyright/copyright.go, tools/fix-copyright/go.mod
=> Change module of fix-copyright

platform-operator/config/samples/install-oci.yaml, platform-operator/scripts/install/create_oci_config_secret.sh
This pull request includes minor changes to sync with updated OCI DNS documentation.
Fixes VZ-2383
=> Minor changes to sync with OCI DNS documentation

examples/multicluster/README.md, examples/multicluster/change-placement/README.md, examples/multicluster/change-placement/mc-hello-helidon-app.yaml, examples/multicluster/change-placement/mc-hello-helidon-comp.yaml
An en example to demonstrate how to change the placement of an application
Fixes VZ-2232
=> Add a Multi-Cluster example of changing the placement of an application

tests/e2e/pkg/kubernetes.go
=> stop caching clientset in acceptance tests

examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md
Document the steps for de-registering a managed cluster.
Fixes VZ-2344
=> VZ-2344.  Document current managed cluster deregistration steps

ci/multicluster/Jenkinsfile, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_suite_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go
This PR creates a new acceptance test for the multi-cluster hello-helidon example application. The test is integrated into the Jenkins MC AT pipeline. I tested on both 2 and 3 cluster Kind configurations.
Implements VZ-2339
=> VZ-2339: MC hello-helidon acceptance test

platform-operator/helm_config/charts/verrazzano/values.yaml, tools/fix-copyright/copyright.go
… tool
Update console image for VZ-2323, and fix formatting in fix-copyright tool.
Fixes VZ-9999
=> VZ-2323.  Update console image

platform-operator/hack/add-crd-header.sh
fix typo in add-crd-header.sh script
=> fix typo in add-crd-header.sh script

ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster, ci/uninstall/Jenkinsfile
This PR includes the changes required to run the install loop continuously with master branch and changes like sending the slack notification when there the job fails with the master branch.
Fixes VZ-2471
=> Enable the install loop and uninstall tests with master build

platform-operator/helm_config/charts/verrazzano/values.yaml
Update the console image, updated for comments on VZ-2323.
Fixes VZ-2323
=> Update console image for VZ-2323 again

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.13.0 to 0.14.0
=> Updating development version from 0.13.0 to 0.14.0

platform-operator/controllers/verrazzano/installjob/install_config.go, platform-operator/scripts/install/2-install-system-components.sh, tests/e2e/pkg/web.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
Reverts verrazzano/verrazzano#901
Unit tests failed on master, not on the branch, need to rebase and try again
=> Revert "Ddrechse/vz2361"

tools/analysis/internal/util/files/text.go, tools/analysis/internal/util/report/report.go
Quick PR so we can get the issue type included in the report output. Getting that tweak in sooner so reports have that now (automation that may look at the reports can track the issues seen).
This also has a minor cleanup to reduce some duplicate code
=> Cleanup some duplicate code, Add issue type into report output

platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/helm_config/overrides/keycloak-values.yaml
Updates images references to 0.14.0 images.
=> VZ-2466: Update to 0.14.0 images

platform-operator/helm_config/charts/verrazzano/values.yaml
=> update console image version for mc support

ci/multicluster/Jenkinsfile, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/examples/change-placement/change_placement_example_suite_test.go, tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go, tests/e2e/multicluster/examples/example_utils.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/verify-install/defaultresource_test.go, tests/e2e/pkg/api.go, tests/e2e/pkg/common.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/metrics.go, tests/e2e/pkg/resources.go, tests/e2e/pkg/secrets.go, tests/e2e/pkg/vmi.go, tests/e2e/pkg/vmi/elastic.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/restapi/keycloak_url_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go, tests/e2e/verify-infra/restapi/vmi_urls_test.go, tests/e2e/verify-infra/vmi/vmi_test.go
Write an acceptance test for the change-placement multicluster example
Fixes VZ-2338
=> MC Test for Change Placement Example

ci/looping-test/Jenkinsfile
Disable the install-loop pipeline paging/slacksend while we stabilize it.
=> Disable paging/slacksend for now until the loop test is stabilized

application-operator/constants/constants.go, examples/hello-helidon/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md, platform-operator/constants/constants.go, platform-operator/helm_config/charts/verrazzano/templates/04-verrazzano-ingress.yaml, platform-operator/internal/vzinstance/verrazzano_instance.go, platform-operator/internal/vzinstance/verrazzano_instance_test.go, tests/e2e/pkg/api.go, tests/e2e/verify-install/web/web_test.go, tools/analysis/test/cluster/insufficient-mem/cluster-dump/verrazzano-system/events.json
Rename the ingress verrazzano-console-ingress to be verrazzano-ingress.
=> Rename verrazzano-console-ingress to verrazzano-ingress

platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, platform-operator/helm_config/charts/verrazzano/templates/01-verrazzano-operator.yaml, tests/e2e/verify-install/verrazzano/verrazzano_test.go
Had to address following issues:
- role binding for 'verrazzano-project-admin' role - there were some missing resources in the application role definition that it seemed were appropriate to add to allow for the role binding creation to be allowed (i.e. the operator role now includes the same or a superset of the rules to allow the role binding creation to proceed)
- role binding for 'admin' role - this role has extensive administrative permissions so it made more sense to address the need for this role binding creation by specifying the 'bind' verb.
- there were resource references to 'coherences' as the plural for 'coherence', but the CRD actually defines the plural as 'coherence'.  The existing 'coherences' was triggering some issues during role binding creation.
Fixes VZ-2460
As the …
=> JIRA:VZ-2460 address some issues raised by multi cluster testing

application-operator/apis/oam/v1alpha1/verrazzanohelidonworkload_types.go, application-operator/apis/oam/v1alpha1/zz_generated.deepcopy.go, application-operator/config/samples/oam_v1alpha1_verrazzanohelidonworkload.yaml, application-operator/controllers/helidonworkload/helidonworkload_controller.go, platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_verrazzanohelidonworkloads.yaml
Remove replica (ManualScalerTrait) and add Deployment.Strategy (based on hackathon feedback) to Helidon CRD.
Fixes VZ-2450
=> Update Helidon CRD

examples/bobs-books/README.md
Updates Instruction 3 for Bobs Books example.  User would need to update secret names.
=> Fix Bobs Books Example Instruction 3

tools/analysis/README.md, tools/analysis/advice/ImagePullBackOff.md, tools/analysis/advice/ImagePullNotFound.md, tools/analysis/advice/ImagePullRateLimit.md, tools/analysis/advice/ImagePullService.md, tools/analysis/advice/IngressInstallFailure.md, tools/analysis/advice/IngressNoLoadBalancerIP.md, tools/analysis/advice/IngressOciIPLimitExceeded.md, tools/analysis/advice/InstallFailure.md, tools/analysis/advice/InsufficientMemory.md, tools/analysis/advice/PendingPods.md, tools/analysis/advice/PodProblemsNotReported.md
Reviewed and edited the Analysis Tool and Advice files.
Fixes VZ-9999
=> review and edit

platform-operator/scripts/install/2-install-system-components.sh, platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
- Revert use of kubectl apply to create Rancher secret
- add -n to echo command to prevent newline from sneaking into Rancher pwd secret
- Clean up new rancher namespaces/charts
- Clean up verrazzano-mc ns
=> Fix uninstall for new version of rancher

tools/analysis/README.md, tools/analysis/advice/ImagePullBackOff.md, tools/analysis/advice/ImagePullNotFound.md, tools/analysis/advice/ImagePullRateLimit.md, tools/analysis/advice/ImagePullService.md, tools/analysis/advice/IngressInstallFailure.md, tools/analysis/advice/IngressNoLoadBalancerIP.md, tools/analysis/advice/IngressOciIPLimitExceeded.md, tools/analysis/advice/InstallFailure.md, tools/analysis/advice/InsufficientMemory.md, tools/analysis/advice/PendingPods.md, tools/analysis/advice/PodProblemsNotReported.md, tools/analysis/advice/README.md
Re-review and edit of the Analysis Tooling docs.
=> second pass edit

ci/looping-test/Jenkinsfile, tests/e2e/examples/helidonconfig/helidon_config_test.go
Modify looping test Jenkins to patch out Rancher finalizers from install ns
- also fix go fmt issue in tests
=> Modify looping test Jenkins to patch out Rancher finalizers from install ns

examples/README.md, examples/bobs-books/README.md, examples/helidon-config/README.md, examples/hello-helidon/README.md, examples/multicluster/README.md, examples/multicluster/change-placement/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md, platform-operator/README.md
Edited the READMEs for the example applications.
=> edit examples READMEs

application-operator/deploy/verrazzano.yaml_template, application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/verify-infra/vmi/vmi_test.go
* multi-cluster - application-operator/mcagent update system fluentd in managed cluster with mc-registration-secret
* config fluentd in admin cluster to use oidc-proxy
* rename index pattern to verrazzano-*
* helido and containerizedWorkload/springboot functional test
* fix test with date suffix indices
Fixes VZ-2394
=> config fluentd for multi-cluster

tests/e2e/multicluster/verify-permissions/verify_permissions_test.go
add debugging to MC verify permissions test to figure out intermittent issue
=> add debugging to MC verify permissions test

tests/e2e/examples/bobsbooks/bobs_books_test.go
This moves app deployment to BeforeSuite which will end the test run if it fails.  If the app deployment is successful, the complete set of tests will be run against the deployed application
- [x ] Added or updated acceptance tests if appropriate
=> Fail TestSuite if app deploy fails

application-operator/deploy/verrazzano.yaml_template, application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/verify-infra/vmi/vmi_test.go
Reverts verrazzano/verrazzano#974
=> Revert "config fluentd for multi-cluster"

tools/scripts/k8s-dump-cluster.sh
Dump cert-manager `certificaterequest` objects in cluster-dump utility.
=> Dump cert-manager requests

platform-operator/scripts/install/2-install-system-components.sh
Squelch output from the ensure-admin command for Rancher.
=> Squelch output of ensure-admin command

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
Add a cluster dump for the intermittently failing change-placement multi cluster test
=> Do a cluster dump for the change-placement test

tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
Temporarily disable some assertions in MC change placement test while the intermittent failure due to namespace deletion from previous test not completing is being investigated/fixed.
=> Temporarily disable some assertions in MC change placement test

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go
Move MC Test-specific cluster dumps to separate dir
=> Move MC Test-specific cluster dumps to separate dir

ci/looping-test/JenkinsfileCreateCluster, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/uninstall/Jenkinsfile
We're seeing issues in ashburn with OKE (TF problem), remove it from the list in test jobs until the bug is fixed
=> Remove ashburn as OKE region from build jobs until the fix their bug

Jenkinsfile
Enabled test based cluster dumps in main CI run
=> Enable test cluster dumping in main job

tests/e2e/multicluster/examples/helidon/helidon_example_test.go
Reverts VZ-2559: Multi-cluster Example Helidon test instability. Disable tests (verrazzano/verrazzano#1008)
=> Revert VZ-2559: Multi-cluster Example Helidon test instability. Disable tests

tools/scripts/k8s-dump-cluster.sh
Add VerrazzanoProject to cluster dump tool
=> Add VerrazzanoProject to cluster dump tool

ci/uninstall/Jenkinsfile
fix typo in uninstall Jenkinsfile
Tangentially related to VZ-2577 
=> fix typo in uninstall Jenkinsfile

ci/multicluster/Jenkinsfile, platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml, tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/pkg/common.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/vmi/vmi_test.go
* fix fluentd config to enable systemd journal logging on KIND
* remove/replace all the filebeat and journalbeat in e2e tests
* fix parse rule for none-json messages from some operators
* add cluster_name to log record
* fix elasticsearch query, jq in e2e tests
Fixes VZ-2395
=> systemd config fix

application-operator/controllers/loggingscope/fluentd.go, platform-operator/constants/constants.go, platform-operator/controllers/clusters/sync_prometheus.go, platform-operator/controllers/clusters/sync_registration_secret.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/scripts/install/4-install-keycloak.sh
Reverts verrazzano/verrazzano#1025
=> Revert "Add logic to create 2 new internal users for metrics communication be…"

platform-operator/scripts/install/2-install-system-components.sh
use verrazzano-cluster-issuer for rancher ingress
Fixes VZ-2483
=> rancher ingress use certs issued by Verrazzano CA

ci/oke-ocidns/Jenkinsfile
Add us-ashburn-1 as one of the regions in OCI DNS tests.
=> add ashburn to OCI DNS tests

tests/e2e/examples/socks/sock_shop_example_test.go
replace premature FAil with log.
Fixes VZ-2621
=> fix sock_shop test

platform-operator/helm_config/charts/verrazzano/values.yaml
Updates the console to latest version
=> update console version latest

Jenkinsfile
Reverts verrazzano/verrazzano#1080
=> Revert "Suspect notifications Part Deux"

platform-operator/helm_config/charts/verrazzano/values.yaml
update console image version for copyright year change in footer 
=> update console image version for copyright year change in footer 

ci/looping-test/Jenkinsfile
Enable notifications for install loop pipeline failures.
=> Enable notifications on install-loop pipeline failures

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.14.0 to 0.15.0
=> Updating development version from 0.14.0 to 0.15.0

platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml
* Increase buffer to fix elasticsearch connection problem
* Workaround k8s connection problem which will be fixed by updating the fluentd images (VZ-2637)
Fixes VZ-2627
=> fix fluentd config

platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/09-vmi-es-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
Updates to network policies and VMO image id to allow for proper communication between ES resources.
Fixes VZ-2644
=> JIRA:VZ-2644 fixes for proper ES functionality

tests/e2e/pkg/common.go, tests/e2e/pkg/web.go, tests/e2e/verify-install/web/web_test.go
=> VZ-2603: STaaS issue

tests/e2e/security/network-policies/network_policy_test.go
Fix negative egress network policy test failures.
Fixes VZ-2645
=> Network Policy Egress Rules Issues

platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml, tests/e2e/verify-install/web/web_test.go
=> VZ-2601: STaaS issue

application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/cohworkload/coherenceworkload_controller_test.go, go.sum, platform-operator/helm_config/charts/verrazzano/templates/07-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/09-vmi-es-networkpolicy.yaml, tests/e2e/security/network-policies/network_policy_test.go
Remove all NetworkPolicy egress restrictions, allowing all egress from pods.
=> allow all egress for network policies

platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
update fluentd-kubernetes-daemonset image to fluentd v1.12.3
Fixes VZ-2637
=> fluentd-v1.12

examples/todo-list/todo-list-components.yaml, tests/e2e/examples/todo/todo_list_test.go
Manually add Prometheus annotations until WLS fixes Prometheus annotations problem for admin server.
=> Enable metrics test for todo-list

examples/multicluster/hello-helidon/README.md
Minor edits/ cleanup text of the multicluster example README file.
=> edit README

tests/e2e/config/scripts/terraform/cluster/main.tf, tests/e2e/config/scripts/terraform/cluster/multi_cluster_main_tf_template, tests/e2e/config/scripts/terraform/cluster/provider.tf, tests/e2e/config/scripts/terraform/cluster/variables.tf
upgrade tf-oci-oke provider to 3.2.0
=> upgrade tf-oci-oke provider to 3.2.0

README.md, examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md, platform-operator/thirdparty/charts/istio/README-helm3.md, platform-operator/thirdparty/charts/istio/README.md
Some minor text edits/spelling corrections according to the Oracle Style Guide.
=> minor text edits

platform-operator/Makefile
=> Fix typo in .PHONY target

ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, tests/e2e/config/scripts/terraform/cluster/VM.Standard2.4-2.tfvars
default OKE to VM.Standard2.4-2
=> default OKE to VM.Standard2.4-2

application-operator/installer/scripts/2-install-wls-operator.sh, examples/todo-list/todo-list-components.yaml, platform-operator/helm_config/overrides/weblogic-values.yaml, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-cm.tpl, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-role.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, tests/testdata/ingress/console/components.yaml
This pull request updates the WebLogic operator used by Verrazzano to 3.2.3.
In addition, updated the todo-list image used by console tests.
=> Uptake WebLogic operator 3.2.3

tests/e2e/examples/todo/todo_list_test.go
WKO 3.2.3 fixed the prometheus annotations problem for standalone admin server.
=> no need to add prom annotations in todo-list test 

tools/scripts/README.md
Minor formatting and text updates to the README for private registry installation.
=> Private registry installation README updates

platform-operator/controllers/clusters/rancher.go
Updates to Rancher multi-cluster code based on review feedback from the private registry installation work. I updated a function name and tried to improve comments to make it clearer what's going on.
=> Rename a function, try to make the comments better

Jenkinsfile
Followup from the registry PR to change stage name
=> Change stage name

tools/scripts/k8s-dump-cluster.sh
Add ClusterIssuer to CI cluster dumps for diagnosability of some CI failures
=> Add ClusterIssuer to CI cluster dumps

platform-operator/Makefile, tools/scripts/vz-registry-image-helper.sh
Minor fixes to a Makefile and the private registry pull/tag/push helper script, based on PR feedback from the review of the private registry work.
=> Fixes based on PR review of private registry support

platform-operator/controllers/verrazzano/component/cert_manager.go, platform-operator/controllers/verrazzano/component/cert_manager_test.go, platform-operator/controllers/verrazzano/component/helm_component.go, platform-operator/controllers/verrazzano/component/helm_component_test.go, platform-operator/controllers/verrazzano/component/registry.go, platform-operator/controllers/verrazzano/component/testdata/sample_bom.json, platform-operator/scripts/install/2-install-system-components.sh, platform-operator/verrazzano-bom.json
Fix install/upgrade with private registries to work with CM 1.2.
=> Fix private registry install/upgrade with CM 1.2

platform-operator/Dockerfile, tools/analysis/Dockerfile
Fixes a couple of scan errors in the platform operator and analysis tool, CVEs in kubectl and helm.
ELSA-2021-9268
=> Fix helm, kubectl scan errors

tests/e2e/verify-infra/vmi/vmi_test.go
Change caller to controller.  Controller pushes info msgs and they are much more likely to be in elastic search.  mcagent pushes error msgs, i.e. Resource Not Found, and at times, those msgs may not be there.  
=> Resiliency Improvement, check for caller controller which has info msgs

.golangci.yaml, application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go, application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, application-operator/controllers/ingresstrait/ingresstrait_controller_test.go, application-operator/controllers/logging/fluentd.go, application-operator/controllers/logging/wls.go, application-operator/test/integ/integ_test.go, platform-operator/test/integ/integ_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/istio/authz/authpolicy_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/multicluster/verify-resources/verify_resources_test.go, tests/e2e/pkg/environment.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/vmi/vmi_test.go, tools/analysis/internal/util/cluster/install.go, tools/analysis/internal/util/cluster/pods.go
This PR introduces another linter (deadcode) that looks for unused code.  It includes the change to enable this linter, and also fixes for all issues identified by the linter.
=> Add deadcode linter and fix all issues identified by it

platform-operator/verrazzano-bom.json
Update console image version containing change mentioned in https://github.com/verrazzano/console/pull/74
Fixes VZ-9999
=> update console image version 

Jenkinsfile, build/coverage.sh
This pull request contains changes related to code coverage as follows:
1. Exclude code coverage for the generated clientset code
2. Bump the line coverage threshold back to 75%
=> Changes for code coverage

examples/multicluster/README.md, examples/multicluster/sock-shop/README.md, examples/multicluster/sock-shop/sock-shop-app.yaml, examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/multicluster/sock-shop/verrazzano-project.yaml, examples/multicluster/todo-list/README.md, examples/multicluster/todo-list/mc-docker-registry-secret.yaml, examples/multicluster/todo-list/mc-runtime-encrypt-secret.yaml, examples/multicluster/todo-list/mc-tododb-secret.yaml, examples/multicluster/todo-list/mc-weblogic-domain-secret.yaml, examples/multicluster/todo-list/todo-list-application.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/multicluster/todo-list/verrazzano-project.yaml
The artifacts and documentation for deploying the sockshop and todo list sample applications in an MC environment.
Fixes VZ-2791
=> JIRA:VZ-2791 sockshop and todo list mc example apps

examples/bobs-books/bobs-books-comp.yaml, examples/todo-list/todo-list-components.yaml
Update the samples to consume new images from this fix: 
https://github.com/verrazzano/examples/pull/74/files
=> update examples to pick up new images from marco's fix

platform-operator/verrazzano-bom.json
Update to the latest verrazzano-console image
=> Update verrazzano-console image

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.15.0 to 0.16.0
=> Updating development version from 0.15.0 to 0.16.0

platform-operator/verrazzano-bom.json
As part of the release process, this pull request updates the images tags for the development images to 0.16.0
=> Update development image tags to 0.16.0

platform-operator/verrazzano-bom.json
Uptake console version with VerrazzanoProject page updates (Security/Network Policies)
Fixes VZ-2588
=> Uptake console version with VerrazzanoProject page updates

ci/multicluster/Jenkinsfile, platform-operator/controllers/clusters/rancher.go, platform-operator/controllers/clusters/sync_registration_secret.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/scripts/create_managed_cluster_secret.sh, platform-operator/scripts/install/2-install-system-components.sh, platform-operator/scripts/install/config.sh, tests/e2e/config/scripts/register_managed_cluster.sh
This reverts commit 9fe537a716e6933fa7b3c0394db9f97e413c5539.
=> Revert "Fix Rancher managed cluster registration with OCI DNS+ACME

Jenkinsfile
Missing test results, added copying of the files
=> Test results were not being copied

platform-operator/verrazzano-bom.json
Update to UI console version that fixes an issue with links opening in 2 windows.
=> Update to UI console version that fixes links opening in 2 windows

application-operator/installer/scripts/2-install-wls-operator.sh, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
update the weblogic operator to 3.2.4
=> update the weblogic operator to 3.2.4

ci/JenkinsfilePeriodicTests
Fix a parameter setting to be boolean
=> Calico is a boolean parameter

ci/JenkinsfilePeriodicTests
Add short commit hash to capture script parameters
=> Fix periodic test artifact capture

ci/private-registry/Jenkinsfile
Align the netpol and metrics tests to the new locations.
Fixes VZ-2187
=> Fix up changed locations for metrics and netpol tests

platform-operator/scripts/install/2-install-system-components.sh
OCI DNS tests failed with logs showing that cert-manager was successfully rolled out but also showing an error calling the cert-manager webhook.
```
[2021-06-21 16:02:10 UTC] 2021-06-21 16:02:10 UTC In setup_cluster_issuer. Cert Issuer Type = ca
[2021-06-21 16:02:10 UTC] 2021-06-21 16:02:10 UTC Certificate not specified. Creating default Verrazzano Issuer and Certificate in verrazzano-install namespace
[2021-06-21 16:02:10 UTC] Invoking: kubectl apply for 
[2021-06-21 16:02:10 UTC] apiVersion: cert-manager.io/v1
[2021-06-21 16:02:10 UTC] kind: Issuer
[2021-06-21 16:02:10 UTC] metadata:
[2021-06-21 16:02:10 UTC]   name: verrazzano-selfsigned-issuer
[2021-06-21 16:02:10 UTC]   namespace: cert-manager
[2021-06-21 16:02:10 UTC] spec:
[2021-06-21 16:02:10 UTC]   selfSigned: {}
[2021-06-21 …
```
=> OCI DNS tests failed installing Keycloak

examples/bobs-books/README.md, examples/helidon-config/README.md, examples/hello-helidon/README.md, examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md, examples/multicluster/sock-shop/README.md, examples/multicluster/todo-list/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md
Fixed broken links to example instructions.
=> fix links to example instructions

examples/bobs-books/bobs-books-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, tests/testdata/ingress/console/components.yaml
Update example images with wls-exporter.war removed.
Fixes VZ-2706
=> update example images

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.16.0 to 0.17.0
=> Updating development version from 0.16.0 to 0.17.0

platform-operator/verrazzano-bom.json
Update the images in the bom to 0.17.0.
=> update images in bom to 0.17.0

platform-operator/verrazzano-bom.json
This reverts commit a00c0ccbbdc745a250da50f8074ad5c8b09954b0.
=> Revert "update images in bom to 0.17.0 (#1310)"

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/socks/sockshop.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/examples/todo/todo_list_test.go, tests/e2e/ingress/console/console_ingress_test.go, tests/e2e/istio/authz/authpolicy_test.go, tests/e2e/logging/helidon/helidon_logging_test.go, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/multicluster/verify-api/verify_api_test.go, tests/e2e/pkg/acme_ca_certs.go, tests/e2e/pkg/api.go, tests/e2e/pkg/common.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/pkg/environment.go, tests/e2e/pkg/keycloak.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/metrics.go, tests/e2e/pkg/resources.go, tests/e2e/pkg/secrets.go, tests/e2e/pkg/vmi.go, tests/e2e/pkg/vmi/elastic.go, tests/e2e/pkg/web.go, tests/e2e/verify-infra/restapi/keycloak_url_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go, tests/e2e/verify-infra/restapi/vmi_urls_test.go, tests/e2e/verify-infra/vmi/vmi_test.go, tests/e2e/verify-install/web/web_test.go
This PR includes a fair bit of refactoring of shared test code in the `tests/e2e/pkg` code, focused mostly on `web.go`. The changes result in errors being bubbled up to the tests allowing the tests themselves to assert on error conditions. I also consolidated a bunch of utility functions that were very similar (differed by one input arg, etc.)
I also updated several of the test files to dot import gomega and ginkgo. There are still many test files that need the same treatment applied, and that will be done in subsequent PRs.
Note that there is still more refactoring to do, and this won't address all of our test code issues, but it's a step in the right direction.
Fixes VZ-2908
=> VZ-2908: Refactor acceptance test code

platform-operator/verrazzano-bom.json
This reverts commit 96b0fe65e35cacc92f590bbc049c194134f76bc8.
Update versions in the bom to 0.17.0.
=> Revert "Revert "update images in bom to 0.17.0 (#1310)" (#1311)"

application-operator/installer/scripts/2-install-wls-operator.sh, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Uptake WebLogic Kubernetes Operator 3.2.5
Fixes VZ-2931
=> uptake weblogic operator 3.2.5

tests/testdata/install-configurations/install-dev-pvc-keycloak-override.yaml, tests/testdata/install-configurations/install-prod-override-pvc-all.yaml, tests/testdata/install-configurations/install-prod-pvc-all-override.yaml, tests/testdata/install-configurations/install-prod-pvc-keycloak-override.yaml
Update the copyrights for the install examples, add another one.
Fixes VZ-2764
=> Fix up install configuration updates, and a prod global pvc override example

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/socks/sockshop.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/examples/todo/todo_list_test.go, tests/e2e/pkg/web.go
This PR improves the example acceptance tests by:
1. Adding `Eventually` around calls that should be retried
2. Removing `Expect` calls inside `Eventually`
3. Use dot imports for `gomega` and `ginkgo`
I also added `nil` checks in the custom matchers in `web.go`.
Note that I put all of the dot import changes into a single commit to make it easier to review the other changes.
Additional acceptance tests will be improved in subsequent PRs.
Implements VZ-2909
=> VZ-2909: Example acceptance test improvements

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 0.17.0 to 0.18.0
=> Updating development version from 0.17.0 to 0.18.0

platform-operator/verrazzano-bom.json
Updates BOM with initial 0.18.0 upstream images.
Related VZ-2953
=> VZ-2953: Release 0.17.0. Uptake initial 0.18.0 upstream images.

image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go, image-patch-operator/helm_config/charts/image-patch-operator/crds/images.verrazzano.io_imagebuildrequests.yaml
Add jdk and weblogic versions to ImageBuildRequest
Fixes VZ-3060
=> Mgelleca/vz-3060 - add jdk and weblogic versions to imagebuildrequest

pkg/proxy/nginx_conf_template.go, platform-operator/verrazzano-bom.json
=> VZ-2912 changed console image tag and added content-type to nginx_conf_template.go 

platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh, platform-operator/verrazzano-bom.json
* Update BOM and additional rancher images for private registry
* Fix uninstall to remove additional rolebindings and MutatingWebhookConfiguration created by this version of Rancher
Fixes VZ-2986
=> VZ-2986: Update to use Rancher 2.5.9

tools/scripts/k8s-dump-cluster.sh
Enhanced cluster dump to help diagnose VZ-3040
=> Include statefulsets in cluster dump

ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/todo/todo_list_test.go, tests/e2e/pkg/certs.go, tests/e2e/pkg/secrets.go, tools/scripts/k8s-dump-cluster.sh
Various modification to address current test failures, including:
- temporary removal of AP region from OKE related build due to historical and current issues with image pulling.  A story will be filed to track the need for better image pull resiliency
- Sockshop:  extend wait for namespace termination
- Todo-list:  additional logging to try to discern why the cert secret is intermittently not deleted and triggers a failure.  Also introduced a check to ensure the certificate resource has been deleted.
- dump cluster script fix to ensure the target namespace's resource description is save to namespace folder rather than all namespaces saved to each namespace folder
Fixes/Addresses VZ-3099, VZ-3101, VZ-3095
=> Modifications to alleviate test failures and introduce additional logging 

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml, platform-operator/verrazzano-bom.json
Updating development version from 0.18.0 to 1.1.0
=> Updating development version from 0.18.0 to 1.1.0

platform-operator/verrazzano-bom.json
PR to update the console image tag with the newest one from the console master build 
=> updated image tag

tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/multicluster/examples/example_utils.go, tests/e2e/multicluster/verify-install/defaultresource_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/api.go, tests/e2e/pkg/common.go, tests/e2e/pkg/elasticsearch.go, tests/e2e/pkg/environment.go, tests/e2e/pkg/keycloak.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/metrics.go, tests/e2e/pkg/resources.go, tests/e2e/pkg/secrets.go, tests/e2e/pkg/vmi.go, tests/e2e/pkg/web.go, tests/e2e/pkg/weblogic/weblogic.go, tests/e2e/security/rbac/rbac_test.go, tests/e2e/verify-infra/oam/oam_test.go, tests/e2e/verify-infra/restapi/keycloak_url_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go, tests/e2e/verify-infra/restapi/vmi_urls_test.go, tests/e2e/verify-infra/vmi/vmi_test.go, tests/e2e/verify-install/keycloak/keycloak_test.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go, tests/e2e/verify-install/web/web_test.go, tools/cli/vz/cmd/app/helidon/create.go, tools/cli/vz/cmd/app/helidon/list.go, tools/cli/vz/cmd/root.go
This pull request fixes all eventually checker issues found in tests/e2e/pkg/kubernetes.go. Since these changes required errors being returned a number of other source files required change.
Fixes VZ-3120
=> Fix eventually checker issues found in kubernetes.go

ci/looping-test/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
fix fluentd 'pattern not matched' errors on OKE k8s v1.20.8
Fixes VZ-3148
=> fix 'pattern not matched' on OKE k8s v1.20.8

tests/e2e/multicluster/verify-permissions/verify_permissions_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go
Fix linter errors in Eventually clauses for e2e tests
=> Fix linter errors in e2e tests

image-patch-operator/controllers/imagebuildrequest_controller.go, image-patch-operator/controllers/imagebuildrequest_controller_test.go
Disable istio-injection on the image patch operator job
=> Disable istio-injection on the image patch operator job

tests/e2e/multicluster/verify-register/verify_register_test.go
=> fix linter failure in verify-register-test

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/config/samples/install-optional.yaml, platform-operator/controllers/verrazzano/installjob/install_config.go, platform-operator/controllers/verrazzano/installjob/install_config_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/scripts/install/3-install-verrazzano.sh, platform-operator/scripts/install/config.sh
Reverts verrazzano/verrazzano#1383
=> Revert "Allow Fluentd to be optional when installing Verrazzano"

platform-operator/verrazzano-bom.json
Updated console image with scan issues fixed
Fixes VZ-9999
=> update console image version with fixed scan issues

ci/JenkinsfileTestTrigger, ci/upgrade/Jenkinsfile, platform-operator/internal/util/helm/helmcli.go
This PR adds upgrade to the triggered tests.   Change the upgrade to do an install of the latest minor release version, which is 1.0 now.  Also, I found some helm intermittent issues with upgrade and put retry logic and additional logging.
=> Add upgrade triggered test 

ci/upgrade/Jenkinsfile
Get the bom using the branch name and commit id so that the bom syncs up with the operator.yaml.
=> Upgrade should get bom using commit id

platform-operator/Dockerfile, tools/analysis/Dockerfile, tools/scripts/vz-registry-image-helper.sh
This change updates the kubectl version in the Dockerfile of platform operator and analysis tool to v..20.6-2.
=> Update kubectl version to 1.20.6-2 fix security vulnerability

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
This PR uses a better RNG to create seed value for the WKO MII key.
Fixes VZ-3275
=> use crypto/rand instead of math/rand

examples/multicluster/todo-list/todo-list-components.yaml
Fix the JDBC URL to use the correct namespace, mc-todo-list
=> Change the multicluster todo list JDBC string

ci/scripts/update_periodic_on_success.sh
Fix bad invocation of Zip generation script for periodic tests.
=> Fix invocation of Zipfile generation for periodic tests

ci/scripts/update_periodic_on_success.sh
Fix the generated BOM download.
=> Another attempted fix for the periodic test zip generation

ci/JenkinsfilePeriodicTests
Add email/slack/PD notifications on periodic test suite failures.
=> Add Slack/PD trigger to the periodic tests

Jenkinsfile, ci/JenkinsfileTestTrigger, ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/scripts/metric_del.sh, ci/scripts/metric_emit.sh, ci/scripts/oci_metric_emit.sh, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
emit metrics from jenkins build and tests stages
Fixes VZ-3289
=> emit jenkins metrics

pkg/proxy/auth_lua_template.go, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml
=> backport fix for vz-2996

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
This pull request backports the update of Coherence Operator to v3.2.1. 
Commit 3d76aa73b0fb85571f51ba381bc30ffbb20de144 was cherry picked for this pull request.
Fixes VZ-3333
=> Backport: Update Coherence Operator to v3.2.1

ci/looping-test/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
VZ-3148 (release-1.0 back port) fix 'pattern not matched' on OKE k8s v1.20.8
Fixes VZ-3148
=> VZ-3148 (release-1.0 back port) fix 'pattern not matched' on OKE k8s v1.20.8

ci/kind/Jenkinsfile
The additional logging from the previous PR has yet to reveal the reason.  Therefore, this PR increases the amount of debug logging and adds the envoy proxy from the nginx controller to see if the root cause of the 503 lies with that proxy.
Reference:  https://medium.com/expedia-group-tech/all-about-istio-proxy-5xx-issues-e0221b29e692
Fixes VZ-3353
=> JIRA:VZ-3353 enable full debug logging and add nginx istio proxy to logged proxies

ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
Don't fail the Jenkins job if the post action to emit metrics fails
Fixes a spurious Jenkins failure
=> Don't fail the Jenkins job if the post action to emit metrics fails

platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Update Helm chart versions for patch release 1.0.1
=> Update Helm chart versions for patch release 1.0.1

pkg/proxy/auth_lua_template.go, pkg/proxy/conf_lua_template.go, pkg/proxy/nginx_conf_template.go, pkg/proxy/proxy_config.go, pkg/proxy/proxy_config_test.go, pkg/proxy/reload_sh_template.go, pkg/proxy/startup_sh_template.go, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
Remove conditional inclusion directives so that all api and oidc proxy code is present. Update code to be able to distinguish between api proxy and oidc proxy requests and handle them appropriately. Update code to direct oidc-proxy requests to the backend service they're for.
Partial fix for VZ-3419.
=> WIP: VZ-3419: POC of combined api/oidc proxy

ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, tests/e2e/config/scripts/create_kind_cluster.sh
We've been seeing intermittent failures in master at least where the Kind cluster creation itself is failing. There is not enough info there to debug what happened though. We saw a spurt of activity this morning, but attempts to reproduce the issue spinning test runs has not shown the issue again.
This adds a few things:
- --retain to the cluster creation
- guard to check if kind create failed, this will then export kind logs and archive them, then will fail immediately 
=> Tvlatas/debug kindat VZ-3460 & VZ-3461 related

pkg/proxy/auth_lua_template.go, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
Minor fixes for keycloak host configuration
=> Minor fixes for keycloak host configuration

platform-operator/scripts/install/3-install-verrazzano.sh
Backport VZ-3278 fix to release-1.0
=> Update the URL reference for the OKE troubleshooting (#1465)

Jenkinsfile, ci/private-registry/Jenkinsfile, ci/scripts/generate_product_zip.sh
Updates to the top-level product zip generation and testing for private registry installs
- Add a top-level readme.txt to the zip file to satisfy ARU upload requirements.
- Do not automatically build/test the Zip file in release-* branches
- Fix the branch repo name used for the private registry repos (so it's the actual branch name and not "detached")
Fixes VZ-3240
=> Zip file/private registry pipeline update

Jenkinsfile, ci/JenkinsfilePeriodicTests, ci/private-registry/Jenkinsfile, ci/scripts/generate_product_zip.sh, ci/scripts/update_periodic_on_success.sh, tests/e2e/config/scripts/create_ocir_repositories.sh
Backport of build changes for private registry zip file generation and testing from master.
- generate the PLS/ARU accepted Zip format and test it automatically when GENERATE_TARBALL is checked
Includes the following commits:
f025724705974e90c0cb1835579a4d42a64410d2
6a5b842b3b03cd1f7ac0b88a9da0f986e1e520ea
c9df75942fa37328574adfad9a6b8daab5df0735
290e690642f76ae7310a05e8e158e6d0202482af
62f64b32d4f4d30f35fac18c8b1bcf4908c5330e
9f08f8b8f314895014b4c906833cd22c7b32fae0
=> Backport private registry zip file generation and test updates to 1.0

platform-operator/controllers/verrazzano/component/helm_component.go, platform-operator/controllers/verrazzano/component/registry.go, platform-operator/controllers/verrazzano/controller_test.go, platform-operator/scripts/install/3-install-verrazzano.sh
=> VZ-3241.  Move COH operator install to platform operator

tools/analysis/internal/util/cluster/verrazzano.go, tools/analysis/main_test.go, tools/analysis/test/cluster/install-unknown/cluster-dump/verrazzano-install/events.json, tools/analysis/test/cluster/install-unknown/cluster-dump/verrazzano-install/pods.json, tools/analysis/test/cluster/install-unknown/cluster-dump/verrazzano-install/verrazzano-install-my-verrazzano-p7mqx/logs.txt
Backport analysis tool update to find resources after move
=> Tvlatas/vz 3432 (#1513)

ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
First run of new branches was hitting failure. Fix interpolation problem with TAGGED_TESTS, use params. prefix
=> Fix interpolation problem with TAGGED_TESTS, use params. prefix

ci/upgrade/Jenkinsfile, platform-operator/internal/helm/helmcli.go
Remove some accidentally checked in debug output.
=> No Bug.  Remove some local debug output that got checked in

ci/kind/Jenkinsfile
Fix console screenshots not being captured on Jenkins console test failure.
=> Fix console screenshots not being captured on Jenkins console test failure

Jenkinsfile
Add release-1.* pattern for notifications so we get alerted when the release branch builds fail
=> Add release-1.* pattern for notifications

ci/ticket-commits/JenkinsfileCommits, ci/ticket-commits/JenkinsfilePullRequests
This PR adds two Jenkinsfiles for JIRA & Git automation. One Jenkinsfile records Git commits in JIRA tickets for the master and release branches. The commit messages must have the JIRA ticket(s) otherwise JIRA tickets are not updated.
The other Jenkinsfile handles pull requests. When a PR is created, if the title contains one or more JIRA ticket ids, the JIRA tickets will be updated with a link to the PR.
Implements VZ-3301
=> VZ-3301: Initial commit of Jenkinsfiles for jira/git automation

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
conditional configmap data es-url and es-secret in verrazzano-logging helm template
=> conditional configmap data es-url and es-secret in verrazzano-logging helm template

platform-operator/helm_config/charts/verrazzano/values.yaml
default values for logging helm chart
=> default values for logging helm chart

platform-operator/scripts/install/2-install-system-components.sh
This pull request backports VZ-3329 changes to 1.0.2
=> VZ-3329 backport to 1.0.2

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/vmi-es-networkpolicy.yaml
Tweak network policy files to minimize diffs vs. master.
=> minimize network policy diffs vs. master

application-operator/controllers/webhooks/multicluster_validation.go, application-operator/controllers/webhooks/multicluster_validation_test.go, application-operator/controllers/webhooks/multiclusterapplicationconfiguration_webhook.go, application-operator/controllers/webhooks/multiclusterapplicationconfiguration_webhook_test.go, application-operator/controllers/webhooks/multiclustercomponent_webhook.go, application-operator/controllers/webhooks/multiclustercomponent_webhook_test.go, application-operator/controllers/webhooks/multiclusterconfigmap_webhook.go, application-operator/controllers/webhooks/multiclusterconfigmap_webhook_test.go, application-operator/controllers/webhooks/multiclustersecret_webhook.go, application-operator/controllers/webhooks/multiclustersecret_webhook_test.go, application-operator/test/integ/multi_cluster_test.go
Reverts verrazzano/verrazzano#1547
=> Revert "VZ-2522 Disallow Mcxxxx resources that are not in a VerrazzanoProject"

Jenkinsfile, tools/scripts/bom_utils.sh, tools/scripts/generate_image_list.sh, tools/scripts/generate_tarball.sh
Generate release image list from BOM instead of running oci-dns tests
VZ-3462
=> VZ-3462 BOM to image list

platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/internal/istio/istioctl.go, platform-operator/internal/istio/istioctl_test.go
…d registry.go accordingly
Fixes VZ-9999
=> VZ-3478 Add istio package with istioctl implementation

ci/upgrade/Jenkinsfile
Increase delay before starting upgrade to allow old operator to terminate.
=> increase delay before starting upgrade

ci/ticket-commits/JenkinsfilePullRequests
Minor enhancement to the automation that logs pull requests in JIRA tickets. We now include the target branch in the JIRA comment. This makes it easier to track the branches that PRs are targeting.
Enhances VZ-3301
=> VZ-3301: Add change target to JIRA comment for pull requests

ci/JenkinsfileFlakyTests, ci/JenkinsfileTestTrigger
The flaky test run jenkinsfile still had the old post section stub, removed that. The new section handles alerting now.
We don't have a good way to test this job outside of master, but it is not blocking other folks so fixing forward
=> remove old post section

platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/install.go, platform-operator/controllers/verrazzano/upgrade.go
Create pre/post hooks for install; no impls at present.
=> Create Component pre/post install and upgrade hooks

ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger
Reverts verrazzano/verrazzano#1598
=> Revert "Fix promotion of master level broken during disconnect, add debug aro…"

release/scripts/check_versions.sh, release/scripts/compare_crds.sh, release/scripts/prerelease_validation.sh
Pre-release validation scripts. This is the back port PR for the 1.0 release branch.
Implements VZ-3497
=> VZ-3497: Pre-release validation scripts (release 1.0 branch)

ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger
This combines the reverted fixes for the promotion and notifications and adds the removal of the bad cd
=> Fix the promotion issue and notification issue

platform-operator/scripts/install/3-install-verrazzano.sh, platform-operator/thirdparty/charts/istio/gateways/istio-ingress/templates/service.yaml
Backport of OLCNE fixes to release-1.0,
=> VZ-3584 backport OLCNE fixes to release 1.0 

tools/scripts/generate_image_list.sh, tools/scripts/list_package_versions.sh
For each image in BOM (platform-operator/verrazzano-bom.json) list the version verrazano is using, and newer versions available.
Fixes VZ-3574
=> list versions of packages

platform-operator/verrazzano-bom.json
Uptake changes to Console UI to prevent errors when MC apps with simplified placement are deployed
Partially fixes VZ-3520
=> Uptake changes to Console UI to prevent errors when MC apps with simplified placement are deployed

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go
Attempt to prevent concurrent upgrade operations from occurring while the old operator is terminating
- webhook to verify only a single instance is running
- update webhook unit tests
=> VZ-3573.  Back from the dead.

ci/upgrade/Jenkinsfile, tests/e2e/config/scripts/install-verrazzano-kind-upgrade.yaml, tests/e2e/config/scripts/process_kind_install_yaml.sh, tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/keycloak/keycloak_test.go
Add persistence to upgrade tests
- remove workaround for disabling MySQL persistence in dev profile for ATs
=> Add persistence to upgrade tests

tools/scripts/list_go_mod_versions.sh
generate list of go module version and available versions as csv format
Fixes VZ-3575
=> list go module versions as csv format

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml, platform-operator/verrazzano-bom.json
=> minor tweaks to proxy

release/builds/Jenkinsfile, release/scripts/create_branch.sh, release/scripts/prerelease_validation.sh
A follow up to initial PR to correct some issues and enable easier testing:
- Removed "Source Branch" input since the pipeline executes in the given branche's build
- Correct some references to the git commit
- Added some testing capabilities to some of the scripts, allowing for mock releases and skipping some checks
- fixed issues with the "wait for new build to appear" logic
Fixes VZ-3509
=> JIRA: VZ-3509 Updates to release pipeline to enable easier testing and correct issues

platform-operator/verrazzano-bom.json
Uptake Console changes to handle display of MC apps with simplified placement (VZ-3520)
Fixes VZ-3520
=> Uptake Console changes to handle display of MC apps with simplified placement

release/builds/JenkinsfilePostPRT, release/scripts/create_github_release.sh, release/scripts/get_release_artifacts.sh, release/scripts/scan_release_binaries.sh
Includes a Jenkins script to call the scripts added for post PRT steps. The scripts added earlier were updated, as appropriate.
Fixes VZ-3516
=> VZ-3516: Create a Jenkins script for post PRT steps

ci/scripts/prepare_jenkins_at_environment.sh, ci/upgrade/Jenkinsfile
Add uninstall/verify stage to upgrade tests
=> Add uninstall/verify stage to upgrade tests

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
Fix an elastic search URL missed by the initial check-in of new proxy code.
=> fix elastic search url

release/builds/JenkinsfilePostPRT, release/scripts/scan_release_binaries.sh
Use environment variable for virus definition location.
=> Use environment variable for virus definition location

release/builds/JenkinsfilePostPRT, release/scripts/scan_release_binaries.sh
Clean-up Jenkinsfile used for release process automation.
=> Clean-up Jenkinsfile used for release process automation

platform-operator/verrazzano-bom.json
Upgrade Prometheus to v2.21.0 and Grafana to v7.2.1
=> Upgrade Prometheus to v2.21.0 and Grafana to v7.2.1

examples/bobs-books/bobs-books-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, platform-operator/verrazzano-bom.json, tests/testdata/ingress/console/components.yaml
Uptake mysql:8.0.26 image
Fixes VZ-3581
=> update to mysql:8.0.26

platform-operator/verrazzano-bom.json
Uptake console version that displays response status, if available, in error message
=> Uptake console version that displays response status, if available, in error message

ci/JenkinsfilePeriodicTests, ci/dynamic-updates/Jenkinsfile, tests/e2e/config/scripts/wait-for-component-ready.sh, tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go
Dynamic configuration test pipeline
- organize AT stages into reusable functions
- add disable logic for install, enable logic for update
- Use maps of closures for test reuse
- Add new suite to periodic runs
The tests essentially do the following:
- Install VZ without WKO/COH operators enabled
- Run validation tests (including checks to validate those pods aren't present) and examples tests, minus WLS/COH examples
- Update VZ to enable those operators
- Re-run validation tests, including WLS/COH examples
- This is the first pass, as we add more capabilities we'll need to add to the pipeline.
Fixes VZ-3610
=> VZ-3610.  Dynamic configuration test pipeline

ci/upgrade/Jenkinsfile
Add cluster dump to post-processing block after AT runs
=> Add cluster dump to post-processing block after AT runs

platform-operator/verrazzano-bom.json
update console image containing fix for firefox fetch. see https://github.com/verrazzano/console/pull/123 for the fix that was done
Fixes VZ-9999
=> update console image containing fix for firefox fetch

platform-operator/verrazzano-bom.json
Update image - 1.0.1_verrazzano_configmap-reload:0.3
Fixes VZ-3713
=> VZ-3713 update configmap-reload

platform-operator/verrazzano-bom.json
OCIR cleared fluentd Kubernetes runtime image
Fixes VZ-3718
=> VZ-3718 update to OCIR scan cleared fluentd image

platform-operator/verrazzano-bom.json
Update to an OCIR scan cleared image.
Fixes VZ-3727
=> VZ-3727 update to OCIR scan cleared oam kubernetes runtime image

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
This is the master PR that cherry picks the release-1.0 branch commit to add support for processing scan results in Jenkins.
**NOTE**: I added a cron trigger so the branch pipelines will run once a day. I tested this and it seems to work as advertised. I'll need to backport the trigger to the release-1.0 branch too.
Implements VZ-3938
=> VZ-3938: Jenkins support for processing scan results (master)

ci/scan-results/Jenkinsfile
Add a cron trigger to the scan results pipeline (backport to release-1.0 branch).
Implements VZ-3938
=> Add cron trigger

Jenkinsfile, release/builds/Jenkinsfile
Release automation needs to ensure everything is clean. This adds a WAIT_FOR_TRIGGERED parameter to the main pipeline, it will default to "false" so jobs there continue to be async, but the release pipeline job that runs will provide a value of "true" for the parameter so it will wait for the triggered tests to complete cleanly.
=> Tvlatas/vz 3889 Release automation needs to ensure everything is clean

platform-operator/verrazzano-bom.json
Update Istio Pilot image to 1.7.3-2 built from OLCNE
Fixes VZ-3728
=> Update Istio Pilot image to 1.7.3-2

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml, tests/e2e/pkg/web.go, tests/e2e/verify-infra/vmi/vmi_test.go, tests/e2e/verify-install/kiali/kiali_suite_test.go, tests/e2e/verify-install/kiali/kiali_test.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go
Initial acceptance test for Kiali.  This also handles the upgrade case, where Kiali is not installed for 1.0.  The PR includes 2 minor Network Policies changes because the kiali label name changed.
=> VZ-3340 - Kiali Acceptance test

application-operator/apis/weblogic/v8/domain_status.go, application-operator/apis/weblogic/v8/istio.go, platform-operator/helm_config/overrides/weblogic-values.yaml, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-cm.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update to WKO v3.3.3 with support for Istio 1.10+
- Update helm chart
- Update BOM entry
- Add chart override to set `istioLocalhostBindingsEnabled: false` for Istio 1.10+ support on by default
Fixes VZ-3946
=> VZ-3946.  Update WKO to v3.3.3

Jenkinsfile, ci/upgrade/Jenkinsfile
Right now, I am trying to test the experimental image
Fixes VZ-3619
=> VZ-3619 upgrade tests validate istio upgrade

platform-operator/verrazzano-bom.json
Pickup new VO and VMO images that have been upgraded to k8s v0.19.2 and controller-runtime v0.6.2
VZ tests:  https://build.verrazzano.io/job/verrazzano/job/jmaron%252FVZ-3948-new-vmo-and-vo/
triggered tests: https://build.verrazzano.io/job/verrazzano-push-triggered-acceptance-tests/job/jmaron%252FVZ-3948-new-vmo-and-vo/
Fixes VZ-3948
=> pickup new vmo and vo

platform-operator/verrazzano-bom.json
Kiali Link added to Console.
Fixes VZ-3274
=> VZ 3274: Kiali link on Console

platform-operator/verrazzano-bom.json
Update the MySQL image.
Fixes VZ-3739
=> VZ 3739: Update MySQL

application-operator/apis/weblogic/v8/domain_status.go, application-operator/apis/weblogic/v8/istio.go, platform-operator/helm_config/overrides/weblogic-values.yaml, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-cm.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Backport the WKO 3.3.3 update to the 1.0 line.
Fixes VZ-3732
=> VZ-3732. Backport WKO 3.3.3 for 1.0.3 release

ci/JenkinsfileFlakyTests
Add the upgrade suite to the flaky runs.
=> No JIRA.  Add upgrade test suite to flaky runs

application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, application-operator/controllers/wlsworkload/weblogicworkload_controller.go
=> ignore restartVersion when restart-version is empty

platform-operator/verrazzano-bom.json
=> VZ 3739: Uptake new MySQL image

platform-operator/verrazzano-bom.json
=> VZ 3739 - 1.0 Port

platform-operator/verrazzano-bom.json
Update the tags of two rancher images to pick up the latest builds.
=> Update rancher image tags for release-1.0

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#1906
=> Revert "VZ 3739: Uptake new MySQL image"

ci/scripts/run_console_tests.sh
Make a failure in console tests fail the suite - this is not happening in the Kind acceptance tests
=> Make a failure in console tests fail the suite

tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/kiali/kiali_test.go
Kiali tests in kiali_test.go and kubernetes_test.go would not run due to bug in version checking.
=> Kiali test bug

ci/scripts/push_to_ocir.sh
Found in release 1.0.3 work, remove vars not needed yet
=> Remove env settings not required yet

application-operator/controllers/appconfig/appconfig_controller.go
less misleading logs in appconfig controller
=> less misleading logs in appconfig controller

platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/internal/helm/helmcli.go
Clean up some of the extraneous/verbose logging in the platform operator.
=> No JIRA.  Clean up some of the Info logs in the platform operator.

ci/kind/Jenkinsfile, examples/sock-shop/README.md, examples/sock-shop/spring/sock-shop-app.yaml, examples/sock-shop/spring/sock-shop-comp.yaml
Added the Spring Sockshop example 
Fixes VZ-3672
=> Add Spring Sockshop example

CONTRIBUTING.md, ci/scripts/check_if_clean_after_generate.sh, tools/cli/README.md, tools/url_linter/ignore_urls.txt
=> Cleanup dead urls

examples/bobs-books/bobs-books-comp.yaml, examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/springboot-app/springboot-comp.yaml, examples/todo-list/todo-list-components.yaml
Labels the application and version for each workload for observation in Kiali.
Fixes VZ-4007
=> Label application and version for Kiali observation

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.0.3 to 1.0.4
=> Updating development version from 1.0.3 to 1.0.4

platform-operator/verrazzano-bom.json
Update keycloak build-from-source image
Fixes VZ-3840
=> keycloak update

examples/bobs-books/bobs-books-comp.yaml, examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/springboot-app/springboot-comp.yaml, examples/todo-list/todo-list-components.yaml
Reverts verrazzano/verrazzano#1923
=> Revert "Label application and version for Kiali observation"

release/builds/JenkinsfilePostPRT
Fix the stage 2 release pipeline to login to GitHub before running the script to create the github release.
=> Release automation pipeline fix

platform-operator/apis/verrazzano/v1alpha1/validate_test.go, platform-operator/controllers/clusters/sync_prometheus.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/verrazzano-bom.json, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go, tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/common.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/metrics.go
Reverts verrazzano/verrazzano#1919
=> Revert "VZ-3747 Part 2 - Uptake dashboard changes to add cluster drop down, remove old managed_cluster label, update tests"

application-operator/constants/constants.go, application-operator/controllers/appconfig/appconfig_controller.go, application-operator/controllers/appconfig/appconfig_controller_test.go, application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/cohworkload/coherenceworkload_controller_test.go, application-operator/controllers/containerizedworkload/containerizedworkload_controller.go, application-operator/controllers/containerizedworkload/containerizedworkload_controller_test.go, application-operator/controllers/helidonworkload/helidonworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, application-operator/controllers/wlsworkload/weblogicworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, application-operator/main.go
For ContainerizedWorkloads to restart on annotation "verrazzano.io/restart-version".
Fixes VZ-4016
=> VZ 4016 restart support for ContainerizedWorkloads

examples/bobs-books/bobs-books-comp.yaml, examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/springboot-app/springboot-comp.yaml, examples/todo-list/todo-list-components.yaml, tests/e2e/examples/bobsbooks/bobs_books_test.go
New re-merge of labeling application and version on pods for Kiali. Now, this PR includes test changes that resulted from the new labeling. Prometheus Istio metrics have changed and now reflect the label application name rather than the pod name.
Fixes VZ-4007
=> Draft: Labeling application and version on examples

ci/upgrade/Jenkinsfile, platform-operator/Dockerfile, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/verrazzano-bom.json
=> VZ 3893: Istio update to 1.10.4

platform-operator/verrazzano-bom.json
Per the Release Process instructions, updating the image tags for console and monitoring operator images to pick up the next patch version.
Looks like console was missed during post release of 1.0.2.
=> Update image tags for next release-1.0 patch release

release/builds/JenkinsfilePostPRT
Fix on release-1.0 branch. This makes release-1.0 consistent with master.
=> Fix github access token in release stage 2 pipeline

platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Upgrade weblogic operator to 3.3.4
Fixes VZ-9999
=> Upgrade weblogic operator to 3.3.4

application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, image-patch-operator/README.md, platform-operator/controllers/verrazzano/controller.go, tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go
I'll submit another PR to port these changes to the release-1.0 branch. There are another 100-200 instances of "verrazzano" that should be "Verrazzano" in code comments. I'll submit a separate PR to fix those.
=> Fix several places where names are not capitalized correctly

application-operator/controllers/cohworkload/coherenceworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, platform-operator/controllers/verrazzano/controller.go, tests/e2e/examples/bobsbooks/bobs_books_test.go
Cherry pick master commit to fix capitalization of names on the release-1.0 branch.
=> Fix several places where names are not capitalized correctly (#1963)

tests/e2e/examples/todo/todo_list_test.go
Fix up the names/descriptions for the new WLS logging tests in the ToDo test suite.
=> No JIRA.  Fix up ToDo test spec descriptions for enhanced wls-logging tests

ci/multicluster/Jenkinsfile, platform-operator/apis/verrazzano/v1alpha1/validate_test.go, platform-operator/controllers/clusters/sync_prometheus.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/verrazzano-bom.json, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go, tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/common.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/metrics.go
Reinstate reverted verrazzano_cluster metrics label and dashboard changes with fixes
Fixes VZ-3747
=> VZ-3747: Reinstate reverted verrazzano_cluster metrics label and dashboard changes with fixes

platform-operator/verrazzano-bom.json
Uptake console branch version that removes unused clientnode dependency
Fixes VZ-9999
=> Uptake console branch version that removes unused clientnode dependency

platform-operator/verrazzano-bom.json
Update keycloak:10.0.2 image
Fixes VZ-3724
=> keycloak BFS update

tests/e2e/pkg/web.go, tests/e2e/verify-install/keycloak/keycloak_test.go
Added AT to validate Keycloak RedirectURIs and WebOrigins are being set correctly
=> Add KeyCloak Tests that verify the correct redirectURIs and WebOrigins

application-operator/controllers/metricstrait/metricstrait_controller.go
Metrics trait controller should only update Prometheus configmap, not create it. Only VMO should create it.
Fixes VZ-4080
=> VZ-4080 - Metrics trait controller should only update Prometheus configmap, not create it. Only VMO should create it.

tests/e2e/verify-install/keycloak/keycloak_test.go
=> Remove commented code

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
Additional fix for VZ-3985.
During a WLS domain shutdown request via the `verrazzano.io/lifecycle-action`, we attempt to save the current value for existing server restart policy on the domain object in the annotation `verrazzano-io/last-server-start-policy` on the Domain object.   This was getting lost as we were modifying the unstructured object, then calling `CreateOrUpdate` which will replace the modified object with the version from the cluster.
To fix, the code to manipulate the restart annotations/fields was moved to the `CreateOrUpdate` mutator.
=> VZ-3985.  Fix setting the last-restart annotation during WLS domain shutdown

THIRD_PARTY_LICENSES.txt, go.mod, go.sum, pkg/test/framework/metrics/metrics.go, pkg/test/framework/metrics/prometheus.go, pkg/test/framework/metrics/prometheus_test.go
Initial version of metrics wrapper for tests
=> Initial version of metrics wrapper for tests

examples/sock-shop/helidon/sock-shop-app.yaml, examples/sock-shop/micronaut/sock-shop-app.yaml, examples/sock-shop/spring/sock-shop-app.yaml
=> VZ-4091 Fix the wrong destination port in Sock Shop app config

pkg/test/framework/metrics/prometheus.go, pkg/test/framework/metrics/prometheus_test.go
Metrics cleanup, generate metrics name, logging
=> Metrics cleanup, generate metrics name, logging

platform-operator/verrazzano-bom.json
Pick up of new Kibana-oss image 
Full suite of tests:  https://build.verrazzano.io/job/verrazzano/job/jmaron%252FVZ-4120/5/
Also tested functionally by installing on a kind cluster and leveraging Kibana UI
Fixes VZ-4120
=> JIRA:VZ-4120 new kibana-oss image added to BOM

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfilePeriodicTests, ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/ticket-commits/JenkinsfileCommits, ci/ticket-commits/JenkinsfilePullRequests, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
Backport slack notification changes to release-1.0
=> Tvlatas/vz 3943 1.0

tests/e2e/verify-install/kiali/kiali_test.go
=> Kiali test fix

platform-operator/verrazzano-bom.json
This change updates the components images in platform-operator/verrazzano-bom.json
Contributes to VZ-4050
=> Update component images

Jenkinsfile, ci/JenkinsfileTestTrigger, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/scripts/dashboard/emit_metrics.sh, ci/scripts/metric_del.sh, ci/scripts/metric_emit.sh, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
=> fix prometheus names

pkg/test/framework/ginkgo_wrapper.go, pkg/test/framework/ginkgo_wrapper_util.go, pkg/test/framework/ginkgo_wrapper_util_test.go
First pass at emitting metrics from ginkgo wrapper
=> Prepare to emit metrics from ginkgo wrapper

pkg/test/framework/ginkgo_wrapper.go, pkg/test/framework/metrics/prometheus.go
=> Make metrics pushing async

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfileFlakyTests, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/looping-test/Jenkinsfile, ci/looping-test/JenkinsfileCreateCluster, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
=> switch to main runner image

platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go
Fixing cert manager annotations on rancher ingress. 
Fixes VZ 4161.
=> VZ 4161: fix rancher ingress

ci/looping-test/JenkinsfileCreateCluster
Fix typo in the cluster creation Jenkinsfile
Fixes VZ-3671
=> VZ-3671 fix missing parentheses

ci/dynamic-updates/Jenkinsfile
FIx dynamic update Jenkinsfile. change focus.file to focus-file
=> fix dynamic update Jenkinsfile

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml, tests/e2e/verify-install/web/web_test.go
Reverts verrazzano/verrazzano#2028
=> Revert "Validate request body for console and api"

application-operator/Dockerfile, image-patch-operator/Dockerfile, platform-operator/Dockerfile, platform-operator/verrazzano-bom.json, tools/analysis/Dockerfile
VZ-4154 Remove an unneeded yum repo from Dockerfiles.
Partially fixes VZ-4154
=> VZ-4154 Remove an unneeded yum repo from Dockerfiles

platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/apis/verrazzano/v1alpha1/validate_test.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go
Requests with invalid profiles is rejected before install begins
Fixes VZ-4090
=> VZ-4090 reject invalid profile

Makefile, make/quality.mk
This PR adds some documentation to our makefile(s) to make them a bit easier to use :) 
No JIRA
With this fix, when you run `make` the default target will print out help, as shown below. 
```
$ make
Usage:
make <target>
help                       Display this help.
clean                      remove coverage and test results
Build
docker-push                build and push all images
docker-push-ipo            build and push just the Image Patch Operator
docker-push-wit            build and push the WebLogic Image Tool image for the Image Patch Service
Compliance
copyright-test             run the tests for the copyright checker
copyright-check-year       check copyright notices have correct current year
copyright-check            check …
```
=> add some documentation to the makefile(s)

ci/JenkinsfileTestTrigger
This pull request comments out the 1.22 Kind AT for the time being until the work to support 1.22 is startup again.
=> Comment out 1.22 Kind AT in triggered test ATs

platform-operator/verrazzano-bom.json
Update images in the bom file for new build from source images.
Fixes VZ-4154
=> Draft: VZ-4154 Update BFS images to newly built images

Jenkinsfile
Backport Trivy scan report generation for 1.0 release branch.
Fixes VZ-3558
- [] Added or updated unit tests for any new functions I added
=> VZ-3558 Trivy scan tool onboarding for release-1.0 branch

Jenkinsfile, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, ci/scripts/push_to_ocir.sh, ci/scripts/update_periodic_on_success.sh, release/scripts/get_ocir_scan_results.sh, tests/e2e/config/scripts/create_ocir_repositories.sh, tests/e2e/registry/registry_test.go
Backport VZ-4041, VZ-4045, VZ-4030 to release-1.0
=> Tvlatas/vz 4041 1.0

ci/multicluster/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, ci/scripts/prepare_private_registry_jenkins_at_environment.sh, ci/upgrade/Jenkinsfile, tools/analysis/internal/util/cluster/verrazzano.go
Signed-off-by: Prasad Shirodkar <prasad.shirodkar@oracle.com>
Fixed typos in the word "Verrazzano"
=> Fixed typos in the word "Verrazzano"

platform-operator/verrazzano-bom.json
=> update keycloak image

ci/JenkinsfilePeriodicTests
Fix a syntax error with the cron schedule for the release branch
=> Fix daliy cron syntax for release branches

platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/controllers/clusters/vmc_controller.go, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml, platform-operator/verrazzano-bom.json
VZ-3692: Fixed cluster status typo
- Updated Verrazzano bom file with new console image tag. 
Fixes VZ-3692
=> VZ-3692: Fixed cluster status typo

platform-operator/verrazzano-bom.json
Uptake Rancher fixes from v2.5.9 branch into Verrazzano
Partially Fixes VZ-4154
=> VZ-4154 Uptake Rancher fixes from v2.5.9 branch

platform-operator/verrazzano-bom.json
consumes updated image needed for 1.1 release
=> uptake new keycloak image with updated attributions

ci/JenkinsfilePeriodicTests, release/builds/JenkinsfilePreRelease
VZ-4044 backport to release-1.0 
=> VZ-4044 backport to release-1.0

platform-operator/verrazzano-bom.json
Uptake new version of keycloak with updated log4j dependency
=> uptake log4j dependency

platform-operator/verrazzano-bom.json
Uptake new keycloak image with updated log4j dependency.
=> update log4j dependency

examples/springboot-app/springboot-comp.yaml, platform-operator/verrazzano-bom.json
This PR picks up an updated sample application with dependency updates. 
=> uptake updated sample

examples/springboot-app/springboot-comp.yaml, platform-operator/verrazzano-bom.json
This PR picks up an updated sample which has some dependencies updated.
=> consume updated sample image

platform-operator/verrazzano-bom.json
This PR updates cert-manager images.
=> Update cert-manager images

platform-operator/verrazzano-bom.json
=> pick up new keycloak image

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
=> Fix PW masking for err

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Port forward the cleartext pq fix when exceptions are being thrown
Fixes VZ-9999
=> vz-4307 Port forward the release1.1 cleartext password fix

platform-operator/verrazzano-bom.json
=> Uptake elasticsearch log4j 2.16 fix release 1.1

platform-operator/verrazzano-bom.json
This change updates Keycloak and verrazzano-operator images
=> Update Keycloak and verrazzano-operator images

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.1.0 to 1.1.1
=> Updating development version from 1.1.0 to 1.1.1

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.1.0 to 1.2.0
=> Updating development version from 1.1.0 to 1.2.0

platform-operator/verrazzano-bom.json
Updates the Elasticsearch 7.6.1 images with patched log4j images
Fixes VZ-9999
=> Update test Elasticsearch 7.6.1 image

application-operator/controllers/controller_utils.go, application-operator/controllers/ingresstrait/ingresstrait_controller.go
The controller-runtime reconciler does an exponential backoff without a limit.  Change the backoff params to start of 5 seconds and limit the backoff to 60.  Also, add delay in case where re-queue is needed.
=> VZ-4332 Set max backoff for reconcile for IngressTrait

pkg/test/framework/metrics/search_writer.go
=> Basic auth

Jenkinsfile, ci/JenkinsfileTestTrigger
This addresses VZ-3100, basically guard against git commits from other repositories that end up in the git commit list (like when the jenkins shared pipeline library is updated(
=> VZ-3100 git bad object intermittent issue

tests/e2e/security/netpol/network_policy_test.go
Backport test fix (commit 2bed345ede21726de178a333cb2781970ebbcd77) to rel 1.1
Fixes VZ-4316.
=> VZ-4316.  Backport test fix to 1.1

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.0.4 to 1.0.5
=> Updating development version from 1.0.4 to 1.0.5

platform-operator/verrazzano-bom.json
Update a couple of image tags to the next patch release version on the release-1.0 branch.
=> Update image tags to next patch release

Jenkinsfile
Backport VZ-3100 to release-1.0
=> Tvlatas/vz 3100 (#2182)

tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/springboot/springboot_test.go
Fixes VZ-4373: Timeout in examples tests too short
=> VZ-4373: Timeout in examples tests too short

tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/socks/sockshop.go
Backport of the Sock Shop test fix.
Fixes VZ-4370
=> VZ-4370 Update Sock Shop test Eventually and Expect Combination Backport (#2203)

tests/e2e/metrics/deploymetrics/deploymetrics_test.go, tests/e2e/pkg/kubernetes.go
Ensure namespace is deleted in deploymetrics_test
=> Backport VZ 4355 to 1.1

pkg/bom/bom.go, pkg/bom/bom_test.go, pkg/bom/testdata/test_bom_image_overrides.json, platform-operator/controllers/verrazzano/component/istio/istio_component.go
Developer use case to override individual image repositories and registries.
=> Image registry overrides

tests/e2e/pkg/web.go, tests/e2e/verify-install/web/web_test.go
Add retries for several http requests in web_test that were missing retries
Fixes VZ-4382
=> VZ-4382 Add retries for several http requests in web_test that were missing retries

Makefile
Remove the validation for the current year in the copyright notice.
=> Remove the validation for the current year in the copyright notice.

Makefile
Remove the validation for the current year in the copyright notice.
=> Remove the validation for the current year in the copyright notice

platform-operator/verrazzano-bom.json
update to the 1.2.0 images
Fixes VZ-9999
=> update to the 1.2.0 images

examples/bobs-books/bobs-books-comp.yaml
Replaced bobbys front end ocr image with the latest OCR image with rectifications  
Fixes VZ-3140
=> VZ-3140 : Replaced bobbys front end ocr image with the latest rectified image

tests/e2e/loggingtrait/coherenceworkload/coherence_loggingtrait_test.go
Add cluster dump for Coherence logging test failure.
=> Add cluster dump for Coherence logging test

tests/e2e/ingress/console/console_ingress_test.go, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go
PR to add cluster dump for weblogic logging test and console ingress test
=> Add cluster dump for weblogic logging test and console ingress test

platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_component.go, platform-operator/scripts/install/create_oci_config_secret.sh
Update copyright dates to 2022 for some files modified this year
=> Update copyright dates to 2022 for some files modified this year

Jenkinsfile, JenkinsfileCopyrightTest, Makefile, application-operator/hack/add-crd-header.sh, application-operator/hack/add-yml-header.sh, image-patch-operator/hack/add-crd-header.sh, image-patch-operator/hack/add-yml-header.sh, platform-operator/hack/add-crd-header.sh, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, tools/fix-copyright/copyright.go
Fixes
Fixes VZ-4390 for copyright date checks that occurred after 1/1/2022.
=> VZ-4390 Fixes for copyright date checks

Makefile, ci/scripts/check_if_clean_after_generate.sh
Incorporate some review feedback from the initial set of changes made for VZ-4390.
Fixes VZ-4390
=> VZ-4390 incorporate some review feedback on copyright checking changes

ci/scripts/get_branch_scan_results.sh, release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh, release/scripts/scan_bom_images.sh
Backport VZ-4250 and VZ-4251 to release-1.1
=> Tvlatas/vz-4250 and vz-4251 (#2156)

Makefile, ci/scripts/check_if_clean_after_generate.sh
Reverts verrazzano/verrazzano#2246
=> Revert "VZ-4390 incorporate some review feedback on copyright checking changes"

Jenkinsfile, JenkinsfileCopyrightTest, Makefile, application-operator/hack/add-crd-header.sh, application-operator/hack/add-yml-header.sh, image-patch-operator/hack/add-crd-header.sh, image-patch-operator/hack/add-yml-header.sh, platform-operator/hack/add-crd-header.sh, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, tools/fix-copyright/copyright.go
Reverts verrazzano/verrazzano#2245
=> Revert "VZ-4390 Fixes for copyright date checks"

Jenkinsfile, ci/JenkinsfileTestTrigger
backport console flag in ATs to 1.1
=> backport console test flag

Jenkinsfile, JenkinsfileCopyrightTest, Makefile, application-operator/hack/add-crd-header.sh, application-operator/hack/add-yml-header.sh, ci/scripts/check_if_clean_after_generate.sh, image-patch-operator/hack/add-crd-header.sh, image-patch-operator/hack/add-yml-header.sh, platform-operator/hack/add-crd-header.sh, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, tools/copyright/copyright.go, tools/fix-copyright/copyright.go
Back port copyright check changes to release-1.1 branch
Fixes VZ-4390
=> VZ-4390 Back port copyright check changes to release-1.1 branch

Jenkinsfile, JenkinsfileCopyrightTest, Makefile, application-operator/hack/add-crd-header.sh, application-operator/hack/add-yml-header.sh, ci/scripts/check_if_clean_after_generate.sh, image-patch-operator/hack/add-crd-header.sh, image-patch-operator/hack/add-yml-header.sh, platform-operator/hack/add-crd-header.sh, platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml, tools/copyright/copyright.go, tools/fix-copyright/copyright.go
Back port copyright check changes to release-1.0 branch
Fixes VZ-4390
=> VZ-4390 Back port copyright check changes to release-1.0 branch

release/builds/JenkinsfilePreRelease
Backport VZ-4348 to release-1.0
=> Tvlatas/vz 4348 1.0

release/builds/JenkinsfilePreRelease
Backport VZ-4348 to release-1.1
=> VZ-4348 (#2189)

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/k8sutil/testdata/objects/crd2.yaml, pkg/k8sutil/testdata/objects/not-yaml.txt, pkg/k8sutil/testdata/objects/service.yaml, pkg/k8sutil/testdata/templated_service.yaml, pkg/k8sutil/testdata/two_objects.yaml, platform-operator/controllers/verrazzano/component/appoper/app_operator.go, platform-operator/controllers/verrazzano/component/appoper/testdata/charts/verrazzano-application-operator/crds/invalid.yaml, platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go
Branch was around in 2021 but copyrights did not get updated.
=> Updating copyrights to 2022

tools/scripts/k8s-dump-cluster.sh
Backport cluster dump tweak to 1.0
=> Cluster dump tweak (#2184)

ci/upgrade/Jenkinsfile
=> VZ-4463 add post-upgrade cluster dump

Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
This updates the release-1.1 branch so we can control the tool images being used for that branch. It currently is using the same tools that master has now, but that will change up very soon. The images are controlled using new globals and labels which are setup in Jenkins.
=> Tvlatas/4454 1.1

application-operator/internal/app/resources/templates/standard-k8s-metrics-template.yaml, application-operator/internal/app/resources/workloads/hello-helidon-deployment.yaml, application-operator/internal/app/resources/workloads/hello-helidon-replicaset.yaml, application-operator/internal/app/resources/workloads/hello-helidon-statefulset.yaml
Cleanup workload yamls.  Remove  app.verrazzano.io/metrics-scrape: "true"
=> Update workload yamls

application-operator/controllers/namespace/fluentd_configmap.go, application-operator/controllers/namespace/fluentd_configmap_test.go, application-operator/controllers/namespace/namespace_controller.go, application-operator/controllers/namespace/namespace_controller_test.go, application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, pkg/constants/constants.go, platform-operator/constants/constants.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install_test.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go, tests/e2e/pkg/fluentd.go, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
Reverts verrazzano/verrazzano#2288. Push triggered tests are failing, not sure why yet, I'll revert and figure it out.
=> Revert "VZ-V4453: Integrate OCI Logging code"

tests/e2e/registry/registry_test.go
Fixes the package passed to the new test framework in registry_test
Contributes to VZ-4520
=> VZ-4520: Fix the package passed to the new test framework in registry_test

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
This change fixes a group name and removes some roles that are no longer required
=> Fix monitors group. Remove some unused roles

release/builds/Jenkinsfile
Fix typo in release/builds/Jenkinsfile
Fixes bug in release process
=> Fix typo in release/builds/Jenkinsfile

release/builds/Jenkinsfile
=> fix copyright in release/builds/Jenkinsfile

ci/JenkinsfilePeriodicTests
=> VZ-4574: Fix missing comma

ci/JenkinsfilePeriodicTests, release/builds/Jenkinsfile, release/builds/JenkinsfilePreRelease, release/builds/JenkinsfileReleaseExistingCandidate
VZ-4446 - Introduce a "release existing candidate" Jenkinsfile which allows releasing a pre-tested release candidate
=> VZ-4446 - Introduce a "release existing candidate" Jenkinsfile which allows releasing a pre-tested release candidate

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.1.1 to 1.1.2
=> Updating development version from 1.1.1 to 1.1.2

ci/private-registry/Jenkinsfile, ci/scripts/prepare_private_registry_jenkins_at_environment.sh, platform-operator/verrazzano-bom.json
Fixes the BOM for private registry uninstall, add an uninstall stage to the private registry pipeline.
Fixes VZ-4490.
=> VZ-4490.  Fix private registry uninstall, add uninstall stage to private registry pipeline

ci/private-registry/Jenkinsfile, ci/scripts/prepare_private_registry_jenkins_at_environment.sh, platform-operator/verrazzano-bom.json
Backport Rancher uninstall fix for private registry case, and update to private registry pipeline to account for uninstall case.
Fixes VZ-4490.
=> VZ-4490.  Backport to release 1.1

ci/private-registry/Jenkinsfile, ci/scripts/prepare_private_registry_jenkins_at_environment.sh, platform-operator/verrazzano-bom.json
Backport Rancher uninstall fix for private registry case, and update to private registry pipeline to account for uninstall case.
Fixes VZ-4490.
=> VZ-4490.  Backport to release 1.0

application-operator/controllers/wlsworkload/weblogic_logging.go, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
This pull request fixes two problems reported with Kibana and logs we send to Elasticsearch.
1. Fix shards failed error which prevented logs being shown
2. Fixed a conflicting format warning for the timestamp field
Fixes VZ-4506
=> VZ-4506: Fixes for Kibana issues

pkg/log/field.go, platform-operator/controllers/verrazzano/component/appoper/app_operator_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/app_restart.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/spi/component_context.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/install.go, platform-operator/internal/helm/helmcli.go, platform-operator/main.go
Start of VPO logging cleanup per best-practices.  This is an incremental effort which will have multiple PRs.
=> VZ-4619 VPOI logging cleanup

platform-operator/verrazzano-bom.json
Update kibana image in platform-operator/verrazzano-bom.json
Fixes VZ-4325
=> kibana image update

ci/JenkinsfilePeriodicTests, ci/oke-ocidns/Jenkinsfile, platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml, platform-operator/helm_config/overrides/external-dns-values.yaml, platform-operator/scripts/install/create_oci_config_secret.sh, platform-operator/thirdparty/charts/external-dns/templates/deployment.yaml, platform-operator/thirdparty/charts/external-dns/values.yaml, platform-operator/verrazzano-bom.json, tests/e2e/config/scripts/create-test-oci-config-secret.sh, tests/e2e/config/scripts/install-verrazzano-ocidns.yaml, tests/e2e/config/scripts/oci_dns_ops.sh, tests/e2e/config/scripts/process_oci_dns_install_yaml.sh, tests/e2e/config/scripts/terraform/cluster/create-cluster.sh, tests/e2e/config/scripts/wait-for-verrazzano-install.sh, tools/scripts/generate_operator_yaml.sh
=> aamitra/VZ-4654-backport fixes for epic VZ-3670 new

platform-operator/thirdparty/charts/external-dns/templates/clusterrole.yaml, platform-operator/verrazzano-bom.json
To be merged only after https://github.com/verrazzano/external-dns/pull/21 is merged and correct external DNS image is updated
=> VZ-4545-update external-dns to 10.2-merge after PLS approval

platform-operator/apis/verrazzano/v1alpha1/validate_test.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go
Fix copyright headers in last revert
=> Fix copyright headers in last revert

Jenkinsfile, ci/lre/Jenkinsfile, pkg/test/framework/metrics/ginkgo_metrics.go
- Added more keywords for ES logs. 
- Updated Jenkins file with a new ENV. 
Fixes VZ-4489
=> VZ-4489: Updated ES Log Data for Dashboard Enhancement. 

platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/apis/verrazzano/v1alpha1/validate_test.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/main.go
Re-introduce changes for VZ-4616, and add temp file cleanup hooks on container restart
Fixes VZ-4616.
=> VZ-4616.  Re-introduce changes, and add temp file cleanup hooks on container restart

ci/JenkinsfilePeriodicTests
This PR adds a stage to the periodic test pipeline that kicks off the OCI service integration test pipeline.
=> No JIRA: Add stage to periodic test pipeline for OCI service integration tests

pkg/test/framework/metrics/search_writer.go
=> VZ-4741 Replace http.Client with retryablehttp.Client 

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/verify-infra/vmi/vmi_test.go
Reverts verrazzano/verrazzano#2380
=> Revert "Scchen/vz 4507 logstash index"

tests/e2e/verify-infra/vmi/vmi_test.go
remove ES oss flavor test
Fixes VZ-4742
=> remove oss flavor test

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
remove logstash index
Fixes VZ-4507
=> remove logstash index

Jenkinsfile
Fix interpolation, add params. prefix to the new setting
=> VZ-4745 fix interpolation

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/verrazzano/verrazzano_test.go
Add an affinity configuration for the AuthProxy deployment.  The option to customize the affinity configuration via The Verrazzano custom resource will be handled in a separate task.
=> VZ-4747 - Add an affinity configuration for the AuthProxy deployment

platform-operator/helm_config/charts/verrazzano/crds/verrazzano.io_verrazzanomonitoringinstances_crd.yaml, platform-operator/verrazzano-bom.json
* prometheus:v2.31.1 
* add http2Enabled in vmi.prometheus
* update VMO with http2 option
Fixes VZ-4461
=> prometheus:v2.31.1 and add http2Enabled in vmi.prometheus

platform-operator/verrazzano-bom.json
Uptake new verrazzano-operator image with updated dependencies.
Fixes VZ-4727
=> VZ-4727: Uptake new verrazzano-operator image

pkg/controller/errors/errors.go, pkg/helm/helmcli.go, pkg/istio/istioctl.go, pkg/log/vzlog/vzlog.go, platform-operator/controllers/clusters/rancher.go, platform-operator/controllers/verrazzano/component/appoper/app_operator.go, platform-operator/controllers/verrazzano/component/appoper/app_operator_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/app_restart.go, platform-operator/controllers/verrazzano/component/istio/envoy_filter.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/kiali/kiali.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_letsencrypt.go, platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/component/spi/component_context.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/main.go
1. Major cleanup of error logging.  
2. Return formatted message that is logged, instead of the underlying message that doesn't have the full context.  
3. Make errors consistently start with Failed
4. Add progress messages to application restart
5. Minor tweek to vzlog package
=> VZ-4619 log errors for VPO

platform-operator/verrazzano-bom.json
Update the VMO image in the BOM.
Fixes VZ-4732.
=> VZ-4732.  Update VMO image.

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh
Backport VZ-4744 to release-1.1 for scanning updates
=> Tvlatas/vz 4744 1.1

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh
Backport VZ-4744 to release-1.0 for scanning updates
=> Tvlatas/vz 4744 1.0

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
remove unnecessary @timestamp
Fixes VZ-4507
=> remove fluentd.** @timestamp

Jenkinsfile, JenkinsfileCopyrightTest, ci/multiplatform/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/upgrade/Jenkinsfile
Backport VZ-4766 to release-1.0
=> Tvlatas/vz 4766 1.0

platform-operator/controllers/clusters/vmc_controller.go, platform-operator/controllers/verrazzano/component/appoper/app_operator.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/coherence/coherence.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/kiali/kiali.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/oam/oam.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/weblogic/weblogic_operator.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/internal/k8s/status/deployment_ready.go, platform-operator/internal/k8s/status/ingresses_present.go, platform-operator/internal/k8s/status/statefulset_ready.go
A few additional logs plus logging fixes to the component that are waiting for deployments.  Need to use the context component name (the calling component waiting on the dep), not the component itself.  
=> VZ-4614 misc logging for VPO

tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/metrics/deploymetrics/deploymetrics_test.go
Increase timeout waiting for resources and namespace to be deleted
=> Increase timeout waiting for resources and namespace to be deleted in deploymetrics test

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
cleanup logstash from fluentd config
Fixes VZ-4507
=> remove logstash

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
This PR fixes timestamp and loglevel logging for Kiali
=> Add parsing/filtering rules to Fluentd config for Kiali

pkg/test/framework/metrics/ginkgo_metrics.go
-Removed the Jenkins build info from the metric log field jenkins_job. 
Fixes VZ-4830
=> Remove the build info from the Dashboard Job filter. 

ci/JenkinsfilePeriodicTests
Backport periodic disable concurrent to 1.0
=> backport periodic non concurrent tweak to 1.0

ci/JenkinsfilePeriodicTests
Backport periodic disable concurrency to release-1.1
=> backport periodic non concurrent tweak to 1.1

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
Fix timestamp and level logging for Istio-proxy sidecar containers
Fixes VZ-4812
=> VZ-4812 - Fix timestamp and level logging for Istio-proxy sidecar containers

tests/e2e/framework/cleanup.go, tests/e2e/framework/exec_util.go, tests/e2e/framework/expect.go
=> VZ-4822 expect exec and cleanup

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
Add parsing/filtering rules to Fluentd configuration for CertManager
=> Add parsing/filtering rules to Fluentd configuration for CertManager

platform-operator/verrazzano-bom.json
Uptake the new VO image that has logging improvements
=> uptake new VO image

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
This PR adds Klog filter to fluentd Kiali filter and removees the Keep_time_key attribute
=> Add klog filter, remove keep_time_key true

platform-operator/verrazzano-bom.json
This PR updates the Keycloak 15.0.2 image in release-1.1
=> Update Keycloak image in release-1.1

Jenkinsfile
Fix alerting for the release branches, will need to backport this to them
=> fix release alerting

Jenkinsfile
=> backport alert updates to 1.1

Jenkinsfile
=> backport alert updates to 1.0

platform-operator/helm_config/charts/verrazzano/values.yaml
This changes the number of es-data nodes to 3 as per the VZ-4861 acceptance criteria.
=> VZ-4861: 3 es-data nodes

tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/istio/authz/authpolicy_test.go
Increase wait for sockshop namespace deletion
=> Increase wait for sockshop namespace deletion

tests/e2e/examples/bobsbooks/bobs_books_suite_test.go, tests/e2e/examples/helidonconfig/helidon_config_suite_test.go, tests/e2e/examples/springboot/springboot_suite_test.go, tests/e2e/examples/todo/todo_list_suite_test.go
Signed-off-by: Prasad Shirodkar <prasad.shirodkar@oracle.com>
Fixes VZ-9999
=> Restored missing ginkgo import

tests/e2e/examples/helidon/helidon_example.go, tests/e2e/framework/eventually.go, tests/e2e/framework/expect.go
=> VZ-4822 Evemntually and expect, and more

tests/e2e/framework/framework.go
Signed-off-by: stshapir <steven.shapiro@oracle.com>
Fixes VZ-9999
=> more skeleton

tests/e2e/examples/helidon/framework.go, tests/e2e/examples/helidon/helidon_example.go, tests/e2e/framework/eventually.go
=> VZ-4822 Evemntually changes and helidon test changes

platform-operator/verrazzano-bom.json
update Grafana image to Grafana:v7.5.11
=> grafana:v7.5.11 image update

tests/e2e/framework/framework.go
=> VZ-4822 couple of changes to framework

Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/lre/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile
Remove OCR logins from Jenkinsfiles as they are no longer needed
Partially Fixes VZ-3991
=> VZ-3991 part 1 - Remove OCR logins from Jenkinsfiles as they are no longer needed

platform-operator/Dockerfile
Updates helm to v3.8.0-1 and istioctl-1.10.4-6.
Fixes VZ-4724, VZ-4725, VZ-4726
=> VZ-4724, VZ-4725, VZ-4726.  Update helm and istioctl in the VPO

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/examples/todo/todo_list_test.go
Fix example e2e tests that continue to verify scenarios even when the given example application fails to deploy.
Fixes VZ-4846
=> VZ-4846 Fix example e2e tests that continue to verify scenarios even when the given example application fails to deploy

platform-operator/verrazzano-bom.json
Update BOM file to pick up new builds for Istio proxyv2, Istio pilot, and Kiali.
Fixes VZ-4837
=> VZ-4837: Update dependencies

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.2.0 to 1.3.0
=> Updating development version from 1.2.0 to 1.3.0

tests/e2e/config/scripts/install-metallb.sh
This PR updates the version of MetalLB that we use in tests.  This was done in an attempt to cut down on the 5xx's we see, but does not seem to have made an impact on that issue.  However, submitting anyway just for hygiene. 
=> Update Metal-LB version used in tests

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
Add parser for VPO, VO, and VMO.
Fix level parsing for Klog
=> VZ-4810 Fluentd parsing for verrazzano operators

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
This pull request adds filtering rules for parsing of istio-system component s.
=> VZ-4944: Update fluentd parsing for istio-system components

tests/e2e/logging/system/system_logging_test.go
=> VZ-4810 add VAO, VMO, VO logging tests

examples/bobs-books/bobs-books-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, platform-operator/verrazzano-bom.json
Update to mysql 8.0.28 which is from mysql/mysql-server:8.0.28
Fixes VZ-4953
=> VZ-4953 - Update to mysql 8.0.28 which is from mysql/mysql-server:8.0.28

tests/e2e/pkg/hello_helidon.go
=> VZ-4822 update templates dir

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/logging/system/system_logging_test.go
Creates a Fluentd log parsing section for Grafana component and implements a subsequent acceptance test.
Fixes VZ-4951
=> VZ-4951 Introduce Fluentd log parsing for Grafana

examples/bobs-books/bobs-books-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#2522
=> Revert "VZ-4953 - Update to mysql 8.0.28 which is from mysql/mysql-server:8.0.28"

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/verify-infra/restapi/vmi_urls_test.go
Backport Mark's FlakeAttempts changes to release 1.2
=> backport flake attempts to 1.2

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/logging/system/system_logging_test.go
This includes a new Kibana logging config and acceptance test to improve the logging fields in the Verrazzano components.
Fixes VZ-4956
=> VZ-4956 Fluentd logging config for OpenSearch Dashboards

tests/e2e/logging/system/system_logging_test.go
Fix index tests for VOA, VMO, VO
=> VZ-4810 fix index tests

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/logging/system/system_logging_test.go
This pull request adds parsing rules for node-exporter and related ATs.
=> VZ-4974: Add fluentd parsing rules for node-exporter

ci/lre/Jenkinsfile
Adding env variables to add the LRE runs to the dashboard
=> add env vars for lre runs to show in dashboard

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/ingress/console/console_ingress_test.go, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/e2e/metricsbinding/helidon-deployment/helidon_deployment_test.go
This PR tweaks some of the FlakeAttempts decorations on tests.
Fixes VZ-3643
=> Tweak flakeAttempts

platform-operator/verrazzano-bom.json
Uptake 1.3.0 tags of Verrazzano components
=> Uptake 1.3.0 tags of Verrazzano components

platform-operator/verrazzano-bom.json
This PR updates the Keycloak 15.0.2 image in Verrazzano, backports a change submitted to master.
=> Update Keycloak image release1.1

platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
Add delete of authproxy helm chart to Verrazzano uninstall.  This was missed when I added authproxy as a top level component.
=> Add delete of authproxy helm chart to Verrazzano uninstall

tests/testdata/ingress/console/components.yaml
Cherry pick bug fix + image update in the console ingress e2e test.
=> No JIRA: Fix Console ingress test (#2558) (release-1.0 branch)

tests/testdata/ingress/console/components.yaml
Cherry pick bug fix + image update in the console ingress e2e test.
=> No JIRA: Fix Console ingress test (#2558) (release-1.2 branch)

platform-operator/verrazzano-bom.json
Updating the Kibana build-from-source image due to recent image changes.
Fixes VZ-4901
=> VZ-5006 Update Kibana bfs image

platform-operator/controllers/verrazzano/component/authproxy/authproxy_component.go
Skip pre-install checks for AuthProxy if already installed.  This is a temporary fix to work around an installer issue of pre-install being called for AuthProxy after the install is complete.  The pre-install check is expecting that AuthProxy is not installed, and continuously fails waiting for it to not be installed.
Fixes VZ-5025
=> VZ-5025 Skip pre-install checks for AuthProxy if already installed

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go
While manually testing custom CA certs in release 1.2, I discovered that the CA cert I provided was not being used by the system. The problem is that Verrazzano was incorrectly creating a new CA cert and Issuer, and that was being used in place of the CA cert I specified. The fix is to only create the Certificate and Issuer resources when the secret containing the CA cert does not exist.
Fixes VZ-5019
=> VZ-5019: Fix bug, don't create Issuer and Certificate when user specifies CA cert

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go
Cherry pick commits from master to fix bugs when using a custom CA certificate (release-1.2 branch).
Fixes VZ-5019
=> VZ-5019: Fix bugs when using custom CA cert (release-1.2)

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go
Cherry pick commits from master to fix bugs when using a custom CA certificate (release-1.1 branch).
Fixes VZ-5019
=> VZ-5019: Fix bugs when using custom CA cert (release-1.1)

ci/multicluster/Jenkinsfile, ci/upgrade/Jenkinsfile
As discussed, updating the suites run during upgrade/mc.
=> Upgrade Tests

ci/JenkinsfilePeriodicTests
release branch notification check wasn't working, fix then backport
=> Fix release branch alert enablement check

platform-operator/verrazzano-bom.json
uptake console UI fix for partially registered managed cluster
Fixes VZ-5029
=> VZ-5029 - uptake console UI fix for partially registered managed cluster

tests/e2e/ingress/console/console_ingress_test.go
Removes duplicate call to create/update test yaml, added by mistake in my previous commit.
=> Remove duplicate create/update test yaml

platform-operator/verrazzano-bom.json
Includes updates to the Fluentd daemonset image from new build.
Fixes VZ-5009
=> VZ-5009 Update Fluentd daemonset image

Jenkinsfile
Removed the Stage Integration Tests from the pipeline
Fixes VZ-5055
=> VZ-5055 Remove Integrtion Tests from Pipeline

release/builds/JenkinsfilePreRelease
Fix typo in JenkinsfilePreRelease, enable override for pre-release failures
=> Fix typo in JenkinsfilePreRelease, enable override for pre-release failures and still create release candidate.

ci/scripts/run_console_tests.sh, platform-operator/verrazzano-bom.json
Uptake the latest Console image. Also includes a script fix provided by @desagar that fixes a bug when trying to run the main Verrazzano pipeline against a branch.
Fixes VZ-4910
=> VZ-4910: Uptake latest Console image

ci/chaos/Jenkinsfile
This is the initial commit of the upgrade resiliency Jenkins pipeline
=> Initial commit of upgrade resiliency Jenkinsfile

ci/JenkinsfilePeriodicTests
backport periodic notification update to 1.1
=> backport periodic notification update

ci/scripts/run_console_tests.sh
Fix console Jenkins test run to work for branch names and tags as well as commits
=> Fix console Jenkins test run to work for branch names and tags as well as commits

platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Signed-off-by: stshapir <steven.shapiro@oracle.com>
Fixes the problem that after Verrazzano install, a SEVERE log message appears in the WebLogic Operator log (generated by WKO). The new WKO version fixes this bug.
Fixes VZ-4458
=> VZ-4458 Upgrade WKO image version 3.3.7 -> 3.3.8

tests/e2e/verify-infra/vmi/vmi_test.go
Increase OpenSerach test wait timeout in VMI
Fixes VZ-9999
=> VZ-4503: increase OS wait timeout

platform-operator/verrazzano-bom.json
=> Refresh images release 1.2

platform-operator/verrazzano-bom.json
Add VMO with Kibana upgrade strategy.
=> VZ 5042: Uptake VMO

platform-operator/verrazzano-bom.json
Updates Elasticsearch v.7.10.2 image
=> Update Elasticsearch image

platform-operator/verrazzano-bom.json
Refreshes build from source images
=> Refresh build from source images

platform-operator/verrazzano-bom.json
Update kibana image
Fixes VZ-4899
=> Update kibana imgae

examples/springboot-app/springboot-comp.yaml
Updates example-springboot image
Contributes to VZ-4494
=> VZ-4494: Update springboot image

ci/chaos/Jenkinsfile
This fix removes the sleep and adds log checks
Fixes copyright
Removes some tests which dropped runtime for 1 hr 10 min to 40 min
=> Add log checks and retest helm.chart.corrupted

platform-operator/verrazzano-bom.json
Updates Elasticsearch v.7.6.1 image in release-1.0
Contributes to VZ-4494
=> VZ-4494: Update Elasticsearch v.7.6.1 image in release-1.0

examples/springboot-app/springboot-comp.yaml
Updates spring-boot image in release-1.0
Contributes to VZ-4494
=> VZ-4494: Update springboot image in release-1.0

examples/springboot-app/springboot-comp.yaml
Updates spring-boot image in release-1.1
Contributes to VZ-4494
=> VZ-4494: Update springboot image in release-1.1

platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Uptake Coherence Operator v3.2.5. Includes updating the helm chart.
=> No JIRA: Upgrade Coherence Operator to v3.2.5

ci/JenkinsfilePeriodicTests
Remove OCI Private DNS tests from periodic tests
=> Remove OCI Private DNS tests from periodic tests

platform-operator/helm_config/charts/verrazzano/templates/nodeexporter.yaml
Node Exporter SA was missing the imagePullSecrets.
=> Node Exporter SA

tests/e2e/logging/helidon/helidon_logging_suite_test.go, tests/testdata/logging/helidon/helidon-logging-app.yaml, tests/testdata/loggingtrait/coherenceworkload/coherence-logging-application.yaml, tests/testdata/loggingtrait/coherenceworkload/coherence-logging-components.yaml, tests/testdata/loggingtrait/helidonworkload/helidon-logging-application.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-application.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-components.yaml
=> update copyright year

platform-operator/verrazzano-bom.json
We have upgraded the version of configmap-reload from v0.3 to v0.7.1. This PR updates the BOM to use the new version.
Implements VZ-5138
=> VZ-5138: Uptake configmap-reload v0.7.1

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi_test.go
Reverts verrazzano/verrazzano#2657
=> Revert "VZ 5128: Uncomment code for isReady"

ci/examples/Jenkinsfile
a new pipeline for testing the example applications separate from gating tests
=> jenkinsfile to run examples only

release/builds/JenkinsfilePreRelease
Backport override switch to release-1.1
=> backport override for pre-release failures to 1.1

ci/lre/Jenkinsfile, ci/scripts/lre_setup_ssh_tunnel.sh
lre jenkinsfile creates a bastion session for every run. Updating it to reuse the bastion session if one exists.
=> reuse bastion sessions in lre clusters

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
=> VZ-4533: backport fix to 1.1 release branch

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Fix copyright string in keycloak.go.
=> No Jira: fix copyright string in keycloak.go

platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Reverts verrazzano/verrazzano#2678
=> Revert "VZ-4365: Rancher post-install step failed to reset admin password"

ci/scan-results/Jenkinsfile, ci/scripts/generate_html_report.py
Use the consolidated scan report CSV file to generate an HTML report which has clickable links to the individual vulnerabilities
Fixes VZ-4385
=> VZ-4385 Generate consolidated scan reports in HTML

.verrazzano-development-version, pkg/bom/testdata/verrazzano-bom.json
Update development version to v1.1.3
Update v1.1.3 console image.
=> Update development version to v1.1.3

ci/JenkinsfilePeriodicTests
Removing the upgrade resiliency tests due to stability issues.
Fixes VZ-5061
=> JIRA: VZ-5061 remove upgrade resiliency tests from periodic tests

platform-operator/internal/k8s/status/deployment_ready.go, platform-operator/internal/k8s/status/statefulset_ready.go
=> VZ-5027: fix a couple of typos from previous pull request

examples/multicluster/sock-shop/sock-shop-app.yaml, examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-app.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/sock-shop/spring/sock-shop-app.yaml, examples/sock-shop/spring/sock-shop-comp.yaml, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go, tests/e2e/pkg/kubernetes.go
Added coherence metric ports in example files for spring and micronaut variants of Sock Shop application. Also, enabled the corresponding tests to verify the coherence metrics.
Fixes VZ-3012
=> VZ-3012 Add coherence metric ports in Sock Shop example files

platform-operator/helm_config/charts/verrazzano/crds/verrazzano.io_verrazzanomonitoringinstances_crd.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/verrazzano-bom.json
- Uptake new VMO image that waits for OS to be ready before updating OSD
- introduce node-level storage options in the VMO
=> VZ 5251: OSD waits for OS to be ready

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.2.0 to 1.2.1
=> Updating development version from 1.2.0 to 1.2.1

platform-operator/controllers/verrazzano/component/istio/platform_restart.go, platform-operator/controllers/verrazzano/component/istio/platform_restart_test.go, platform-operator/controllers/verrazzano/upgrade.go
Add additional Unit tests for restart workloads.  Change the restart code to use go client for update as well.
Fixes VZ-9999
=> VZ-4503 istio test

pkg/log/vzlog/vzlog.go, pkg/log/vzlog/vzlog_test.go
Cherry pick logging progress fix to 1.2
=> VZ-5311 cherry pick to 1.2

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
This includes parsing vital fields from open search logs i.e es-data, es-ingest and es-master.
Fixes VZ-5265
=> Added timestamp, level and message parsing mechanism for opensearch logs

ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, platform-operator/internal/k8s/status/deployment_ready.go, platform-operator/verrazzano-bom.json
Corrected some issues introduced into upgrade resiliency pipeline and enabled periodic running of the upgrade resiliency test scenarios.  Picked up newer version of VMO with a stricter check for OS readiness.
Fixes VZ-5061
=> JIRA:VZ-5061 Pipeline fixes and setup for periodic run of upgrade resiliency tests

platform-operator/internal/config/config_test.go
=> fix copyright

platform-operator/helm_config/charts/verrazzano/templates/authorizationpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/vmi-es-networkpolicy.yaml
The VMO needs HTTP access to OSD/Kibana.
=> Allow access from VMO to OSD

tests/testdata/test-applications/coherence/hello-coherence/hello-coherence-comp.yaml, tests/testdata/test-applications/weblogic/hello-weblogic/hello-wls-comp.yaml
This change updates the docker images for the test samples
Contributes to VZ-5333
=> Update the image for test samples

platform-operator/verrazzano-bom.json
The trait display for the console has been updated to more accurately display the present traits. This fix introduces the new console image.
Fixes VZ-4290
=> VZ-4290 Update console image with new trait display

platform-operator/controllers/verrazzano/component/appoper/app_operator_component.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_component_test.go, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_component.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component_test.go, platform-operator/controllers/verrazzano/component/kiali/kiali_component.go, platform-operator/controllers/verrazzano/component/mysql/mysql_component.go, platform-operator/controllers/verrazzano/component/mysql/mysql_component_test.go, platform-operator/controllers/verrazzano/component/nginx/nginx_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx_component_test.go, platform-operator/controllers/verrazzano/component/oam/oam_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go, platform-operator/controllers/verrazzano/component/weblogic/weblogic_component.go
Update the component-level validators to reject any edits that have not been validated.  These will be relaxed over time as we verify what updates are possible.
Fixes VZ-5337.
=> VZ-5337.  Explicitly reject any post-install updates that have not been vetted.

platform-operator/verrazzano-bom.json
This fix introduces the console image update for the trait display.
Fixes VZ-4920
=> VZ-4290 console image trait display fix

platform-operator/verrazzano-bom.json
This updates the console image to include the new trait display updates.
Fixes VZ-4290
=> VZ-4290 Console image update for trait display fix

ci/upgrade/Jenkinsfile, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/config/scripts/install-vz-prod-kind.yaml, tests/e2e/verify-infra/vmi/vmi_test.go
Change upgrade test to use prod with 10g for each volume (there are 8 volumes)
=> VZ-5084 prod upgrade

platform-operator/verrazzano-bom.json
Pickup the latest VMO image to be installed
=> Update VMO image

tests/e2e/verify-install/web/nginx_errors_test.go
Fix incorrect function call that was introduced by previous merge.
Fixes VZ-9999
=> Fix merge error

platform-operator/verrazzano-bom.json
Update VMO image with changes having opensearch backup enhancements
=> VZ-5380: VMO change

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
=> VZ-5359 - WLS workload controller should handle nil Data field in a ConfigMap

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
=> VZ-5359 - Fix duplicate import of vzlogInit in weblogicworkload_controller

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi_test.go, platform-operator/verrazzano-bom.json
Creating a new secret for backup rather than using the existing secret
=> VZ-5396: Creating separate backup secret

ci/scripts/metric_emit.sh
=> No-Jira: Remove timestamp field from job metrics

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, platform-operator/helm_config/overrides/ingress-nginx-values.yaml
This updates the Nginx controller and the Fluentd config to handle JSON log messages and parse them correctly. 
Fixes VZ-5342
=> VZ-5342 Update Nginx controller to use JSON log messages

ci/uninstall/Jenkinsfile, platform-operator/scripts/install/config.sh
Fix bash syntax during uninstall
=> VZ-5459: Fix bash syntax

ci/chaos/Jenkinsfile, ci/scripts/chaos_test_ephemeral_storage.sh, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/install.go, platform-operator/controllers/verrazzano/install_test.go, platform-operator/controllers/verrazzano/upgrade_test.go
Reverts verrazzano/verrazzano#2831
=> Revert "Revert "VZ-5087 Repair Keycloak configuration when MySQL restarts and using ephemeral storage""

platform-operator/verrazzano-bom.json
=> VZ-5437 Pick up console changes to tolerate and handle error when fetching trait

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-monitoring-operator.yaml, platform-operator/verrazzano-bom.json
Pickup latest VMO with 1.22 changes
=> VZ-3844: Pickup latest VMO with 1.22 changes

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/vmi-es-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/verrazzano-bom.json
Allows VMO connection to OpenSearch
=> VZ 5554: Backport VMO Networking

platform-operator/Dockerfile, platform-operator/verrazzano-bom.json
Uptake Istio 1.11.4 and istioctl 1.11.4
=> VZ-5568 Uptake Istio 1.11.4

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go
In preparation for adding several more Prometheus install/upgrade components, refactor the existing Prometheus Operator component and create a top-level `prometheus` directory for all of the related components.
=> VZ-5537: Refactor Prometheus Operator install/upgrade component

ci/chaos/Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/lre/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile, tests/e2e/jobmetrics/jobmetrics_test.go
Send job metrics to the sauron instance in milliseconds.
=> VZ-5622: send job metrics in milliseconds

platform-operator/controllers/verrazzano/component/nginx/nginx_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx_component_test.go
Allow nginx service ports update
Fixes VZ-5593
=> VZ-5593: allow nginx service ports update

platform-operator/verrazzano-bom.json
New VMO image with PVC labelling change
=> VZ-5659: PVC labelling change in VMO

ci/multicluster/Jenkinsfile
Changing test environment to uppercase to be consistent with other kind pipelines.
=> MC TEST_ENV from kind to KIND

platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_test.go, platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/verrazzano/override.go, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesDevDefault.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesDevWithOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesManagedClusterDefault.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdDefault.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithAdminAndMonitorRoleOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithAdminRoleOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithExternaDNSEnabled.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithFluentdEmptyExtraVolumeMountsOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithFluentdOCILoggingOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithFluentdOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzOverridesProdWithMonitorRoleOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzValuesDevNoOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzValuesDevWithOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzValuesMgdClusterNoOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzValuesProdNoOverrides.yaml, platform-operator/controllers/verrazzano/component/verrazzano/testdata/vzValuesProdWithExternalDNS.yaml, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_values.go, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/helm_config/overrides/kube-state-metrics-values.yaml, platform-operator/internal/vzconfig/enabled.go, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh, platform-operator/verrazzano-bom.json
=> VZ-5630 Add install/uninstall of kube-state-metrics to Verrazzano

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go
Add validation of OCI-Logging to webhook.ValidateUpdate
Fixes VZ-5519
=> VZ-5519 validate update of oci-logging

ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/lre/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile, tests/e2e/jobmetrics/jobmetrics_suite_test.go, tests/e2e/jobmetrics/jobmetrics_test.go
Backport for job metrics changes
=> VZ-5622: jobmetrics release-1.2 backport

ci/multicluster/Jenkinsfile
=> VZ-5622: jobmetrics only on admin cluster

tests/e2e/verify-install/promstack/promstack_test.go
=> Move Fail() call to "It()" function in promstack_test.go - otherwise ginkgo complains about assertion in the body of a container node

platform-operator/verrazzano-bom.json
…sts - no main code changes
Fixes VZ-9999
=> Uptake new Console version which corresponds to updated prometheus tests - no main code changes

tests/e2e/config/scripts/install-verrazzano-kind-upgrade.yaml, tests/e2e/config/scripts/install-verrazzano-kind-with-persistence.yaml, tests/e2e/config/scripts/install-verrazzano-kind.yaml, tests/e2e/config/scripts/install-verrazzano-nipio.yaml
few files had invalid copyrights according to the linter.
=> copyright fixes

platform-operator/verrazzano-bom.json
New OpenSearch image includes ISM Plugin.
=> VZ 4629: ISM Plugin for OpenSearch

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml, tests/e2e/security/rbac/rbac_test.go
Update Authproxy RBAC to support k8s 1.22
Fixes VZ-5473
=> VZ-5473: Update authproxy rbac for k8s 1.22

ci/upgrade-paths/JenkinsfileTestTriggerReleaseCandidate
Fixes Jenkins pipeline for periodic tests. 
Fixes VZ-5480
=> VZ-5480: Fix Jenkins pipeline for periodic tets

Jenkinsfile, JenkinsfileCopyrightTest, ci/chaos/Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade/Jenkinsfile
Remove unused jenkins credentials
=> Remove unused jenkins creds github-userid-release and github-email-release

ci/JenkinsfileTestTrigger
Added warning about last stable commit text update to be not performed in other jobs
=> Added warning about last stable commit text update to be not performed in other jobs

ci/private-registry/Jenkinsfile, tests/e2e/pkg/common.go, tests/e2e/registry/registry_test.go, tests/e2e/verify-install/promstack/promstack_test.go
This fix is aimed to solving the private registry default image search.
Fixes No JIRA
=> Fix the Private Registry verify install test

platform-operator/verrazzano-bom.json
Update Keycloak 15.0.2 image, built from source.
Contributes to VZ-4577
=> VZ-4577: Update Keycloak 15.0.2 image

ci/kind/Jenkinsfile, platform-operator/verrazzano-bom.json, tests/e2e/opensearch/topology/topology_suite_test.go, tests/e2e/opensearch/topology/topology_test.go
Adds simple acceptance test for node groups
=> VZ 5704: Acceptance test for node groups

ci/upgrade-paths/Jenkinsfile
First iteration of the new multicluster pipeline
Fixes VZ-5503
=> VZ-5503 First iteration of the new multicluster pipeline

platform-operator/verrazzano-bom.json, tools/bom-validator/bom-validator.go
=> VZ-5509 Align the versions of node-exporter installed with VMO and the one installed in verrazzano-monitoring

release/builds/Jenkinsfile, release/builds/JenkinsfilePreRelease, release/builds/JenkinsfileReleaseExistingCandidate
Release Jenkinsfiles still referenced Marks cred, switch that up
=> Change to new cred replaces Marks

platform-operator/verrazzano-bom.json
This PR updates the Keycloak 15.0.2 image in release-1.2.
Contributes to VZ-4577, VZ-5746 and VZ-5747
=> VZ-4577, VZ-5746, VZ-5747: Update Keycloak 15.0.2 image in release-1.2 branch

ci/chaos/Jenkinsfile
=> VZ-5473 Fix forward the chaos test because it does an upgrade

Jenkinsfile, JenkinsfileCopyrightTest, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/upgrade/Jenkinsfile, release/builds/Jenkinsfile, release/builds/JenkinsfilePreRelease, release/builds/JenkinsfileReleaseExistingCandidate
Backport cred changes to release 1.2:
- remove unused creds
- change from Mark's named cred to new cred
=> Tvlatas/vz 5699 backport to 1.2 (pipeline cred changes)

Jenkinsfile, JenkinsfileCopyrightTest, ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/upgrade/Jenkinsfile, release/builds/Jenkinsfile, release/builds/JenkinsfilePreRelease, release/builds/JenkinsfileReleaseExistingCandidate
Backport cred changes to release 1.1:
remove unused creds
change from Mark's named cred to new cred
=> Tvlatas/vz 5699 1.1

ci/upgrade-paths/Jenkinsfile
Refactors the external-dns script name. 
Fixes VZ-5480, VZ-5478
=> Refactor external-dns script name

Jenkinsfile, JenkinsfileCopyrightTest, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/upgrade/Jenkinsfile, release/builds/Jenkinsfile, release/builds/JenkinsfilePreRelease, release/builds/JenkinsfileReleaseExistingCandidate
Backport cred changes to release 1.1:
- remove unused creds
- change from Mark's named cred to new cred
=> Tvlatas/vz 5699 backport to 1.0 (pipeline cred changes)

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Update next version to be 1.2.2
Fixes VZ-9999
=> VZ-5754: Update dev version to 1.2.2

platform-operator/verrazzano-bom.json
Update release-1.2 bom to use 1.2.1 tags
Fixes VZ-9999
=> VZ-5754 Update release-1.2 bom to use 1.2.1 tags

platform-operator/controllers/secrets/secrets_controller.go
Fixes a bug in earlier change for VZ-5621
=> No Jira: fix initialization issue creating new secret

ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease
Fix periodic schedule 
Fixes VZ-5480
=> Fix periodic trigger of patch release upgrade testing. 

platform-operator/verrazzano-bom.json
Promotes Keycloak image with updates to artemis-commons to Verrazzano release-1.2
Contributes to VZ-5748
=> VZ-5748: Update Keycloak image in release-1.2

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/thirdparty/manifests/jaeger/jaeger-operator.yaml, platform-operator/verrazzano-bom.json
=> Jaeger Ingester

platform-operator/verrazzano-bom.json
=> VZ 4381: Fluentd v1.14.5

ci/upgrade-paths/Jenkinsfile
Verify Verrazzano install resource has the expected console URLs
Fixes VZ-5772
=> VZ-5772 Verify Verrazzano install resource has the expected console URLs

ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease
- Fix missing patch release upgrade
- Fix vz profile for patch and minor release upgrade. 
Fixes VZ-5483
=> Fix for patch and minor release upgrade. 

platform-operator/verrazzano-bom.json
Update Keycloak image, built with OEL-8 base image.
Contributes to VZ-5774
=> VZ-5774: Update Keycloak image, built with OEL-8 base image

platform-operator/verrazzano-bom.json
Update Keycloak image, built with OEL-8 base image.
Contributes to VZ-5774
=> VZ-5774: Update Keycloak image in release-1.2, built with OEL-8 base image

ci/dynamic-updates/Jenkinsfile
Replace Bobs-books and to-do with WLS and COH workload tests.
=> Fix Dynamic config tests

platform-operator/helm_config/charts/verrazzano/values.yaml
Remove a few things from the Verrazzano helm chart values.yaml file that shouldn't be there.
=> NO JIRA: Remove a few values that aren't used and don't belong in the Verrazzano helm chart

platform-operator/internal/yaml/expand.go, platform-operator/internal/yaml/expand_test.go
This updates some copyright files that are failing the build.
Fixes NO-JIRA
=> NO JIRA: Copyright update

platform-operator/controllers/verrazzano/component/common/vmi.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearch/vmi_test.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
This pull request allows OS and OSD to install without NGINX being enabled.
=> VZ-5680: Allow OS and OSD to install without nginx

ci/upgrade/Jenkinsfile, tests/e2e/logging/opensearch/opensearch_mappings_test.go, tests/e2e/logging/opensearch/opensearch_retention_policy_test.go, tests/e2e/logging/opensearch/opensearch_rollover_policy_test.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/opensearch_dashboards.go, tests/e2e/pkg/web.go, tests/e2e/update/updater.go, tests/e2e/upgrade/post-upgrade/opensearch-dashboards/opensearch_dashboards_test.go, tests/e2e/upgrade/post-upgrade/opensearch/opensearch_test.go, tests/e2e/upgrade/pre-upgrade/opensearch-dashboards/opensearch_dashboards_test.go, tests/e2e/upgrade/pre-upgrade/opensearch/opensearch_test.go
Removed the checks added in tests for handling scenarios when data stream support was not available. Fixed tests in pre-upgrade phase and included it in the pipeline.
Fixes VZ-5500
=> VZ-5500 Enabling Datastream based tests for ISM policies

ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, tests/e2e/config/scripts/terraform/cluster/variables.tf
=> NO-JIRA Update Release 1.0 to use OKE 1.20.8

ci/kind/Jenkinsfile, ci/upgrade/Jenkinsfile, tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/istio/istio_test.go
Adds a simple update scenario to include with the upgrade, to validate that updates are successfully applied when coupled with an upgrade.
Fixes VZ-5762.
=> VZ-5762.  Add tests to add update during upgrade scenario.

ci/upgrade-paths/Jenkinsfile, tests/e2e/multicluster/workloads/mccoherence/coherence_workload_mc_suite_test.go, tests/e2e/multicluster/workloads/mccoherence/coherence_workload_mc_test.go, tests/e2e/workloads/coherence/coherence_workload_suite_test.go, tests/e2e/workloads/coherence/coherence_workload_test.go
As per new upgrade pipeline, example coherence application has been modified and placed. 
Fixes VZ-5759
=> VZ-5759 Coherence Example App fit into New Upgrade Pipeline

ci/JenkinsfilePeriodicTests
Fix a typo in the periodic tests, missing quote
=> add missing single quote

tools/bom-validator/bom-validator.go
Remove additional-rancher from ignore list
=> No JIRA. Remove additional-rancher from ignore list

platform-operator/verrazzano-bom.json
Pick up new Rancher tag, which resolves issue of a right curly brace being added to the rancher-agent image name.
Fixes VZ-5816
=> VZ-5816 pick up new rancher tag

platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/mysql/mysql_test.go, platform-operator/scripts/hooks/mysql-hook.sh
The mysql hook can be used with velero backup CR , when implemented
=> VZ-5799: mysql backup hook

ci/dynamic-updates/Jenkinsfile, tests/e2e/update/authproxy/authproxy_update_test.go, tests/e2e/update/nginxistio/nginxistio_suite_test.go, tests/e2e/update/nginxistio/nginxistio_test.go, tests/e2e/update/updater.go, tests/e2e/update/validation.go
Acceptance tests for Nginx and Istio updates in dynamic-updates
Fixes VZ-5466
=> VZ-5466 Nginx and Istio update tests

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml
Backporting #2818 
* VZ-5338 Corrected error log location
* VZ-5338 Change logging to /var/log/nginx/error.log.
=> Pshirodkar/vz 5338 (#2818)

platform-operator/helm_config/charts/verrazzano/templates/authorizationpolicy.yaml
Backporting #2846
Fixes VZ-5436
=> VZ-5436: AuthPolicy vmi-system-es-ingress-authzpol is incorrect and has the wrong name
