install/chart/values.yaml

- Change registry from OCR to OCIR on develop branch
- https://jira.oraclecorp.com/jira/browse/VZ-1164
- https://build.verrazzano.io/job/verrazzano/job/kminder%252Fvz1164/

VZ-1164: revert verrazzano develop branch back to ocir

---

uninstall/uninstall-steps/0-uninstall-applications.sh
uninstall/uninstall-steps/1-uninstall-istio.sh
uninstall/uninstall-steps/2-uninstall-system-components.sh
uninstall/uninstall-steps/3-uninstall-verrazzano.sh
uninstall/uninstall-steps/4-uninstall-keycloak.sh

Currently, some of the resources in the uninstall are grabbed by grepping for an aspect of their descriptions. Unfortunately, grep returns an error status of 1 when nothing is found. This is a functionality we want when performing the uninstall. Thus, we need a command that will grab these items but still return 0 when nothing is found to improve the error handling. then, the two part delete commands can be merged into one command again.
As an example, in 1-uninstall-istio.sh function delete_secrets() the following code block has to be written in 2 parts because `grep "istio.io" || true` will always be true.
```
local secret_res=("$(kubectl get secrets -n kube-system --no-headers -o custom-columns=":metadata.name,:metadata.annotations" \
| grep "istio.io" || true)")
printf "%s\n" …
```

Find alternative to grep to find resources

---

install/1-install-istio.sh

- Fix 1-install-istio.sh to update core dns config for OKE and OLCNE installs.
- https://build.verrazzano.io/job/verrazzano/job/kminder%252Fvz1171/
- Manually applied coredns-template.yaml change to a cluster.
- Manually updated 1-install-istio.sh and completed install of a cluster.
- https://jira.oraclecorp.com/jira/browse/VZ-1171

VZ-1171: istio dns not configured for olcne installs

---

install/chart/values.yaml

This pull request updates the verrazzano-operator tag to v0.0.91-b4c3058-1.
Test run: https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/rdonat%2Fvz-953/3/pipeline
JIRA: https://jira.oraclecorp.com/jira/browse/VZ-953

Update to use verrazzano-operator v0.0.91-b4c3058-1

---

uninstall/uninstall-steps/1-uninstall-istio.sh

In finalize() ...
```helm repo ls \
| awk '/istio.io|stable|jetstack|rancher-stable|codecentric/ {print $1}' \
| xargsr -I name helm repo remove name \
|| return $?
```
```
helm repo ls
Error: no repositories to show
echo $?
1
```
gives an error output of 1 when no elements are present. This causes the pipeline to fail. This task will be completed when the uninstall avoids non-zero output with no helm repo elements, and deletes elements when they are present in the repo.

Find clean way to delete helm repo elements.

---

install/chart/values.yaml

JIRA: https://jira.oraclecorp.com/jira/browse/VZ-830
Test: https://build.verrazzano.io/job/verrazzano/job/guzhang%252Fvz830/

Update to use verrazzano-operator v0.0.93-8be65b3-1 for VMI memory requests

---

install/install-olcne.md

A manual DNS mode requires load balancers, the removed text is not longer true.
Signed-off-by: Mark Cram <mark.cram@oracle.com>

Docs: OLCNE requires load balancers

---

uninstall/uninstall-steps/0-uninstall-applications.sh
uninstall/uninstall-steps/1-uninstall-istio.sh
uninstall/uninstall-steps/2-uninstall-system-components.sh
uninstall/uninstall-steps/3-uninstall-verrazzano.sh
uninstall/uninstall-steps/4-uninstall-keycloak.sh
uninstall/uninstall-utils.sh

There is a lot of repeated code to maintain throughout the uninstaller. This code can be refactored to make maintaining and updating easier. 
The code should transform:
```
kubectl get csr --no-headers -o custom-columns=":metadata.name" \
| awk '/csr-/' \
| xargsr kubectl delete csr \
|| return $?
```
to this:
```
delete_k8s_resources csr '/csr-/' ":metadata.name" || return $?
```

Create delete resource and remove finalizer functions.

---

install/3-install-verrazzano.sh
install/chart/templates/01-verrazzano-operator.yaml
install/chart/templates/02-verrazzano-cluster-operator.yaml
install/chart/templates/03-verrazzano-monitoring-operator.yaml
install/chart/templates/04-verrazzano-admission-controller.yaml
install/chart/values.yaml

Set up memory requests in verrazzano and VMI pods.
JIRA:  https://jira.oraclecorp.com/jira/browse/VZ-830
Acceptance tests:  https://build.verrazzano.io/job/verrazzano/job/guzhang%252Fvz830_v/

update verrazzano-operator to v0.0.95-2a2ed1c-1 for memory requests in Verrazzano components and VMI pods

---

.github/workflows/pagerduty.yml

When an issue is opened or reopened in the verrazzano repo the action will be triggered and generate a pagerduty incident to alert the on-call engineer

JIRA:VZ-1214 github action to generate pagerduty incident when an issue is opened

---

install/chart/values.yaml

This pull request updates images that include changes for Go Report Card compliance.
Images updated are: verrazzano-admission-controller, verrazzano-helidon-app-operator, verrazzano-wko-operator, verrazzano-coh-cluster-operator and verrazzano-cluster-operator.

Update images with Go Report Card compliance changes

---

install/chart/values.yaml

Update to v0.0.97 of the verrazzano-operator - which detects imagePullSecrets in the verrazzano-operator service account and propagates them to service accounts created by the operator.

Update to v0.0.97 of the verrazzano-operator

---

install/README.md

Document the optional image pull secret `verrazzano-container-registry`.  This secret is only required when Installing Verrazzano with one or more Docker images that are marked private.  For example, this may be true when you are testing a change to one of the operators (e.g. verrazzano-operator).  Your test image may be private until you have validate the changes.

Document the optional image pull secret verrazzano-container-registry

---

install/chart/templates/03-verrazzano-monitoring-operator.yaml
install/chart/values.yaml

The `verrazzano-monitoring-instance-eswait` and `verrazzano-monitoring-instance-api` are not published to ghcr.io

Pull more verrazzano-monitoring-operator related images from ghcr.io

---

install/2a-install-system-components-magicdns.sh
install/2b-install-system-components-ocidns.sh
install/chart/templates/01-verrazzano-operator.yaml
install/chart/templates/03-verrazzano-monitoring-operator.yaml
install/chart/values.yaml
install/common.sh

Pull many more images from ghcr.io.
Removed the global switch of being able to select which repository to pull images from.  Now each image can individually be overridden.

Get most of the build-from-source images from ghcr.io

---

install/chart/values.yaml

This pull request picks up these new images:
ghcr.io/verrazzano/verrazzano-monitoring-instance-eswait:v0.0.24
ghcr.io/verrazzano/verrazzano-monitoring-operator:v0.0.24
ghcr.io/verrazzano/verrazzano-operator:v0.0.99-07df6c6-1

Update installer to pickup new versions of verrazzano-operator and verrazzano-monitoring images

---

install/chart/values.yaml

Use new verrazzano monitoring operator, v.0.0.25, with Elasticsearch Master PV support.

Use new verrazzano monitoring operator with Elasticsearch Master PV support

---

install/3-install-verrazzano.sh

Added error checking for openssl commands in v8o install script.
Now if an openssl command fails, the script will fail and provide an error message.
Also, made a change to generate temporary artifacts into a temp directory instead of the previous directory under build.
The temp directory is now cleaned up via a signal trap instead of on the last line of the script to guarantee that the cleanup will occur even in the event of a failure.

VZ-1426: Add error checking for openssl commands in install script

---

.github/workflows/pagerduty.yml

Given new security constraints that only allow local, oracle/*, or docker/* actions the workflow that trigger pagerduty alerts for new, re-opened, or commented issues has been modified to use curl directly.

JIRA:VZ-1601 modify workflow to use curl directly

---

uninstall/uninstall-steps/1-uninstall-istio.sh
uninstall/uninstall-steps/3-uninstall-verrazzano.sh

This pull request updates the uninstall scripts to not delete resources related to in-cluster install.  For example, the verrazzanos.install.verrazzano.io crd and verrazzano-platform-operator resources should not be deleted.

Update uninstall scripts to not delete resources related to in-cluster install

---

install/chart/crds/verrazzano.io_verrazzanomodels_crd.yaml
install/chart/values.yaml

Pick up latest verrazzano-operator, verrazzano-cluster-operator and verrazzano-admission-controller images.
Also an updated CRD file for models.

Update to latest docker images

---

install/chart/values.yaml

Update the verrazzano-operator image in install/chart/values.yaml from master build#251, which contains the change submitted for VZ-1653
Acceptance Test - https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/pabhat%2Fvz1653/2/pipeline

VZ-1653 : Update verrazzano-operator from master build# 251

---

install/2a-install-system-components-magicdns.sh
install/2b-install-system-components-ocidns.sh

If resetting the Rancher password fails during install step 2, the error is swallowed which causes downstream install steps to fail. This PR adds a check and fails the install if we are unable to reset the Rancher password.
Example install output showing the failure:
```
$ ./2a-install-system-components-magicdns.sh 
Output redirected to /Users/ftibbitts/go/src/github.com/verrazzano/verrazzano/install/build/logs/2a-install-system-components-magicdns.sh.log
Installing NGINX ingress controller                                          [  OK  ]
Installing certificate manager                                               [  OK  ]
Installing Rancher                                                           [  \   ]
ERROR: Failed to reset Rancher password
Installing Rancher …
```

VZ-1177: Add check for empty Rancher password in install step 2

---

Jenkinsfile

Also, ONLY run the acceptance tests on develop or master branches, unless explicitly set to run them using the RUN_ACCEPTANCE_TESTS parameter

Trigger job in verrazzano-magic-dns-acceptance-tests

---

Makefile
operator/config/crd/bases/install.verrazzano.io_verrazzanos.yaml
operator/deploy/operator.yaml

This pull request changes the verrazzano CRD to use apiextensions.k8s.io/v1 instead of  apiextensions.k8s.io/v1beta1

Update verrazzano CRD to use apiextensions.k8s.io/v1

---

Jenkinsfile

The ACCEPTANCE_TESTS_BRANCH parameter value should be passed to the downstream acceptance tests job

Pass test branch to downstream Jenkins job

---

Jenkinsfile

Clean workspace at end of Jenkins pipeline in the event agents are reused (which they were temporarily) you start w/ a clean workspace.

Cleanup jenkins workspace after build

---

operator/scripts/install/chart/values.yaml

Bump verrazzano-operator image version to pick up the latest version of the operator. Contains a fix for customer reported issue https://github.com/verrazzano/verrazzano/issues/339.

Bump verrazzano-operator image version

---

operator/internal/installjob/install_config.go
operator/internal/installjob/install_config_test.go

ClusterResourceNamespace and SecretName when specified in verrazzano resource were being ignored by platform-operator. This is fixed with this pull request.

Fix bug where the verrazzano CR Certificate.CA fields were ignored

---

operator/internal/util/log/log.go

This pull request changes the platform operator to not use the zapcore.FullCallerEncoder for logging the caller field.
With this change the caller field looks like this: 
"caller":"log/log_test.go:19"
Prior to this change the caller field looked like this: 
"caller":"/root/go/src/github.com/verrazzano/verrazzano/operator/internal/util/log/log_test.go:18
Also, removed explicit setting the caller. level, and name keys since those are the defaults.
These changes are inline with the what the other operators (verrazzano-operatort, helidon-app-operator, etc)  are doing.

Change platform-operator to not use zapcore.FullCallerEncoder

---

operator/scripts/install/4-install-keycloak.sh
operator/scripts/install/chart/templates/01-verrazzano-operator.yaml
operator/scripts/install/chart/templates/05-verrazzano-console.yaml
operator/scripts/install/chart/values.yaml
operator/scripts/install/config/keycloak.json

The Verrazzano Console is added to the Helm chart so that it is installed when the installer is run.

Add Verrazzano Console to Helm chart

---

Makefile
operator/README.md
operator/config/scripts/run.sh
operator/controllers/verrazzano_controller.go
operator/controllers/verrazzano_controller_test.go
operator/internal/installjob/job.go
operator/internal/installjob/job_test.go
operator/internal/jobs.go
operator/internal/uninstalljob/job.go
operator/internal/uninstalljob/job_test.go
operator/main.go

Save the install resource spec to an internal configmap
- Also, add support for a NOOP mode for the install jobs to allow testing operator flow in-cluster without trigger actual installs/uninstalls
- add a helper make target to generate an operator deploy YAML file

VZ-1788.  Save current Verrazzano install state

---

operator/deploy/operator.yaml

Update operator.yaml to use the release build of the verrazzano-platform-operator.  The automated process for updating this file did not work.

Update operator.yaml to use release build

---

Jenkinsfile

The service key is currently not set so two issues arise in the build failure processing block:
- the processing fails due to the missing property
- the notifications to slack and on-call for master and develop branch failures do not occur

JIRA:VZ-1889 add pager duty service key so failure processing succeeds

---

Jenkinsfile

The region list had San Jose, but turns out the tenancy is not subscribed there, removing it

Remove San Jose from region list it was not subscribed

---

operator/config/scripts/run.sh
operator/scripts/install/chart/Chart.yaml

Change the Chart.yaml from 0.6.0 to 0.7.0
Create kubeconfig for platform operator.  This got removed is recent commit but is needed for helm to run during upgrade.

Change the Chart.yaml from 0.6.0 to 0.7.0 and create kubeconfig for platform operator

---

README.md
install.md

This pull requests adds 
kubectl -n verrazzano-install rollout status deployment/verrazzano-platform-operator
to a couple of readmes after applying operator.yaml

Add kubectl command to readmes to wait for verrazzano-platform-operator deployment

---

operator/scripts/install/2-install-system-components.sh
operator/scripts/install/3-install-verrazzano.sh
operator/scripts/install/4-install-keycloak.sh
operator/scripts/install/common.sh
operator/scripts/install/config.sh

On MAC, unlike Linux, container ip is not accessible in docker bridge network.  The workaround is to port forwarding.
Nginx ingresses are now bound to 127.0.0.1.

KinD support on MAC

---

Makefile
operator/api/verrazzano/v1alpha1/validate.go
operator/api/verrazzano/v1alpha1/validate_test.go
operator/api/verrazzano/v1alpha1/verrazzano_webhook.go
operator/api/verrazzano/v1alpha1/verrazzano_webhook_test.go
operator/controllers/upgrade_reconciler_test.go
operator/internal/util/env/env.go
operator/internal/util/env/env_test.go
operator/internal/util/semver/semver.go
operator/internal/util/semver/semver_test.go

Added a few more unit tests for validation code, and added comments/prologues where needed
Also, added operator/api packages to unit test suite
Updated SemVersion
- Added test comments and some new test cases
- Added some convience comparison methods (==, >, <) with unit tests
- Removed the full version string from the struct

VZ-1897 validation/webhook cleanup

---

operator/scripts/install/chart/values.yaml

In https://github.com/verrazzano/console/pull/40 and https://github.com/verrazzano/verrazzano-operator/pull/217 a new field `isUsingSharedVMI` is added to instance api response and UI changes to display the telemetry links accordingly. This PR to uptake these two changes which are now merged

Update image version for console and verrazzano-operator for isUsingSharedVMI field changes to instance api

---

operator/scripts/install/chart/values.yaml

that uses in-cluster address to connect to keycloak

upgrade verrazzano-operator to 0.8.0-20201223143759-ba517ea

---

operator/internal/certificate/certificate.go

Rename misspelled file certicates.go to certificates.go
Add SAN to webhook certificate to avoid errors in later golang versions to resolve this error:
"operator/config/samples/install-default.yaml": Internal error occurred: failed calling webhook "install.verrazzano.io": Post "https://verrazzano-platform-operator.verrazzano-install.svc:443/validate-install-verrazzano-io-v1alpha1-verrazzano?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

Add SAN to webhook certificate

---

operator/scripts/install/common.sh

Uninstall broke with the changes for adding the helm charts into the verrazzano repository.   The manifests folder was not being set correctly for uninstall, so the uninstall of cert-manager was failing.

Fix uninstall regression

---

operator/internal/config/config.go
operator/internal/config/config_test.go
operator/scripts/install/3-install-verrazzano.sh
operator/scripts/install/chart/templates/01-verrazzano-operator.yaml
operator/scripts/install/chart/templates/02-verrazzano-cluster-operator.yaml
operator/scripts/install/chart/values.yaml

A recent merge moved the charts on the image which broken upgrade.
Another merge changed rancher helm schema for values that do not have defaults, which also broke upgrade
Fix both issues.

Fix the chart location used by upgrade

---

operator/scripts/install/chart/values.yaml

Updating the monitoring operator image to work around an issue with the ES rolling upgrade logic in that code.  This fixes ES patching, and we will address rolling upgrade subsequently.

VZ-1885.  Patch Elasticsearch

---

operator/scripts/install/chart/values.yaml

This PR picks up a new version of the verrazzano-operator image, from VZ-1947, which contains a small fix to deduplicate secrets lists in the domain configuration.

Promote new verrazzano-operator image

---

operator/internal/component/component.go
operator/internal/component/component_test.go
operator/internal/component/helm_component.go
operator/internal/component/helm_component_test.go
operator/scripts/install/2-install-system-components.sh
operator/scripts/install/common.sh
operator/scripts/install/components/cert-manager-values.yaml

Enable patch-level upgrades for cert-manager.
AT: https://build.verrazzano.io/blue/organizations/jenkins/verrazzano-kind-acceptance-tests/detail/mcico%2Fvz-1878-patch-certmgr/1/pipeline

VZ-1878. Patch cert-manager

---

operator/internal/component/helm_component.go
operator/internal/util/helm/helmcli.go
operator/internal/util/helm/helmcli_test.go

Certain components may not be installed, like external-dns.  Before doing the helm upgrade of a component, check if it is installed, otherwise upgrade will fail.

Check if component installed before upgrading it

---

Jenkinsfile

Change the build pipeline to run a reduced set of acceptance tests for changes to the verrazzano repository.  Saves about 12 minutes.

Use reduced set of acceptance tests

---

oam-application-operator/Makefile
operator/Makefile

Add -v 1 to the KIND create in integ-test targets to get debug stack details for the intermittent issues that we are seeing recently. VZ-1934

Add -v 1 to kind create in integ-test targets to get debug details

---

oam-application-operator/examples/bobs-books/README.md
oam-application-operator/examples/bobs-books/install-bobs-books.sh
oam-application-operator/examples/todo/README.md
oam-application-operator/examples/todo/install-todo.sh
oam-application-operator/installer/scripts/2-install-wls-operator.sh
operator/scripts/install/3-install-verrazzano.sh

Changes the namespace label the WebLogic operator watches to detect Domain CRs from `verrazzano-domain` to `verrazzano-managed`.  This is more future proof as this namespace label can then be used for other Verrazzano features that might apply for a given namespace.

VZ-2011: use a more generic namespace label selector for oam based weblogic workloads

---

application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/helidon_test.go
application-operator/controllers/loggingscope/loggingscope_controller.go
application-operator/controllers/loggingscope/loggingscope_controller_test.go
application-operator/controllers/loggingscope/wls.go
application-operator/test/integ/integ_test.go
application-operator/test/integ/k8s/resource.go

* loggingscope adds logging sidecar to generated k8s Deployment of containerized workload (ex. Helidon application) to send logs to system VMI Elasticsearch
* changed the index pattern to include namespace prefix
filed VZ-2016 to refactor OAM logging handlers to share common codes

fluentd sidecar of helidon

---

examples/hello-helidon/install-hello-world.sh
examples/sock-shop/install-sock-shop.sh

Fixed the path for config.sh and logging.sh in the install scripts of verrazzano examples.

Fix the path for config.sh and logging.sh in the install scripts for verrazzano examples

---

platform-operator/controllers/component/component.go
platform-operator/controllers/component/helm_component.go
platform-operator/controllers/component/helm_component_test.go
platform-operator/controllers/component/istio.go
platform-operator/controllers/component/istio_test.go
platform-operator/controllers/component/verrazzano.go
platform-operator/controllers/component/verrazzano_test.go
platform-operator/controllers/controller.go
platform-operator/controllers/upgrade.go
platform-operator/internal/util/helm/helmcli.go
platform-operator/internal/util/helm/helmcli_test.go

This pull request changes the logging to consistently use the zap SugaredLogger and to use the same logger created in the Verrazzano controllers Reconcile function throughout the code.  All platform-operator log messages now contain the same fields: level, timestamp, caller, message and resource fields.

Use consistent logging in platform-operator

---

platform-operator/scripts/install/3-install-verrazzano.sh
platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
tests/e2e/verify-install/kubernetes/kubernetes_test.go

The the verrazzano-mc namespace as part of an install, it will be used to contain the verrazzano multi-cluster objects.
Add a test to verify the namespace is created.

Create verrazzano-mc namespace as part of install

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go
application-operator/controllers/loggingscope/loggingscope_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go
application-operator/controllers/navigation/trait.go
application-operator/controllers/navigation/trait_test.go
application-operator/controllers/navigation/workload.go
application-operator/controllers/navigation/workload_test.go

I'm breaking this ticket into multiple PRs to try to make them easier to review rather than submitting a single, bigger PR. This PR continues support for VerrazzanoCoherenceWorkload.
Specifically, this PR updates the ingress and metrics traits so that they are Verrazzano workload aware. When fetching the workload for the trait, if the workload is a Verrazzano workload type, we unwrap the contained workload before fetching the workload definition and children. Most of the code here is in additional unit tests.
**Note**: Based on the late-breaking decision to remove the kind and API version from the wrapped CRs, I will have to make corresponding CRD and implementation changes. I'm not going to do that yet, I'll submit a separate PR for those changes.

VZ-2044: Additional support for VerrazzanoCoherenceWorkload

---

application-operator/apis/clusters/v1alpha1/multicluster_common_types.go
application-operator/config/rbac/role.yaml
ignore_copyright_check.txt
tests/e2e/examples/sock-shop/sockshop.go

The ignore_copyright_check.txt file had a blank line and the copyright scanner seems to have a bug where this causes the entire root directory to be skipped.
This PR removes the blank line and fixes copyright scan errors that were reported.

Restore copyright scanning in this repo

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/loggingscope/fluentd.go
application-operator/controllers/loggingscope/fluentd_test.go
application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/wls.go
tests/e2e/examples/todo-list/todo_list_test.go

This PR updates the Coherence ES index to match the work that GZ recently did for WLS. The index uses the pattern `oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}` so that users can more easily search logs for their applications.
The work in the VerrazzanoCoherenceWorkload controller was simply to update the fluentd rules and also to copy the OAM app and component name labels into the Coherence CR that the controller writes out.
I also moved 3 fluentd container environment variables out of `wls.go` into `fluentd.go` as they will be needed by all workload types.

VZ-2044: Update Coherence ES index

---

platform-operator/helm_config/overrides/istio-values.yaml

This pull request fixes a problem where the istio-proxy sidercar was not getting to a ready state because a readiness probe was failing.  The fix was to include additional settings during istio install.  Also, removed explicitly setting of ingressgateway ports which were not needed.

Fix problem where istio-proxy container not in ready state

---

examples/sock-shop/sock-shop-app.yaml
examples/sock-shop/sock-shop-comp.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_verrazzanocoherenceworkloads.yaml
tests/e2e/examples/sock-shop/sock_shop_example_test.go

I updated the components to use the new VerrazzanoCoherenceWorkload workload. I also updated the app config file so there's a single app config instead of one per component.
I deployed the components and app, verified that all of the pods, etc. come up cleanly, used curl to test the apps, confirmed that metrics, etc. are reporting correctly.

VZ-V2044: Update sockshop example to use VerrazzanoCoherenceWorkload

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/go.sum

This pull request adds the sidecar.istio.io/inject annotation as part of the Coherence workload and sets the value to false.
Setting the value to false insures that the sidecar istio-provy is not injected into a Coherence pod.  Coherence does not work with istio so this is required.

Add  sidecar.istio.io/inject annotation to Coherence workload

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go

There is a problem with the way we manage fluentd configmaps for our OAM components. We create a single configmap in the namespace and all pods refer to the one configmap. When deleting an app config, if the configmap is deleted and one or more pods happen to restart, they fail to come up because they cannot mount the configmap, resulting in the pods being in a bad state.
For now, I'm removing the code from the VerrazzanoCoherenceWorkload controller that deletes the configmap. This means the configmap will not get deleted but at least all of the statefulsets, pods, etc. will get cleaned up and the namespace won't be blocked from being deleted.
We need to come up with a long-term solution for this problem. Maybe create a separate configmap per component? I think there still may be a race …

Remove delete of fluentd configmap

---

.github/workflows/pagerduty.yml

Looking at how to best verify this, the change is to add a conditional to the job which will not execute on PR's
From the github examples:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment

Do not page on PR issues

---

platform-operator/Makefile
platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
platform-operator/config/crd/bases/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
platform-operator/controllers/verrazzanomanagedcluster/verrazzanomanagedcluster_controller.go
platform-operator/controllers/verrazzanomanagedcluster/verrazzanomanagedcluster_controller_test.go
platform-operator/deploy/operator.yaml
platform-operator/test/integ/integ_test.go
platform-operator/test/integ/testdata/vmc_sample.yaml

Update the controller for the VerrazzanoManagedCluster objects to generate a service account and associate it with the VMC object.
Fixes VZ-2057

Upgrade VMC controller to generate a service account

---

application-operator/controllers/loggingscope/wls.go
application-operator/controllers/loggingscope/wls_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

This PR continues the implementation of the VerrazzanoWebLogicWorkload controller. It includes most of the core functionality, including logging. I think support for deleting resources is the only chunk left and that will come in the next PR.
Code coverage on the controller is only at 76%. Most of the uncovered lines are error conditions that are not easily tested. I will increase the coverage % in the next PR.
Note that nothing is actually using this new workload type yet. The last PR will switch the examples over to use this workload.
Provide details about how you tested this changed, if necessary
provide instructions to reproduce the testing.

VZ-2047: More implementation of the VerrazzanoWebLogicWorkload controller

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go

Fix bug, the VerrazzanoCoherenceWorkload controller was copying labels into the Coherence CR metadata labels. It needs to copy them into the `spec/labels` field instead.
Ran sockshop example, dumped the Coherence CR and confirmed the labels were in the correct location. Dumped the resulting Coherence pods and verified that the labels were present in the metadata labels section.

Fix bug copying labels in VerrazzanoCoherenceWorkload

---

application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go
application-operator/controllers/reconcileresults/reconcile_results.go
platform-operator/helm_config/charts/verrazzano-application-operator/values.yaml
platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
platform-operator/scripts/uninstall/uninstall-utils.sh
platform-operator/scripts/uninstall/uninstall-verrazzano.sh

Improves the resiliency of Verrazzano uninstall.  Fixes N things in particular.
1. Fixes issues in metrics trait controller that prevented finalizer removal if a related resource was deleted before the trait.
2. Removes all OAM apps as part of uninstall.
3. Improves resiliency of Rancher CRD cleanup.
4. Checks for existence of OAM components before attempting to delete them. 
5. Uses the correct namespace when deleting OAM components.
Fixes VZ-2031
In KinD cluster did repeated (>20) apply/delete of OAM apps. 
Also did repeated install/uninstall of Verrazzano with OAM apps left deployed.

VZ-2031: uninstall hangs when oam applications are running

---

platform-operator/helm_config/charts/verrazzano/values.yaml

Updates the Verrazzano Monitoring Operator image to incorporate the fix to set ES logging to INFO by default.
Fixes VZ-2097

VZ-2097.  Make ES logging level INFO by default

---

Jenkinsfile
platform-operator/test/kind-config.yaml
tests/e2e/config/scripts/install-metallb.sh
tests/e2e/config/scripts/install-verrazzano-kind.yaml
tests/e2e/pkg/api.go
tests/e2e/pkg/environment.go
tests/e2e/pkg/vmi.go
tests/e2e/pkg/web.go
tests/e2e/verify-install/web/web_test.go

In Verrazzano build pipeline, update acceptance test to use metallb to replace nodeport for nginx and istio ingress access in KinD.
Fixes VZ-2146

Update Verrazzano acceptance test to use Kind with metallb

---

application-operator/controllers/loggingscope/wls.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
examples/bobs-books/bobs-books-comp.yaml
examples/todo-list/todo-list-components.yaml
tests/e2e/examples/bobs-books/bobs_books_test.go
tests/e2e/examples/todo-list/todo_list_test.go

This PR updates the bobs-books and todo-list examples to use the new VerrazzanoCoherenceWorkload and VerrazzanoWebLogicWorkload workload types. I also discovered a bug in the logging for WebLogic workloads and fixed it (there were two environment variables missing from the logging sidecar container).
Note that I also updated the e2e tests for these examples to use the correct ES index. Due to timing issues, the app name and component names were not set before the logging container started so those values in the index were blank. Now that the new workloads are pre-configuring logging, that problem goes away.

VZ-2047: Update examples to use VerrazzanoCoherenceWorkload and VerrazzanoWebLogicWorkload

---

platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/3-install-verrazzano.sh
platform-operator/scripts/install/common.sh
platform-operator/scripts/install/config.sh

Use nodeport instead of lb address to access rancher during install.  This way, installer will not access public endpoint, hence no DNS resolution needed.
Manually tested with OKE magicdns and OKE OCIDNS as well.

use nodeport instead of lb address to access rancher during install

---

application-operator/Makefile
application-operator/THIRD_PARTY_LICENSES.txt
application-operator/go.mod
application-operator/tools.go
platform-operator/Makefile
platform-operator/THIRD_PARTY_LICENSES.txt
platform-operator/go.mod
platform-operator/tools.go

go.mod due to go get calls.
Attempt to pin golint & ineffassign versions so `make check` doesn't modify go.mod.

Pin ineffassign and go-lint versions - avoid having make check modify

---

platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

The example apps create several resources as components/workloads which were not listed in permissions in the clusterrole created for console. This change adds those.
Fixes issue with displaying example apps in console

add additional permissions based on examples to console clusterrole

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

When I initially implemented the VerrazzanoWebLogicWorkload and VerrazzanoCoherenceWorkload controllers, I didn't know `SetOwnerReference` was a thing. This PR updates the controllers to call `SetOwnerReference` and removes all of the explicit delete handling code.
I tested by running the sockshop and todo-list examples and confirmed that when the OAM application YAML is deleted, all of the resources are cleanup up correctly.

VZ-2190: Set owner ref in workload wrapper controllers

---

platform-operator/helm_config/charts/verrazzano/values.yaml

Use new Verrazzano Operator image that fixes filebeat crash.  See https://github.com/verrazzano/verrazzano-operator/pull/229
Fixes VZ-2148

Use new Verrazzano Operator image

---

ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/uninstall/Jenkinsfile
tests/e2e/config/scripts/create_oke_cluster.sh
tests/e2e/config/scripts/kind-config.yaml
tests/e2e/config/scripts/looping-test/get_resources.sh

1. Fix the issue with the newly added Jenkins pipeline to run the ATs with kind clusters (various k8s versions), by installing metallb
2. Archive the output of the script which gathers the resources in default namespace, before installing verrazzano and after uninstalling verrazzano
3. Minor changes to the console output from the script, which creates the OKE cluster

Fix the acceptance test failures run with kind cluster

---

application-operator/mcagent/mcagent_configmap.go
application-operator/mcagent/mcagent_configmap_test.go
application-operator/mcagent/mcagent_loggingscope.go
application-operator/mcagent/mcagent_loggingscope_test.go
application-operator/mcagent/testdata/multicluster-configmap-update.yaml
application-operator/mcagent/testdata/multicluster-configmap.yaml
application-operator/mcagent/testdata/multicluster-loggingscope-update.yaml

This is a continuation of the work for VZ-2065.  This PR adds support for syncing MultiClusterConfigMap objects.  Also fixes a problem of updates to labels not being handled properly.
Fixes VZ-9999

Add support for syncing MultiClusterConfigMap 

---

application-operator/mcagent/mcagent_appconfig.go
application-operator/mcagent/mcagent_appconfig_test.go
application-operator/mcagent/mcagent_component.go
application-operator/mcagent/mcagent_component_test.go
application-operator/mcagent/mcagent_secret.go
application-operator/mcagent/mcagent_secret_test.go
application-operator/mcagent/testdata/multicluster-appconfig-update.yaml
application-operator/mcagent/testdata/multicluster-appconfig.yaml
application-operator/mcagent/testdata/multicluster-component-update.yaml
application-operator/mcagent/testdata/multicluster-secret-update.yaml

Add support for MulticlusterApplicationConfiguration to cluster agent
Fixes VZ-2065

Add support for MulticlusterApplicationConfiguration to cluster agent

---

platform-operator/helm_config/charts/verrazzano/templates/01-verrazzano-operator.yaml
platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-cluster-operator.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/scripts/install/3-install-verrazzano.sh
tests/e2e/verify-install/kubernetes/kubernetes_test.go

Uptake new cluster-opeartor and varrazzano-operator that accress rancher by nodeport instead of public address.

uptake operators that access rancher by nodeport instead of public address

---

application-operator/internal/certificates/certificates.go
application-operator/internal/certificates/certificates_test.go

This PR adds Subject Alternate Name (SAN) value DNSNames to validating webhook of application-operator, to fix the issue observed with OAM examples when run with KIND cluster v1.18 and 1.19. The creation of application resources fail with an exception like 
`Failed to create ToDo List application resource: failed to create or update resource: Internal error occurred: failed calling webhook "verrazzano-application-appconfig-defaulter.verrazzano.io": Post "
https://verrazzano-application-operator.verrazzano-system.svc:443/appconfig-defaulter?timeout=30s
": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`
This change fixes VZ-2207

Add Subject Alternate Name (SAN) - DNSNames to validating webhook of application-operator

---

application-operator/installer/scripts/3-install-coh-operator.sh
application-operator/test/templates/coherence_workload_statefulset.yaml
platform-operator/helm_config/overrides/coherence-values.yaml
platform-operator/thirdparty/charts/README.md
platform-operator/thirdparty/charts/coherence-operator/Chart.yaml
platform-operator/thirdparty/charts/coherence-operator/values.yaml

Upgrading the Coherence Operator from 3.1.1 to 3.1.3. I tested by installing Verrazzano on a local test cluster and went through the Coherence examples to make sure there were no regressions.
I also looked at public-facing docs to see if there were any references to the version of the Coherence Operator and did not find any.

VZ-2101: Bump Coherence Operator to 3.1.3

---

application-operator/mcagent/mcagent_appconfig.go
application-operator/mcagent/mcagent_appconfig_test.go

This is the initial PR for adding support to the multi-cluster agent to delete local multi-cluster objects that have deleted on the admin cluster.  Once this PR is approved, a follow-up PR will implement the delete for the rest of the MC resources.
Fixes VZ-2170

Support multi-cluster delete of application configuration objects

---

Jenkinsfile

Updates the Jenkinsfile to move the loading of the todo images into the todo stage and the bob's books images into the bob's books stage.  This ensures that the image loads only happen if required.

Move the load of the example images

---

application-operator/mcagent/mcagent_appconfig.go
application-operator/mcagent/mcagent_appconfig_test.go
application-operator/mcagent/mcagent_component.go
application-operator/mcagent/mcagent_component_test.go
application-operator/mcagent/mcagent_configmap.go
application-operator/mcagent/mcagent_configmap_test.go
application-operator/mcagent/mcagent_loggingscope.go
application-operator/mcagent/mcagent_loggingscope_test.go
application-operator/mcagent/mcagent_project_test.go
application-operator/mcagent/mcagent_secret.go
application-operator/mcagent/mcagent_secret_test.go

Complete the implementation of deleting Mcxxxx resources on managed clusters when they have been deleted on the admin cluster.
Fixes VZ-2170

Complete the implementation of deleting Mcxxxx resources

---

application-operator/constants/constants.go
application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller_test.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/testdata/hello-multiclusterappconfig.yaml
application-operator/controllers/clusters/multiclustercomponent/controller.go
application-operator/controllers/clusters/multiclustercomponent/controller_test.go
application-operator/controllers/clusters/multiclustercomponent/testdata/hello-multiclustercomponent.yaml
application-operator/controllers/clusters/multiclusterconfigmap/controller.go
application-operator/controllers/clusters/multiclusterconfigmap/controller_test.go
application-operator/controllers/clusters/multiclusterconfigmap/testdata/sample-mcconfigmap.yaml
application-operator/controllers/clusters/multiclusterloggingscope/controller.go
application-operator/controllers/clusters/multiclusterloggingscope/controller_test.go
application-operator/controllers/clusters/multiclusterloggingscope/testdata/sample-multiclusterloggingscope.yaml
application-operator/controllers/clusters/multiclustersecret/controller.go
application-operator/controllers/clusters/multiclustersecret/controller_test.go
application-operator/controllers/clusters/test/test_utils.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_appconfig_test.go
application-operator/mcagent/mcagent_component_test.go
application-operator/mcagent/mcagent_configmap_test.go
application-operator/mcagent/mcagent_loggingscope_test.go
application-operator/mcagent/mcagent_secret_test.go
application-operator/test/integ/integ_test.go
application-operator/test/integ/multi_cluster_test.go

Multi cluster controllers process only locally placed multi cluster resources.
Fixes VZ-2115
Cleanup changes:
- MC controllers should also set labels and annotations when mutating resources
- Added deletion test case for MCxxx resources
- Don’t log errors on notfound MCxxx resources - only if some other problem occurred
- separated test utility and non-test utility methods in the clusters package

Process only locally placed multi cluster resources

---

application-operator/controllers/navigation/trait.go
application-operator/controllers/navigation/trait_test.go
application-operator/deploy/workloaddefinition_vzhelidon.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_workloaddefinition_vzhelidon.yaml

This PR contains changes to support ingress trait for VerrazzanoHelidonWorkload.
Fixes VZ-2120

Ingress support for Helidon Workload

---

examples/bobs-books/README.md
tests/e2e/examples/bobs-books/bobs_books_test.go

Two PRs were merged that resulted in the Bob's Books example end-to-end test failing. When there were three separate app configs, we had to find the correct app ingress gateway for the app to get the right hostname. When the Bob's Books example app changed to use a single config, the test was looking for ingress gateways that no longer existed, and the tests could not access the 3 separate UI endpoints.
Since there is now a single app config, there is a single gateway and single ingress host name. The fix is to simply not look for specific gateways and just use the first (and only) gateway.
I also updated the Bob's Books README to reflect the fact that there is now a single app.

Bob's Book example e2e test fix

---

application-operator/Makefile
platform-operator/helm_config/overrides/oam-kubernetes-runtime-values.yaml

This PR uptakes the OAM Kubernetes Runtime image built from source by Oracle.  This image uses Oracle Linux 7 slim as the base image, and has some updated dependencies.
Fixes VZ-1470

Uptake OAM Kubernetes Runtime image built from source by Oracle

---

ci/kind/Jenkinsfile
ci/kind/JenkinsfileBuildTrigger
ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/uninstall/Jenkinsfile
tests/e2e/config/scripts/create_kind_cluster.sh

This PR removes triggering AT with k8s version 1.18 from verrazzano-triggered-acceptance-tests, which is already done by the top level Jenkinsfile (which runs by default). Also the references to 'develop' branch is replaced with 'master' as appropriate.

Remove triggering AT with k8s version 1.18 from the stable master build

---

tests/e2e/config/scripts/create_kind_cluster.sh

This PR allows creation of KIND cluster v1.18 from Jenkins pipeline verrazzano-new-kind-acceptance-tests and for any other purposes. This is basically reverting the change to tests/e2e/config/scripts/create_kind_cluster.sh, done by https://github.com/verrazzano/verrazzano/pull/710

Support creating k8s 1.18 KIND cluster

---

application-operator/Makefile
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_appconfig.go
application-operator/mcagent/mcagent_appconfig_test.go
application-operator/mcagent/mcagent_common.go
application-operator/mcagent/mcagent_component.go
application-operator/mcagent/mcagent_component_test.go
application-operator/mcagent/mcagent_configmap.go
application-operator/mcagent/mcagent_configmap_test.go
application-operator/mcagent/mcagent_loggingscope.go
application-operator/mcagent/mcagent_loggingscope_test.go
application-operator/mcagent/mcagent_project.go
application-operator/mcagent/mcagent_project_test.go
application-operator/mcagent/mcagent_secret.go
application-operator/mcagent/mcagent_secret_test.go

Refine the multi-cluster agent to only synchronize objects that are contained in namespaces specified by VerrazzanoProject resources.
- Each time VP resources are synced the list of namespaces to watch is rebuilt
- If a namespace gets from a VP, the agent will stop watching the namespace and leave it's content intact
Also fixed a problem where the `mcagent` unit tests were not being run
Fixes VZ-2209

Only synchronize multi-cluster objects from namespaces specified by VerrazzanoProject resources

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/loggingscope/fluentd.go
application-operator/controllers/loggingscope/fluentd_test.go
application-operator/controllers/loggingscope/wls.go
tests/e2e/examples/bobs-books/bobs_books_test.go

This is a short/medium-term fix for ES logging when an application is compromised of multiple workload types. Previously we created a single shared fluentd configmap for all pods regardless of workload type. This change results in a separate configmap per workload type.
I tested by running multiple examples and looking in Kibana to make sure I saw logs for all pods. For Bob's Books, I confirmed that both WebLogic and Coherence logs were sent. I also added another test to the Bob's Books test suite to look for Coherence log records in addition to WebLogic log records.

VZ-2189: Fix ES logging when app has multiple workload types

---

application-operator/Makefile
application-operator/constants/constants.go
application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/webhooks/logging_scope_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go

logging_scope_defaulter supports managed clusters where the default is supposed to Elasticsearch on the admin cluster. The Elasticsearch connection information is specified in the managed cluster registration secret.
Partially fixes VZ-2236

Support managed cluster when defaulting logging scope

---

application-operator/mcagent/mcagent_project.go
application-operator/mcagent/mcagent_project_test.go

Handle the use case where a VerrazzanoProject object is deleted on the admin cluster - the copies of the object on the managed clusters will also get deleted.
Fixes VZ-2210

Delete VerrazzanoProject resources on managed cluster when they no longer exist on the admin cluster

---

application-operator/constants/constants.go
application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go

Make Elasticsearch secret be a well known secret name
changes for VZ-2236

Make Elasticsearch secret be a well known secret name

---

Jenkinsfile
JenkinsfileCopyrightTest
Makefile
ignore_copyright_check.txt
tools/copyright/README.md
tools/copyright/copyright.go
tools/copyright/copyright_test.go
tools/copyright/go.mod
tools/copyright/go.sum
tools/copyright/ignore_copyright_check.txt
tools/copyright/test/ignore/someFile.txt
tools/copyright/test/include/badcopyright.txt
tools/copyright/test/include/badlicense.txt
tools/copyright/test/include/buried.txt
tools/copyright/test/include/good.txt
tools/copyright/test/include/ignore.txt
tools/copyright/test/include/nocopyright.txt
tools/copyright/test/include/nolicense.txt

Moves the copyright scanner from the internal repository and re-implements it in Go.  Also adds the ability to scan files explicitly.  
- You can provide a list of files and dirs to scan, which enables us to pass in just a set of modified files to check
- Error output now lists what checks failed for each file
- Added a verbose flag
- Added the ability to enforce the current year is in the copyright string; useful for checking modified files in a branch
- Updated the Makefile to add targets to check only the files that have changed locally in a branch, or files that have been changed in a branch (compared with master at present)
- Updated the Jenkinsfile to use the scanner
- Will use the branch-diff/current-year target later once resolve some issues with using `git log`/`git diff` in …

VZ-2173.  Move and update copyright scanner

---

tools/copyright/copyright.go
tools/copyright/copyright_test.go

Fix a bug in the copyright checker, not returning non-zero error code when errors exist.
Fixes VZ-2173

Fix bug in copyright checker

---

application-operator/controllers/webhooks/istio_defaulter.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
examples/bobs-books/bobs-books-comp.yaml
examples/todo-list/todo-list-components.yaml
tools/copyright/go.mod

This pull request contains Istio related changes to the Weblogic workload controller.
The changes are:
1. Automatically set the domain resource spec.configuration.istio.enabled value.  If the namespace of the domain has Istio enabled then set the value to true otherwise set the value to false.
2. Create an istio destination rule for the WebLogic servers when the namespace is Istio enabled.
3. Remove the setting of spec.configuration.istio.enabled from the examples - todo-list and bobs-books.
Fixes VZ-2114

Changes to Weblogic workload controller for istio

---

application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/helidon_test.go

This reverts commit 9091971c624c2c302e3ee1acb0cce96d5c9fb2fc.
Revert change that broke build
Related to VZ-2236

Revert "Changes in loggingscope secret for multi cluster"

---

.gitignore
tests/e2e/pkg/common.go
tests/e2e/verify-infra/vmi/vmi_test.go

fix intermittent failures in verify-infra/vmi, kibana and prometheus get 302(redirect) instead of 200(ok)
```
Ex. redirect &{GET https://kibana.vmi.system.xxx/app/kibana Referer:[https://kibana.vmi.system.xxx/]
Ex. redirect &{GET https://prometheus.vmi.system.xxx/graph Referer:[https://prometheus.vmi.system.xxx/]
```

fix vmi_test

---

Jenkinsfile
ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/uninstall/Jenkinsfile

Just to remove the content of the operator.yaml from Jenkins logs to make it more readable.

remove printing out operator.yaml in Jenkins logs

---

application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller.go
application-operator/controllers/clusters/multiclustercomponent/controller.go
application-operator/controllers/clusters/multiclusterconfigmap/controller.go
application-operator/controllers/clusters/multiclusterloggingscope/controller.go
application-operator/controllers/clusters/multiclustersecret/controller.go
application-operator/test/integ/multi_cluster_test.go

This PR fixes a problem where the controllers for MCxxxxx resources would go into a compute bound reconcile loop writing the status field of a resource.  This would occur when the resource embedded in the Mcxxxx envelope could not be created.

Fix compute bound controller loop when writing a failed status

---

application-operator/apis/oam/v1alpha1/loggingscope_types.go
application-operator/config/crd/bases/clusters.verrazzano.io_multiclusterloggingscopes.yaml
application-operator/config/crd/bases/oam.verrazzano.io_loggingscopes.yaml
application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/loggingscope/fluentd.go
application-operator/controllers/loggingscope/loggingscope_controller.go
application-operator/controllers/loggingscope/loggingscope_controller_test.go
application-operator/controllers/navigation/workload.go
application-operator/controllers/navigation/workload_test.go
application-operator/controllers/webhooks/logging_scope_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/deploy/verrazzano.yaml_template
examples/bobs-books/bobs-books-logging-scope.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclusterloggingscopes.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_loggingscopes.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/values.yaml

All logging scope fields are now optional, except for the workload refs field, because the OAM operator cannot handle a logging scope missing workload refs. The Fluentd image now comes from an environment variable set on the Verrazzano application operator, which is configured by the installer. The Elasticsearch URL and the secret name defaults are still hard-coded (that may change in the future).
Notes:
- I moved the function to fetch the logging scope given labels out of the workload functions file and into the logging scope file. The function has grown in scope, beyond just a simple workload utility function. As a result, the linter complained that the name should drop "LoggingScope" from the front to prevent stuttering when prefixed with the package.
- The defaults apply to …

VZ-2108: Make all logging scope fields optional

---

platform-operator/helm_config/charts/verrazzano/values.yaml
tests/e2e/pkg/elasticsearch.go
tests/e2e/verify-infra/vmi/vmi_test.go

Upgrade verrazzano-operator to fix filebeat on KinD; re-enable the filebeat test; add journalbeat test.

enable filebeat test in verify-infra/vmi

---

platform-operator/helm_config/charts/verrazzano/templates/03-verrazzano-monitoring-operator.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

This pull request updates the images for the monitoring operator.  The changes to the monitoring operator add an Istio sidecar to a Prometheus deployment.
Fixes VZ-2312

Update installer to pickup new monitoring operator images

---

examples/bobs-books/bobs-books-logging-scope.yaml

The changes to make logging scope fields optional included a change to the Bob's Books example to remove the Fluentd image, as a test to prove that it gets defaulted properly. Unfortunately the hackathon participants pull the examples from master so this breaks against the latest release.

Put fluentdImage back in Bob's Books logging scope

---

application-operator/constants/constants.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
application-operator/test/integ/k8s/resource.go
application-operator/test/integ/multi_cluster_test.go
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_default_labels.yaml
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_override_labels.yaml

Apply the verrazzano required labels to namespaces that are created or updated for a VerrazzanoProject.  Each namespace will get the following labels applied:
- verrazzno-managed: true
- istio-injection: enabled
However, if a user specifies these labels in the VerrazzanoProject resource, the customer supplied value wins.
Fixes VZ-2226

Add verrazzano required labels to namespaces created via a VerrazzanoProject

---

platform-operator/helm_config/overrides/istio-values.yaml
platform-operator/scripts/install/3-install-verrazzano.sh

This pull request changes the Istio install to not merge Prometheus metrics.   See https://istio.io/v1.7/docs/ops/integrations/prometheus/ for more details.  Without this change,  Prometheus annotations are overwritten and WLS metrics are not scraped when in the Istio mesh.
Also, unrelated I removed the creation of the admission controller certs since the admission controller is no longer deployed.

Change Istio install for prometheus metrics

---

ci/multicluster/Jenkinsfile

This change configures OCI DNS for the OKE multi-cluster environment. As part of this change, the groovy methods are added to dump various logs, similar to what is done by other CI pipelines.
Fixes the remaining part of VZ-2311

Configures OCI DNS for the OKE multi-cluster environment

---

application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
application-operator/test/integ/k8s/resource.go
application-operator/test/integ/multi_cluster_test.go
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_sample.yaml
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_update_rolebindings.yaml

This PR adds support for rolebindings in multi-cluster project namespaces. The VerrazzanoProject CR supports two optional lists of security subjects, one for admins and one for monitors. If the Project specifies subjects, we create up to four rolebindings per namespace. Admins are bound to the `verrazzano-project-admin` role as well as the cluster `admin` role. Monitor subjects are bound to the `verrazzano-project-monitor` role as well as the cluster `view` role.
I tested this manually by creating admin and managed clusters and applying a VerrazzanoProject YAML containing both admin and monitor subjects. I validated that the rolebindings were created in the project namespaces. For example:
```
$ k get rolebindings -n fred4
NAME                         ROLE …
```

VZ-2227: Add support for rolebindings in multi-cluster project namespaces

---

Jenkinsfile
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/helidon_test.go
application-operator/test/templates/helidon_workload_multi_container.yaml
application-operator/test/templates/logging_scope.yaml
tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/logging/helidon/helidon_logging_suite_test.go
tests/e2e/logging/helidon/helidon_logging_test.go
tests/testdata/logging/helidon/helidon-logging-app.yaml
tests/testdata/logging/helidon/helidon-logging-comp.yaml
tests/testdata/logging/helidon/helidon-logging-logging-scope.yaml

Current containerized and helidon workload's fluentd sidecar implementation assumes there is only one application-container in the generated k8s Deployment. OAM ContainerizedWorkload and Deployment allow multiple containers.
Refactor helidon logging: 
- add container name to ElasticSearch index
- add `oam.container.name` to logged fields 
- create source, filter and match in fluentd config for each app container 
- single fluent sidecar container and config map works for all app containers
- unit tests for helidon ContainerizedWorkloads and VerrazzanoHelidonWorkload
- update integration test
- add helidon logging acceptance tests
Fixes VZ-2017

Logs of multiple containers in a workload

---

application-operator/Makefile
application-operator/constants/constants.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_common.go
application-operator/mcagent/mcagent_test.go
application-operator/test/integ/multi_cluster_test.go

Watch for changes in the registration secret.  
- If secret is deleted stop syncing multi-cluster objects
- If the secret changes, re-establish the connection to the admin cluster with the new values
Fixes VZ-2228

Watch for changes in the registration secret

---

application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go
application-operator/controllers/webhooks/istio_defaulter.go
application-operator/controllers/webhooks/istio_defaulter_test.go

Update generated Prometheus scrape targets to use istio-certs and Update Auth Policy to allow Prometheus to scrape metrics from deployed OAM apps

---

application-operator/controllers/webhooks/appconfig_defaulter.go
application-operator/controllers/webhooks/appconfig_defaulter_test.go
application-operator/main.go
tests/e2e/examples/todo/todo_list_test.go

Clean up generated certificates and secrets during app deletion.
Fixes VZ-2222
- add cleanup to AppConfigWebhook
- add functions to clean up the generated certificates and secrets associated with the app config
- write unit tests to verify AppConfigWebhook behavior on delete
- modify TODO example acceptance test to check for creation of secret on deploy and cleanup on delete

Clean up generated certificates and secrets during app deletion

---

examples/bobs-books/bobs-books-app.yaml
tests/e2e/examples/bobsbooks/bobs_books_test.go

Updating tests to verify that the issues described in VZ-2099 & VZ-2147 are no longer a problem.
- Remove explicit logging scope on `bobby-wls` in `bobs-books-app` so that it will use the default logging scope.  Verified by existing case in `bobs-books-test`
- Update `WebLogic logging` test in `bobs-books-test` to also check for records under index `bobs-books-bobs-books-bobs-orders-wls`
Fixes VZ-2099 & VZ-2147

Update bobs example tests to test bobby-wls with default logging scope

---

application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
platform-operator/helm_config/charts/verrazzano/values.yaml

When the registration is updated (new reg, un-reg, cluster name updates), re-configure the beats by restarting the verrazzano operator. 
Fixes VZ-2168

update beats config upon multi-cluster registration change

---

ci/multicluster/Jenkinsfile
tests/e2e/config/scripts/install-metallb.sh

Enables multicluster acceptance testing on KinD in Jenkins.
- install up to 3 clusters (1 admin, to managed) 
- install VZ on each in parallel (using `managed-cluster` profile on the mgd clusters)
- execute the verify-infra tests that are currently working with it.
OKE support will be followed up through a separate PR.
Fixes VZ-2333

VZ-2333.  Multicluster acceptance test pipeline for KinD 

---

platform-operator/scripts/install/config/coredns-template.yaml

This pull request fixes the verrazzano-new-kind-acceptance-tests which are failing on Kubernetes 1.19 and 1.20.
The failure was due to a deprecated value being set in the coredns configmap in the kube-system namespace during the Istio install.
Fixes VZ-2396

Don't set upstream value in coredns config map

---

application-operator/main.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
platform-operator/helm_config/charts/verrazzano-platform-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
platform-operator/helm_config/charts/verrazzano-platform-operator/templates/clusterrole.yaml

Managed cluster agent updates VMC status on admin cluster to indicate last connection time.
Fixes: VZ-2266

Agent Updates VMC status with LastAgentConnectTime

---

tests/e2e/pkg/web.go

This PR changes the behavior of doReq() so that it does not call ginkgo.Fail() when a requests "fails" in a way that may not be permanent, but could be just due to the requested resource not yet being available, for example when the pod serving the request has not yet reached the ready/running state.

Don't call ginkgo.Fail() in web.go doReq()

---

ci/looping-test/Jenkinsfile
ci/uninstall/Jenkinsfile

This change fixes the issue with archiving the cluster dumps on failure, from the Jenkins script used by uninstall test and install-uninstall loop test. The Jenkins scripts are updated to list all the namespaces and list the pods in all the namespaces, for easier reference, even though the cluster dump might provide the same information.

Archive cluster dump on failures from uninstall pipeline

---

application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go

Remove unnecessary codes of restarting Prometheus when the config is updated
Fixes VZ-22199

Prevent Prometheus restart per application

---

ci/multicluster/Jenkinsfile
tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/web.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go

Update the verify-infra and verify-install ATs and include them in the MC AT pipelne.  Also cleans up a few things in the MC Pipeline Jenkinsfile.
- Check for VMI endpoints based on profile
- Check for VMI persistent volume configurations based on profile
- Also account in tests for cases where envName is not "default"
- enable the verify-infra and verify-install tests for the MC pipeline
- Jenkinsfile, rename KinD cluster version parameter, and spit out the cluster version before installing VZ
- Jenkinsfile, make profile parameters dropdown lists
- Jenkinsfile, go back to using the same env names in the VZ install CR regardless of cluster type
Fixes VZ-2334

VZ-2334.  Update verify-infra and verify-install for profiles, MC AT pipeline

---

application-operator/controllers/webhooks/logging_scope_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go
tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/examples/socks/sockshop.go

Attempts to delete a namespace containing an Verrazzano OAM based application (e.g. sock shop) are failing. In this use case an attempt is being made to delete the namespace without previously deleting the application.
This occurs when the application uses the default logging scope and the namespace is terminated without deleting the app config first.  When the namespace is deleted, the resources in that namespace are cleaned up including the default logging scope.  During that process the application config defaulter webhook is triggered with an UPDATE notification.  The webhook determines that a default logging scope is required for the app config, so it attempts to create a new one.  Obviously this should be skipped in the case where the namespace is being terminated.
This PR adds code …

Application configuration deletion failure prevents namespace deletion

---

ci/looping-test/Jenkinsfile
ci/uninstall/Jenkinsfile

This PR contains minor changes to list k8s resources, in Jenkins scripts used by uninstall tests and install-uninstall loop. The change skips certain stages when the previous stage fails, when applicable. As part of this change, the loop test is modified to run examples/todo, as we have an intermittent issue where some of the pods in cattle-system won't come up after reinstall. The issue will be investigated separately.

Update uninstall and loop scripts to list k8s resources

---

.gitignore
platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_webhook.go
platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_webhook_test.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/controllers/verrazzano/component/registry.go
platform-operator/controllers/verrazzano/component/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano_test.go
platform-operator/test/integ/integ_test.go

Reverts verrazzano/verrazzano#852
This change is causing a failure in the new multi-cluster acceptance test suite.  Reverting to investigate.

Revert "Add validating webhook to prevent VMC creation when Verrazzano not installed"

---

platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh

In this PR, a change is made to uninstall scripts to continue with the installation in case of an issue in deleting the rancher local cluster. The uninstall relies on 2-uninstall-system-components.sh to remove the resources in the cattle-system namespace using helm uninstall. Also this change makes the stderror available in the console log, when resetting the rancher password fails.
During the testing, it is noticed that the pods cattle-node-agent and cattle-agent fail to come up on verrazzano reinstall after a failure to delete the local cluster in the previous uninstall at times, which I would like to track separately, outside of this issue.
During the testing, it is noticed that the pods cattle-node-agent and cattle-agent don't come up on verrazzano reinstall after a failure to delete …

Ignore an issue with deletion of rancher local cluster during Verrazzano uninstall

---

tests/e2e/verify-infra/restapi/rancher_url_test.go

This PR attempts to resolve an intermittent test failure which occurs when the the certificate is not obtained quickly enough and the test times out/fails.  There is an excerpt of a test log below showing this condition. 
Contirbutes to VZ-2371
```
rancher url test Fetching the rancher url using api and test  
Fetches rancher url
/home/opc/jenkins/workspace/_oci-dns-acceptance-tests_master/tests/e2e/verify-infra/restapi/rancher_url_test.go:23
2021/03/23 16:28:14 [DEBUG] POST https://keycloak.b19.z55b.example.com/auth/realms/verrazzano-system/protocol/openid-connect/token
2021/03/23 16:28:15 [DEBUG] GET https://verrazzano.b19.z55b.example.com/20210501/apis/extensions/v1beta1/namespaces/cattle-system/ingresses/rancher
2021/03/23 16:28:20 …
```

Attempt to resolve intermittent AT fail by making test retry more times

---

make/generate.mk

Fix make manifests target to not generate a domain crd

Fix make manifests target to not generate a domain crd

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

Prior to these changes, the VerrazzanoWebLogicWorkload and VerrazzanoCoherenceWorkload components did not support updating. Once the underlying WebLogic domain and Coherence resources were created, they could not be updated. This PR fixes that so that the component specs can be updated and applied and the controllers will update the specs in the WebLogic domain and Coherence resources.
I tested this manually by deploying the Sock Shop example, updated the "replicas" from 1 to 3, applied the component YAML, and verified that the Coherence pods scaled up. I ran a similar test with the ToDo example and updated the VerrazzanoWebLogicWorkloads.
Fixes VZ-2370

VZ-2370: Fix VerrazzanoWebLogicWorkload and VerrazzanoCoherenceWorkload to handle workload updates

---

application-operator/apis/oam/v1alpha1/verrazzanocoherenceworkload_types.go
application-operator/apis/oam/v1alpha1/verrazzanohelidonworkload_types.go
application-operator/apis/oam/v1alpha1/verrazzanoweblogicworkload_types.go
application-operator/constants/constants.go
application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/controller_utils.go
application-operator/controllers/controller_utils_test.go
application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
application-operator/controllers/loggingscope/fluentd.go
application-operator/controllers/loggingscope/fluentd_test.go
application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/loggingscope_controller.go
application-operator/controllers/loggingscope/loggingscope_controller_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

Introduces a new label which users can set to upgrade their applications to use the latest installed version of Verrazzano. When a user upgrades Verrazzano, they may not want to immediately restart their applications and uptake any Verrazzano resource changes. When a user is ready to upgrade their application and uptake the latest Verrazzano provided resources, the user can set the label value to a different value in their application configuration. If the label value differs from the value stored in the workload status which was the last used value, then the application will be upgraded to the latest Verrazzano version. The label can be any valid string such as a simple counter or a timestamp.
`  labels:
upgrade-version: "1616527520"`
Fixes VZ-1996
- [ …

Allow users to control when OAM application is upgraded to latest Verrazzano

---

examples/sock-shop/README.md
examples/springboot-app/README.md

Minor doc updates for issues called out during hackathon.
> The instructions provided in this doc link to the app through the browser is not accurate and has to be fixed. https://github.com/verrazzano/verrazzano/tree/master/examples/sock-shop
I had to add *.xip.io to the NO_PROXY list, get the host using this command (
$ HOST=$(kubectl get gateway -n sockshop -o jsonpath={.items[0].spec.servers[0].hosts[0]}))
and use the HOST to access the app in the browser. Ex: https://${HOST}/catalogue
> The instructions provided in this doc link to access the app through the browser is not accurate though and has to be fixed. https://github.com/verrazzano/verrazzano/tree/master/examples/springboot-app
I had to add *.xip.io to the NO_PROXY list, get the host using this command: ($ HOST=$(kubectl get …

Misc doc updates

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
application-operator/controllers/loggingscope/fluentd.go
application-operator/controllers/loggingscope/fluentd_test.go
application-operator/controllers/loggingscope/helidon.go
application-operator/controllers/loggingscope/helidon_test.go
application-operator/controllers/loggingscope/wls.go
application-operator/controllers/loggingscope/wls_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

When ca-bundle is empty, do not set ca_file is the fluentd conf.  It applies to the fluentd sidecar in helidon, wls, and coh apps.
Fixes VZ-2447

conditionally set ca_file in fluentd conf

---

Jenkinsfile
tests/e2e/pkg/kubernetes.go
tests/e2e/security/rbac/rbac_suite_test.go
tests/e2e/security/rbac/rbac_test.go

Create an Acceptance Test suite for RBAC based on new roles, verrazzano-project-admin and verrazzano-project-monitor.
Add helper functions CanI, CanIGroup where the api group is specified and CreateClusterRoleBinding
Verify that users with these rules can and cannot do what the roles grant

RBAC Acceptance Tests for new verrazzano cluster roles

---

tests/e2e/multicluster/examples/helidon/helidon_example_test.go

I noticed a few intermittent MC AT test failures in the hello-helidon example test because the beforeSuite setup was applying the MC component and app config YAML right after creating the VerrazzanoProject, and if the VP creation hasn't had time to create the namespace on the admin cluster, applying the components and app config can fail.
This PR adds a wait for the namespace to exist on the admin cluster before applying the YAML files.

MC test fix: Wait for namespace to exist on set up

---

Jenkinsfile
build/coverage.sh
platform-operator/controllers/clusters/vmc_controller_test.go

Fix VMC unit test failure and modify the coverage.sh script to report test failures in its exit status so that the Jenkins stage will fail on unit test failures

Fix VMC unit test failure and coverage.sh failure reporting

---

examples/hello-helidon/README.md
examples/sock-shop/README.md
examples/springboot-app/README.md
examples/todo-list/README.md
platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
platform-operator/apis/verrazzano/v1alpha1/zz_generated.deepcopy.go
platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/internal/vzinstance/verrazzano_instance.go
platform-operator/internal/vzinstance/verrazzano_instance_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go

Changes to allow for the removal of the verrazzano-monitoring-instance-api image completely from Verrazzano platform-operator/helm_config/charts/verrazzano/values.yaml.
- remove `verrazzano-monitoring-instance-api` image from helm_config `values.yaml`
- update VMO image
- remove System API URL from `verrazzano_types.go`
- remove systemApi from `crds/install.verrazzano.io_verrazzanos.yaml` and `verrazzano_instance.go`
- clean-up of README in examples to remove references to ingress `vmi-system-api`
- clean up test test cases
Fixes VZ-2452

Remove verrazzano-monitoring-instance-api image from Verrazzano 

---

ci/looping-test/Jenkinsfile
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/3-install-verrazzano.sh
platform-operator/scripts/install/config.sh
platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh

Resolve some lingering issues around install/uninstall
- Have install wait for pods in verrazzano-system to reach Ready state before looking for secrets
- Uninstall should be more resilient around Rancher `local` cluster object removal, and general not prevent the uninstall from continuing
- On uninstall, patch Rancher local cluster object to remove any dangling finalizers as a semi-hack to allow it to be deleted
- Do an `ensure-default-admin` with Rancher on install to avoid issues with resetting the password subsequently
- Honor `letsEncrypt` `environment` setting and use the ACME staging env URL when specified
- Updates for `verrazzano-install-loop` pipeline
Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another …

VZ-1343, VZ-2348.  Install/uninstall issues

---

ci/JenkinsfileBuildTrigger

This PR removes supplying VERRAZZANO_OPERATOR_IMAGE to the uninstall job.

Fix the jenkins job which triggers KIND AT and uninstall test

---

platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/scripts/install/config/keycloak.json

This PR includes the following:
- Pulls in the latest version of the verrazzano-monitoring-operator with support for VMI authorization and Grafana identity propagation
- Updates the Keycloak configuration to make the verrazzano-oauth-client public, adds console_user as a default realm role for users, and adds a mapper to the webui and verrazzano-oauth-client clients so that realm roles are included in the id_token
- Fixes a Lua script bug with user impersonation in the API proxy.
Implements VZ-2347

VZ-2347: More changes to support authorization in the VMI stack

---

application-operator/constants/constants.go
application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/values.yaml
platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml
platform-operator/scripts/install/3-install-verrazzano.sh

This pull request adds the network policies needed for the Coherence operator.
The network policies required are:
1. ingress from Kubernetes API server
2. egress to Kubernetes API server
3. egress to Coherence pods in application namespace
Fixes VZ-2479

Add network policies for the Coherence operator

---

platform-operator/scripts/install/config.sh

This change removes "set -o pipefail" from platform-operator/scripts/install/config.sh, where it is not necessary.

Remove set -o pipefail from functions, where it is not required

---

platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
tests/e2e/multicluster/examples/example_utils.go

More resiliency around Rancher install/uninstall
- Create rancher secret using apply, so re-runs of install are idempotent
- Add more checks around cleanup of 'local' cluster object prior to patching out the finalizers; may have been contributing to cluster instability on reinstalls
- Fix go fmt error in MC test code
Partially addresses VZ-2385.

VZ-2385 (Partial).  More resiliency around Rancher install and cleanup

---

ci/looping-test/Jenkinsfile

Update the install-loop Jenkinsfile to pull the latest master/operator.yaml, not one for a specific commit hash.

Use latest master operator.yaml, not one for a specific commit-hash

---

platform-operator/helm_config/overrides/mysql-values.yaml
platform-operator/scripts/install/4-install-keycloak.sh

Grant specific privileges instead of 'ALL', to the keycloak user on the keycloak database schema in MySQL. This required the following additional changes:
* Disabling the keycloak database as the default mysqlDatabase in the MySQL Helm chart overrides - otherwise, MySQL automatically created the database and the user specified in mysqlUser, and granted all privileges on the database to the user.
* Changing the intializationFiles key to have a ".sql" extension - otherwise MySQL does not execute the SQL at all - the only reason keycloak database was being created was because of the mysqlDatabase Helm chart setting which I removed as explained above.
Fixes VZ-2182

Grant specific privileges instead of 'ALL' for keycloak user in MySQL

---

tests/e2e/pkg/kubernetes.go

The `DoesNamespaceExist` test utility function fails hard if the namespace doesn't exist. Any "Eventually" calls that use this function will not retry. The fix is to add a check so the test does not fail if the namespace is not found.
Fixes VZ-2532

VZ-2532: Fix DoesNamespaceExist test function

---

application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
application-operator/test/integ/multi_cluster_test.go
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_exists.yaml

Do not log stack trace when a VerrazzanoProject resource is not found.
Add a test for deleting a VerrazzanoProject resource
Add a test for creating a VerrazzanoProject for an existing namespace, make sure the Verrazzano labels get applied.

Do not log stack trace when a VerrazzanoProject resource is deleted

---

platform-operator/scripts/install/4-install-keycloak.sh
tests/e2e/pkg/keycloak.go
tests/e2e/verify-install/keycloak/keycloak_suite_test.go
tests/e2e/verify-install/keycloak/keycloak_test.go

Adds Keycloak password policy for master and Verrazzano-system realm during install.
Fixes VZ-2498

VZ-2498: Enable a password policy.

---

tests/e2e/security/rbac/rbac_test.go

This change adds more test resiliency. There have been observed instances where the role binding was created but the access check immediately following fails.  The eventually around that check should eliminate this intermittent failure

Add eventually to rbac checks after rolebinding creation

---

platform-operator/controllers/verrazzano/installjob/install_config.go
platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/3-install-verrazzano.sh

This PR adds network policies for Rancher. Since we are not use many of Rancher's features, these policies are fairly restrictive. As we take advantage of more of Rancher's features in the future, we will likely need to relax these policies.
I tested by installing admin and managed clusters and validating that I could still register managed clusters and they show up properly in the Rancher UI. I also verified that I could inspect managed cluster events, services, etc. in the UI.
NOTE: We create the `cattle-system` namespace and network policy even if the `rancher.enabled` flag is false. That way when the user applies the managed cluster registration YAML at some point in the future, the network policy will already exist. 
Implements VZ-2482
Code reviewer, …

VZ-2482: Add Rancher network policies

---

platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml
platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml

Run verrazzano-api pod as non-root user. This required changing the default prefix path to a location that the nginx user has permissions to, and changing the permissions on some of the startup shell scripts, since those are owned by root. 
**Note**: I tried to fix fluentd to not run as root, but from what I can gather, it needs root permission to read /var/log. Found some info [here](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/420) and [here](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/)
Partially Fixes VZ-2504

Run verrazzano-api pod as non root user

---

examples/bobs-books/bobs-books-comp.yaml

Fixes VZ-2260. This is an issue reported by Fortify scan and the fix takes care of closing JDBC resources.  The fix has been merged to the examples repo. Here is the PR for VZ-2260: https://github.com/verrazzano/examples/pull/64.
Note: None of the items in the checklist is applicable to this change.

Change image

---

application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
examples/multicluster/README.md
platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
platform-operator/config/samples/install-managed-cluster.yaml
platform-operator/controllers/clusters/sync_prometheus.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/controllers/verrazzano/installjob/install_config.go
platform-operator/controllers/verrazzano/installjob/install_config_test.go
platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/scripts/create_managed_cluster_secret.sh
platform-operator/scripts/install/4-install-keycloak.sh
platform-operator/scripts/install/config.sh
platform-operator/scripts/install/install-overrides/config.dev.json
platform-operator/scripts/install/install-overrides/config.json
platform-operator/scripts/install/install-overrides/config.managed-cluster.json
platform-operator/scripts/install/install-overrides/config.prod.json
tests/e2e/config/scripts/register_managed_cluster.sh
tests/e2e/verify-infra/restapi/keycloak_url_test.go
tests/e2e/verify-infra/restapi/rancher_url_test.go
tests/e2e/verify-infra/restapi/vmi_urls_test.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/keycloak/keycloak_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go

1. VMO redeploy to update the OIDC sidecars, upon cluster registration changes.
2. managed cluster prometheus secret no longer includes password.
3. prometheus scraper uses admin verrazzano password
4. remove keycloak in managed-cluster profile
5. uptake VMO in which managed cluster prometheus re-routes auth requests to admin keycloak, proxy-body-size and reduced log
Fixes VZ-2357

 managed cluster uses admin keycloak for auth; remove keycloak from managed-cluster

---

platform-operator/helm_config/charts/verrazzano/templates/04-verrazzano-ingress.yaml

add security headers related annotations to verrazzano ingress. Adds all headers suggested by the [Oracle JET Developers Guide](https://docs.oracle.com/en/middleware/developer-tools/jet/10/develop/securing-oracle-jet-applications.html#GUID-D5B80E16-C323-4940-9605-C8B84B114FFA) and as well as the ones found in testing using [zap](https://www.zaproxy.org/)
Fixes VZ-2526

add security headers related annotations to verrazzano ingress

---

examples/bobs-books/bobs-books-comp.yaml

Fixes VZ-2258.  This is an issue reported by Fortify scan and the fix takes care of closing IO resources. The fix has been merged to the examples repo. Here is the PR for VZ-2258: verrazzano/examples#65
Note: None of the items in the checklist is applicable to this change.

Test vz-2258

---

platform-operator/scripts/install/2-install-system-components.sh

Recently some code was added to the install scripts to ensure that the default admin user is present during Rancher bootstrapping before trying to reset the password.  This PR tries to make that more resilient by adding retries around it to avoid any timing issues during the lookup.

Add retries around lookup of Rancher admin user

---

ci/multicluster/Jenkinsfile
platform-operator/helm_config/charts/verrazzano/templates/07-networkpolicy.yaml

Network Policy to allow MC agent to connect to admin cluster. Enable Calico by default on MC tests.
Fixes VZ-2550

Network Policy to allow MC agent to connect to admin cluster

---

tests/e2e/config/scripts/looping-test/types.txt

Remove CSRs from the resources being checked before/after, this is causing intermittent failures and we need to review whether that really makes sense to compare those for testing

Remove CSRs from the resource list that gets dumped and compared

---

application-operator/apis/clusters/v1alpha1/multicluster_common_types.go
application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/clusters/cluster_utils_test.go
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclusterapplicationconfigurations.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclustercomponents.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclusterconfigmaps.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclusterloggingscopes.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_multiclustersecrets.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/clusters.verrazzano.io_verrazzanoprojects.yaml

Add a message field to the ClusterLevelStatus reported back from managed clusters to the admin cluster.

Add message field to ClusterLevelStatus

---

application-operator/mcagent/mcagent.go
platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml
platform-operator/helm_config/charts/verrazzano/templates/09-vmi-es-networkpolicy.yaml

Change fluentd default elasticsearch endpoint to oidc:8775
Fixes VZ-2394

use oidc:8775

---

tests/e2e/config/scripts/create_kind_cluster.sh

Small tweak to fix the echo of which config yaml being used for kind and always echo it.

Fix echo of the kind config being used, always report it

---

ci/multicluster/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
tests/e2e/config/scripts/process_oci_dns_install_yaml.sh
tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/helidonconfig/helidon_config_test.go
tests/e2e/examples/todo/todo_list_test.go
tests/e2e/pkg/acme_ca_certs.go
tests/e2e/pkg/vmi.go
tests/e2e/pkg/web.go

Convert OCI DNS pipeline to use ACME staging environment by default.
- update test client to load ACME staging CA certs
- Update OCI DNS and MC ATs to use staging env for certs by default
- fix typo in getHTTPClientWithCABundle function name
- some go fmt updates for e2e tests

Use ACME staging env for tests using OCI DNS by default

---

tests/e2e/multicluster/examples/helidon/helidon_example_test.go

Disables the multi-cluster example Helidon logging tests.  This is intended to be temporary until the xip.io DNS resolution issues can be worked around.
Fixes VZ-2559

VZ-2559: Multi-cluster Example Helidon test instability. Disable tests

---

tests/e2e/config/scripts/register_managed_cluster.sh
tests/e2e/multicluster/verify-register/verify_register_test.go

disable multi-cluster system logging tests until xip.io issue is resolved.
Fixes VZ-2546

disable multi-cluster system logging tests

---

application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller_test.go
application-operator/controllers/clusters/multiclustercomponent/controller.go
application-operator/controllers/clusters/multiclustercomponent/controller_test.go
application-operator/controllers/clusters/multiclusterconfigmap/controller.go
application-operator/controllers/clusters/multiclusterconfigmap/controller_test.go
application-operator/controllers/clusters/multiclusterloggingscope/controller.go
application-operator/controllers/clusters/multiclusterloggingscope/controller_test.go
application-operator/controllers/clusters/multiclustersecret/controller.go
application-operator/controllers/clusters/multiclustersecret/controller_test.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go

Return errors from MC controllers when the create/update fails but the status update succeeds. Previously they were swallowing these errors and failing to requeue.
expected to fix VZ-2549 

Verify_Permissions potential fix

---

application-operator/test/integ/multi_cluster_test.go

Fixes the integ test failure in master - integ tests have a check for a string value in the condition message field which may no longer be there.

remove spurious check for condition msg in integ tests

---

ci/uninstall/Jenkinsfile

The OKE cluster name got too long in master, this is a quick interim solution to get master unblocked
We need a longer term solution see VZ-2573

Quick attempt to unblock the uninstall test

---

application-operator/controllers/webhooks/appconfig_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go
application-operator/controllers/webhooks/testdata/hello-conf-deleting.yaml

Currently, the default logging scope is deleted but then recreated with empty workload reference on app configuration delete. This change provides the fix such that its not recreated.
Fixes VZ-2407

Delete default logging scope on app configuration delete

---

application-operator/controllers/clusters/cluster_utils.go
application-operator/controllers/clusters/cluster_utils_test.go
tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
tests/e2e/multicluster/examples/example_utils.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go
tests/e2e/pkg/kubernetes.go

Potential fix for MC change placement test failure - does the following things:
* Changes the Helidon and ChangePlacement example tests to explicitly delete apps in managed cluster and wait for namespace deletion to complete before proceeding
* Changes the finalizer removal logic for MC resources to remove the finalizer _after_ deleting the underlying resource
* Re-enables the disabled previously failing assertions in Change Placement test
* Only perform a cluster dump for the 2 examples e2e tests if they fail
Partially fixes VZ-2559

Potential fix for MC change placement test failure

---

.gitignore
ci/oke-ocidns/Jenkinsfile
platform-operator/scripts/install/2-install-system-components.sh
tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/examples/todo/todo_list_test.go
tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/security/rbac/rbac_test.go

Update timeout for Springboot tests, add test-specific cluster dumps on failure.
- fix ingress-nginx service TTL annotation for external-dns
- add cluster-dump on failure to tests
- update .gitignore to ignore ginkgo generated ".test" files
Fixes VZ-2572

Update timeout for Springboot tests, add test-specific cluster dumps on failure.

---

ci/multicluster/Jenkinsfile
platform-operator/scripts/install/config.sh

This PR fixes the jq error, complaining about non-existing effective.config.json when config.sh reads the value from CONFIG_JSON from function validate_config_json() before the step which generates "effective.config.json" and during undeploy.
As part of this change, the Jenkinsfile used by multi-cluster test is updated to archive the install and uninstall logs.
Fixes VZ-2564

Fix jq error complaining about non-existing effective.config.json in install/uninstall logs

---

ci/uninstall/Jenkinsfile

This change captures the cluster dumps and output of helm list -A after install, uninstall and re-install, from the uninstall CI pipeline. The default value for DUMP_K8S_CLUSTER_ON_SUCCESS is set to true, will be reverted once the uninstall job becomes stable. The intention is to get more information when one of these stages fail in the pipeline.

Capture cluster dump and helm releases on install, uninstall and re-install

---

platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml
platform-operator/scripts/install/3-install-verrazzano.sh

Adds network policies to limit ingress and egress in the Keycloak namespace.
Implements VZ-2486

VZ-2486: Add network policies for Keycloak

---

ci/oke-ocidns/Jenkinsfile
tests/e2e/config/scripts/create_oke_cluster.sh
tests/e2e/config/scripts/setup_ssh_tunnel.sh
tests/e2e/config/scripts/terraform/cluster/create-cluster.sh
tests/e2e/config/scripts/terraform/cluster/main.tf
tests/e2e/config/scripts/terraform/cluster/variables.tf

Install and run Verrazzano in an OKE cluster that is in a VCN that is not internet accessible (no Internet gateway) and has private workers and private endpoints.
- add cluster_access variable to terraform files
- update oci-dns Jenkinsfile 
- create OKE cluster with private endpoints
-  add`--cap-add=NET_ADMIN` to `RUNNER_DOCKER_ARGS` (required for sshuttle)
- set oci-oke terraform option `TF_VAR_cluster_access=private` to create cluster with private endpoint
- set oci-oke terraform option `TF_VAR_bastion_enabled=true` to create bastion host
- create script to setup ssh tunnel through bastion host
- install sshuttle for ssh tunnel through bastion host
- get the VCN CIDR and bastion host public IP
- run sshuttle in background
Fixes VZ-VZ-2453
Code …

OKE With Private Endpoints

---

platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml

nginx reload should use correct prefix path

nginx reload should use correct prefix path

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go
platform-operator/helm_config/charts/verrazzano/templates/04-verrazzano-ingress.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/scripts/install/3-install-verrazzano.sh

This pull request removes the harding of wildcard domain checks and instead reads an annotation to get the wildcard domain.  This allows the code to be generic and work with any wildcard DNS provider.
This is a follow on pull request from a post merge comment from @gilbode.
Tested with OCI DNS, xio,io and nip.io.

Remove hardcoding checks of wildcard domains xio.io, nip.io, and sslip.io

---

tests/e2e/config/scripts/terraform/cluster/multi_cluster_main_tf_template
tests/e2e/multicluster/verify-register/verify_register_test.go

Fixes the multi-cluster test Terraform that didn't get updated with the Terraform version upgrade. As a result, the Terraform failed creating OKE clusters. Also cleaned up a couple of deprecation warnings.
**NOTE**: After fixing the Terraform, the pipeline was able to get further, but one of the "verify register" tests failed repeatedly. It appears to be a problem with filebeats on OKE clusters. Filebeats and Journalbeats are going away though (@shihchang has this in progress), so I just marked the test pending since it will be removed very soon.
Fixes VZ-2576

VZ-2576: Fix bad multi-cluster test Terraform

---

platform-operator/scripts/install/4-install-keycloak.sh

There was a single failure of the OCI DNS acceptance test run that showed a failure installing Keycloak during the Verrazzano install. Looking at the installation logs and cluster dump info it appears that the helm install of Keycloak timed out waiting for pods, services, etc. to become ready. The MySQL pod shows ready but the Keycloak pod was still initializing when helm timed out.
This PR bumps the helm timeout from 5 minutes to 10 minutes (we use 10m in other helm install commands). Will leave the ticket open and watch the builds to see if the problem occurs again.
Fixes VZ-2579

VZ-2579: Keycloak installation failure

---

tests/e2e/pkg/web.go

disable custom DNS resolver for wildcard domain in acceptance tests.
Fixes VZ-2589

disable custom DNS resolver for wildcard domain in acceptance tests

---

ci/oke-ocidns/Jenkinsfile
tests/e2e/config/scripts/create_oke_cluster.sh

Keep the OKE cluster on failure for post-mortem analysis for VZ-2591.

Keep OKE cluster on failure in OCI DNS tests

---

ci/oke-ocidns/Jenkinsfile

There are image pull failures observed multiple times in ap-mumbai-1 and sa-saopaulo-1 region and tests failing due to that. Removing the region from oci dns
Fixes VZ-9999

remove ap-mumbai-1 and sa-saopaulo-1 from oci dns test

---

ci/scripts/install_calico.sh

This change loads all the .tar files from ${CALICO_HOME}/${CALICO_VERSION}/images in a loop, rather than loading individual tar files.

Load calico images in a loop

---

tools/scripts/k8s-dump-cluster.sh

Have the cluster dump create the entire output directory path not just the specific directory for the dump.

Have it create the entire path for the directory if it needs to

---

ci/oke-ocidns/Jenkinsfile
tests/e2e/config/scripts/setup_ssh_tunnel.sh

- Fix problem of creating an OKE cluster for oke-ocidns test run.  The script that sets up an ssh tunnel to the OKE cluster was obtaining the incorrect public IP address.
- Re-enable the sao-paulo region for tests
Fixes VZ-2591

Fix enable to connect to the server: x509: certificate signed by unknown authority

---

tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go

Fixes intermittent tests failures caused by misuse of the gomega.Eventually utility.
Fixes VZ-2620: grafana endpoint test failing with http 407 in vmi_test

VZ-2620: grafana endpoint test failing with http 407 in vmi_test

---

ci/oke-ocidns/Jenkinsfile
tests/e2e/config/scripts/oci_dns_ops.sh

This PR changes the acceptance tests that use OCI DNS to use a new DNS zone (v8o.io).
Contributes to VZ-2612

swap dns zone to v8o.io

---

tests/e2e/ingress/console/console_ingress_test.go
tests/testdata/ingress/console/application.yaml
tests/testdata/ingress/console/components.yaml
tools/scripts/k8s-dump-cluster.sh

Fix console-ingress tests to not use the same domain UID as the ToDo examples tests
- Also add OAM components and ACME cert orders to the cluster dumps
Fixes VZ-9999

Fix duplicate domain UID in the console-ingress tests

---

Jenkinsfile
ci/kind/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/rolebased/Jenkinsfile
ci/scripts/download_calico.sh
ci/scripts/install_calico.sh
platform-operator/helm_config/charts/verrazzano/templates/07-networkpolicy.yaml
platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml
platform-operator/internal/netpolicy/netpolicy.go
tests/e2e/config/scripts/create_oke_cluster.sh
tests/e2e/config/scripts/create_oke_multi_cluster.sh
tests/e2e/config/scripts/install_calico_oke.sh

This PR adds support for installing Calico on OKE when running OKE tests.
Notes:
- The OKE documentation for Calico recommends installing Calico in the cluster before the node pool is created. I'm doing it this way in the script that creates the OKE cluster and it seems to solve the issues with coredns pods restarting and getting into a bad state.
- For some reason I can't explain, the network policy for webhook ingress was causing problems with our operator webhooks. Removing the source IP from the rule and just specifying the 9443 ingress port solved the problem. I don't think we saw this problem with Kind, so not sure what's going on, but this seems like a reasonable solution (at least for now).
- The `create_oke_cluster.sh` script was using an optional arg to setup the cluster with …

VZ-2484: Add support for Calico on OKE

---

platform-operator/controllers/verrazzano/installjob/install_config.go
platform-operator/controllers/verrazzano/installjob/install_config_test.go

Change the default wildcard DNS from xip.io to nip.io
Fixes VZ-2626

WVZ-2626: Change default wildcard DNS from xip.io to nip.io

---

Jenkinsfile

The commit authors that we get back from the changeSets when in master behave differently than for other branches. We are seeing "noreply" as the user there.
This does a few things:
1. Directly call git to get the commit author information, this doesn't rely on what the plugin gives us in changeSets
2. Look further back to the changes since the last clean build. This way the suspect list includes everyone who has a commit while master is broken if multiple runs have failed in a row.
3. Add more debugging. Unfortunately as we have seen with the previous attempt master doesn't behave the same way as branches, so it is possible that this will not work on master as well and if that is the case we at least will have more debug to look at.
Code reviewer, please …

Suspect notifications Part Deux

---

tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/pkg/kubernetes.go
tests/e2e/security/rbac/rbac_test.go

Remove some premature Fail in acceptance tests.
For example, instead of Fail, we want to return false in case of IsNotFound when getting a resource.  So, Eventually block in tests would have a chance to come back later to retry.

Remove premature Fail in acceptance tests

---

Jenkinsfile
ci/looping-test/Jenkinsfile

The install loop test pipeline, unless overridden through a parameter, tries to download the latest `operator.yaml` file from ObjectStore based on the most recent commit hash for the branch it's running off of (typically `master`).
However,  depending on when the file download and Verrazzano install occurs on the loop test pipeline, it may result in trying to pull an operator.yaml from ObjectStore before the image has been built and pushed.  This will cause the image pull errors in the cluster for the operator.
The solution is:
- Move the`Update operator.yaml` stage in the master build that pushes the operator.yaml to ObjectStore to run after the `Build` stage to ensure the `branch-name/operator.yaml` file always contains an image that has been successfully pushed
- In the loop-install …

Use branch name to download operator.yaml from OS

---

application-operator/Makefile
application-operator/README.md

Fixes a few build issues w application operator
make run fails even though KUBECONFIG is valued in the env
make install-crds fails because the oam crds aren't installed
The readme pointed at the wrong script

Fix Build target issues

---

application-operator/Makefile
application-operator/constants/constants.go
application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/webhooks/appconfig_defaulter.go
application-operator/controllers/webhooks/appconfig_defaulter_test.go
application-operator/controllers/webhooks/istio_defaulter_test.go
application-operator/controllers/webhooks/logging_scope_defaulter.go
application-operator/controllers/webhooks/logging_scope_defaulter_test.go
application-operator/controllers/webhooks/net_policy_defaulter.go
application-operator/controllers/webhooks/net_policy_defaulter_test.go
application-operator/main.go
platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml

This PR adds ingress network policies for things running in the `istio-system` namespace. There are static policies that get created at Verrazzano install time (in `08-thirdparty-networkpolicy.yaml`) as well as dynamic policies created by the Verrazzano Application Operator by the app config mutating webhook. The dynamic policies allow the Istio proxy sidecars in pods in the application namespaces to talk to iostiod.
**Notes**:
- I ran into intermittent problems labeling the application namespace because other things were updating the namespace at the same time. This resulted in sporadic "the resource has already been updated, please retry..." errors that resulted in test failures. I added retries around labeling the namespace to handle that case.
- The application operator integration …

VZ-2542: Add network policies for Istio

---

platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml

Allow Rancher to talk to Kubernetes API server.   This fixes errors seen in the AT logs.  Also, allow Rancher to communicate with other pods in the Rancher namespace.  We can see from the logs that it is attempting to do that.
From. the logs, this is the new policy
Name:         rancher
Namespace:    cattle-system
Created on:   2021-05-07 19:09:03 +0000 UTC
Labels:       <none>
Annotations:  <none>
Spec:
PodSelector:     app=rancher
Allowing ingress traffic:
To Port: <any> (traffic allowed to all ports)
From:
NamespaceSelector: verrazzano.io/namespace=cattle-system
----------
To Port: 80/TCP
From:
NamespaceSelector: verrazzano.io/namespace=ingress-nginx
From:
PodSelector: app.kubernetes.io/instance=ingress-controller
Allowing egress traffic:
To Port: <any> (traffic allowed to all ports) …

Add rancher egress to api server and ingress/egress to cattle-system

---

examples/todo-list/todo-list-components.yaml
tests/testdata/ingress/console/components.yaml

Not sure it's related to the transient issues we see with the to-do list app, but this will get rid of the JDBC driver deprecation warnings in the tests/examples:
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary. 

VZ-2584.  Change the MySQL driver to the non-deprecated one

---

Jenkinsfile
platform-operator/helm_config/charts/verrazzano/templates/07-networkpolicy.yaml
tests/e2e/multicluster/verify-install/defaultresource_test.go
tests/e2e/pkg/kubernetes.go
tests/e2e/security/network-policies/network_policy_suite_test.go
tests/e2e/security/network-policies/network_policy_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go
tests/testdata/security/network-policies/netpol-test.yaml

Add automated tests for the layer 3/4 network security policies. 
For the expected set of network policies...
- examine each ingress rule
- from a pod specified in the ingress rule attempt to connect to the policy's pod on the specified port(s) and verify connection
- from a pod NOT specified in the ingress rule attempt to connect to the policy's pod on the specified port(s) and verify that connection can not be established
- examine each egress rule
- from the policy's pod attempt to connect to a pod specified in the egress rule on the specified port(s) and verify connection
- from the policy's pod attempt to connect to a pod NOT specified in the egress rule on the specified port(s) and verify that connection can not be established
Fixes VZ-2561
Code …

Automated tests for network security policies

---

platform-operator/helm_config/charts/verrazzano/templates/03-verrazzano-monitoring-operator.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

This pull request picks up new images for verrazzano-monitoring-operator and verrazzano-operator.
Fixes for VZ-2455 and VZ-2418

Pickup new images for VMO and VO

---

THIRD_PARTY_LICENSES.txt
go.mod
tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/helidonconfig/helidon_config_test.go
tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/examples/todo/todo_list_test.go

Removes the use of the avast/go-retry modules in tests.
Related to fix for VZ-2548: Uninstall test failing intermittently with internal error in todo list test

VZ-2548: Uninstall test failing intermittently with internal error in todo list test

---

Jenkinsfile

Add bare formatted noreply user match for slack notifications, seeing that with some users.

Add bare formatted no-reply user match

---

tests/e2e/pkg/common.go

Change to fix a typo in tests/e2e/pkg/common.go.

Fix a typo in tests/e2e/pkg/common.go

---

examples/bobs-books/bobs-books-comp.yaml
examples/todo-list/todo-list-components.yaml

Add or update retry/timeout settings to JDBC CP for WLS examples (Bob's Books, and ToDo-List).
- Seems like the failures we've been seeing intermittently are due to a temporarily dropped connection during MySQL/adminServer startup, and the pool doesn't recover
- Bob's Books already had some settings, which tends to not have this failure whereas the tests based on the ToDo example do
- Align the settings across both examples
Fixes VZ-2584

VZ-2584.  Add retry/test settings to JDBC CP for Bob's Books and ToDo examples

---

platform-operator/scripts/install/4-install-keycloak.sh
platform-operator/scripts/install/config.sh

A message has been added to the messages printed at the end of an installation indicating to the user that the OCI DNS secret can be removed post-installation (if the user indicate the use of OCI DNS)
Fixes VZ-2425

JIRA:VZ-2425 Add message indicating ability to remove OCI DNS secret post-installation

---

application-operator/Makefile
application-operator/apis/clusters/v1alpha1/verrazzanoproject_webhook.go
application-operator/apis/clusters/v1alpha1/verrazzanoproject_webhook_test.go
application-operator/test/integ/multi_cluster_test.go
application-operator/test/integ/testdata/multi-cluster/verrazzanoproject_namespace_override_labels.yaml
tests/e2e/multicluster/verify-permissions/verify_permissions_test.go
tests/e2e/pkg/kubernetes.go

VerrazzanoProject validation needs to disallow two projects having the same namespace
Added unit tests
fixed up integ tests
add fix for a race in AT support code
- [ x] Added or updated unit tests for any new functions I added
- [ x] Added or updated integration tests if appropriate

validation to disallow two projects having the same namespace

---

application-operator/constants/constants.go
application-operator/controllers/webhooks/istio_defaulter.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
pkg/string/slice.go
pkg/string/slice_test.go
platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml
platform-operator/helm_config/overrides/istio-values.yaml
platform-operator/helm_config/overrides/weblogic-values.yaml
platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl

This PR has changes to put the WebLogic Operator in the Istio mesh and configure it to have access to WebLogic applications in the mesh.  This is needed so that the operator can make admin REST calls to the WebLogic applications in the mesh.  When this is working correctly, the domain status is correctly updated, for example:
servers:
- desiredState: RUNNING
health:
activationTime: "2021-05-18T18:23:49.440000Z"
overallHealth: ok
When it was NOT working (the bug), the overallHealth is [not available]
The following changes were made:
1. Remove weblogic-operator from the istio sidecar config neverInjectSelector. 
2. Add the excludeOutbound port annotation to the weblogic operator so that it can access the API server
3. Add the WebLogic operator service account to the list of principals in …

Put WebLogic operator into the Istio Mesh

---

ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/uninstall/Jenkinsfile

In OCI container engine, Linux Images for Gen2-GPU shapes are added to node pool image list and they don’t work with VM standard shapes.

default VM.Standard.E3.Flex-8-2 for OKE nodepool

---

ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/uninstall/Jenkinsfile

We will revert the default back to v19.7 once there is a real solution.

default k8s to v1.18.10

---

ci/oke-ocidns/Jenkinsfile

Disable keepig OKE cluster on failure

Disable OCI DNS keeping clusters around on failure

---

platform-operator/helm_config/charts/verrazzano/templates/03-verrazzano-monitoring-operator.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

Instead of cert issued by cert-manager, VMO uses self-signed cert for liveness probe.
Fixes VZ-2667

VMO uses self-signed cert for liveness

---

examples/bobs-books/README.md

In Bobs Books README, make it easier to copy/paste commands for secret creation by replacing `<username>` and `<password>` with env vars except in one place.

In Bobs Books README, make it easier to copy/paste commands

---

examples/bobs-books/README.md

Add missing "/" to the end of the bobbys-front-end URLs.  The omission of the slash is resulting in a redirect to a URL that contains the trailing "/", however, the redirect is going to "http" instead of "https".  The redirect to http is a separate issue that may need to be resolved.

Add missing slash to bobbys-front-end urls

---

platform-operator/scripts/install/2-install-system-components.sh

When CA is the cert issuer type and the default secret is used, set "privateCA=true" when installing rancher.
If customers provide ca secret in verrrazzano install CR, skip "privateCA=true" since we have no idea whether or not their CA is private.

rancher set privateCA when using CA cert issuer

---

application-operator/controllers/webhooks/metrics_trait_defaulter.go
application-operator/controllers/webhooks/metrics_trait_defaulter_test.go
application-operator/deploy/traitdefinition_ingresstrait.yaml
application-operator/deploy/traitdefinition_metricstrait.yaml
application-operator/deploy/verrazzano.yaml_template
application-operator/main.go
platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_traitdefinition_ingresstrait.yaml
platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_traitdefinition_metricstrait.yaml

The Application operator creates a default metrics trait for configmap, which causes metricstrait  reconcile to fail. 
The metrics trait defaulter should only add default metrics traits to components with workload types listed in the appliesToWorkloads field of the trait definition.  
- Add all of the wrapper workload types to the metrics trait definition.
- In metrics trait defaulter, check that workload kind is in appliesToWorkloads set before adding a default metrics trait.
- Add tests case for workload kind not in appliesToWorkloads.
Fixes VZ-2397

Application operator creates a default metrics trait for configmap

---

platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/controller_test.go

Explicitly pre-create the Verrazzano system namespace before kicking off install, so that sync_local_registration_secret does not have failures due to missing namespace.
Refactored the verrazzano controller_test to reduce duplication of the similar mocks in several tests.
Fixes VZ-2404

Explicitly pre-create the Verrazzano system namespace

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go

add e2e test to assert that "pattern not matched" in WLS fluentd sidecar logs is fixed
Fixes VZ-2673

test WLS pattern-matched log records

---

platform-operator/Makefile
tools/scripts/generate_operator_yaml.sh

This PR fixes a problem introduced by the new bill of materials-based installation. The developer `make create-test-deploy` scenario resulted in an operator.yaml that when applied, failed to install the Verrazzano Application Operator.
The fix is to add a `--set` argument to the `helm template` command that sets the helm value to override the application operator image. I searched through the makefiles and jenkinsfiles to make sure this only gets applied when building locally, and as best I can tell, that is the case.

Fix operator.yaml generation in local builds

---

platform-operator/helm_config/charts/verrazzano/templates/02-verrazzano-logging.yaml
tests/e2e/verify-infra/vmi/vmi_test.go

Remove the systemd source which is without path and defaults to /var/log/journal
* /var/log/journal may be missing on some instances without persistent systemd journal causing repeated warnings of "Systemd::JournalError: No such file or directory"
* /var/log/journal may contains old systemd journal
Fixes VZ-2646

systemd journal fix

---

platform-operator/verrazzano-bom.json
tests/e2e/pkg/acme_ca_certs.go
tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/web.go

Use cert-manager-controller, cert-manager-webhook, and cert-manager-cainjector images built from the Verrazzano forked repo to pick up support for OCI DNS added there.
Fixes VZ-2722

VZ-2722.  Use webhook and cainjector images built from source

---

tests/e2e/config/scripts/create_kind_cluster.sh

This pull request adds some logging during the "Prepare AT Environment" stage to help diagnose a failure seen creating a Kind cluster
Fixes VZ-2725

Add some logging to help diagnose Kind create cluster failure

---

tests/e2e/pkg/web.go

Fix CA handling in the e2e test client to account for both the self-signed and ACME staging scenarios.
Additional test fix for VZ-2722

Fix test client to accommodate ACME staging and self-signed scenarios

---

ci/uninstall/Jenkinsfile

Add a dump of the verrazzano cluster when the verify uninstall stage fails.  Currently if that stage fails, the dump does not occur until after the reinstall stage runs, so it is not dumping the actual failed environment.
Fixes VZ-2724

Add cluster dump when verify uninstall stage fails

---

tests/e2e/pkg/web.go

While investigating a different build issue, I found a few failures due to calling `Fail()` from a function that makes HTTP requests. It looks like this code path fails occasionally and results in a panic, and the `Fail()` also prevents retries. The fix is to return an error and let the test code retry.

Test fix, remove Fail() call

---

tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/web.go

A recent change regressed the hello-helidon multicluster test.  An underlying function was obtaining the default kubeconfig for a system instead of the specific kubeconfig for the cluster being tested.
Fixes VZ-2741

Fix regression in hello-helidon multicluster test

---

Makefile
platform-operator/Makefile
tools/scripts/generate_operator_yaml.sh

This PR fixes two build-related issues with the generated `operator.yaml` file:
1. A build issue discovered by @mgianatagh. When doing a MC AT run using "build with parameters", if you specify a platform operator image to use, the build would fail with an "unbound variable" shell script error. The `generate_operator_yaml.sh` script uses `set -u` and in this case the `APP_OPERATOR_IMAGE` optional env var was not set. The fix is to default the value to empty before testing the variable.
2. The developer case when running `make create-test-deploy` was broken. I had tested that previously and it worked, but I must have had an environment variable set. The fix is to pass the correct environment variable so the application operator image is correctly overridden in the generated operator.yaml. …

Build fixes for operator.yaml generation

---

ci/multicluster/Jenkinsfile

The multi-cluster pipeline attempts to capture the install log, after uninstall, resulting in an empty file. This PR fixes that.

Capture install logs before uninstall in the multi-cluster pipeline

---

ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
tests/e2e/config/scripts/oci_dns_ops.sh

This PR includes two changes to OCI DNS zone creation:
1. Increase the random zone string length from 3 characters to 6 characters
2. If zone creation fails, attempt to fetch the zone details, which should tell us if the zone already exists and when it was created
Does not resolve VZ-2743 but hopefully will provide more information the next time we see a failure creating a zone.

VZ-2743: Updates for OCI DNS zone creation in automation pipeline

---

platform-operator/scripts/install/4-install-keycloak.sh

This change disables the network logs from Kubernetes when the Verrazzano installer configures Keycloak realms using kubectl exec, by unsetting the environment variable DEBUG. The variable is set back to original value after the kubectl exec call is over.

Disable network logs from Kubernetes while configuring Keycloak realms

---

platform-operator/scripts/install/2-install-system-components.sh

Update the `cert-manger` `ClusterIssuer` and `Issuer` objects to `v1` from `v1alpha1`.

Update Issuer and ClusterIssuer objects to v1

---

ci/multicluster/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
platform-operator/helm_config/charts/verrazzano/templates/06-verrazzano-api.yaml
platform-operator/scripts/create_managed_cluster_secret.sh
tests/e2e/config/scripts/register_managed_cluster.sh
tools/scripts/k8s-dump-cluster.sh

Fixes behavior change in CM 1.2 by marking the `ca.crt` secret mount optional, as CM no longer creates an empty `ca.crt` field in the cert secret in the case where no CA is provided when the `ClusterIssuer` is created.
Also
* Fix the `platform-operator/scripts/create_managed_cluster_secret.sh` and `tests/e2e/config/scripts/register_managed_cluster.sh` scripts to handle the case where `ca.crt` is not present in the secret
* Fix Multicluster pipeline OCI DNS/ACME configurations
* Remove a duplicate ACME_ENVIRONMENT parameter from the OCI DNS Jenkinsfile
* Add Mutating/Validating webhooks to cluster dump script
Note that there is still an issue with managed cluster registration in the OCI-DNS/ACME configuration, which we will resolve through a subsequent PR.
Fixes VZ-2737
As the author of …

VZ-2737.  Make ca.crt TLS secret field mount optional in the verrazzano-api deployment

---

platform-operator/helm_config/charts/verrazzano/templates/08-thirdparty-networkpolicy.yaml

We have been getting intermittent "no such host" errors in the OCI DNS tests (mostly the Springboot and Lift & Shift example tests). The root cause is a failure to invoke the istiod webhook when the Verrazzano Application Operator attempts to create an ingress gateway for the app. The webhook failure prevents external DNS from adding the A record.
We have seen odd behavior in other build pipeline failures due to the istiod webhook, and we suspected the webhook port in the istiod network policy was wrong but we couldn't explain why it worked most of the time. This PR changes the istiod webhook port from 443 to 15017. Port 15017 is the advertised port for webhook communication to the istiod pod.
With this change, I have had many clean OCI DNS test runs and have not seen the "no such host" …

Fix webhook port in istiod network policy

---

tests/e2e/istio/authz/authpolicy_test.go

Minor test enhancement to not fail immediately inside an `Eventually` block. If we encounter any transient network issues we want to retry, so just log the error and continue.

Test enhancement, remove gingko.Fail inside Eventually

---

ci/looping-test/Jenkinsfile

Increase the install-loop test timeout to 120 min, to prevent aborting a run due to extended test retries.  The aborts seem to be preventing cleanup also, and preventing capturing relevant diagnostic data.

Bump install loop test timeout to prevent aborts

---

tests/e2e/examples/springboot/springboot_test.go
tests/e2e/istio/authz/authpolicy_test.go

There are two tests that called `gomega.Expect` inside of an `Eventually` block. Calling `Expect` inside `Eventually` fails immediately if the conditions aren't met, which means the block is never retried. This could be why we saw intermittent failures in these tests.
I ran a few different tests and confirmed that failed expectations cause the tests to fail without retrying, and I also validated that the `Eventually` blocks work as expected after removing the `Expect` calls.
Fixes VZ-2579

Remove gomega.Expect calls from inside Eventually

---

ci/multicluster/Jenkinsfile
platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/clusters/sync_registration_secret.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/scripts/create_managed_cluster_secret.sh
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/config.sh
tests/e2e/config/scripts/register_managed_cluster.sh

Fix multicluster registration when using OKE with OCI DNS and LetsEncrypt staging or production envs
- also, update AT pipeline to skip tests when install or mgd cluster registration fails
- Use the flag "privateCA=true" and create a "tls-ca" secret with the ACME staging CAs to allow the remote cattle-agent to talk to Rancher when it's installed with an ACME staging cert
- Update platform operator to use the "tls-ca" secret to load any additional CAs instead of "tls-rancher-ingress", for Rancher interaction and generation of the managed cluster secrets.  This should work across both the self-signed and ACME staging scenarios.
- Update `platform-operator/scripts/create_managed_cluster_secret.sh` and `tests/e2e/config/scripts/register_managed_cluster.sh` to add the ACME staging CA bundle …

Fix Rancher managed cluster registration with OCI DNS+ACME

---

tests/e2e/verify-infra/restapi/vmi_urls_test.go

This PR fixes a test that was incorrectly using Expect inside a function, and which was thereby short-circuiting test retries.

fix bad test

---

Jenkinsfile

The Jenkins file for the default build pipeline has reached a limit where no more stages can be added.  Adding a new stage results in the pipeline immediate failing with this error:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during class generation: Method code too large!
This is due to a limit between Java and Groovy, requiring that method bytecode be no larger than 64kb. There is an outstanding bug for this issue. We did some experimentation and found that by moving portions of the code executed for a stage into a function will work around this issue. This task is to change some of our stages to call functions to perform the steps to create additional head room for adding new stages.
Fixes VZ-2858
Code …

Updated Jenkinsfile to work around method code too large issue

---

application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go
application-operator/controllers/webhooks/metrics_trait_defaulter.go
application-operator/controllers/webhooks/metrics_trait_defaulter_test.go
application-operator/main.go
tests/e2e/examples/bobsbooks/bobs_books_test.go

Fixes an issue where the default metrics traits do not always get created.  The check that was being done in the webhook metrics trait defaulter relied on getting the workload kind from each component.  It is possible that the app config can exist and the webhook called before the components are created.  In this case the check failed and the default metrics traits were not created.
Since it is not possible to do a reliable check in the webhook, this change checks to see if the metric type is a supported kind in the metrics trait reconciler.  If it is not then the trait is deleted.
- Added unit test for above scenario.  
- Changed order of app config / component in bobs books acceptance test to create the conditions above. 
Fixes VZ-2848
Code reviewer, …

Default metrics traits sometimes not injected into appconfig

---

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go

This pull request includes new code to create the runtimeEncryptionSecret secret specified in the WebLogic domain spec, if the secret does not already exist.  The secret is created with a random password.  This change removes the need for this secret to be created before deploying the application.  If the application operator creates the secret then this secret will also be deleted when the application is deleted.

Create the runtimeEncryptionSecret secret specified in domain spec

---

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml
tests/e2e/security/network-policies/network_policy_test.go

There are 3 problems:
1) The node exporter network policy has the wrong target label. 
It has this
```
podSelector:
matchLabels:
verrazzano.io/namespace: monitoring
```
Should be this
```
podSelector:
matchLabels:
app: node-exporter
```
2) This error was found in an egress test, which we should not be testing anymore since we allow all egress. Those egress tests need to be removed.
3) We are missing a node exporter ingress test, that needs to be added.
Fixes VZ-2841

Network Policies Test oam-kubernetes-runtime egress rules failed

---

ci/JenkinsfilePeriodicTests

Add an OCI DNS run with ACME/staging configuration for certificate management
- near term solution until we can come up with a less-expensive form of integration testing this

Add OCI DNS run with ACME/staging params

---

image-patch-operator/main.go

Changed logging structure used in main.go of the Image Patch Operator to follow the application and platform operator.
Fixes VZ-2868

Changed logging structure in Image Patch Operator

---

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
examples/bobs-books/bobs-books-comp.yaml
tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go
tests/testdata/ingress/console/application.yaml
tests/testdata/ingress/console/components.yaml

- Add the default monitoringExporter to the weblogic domain spec if it is not specified.
- Add sample monitoringExporter to the domain specs in bobs-books example.
Fixes VZ-2706

add default monitoringExporter to wls domain spec.

---

application-operator/Dockerfile
image-patch-operator/Dockerfile
platform-operator/Dockerfile

Fix name of third party license file on our docker images.  It was being copied as the name "licenses" instead of "THIRD_PARTY_LICENSES.txt"
Fixes VZ-9999

Fix name of license file that we copy to the docker images

---

ci/uninstall/Jenkinsfile

This change captures the cluster dump on test failure after verrazzano reinstall, in the uninstall pipeline.

Capture cluster dump on test failure after verrazzano reinstall, in uninstall pipeline

---

tests/e2e/examples/todo/todo_list_test.go
tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/metrics/syscomponents/metrics_test.go
tests/e2e/multicluster/verify-api/verify_api_test.go
tests/e2e/multicluster/verify-install/defaultresource_test.go
tests/e2e/multicluster/verify-permissions/verify_permissions_test.go
tests/e2e/multicluster/verify-register/verify_register_test.go
tests/e2e/pkg/api.go
tests/e2e/pkg/common.go
tests/e2e/pkg/environment.go
tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/logging.go
tests/e2e/pkg/secrets.go
tests/e2e/pkg/vmi/elastic.go
tests/e2e/pkg/web.go
tests/e2e/scripts/install/install_test.go
tests/e2e/security/rbac/rbac_test.go
tests/e2e/verify-infra/restapi/keycloak_url_test.go
tests/e2e/verify-infra/restapi/rancher_url_test.go
tests/e2e/verify-infra/restapi/vmi_urls_test.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/istio/istio_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go
tests/e2e/verify-install/verrazzano/verrazzano_test.go

This PR removes most of the `gomega.Fail` calls from the shared acceptance test code. I analyzed the shared test code to find assertions, expectations, and `Fail` calls that might prevent tests from retrying operations. Previous rounds of test fixes have removed all of the `gomega.Expect` calls, so I only needed to remove `gomega.Fail`.
Note that I did leave in some `gomega.Fail` calls, particularly for operations that will never succeed no matter how many times they are retried. For example, loading a kubeconfig, fetching a clientset, and passing a bad log level to the `Log` function.
I have additional tasks for more improvements to the tests, refactoring to eliminate duplication and confusing code, wrap operations in Eventually where needed, etc. That work will be done in future PRs. …

VZ-2898: Remove most gomega.Fail calls from shared acceptance test code

---

Jenkinsfile
ci/kind/Jenkinsfile

Change the default build pipeline to trigger the Kind acceptance test suite pipeline instead of running them embedded.  
This is being done because the declarative pipeline code had reached the limit of 64k for building a method.  We had tried to reduce the size of the method by separating some of the scripts into "def" functions.  However, that approach did not create much headroom for making further additions to the Jenkinsfile.  Instead, the decision was to split the acceptance tests out of the build pipeline which should reduce the method built considerably.  We already use another pipeline, named verrazzano-new-kind-acceptance-tests, that replicates most of the acceptance test suite that was being run by default.
Fixes VZ-2930
Code reviewer, please …

Run acceptance tests as a triggered job

---

platform-operator/scripts/install/config.sh
tests/testdata/install-configurations/install-managed-cluster-default-volume-override.yaml
tests/testdata/install-configurations/install-managed-cluster-emptydir-default.yaml

Allow empty values for helm overrides, to allow `emptyDir` volumeSource overrides with non-dev profiles to work.
At present, the VZ install prunes out helm overrides specified by the user in the CR if the values are empty (e.g., `name=`).  However, to allow the `defaultVolumeSource` to override the default VMI settings for any given profile, we need to set storage values equivalent to the empty string to tell the VMI to not allocate a PVC for a particular component, e.g.,
"verrazzanoInstallArgs": [
{
"name": "elasticSearch.nodes.data.requests.storage",
"value": "",
"setString": true
},
{
"name": "grafana.requests.storage",
"value": "",
"setString": true
},
{
"name": "prometheus.requests.storage",
"value": "",
"setString": true
}
]
Fixes VZ-2938
Code …

Allow empty values for helm overrides in config.json

---

platform-operator/scripts/install/4-install-keycloak.sh
tests/testdata/install-configurations/install-dev-custom-monitoring-keycloak.yaml

Added a `dev` profile example that
* Disables prometheus and Grafana
* Uses custom storage for Keycloak
This example surfaced a bug in the install scripts with this configuration, the fix is included in the MR also.

Installation examples, and fix Keycloak install when Prometheus disabled.

---

ci/kind/Jenkinsfile

Temporarily remove the console UI tests so that the yum install of Chrome is not being called.  This is to alleviate the builds that are hanging due to a race condition between the stages.
Fixes VZ-9999

Temporarily remove the console UI tests

---

ci/looping-test/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/uninstall/Jenkinsfile
platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh
platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
platform-operator/scripts/uninstall/uninstall-utils.sh
tests/e2e/config/scripts/looping-test/dump_cluster.sh
tests/e2e/config/scripts/looping-test/get_resources.sh

Made changes to Verrazzano uninstall so that application resources are only deleted if they are in a namespace which is managed by Verrazzano. Namespaces indicate that they are Verrazzano managed via a namespace label: "verrazzano-managed=true". Additionally, no application CRD's are deleted regardless of namespace.
Fixes VZ-2872
- [ x] Added or updated unit tests for any new functions I added
- [x ] Added or updated integration tests if appropriate
- [x ] Added or updated acceptance tests if appropriate

During uninstall, only delete application resources from namespaces which are managed by Verrazzano

---

.gitignore
Jenkinsfile
Makefile
image-patch-operator/weblogic-imagetool/Dockerfile
image-patch-operator/weblogic-imagetool/Makefile
image-patch-operator/weblogic-imagetool/README.md
image-patch-operator/weblogic-imagetool/installers/.gitkeep
image-patch-operator/weblogic-imagetool/installers/fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip.download
image-patch-operator/weblogic-imagetool/installers/jdk-8u291-linux-x64.tar.gz.download
image-patch-operator/weblogic-imagetool/installers/weblogic-deploy.zip.download
tools/copyright/copyright.go

These changes add the Docker image running WIT to the Jenkins pipeline. Does not run the clairScan on the image as a temporary measure.
Fixes VZ-2819

Mgelleca/vz-2819-2 - Add build of WIT Docker Image

---

tests/e2e/multicluster/examples/helidon-ns-ops/helidon_example_delete_ns_test.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go
tests/e2e/multicluster/verify-api/verify_api_test.go
tests/e2e/multicluster/verify-install/defaultresource_test.go
tests/e2e/multicluster/verify-permissions/verify_permissions_test.go
tests/e2e/multicluster/verify-register/verify_register_test.go
tests/e2e/multicluster/verify-resources/verify_resources_test.go

This PR improves the multi-cluster acceptance tests by:
1. Adding `Eventually` around calls that should be retried
2. Removing `Expect` calls inside `Eventually`
3. Use dot imports for gomega and ginkgo
Additional acceptance tests will be improved in subsequent PRs.
Implements VZ-2909

VZ-2909: Multi-cluster acceptance test improvements

---

platform-operator/controllers/verrazzano/component/app_operator.go
platform-operator/controllers/verrazzano/component/app_operator_test.go
platform-operator/controllers/verrazzano/component/registry.go

The APP_OPERATOR_IMAGE is used to override the application operator image when using a dev build, but isn't being honored for the upgrade scenario.  This change addresses that; if set, the app operator helm upgrade is appended with an image override for that value.
This mimics what we do at install time in the scripts.

Honor APP_OPERATOR_IMAGE override during upgrade if present

---

platform-operator/controllers/verrazzano/component/app_operator.go
platform-operator/controllers/verrazzano/component/app_operator_test.go
platform-operator/controllers/verrazzano/component/registry.go

This reverts commit 69ed3968ec6a0805c6753d363f317a5a1f00c99d.
(revert of a revert)

Re-merge fix to honor APP_OPERATOR_IMAGE override during upgrade

---

tests/e2e/ingress/console/console_ingress_test.go
tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/logging/helidon/helidon_logging_test.go
tests/e2e/metrics/deploymetrics/deploymetrics_test.go
tests/e2e/metrics/syscomponents/metrics_test.go
tests/e2e/registry/registry_test.go
tests/e2e/scripts/install/install_test.go

This PR improves more of the acceptance tests by:
1. Adding `Eventually` around calls that should be retried
2. Removing `Expect` and `Fail` calls inside `Eventually`
3. Use dot imports for gomega and ginkgo
Note that I put all of the dot import changes into a single commit to make it easier to review the other changes.
Additional acceptance tests will be improved in one last PR.
Implements VZ-2909

VZ-2909: More acceptance test improvements

---

tests/e2e/pkg/web.go
tests/e2e/security/netpol/network_policy_test.go
tests/e2e/security/rbac/rbac_test.go
tests/e2e/verify-infra/oam/oam_test.go
tests/e2e/verify-infra/restapi/keycloak_url_test.go
tests/e2e/verify-infra/restapi/rancher_url_test.go
tests/e2e/verify-infra/restapi/vmi_urls_test.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/istio/istio_test.go
tests/e2e/verify-install/keycloak/keycloak_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go
tests/e2e/verify-install/verrazzano/verrazzano_test.go
tests/e2e/verify-install/web/web_test.go

This PR improves the remaining acceptance tests by:
1. Adding `Eventually` around calls that should be retried
2. Removing `Expect` and `Fail` calls inside `Eventually`
3. Use dot imports for gomega and ginkgo
Note that I put all of the dot import changes into a single commit to make it easier to review the other changes.
This is the final PR for this work to improve the acceptance tests.
Implements VZ-2909

VZ-2909: Improve remaining acceptance tests

---

ci/JenkinsfilePeriodicTests

There is a chicken & egg problem with the periodic triggered tests and the private registry tests. The private registry tests install from the last good tarball generated by the periodic tests, but the periodic tests fail because the private registry tests fail. They are running tests from master and require a matching platform operator.
This PR temporarily disables the private reg tests so we can get a good tarball published, and then we will re-enable the tests. This is a stop-gap solution until we can fix this issue longer term.
Fixes VZ-3013

VZ-3013: Temporarily disable priv reg tests

---

ci/JenkinsfilePeriodicTests

Reverts verrazzano/verrazzano#1345
The periodic tests ran successfully and published a new install tarball, so we can revert the change which will re-enable the private registry tests.

Revert "VZ-3013: Temporarily disable priv reg tests"

---

Jenkinsfile
ci/JenkinsfilePeriodicTests
ci/kind/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/oke-ocidns/Jenkinsfile

The timestamps allow for better correlation with other logs and metrics to diagnose issues.
Helps with VZ-2954
An image of what the build logs look like with this enabled:

JIRA:VZ-2954 add timestamps to jenkins build logs

---

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
platform-operator/config/samples/install-optional.yaml
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/installjob/install_config.go
platform-operator/controllers/verrazzano/installjob/install_config_test.go
platform-operator/helm_config/charts/verrazzano/templates/networkpolicy.yaml
platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml
platform-operator/internal/vzinstance/verrazzano_instance.go
platform-operator/internal/vzinstance/verrazzano_instance_test.go
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/config.sh
platform-operator/scripts/install/install-overrides/config.dev.json
platform-operator/scripts/install/install-overrides/config.json
platform-operator/scripts/install/install-overrides/config.managed-cluster.json
platform-operator/scripts/install/install-overrides/config.prod.json

This pull request contains a number of fixes for the Verrazzano install.  The fixes include:
1. The optional install of Keycloak now works when disabling the component in the vz resource
2. The optional install of Rancher now works when disabling the component in the vz resource
3. The optional install of Elasticsearch now works when disabling the component in the vz resource
4. Network policies were being installed if component was disabled. This has been fixed.
Fixes VZ-3010

Fixes for installing optional components

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml

Fixes VZ-9999
VZ-2912 added  content-type to access-control-allow-headers

VZ-2912 added  content-type to access-control-allow-headers

---

tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/security/netpol/network_policy_test.go

This PR updates two acceptance tests:
1. Sock shop intermittently fails in `AfterSuite` because the sockshop namespace is not deleting properly. I added calls to delete the test resources, which should not make a difference, but all of the other tests clean up resources they create so I made this consistent. I also added a cluster dump when the namespace doesn't delete, so hopefully when this problem occurs the cluster dump will give us more to go on.
2. The network policy test, when testing access from one pod to another, had two issues:
- When expecting pod-to-pod access to work, it was only running the check once. A transient network issue could make the check fail, so I wrapped it in `Eventually`.
- When expecting pod-to-pod access to NOT work, again it was only doing the check once. …

Acceptance test fixes

---

platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
platform-operator/verrazzano-bom.json

Update verrazzano-bom to use Rancher 2.5.9. Also update additional_rancher images in the bom file for private registry install. Fix uninstall to clean up additional rolebindings and mutating webhook added in this version of Rancher.
Fixes VZ-3085

Update to use Rancher 2.5.9

---

platform-operator/scripts/install/2-install-system-components.sh

Add --timeout to the certificate manager helm install command.
Fixes VZ-3102

VZ-3102: Set helm upgrade timeout during install

---

Jenkinsfile
Makefile
THIRD_PARTY_LICENSES.txt
go.mod
tools/eventually-checker/README.md
tools/eventually-checker/check_eventually.go
tools/eventually-checker/check_eventually_test.go
tools/eventually-checker/test/internal/helper.go
tools/eventually-checker/test/main.go

This PR introduces the acceptance test Eventually checker into the build. The checker looks for `Fail` and `Expect` calls that can result in an `Eventually` exiting prematurely.
**NOTE**: The checker is currently configured in report mode, so it displays problems but it does not exit with a non-zero code, thus it will not gate the build. Once we have cleaned up all of the existing complaints, we can remove the "-report" flag and the build will be gated on the check.
@markxnelson I'm not exactly sure that my updates to the third party license file are correct. I didn't expect the addition of golang.org/x/mod but I left it in. Let me know if I need to fix anything in there.
Implements VZ-3093

VZ-3093: Initial commit of acceptance test Eventually checker tool

---

Jenkinsfile

One of the master runs failed because the eventually checker unit tests failed. The failure happened in one of four runs. I'm temporarily disabling the checker in Jenkins until I can figure out why the unit tests failed, but the tool can still be run manually.

Disable eventually checker until unit test failure is fixed

---

Jenkinsfile
tools/eventually-checker/check_eventually_test.go

Fixed a bug in the Eventually checker unit tests. The `TestDisplayResults` test needed to clear the two state maps. The results from the previous scan were still in the maps and the file position numbers were relative to a previous token.FileSet, causing the files/lines to be incorrectly displayed.
I fixed this by clearing the maps before running the test. I have also re-enabled the checker in the Jenkinsfile.

Fix eventually checker unit test bug, re-enable checker in Jenkinsfile

---

tests/e2e/pkg/logging.go

Change to default the log level header string instead of calling `ginkgo.Fail`. This cleans up a bunch of linter complaints.

Default log level header instead of calling ginkgo.Fail

---

platform-operator/helm_config/overrides/coherence-values.yaml
platform-operator/thirdparty/charts/coherence-operator/Chart.yaml
platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml
platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml
platform-operator/thirdparty/charts/coherence-operator/values.yaml
platform-operator/verrazzano-bom.json

Upgrade Coherence Operator to 3.2.0. The changes:
- Update the Coherence Operator image tag in the bill of materials file
- Update the Coherence Operator helm chart
Note that the copyright headers in the helm files do not include 2021. They are incorrect in the Coherence Operator github repo. I have let that team know and they will fix them.
Fixes VZ-3122

VZ-3122: Upgrade Coherence Operator to 3.2.0

---

Jenkinsfile
tests/e2e/config/scripts/create_ocir_repositories.sh

Update product tarball/Zip generation for upload to PLS for release
- Create a Zip that combines the image tarball, the commit-file, and the checksum file
- Use a versioned name for the tarball and Zip
- Also generate the tarball in `release*` branches
- Adds a fix for the private registry test to always mark the VPO OCIR repository as public during the test run
Fixes VZ-2141

Use versioned name for Verrazzano tarball generation, generate automatically on release builds

---

pkg/proxy/auth_lua_template.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml

Handle well-known managed cluster CA in api proxy lua code when proxying requests to managed cluster. Based on Ravi's branch with some additional fixes, so that UI does not show an error in an OCI DNS multicluster environment with applications deployed.
Fixes VZ-3092

Handle well-known managed cluster CA in api proxy

---

platform-operator/helm_config/overrides/coherence-values.yaml
platform-operator/thirdparty/charts/coherence-operator/Chart.yaml
platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml
platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml
platform-operator/thirdparty/charts/coherence-operator/values.yaml
platform-operator/verrazzano-bom.json

This pull request updates the Coherence Operator helm chart to 3.2.1.  Previously, we had tried 3.2.0 but with that version the  helm upgrade from 3.1.5 failed. 3.2.1 fixes the helm upgrade from 3.1.5.
Fixes VZ-3122

Update coh operator to 3.2.1

---

image-patch-operator/README.md
image-patch-operator/controllers/imagebuildrequest_controller_test.go
image-patch-operator/controllers/imagejob/job.go
image-patch-operator/helm_config/charts/image-patch-operator/templates/persistentvolume.yaml
image-patch-operator/helm_config/charts/image-patch-operator/templates/persistentvolumeclaim.yaml
image-patch-operator/helm_config/charts/image-patch-operator/values.yaml
image-patch-operator/weblogic-imagetool/Dockerfile
image-patch-operator/weblogic-imagetool/Makefile
image-patch-operator/weblogic-imagetool/v8o-imagetool.sh

The initial POC of the verrazzano-weblogic-image-tool image has the installers built into the image. With this change, the image build job will now access the installers from a mounted volume at runtime.
Fixes VZ-3114

Persistent Volume hosts installers for weblogic-image tool

---

image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
image-patch-operator/helm_config/charts/image-patch-operator/crds/images.verrazzano.io_imagebuildrequests.yaml

Added parameters for LatestPSU and RecommendedPatches to ImageBuildRequest CRD. These are features supported by WIT: LatestPSU - Find and apply the latest PatchSet Update, RecommendedPatches - Find and apply the latest PatchSet Update and recommended patches (this takes precedence over latestPSU).
Fixes VZ-3186

Added parameters for LatestPSU and RecommendedPatches to ImageBuildRequest CRD

---

image-patch-operator/README.md
image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
image-patch-operator/controllers/imagebuildrequest_controller.go
image-patch-operator/controllers/imagebuildrequest_controller_test.go
image-patch-operator/controllers/imagejob/job.go
image-patch-operator/helm_config/charts/image-patch-operator/templates/deployment.yaml
image-patch-operator/helm_config/charts/image-patch-operator/values.yaml
image-patch-operator/main.go
image-patch-operator/weblogic-imagetool/v8o-imagetool.sh

With this change, the user may now specify if they would like to run the image job as a DryRun. Setting the DryRun flag to true will cause WIT to print the Dockerfile to stdout instead of building the image.
Fixes VZ-3115

Added support for DryRun feature of WIT

---

image-patch-operator/controllers/imagebuildrequest_controller_test.go
image-patch-operator/controllers/imagejob/job.go
image-patch-operator/test/templates/imagebuildrequest_instance.yaml

The image job gets passed parameters for LatestPSU and RecommendedPatches options. Added unit tests to verify this functionality.
Fixes VZ-3188

ImagePatchOperator supports LatestPSU and RecommendedPatches parameters

---

Makefile
tools/eventually-checker/check_eventually.go
tools/eventually-checker/test/main.go

This PR fixes a bug in the Eventually linter that resulted in false positives. The problem occurred when the parser encountered generic decls after a function decl, and the calls inside the generic decl were incorrectly associated with the previous function decl. For example:
```
func foo() {
...
}
var _ = Describe("Tests", func() {
It("aSpec", func() {
Expect(...)
})
})
```
Prior to the fix, the `Expect` was incorrectly associated with the `foo` function.
To fix the bug, I first added a generic decl to the test `main.go` and reproduced the false positive. The fix is to keep track of the token end position of the current function decl. Once the parser encounters a node after that end position, it resets the current func decl name and end position. Then we only record the function calls …

Eventually linter bug fix and enable build gate

---

ci/upgrade/Jenkinsfile
platform-operator/internal/util/helm/helmcli.go

The upgrade test was failing for 2 reasons:
1) The helm upgrade command intermittently fails.   Use a retry loop to fix this.
2) Use the BOM version for the upgrade target, instead of the verrazzano-development-version file.  This is because, the BOM version has a version suffix that is appended during each build.  During upgrade, the version field that we put in the Verrazzano CR must match that BOM version.

Fix upgrade test

---

image-patch-operator/controllers/imagebuildrequest_controller.go
image-patch-operator/controllers/imagebuildrequest_controller_test.go
image-patch-operator/controllers/imagejob/job.go
image-patch-operator/helm_config/charts/image-patch-operator/templates/deployment.yaml
image-patch-operator/helm_config/charts/image-patch-operator/values.yaml
image-patch-operator/internal/k8s/job.go
image-patch-operator/weblogic-imagetool/v8o-imagetool.sh

Image Patch Service.
Includes the `--fromImage` parameter to specify the base image in the call to `imagetool create`.
Adds resource limits and requests to the Pod running the Image Tool in order for this to work. Values for the resource limits and requests are specified as Helm values.
Fixes VZ-3185

Pass base image to Image Tool

---

pkg/proxy/auth_lua_template.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml

Return specific messages with errors, so that nginx doesn't default to sending server name/version.
Ensure all error returns use wrappers that say the messages.
Fixes VZ-2996

VZ-2996: nginx bug

---

tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/pkg/common.go
tests/e2e/verify-infra/vmi/vmi_test.go

There is a common `PodsNotRunning` function that checks to make sure pods with specific prefixes are not running in a namespace. That function could fail with no retries.
I fixed the `PodsNotRunning` function to:
1. Return an error in addition to the boolean
2. Remove the loop with sleep
I also changed the tests that call that function to use Eventually. Now the call will be retried if it returns an error or if it returns `false`.
Fixes VZ-3266

VZ-3266: Acceptance test fix to use Eventually around PodsNotRunning

---

ci/oke-ocidns/Jenkinsfile

set default value of jenkins parameter to true to enable calico in oci dns tests
Fixes VZ-9999

set default value of jenkins parameter to true to enable calico in oci dns tests

---

Jenkinsfile
ci/JenkinsfilePeriodicTests
ci/private-registry/Jenkinsfile
ci/scripts/generate_product_zip.sh
ci/scripts/update_periodic_on_success.sh

This updates the main Jenkins run, periodic tests, and private registry tests to use the new Zip format for PLS
* Always run the Zip generation and private registry tests from the main build in `release-*` branches, or when `GENERATE_TARBALL==true`
* Refactors the tarball/Zip generation into a shared script between the periodic tests and main Jenkins run 
* Updates the periodic tests to do the Zip generation and private registry test run to validate that zip in a separate stage after the main test runs
* Also adds a checksum-check of the expanded tarball before testing
Fixes VZ-3144.

VZ-3144.  Update private registry tests, run automatically from release branches

---

platform-operator/verrazzano-bom.json

Uptake console version to render MC apps even if not on managed cluster
Fixes VZ-3155

Uptake console version to render MC apps even if not on managed cluster

---

application-operator/constants/constants.go
application-operator/controllers/logging/fluentd.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
pkg/proxy/nginx_conf_template.go
pkg/proxy/startup_sh_template.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
platform-operator/verrazzano-bom.json
tests/e2e/config/scripts/terraform/cluster/multi_cluster_main_tf_template

- Pick up VMO changes that resolve issue of admin cluster being able scrape metrics from a managed cluster when using well known certs.
- Fix issue of managed cluster being able to send logs to the admin cluster when using well known certs
- Updated unit tests to handle cases of ca-bundle being present and being empty
- Copied over Lua changes for new VMO and regenerated the helm chart
Fixes VZ-3125

Include updated VMO images and fix issue of logs and metrics not being collected for MC when using OCIDNS

---

platform-operator/scripts/install/2-install-system-components.sh

Adding a timestamp to the txtOwner fields to ensure specific record ownership for a given installation.  This will hopefully prevent the overwriting of DNS records by a cluster with the same env name in the same DNS zone.
Fixes VZ-3324

JIRA:VZ-3324 make txt owner unique for external dns installation

---

platform-operator/Dockerfile
tools/analysis/Dockerfile
tools/scripts/vz-registry-image-helper.sh

* Update kubectl version to 1.20.6-2 to fix the security vulnerability
* Update the kubectl version in the Dockerfile used by analysis tool
* Fix the comment, to address the review comment
* Remove adding olcne11 to the repo
Backport fix of kubectl version update to 1.20.6.-2.
Fixes VZ-3357

Update kubectl version to 1.20.6-2

---

examples/multicluster/todo-list/todo-list-components.yaml

This is a cherry-pick of ea4133d0ea281075275fadd6beaa27815289a8d9 into release-1.0.  This commit fixes a ToDo List MC bug where the MySQL URL had the wrong namespace name.

Backport ea4133d0ea281075275fadd6beaa27815289a8d9 to release-1.0

---

platform-operator/scripts/install/2-install-system-components.sh
platform-operator/verrazzano-bom.json

This PR upgrades the versions of external-dns and cert-manager in the Verrazzano bill of materials file. Those images contain a bug fix for parsing private keys used in OCI. With this fix, Verrazzano now accepts PKCS1 and PKCS8 keys for making OCI API calls.
There is also another related fix in this PR that was needed to make this work. The Rancher installation was broken when using LetsEncrypt due to a recent change to add `-wait` to the helm install of Rancher. The secret containing additional CA certs needed by Rancher was being created after the helm install of Rancher. That happened to work when we were not waiting on the Rancher install, but now that we do wait, it was broken. The fix was to move the secret creation before the helm install.
Fixes VZ-3235
As the author of this PR, I …

VZ-3235: Upgrade versions of external-dns and cert-manager images

---

platform-operator/verrazzano-bom.json

Backport of VZ-3235 fix to the 1.0 release branch.
Fixes VZ-3235

VZ-3235: Upgrade versions of external-dns and cert-manager images (1.0 release branch)

---

platform-operator/scripts/uninstall/uninstall-steps/1-uninstall-istio.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh

- added code to remove the cainjector ConfigMap
- moved code removing istio configmaps prior to helm repo deletion to ensure the code is executed regardless of any helm related issues
Fixes VZ-3023

JIRA:VZ-3023 (release-1.0 back port) ensure configmaps are deleted during uninstall (#1436)

---

platform-operator/helm_config/overrides/istio-values.yaml

- Currently the HPA components running enabled in some istio components are generating a large number of warnings due to the inability to query for certain pod runtime metrics (no metrics server running in the cluster)
- Since we are not currently using the HPA this PR disables it to prevent the generation of these messages in the event log, elastic search, etc.
Fixes VZ-3314

JIRA:VZ-3314 disable horizontal pod autoscaler to eliminate continuous warning messages from istio components

---

ci/JenkinsfilePeriodicTests

Remove redundant call to update_perodic_on_success.sh in post-run steps.  This is done in the `Private Registry` stage now.

Remove redundant call to update_perodic_on_success.sh in post-run steps

---

platform-operator/verrazzano-bom.json

Backport: Uptake Console 1.0.1 fixes into Verrazzano helm chart (From VZ-3155)

Backport: Uptake Console 1.0.1 fixes for VZ-3155 into Verrazzano helm chart

---

platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/component/helm_component.go
platform-operator/controllers/verrazzano/component/registry.go
platform-operator/controllers/verrazzano/component/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano_test.go

This pull request fixes the upgrade on a managed cluster when moving to v1.0.1. 
The problem was that the daemonset for fluentd contains a couple of environment variables that are defined as "value" in the helm template.  However, on the managed cluster, the registration process changes those variables to be "valueFrom" in order to obtain the values from the cluster registration secret.  The upgrade was failing because this difference.
Fixes VZ-3378

Fix upgrade of fluentd daemonset on a managed cluster

---

application-operator/constants/constants.go
application-operator/controllers/logging/fluentd.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
pkg/proxy/nginx_conf_template.go
pkg/proxy/startup_sh_template.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
platform-operator/verrazzano-bom.json

Backport the fix for VZ-3125 (logs and metrics not working for multicluster when configured with OCIDNS)
Fixes VZ-3125

Backport fix for VZ-3125 to release-1.0 branch

---

platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/component/helm_component.go
platform-operator/controllers/verrazzano/component/registry.go
platform-operator/controllers/verrazzano/component/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano_test.go

This pull request contains the backport to v1.0.1 for fixing the upgrade of the fluentd daemonset on a managed cluster.
This pull request fixes the upgrade on a managed cluster when moving to v1.0.1.
The problem was that the daemonset for fluentd contains a couple of environment variables that are defined as "value" in the helm template. However, on the managed cluster, the registration process changes those variables to be "valueFrom" in order to obtain the values from the cluster registration secret. The upgrade was failing because this difference.
Fixes VZ-3378

Backport: Fix upgrade of fluentd daemonset on a managed cluster (#1462)

---

make/quality.mk

Adds a "linter" to "make check" to look for forbidden/bad words. Fails build if any target words are detected or if curl command does return status=200. The list of words can be updated by modifying the file in object store.
Changes were validated by placing "bad words" in different files at various directory levels to ensure the build failed when the words were present.
Fixes VZ-3280

VZ-3280. Internal word linter

---

ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/private-registry/Jenkinsfile
ci/rolebased/Jenkinsfile
ci/uninstall/Jenkinsfile
ci/upgrade/Jenkinsfile
platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/installjob/clusterrolebinding.go
platform-operator/controllers/verrazzano/installjob/clusterrolebinding_test.go
platform-operator/controllers/verrazzano/sync_local_registration_secret.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_test.go
platform-operator/main.go
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/4-install-keycloak.sh
platform-operator/scripts/install/create_oci_config_secret.sh
tests/e2e/config/scripts/create-test-oci-config-secret.sh

Move the following resources to the verrazzano-install namespace from the default namespace
- service account
- config map
- install/uninstall jobs
- install/uninstall pods
- OCI secret (created by user)
In addition
- Cleanup old resources in default namespace from previous install
- Fix Jenkins files to look in verrazzano-install for the pod logs
- This includes Bhat's OCI DNS secret change from  pabhat/oci-secret-vz-nsg (required for this change)
I tried to use a RoleBinding instead of a ClusterRoleBinding but got an error since our install gets nodes, which is cluster level. Also, I had to add a different type of watch for jobs, since the VZ CR no longer owns the jobs because they are in a different namespace.

Move install jobs, pods, service accounts, oci secret to verrazzano-install

---

ci/kind/Jenkinsfile

Jenkins - try to enable debug logging for api proxy and ingress controller, only if the pods are present

Jenkins - try to enable debug logging for api proxy and ingress controller, only if the pods are present

---

platform-operator/internal/util/helm/helmcli.go

Force a `--wait` on helm upgrade commands during a VZ upgrade.

Force --wait on helm upgrade commands

---

platform-operator/helm_config/overrides/coherence-values.yaml
platform-operator/thirdparty/charts/coherence-operator/Chart.yaml
platform-operator/thirdparty/charts/coherence-operator/LICENSE.txt
platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml
platform-operator/thirdparty/charts/coherence-operator/values.yaml
platform-operator/verrazzano-bom.json

Uptake Coherence operator v.3.2.2. As part of this change, verrazzano-operator version is updated to get the Coherence dashboards from v.3.2.2.
Fixes VZ-3482

Update coherence operator to v3.2.2

---

Jenkinsfile

This backports the release-1.* pattern for getting notifications on the release branch build failures

Add release-1.* pattern for notifications (#1524)

---

Jenkinsfile
ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/uninstall/Jenkinsfile
ci/upgrade/Jenkinsfile

Renamed label "number" to "jenkins_build_number" in metrics published from CI pipeline. Also added a new label build_number, to get the metrics in the order in which they are published (that is also order by the label indicating the build number). Without this change, when the X-axis displays the metrics in Series mode in a Grafana panel, the data will be sorted based on the Git commit id. This is nothing but the order in which the Prometheus query returns the result, sorts by the label in the order. With the introduction of the new label "build_number" (which comes before label commit_sha), the result of the prometheus query will be sorted in the order of build number.
The value for the label indicating the status is changed to the first character of the ${currentBuild.currentResult} so …

Add a label to provide an incremental build number with trailing zeroes, to the metrics from CI pipeline

---

examples/bobs-books/bobs-books-app.yaml

This change fixes the once broken link to the `/books` path in the Bob's Books Order Manager application.
Fixes VZ-2231

Fix ingress rule for Bob's Books Order Manager

---

platform-operator/controllers/verrazzano/component/component.go
platform-operator/controllers/verrazzano/component/helm_component.go
platform-operator/controllers/verrazzano/component/helm_component_test.go
platform-operator/controllers/verrazzano/component/image_pull_secret.go
platform-operator/controllers/verrazzano/component/image_pull_secret_test.go
platform-operator/controllers/verrazzano/component/istio.go
platform-operator/controllers/verrazzano/component/registry.go
platform-operator/controllers/verrazzano/component/registry_test.go
platform-operator/controllers/verrazzano/component/weblogic_operator.go
platform-operator/controllers/verrazzano/component/weblogic_operator_test.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/install.go
platform-operator/internal/helm/helmcli.go
platform-operator/internal/helm/helmcli_test.go
platform-operator/internal/k8s/status/deployment_ready.go
platform-operator/internal/k8s/status/deployment_ready_test.go
platform-operator/scripts/install/3-install-verrazzano.sh

Move the WKO install to the platform operator.
- Added hooks for pre-install fn for a `helmComponent`, and added a WKO impl to set up the pre-reqs for that service
- Added the ability to declare dependencies between components in the registry, and validate that those dependencies are `Ready` before allowing install
- Declared dependency on Istio from WKO, and added Istio ready check fn
- Add the correct labels to the `verrazzano-system` namespace
- Added/updated the unit tests
Fixes VZ-3240.

VZ-3420. Move WKO install to platform operator.

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

When upgrading from 1.0 where elasticsearchURL and elasticsearchSecret are absent, value.yaml won't be fed to helm command either, we need to default them in the logging helm template.

default elasticsearchURL and elasticsearchSecret in logging helm

---

platform-operator/scripts/install/2-install-system-components.sh

This pull request fixes a failure of the cattle-cluster-agent on a manged cluster to connect to Rancher on the admin cluster.  The result of the failure was a crashloopbackoff of the cattle-cluster-agent pod.  The failure was intermittent and was caused by a bug in the install scripts.  The install scripts were creating the tls-ca secret n the cattle-system namespace with an empty cacerts.pem value.  The cacerts.pem value comes from the cert-manager secret verrazzano-ca-certificate-secret.  The install script was changed to wait for the cert-manager secret verrazzano-ca-certificate-secret before setting the tls-ca secret.
Fixes VZ-3329

VZ-3329 cattle-cluster-agent failure to connect to Rancher on the admin cluster

---

ci/ticket-commits/JenkinsfileCommits
ci/ticket-commits/JenkinsfilePullRequests

This back-ports the Jira/Git automation Jenkinsfiles to the 1.0 release branch. Since these aren't on the 1.0 release branch the jobs don't run and PRs and commits aren't recorded for activity on that branch.
Implements VZ-3301

VZ-3301: Jenkinsfiles for Jira/Git automation (release 1.0 branch)

---

platform-operator/helm_config/overrides/istio-values.yaml

Disable Istio pod disruption budget(pdb) to allow node upgrade or draining without violating pdb. 
To upgrade worker nodes, istio pdb and following default rolling policy would require scaling up istiod, istiocoredns, and istio-ingressgateway to 4 replicas:
```
autoscaleMin: 1
rollingMaxUnavailable: 25%
```
In order to drain the worker nodes the istio pods are scheduled on, the istio deployments must be scaled up to 4 replicas to satisfy disruption budget so that one (25%) of the 4 replicas can be evicted.
Fixes VZ-3310

istio disruption budget

---

application-operator/controllers/webhooks/multicluster_validation.go
application-operator/controllers/webhooks/multicluster_validation_test.go
application-operator/controllers/webhooks/multiclusterapplicationconfiguration_webhook.go
application-operator/controllers/webhooks/multiclusterapplicationconfiguration_webhook_test.go
application-operator/controllers/webhooks/multiclustercomponent_webhook.go
application-operator/controllers/webhooks/multiclustercomponent_webhook_test.go
application-operator/controllers/webhooks/multiclusterconfigmap_webhook.go
application-operator/controllers/webhooks/multiclusterconfigmap_webhook_test.go
application-operator/controllers/webhooks/multiclustersecret_webhook.go
application-operator/controllers/webhooks/multiclustersecret_webhook_test.go
application-operator/test/integ/multi_cluster_test.go

This pull request validates that the namespace of a Mcxxx resource is specified in a VerrazzanoProject resource.
The validation is via a validating webhook and addresses:
- MultiClusterApplicationConfigurations
- MultiClusterComponents
- MultiClusterConfigMaps
- MultiClusterSecrets

VZ-2522 Disallow Mcxxxx resources that are not in a VerrazzanoProject

---

ci/scripts/dashboard/main/main.go

Include labels to indicate the status of the test status and the build number with trailing zeroes to get the metrics in the ascending order from the Prometheus in Grafana dashboard.

Update test metrics to include label for test status

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml

Console API calls will rely on the session/session cookie for authN once the console changes are in, but the session won't be available to the authproxy in the remote cluster. To avoid the cost of re-authenticating and acquiring tokens on the managed cluster side, pass the ID token as a bearer token.

Add authorization header when making managed cluster api call

---

platform-operator/controllers/verrazzano/component/istio_component_test.go

Fix a unit test build error caused by overlapping changes.

VZ-3422. Fix build error caused by overlapping change

---

ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/private-registry/Jenkinsfile
ci/rolebased/Jenkinsfile
ci/uninstall/Jenkinsfile
ci/upgrade/Jenkinsfile
platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/installjob/clusterrolebinding.go
platform-operator/controllers/verrazzano/installjob/clusterrolebinding_test.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_test.go
platform-operator/main.go
platform-operator/scripts/install/2-install-system-components.sh
platform-operator/scripts/install/4-install-keycloak.sh
platform-operator/scripts/install/create_oci_config_secret.sh
tests/e2e/config/scripts/create-test-oci-config-secret.sh

Cherry pick change for VZ-3358, this uses verrazzano-install namespace instead of the default namespace for the install/uninstall jobs and pods plus the service account.  It also includes the change where the OCI secret is now created in the verrazzano-install namespace. 

VZ-3358 cherry pick into release-1.0

---

ci/multicluster/Jenkinsfile

Change the multicluster acceptance test suite to do the following:
- Install verrazzano v1.0.0 (by default, but can override with parameter)
- Configure multicluster environment and verify the install
- Upgrade the admin and managed clusters to the version of verrazzano on the branch
- Verify the upgrade
- Run the acceptance tests
Fixes VZ-3380

VZ-3380: Perform an update in the multicluster acceptance tests

---

ci/upgrade/Jenkinsfile
platform-operator/controllers/verrazzano/component/helm/helm_component.go
platform-operator/controllers/verrazzano/component/helm/helm_component_test.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_test.go
platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml
platform-operator/internal/helm/helmcli.go
platform-operator/internal/helm/helmcli_test.go
tests/e2e/config/scripts/wait-for-verrazzano-upgrade.sh

Upgrade/upgrade-test fixes.
- Revert impl for IsReleaseInstalled to previous impl that doesn't do fine-grained status checks
- Separate out new impl into new fn, IsReleaseDeployed for now, will debug and consolidate later if possible
- Set terminationGracePeriodSeconds to 0 on the platform operator deployment
- Handle error where setting UpgradeComplete status returns an error, and requeue for re-processing
- Fix up delays/waits in upgrade test pipeline
- Add unit test case for status update error on UpgradeComplete
Fixes VZ-3568.  

VZ-3568.  Upgrade/upgrade-test fixes

---

ci/ticket-commits/JenkinsfileCommits

This PR enables backport labeling of JIRA tickets when processing commits. Commits on release-* branches with JIRA ticket ids in the commit messages will cause the helper to add a label "bp-<release branch version>" to the tickets.
Implements VZ-3498

VZ-3498: Enable backport labeling when running verrazzano-helper

---

ci/ticket-commits/JenkinsfileCommits

This PR enables backport labeling of JIRA tickets when processing commits. Commits on release-* branches with JIRA ticket ids in the commit messages will cause the helper to add a label "bp-<release branch version>" to the tickets.
Implements VZ-3498

VZ-3498: Enable backport labeling when running verrazzano-helper (release-1.0 branch)

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-api-configmap.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml

Fixes VZ-3533
1. Added helm chart value in values.yaml - api.proxy.MaxRequestSize
2. Modified Verrazzano-api-configmap.yaml to fetch the above value

Created helm chart value - api.proxy.MaxRequestSize

---

application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
platform-operator/controllers/verrazzano/component/appoper/app_operator.go
platform-operator/controllers/verrazzano/component/appoper/app_operator_test.go
platform-operator/controllers/verrazzano/component/coherence/coherence.go
platform-operator/controllers/verrazzano/component/coherence/coherence_test.go
platform-operator/controllers/verrazzano/component/oam/oam.go
platform-operator/controllers/verrazzano/component/oam/oam_test.go
platform-operator/controllers/verrazzano/component/registry/registry.go
platform-operator/controllers/verrazzano/component/weblogic/weblogic_operator.go
platform-operator/controllers/verrazzano/component/weblogic/weblogic_operator_test.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/install.go
platform-operator/controllers/verrazzano/sync_local_registration_secret.go

Allow non-blocking installs of components, validate ready status independently.
Fixes VZ-3422 (partial).

VZ-3422.  Non-blocking installs of Go components; install state-machine

---

ci/multicluster/Jenkinsfile
tests/e2e/scripts/install/install_test.go

The dump of The Verrazzano install logs in the multicluster test pipeline is currently being done for a v1.0 install (and then upgrading later).  The location of the log files has changed from the "default" namespace to the "verrazzano-install" namespace.  This change is to have the test suite choose the source location of the logs based on the Version of verrazzano installed.  For version 1.0.0 and 1.0.1 the default namespace is used, otherwise verrazzano-system is used.
Fixes VZ-3578

VZ-3578 - Change dump of logs to be aware of what version of Verrazzano was installed

---

Jenkinsfile
ci/JenkinsfilePeriodicTests
ci/JenkinsfileTestTrigger

The main verrazzano no more waits for the triggered tests to complete, so measuring the build duration at the end of the scripts used by the main job doesn't provide sufficient data to measure the trend. This change publishes the metrics containing the build duration as the value from the script used by the triggered jobs.
Contributes to VZ-3053

Publish the metrics for the build duration of triggered jobs

---

platform-operator/scripts/install/3-install-verrazzano.sh
platform-operator/thirdparty/charts/istio/gateways/istio-ingress/templates/service.yaml

This PR has 2 fixes for OLCNE
1). Add the ExternIPs back the Istio chart, it existing in Istio 1.4.6, but was removed in Istio 1.7.3.  This is needed to access the application via the Istio Ingress Gateway
2) Fix a verrazzano script problem where multiple Kubernetes API Server IPs are returned on OLCNE causing the following parsing error:
Error: failed parsing --set data: key map "100" has no value

VZ-3584 OLCNE Istio ExternalIP

---

release/scripts/check_versions.sh
release/scripts/compare_crds.sh
release/scripts/prerelease_validation.sh

Automation scripts for pre-release validation. The scripts currently show/check:
- CRD differences
- Versions in .verrazzano-development-version and Chart.yaml files
- JIRA tickets missing backports (for patch releases)
If any of the checks fail, the pre-release validation script exits with a non-zero code. Setting the `IGNORE_FAILURES` environment variable overrides that and the script will always exit with a zero code.
Implements VZ-3497

VZ-3497: Initial pass at pre-release validation scripts

---

pkg/bom/bom.go
pkg/bom/bom_test.go
pkg/bom/testdata/test_bom_sc_overrides.json

Allow a subcomponent in the BOM to override the global registry location.  This is to facilitate testing one-off images in developer scenarios.

Allow BOM subcomponent to override the global registry setting

---

ci/ticket-commits/JenkinsfilePullRequests

Do not add a PR comment to a JIRA if an existing PR is being updated. Quick and dirty solution to check for a change set. There will not be a change set when the PR is created or if the Jenkins job is triggered manually.
This change was requested because PRs that end up with lots of separate commits pushed to them resulted in many PR comments in the JIRAs. Now we only add a comment to the JIRA when the PR is created.

Do not add JIRA comment if PR is being updated

---

ci/ticket-commits/JenkinsfilePullRequests

Backport of a change to not add a PR comment to a JIRA if an existing PR is being updated.

Do not add JIRA comment if PR is being updated (release 1-.0 branch)

---

tools/cli/scripts/cli_test.sh

The CLI tests are failing intermittently.  We believe the failure is a timing condition due to not waiting for the VMC to be deleted during de-register.
Fixes VZ-3604

VZ-3604 - add wait for VMC to be deleted in CLI tests

---

ci/multicluster/Jenkinsfile
tests/e2e/pkg/kubernetes.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/keycloak/keycloak_test.go

Add persistence overrides to the `dev` profile for the Multicluster tests, to provide more stability around pod restarts while still leveraging the minimal `dev` profile resource usage.

Use persistence overrides with dev profile for upgrade test stability.

---

ci/multicluster/Jenkinsfile

Update the Jenkins file for the multicluster test suite to dump a cluster when there is a failure in the CLI tests.

Add cluster dump for fail of cli tests

---

ci/multicluster/Jenkinsfile

Remove the CLI tests stage.  Errors from this stage are causing master builds to fail.  The decision was to remove them for now because the CLI is not yet part of the product.  
Fixes VZ-9999

vz-3693 remove CLI tests stage

---

ci/private-registry/Jenkinsfile

Fix an issue in the private registry test pipeline with branches with upper-case letters.  Branch names are part of the test OCIR repo name, which causes the OCI repository creation to fail.  Fixed by just lower-casing the repo names before processing the Zip file.

Fix private registry tests in branches with upper-case letters

---

Jenkinsfile
ci/kind/Jenkinsfile
ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/private-registry/Jenkinsfile
ci/rolebased/Jenkinsfile
ci/uninstall/Jenkinsfile
ci/upgrade/Jenkinsfile

No JIRA.
Recent changes for golang version, and k8s version support in master require that we start implementing the tool branching strategy for the release-1.0 branch.
This pins the tooling in release-1.0 to images which support the CI for that release.

Specify the release-1.0 pinned RUNNER_DOCKER_IMAGE/ARGS and agent VMs

---

platform-operator/controllers/verrazzano/component/helm/helm_component.go
platform-operator/controllers/verrazzano/component/helm/helm_component_test.go
platform-operator/controllers/verrazzano/component/istio/istio_component.go
platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
platform-operator/controllers/verrazzano/component/registry/registry.go
platform-operator/controllers/verrazzano/component/registry/registry_test.go
platform-operator/controllers/verrazzano/component/spi/component.go
platform-operator/controllers/verrazzano/component/spi/component_context.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/fake_component_test.go
platform-operator/controllers/verrazzano/install.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_test.go
platform-operator/internal/helm/helmcli.go

Refactor Component interface calls around new ComponentContext interface
- Collect parameters into a single object to avoid proliferation of parameters
- Context object will eventually own construction of effective (merged) CR
- Update impls and unit tests
- Unrelated, skip empty values files passed into helm upgrade
- Use fake component impls for controller testing

Introduce ComponentContext to Component interface

---

ci/kind/Jenkinsfile

Change the default to make bob's books tests run in the downstream builds

run bob's books in the downstream tests

---

platform-operator/verrazzano-bom.json

This PR updates both the controller and default-backend images of ingress nginx to images that have no OCIR scan identified HIGH/CRITICAL vulnerabilities.
Fixes VZ-3725, VZ-3726

VZ-3726 VZ-3725 update to OCIR scan cleared ingress nginx images

---

ci/scan-results/Jenkinsfile
ci/scripts/get_branch_scan_results.sh

Jenkinsfile and shell script that process scan results per branch. The pipeline is set up to run on master and release-* branches. For release-* branches, we fetch the scan results for all images for all releases associated with the branch, as well as the tip of the branch.
Implements VZ-3938

VZ-3938: Jenkins support for processing scan results

---

platform-operator/verrazzano-bom.json

This pull request backports changes to use the same version of the nginx-ingress-controller image in the Verrazzano BOM. This change was a straight cherry-pick from master.

VZ-3909: [release-1.0] use same version of the nginx-ingress-controller images (#1879)

---

Jenkinsfile
release/builds/Jenkinsfile

Backport the new parameter to the release-1.0 line, this really is just for aligning the parameters in that pipeline so the parameter exists there (and so the release automation pipeline can be more consistent between master/release-1.0). The release-1.0 line currently only will wait for completion, so the new parameter will be ignored when specified. If the other disconnected behaviour gets backported for some reason this will work as it does in master (and when we cut new release branches).

VZ-3889: backport to release-1.0

---

platform-operator/verrazzano-bom.json

A new image update for proxyv2 provided by OLCNE updates. This is an updated version of the original 1.7.3 image tagged 1.7.3-2
Fixes VZ-3730

VZ-3730 proxyv2 image tag update 1.7.3-2

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go

Fixes case where external LB is used with Wildcard DNS
- Use LB service externalIP value if not auto-assigned by Kubernetes.
Fixes VZ-3968.

VZ-3968.  Use service externalIP field when using external LB

---

application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
platform-operator/controllers/clusters/vmc_controller.go
platform-operator/controllers/clusters/vmc_controller_test.go
tests/e2e/multicluster/verify-permissions/verify_permissions_test.go

This pull request includes changes for supporting a new security model of secrets in multicluster.  Instead of a clusterrolebinding, rolebindings are used to access admin cluster resources from a managed cluster.

VZ- 3977: changes for supporting new security model of secrets in multicluster

---

platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/clusters/vmc_controller.go

Reduce the logging output of the reconcile loop.  Every minute a block of redundant messages was being output to the log.
Fixes VZ-3480

vz-3480 reduce verbosity of logging in reconcile loop

---

platform-operator/verrazzano-bom.json

I had updated the BOM to pick up new build versions (just rebuild no code changes) of the rancher and rancher-agent images, but somehow that resulted in rancher pulling in newer, unexpected versions of the additional rancher images that get installed in the background. That caused the private registry tests to fail because the images were not present in the registry.
Revert to using the previous image tags.

Revert rancher images

---

ci/multicluster/Jenkinsfile
ci/upgrade/Jenkinsfile

Disable the proxy image version check since it doesn't handle the kiali use case where Kiali gets installed after upgrade.  This test will be moved to a go post-upgrade test suite.

Disable the Upgrade check for old envoy images

---

platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/controllers/clusters/sync_prometheus.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/verrazzano-bom.json
tests/e2e/metrics/syscomponents/metrics_test.go
tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go
tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go
tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go
tests/e2e/multicluster/verify-register/verify_register_test.go
tests/e2e/pkg/common.go
tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/metrics.go

VZ-3747 Part 2 - Uptake dashboard changes to add cluster drop down, remove old managed_cluster label, update tests
Fixes VZ-3747

VZ-3747 Part 2 - Uptake dashboard changes to add cluster drop down, remove old managed_cluster label, update tests

---

release/scripts/create_github_release.sh
release/scripts/verify_github_release.sh

Updates to the release automation scripts for creating and verifying a GitHub release. I had to separate the release artifact verification script because creating a GitHub release using "--draft" means the artifacts aren't available for public download. The script always failed as a result.
I also made fixes and enhancements based on my experience performing the last release. For example, I enhanced the verification script so that it can be run on mac or linux.

Release automation script fixes

---

platform-operator/scripts/install/4-install-keycloak.sh

Because the KialiUrl status cannot be guaranteed by install time, we need to give users the command to access the interface URLs rather than the URLs themselves
Fixes VZ-4003

VZ-4003 Replace interface list with command due to Kiali timing issues

---

release/builds/JenkinsfilePostPRT
release/scripts/create_github_release.sh
release/scripts/verify_github_release.sh

Port of release automation fixes to master.
Updates to the release automation scripts for creating and verifying a GitHub release. I had to separate the release artifact verification script because creating a GitHub release using "--draft" means the artifacts aren't available for public download. The script always failed as a result.
I also made fixes and enhancements based on my experience performing the last release. For example, I enhanced the verification script so that it can be run on mac or linux.

Release automation fixes (master port)

---

release/builds/Jenkinsfile

I added a bool param to the Jenkinsfile that allows us to run the stage 1 release pipeline and have it only create the branch. This can be used when creating a major/minor version branch in advance of actually performing a release.
I also removed the check for "master" so that the subsequent release run won't fail when the branch is created ahead of time.
The create_branch.sh script already handles the case where the release branch already exists, so no changes needed there to support this.
Implements VZ-4047

VZ-4047: Release automation updates

---

application-operator/controllers/logging/fluentd.go
application-operator/controllers/logging/fluentd_test.go
tests/e2e/examples/todo/todo_list_test.go
tests/e2e/pkg/conditional_spec.go

In the 1.1 release the fluentd sidecar parse rules for WLS have been updated to accommodate additional log file types that might be available in the server container (nodemanager, access, and domain logs, in addition to the server log).  On upgrade, however, the configmap is not updated.  If the configmap has not changed, the resultant update will be a no-op.  
Also
- renabled the new WLS logging tests, conditionalized for 1.1+
- Added a general utility for conditional execution of a test spec
Fixes VZ-3899.

VZ-3899.  Update fluend sidecar configmap if necessary

---

platform-operator/scripts/install/1-install-init.sh
platform-operator/scripts/install/common.sh

NGINX and Istio installs have been moved to the platform operator as part of a larger effort to move all components there and remove the install job.  The components that are still installed by the scripts depend on Istio and NGINX being available, so some timed-waits were added to the scripts to delay execution until those services are available.  The timeouts are currently not long enough to account for slow image pulls or other performance degradations during install that can delay availability of those services.
This change extends install script max timeouts for istiod and nginx availability and improves diagnostics a little when the timeouts are exceeded.
- Check for slow image pulls and report them
- Add more descriptive output
- dump deployment object on failure
Fixes VZ-4070.
As …

VZ-4070. Improve install script waits for istiod and nginx availability, extend max timeout

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
tests/e2e/pkg/vmi/elastic.go
tests/e2e/verify-infra/vmi/vmi_test.go

- Set index.number_of_replicas to 0 by default
- Enable auto expand replicas setting by configuring "index.auto_expand_replicas" to "0-all"
Fixes VZ-9999

VZ-2528 Fix the number of replicas in elasticsearch

---

platform-operator/controllers/verrazzano/component/istio/istio_cr.go
platform-operator/controllers/verrazzano/component/istio/istio_cr_test.go

Fixes an issue for `istioInstallArgs` handling in the VZ CR for Istio
- generates a separate YAML snippet for each Istio installArg
- merges those with the ExternalIPs snippet and the egress snippet

Fix Istio CR installArgs handling

---

pkg/framework/ginkgo_wrapper.go
pkg/framework/ginkgo_wrapper_util.go
pkg/framework/ginkgo_wrapper_util_test.go
tests/e2e/istio/authz/authpolicy_test.go

Introspect interface arguments and check that they are functions.  This begins to lay the groundwork for needing to do more extensive introspection of interfaces in ginkgo v2.
Undo framework changes from auth policy test to reduce the number of conflicts to address when we uptake ginkgo v2.
Fixes VZ-4021

VZ-4021 Introspect interface arguments and check that they are functions

---

tests/e2e/examples/bobsbooks/bobs_books_test.go

improve test to fail fast when the 'pattern not matched' log is found; using Eventually unnecessarily add 20min timeout to the failure. 
Fixes VZ-3631

fail fast on 'pattern not matched' errors

---

ci/upgrade/Jenkinsfile
tests/e2e/pkg/common.go
tests/e2e/upgrade/post-upgrade/verify/verify_restart_suite_test.go
tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go

Add an e2e test to ensure that the application pods contain the Envoy 1.104 sidecar post-upgrade.  This proves that the applications were restarted and contain the new version of Envoy.

VZ-3985 upgrade test

---

platform-operator/verrazzano-bom.json

Uptakes the new Elastic search 7.10.2 image built from source.
Fixes VZ-3988: Build elasticsearch from source and clear of vulnerabilities.

VZ-3988: Build elasticsearch from source and clear of vulnerabilities.

---

examples/multicluster/todo-list/todo-list-components.yaml

This pull request changes the multicluster todo-list yaml for deploying mysql.  Changed the container port info to match the non-multicluster flavor and fixed some indentation.

Fix multi-cluster todo-list mysql deployment yaml

---

Jenkinsfile

Currently the container images are scanned only using the clair tool. The PR is for introducing scans using the trivy scanning tool.
Fixes VZ-3558
- [X ] Checked that I included or updated copyright and license notices in all files that I altered
- [] Added or updated unit tests for any new functions I added (NA)
- [] Added or updated integration tests if appropriate (NA)
- [] Added or updated acceptance tests if appropriate (NA)

VZ-3558 Include trivy scanning to the build jobs

---

platform-operator/controllers/verrazzano/component/certmanager/certmanager_component.go

Override key name of image to match the cert-manager chart.
Fixes VZ-3936

Change image pull keyname to match cert-manager chart

---

pkg/bom/bom.go
pkg/controller/errors/errors.go
pkg/controller/errors/errors_test.go
platform-operator/controllers/verrazzano/component/certmanager/certmanager.go
platform-operator/controllers/verrazzano/component/helm/helm_component.go
platform-operator/controllers/verrazzano/component/helm/helm_component_test.go
platform-operator/controllers/verrazzano/component/spi/component_context.go
platform-operator/controllers/verrazzano/component/spi/component_context_test.go
platform-operator/controllers/verrazzano/install.go
platform-operator/internal/helm/helmcli_test.go

Creates a custom error type to be returned from `spi.Component` to indicate to the controller that it should requeue, and is a non-fatal event. 
Also, adds support to `bom.KeyValue` and `HelmComponent` to allow a component to specify a custom helm file override.

Component retryable errors for install/upgrade

---

tests/e2e/verify-infra/restapi/keycloak_url_test.go
tests/e2e/verify-infra/restapi/rancher_url_test.go
tests/e2e/verify-infra/restapi/vmi_urls_test.go

Removed the unstable tag from verify-infra restate suite since the new go-based rancher installation merge seems to have resolved the issue.
Fixes VZ-3961

JIRA:VZ-3961 remove unstable tag from verify-infra restapi tests

---

platform-operator/scripts/uninstall/uninstall-steps/1-uninstall-istio.sh

During Verrazzano Uninstallation Steps, there is an error message comes "Error: no repositories to show "
The "Error: no repositories to show" is likely to confuse customers even though we don't think anything was left behind.
This PR basically a fix for the same.
[2021-07-27 17:42:01 UTC] Finalizing Uninstall                                                         [ .... ]
[2021-07-27 17:42:01 UTC] 2021-07-27 17:42:01 UTC Removing Verrazzano ClusterRoles and ClusterRoleBindings
[2021-07-27 17:42:02 UTC] 2021-07-27 17:42:02 UTC Deleting Helm repos
[2021-07-27 17:42:02 UTC] WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/verrazzano/kubeconfig
[2021-07-27 17:42:02 UTC] WARNING: Kubernetes configuration file is world-readable. This is insecure. …

VZ-3173 : fixing vz Uninstall log shows error

---

platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/clusters/vmc_controller_test.go

Fix registration of a managed cluster when using LetsEncrypt staging certs.  If additional CA certs are present on the system, use them for the platform-operator to connect to Rancher in order to register a managed cluster.
Fixes VZ-4134

VZ-4134 Fix registration of a managed cluster when using LetsEncrypt staging certs

---

ci/dynamic-updates/Jenkinsfile
ci/kind/Jenkinsfile
ci/multicluster/Jenkinsfile
tests/e2e/scripts/install/install_test.go

This pull request fixes the verify-scripts AT to run against a single kubeconfig instead of having logic for both multi-cluster and single cluster installs.

VZ-4093: Fix bug in verify-scripts AT and simplify

---

platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/basicManagedClusterMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/managedClusterEnableAllOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml
platform-operator/manifests/profiles/base.yaml
platform-operator/manifests/profiles/dev.yaml

Initially the in-operator profile definitions in `platform-operator/manifests/profiles` defined the storage values in the profile yamls themselves; i.e., the defaults for `prod` profile were defined in `base.yaml` and overridden where necessary.  However, how we do the yaml merges to produce the effective CR might make it difficult to do overrides as we currently document it.
For example, the defaults for MySQL are 8G, and for the VMI stack is 50G.  If I define those in the profile yamls, I would have to add a `defaultVolumeSource` of 50G an override for MySQL of 8G to match the current chart defaults in the profiles.  
```
spec:
defaultVolumeSource:
claimName: default
volumeClaimSpecTemplates:
- metadata:
name: default-storage
spec:
resources:
requests:
storage: 50Gi
- metadata:
name: …
```

Update base profile storage definition to rely on chart defaults

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml
tests/e2e/verify-install/web/web_test.go

This change to validate that the body of a request targeted to console or verrazzano api is a well formed json.
Fixes VZ-4063
This change was earlier merged as part of https://github.com/verrazzano/verrazzano/pull/2028 but was reverted due to a test failure caused due to version mismatch which is now fixed.

Validate request body for console and api

---

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
tests/e2e/pkg/vmi/elastic.go
tests/e2e/verify-infra/vmi/vmi_test.go

Fixes issues that caused Elasticsearch to report a Yellow status.  This occurs when Elasticsearch has a single data node but is also configured to have index replicas.  This change allows Elasticsearch to manage the replica count so avoid this issue in both the Dev and Prod profiles.
Fixes VZ-2528: Elasticsearch number of replicas wrong after upgrade
Note that I decided to leave the code in the Verrazzano post upgrade hook for two reasons.
1. It didn’t seem to add significant time to the upgrade.
2. Once parallel upgrade is worked out this code won’t need to get found and move from the global post upgrade hook.

VZ-2528: Elasticsearch number of replicas wrong after upgrade

---

platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/component/mysql/mysql.go
platform-operator/controllers/verrazzano/component/mysql/mysql_component.go
platform-operator/controllers/verrazzano/component/mysql/mysql_test.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/install.go
platform-operator/controllers/verrazzano/installjob/install_config.go
platform-operator/controllers/verrazzano/installjob/install_config_test.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/internal/vzconfig/enabled_test.go
platform-operator/internal/vzconfig/ingress_test.go

This is a second pass on https://github.com/verrazzano/verrazzano/commit/34bf6e23945a2cd00aa275c3de462206f073aac3
and resolves comments from https://github.com/verrazzano/verrazzano/pull/2045
Contents:
- Leverages the operation field in the component context
- Moves findVolumeTemplate to common code and removes all duplicate non-exported functions
- Cleans up misplaced constant
- Cleans up typo

MySQL second pass cleanup

---

tests/e2e/examples/socks/sock_shop_example_test.go

This pull request changes the AfterSuite function of the sock shop test to delete the appconfig and components before deleting the namespace.  When we only delete the namespace the test intermittently fails due to finalizers not being called for Coherence resources by the Coherence operator.

Explicitly delete sock shop  appconfig and components before deleting namespace

---

application-operator/controllers/wlsworkload/weblogic_logging.go
application-operator/controllers/wlsworkload/weblogic_logging_test.go
tests/e2e/pkg/elasticsearch.go

Fix a case of 'pattern not matched' errors that the format13 pattern failed if the message field contains a ">", greater-than sign, in the message body.
Fixes VZ-3631

fixed wls parse pattern to match more

---

platform-operator/controllers/verrazzano/component/mysql/mysql.go
platform-operator/controllers/verrazzano/component/mysql/mysql_test.go

Re-add the init image override for the MySQL deployment, fixes the private registry use case.

No JIRA.  Fix custom image overrides for MySQL init container

---

ci/upgrade/Jenkinsfile

This pull request fixes a regression in the upgrade AT where the todo-list test was failing during post upgrade testing.
The fix was to deploy todo-list post upgrade.

Fix upgrade-test regression with todo-list post-upgrde

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/navigation/trait.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
tests/e2e/examples/bobsbooks/bobs_books_test.go

- Set WeblogicPluginEnabled to true using WDT config map
- Add WL-Proxy-SSL header by default for WebLogic workload requests
Fixes VZ-2689

VZ-2689 Fix for WLS apps wrong redirection to HTTP instead of HTTPS

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml

The helm chart override keys in `verrazzano-logging.yaml` do match what the code is setting in the platform operator. As a result the `extraVolumeMounts` settings in the Verrazzano CR were being ignored. This fixes the key names.

Fix chart override keys for fluentd extra volume mounts

---

ci/JenkinsfilePeriodicTests
release/builds/JenkinsfilePreRelease

VZ-4044 switch to use a separate job in internal agent for prerelease checks. Some checks required internal corpnet access, need  to run those checks on internal agent.
The periodic job also needed to get the artifacts from that job to properly set the RELEASABLE status

VZ-4044 switch to use a separate job in internal agent for prerelease checks

---

platform-operator/verrazzano-bom.json

Backport BOM change to pick up latest BFS ingress-nginx v0.46.0 image, fixes some CVEs.
Fixes VZ-4170

VZ-4170: backport bom change for ingress-nginx v0.46.0 cve fixes

---

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
platform-operator/helm_config/overrides/rancher-values.yaml
platform-operator/verrazzano-bom.json

Update Rancher webhook version in the BOM to v0.1.2.
- also, set `useBundledSystemChart=true` for all installs to use bundled charts only.

No JIRA.  Update rancher webhook to v0.1.2

---

tools/bom-validator/bom-validator.go

Updates the BOM validator to ignore Rancher images that get installed in the background.  
At present we need to reference these images for private registry installs, however, Rancher does not strictly install what we declare.  Rancher requires a "min version" for these components, so in some cases (like upgrade) it may meet that requirement, but not match what's in our BOM.

No JIRA.  Update BOM validator to ignore Rancher additional images

---

tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/helidonconfig/helidon_config_test.go
tests/e2e/logging/helidon/helidon_logging_test.go

This change adds cluster dumps to the Helidon example and logging tests. It is the only app that does not have a call to dump the cluster on failure in the AfterSuite and there was a Helidon failure that we cannot debug because there is no cluster dump of the Helidon namespace

VZ-3157: Add cluster dump call to the Helidon AfterSuite

---

tests/e2e/security/netpol/network_policy_test.go

Bump network policies async assertion wait timeout to 15 min.
Fixes VZ-4316.

VZ-4316.  Bump network policies async assertion wait timeout to 15min

---

platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
platform-operator/controllers/verrazzano/component/externaldns/external_dns_component.go

Fix the Helm key used for image pull secret overrides when installing external-dns, 1.1 branch port.
Fixes VZ-4319

VZ-4319.  Fix external-dns private registry install for release-1.1 branch.

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go
application-operator/controllers/webhooks/appconfig_defaulter.go
application-operator/controllers/webhooks/appconfig_defaulter_test.go

The logic for deleting the cert and secret associated with an ingress during deletion was moved to the controller from the webhook.  This will facilitate retries of the deletion operations (reconciler retries).
Fixes VZ-4313

JIRA:VZ-4313 Handle ingress cert and secret deletion in controller rather than webhook

---

pkg/test/framework/ginkgo_wrapper.go
pkg/test/framework/ginkgo_wrapper_test.go
pkg/test/framework/ginkgo_wrapper_util_test.go
pkg/test/framework/metrics/ginkgo_metrics.go
pkg/test/framework/metrics/ginkgo_metrics_suite_test.go
pkg/test/framework/metrics/ginkgo_metrics_test.go
pkg/test/framework/metrics/metrics.go
pkg/test/framework/metrics/prometheus.go
pkg/test/framework/metrics/prometheus_test.go
tests/e2e/istio/authz/authpolicy_test.go

Metric would look like:
```
{
"timestamp":1639520348298250000,
"caller":"metrics/ginkgo_logger.go:56",
"suite_id":"ba2b8cff-40fa-490a-97ed-ce43c2a88038",
"package":"metrics_test",
"status":"passed",
"attempts":1,
"test":"Should do another thing"
}
```
Client has full control to emit additional metrics by operating on the SugaredLogger.

Basic Emit Metrics

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml

We have had multiple AT failures related to Elasticsearch, where Fluentd reports a "400" error attempting to send logs to Elasticsearch. This PR enables a flag that causes Fluentd to log the reason for that error. Hopefully this will provide more informations so we can troubleshoot the error.
I first tried to reproduce this locally but could not.

VZ-4334: Set log_es_400_reason to capture more information

---

application-operator/controllers/metricstemplate/metricstemplate_controller.go

Fixes issue caused by VZ-4275 change that prevents VAO from starting if WebLogic or Coherence CRDs are not installed.

VZ-4275: Create skeleton controller for metrics workloads

---

ci/dynamic-updates/Jenkinsfile

No JIRA.  Move SOCKS app test to stage 2 in dynamic config test pipeline.  The example app requires COH, which is disabled in the initial test pass.

No JIRA.  Move SOCKS app test to stage 2 in dynamic config test pipeline

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go

This fix creates the GW immediately in the IngressTrait reconciler.  Before the code would wait until the service was ready.   Evidently, the External-DNS that we use looks for GW resources once the service exists, so there was a race condition where the GW didn't get created in time to be seen by External-DNS once the service existed.

VZ-4321 Todo List DNS record not getting created

---

release/scripts/compare_crds.sh
release/scripts/prerelease_validation.sh

The CRD comparison script used in the release automation pipeline was defaulting to the last tagged release version. However, that does not work in many cases. For example, if the pipeline for release 1.0.4 is run after release 1.1 is created, the CRDs for 1.0.4 are compared with 1.1 instead of 1.0.3.
This PR makes the comparison script smarter about what release tag to compare against. Results from testing:
```
$ release/scripts/compare_crds.sh 1.0.4
Showing all CRD differences between v1.0.3 and HEAD
$ release/scripts/compare_crds.sh 1.2.0
Showing all CRD differences between v1.1.0 and HEAD
$ release/scripts/compare_crds.sh 2.0.0
Showing all CRD differences between v1.1.0 and HEAD
```
These changes will also need to be ported to the release-1.1 and master branches.
Fixes VZ-4345
As the …

VZ-4345: Fix CRD comparison script to be smarter with version tags

---

tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/helidonconfig/helidon_config_test.go
tests/e2e/logging/helidon/helidon_logging_test.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go

Tests have been failing because the ES index cannot be found for hello-helidon, helidon-config, and helidon-logging. It frequently takes the helidon index a long time to come up in ES even on successful runs. This change increases the Helidon tests wait timeout to 20m to try to stop this test from failing.

VZ-4392: increase timeout for helidon index test

---

release/scripts/compare_crds.sh
release/scripts/prerelease_validation.sh

Port of the release automation compare CRDs script fix from the release-1.0 branch. The script now takes the release version into account when looking for the last release tag to compare against.
Fixes VZ-4345

VZ-4345: Fix CRD comparison script to be smarter with version tags (#2173)

---

examples/springboot-app/springboot-comp.yaml
platform-operator/verrazzano-bom.json

This change updates the Keycloak (v.15.0.2) and Elasticsearch (v.7.10.2) images in verrazzano-bom.json. Also the image used by the Spring Boot application is updated in this change.

Update Keycloak and Elasticsearch images

---

tests/e2e/security/netpol/network_policy_test.go

Backport change to bump timeout for netpol tests for rancher-webhook timing issue.
Fixes VZ-4316

VZ-4316.  Backport netpol test update to release-1.0

---

platform-operator/controllers/verrazzano/component/registry/registry.go
platform-operator/controllers/verrazzano/component/registry/registry_test.go
platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/upgrade_test.go

VZ-4322 bug fix - component registry should maintain a list, not a map, since order of items in GetComponents is significant
Fixes VZ-4322

VZ-4322 bug fix - component registry should maintain a list, not a map, since order of items in GetComponents is significant

---

tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/pkg/oam.go

Ensure that the sockshop appconfig and namespace is deleted in the AfterSuite.  Dump cluster if it fails.

VZ-4358 Sockshop ensure application deleted

---

tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/examples/socks/sockshop.go

Sock shop test, "SockShop can be accessed and user can be registered," contains an Expect inside an Eventually which causes unnecessary testing failures. This PR updates the return of this test to include the errors rather than using the Expect.
Fixes VZ-4370

Update Sock Shop test Eventually and Expect Combination

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go

The Fluentd logs have thousands of error messages stating that Elasticsearch has rejected log messages due to parsing errors when running acceptance tests. The errors are due to the same log field being logged as both a string and a complex type.
There are two fields that were being rejected: "trait" and "name". The "trait" field was being logged as a string in some cases and a `NamespacedName` in other cases. One bit of unexpected behavior I found is that when you call `Log.WithValues(...)` and pass it a `NamespacedName` type, it automatically converts the field to a string because the struct implements a `String()` function. I changed all of the places where the `NamespacedName` was being logged as a string so that "trait" is always logged as a complex type.
The "name" field was being …

VZ-4334: Fix Elasticsearch parsing errors

---

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go

VZ-4113 backport part2 - Always create rancher namespace
Fixes VZ-4113

VZ-4113 backport part2 - Always create rancher namespace

---

application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go

This is a backport PR of the fix for the Elasticsearch parsing errors. The original PR was merged to master, and this is the backport to the release-1.1 branch.
I did a run with a cluster dump on success and confirmed that the Fluentd logs do not have any rejected log messages due to parsing errors.
Fixes VZ-4334

VZ-4334: Fix Elasticsearch parsing errors (release-1.1)

---

platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh

Today during cleanup , helm looks for ingress across all namespaces, and finds a match to delete the specific release
helm ls -A \
| awk '/ingress-controller/ {print $1}' \
| xargsr helm uninstall -n ingress-nginx \
this is incorrect, because there might be other ingress controllers with the same release name in other namespaces. As a result deletion will fail for other namespaces 
example 
[opc@aamitrawls-admin ~]$ helm ls -A     | grep ingress-controller[opc@aamitrawls-admin ~]$ helm ls -A     | grep ingress-controlleringress-controller              default                 1        2021-12-16 19:28:39.152258543 +0000 UTC deployed nginx-ingress-controller-1.0.0ingress-controller              ingress-nginx           1        2021-12-16 21:43:43.404289654 +0000 UTC deployed …

VZ-4349-Update helm to list specific namespaces at cleanup

---

tests/e2e/config/scripts/terraform/cluster/create-cluster.sh

The Terraform module for creating clusters does not hold the state for the cluster after it times out on creation. The test case that triggered this creation edit had a cluster that timed out after an hour. In order to avoid conflicts (The creation will fail because the names for the clusters will stick around, and the deletion will fail because of old VNICs that disallow subnets from being deleted), I have decided to delete after every iteration of Terraform apply. This will add about 10 minutes to each iteration if a timeout or failure occurs, but it will avoid conflict errors. I'm not in love with this solution, but I think it will help reliability.
Also, I didn't think extending the timeout was necessary, as I think an hour is enough time to gauge that an apply has gone awry.
Fixes …

VZ-4375 Delete cluster terraform to remove reconciliation errors

---

tests/e2e/metrics/deploymetrics/deploymetrics_test.go
tests/e2e/pkg/metrics.go

This changes the deploymetrics test to not check that the metrics have been deleted from Prometheus after the app is uninstalled. Instead, the test checks the the app has been added to the Prometheus config. It then checks in the AfterSuite after the App components have been deleted that the app has been removed from the Prometheus config.

VZ-4372: Don't check that app metrics have been deleted

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go

Change the IngressTrait cleanup to delete the cert and secret, ignoring the notExist error.  This eliminates a potential race condition where a get and then is called, and another thread could then delete the cert/secret.

pmackin/VZ-4313 IngressTrait finalizer cleanup

---

tests/e2e/examples/socks/sock_shop_example_suite_test.go
tests/e2e/examples/socks/sock_shop_example_test.go

Add a failure handler so that AfterSuite failures are logged.

Add failure handler to sock-shop

---

tests/e2e/scripts/install/install_test.go

Modify install test check for isConsoleURLExpected after backport of VZ-4322 fix to 1.1.1
Fixes VZ-4322

VZ-4322 - Modify install test check for isConsoleURLExpected after backport of VZ-4322 fix to 1.1.1

---

tests/e2e/metrics/deploymetrics/deploymetrics_test.go
tests/e2e/pkg/metrics.go

Reverts verrazzano/verrazzano#2216 which introduced a new test that is intermittently failing

Revert "VZ-4372: Don't check that app metrics have been deleted"

---

tests/e2e/examples/helidon/helidon_example_test.go

Increases the timeout in the Helidon example test as the logs showed that waiting just a bit longer would have resulted in the test passing.
Fixes VZ-4373: Timeout in examples tests too short

VZ-4373: Timeout in examples tests too short

---

application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go

The Ingress Trait Controller repeatedly logs "configuration is invalid: empty domain name not allowed" when creating/updating a destination rule.  Thus change fixes that issue.

VZ-4389:  fix error creating/updating destination rule in ingress trait controller

---

ci/upgrade/Jenkinsfile

This change sets a timeout of 30 minutes for the stage in upgrade pipeline, which uninstalls Verrazzano.

Add a timeout for Verrazzano uninstall in upgrade pipeline

---

application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go

The formatting for the ports of Istio needs to be updated for helidon workloads based on this format: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
I made TCP the default for now. I don't think we allow for this to be customized, so that could possibly be a future addition.
Fixes VZ-4087

VZ-4087 Update Port Name Field for Helidon Workload

---

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go

This PR refactors the Keycloak PostInstall logic to be idempotent. It will now check if verrazzano-system realm resources have previously been created before trying again.  It also includes new unit tests
- [ x] Added or updated unit tests for any new functions I added

vz4236 Keycloak PostInstall need to be made idempotent

---

ci/multicluster/Jenkinsfile

Perform a cluster dump on a MC install failure.  This will generate 2 cluster dumps, 1 for each cluster.

cluster dump on MC install failure

---

platform-operator/scripts/install/3-install-verrazzano.sh

This change adds the --timeout 10m flag to the helm upgrade command for Weblogic Kubernetes Operator. There was an upgrade pipeline run that failed because the WKO helm command timed out. It has a default timeout of 5m and it took 4m58s to pull the image.

VZ-4388 increase wko timeout

---

tests/e2e/loggingtrait/helidonworkload/helidon_loggingtrait_test.go
tests/e2e/scrapegenerator/helidon/helidon_scrape_generator_test.go
tests/e2e/security/netpol/network_policy_test.go

This change adds cluster dumps after a failure to the app tests that don't have it. These are the helidon loggingtrait test, the helidon scrape generator test, and the network policy test. This will allow the team to debug any failures that stem from these tests. Currently, the app namespaces get blown away and so there is no way to debug them.

VZ-4410: Add cluster dumps to app tests that don't have it

---

THIRD_PARTY_LICENSES.txt
go.mod
go.sum
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/oci/logging/ocilogging_suite_test.go
tests/e2e/oci/logging/ocilogging_test.go
tests/e2e/pkg/springboot.go

This PR adds automated e2e tests for the OCI Logging integration. The tests validate that log records appear in both the system and default application Log objects in OCI. The PR includes some refactoring to share the code for deploying and undeploying the Springboot example application.
Note that I added a dependency to `go.mod` for the OCI Golang SDK. The SDK is used to search for log records in OCI. Because this dependency is used only by tests, no additional licenses needed to be added to `THIRD_PARTY_LICENSES.txt` (at least that's my understanding).
Also note that the OCI Log Group and Log objects must exist prior to running this test. The next task is to integrate this test suite into a CI/CD pipeline that will test OCI service integrations. That pipeline will create the cluster, …

VZ-4137: Automated tests for the OCI Logging integration

---

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component_test.go

Fix the Keycloak isReady check for secret existence instead of certificate existence.  The check is better because, in the end, Keycloak needs the existence of the tls secret to offer its services publicly.  
- [ x] Added or updated unit tests for any new functions I added

Fix isReady check to look for TLS secret

---

ci/oci-integration/Jenkinsfile
tests/e2e/config/scripts/create_oci_logging_resources.sh
tests/e2e/config/scripts/delete_oci_logging_resources.sh
tests/e2e/config/scripts/install-verrazzano-nipio-with-persistence.yaml
tests/e2e/config/scripts/process_nipio_install_yaml.sh
tests/e2e/oci/logging/ocilogging_test.go

@michael-cico and I collaborated on this PR. It includes a new Jenkins pipeline for running OCI services integration tests along with scripts to create and delete OCI Log objects needed for the OCI Logging tests.
I also had to update the OCI Logging tests to support running from the CI/CD pipeline. The OCI SDK needed to be configured slightly differently, so now the tests can be run both locally and from CI/CD.
Fixes VZ-4281

VZ-4281: CI/CD pipeline and supporting scripts for running OCI services integration tests

---

Jenkinsfile
JenkinsfileCopyrightTest
Makefile
application-operator/hack/add-crd-header.sh
application-operator/hack/add-yml-header.sh
ci/scripts/check_if_clean_after_generate.sh
image-patch-operator/hack/add-crd-header.sh
image-patch-operator/hack/add-yml-header.sh
platform-operator/hack/add-crd-header.sh
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
tools/copyright/copyright.go
tools/fix-copyright/copyright.go

Re-enables the copyright check fixes for VZ-4390, and disables the fix-copyright tool for now.
- Also, add `.test` files to the ignored file extensions.
Fixes VZ-4390.

VZ-4390.  Re-enable copyright fixes, and disable fix-copyright tool for now

---

ci/private-registry/Jenkinsfile

delete the images from the image registries as the very first thing in the "always" directive
Signed-off-by: Prasad Shirodkar <prasad.shirodkar@oracle.com>
Fixes VZ-9999

VZ-4219: Private registry tests are leaking repositories in the tenancy

---

tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/metrics/deploymetrics/deploymetrics_test.go

Add clusterdump wrappers to deploymetrics and authproxy tests.  This will dumpcluster on aftersuite failure, where we are seeing namespace deletion hang.

Add clusterdump wrappers to deploymetrics and authproxy tests

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml

Back port Fluentd config to enable the "log_es_400_reason" to capture more information when Elasticsearch returns an HTTP 400 response.

No JIRA: Back port Fluentd config "log_es_400_reason" switch to release-1.1 branch

---

application-operator/constants/constants.go
application-operator/controllers/namespace/namespace_controller.go
application-operator/controllers/namespace/namespace_controller_test.go
application-operator/main.go
pkg/controller/requeue.go
pkg/controller/requeue_test.go
pkg/string/slice.go
pkg/string/slice_test.go
platform-operator/controllers/clusters/vmc_controller.go
platform-operator/controllers/verrazzano/controller.go

Adds a namespace controller to the VPO to monitor namespace activity with respect to the new OCI logging feature
- Monitors namespace lifecycle (CRUD), looks for the OCI Logging annotation on the namespace
- If the annotation is detected during a namespace create/update, add a finalizer and call out to (currently placeholder) functions to update the fluentd configuration; it is expected that this will be idempotent
- if the annotation is not present during a namespace update, call the function to remove the OCI logging configuration for that namespace; it is expected that this will be idempotent
- During a namespace deletion, remove any OCI logging configuration for the namespace; it is expected that this will be idempotent
- add unit tests
- refactor common string and controller utils …

VZ-4147.  VPO namespace controller for OCI logging management

---

application-operator/controllers/namespace/fluentd_configmap.go
application-operator/controllers/namespace/fluentd_configmap_test.go
application-operator/controllers/namespace/namespace_controller.go
application-operator/controllers/namespace/namespace_controller_test.go
application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
pkg/constants/constants.go
platform-operator/constants/constants.go
platform-operator/controllers/verrazzano/component/istio/istio_component.go
platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
platform-operator/controllers/verrazzano/component/istio/istio_install_test.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go
tests/e2e/pkg/fluentd.go
tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go

This PR integrates the new namespace controller with the code to update the Fluentd configmap and restart Fluentd. Also has bug fixes found during integration testing, updated controller unit tests, and a bunch of refactoring to share constants.
I have tested this manually and confirmed that it works as expected. I will have another PR to extend the automated e2e tests that includes testing this new functionality.
Fixes VZ-4453

VZ-V4453: Integrate OCI Logging code

---

application-operator/mcagent/mcagent.go
application-operator/mcagent/mcagent_test.go
pkg/constants/constants.go
tests/e2e/pkg/fluentd.go

I reverted a commit to master, and a subsequent build of master failed because the copyright checker thinks the files were updated but don't have the correct year in the copyright header.
This PR fixes those four files to get master building again.

No JIRA: Update copyrights

---

platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go

MySQL is a soft dependency on KeyCloak, we shouldn't need to block until MySQL is fully ready.

mysql soft dependency

---

ci/oci-integration/Jenkinsfile

Fix a bad Jenkinsfile. `Environment` is illegal in `stages`. My first thought was to move the env vars to the global env section, but after looking at all of the other Jenkinsfiles, none of them do that, these env vars are added specifically to all of the AT stages. I followed suit.

No JIRA: Fix broken Jenkinsfile

---

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml

This PR allows a user to configure OCI Logging using a secret containing OCI API configuration. There are two parts to this:
1. Update the helm template to mount the secret data into the Fluentd pods on install
2. Install pre-configuration function update that copies the user-supplied secret from the `verrazzano-install` namespace to the `verrazzano-system` namespace. I also did some refactoring to move the secret copying into a function to reduce duplication.
Implements VZ-4140

VZ-4140: Support user-supplied API creds for OCI Logging integration

---

platform-operator/scripts/install/create_oci_config_secret.sh
platform-operator/scripts/install/create_oci_fluentd_secret.sh
platform-operator/scripts/install/oci_secret_common.sh

Create a helper script to create an OCI config secret for the fluentd OCI plugin.
- Also creates a common base script for both this and the helper that creates an OCI secret for `external-dns`/`Cert-Manager`
Fixes VZ-4142.

VZ-4142.  Helper script for creating a secret for the fluentd OCI plugin

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml

Currently, the auth.lua logger is emitting messages too quickly with little useful information. In response, I have downgraded all of the info messages to debugging. This is a first pass at fixing this issue. Future iterations will need to expand upon the error logging.
Fixes VZ-4467

VZ-4467 Change log levels in the auth lua to remove verbosity

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml

After discussion with the team, it seems important to eliminate load on ES by reducing the amount of log messages in the AuthProxy. This includes updating the buffer size to 256Kb. We will keep an eye on this with load testing that will hopefully tell us how this change affects performance.
Fixes VZ-4627

VZ-4627 update the buffer size to eliminate large ES request warning

---

ci/oci-integration/Jenkinsfile
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
tests/e2e/config/scripts/process_kind_install_yaml.sh
tests/e2e/config/scripts/setup_ssh_tunnel.sh

This PR extends the CI/CD OCI service integration pipeline to test the case where OCI Logging is configured with OCI user API credentials. The pipeline now runs two parallel stages: One with an OKE cluster that uses the default instance principal auth and another with a KinD cluster that uses user API credentials.
In addition to the Jenkinsfile changes, this PR includes:
1. A fix to the Fluentd config match rules to include two KinD namespaces for the system log
2. A bug fix in an OKE cluster setup script. The `sshuttle` process was started in the background, and in some cases we tried to run `kubectl` commands against the cluster before `sshuttle` had completed the tunnel connection. The result was that the scripts failed waiting for the cluster to be ready, which failed the pipeline. I …

VZ-4143: Update CI/CD pipeline to test OCI Logging with user API creds

---

platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go
platform-operator/controllers/verrazzano/component/externaldns/external_dns.go

Add validation in the VPO validating wehbook for the Fluentd OCI config secret if present in the Verrazzano CR.
Fixes VZ-4616.

VZ-4616.  Add webhook validator for the Fluentd OCI config secret

---

ci/ticket-commits/JenkinsfilePullRequests

The PR ticket commits job fails if the PR title contains double quotes. I fixed the Jenkinsfile to escape double quotes in the PR title before passing the string to the helper.

No JIRA: Fix bug in PR ticket commits pipeline, escape " in PR title

---

JenkinsfileCopyrightTest
ci/multiplatform/Jenkinsfile
ci/rolebased/Jenkinsfile
ci/upgrade/Jenkinsfile

Remove PagerDuty Alerts from individual test jobs. We do not page on build/test failures except for periodic and non-commit driven runs now.
These will continue to send a slack message, so someone wanting notification early on those tests needs to watch slack.

Removing PagerDuty notifications from individual jobs

---

tests/e2e/verify-install/kiali/kiali_test.go

The Kiali test in the upgrade pipeline fails intermittently. We looked at several of the recent failures and the test always fails attempting to get the ingress. Wrapping the get of the ingress in Eventually seems to solve the problem.
Fixes VZ-4749

VZ-4749: Wrap call to get Kiali ingress in Eventually

---

platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go
platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
platform-operator/main.go

Re-re-introduce the fluentd OCI auth secret validation again, and fix the case for `instance_principal` auth validation.
Fixes VZ-4616

VZ-4616.  Re-introduce validator, and fix instance-principal case

---

ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oci-integration/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/private-registry/Jenkinsfile
ci/scripts/derive_kubernetes_version.sh
ci/uninstall/Jenkinsfile
pkg/test/framework/metrics/ginkgo_metrics.go

This PR makes use of the existing system property set by most of the Jenkins scripts for the Kubernetes version. A script is added to obtain a consistent Kubernetes version. 
This change also has the change to include the labels added for the feature set while emitting the metrics from the tests.
Contributes to VZ-4601

Fix the issue with getting the Kubernetes version in new test framework

---

pkg/helm/helmcli.go
platform-operator/main.go

This change adds a helm-debug platform-operator flag. When set to true, this adds a --debug helm flag that will be added to helm commands. This can be enabled in conjunction with debug logging to get more detailed logs on failures in helm commands. It is especially useful for debugging when helm commands time out.

VZ-4712: Add optional helm --debug flag

---

tests/e2e/verify-install/verrazzano/verrazzano_test.go

Add additional check that affinity struct is not nil
Fixes VZ-9999

VZ-4747 - Add check for affinity to not be nil

---

platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go

Remove the RSA header check from the private key validation in the VPO.
Fixes VZ-4616.

VZ-4616.  Remove private key header check from OCI auth secret validation

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml

This pull request adds fluentd parsing/filter rules for oam-kubernetes runtime log files.  In addition, removes unneeded settings from previous fluentd PR.

VZ- 4774: add fluentd parsing for oam-kubernetes-runtime log files

---

pkg/controller/requeue.go
platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/clusters/sync_manifest_secret.go
platform-operator/controllers/clusters/sync_prometheus.go
platform-operator/controllers/clusters/sync_registration_secret.go
platform-operator/controllers/clusters/vmc_controller.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/controllers/verrazzano/controller.go

Cleanup logging for Multicluster
1. Use VerrazzanoLogger
2. Don't return error to controller-runtime
3. Cleanup log message

VZ-4767 multi-cluster logging

---

tests/e2e/config/scripts/terraform/cluster/create-cluster.sh

There have been test pipeline failures due to network connectivity issues when performing `terraform plan`. This PR updates the script to add retries when `terraform plan` fails.

No JIRA: Add retries around terraform plan

---

pkg/test/framework/ginkgo_wrapper.go
pkg/test/framework/metrics/ginkgo_metrics.go

This PR fixes the code location reported by some of the test wrappers, so that they will show the actual test source line where the wrapper is called, not the location of the wrapper code.
Fixes VZ-4794

Fix the code location reported by framework

---

application-operator/controllers/webhooks/metrics-binding-labeler-pod.go
application-operator/controllers/webhooks/metrics-binding-labeler-pod_test.go
application-operator/internal/app/resources/templates/standard-k8s-metrics-template.yaml

The default template and the pod labeler have been updated to allow for Prometheus config overrides. The port, path, and scrape enabling can be modified through annotations.
Fixes VZ-4407

VZ-4407 Allow Prometheus port, path, and scrape overrides

---

tests/e2e/security/netpol/network_policy_test.go

Fix network-policy test to wait for hello-helidon pods to be running.  Previous change to the this test did not include this test which can cause an intermittent failure.

Add check for helidon pod running in network-policy AT

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/verify-infra/restapi/vmi_urls_test.go

This PR introduces FlakeAttempts decorations on frequently failing tests, so that they will be retried before being considered a failure.  Testing shows that this change reduces the test failure rate from about 0.08% to around 0.02%, and none of the tests that were such decorated failed in that testing (around ten full/slow/triggered runs).
Contributes to VZ-4793

Introduce FlakeAttempts to improve test resiliency

---

platform-operator/controllers/verrazzano/controller.go

PR to backport adding a call to delete vz resource from initializedSet after uninstall is finished.
Fixes VZ-4558

VZ-4558 vz resource cleanup from initializedSet post uninstall (#2504)

---

platform-operator/controllers/verrazzano/component/authproxy/testdata/affinityOverrideValues.yaml
platform-operator/controllers/verrazzano/component/authproxy/testdata/dnsWildcardDomainOverrideValues.yaml
platform-operator/controllers/verrazzano/component/authproxy/testdata/enabledOverrideValues.yaml
platform-operator/controllers/verrazzano/component/authproxy/testdata/noOverrideValues.yaml
platform-operator/controllers/verrazzano/component/authproxy/testdata/replicasOverrideValues.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/basicManagedClusterMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devKeycloakInstallArgsStorageOverride.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/managedClusterEnableAllOverrideMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml
platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go
platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml
platform-operator/manifests/profiles/base.yaml
platform-operator/manifests/profiles/prod.yaml

- Specify the default and override values for AuthProxy Kubernetes settings via the Verrazzano profile files, instead of through values.yaml

VZ-4705 Default values for new AuthProxy component using profile overrides

---

platform-operator/helm_config/overrides/mysql-values.yaml

Add extraInitContainer to MySQL to chown the data directory to the mysql user/group
Fixes VZ-4953

VZ-4953 part 2 - Add extraInitContainer to MySQL to chown the data directory to the mysql user/group so that upgrade works

---

platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher_test.go

When Verrazzano is using letsencryt production mode, root CA would be empty, and there should not be a secret tls-ca-additional, we can not throw an error in this case. Instead, we use the default RootCAs.
Fixes VZ-9999

fix letsencrypt production in 1.2

---

platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher_test.go

When Verrazzano is using letsencryt production mode, root CA would be empty, and there should not be a secret tls-ca-additional, we can not throw an error in this case. Instead, we use the default RootCAs.

fix letsencrypt production in 1.1

---

platform-operator/controllers/clusters/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher.go
platform-operator/controllers/verrazzano/component/common/rancher_test.go

When Verrazzano is using letsencryt production mode, root CA would be empty, and there should not be a secret tls-ca-additional, we can not throw an error in this case.  Instead, we use the default RootCAs.

fix  letsencryt production 

---

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
tests/e2e/logging/system/system_logging_test.go

This pull request adds fluentd parsing rules for Rancher namespace logs.  The logs are parsed for containers in the following namespaces: cattle-system, fleet-system, local-path-storage, and rancher-operator-system

VZ-4966: Add fluentd parsing rules for Rancher namespace logs

---

ci/lre/Jenkinsfile

jenkins throttle job property set to limit to one job by mistake.

modify limitonejob property

---

platform-operator/controllers/verrazzano/component/istio/istio_cr.go

Remove unnecessary Affinity if in istio operator Go Template
Fixes VZ-9999

Remove if Affinity in go template since it will always be valued

---

tests/testdata/ingress/console/components.yaml

The Console ingress test has the wrong namespace in the MySQL URL. It happens to work because the todo example app test runs at the same time, but the test fails if the todo MySQL pod goes away before this test runs.
The fix removes the qualified domain since it's not needed.
Also, the test uses an older MySQL image so I replaced it with the latest.

No JIRA: Fix Console ingress test

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/helidon/helidon_example_test.go
tests/e2e/examples/helidonconfig/helidon_config_test.go
tests/e2e/examples/socks/sock_shop_example_test.go
tests/e2e/examples/springboot/springboot_test.go
tests/e2e/examples/todo/todo_list_test.go
tests/e2e/ingress/console/console_ingress_test.go
tests/e2e/istio/authz/authpolicy_test.go
tests/e2e/logging/helidon/helidon_logging_test.go

This test fixes the incorrect initialization of variables in some tests, so that those tests will work when run in parallelized and randomized fashion.
Fixes VZ-4991

Fix bad var init - so it will work in parallel and randomized runs

---

ci/looping-test/Jenkinsfile
ci/looping-test/JenkinsfileCreateCluster
ci/multicluster/Jenkinsfile
ci/multiplatform/Jenkinsfile
ci/oke-ocidns/Jenkinsfile
ci/uninstall/Jenkinsfile
tests/e2e/config/scripts/terraform/cluster/variables.tf

The release-1.0 branch has failed pipelines because the OKE version defaults to 1.18 and 1.18 is no longer an option in OKE. This PR updates the versions based on what is currently available.

No JIRA: Update OKE versions

---

pkg/helm/chart.go
pkg/helm/helmcli.go
pkg/helm/helmcli_test.go
platform-operator/controllers/verrazzano/component/helm/helm_component.go
platform-operator/controllers/verrazzano/component/helm/helm_component_test.go
platform-operator/controllers/verrazzano/component/registry/registry_test.go

Add an additional check to the common IsReady function.  Compare the chart app-version being installed/upgraded with the app-version of the chart currently installed.  If they do not match, then IsReady will fail.  This check was added because the function was only checking if the chart is deployed, but not which version of the chart.
Fixes VZ-5026

VZ-5026 Add common check for IsReady for AppVersions

---

platform-operator/internal/k8s/certificate/certificate.go
platform-operator/internal/k8s/certificate/certificate_test.go

Update to k8s.io/api/admissionregistration/v1 for Kubernetes 1.22 support
Fixes VZ-4150

VZ-4150 Update to k8s.io/api/admissionregistration/v1 for Kubernetes 1.22 support

---

platform-operator/controllers/verrazzano/component/authproxy/authproxy.go

The helm override file for the authproxy helm chart was named "verrazzano-overrides".  Instead it is now named "authproxy-overrides".

Change name of authproxy overrides file to be more intuitive

---

platform-operator/helm_config/overrides/mysql-values.yaml

VZ-5017 - Use busybox template values for chown-data-dir initContainer in mysql-values.yaml
Fixes VZ-5017

VZ-5017 - Use busybox template values for chown-data-dir initContainer in mysql-values.yaml

---

tests/e2e/multicluster/examples/example_utils.go
tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go
tests/e2e/multicluster/examples/helidon-ns-ops/helidon_example_delete_ns_test.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go
tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go
tests/e2e/multicluster/examples/sock-shop/sock_shop_example_utils.go
tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go
tests/e2e/multicluster/examples/todo-list/todo_list_example_utils.go

This PR fixes few test cases which were left out in the initial change for VZ-5016. Here is the description provided for the previous PR, which is applicable here as well.
The utility function isPodRunning used by the tests to find out whether the pods with a given prefix and the namespace are up and running, is enhanced to return an error in the event of ImagePullBackOff and CrashLoopBackoff. The tests (except few) are updated to handle the error and abort the test run, rather than waiting for the duration specified by the timeout.
Contributes to VZ-5016

VZ-5016: Fail test immediately when the container enters ImagePullBackOff or CrashLoopBackoff state

---

platform-operator/verrazzano-bom.json

Uptake the latest Rancher images that include upgraded dependencies. Rebuilding the Rancher images upgraded the patch version of rancher-webhook so that also needed to be updated in the BOM.
Fixes VZ-5077

VZ-5077: Uptake latest Rancher images

---

platform-operator/apis/verrazzano/v1alpha1/validate.go
platform-operator/apis/verrazzano/v1alpha1/validate_test.go
platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go
tools/scripts/generate_bom.sh

This reverts commit c1493ff7bc3ee7311e23e2abf1249960a86a2bce.
Reverts VZ-5014 as there is an existing unit test that is supposed to catch this error during build time

Revert "VZ-5014 Added build and runtime validation to check if BOM file is a valid JSON (#2578)

---

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml
tests/e2e/security/netpol/network_policy_test.go

Enable network policy ingress from kiali to prometehus
Fixes VZ-5189

Enable network policy ingress from kiali to prometehus

---

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml
tests/e2e/security/netpol/network_policy_test.go

Enable network policy ingress from kiali to prometheus
Fixes VZ-5189

Enable network policy ingress from kiali to prometheus(1.1)

---

platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml
tests/e2e/security/netpol/network_policy_test.go

Enable network policy ingress from kiali to prometheus
Fixes VZ-5189

Enable network policy ingress from kiali to prometheus(1.2)

---

platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml

Signed-off-by: stshapir <steven.shapiro@oracle.com>
This change should have been made with the previous PR's to exclude namespace kube-system from being watched.
Fixes VZ-3458

VZ-3458 Add namespace selector to vpo webhook config

---

platform-operator/controllers/verrazzano/controller_test.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_component.go
platform-operator/controllers/verrazzano/upgrade_test.go
platform-operator/mocks/controller_mock.go

Do not set the Verrazzano CR status to UpgradeComplete until upgrade is completely done, including restarting all of the components needed for new Istio sidecar injection.
I broke up the code to have an overall upgrade for the Verrazzano CR, and a component upgrade.  This makes it easier to understand the overall flow (IMO).

VZ-4821 Don't set Verrazzano CR to UpgradeComplete until it is completely done

---

platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go
platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall_test.go
platform-operator/controllers/verrazzano/component/rancher/rancher_test.go

Fixes issue where install was attempting to update the admin password by execing into a rancher pod but was picking a non-running pod.  This change selects the first rancher pod found running to perform the operations.

VZ-4365: Rancher post-install step failed to reset admin password

---

application-operator/config/webhook/manifests.yaml
application-operator/constants/constants.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller.go
application-operator/controllers/clusters/multiclusterapplicationconfiguration/controller_test.go
application-operator/controllers/clusters/multiclustercomponent/controller.go
application-operator/controllers/clusters/multiclustercomponent/controller_test.go
application-operator/controllers/clusters/multiclusterconfigmap/controller.go
application-operator/controllers/clusters/multiclusterconfigmap/controller_test.go
application-operator/controllers/clusters/multiclustersecret/controller.go
application-operator/controllers/clusters/multiclustersecret/controller_test.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller.go
application-operator/controllers/clusters/verrazzanoproject/verrazzanoproject_controller_test.go
application-operator/controllers/cohworkload/coherenceworkload_controller.go
application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
application-operator/controllers/helidonworkload/helidonworkload_controller.go
application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
application-operator/controllers/ingresstrait/ingresstrait_controller.go
application-operator/controllers/ingresstrait/ingresstrait_controller_test.go
application-operator/controllers/metricstrait/metricstrait_controller.go
application-operator/controllers/metricstrait/metricstrait_controller_test.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml

Backporting changes from https://github.com/verrazzano/verrazzano/pull/2654 https://github.com/verrazzano/verrazzano/pull/2676 and https://github.com/verrazzano/verrazzano/pull/2689
Fixes VZ-3458

VZ-3458 Webhooks should not watch kube-system namespace

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go

VZ-3631: WLS has a bug at server startup where it can corrupt messages, so there are cases where we can get pattern not matched failures which are due to that, removing the tests that expect that this will never happen.

Tvlatas/vz 3631 backport to 1.2 (test change only)

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go

VZ-3631: WLS has a bug at server startup where it can corrupt messages, so there are cases where we can get pattern not matched failures which are due to that, removing the tests that expect that this will never happen.

Tvlatas/vz 3631 backport to 1.1 (test change only)

---

tests/e2e/examples/bobsbooks/bobs_books_test.go
tests/e2e/examples/todo/todo_list_test.go

VZ-3631: WLS has a bug at server startup where it can corrupt messages, so there are cases where we can get pattern not matched failures which are due to that, removing the tests that expect that this will never happen.

Tvlatas/vz 3631 backport to 1.0 (test change only)

---

platform-operator/helm_config/overrides/oam-kubernetes-runtime-values.yaml
platform-operator/thirdparty/charts/oam-kubernetes-runtime/values.yaml

After we restore a sample app like bobs-books to a new cluster , we see the OAM operator going into crashloop as it runs out of memory when apps are restored together

VZ-5047: Removing limits from OAM runtime

---

platform-operator/controllers/verrazzano/upgrade.go
platform-operator/controllers/verrazzano/upgrade_test.go

Code currently exists to remove helm component release secrets that present a 'pending-upgrade' status in order to un-block the given upgrade.  This PR expands the statuses that qualify for this workaround to all statuses other than 'deployed'
Fixes VZ-5020

JIRA: VZ-5020 clear helm upgrades blocked due to any status other than 'deployed'

---

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
platform-operator/controllers/verrazzano/component/helm/helm_component.go
platform-operator/controllers/verrazzano/controller.go
platform-operator/controllers/verrazzano/install.go
platform-operator/controllers/verrazzano/install_test.go
platform-operator/controllers/verrazzano/upgrade.go
platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml

* allow re-entry of install flow by resetting the component state to disabled to restart the install flow 
* add LastReconciledGeneration to component state
* at the end of install or upgrade, component.LastReconciledGeneration is set to VerrazzanoCR.Generation
* update(re-install) is triggered when component.LastReconciledGeneration < VerrazzanoCR.Generation
* test with following CR, it moved an 'InstallComplete' verrazzano to 'InstallStarted' to update/scale the authProxy to 2 replicas:  
```
apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
name: my-verrazzano
spec:
profile: dev
components:
authProxy:
kubernetes:
replicas: 2
```
Fixes VZ-5171

VZ-5171 re-entry into the install flow

---

pkg/test/framework/ginkgo_wrapper.go
tests/e2e/logging/system/system_logging_test.go
tests/e2e/metrics/syscomponents/metrics_test.go
tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go
tests/e2e/multicluster/examples/helidon/helidon_example_test.go
tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go
tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go
tests/e2e/multicluster/verify-register/verify_register_test.go
tests/e2e/pkg/conditional_spec.go
tests/e2e/pkg/kubernetes.go
tests/e2e/pkg/metrics.go
tests/e2e/pkg/vmi/elastic.go
tests/e2e/scripts/install/install_test.go
tests/e2e/security/netpol/network_policy_test.go
tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
tests/e2e/verify-infra/vmi/vmi_test.go
tests/e2e/verify-install/kiali/kiali_test.go
tests/e2e/verify-install/kubernetes/kubernetes_test.go
tests/e2e/verify-install/verrazzano/verrazzano_test.go
tests/e2e/verify-install/web/nginx_errors_test.go
tests/e2e/verify-install/web/web_test.go

Refactor tests to explicitly pass a kubeconfigPath to IsVerrazzanoMinVersion and GetClusterNameMetricsLabel
Fixes VZ-5277

VZ-5277 - Refactor tests to explicitly pass a kubeconfigPath to IsVerrazzanoMinVersion and GetClusterNameMetricsLabel

---

application-operator/controllers/namespace/namespace_controller.go
application-operator/controllers/namespace/namespace_controller_test.go

This is a small change to the namespace controller to not reconcile namespaces with the name kube-system
Fixes VZ-3458

VZ-3458 Namespace controller should not be reconciled for kube-system namespace

---

pkg/log/vzlog/vzlog.go
pkg/log/vzlog/vzlog_test.go

Logging a Progress message is ignored if it has been logged previously and a new progress message has been logged.
This is a logic bug in the Verrazzano logger.   The vzlog.go doLog method is putting an old progress message in the trash if a new progress message is logged.  

VZ-5311  Bug, progress logging skipping old messages

---

platform-operator/controllers/verrazzano/component/mysql/mysql.go
platform-operator/controllers/verrazzano/component/mysql/mysql_component.go
platform-operator/controllers/verrazzano/component/mysql/mysql_component_test.go
platform-operator/controllers/verrazzano/component/registry/registry_test.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go

Reject any persistence changes that are not supported:
- If the volumeSource or defaultVolumeSource is changed from emptyDir to persistent storage, or vice-versa
- If the requested volume size is different than the current size
- If the storage class is changed
Fixes VZ-5236

VZ-5236 Reject changes to persistence settings until supported

---

platform-operator/controllers/verrazzano/component/appoper/app_operator.go
platform-operator/controllers/verrazzano/component/authproxy/authproxy.go
platform-operator/controllers/verrazzano/component/certmanager/certmanager.go
platform-operator/controllers/verrazzano/component/coherence/coherence.go
platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
platform-operator/controllers/verrazzano/component/istio/istio_component.go
platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/kiali/kiali.go
platform-operator/controllers/verrazzano/component/mysql/mysql.go
platform-operator/controllers/verrazzano/component/nginx/nginx.go
platform-operator/controllers/verrazzano/component/oam/oam.go
platform-operator/controllers/verrazzano/component/rancher/rancher.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano.go
platform-operator/controllers/verrazzano/component/weblogic/weblogic_operator.go
platform-operator/internal/k8s/status/daemonset_ready.go
platform-operator/internal/k8s/status/daemonset_ready_test.go
platform-operator/internal/k8s/status/deployment_ready.go
platform-operator/internal/k8s/status/deployment_ready_test.go
platform-operator/internal/k8s/status/pod_ready.go
platform-operator/internal/k8s/status/statefulset_ready.go
platform-operator/internal/k8s/status/statefulset_ready_test.go

This pull request is a followup pull request to remove the need to explicitly specify a label selector for is ready checking.  The label selector is retrieved from the workload resource instead.  Also, removed the use of the PodReadyCheck type that is not needed.

VZ-5027: followup to not explicity specify label selector for isReady checks

---

platform-operator/verrazzano-bom.json

VZ-4290 pick up console fix to display SprintBoot application without errors when workload metadata has no namespace

---

platform-operator/controllers/verrazzano/component/istio/app_restart.go
platform-operator/controllers/verrazzano/component/istio/app_restart_test.go
platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
platform-operator/controllers/verrazzano/component/istio/platform_restart.go
platform-operator/controllers/verrazzano/component/istio/platform_restart_test.go

During upgrade, if Verrazzano installs a new Istio version with a new proxyv2 image, then all apps with the old Istio sidecar must be restarted.  Previously, we always restarted the apps.
Also, make some log messages consistent.

VZ-5254 only restart apps if they have the old Istio sidecar proxy

---

platform-operator/verrazzano-bom.json

VZ-4290 pick up console fix to display SprintBoot application correctly when workload metadata has no namespace

---

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go
platform-operator/controllers/verrazzano/component/certmanager/certmanager_component.go
platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go
platform-operator/controllers/verrazzano/upgrade.go

Fixes the re-entry into the CertManager and Keycloak components when DNS and Cert-Manager are updated
- Have Keycloak rebuild the PKCE client URIs in the realm config
- Have Cert-Manager update the ClusterIssuer in both `PostInstall` and `PostUpgrade`
- Add some Cert-Manager and Keycloak component unit tests to validate updates, and update during upgrade
- Also fix an issue in the Keycloak component to fix the certificate checks
Fixes VZ-5117.

VZ-5117.  Fixes for DNS and Cert-Manager updates

---

platform-operator/verrazzano-bom.json

Enabled S3 plugin in open-search repository. This image will have the s3 plugin enabled by default which we will be using for backup and restore . 

VZ-5373: Update opensearch image with s3 plugin

---

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
ci/private-registry/Jenkinsfile
platform-operator/controllers/verrazzano/component/appoper/app_operator.go
platform-operator/controllers/verrazzano/component/appoper/app_operator_test.go
platform-operator/controllers/verrazzano/testdata/test_bom.json
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
platform-operator/verrazzano-bom.json
tests/e2e/config/scripts/create_ocir_repositories.sh
tools/scripts/README.md

- add weblogic-monitoring-exporter image to BOM
-  weblogic-monitoring-exporter image in BOM is passed to VPO as env WEBLOGIC_MONITORING_EXPORTER_IMAGE
- VAO set spec.monitoringExporter.image in domain to the specified WEBLOGIC_MONITORING_EXPORTER_IMAGE; unset spec.monitoringExporter.image for empty WEBLOGIC_MONITORING_EXPORTER_IMAGE, which means WebLogic Monitoring Exporter uses its default image.
- update private registry instruction to add more public images
Fixes VZ-5319

VZ-5319 Support weblogic-monitoring-exporter in private registry configurations

---

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
platform-operator/controllers/verrazzano/component/appoper/app_operator.go
platform-operator/controllers/verrazzano/component/appoper/app_operator_test.go
platform-operator/controllers/verrazzano/testdata/test_bom.json
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
platform-operator/verrazzano-bom.json
tests/e2e/config/scripts/create_ocir_repositories.sh
tools/scripts/README.md

Backport https://github.com/verrazzano/verrazzano/pull/2765
Fixes VZ-5319 in release 1.2

backport VZ-5319 Support weblogic-monitoring-exporter in private registry configurations

---

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
platform-operator/controllers/verrazzano/component/verrazzano/vmi.go

This is required for backing up OpenSearch. This will allow the repository-s3 plugin to backup indicess to an S3 compatible object store

VZ-5377: Opensearch backup preparedness

---

platform-operator/scripts/uninstall/uninstall-steps/1-uninstall-istio.sh
platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh

This will remove all the ingress from ExternalDNS so that the DNS records get deleted before ExternalDNS is uninstalled.
Fixes VZ-5050

VZ-5050 Remove all Verrazzano Ingresses before uninstall of ExternalDNS

---

ci/chaos/Jenkinsfile
ci/chaos/JenkinsfileResiliencyTrigger
platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go
platform-operator/controllers/verrazzano/controller.go

When upgrading an environment configured to use ephemeral storage, rebuild the keycloak configuration to it's default settings.  Previous to this change the upgrade would fail because the Keycloak configuration is lost when the MySQL pod recycles.
A subsequent PR will address the issue of the MySQL pod unexpectedly getting recycled at any time.
Fixes VZ-9999

VZ-5087 Rebuild keycloak config on upgrade using ephemeral storage

---

tests/e2e/verify-install/prometheusoper/prometheusoper_suite_test.go
tests/e2e/verify-install/prometheusoper/prometheusoper_test.go

This adds a test to verify the Prometheus Operator install. The resources to be verified are as follows:
- The `verrazzano-monitoring` namespace exists
- The Prometheus Operator pod is running
- The CRDs for the Prometheus Operator exist
- The TLS secret for the stack webhook exists
Fixes VZ-5304

VZ-5304 Prometheus Operator install e2e test

---

ci/chaos/Jenkinsfile
ci/multicluster/Jenkinsfile
ci/upgrade/Jenkinsfile

This pull request bumps the default starting point for upgrades to 1.0.2.  This prevents failures we are seeing with Kibana pods not starting and the health of the ES cluster being yellow before upgrade.

Bump VERSION_FOR_INSTALL TO 1.0.2 for starting point of upgrade

---

tests/e2e/verify-install/prometheusoper/prometheusoper_suite_test.go
tests/e2e/verify-install/prometheusoper/prometheusoper_test.go

Resubmitting the end-to-end tests of Prometheus Operator.
Reverts verrazzano/verrazzano#2799

VZ-5304: Prometheus Operator install e2e test

---

platform-operator/verrazzano-bom.json

VZ-5029 pick up console fix to remove error when VMC has no apiUrl in status, and show component status info if all apps pending

---

platform-operator/controllers/verrazzano/component/prometheusoper/prometheus.go
platform-operator/controllers/verrazzano/component/prometheusoper/prometheus_component.go
platform-operator/helm_config/charts/verrazzano/templates/verrazzano-monitoring.yaml
platform-operator/helm_config/charts/verrazzano/values.yaml
platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh

This moves the namespace creation for the Prometheus Operator from the helm chart to the PreInstall function.
Fixes VZ-5214

VZ-5214 Move Prometheus Operator namespace creation to PreInstall

---

platform-operator/controllers/clusters/sync_registration_secret.go
platform-operator/controllers/clusters/vmc_controller_test.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_component_test.go
platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go
platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml
platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-ingress.yaml
tests/e2e/config/scripts/register_managed_cluster.sh
tests/e2e/pkg/api.go
tests/e2e/pkg/keycloak.go
tests/e2e/pkg/web.go
tests/e2e/verify-infra/restapi/rancher_url_test.go
tools/cli/vz/cmd/login/login.go
tools/cli/vz/cmd/login/login_test.go

rename the tls secret from env-secret to verrazzano-tls and keycloak-tls
Fixes VZ-5414

VZ-5414 rename tls secret for verrazzano and keycloak

---

application-operator/controllers/ingresstrait/ingress_watch_test.go
application-operator/controllers/ingresstrait/ingresstrait_controller.go

The ingress watch added for the IngressTrait controller only filters on type; this fixes the filtering to happen in the watch predicate to limit the amount of reconciles triggered by an DNS change.
Fixes VZ-5370.

Refine IngressTrait controller Ingress watch

---

application-operator/controllers/metricsbinding/metricsbinding_controller.go
application-operator/controllers/metricsbinding/metricsbinding_controller_test.go
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
tests/e2e/metricsbinding/helidon-deployment/helidon_deployment_test.go
tests/e2e/metricsbinding/helidon-pod-annotation-overrides/helidon_pod_annotation_overrides_test.go
tests/e2e/metricsbinding/helidon-pod/helidon_pod_test.go
tests/e2e/metricsbinding/helidon-replicaset/helidon_replicaset_test.go
tests/e2e/metricsbinding/helidon-statefulset/helidon_statefulset_test.go
tests/e2e/metricsbinding/metrics_binding_helper.go

This pull request fixes scraping of POKO metrics with the namespace the workload is running in has istio-injection disabled.

VZ-5362: Fix scraping of POKO metrics when istio-injection is not enabled

---

application-operator/controllers/wlsworkload/weblogic_logging.go
application-operator/controllers/wlsworkload/weblogicworkload_controller.go
application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go

This PR addresses the bug where Verrazzano always sets the WebLogic domain `logHome` field. If the user has already set a `logHome`, Verrazzano overwrites it. With these changes, if `logHome` is already set, Verrazzano will honor it.
I manually tested this on an OKE cluster with a `logHome` set to use a persistent volume. I verified that logs show up correctly in OpenSearch. I will create an end-to-end test for this in a follow-on PR.
Fixes VZ-5278

VZ-5278: Bug fix - Do not overwrite WebLogic domain logHome

---

application-operator/controllers/metricsbinding/metricsbinding_controller.go
application-operator/controllers/metricsbinding/metricsbinding_controller_test.go
platform-operator/helm_config/charts/verrazzano-application-operator/templates/verrazzano-application-operator.yaml
tests/e2e/metricsbinding/helidon-deployment/helidon_deployment_test.go
tests/e2e/metricsbinding/helidon-pod-annotation-overrides/helidon_pod_annotation_overrides_test.go
tests/e2e/metricsbinding/helidon-pod/helidon_pod_test.go
tests/e2e/metricsbinding/helidon-replicaset/helidon_replicaset_test.go
tests/e2e/metricsbinding/helidon-statefulset/helidon_statefulset_test.go
tests/e2e/metricsbinding/metrics_binding_helper.go

Backport of commit 35a0ec3cef2b9f71efb34e42f3d4fe9bf9ec6307 to release-1.2

VZ-5362: backport POKO metrics not scraped when istio-injection was disabled to release-1.2

---

tests/e2e/logging/system/system_logging_test.go

This pull request removes the logging test for the verrazzano-namespace-local-path-storage index.

No Jira: remove logging test for the verrazzano-namespace-local-path-storage index
