ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease
- Add a new parameter and logic to exclude releases from automated upgrade tests. 
=> No Jira: Enable excluding releases from automated upgrade tests

platform-operator/verrazzano-bom.json
-  Backports the fix for Helidon dashboard to work correctly with multicluster 
Fixes VZ-5168
=> VZ-5168: Backport fix to 1.2 release for Helidon dashboard to work correctly with multicluster 

platform-operator/controllers/verrazzano/component/kiali/kiali.go, platform-operator/controllers/verrazzano/component/kiali/kiali_component.go
=> VZ-5830: Check if NGINX is enabled before building DNS suffix for Kiali

pkg/security/password/password.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/kiali/kiali.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-ingress.yaml
Reverts verrazzano/verrazzano#3081
=> Revert "VZ-4588: partial backport from master to release-1.2"

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, ci/dynamic-updates/Jenkinsfile, pkg/constants/constants.go, platform-operator/controllers/clusters/sync_registration_secret.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go, tests/e2e/update/fluentd/fluentd_update_suite_test.go, tests/e2e/update/fluentd/fluentd_update_test.go, tests/e2e/update/updater.go
* add validation for OCI logging and external Opensearch
* updater may return error for testing validation
* add fluentd update to dynamic-config-tests
Fixes VZ-5464
=> VZ-5464 fluentd update tests

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-authproxy-configmap.yaml
Backporting https://github.com/verrazzano/verrazzano/pull/3107
- VZ-5076 Cleanup errors in AuthProxy log during install
=> VZ-5076 Cleanup errors in AuthProxy log during install

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.2.2 to 1.2.3
=> Updating development version from 1.2.2 to 1.2.3

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go
Backporting "Problems using OCI public DNS zone and lets encrypt with instance principals"
VZ-5553
=> VZ-5844: Backport OCI dns instance principal fixes to release-1.2

platform-operator/verrazzano-bom.json
Updates VMO image from https://github.com/verrazzano/verrazzano-monitoring-operator/pull/196
=> VMO Array bounds

platform-operator/verrazzano-bom.json
Refreshes keycloak and keycloak-oracle-theme image in Verrazzano.
=> VZ-5847: Refresh keycloak and keycloak-oracle-theme image

application-operator/controllers/ingresstrait/ingresstrait_controller.go
fix the comments/logs/variable names in IngressTrait finalizer 
=> fix the comments/logs/variable names in IngressTrait finalizer 

examples/sock-shop/spring/sock-shop-comp.yaml
Backports the change to update sock shop images for the Spring variant to release-1.2.
=> VZ-5853: Update sock shop images for the Spring variant in release-1.2

platform-operator/verrazzano-bom.json
Backports the change to update keycloak and keycloak-oracle-theme image to release-1.2.
=> VZ-5847: Refresh keycloak and keycloak-oracle-theme image in release-1.2

platform-operator/controllers/verrazzano/upgrade_test.go
Another batch of conversions from mock to fake
=> Convert so more mocks to fakes in the upgrade tests

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preupgrade.go
Back port Rancher upgrade fix to release-1.3 branch
=> VZ-5864 Back port Rancher upgrade fix to release-1.3 branch

ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
- Fixes stage names for minor release upgrade path. 
=> Fix stage names for minor release upgrade path

ci/multicluster/Jenkinsfile, tests/e2e/update/fluentd/fluentd_update.go, tests/e2e/update/fluentd/fluentd_update_test.go, tests/e2e/update/fluentdextes/fluentdextes_suite_test.go, tests/e2e/update/fluentdextes/fluentdextes_test.go
* refactor update/fluentd suite to be reusable
* add an Fluentd/OpenSearch update stage to Multicluster AT pipeline
* add extraVolumeMounts update test
Fixes VZ-5464
=> VZ-5464 add fluentd update to e2e AT

ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
- Fixes stage names for minor release upgrade path.
=> Fix stage names for minor release upgrade path (#3146)

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/controller_test.go, platform-operator/controllers/verrazzano/install.go, platform-operator/main.go
Reverts verrazzano/verrazzano#3145
=> Revert "VZ 5882: Fire watch using flag"

ci/upgrade-paths/Jenkinsfile, tests/e2e/pkg/bom.go, tests/e2e/registry/registry_suite_test.go, tests/e2e/registry/registry_test.go
Also modified registry test to read the registry details from BOM for
non-private registry configurations.
Fixes VZ-5819
=> VZ-5819 Execute registry test in the upgrade-paths pipeline

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/lre/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/test-examples/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease, ci/upgrade/Jenkinsfile
This isolates the runner and agent VM for release-1.3 moving forward
=> Tvlatas/lock tooling 1.3

tests/e2e/opensearch/topology/topology_test.go
=> Reduce topology test scope

platform-operator/verrazzano-bom.json
Downgrade version of Prometheus from 2.34.0 to 2.31.1.
=> NO JIRA: Downgrade Prometheus version

ci/upgrade-paths/Jenkinsfile
=> VZ-5926 Upgrade wait timeout increased in Jenkinsfile for upgrade-paths test

platform-operator/verrazzano-bom.json, tests/e2e/opensearch/topology/topology_test.go
=> Update VMO image (#3158)

examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/springboot-app/springboot-comp.yaml, tests/testdata/deploymetrics/deploymetrics-comp.yaml, tests/testdata/istio/authz/bar/springboot-backend.yaml, tests/testdata/istio/authz/bar/springboot-frontend.yaml, tests/testdata/istio/authz/foo/springboot-backend.yaml, tests/testdata/istio/authz/foo/springboot-frontend.yaml, tests/testdata/istio/authz/noistio/springboot-backend.yaml, tests/testdata/istio/authz/noistio/springboot-frontend.yaml, tests/testdata/loggingtrait/helidonworkload/helidon-logging-components.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-components.yaml, tests/testdata/multicluster/multicluster_component_placement_clusters_invalid.yaml, tests/testdata/multicluster/permissiontest1-oam-component.yaml, tests/testdata/security/network-policies/netpol-test.yaml
Updates SpringBoot image in various test files. As part of this change, I have also updated the image for the Helidon example.
Contributes to VZ-5838
=> VZ-5838: Update SpringBoot image in various test files

ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/examples/Jenkinsfile
backport promotion job retries to 1.3
=> backport promotion job retries to 1.3

ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger
backport promotion job retries to 1.2
=> Tvlatas/job retries 1.2

examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/springboot-app/springboot-comp.yaml, tests/testdata/deploymetrics/deploymetrics-comp.yaml, tests/testdata/istio/authz/bar/springboot-backend.yaml, tests/testdata/istio/authz/bar/springboot-frontend.yaml, tests/testdata/istio/authz/foo/springboot-backend.yaml, tests/testdata/istio/authz/foo/springboot-frontend.yaml, tests/testdata/istio/authz/noistio/springboot-backend.yaml, tests/testdata/istio/authz/noistio/springboot-frontend.yaml, tests/testdata/loggingtrait/helidonworkload/helidon-logging-components.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-components.yaml, tests/testdata/multicluster/multicluster_component_placement_clusters_invalid.yaml, tests/testdata/multicluster/permissiontest1-oam-component.yaml, tests/testdata/security/network-policies/netpol-test.yaml
Updates SpringBoot image in various test files. As part of this change, I have also updated the image for the Helidon example.
Contributes to VZ-5838
=> VZ-5838: Update SpringBoot image used by various test files in release 1.3

ci/dynamic-updates/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/scripts/save_console_test_artifacts.sh, ci/upgrade-paths/Jenkinsfile
=> Jenkinsfiles should save console test browser logs, in addition to screenshots

tests/e2e/config/scripts/terraform/cluster/provider.tf
=> Latest TF provider is broken don't use it

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/thirdparty/manifests/README.md, platform-operator/thirdparty/manifests/prometheus-operator/envoy_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/nginx_ingress_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/opensearch_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/pilot_monitor.yaml
Resubmitting this PR after having reverted due to test failures. Test failures do not appear to be related to these changes.
=> VZ-5899: Add SystemMonitors and PodMonitors for Verrazzano system components

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go
Updating image for Prometheus.
Fixes No JIRA
=> No JIRA Explicitly set the Prometheus image in Helm overrides

platform-operator/controllers/verrazzano/component/rancher/rancher.go
Back port fix to generalize check for failing to find any system charts
Fixes VZ-5864
=> VZ-5864: Back port fix for Rancher upgrade failure

Jenkinsfile, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/test-examples/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade/Jenkinsfile, tests/e2e/config/scripts/terraform/cluster/create-cluster.sh, tests/e2e/config/scripts/terraform/cluster/create-multi-cluster.sh
Reverts verrazzano/verrazzano#3168
We hit IP limits in PHX due to concentrating the OKE clusters (master runs), and a super low free count in PHX.
I requested a limit increase there, but that may take time, so reverting this
=> Revert "Tvlatas/agent oke region lock"

tests/e2e/config/scripts/terraform/cluster/create-multi-cluster.sh
Revert of the region locking resulted in a file that needed copyright bumped
=> copyright needed after revert

tools/bom-validator/bom-validator.go
=> Put additional-rancher back on bom-validator ignore list. This reverts commit 0b83e1a751d60348ad193e0592592d44d4560ea0.

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#3164
=> Revert "NO JIRA: Downgrade Prometheus version"

ci/upgrade-paths/Jenkinsfile
Added OpenSearch pre-upgrade and post-upgrade tests to upgrade-paths pipeline. Also, extracted some code into function s to fix "Method code too large!" issue
Fixes VZ-5920
=>  VZ-5920 Add OpenSearch upgrade tests to upgrade-paths pipeline

ci/upgrade-paths/Jenkinsfile
Parallelized few stages and functions to cut down on build time. This is first of the PRs. More PRs will follow-up later.
Fixes VZ-5848
=> VZ-5848: Parallelize steps and stages in the upgrade paths jenkinsfile to cut down on build time

examples/springboot-app/springboot-comp.yaml, tests/testdata/deploymetrics/deploymetrics-comp.yaml, tests/testdata/istio/authz/bar/springboot-backend.yaml, tests/testdata/istio/authz/bar/springboot-frontend.yaml, tests/testdata/istio/authz/foo/springboot-backend.yaml, tests/testdata/istio/authz/foo/springboot-frontend.yaml, tests/testdata/istio/authz/noistio/springboot-backend.yaml, tests/testdata/istio/authz/noistio/springboot-frontend.yaml
Updates SpringBoot image in various test files. As part of this change, I have also updated the image for the Helidon example.
Contributes to VZ-5838
=> VZ-5838: Update SpringBoot image used by various test files in release 1.2

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/multicluster_helper.go, tests/e2e/update/fluentd/fluentd_update.go, tests/e2e/update/fluentdextes/fluentdextes_test.go, tests/e2e/update/updater.go
- add test to verify Opensearch's ca-bundle is synced to managed cluster
- improve updater util to support multicluster and allow update during update
Fixes VZ-5919
=> multicluster fluentd update test

platform-operator/controllers/verrazzano/component/rancher/rancher.go
Skip deleted pods for Rancher upgrade work around. Also, log full text of line that matches which system chart is not found.
Fixes VZ-9999
=> VZ-5864: skip deleted pods for Rancher upgrade work around

platform-operator/controllers/verrazzano/component/rancher/rancher.go
Reverts verrazzano/verrazzano#3228
=> Revert "VZ-5864: skip deleted pods for Rancher upgrade work around"

tools/bom-validator/bom-validator.go
Backports known-issues support in bom-validator to release-1.1.
Relates to VZ-5937.
=> Backport BOM validator updates to release-1.1

ci/examples/Jenkinsfile
Renames the repository for Bob's Books order-manager image.
=> Rename the repo for Bob's Books order-manager

platform-operator/controllers/verrazzano/component/rancher/rancher.go
Reverts verrazzano/verrazzano#3236
=> Revert "Revert "VZ-5864: skip deleted pods for Rancher upgrade work around""

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.0 to 1.3.1
=> Updating development version from 1.3.0 to 1.3.1

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.0 to 1.4.0
=> Updating development version from 1.3.0 to 1.4.0

platform-operator/constants/constants.go, platform-operator/controllers/configmaps/configmaps_controller.go, platform-operator/controllers/configmaps/configmaps_controller_test.go, platform-operator/controllers/configmaps/configmaps_utils_test.go, platform-operator/controllers/controller_utils.go, platform-operator/controllers/controller_utils_test.go, platform-operator/controllers/secrets/helm_override_secret.go, platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/secrets_utils_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/install.go, platform-operator/main.go, platform-operator/mocks/component_mock.go
PR to backport VZ-5733 Helm values monitoring of overrides resources to 1.3 line.
VZ-5733
=> VZ-5733 Backport-1.3

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/multicluster_helper.go, tests/e2e/update/certmc/certmc_suite_test.go, tests/e2e/update/certmc/certmc_test.go
- test update cert-manager config of managed-cluster 
- assert ca secret sync, prometheuse scrapper
Fixes VZ-5919
=> VZ-5919 test cert-manager managed-cluster update

ci/chaos/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/upgrade/Jenkinsfile
…he upgrade-paths test
Fixes VZ-9999
=> Increase upgrade timeouts everywhere that upgrade is done

tests/e2e/update/nginxistio/nginxistio_test.go
add ingress service annotations update in verrazzano-dynamic-config-tests
Fixes VZ-6013
=> VZ-6013 add ingress service annotations update

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/thirdparty/manifests/README.md, platform-operator/thirdparty/manifests/prometheus-operator/envoy_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/nginx_ingress_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/opensearch_monitor.yaml, platform-operator/thirdparty/manifests/prometheus-operator/pilot_monitor.yaml
Resubmitting this PR now that the Istio sidecar bug appears to be fixed. This code has already been reviewed, merged, and reverted.
Implements VZ-5899
=> VZ-5899: Add monitors for Verrazzano system components

tools/bom-validator/bom-validator.go
we rectified the following issues with the bom validation process.
1.  Now cluster images / tags will be matched to vz bom, earlier it was in reverse order.
2. Added feature of allowed or whitelisted namespaces list
3. Cleaned up code redundancies
4. Simplified code of many unnecessary nested loops
5. Improvised data structures, replaced static ds to dynamic  
Fixes [VZ-5962](https://jira.oraclecorp.com/jira/browse/VZ-5962)
=> VZ-5962 Generalisation of BOM Validation Process

platform-operator/verrazzano-bom.json
uptake new OAM image which turns off development logging.
=> VZ 6061: OAM log level

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml
Adds TCP liveness probe in case nginx server is stopped or unresponsive.
=> VZ 6058: AuthProxy liveness probe

tests/e2e/metrics/deploymetrics/deploymetrics_test.go
Fixed test failures in upgrade pipeline caused due to PR #3201 
As part of VZ-5910, the format of the job name in prometheus scrape config was modified. Due to this the tests were failing in the pre-upgrade scenario, when the job name had old format but the tests were attesting for the new format.
Fixes VZ-5744, VZ-5910
=> Fix for deploymetrics test failures in upgrade scenario

tools/vz/cmd/install/install.go, tools/vz/cmd/root/root.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go, tools/vz/pkg/constants/constants.go
=> VZ-5893 Doc review of vz command line help

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go
=> Add cert-manager as an install dependency for Prometheus Operator

pkg/semver/semver_test.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/fake_component_test.go, platform-operator/controllers/verrazzano/install.go, platform-operator/controllers/verrazzano/install_test.go, tests/e2e/update/overrides/overrides_test.go
Reverts verrazzano/verrazzano#3300
=> Revert "VZ-6006 monitorChanges skips all component updates"

tools/vz/cmd/helpers/command.go, tools/vz/cmd/helpers/log_format.go, tools/vz/cmd/install/install.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/pkg/helpers/vzhelper.go
add support for log-format json to vz cli.
Fixes VZ-6070
=> VZ-6070 add support for log-format json to vz cli

pkg/constants/constants.go, pkg/scrapeconfigutils/edit_scrapeconfig.go, pkg/scrapeconfigutils/edit_scrapeconfig_test.go, pkg/scrapeconfigutils/testdata/scrapejobs.yaml, platform-operator/constants/constants.go, platform-operator/controllers/clusters/sync_prometheus.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go
=> VZ-6049 - Refactor scrape config editing into a separate package so that it can be shared

tools/vz/cmd/helpers/cmd_context.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/pkg/helpers/vzhelper.go, tools/vz/pkg/helpers/vzhelper_test.go, tools/vz/test/helpers/fake_cmd_context.go
This pull request adds unit tests for the vz CLI install command.
=> VZ-5950:  Add unit tests for vz install

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/multicluster_helper.go, tests/e2e/pkg/dns.go, tests/e2e/pkg/metrics.go, tests/e2e/update/dnsac/dnsac_suite_test.go, tests/e2e/update/dnsac/dnsac_test.go, tests/e2e/update/dnsmc/dnsmc_suite_test.go, tests/e2e/update/dnsmc/dnsmc_test.go
Multicluster DNS update tests
- test admin-cluster dns update, assert managed Fluentd OpenSearch url
- test managed-cluster dns update, assert admin Prometheus scrapeTargests
Fixes VZ-6056
=> VZ-6056 multicluster dns update tests

platform-operator/controllers/verrazzano/component/authproxy/authproxy_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go, tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/resources.go, tests/e2e/update/authproxy/authproxy_update_test.go, tests/e2e/update/nginxistio/nginxistio_suite_test.go, tests/e2e/update/nginxistio/nginxistio_test.go, tests/testdata/external-lb/application-external-lb-cm.yaml, tests/testdata/external-lb/application-external-lb-svc.yaml, tests/testdata/external-lb/application-external-lb.yaml, tests/testdata/external-lb/system-external-lb-cm.yaml, tests/testdata/external-lb/system-external-lb-svc.yaml, tests/testdata/external-lb/system-external-lb.yaml
=> backport VZ-5843, VZ-6012, VZ-6013

platform-operator/verrazzano-bom.json
=> VZ 5985: Prometheus v2.34.0-1 (backport 1.3)

platform-operator/verrazzano-bom.json
=> VZ 5985: Prometheus v2.34.0-1

tools/vz/cmd/helpers/cmd_context.go, tools/vz/cmd/helpers/command.go, tools/vz/cmd/install/install.go, tools/vz/pkg/github/github.com.go, tools/vz/pkg/helpers/vzhelper.go, tools/vz/pkg/helpers/vzhelper_test.go, tools/vz/test/helpers/fake_cmd_context.go
Add support for the operator-file option, which will be used internally for test pipelines
Fixes VZ-6074
=> VZ-6074 Add support for operator-file option

platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
Back port fix to resolve uninstall issue of a namespace not owned by Verrazzano being deleted.
Fixes VZ-6099
=> VZ-6099 Back port to 1.3 branch fix to resolve uninstall issue of a namespace not owned by Verrazzano

platform-operator/verrazzano-bom.json
=> VZ-5775: Update Keycloak image in 1.2

platform-operator/verrazzano-bom.json
=> VZ-5775: Update Keycloak image

platform-operator/verrazzano-bom.json
=> VZ-5775: Update Keycloak image in 1.3

ci/JenkinsfilePeriodicTests
Backports the change to conditionally execute the periodics IFF the latest stable commit != last clean periodics commit
Fixes VZ-6067.
=> VZ-6067.  Backport to release-1.3

ci/JenkinsfilePeriodicTests
Backports the change to conditionally execute the periodics IFF the latest stable commit != last clean periodics commit
Fixes VZ-6067.
=> VZ-6067.  Backport to release-1.1

ci/JenkinsfilePeriodicTests
Backports the change to conditionally execute the periodics IFF the latest stable commit != last clean periodics commit
Fixes VZ-6067.
=> VZ-6067.  Backport to release-1.2

application-operator/controllers/ingresstrait/ingresstrait_controller.go, application-operator/controllers/ingresstrait/ingresstrait_controller_test.go, ci/kind/Jenkinsfile, tests/e2e/jwt/helidon-svc/helidon_example_suite_test.go, tests/e2e/jwt/helidon-svc/helidon_example_test.go, tests/testdata/jwt/helidon-svc/hello-helidon-svc-app.yaml, tests/testdata/jwt/helidon-svc/hello-helidon-svc-comps.yaml
- Modified ingress controller to support native core v1 resources as components
- Added unit test
- Added end to end test
- Integrated end to end test into KIND tests, executed with JWT enabled parameter (currently periodic tests only)
Fixes VZ-6084
=> JIRA: VZ-6084 Support service components with traits  - Backport to release 1.3

ci/chaos/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, ci/upgrade/Jenkinsfile, tools/vz/cmd/helpers/cmd_context.go
Change the common script for install Verrazzano on Kind to use the "vz install" command
Fixes VZ-6163
=> VZ-6163 Use vz install in the common test setup script for Kind cluster

tools/vz/cmd/helpers/cmd_context.go
Remove timeout that was causing intermittent failures in test pipelines.
=> Remove timeout from http context (for the cli)

ci/JenkinsfilePeriodicTests
Update display name in periodics for up-to-date or dry-run scenarios. 
Fixes VZ-6067.
=> VZ-6067.  Indicate up-to-date or dry-run in build display name

tools/vz/cmd/helpers/cmd_context.go
Remove timeout from HTTP request that is causing intermittent failure in E2E tests.
=> remove timeout from http context for vz command

release/builds/JenkinsfilePostPRT
Reverts verrazzano/verrazzano#3405
=> Revert "Tvlatas/save scan info"

ci/multicluster/Jenkinsfile, tests/e2e/multicluster/verify-install/defaultresource_test.go, tests/e2e/multicluster/verify-rancher/rancher_suite_test.go, tests/e2e/multicluster/verify-rancher/rancher_test.go
Added a test to detect when a large number of "bad handshake" error messages (> 20) are logged by Rancher on the admin cluster.
Fixes VZ-4509
=> JIRA: VZ-4509 add "bad socket" detecting acceptance test to MC pipeline

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml
=> Make default secret optional to allow managed cluster installs to complete when secret is not available

ci/chaos/Jenkinsfile, ci/upgrade/Jenkinsfile
Use vz CLI in upgrade pipeline to uninstall Verrazzano
Fixes VZ-6196
=> VZ-6196: use vz uninstall in upgrade pipeline

ci/chaos/Jenkinsfile
Use vz uninstall on the chaos pipeline
=> VZ-6196: Add vz uninstall to the chaos pipeline

release/builds/JenkinsfilePostPRT
Backport saving malware scan info into object storage in stage 2 release job to 1.3
=> backport saving scan info to 1.3

release/builds/JenkinsfilePostPRT
Backport saving malware scan info into object storage in stage 2 release job to 1.2
=> backport saving scan info to 1.2

release/builds/JenkinsfilePostPRT
Backport saving malware scan info into object storage in stage 2 release job to 1.1
=> backport saving scan info to 1.1

Jenkinsfile
=> Always build the CLI now

platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/controller_test.go, platform-operator/controllers/verrazzano/fake_component_test.go, platform-operator/controllers/verrazzano/uninstall.go, platform-operator/controllers/verrazzano/uninstall_component.go, platform-operator/controllers/verrazzano/uninstall_test.go, platform-operator/mocks/component_mock.go
Check if uninstall is supported in the uninstallComponent loop.  This was causing upgrade tests to fail when component level uninstall is a noop.
=> VZ-6222 check if uninstall supported

ci/upgrade-paths/Jenkinsfile
- Fix to download the right platform operator yaml
- Refactored the env variables to avoid confusion and added comments. 
Fixes VZ-6290
=> VZ-6290: Fix upgrade path manual testing

platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/uninstall.go, platform-operator/scripts/uninstall/uninstall-steps/0-uninstall-applications.sh
Implement Rancher delete local cluster in go component code and remove it from uninstall script.
=> VZ-6248 rancher

platform-operator/controllers/verrazzano/component/velero/velero_operator_component.go
The comments referred to a different component. This PR will address that
=> NO JIRA: Update comments in component code

tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/uninstall/uninstall_test.go
This pull request updates uninstall CLI messages to be consistent with install/upgrade
=> NO JIRA: Make uninstall messages in CLI consistent with install/upgrade

ci/multicluster/Jenkinsfile
Use vz upgrade and vz uninstall in the multi-cluster pipeline
=> VZ-6196 Use vz to upgrade and uninstall in the multi-cluster pipeline

ci/multicluster/Jenkinsfile
Reverts verrazzano/verrazzano#3468
=> Revert "VZ-6196 Use vz to upgrade and uninstall in the multi-cluster pipeline"

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
Incorporated the minor review comment raised as part of PR https://github.com/verrazzano/verrazzano/pull/3480
=> VZ-6112 Fix the comment to remove Elastic storage reference

pkg/k8s/webhook/webhook.go, pkg/k8s/webhook/webhook_test.go, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
Uninstall Coherence using go components.
=> VZ-6235 uninstall coherence

platform-operator/controllers/verrazzano/component/vmo/vmo_component.go, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
This pull request contains the changes needed to have VMO uninstall done from Go code instead of scripts.
=> VZ-6241: Move VMO uninstall out of scripts

application-operator/controllers/metricstrait/metricstrait_controller.go
handle error when removing metrics trait finalizers.
=> VZ 5363: Handle error for metrics trait

platform-operator/controllers/verrazzano/component/common/vmi.go, platform-operator/controllers/verrazzano/component/common/vmi_test.go, platform-operator/controllers/verrazzano/component/grafana/dashboard.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go
Enable component-level uninstall for Grafana in the VPO.
=> VZ-6239.  Component level uninstall for Grafana

THIRD_PARTY_LICENSES.txt, go.mod, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go
We do not need the kyaml dependency directly.
=> NO JIRA: Remove kyaml

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go
=> Make Prometheus Operator webhook error message clearer

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/uninstall_component.go
=> Improve uninstall logging

ci/upgrade-paths/Jenkinsfile
coherence app failure fix due to env variable renamed
=> VZ-5814 coherence param renaming fix

platform-operator/controllers/verrazzano/component/fluentd/override.go, platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/templates/service.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/templates/servicemonitor.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/values.yaml
Enables prometheus metrics to be scraped from Fluentd.
=> VZ 6023: Fluentd prometheus metrics

platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicManagedClusterMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devKeycloakInstallArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/managedClusterEnableAllOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESStorageArgsMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, platform-operator/helm_config/charts/verrazzano-console/templates/console-deployment.yaml, platform-operator/helm_config/charts/verrazzano-console/values.yaml, platform-operator/manifests/profiles/base.yaml, platform-operator/manifests/profiles/prod.yaml, tests/e2e/verify-install/verrazzano/verrazzano_test.go
=> VZ 6273: Console HA

platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicManagedClusterMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devKeycloakInstallArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/managedClusterEnableAllOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESStorageArgsMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, platform-operator/helm_config/charts/verrazzano-console/templates/console-deployment.yaml, platform-operator/helm_config/charts/verrazzano-console/values.yaml, platform-operator/manifests/profiles/base.yaml, platform-operator/manifests/profiles/prod.yaml, tests/e2e/verify-install/verrazzano/verrazzano_test.go
Reverts verrazzano/verrazzano#3525
=> Revert "VZ 6273: Console HA"

tests/e2e/verify-install/bom-validator/bom_validator_suite_test.go, tests/e2e/verify-install/bom-validator/bom_validator_test.go
added ginkgo test for BOM validations that will run post vz installations verifications.
=> VZ-5679 Ginkgo Test for Bom Validations Under Verify Install   

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/upgrade_component.go
Reverts verrazzano/verrazzano#3531
=> Revert "VZ-6353: Update condition timestamp and add upgrade conditions"

platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/nginx/nginx_test.go, platform-operator/internal/vzconfig/ingress.go
Verrazzano install must set condition InstallComplete only when the component is really ready
=> VZ-6195 Verrazzano InstallComplete Status Fix 

platform-operator/controllers/verrazzano/component/nginx/nginx_test.go
added test case to verify nginx not ready if it does not have valid compartment ip regardless of having valid deployment replicas
=> VZ-6195 added new nginx test case

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/upgrade_component.go, platform-operator/controllers/verrazzano/upgrade_test.go
Re-merge of https://github.com/verrazzano/verrazzano/pull/3531
=> VZ-6353 update condition timestamp re-merge

pkg/k8s/resource/resource.go, platform-operator/controllers/verrazzano/component/velero/velero_operator_component.go, platform-operator/controllers/verrazzano/component/velero/velero_operator_component_test.go, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
This pull request moves the uninstall of Velero from the install scripts to Go code.
=> VZ-6327: Move Velero uninstall to Go code

platform-operator/controllers/verrazzano/component/nginx/nginx_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx_component_test.go, platform-operator/scripts/uninstall/uninstall-steps/2-uninstall-system-components.sh
This pull request moves the nginx uninstall to Go code
=> VZ-6320: Move nginx uninstall from scripts to Go code

platform-operator/controllers/verrazzano/component/kiali/kiali_component.go, platform-operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
This pull request moves the Kiali uninstall out of scripts and into Go code
=> VZ-6417: Move Kiali component uninstall to Go code

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall_test.go
This will sharpen the removal of the local namespace for Rancher.
=> VZ-6321 Update local namespace regex search

platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESStorageArgsMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, platform-operator/controllers/verrazzano/transform/merge.go, platform-operator/manifests/profiles/prod.yaml
Copy component overrides when merging profiles into the actual CR.
=> VZ 6413: merge profile overrides

platform-operator/verrazzano-bom.json
Updated rancher and rancher-agent with updated git version.
Fixes VZ-4508
=> VZ-4508: Managed cluster cattle-cluster-agent log has git errors

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/uninstall.go
This reverts commit 83a9ed9290c7b8b8479d79ced59dfce945ecf24b.
=> Revert "VZ-6325.  Fix ns deletion wait handling and logging (#3583)"

platform-operator/thirdparty/charts/rancher/Chart.yaml, platform-operator/thirdparty/charts/rancher/README.md, platform-operator/thirdparty/charts/rancher/scripts/post-delete-hook.sh, platform-operator/thirdparty/charts/rancher/templates/deployment.yaml, platform-operator/thirdparty/charts/rancher/templates/post-delete-hook-job.yaml, platform-operator/thirdparty/charts/rancher/templates/secret.yaml, platform-operator/thirdparty/charts/rancher/tests/deployment_test.yaml, platform-operator/thirdparty/charts/rancher/tests/pvc_test.yaml, platform-operator/verrazzano-bom.json
This PR includes the BOM update to reference the Rancher 2.6.5 images and updates to the Rancher helm chart for 2.6.5.
=> VZ-6389: Uptake Rancher 2.6.5

tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go
Add example and unit test for passing a comma separated list to -f option
=> Add example and unit test for passing a comma separated list to -f option

platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
Updates version and appVersion in Chart.yaml of monitoring operator for release-1.3.2
=> Update version and appVersion in Chart.yaml of monitoring operator

tests/e2e/verify-infra/restapi/rancher_url_test.go
Run test to validate oci and oke driver state in Rancher only for VZ >= 1.4
=> VZ-5012: run rancher oci/oke driver test only for 1.4

tools/vz/cmd/bugreport/bugreport.go
This change updates the help for bug-report command. 
Contributes to VZ-6337
=> VZ-6337: Update the help for bug-report command

tools/vz/cmd/helpers/vpo.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/uninstall/uninstall_test.go
Reverts verrazzano/verrazzano#3601
=> Revert "VZ-6444: uninstall CLI must stream uninstall job log for pre v1.4.0"

pkg/istio/istioctl.go
Squelch harmless Istio error during install and leave reporting of errors to the caller
- Make `runIstioctl` commmand/error logging tunable using internal flag to prevent displaying verify-install command
=> VZ-6441. Squelch harmless Istio error during install

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall_test.go
The namespace search for Rancher has been improved
=> VZ-6321 Rancher deletion search improvements

ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scripts/install_verrazzano.sh, ci/uninstall/Jenkinsfile, ci/upgrade/Jenkinsfile, platform-operator/controllers/verrazzano/uninstall.go
Remove Jenkinsfile hooks to grab install/uninstall job logs.
=> VZ-6418. Remove Jenkinsfile references to install/uninstall jobs

examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, tests/testdata/test-applications/coherence/hello-coherence/hello-coherence-comp.yaml
VZ-6478 - Socks Shop Helidon 1.2.0 release update
=> Update to version 1.2.0 of Helidon Sockshop example

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall_test.go, platform-operator/controllers/verrazzano/controller_test.go, platform-operator/controllers/verrazzano/uninstall.go
This is a reattempt to merge the Rancher deletion updates I made yesterday. None of the functionality has changed, but a unit test has been updated.
=> VZ-6321 Reintegrate Rancher deletion updates

Jenkinsfile
CLI build, image build, compliance checks, unit tests are combined into a parallel stage. This took 6m30s on my branch. Typically the combined sequential run for these is at least 15 minutes.
=> NO JIRA: Parallel Build on main Jenkins file

examples/sock-shop/micronaut/sock-shop-comp.yaml
VZ-6482 - Socks Shop Micronaut 1.2.1 release update
=> Update to version 1.2.1 of Micronaut Sockshop Example

platform-operator/thirdparty/charts/rancher/Chart.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#3641
=> Revert "NO JIRA: Uptake Rancher 2.6.6"

platform-operator/controllers/verrazzano/component/common/rancher.go
An intermittent issue was see with OLCNE installs while activating OCI/OKE drivers which was enabled in https://github.com/verrazzano/verrazzano/pull/3543. The error was
```Failed activating OKE Driver: failed activating rancher oke driver, url ```
in VPO logs and in rancher logs, following error was there
```
2022/07/19 15:04:10 [ERROR] Unknown error: Operation cannot be fulfilled on kontainerdrivers.management.cattle.io "oraclecontainerengine": the object has been modified; please apply your changes to the latest version and try again
```
Since the error is intermittent, this PR changes the rest api client to `retryablehttp` client so that any >=500 code responses can be retried.
=> VZ-6487: Enable retries for invoking rest apis in rancher on install/upgrade

platform-operator/verrazzano-bom.json
Update the grafana image to 7.5.15
=> VZ-6394 update grafana image

ci/ha/JenkinsfileRollingUpgrade, tests/e2e/ha/common.go, tests/e2e/ha/rollingupdate/rolling_update_test.go, tests/e2e/ha/scheduling/scheduling_test.go
Test test simulates a rolling update on a Kind cluster by manipulating scheduling roles.
=> VZ 6436: Jenkins pipeline for Rolling Update HA Test

examples/sock-shop/spring/sock-shop-comp.yaml
VZ-6481 - Socks Shop Spring 1.2 release update
=> Update to version 1.2.0 of Spring Sockshop Example

platform-operator/verrazzano-bom.json
=> VZ-6316: flip fluentd-kubernetes-daemonset image

ci/JenkinsfilePeriodicTests
backport periodic alerting VZ-6081 to 1.3
=> backport periodic alerting VZ-6081 to 1.3

ci/JenkinsfilePeriodicTests
backport periodic alerting VZ-6081 to 1.1
=> backport periodic alerting VZ-6081 to 1.1

ci/JenkinsfilePeriodicTests
backport periodic alerting VZ-6081 to 1.2
=> backport periodic alerting VZ-6081 to 1.2

platform-operator/verrazzano-bom.json
This PR will uptake latest console image.
=> VZ-5817: Fix Console test issue with multiple app deployment of same name

Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh
Reverts verrazzano/verrazzano#3650
=> Revert "VZ 6512: Save CLI to Object Storage"

platform-operator/verrazzano-bom.json
=> VZ-6394 update mysql image

platform-operator/verrazzano-bom.json
Uptake the latest OpenSearch Dashboards image.
=> VZ-6339: Uptake latest build of OS Dashboards image

platform-operator/verrazzano-bom.json
Update external-dns image to the latest build
=> VZ-6394 update external-dns image

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml, platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml, tests/e2e/logging/system/system_logging_test.go
Backport to 1.3: Enable access logs for Authproxy
Fixes VZ-5339
=> VZ-5339: Enable access logs for Authproxy (#3534)

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.2 to 1.3.3
=> Updating development version from 1.3.2 to 1.3.3

platform-operator/Dockerfile, platform-operator/verrazzano-bom.json, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
This pull request uptakes Istio 1.13.5.
=> VZ-6385: VZ-6378: uptake Istio 1.13.5

platform-operator/verrazzano-bom.json
Backport of the cert-manager image update
=> VZ-6428 update cert manager image

platform-operator/Dockerfile, platform-operator/verrazzano-bom.json, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
=> VZ-6385: VZ-6378: uptake Istio 1.13.5 (#3672)

platform-operator/verrazzano-bom.json
This pull request updates the images oam-kubernetes-runtime, configmap-reload, and keycloak-oracle-theme.
=> VZ-6539: VZ-6540: Update images in bom

platform-operator/verrazzano-bom.json
Cherry-pick : update Grafana image to 7.5.15
=> VZ-6549 update Grafana image to 7.5.15 

platform-operator/verrazzano-bom.json
Backport MySQL and extern-dns new images in another repository, list those.
=> VZ-6549 backport MySQL and extern-dns new images

ci/uninstall/JenkinsfileUninstallSuite, ci/uninstall/JenkinsfileUninstallTest
- Add support for managed-cluster loop tests
- tweak the stage naming and dump directory naming
=> VZ-6552.  Uninstall resiliency pipeline updates

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go
Enable Jaeger ingress and URL to be created when using external
OpenSearch for the Jaeger instance configured in the VZ CR.
Also, skip Jaeger ingress and certs creation when Jaeger instance is
disabled in the VZ CR.
=> VZ-6318 Default Jaeger instance support for external OpenSearch

platform-operator/verrazzano-bom.json
This PR fixes the console test failure issues for the following scenarios.
When more than one app is deployed with the same app name
When apps have a different name but the namespace is same.
=> VZ-6519: Update console image to backport a fix for console test issue

platform-operator/helm_config/charts/verrazzano/templates/networkpolicy.yaml, platform-operator/internal/k8s/netpolicy/netpolicy.go, tests/e2e/metrics/syscomponents/metrics_test.go
- End to End Tests for VPO Metrics
-  Changes to Network Policy Configuration for VPO 
Checklist
=> VZ-6432 Add e2e tests for VPO

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#3710
=> Revert "VZ-5822 Use the latest VMO version"

platform-operator/helm_config/charts/verrazzano-monitoring-operator/templates/networkpolicy.yaml, platform-operator/verrazzano-bom.json, tests/e2e/metrics/syscomponents/metrics_test.go
Reverts verrazzano/verrazzano#3706
=> Revert "VZ-5822 Use Latest VMO and add VMO metrics e2e tests"

platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Updates the Coherence Operator to 3.2.6
=> VZ-6587: Update Coherence Operator to 3.2.6

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.3 to 1.3.4
=> Updating development version from 1.3.3 to 1.3.4

platform-operator/verrazzano-bom.json
Update BOM with v1.3.4 Console and VMO images
=> Update BOM with 1.3.4 images

release/scripts/scan_release_binaries.sh
Extracts release bundle to directory and scans the extracted directory (v/s scanning the release bundle)
=> VZ-6514: Scan release bundle from extracted directory

platform-operator/verrazzano-bom.json
=> VZ-6582 VZ-6584 uptake newer rancher images

platform-operator/verrazzano-bom.json
This PR fixes the console test failure issues for the following scenarios.
When more than one app is deployed with the same app name
When apps have a different name but the namespace is same.
=> VZ-6519: Update release-1.2 console image

platform-operator/main.go
Backport logging of Verrazzano version in the VPO log file to release 1.3
=> NO JIRA: Log Verrazzano version in VPO log file (#3743)

release/scripts/create_github_release.sh
add prefix v to tag and draft release name
=> VZ-4366 add prefix v to tag and draft release name

release/scripts/create_github_release.sh
add prefix v to tag and draft release name
=> VZ-4366 prefix v to tag and draft release name

ci/multicluster/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, pkg/test/mockmatchers/matchers.go, platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/controllers/clusters/rancher.go, platform-operator/controllers/clusters/sync_manifest_secret.go, platform-operator/controllers/clusters/vmc_controller.go, platform-operator/controllers/clusters/vmc_controller_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/kubernetes.go
=> Add VMC status condition for managed CA retrieved from Rancher, add cluster id to Rancher registration status of VMC

platform-operator/verrazzano-bom.json
This PR fixes the console test failure issues for the following scenarios.
When more than one app is deployed with the same app name
When apps have a different name but the namespace is same.
=> VZ-6519: Update release-1.1 console image with console fix

platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/mysql/mysql_test.go
Added code and test code to handle the upgrade of a cluster with ephemeral storage specified for MySQL
Testing is still in progress....
=> JIRA: VZ-6263 Handle MySQL ephemeral storage during upgrade

platform-operator/verrazzano-bom.json
Dependency updates for Rancher image used in Release 1.3 line.
=> VZ-6676 VZ-6677 Dependency updates for Rancher

tests/e2e/update/authproxy/authproxy_update_test.go, tests/e2e/update/env-dns-cm/env_dns_cert_update_test.go, tests/e2e/update/fluentd/fluentd_update.go, tests/e2e/update/updater.go
Fixes issue where test may fail due to resource conflict when updating the Verrazzano CR.
=> VZ 6615: Retry updating the CR

ci/multicluster/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, tests/e2e/multicluster/verify-register/verify_register_test.go
=> VZ-6448 fix Jenkins setting of env var ADMIN_VZ_VERSION_AT_REGISTRATION for verify_register test

examples/ha/README.md
Add a readme to the examples/ha directory.
=> VZ-6425: Add a readme to examples/ha

tests/e2e/pkg/keycloak.go, tests/e2e/verify-install/jaeger-operator/jaeger_operator_test.go
=> Fix WhenJaegerOperatorEnabledIt function in Jaeger operator e2e test

platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/controllers/verrazzano/component/mysql/mysql_test.go, platform-operator/scripts/hooks/mysql-hook.sh, platform-operator/thirdparty/charts/mysql/templates/configurationFiles-configmap.yaml, platform-operator/thirdparty/charts/mysql/templates/primary/statefulset.yaml, platform-operator/thirdparty/charts/mysql/values.yaml
Re-introduce backup hook configuration after it was removed as a result of mysql HA implementation
=> VZ-6685 mysql backup fix

platform-operator/verrazzano-bom.json
Pick up new VMO image that has updated affinity rules for OpenSearch components.
=> VZ-6699: Pick up new VMO tag

examples/README.md, examples/ha/README.md
Additional doc updates to for the HA example
=> VZ-6425: Additional updates to HA example

tests/e2e/update/authproxy/authproxy_update_test.go, tests/e2e/update/env-dns-cm/env_dns_cert_update_test.go, tests/e2e/update/fluentd/fluentd_update.go, tests/e2e/update/updater.go
Reverts verrazzano/verrazzano#3755
=> Revert "VZ 6615: Retry updating the CR"

platform-operator/controllers/verrazzano/component/certmanager/certmanager_component.go
=> reduce a specific internal webhook error in Install log

platform-operator/verrazzano-bom.json
=> VZ-6721: Update rancher backup with new golang patched image

ci/backup/JenkinsfileAlllBackupOKETest
=> [NO-PR]: Update bucket name

ci/JenkinsfilePeriodicTests
**Description**
- Fixes: VZ-6675
- Added stage to trigger Jenkins pipeline to install Verrazzano on OLCNE periodically
=> VZ-6675: Trigger Jenkins pipeline to install Verrazzano on OLCNE periodically

ci/ha/JenkinsfileRollingUpgrade, ci/scripts/prepare_jenkins_at_environment.sh, tests/e2e/ha/nodes.go, tests/e2e/ha/pods.go
- Update the HA test pipeline to be based on a prod profile instead of dev
- Support longer install timeout (sometimes ha install takes longer than 30 minutes)
- Skip stages after a failure
=> VZ-6698 - update HA pipeline to use prod profile

platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
=> Update WebLogic Operator to 3.4.2 and Monitoring Exporter to 2.0.7

application-operator/controllers/metricstrait/metricstrait_controller.go, application-operator/controllers/metricstrait/metricstrait_utils.go, application-operator/controllers/metricstrait/metricstrait_utils_test.go, application-operator/controllers/metricstrait/monitor.go, application-operator/controllers/metricstrait/operator.go, ci/kind/Jenkinsfile, tests/e2e/examples/helidonmetrics/helidon_metrics_test.go, tests/e2e/metrics/deploymetrics/deploymetrics_test.go, tests/e2e/pkg/metrics.go
=> Delete ServiceMonitor when MetricsTrait is disabled, fix helidonmetrics test issues

platform-operator/verrazzano-bom.json
This pull request updates the release 1.3 Kiali image
=> VZ-6539: VZ-6540: update Kiali image (#3827)

Jenkinsfile
Add retry to the Kind AT job fired off from the main job (that sometimes fails intermittently and works on retry, so automating that to avoid noise and manual retry runs for that)
=> Add retry to kind AT stage

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/convert_from.go, platform-operator/apis/verrazzano/v1beta1/convert_from_istio.go, platform-operator/apis/verrazzano/v1beta1/convert_from_test.go, platform-operator/apis/verrazzano/v1beta1/testdata/fromallcomps/v1beta1.yaml, platform-operator/apis/verrazzano/v1beta1/testdata/fromopensearch/v1beta1.yaml, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/internal/k8s/certificate/certificate.go, platform-operator/main.go
Added patch strategy for nodes, so strategic merges do not replaces converted values.
=> VZ 6726: Enable Conversion Webhook

tools/vz/cmd/helpers/vpo.go
This pull request fixes the vz CLI upgrade command to not prematurely exit before upgrade has completed.  This would happen if an upgrade had previously been run.  This issue was discovered during the LRE auto upgrade.
=> VZ-6741: vz upgrade prematurely exiting before upgrade completes

application-operator/test/kind-config-ci.yaml, application-operator/test/kind-config.yaml, ci/scripts/create_kind_clusters.sh, platform-operator/test/kind-config-ci.yaml, platform-operator/test/kind-config.yaml, tests/e2e/config/scripts/create_kind_cluster.sh
Uptake images recommended by kind 0.14.0
Fixes VZ-6554.
=> VZ-6554: uptake images recommended by kind 0.14.0

Jenkinsfile, tools/vz/cmd/version/version.go, tools/vz/cmd/version/version_test.go, tools/vz/pkg/analysis/internal/util/report/action.go
This reverts commit 0ecb3d2bee9ea72ea6de5064f95b616498b60efc.
=> Revert "Versioning analysisadvice links (#3845)"

platform-operator/verrazzano-bom.json, tests/e2e/ha/nodes.go
Pick up VMO that reverts back to using zone affinity.
=> VZ-6699: Pick up new VMO that reverts back to using zone affinity

Jenkinsfile
=> backport kind at retry in main job to 1.3

Jenkinsfile
backport kind at retry in main job to 1.2
=> backport kind at retry in main job to 1.2

Jenkinsfile
backport kind at retry in main job to 1.1
=> backport kind at retry in main job to 1.1

ci/JenkinsfilePeriodicTests
=> backport periodic fix to 1.1

ci/JenkinsfilePeriodicTests
=> backport periodic fix to 1.2

ci/JenkinsfilePeriodicTests
=> backport periodic fix to 1.3

ci/multicluster/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile
Update OKE versions being tested, down to one now, the others are no longer supported
=> Tvlatas/update 1.1 oke versions

Jenkinsfile, tools/vz/Makefile, tools/vz/cmd/version/version.go, tools/vz/cmd/version/version_test.go, tools/vz/pkg/analysis/internal/util/report/action.go
=> Versioning analysis advice links

application-operator/main.go, application-operator/metricsexporter/metricsexporter_utils.go
=> Reduce the noisy logs in metrics exporter for application operator

platform-operator/verrazzano-bom.json
Update docker images with THIRD_PARTY _LICENSE text files
=> VZ-6748: Update velero and dependencies with new images

tools/scripts/vz-registry-image-helper.sh
Re-add the script code to create the tarball.
=> Fix tarball creation

application-operator/controllers/helidonworkload/helidonworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, examples/hello-helidon/hello-helidon-comp.yaml, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/pkg/kubernetes.go
Reverts verrazzano/verrazzano#3791
=> Revert "VZ-6360 Integration Test for Label Selectors into Hello Helidon Example App"

application-operator/controllers/helidonworkload/helidonworkload_controller.go, application-operator/controllers/helidonworkload/helidonworkload_controller_test.go, examples/hello-helidon/hello-helidon-comp.yaml, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/pkg/kubernetes.go
Now Supports Selector MatchLabels & MatchExpressions mechanism for Helidon Workload
=> VZ-6360 Added Selector MatchLabels & MatchExpressions mechanism for Helidon Workload

platform-operator/controllers/verrazzano/component/rancher/rancher.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
Fix typo for short form of GlobalRoleBinding
=> VZ-5010: gbr to grb (short for GlobalRoleBinding)

ci/ha/JenkinsfileRollingUpgrade, examples/hello-helidon/hello-helidon-app-scaler-trait.yaml, tests/e2e/examples/helidon/helidon_example_suite_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/jwt/helidon/helidon_example_test.go, tests/e2e/oci/logging/ocilogging_test.go, tests/e2e/pkg/hello_helidon.go, tests/e2e/security/netpol/network_policy_test.go
Deploy two replicas of the hello world app in the HA test pipeline, to be used for HA testing
=> VZ-6689 Deploy hello world app for HA testing

Jenkinsfile, ci/JenkinsfilePeriodicTests, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, ci/scripts/save_tooling.sh, ci/scripts/update_periodic_on_success.sh, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease, ci/upgrade/Jenkinsfile
Backport object storage separation work, this moves per-commit related object storage into a new bucket with short lived object retention policies.
=> Backport object storage separation to 1.3

ci/JenkinsfilePeriodicTests
=> backport kind at retry to 1.3

application-operator/controllers/metricstrait/metricstrait_controller_test.go, application-operator/controllers/metricstrait/metricstrait_utils.go, application-operator/controllers/metricstrait/metricstrait_utils_test.go, tests/e2e/istio/authz/authpolicy_test.go
=> Remove the use of ObjectMeta.ClusterName which is deprecated in K8S

platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
Add fluentd configuration for the new MySQLOperator component
=> VZ-6786: Add fluentd configuration for MySQLOperator

platform-operator/verrazzano-bom.json
Pick up new VMO with updated ready check for OS Dashboards
=> VZ-6757: Pick up new VMO with updated ready check for OS Dashboards

ci/olcne/Jenkinsfile
=> OCNE Jenkinsfile should install from specified branch and commit instead of tip of master

ci/JenkinsfilePeriodicTests, ci/scripts/generate_vz_distribution.sh
Creates text files containing the list of files part of the Verrazzano distributions and upload to object store. These files can be used to validate the contents of the the bundles.
=> VZ-6900: Create a text files containing the list of files part of the Verrazzano distributions

tests/e2e/uninstall/verifycrds/verify_crds_test.go
Fix verify crd test that started failing when the MySQL Operator was added.
=> VZ-6786 Fix verify crd test

pkg/capi/bootstrap_provider.go, tools/vz/cmd/cluster/cluster.go, tools/vz/cmd/cluster/cluster_delete.go, tools/vz/cmd/cluster/cluster_test.go
=> VZ-6650 CAPI delete function in VZ CLI

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
Configure Keycloak/Rancher sso only when both are enabled
=> VZ-5010: Configure Keycloak/Rancher sso only when both are enabled

ci/lre/Jenkinsfile, ci/scripts/update_lre_kubeconfig.sh
This pull request changes the dev LRE Jenkinsfile to use a bastion host instead of the rancher proxy which is not working with kubectl exec.
=> VZ-6909: Convert dev LREJenkinsfile  to use bastion

ci/JenkinsfilePeriodicTests, ci/scripts/generate_vz_distribution.sh
This change includes README.md in Verrazzano release distributions. As part of this change, the existing profiles directory is removed and will be added once the final set of profiles are available.
=> VZ-6902: Include README.md in Verrazzano release distributions

tests/e2e/grafana-db/grafana_test.go
=> NO-JIRA: Disable the failing grafana test for now

platform-operator/thirdparty/charts/rancher-backup-crd/Chart.yaml, platform-operator/thirdparty/charts/rancher-backup/Chart.yaml, platform-operator/thirdparty/charts/rancher-backup/README.md, platform-operator/thirdparty/charts/rancher-backup/files/default-resourceset-contents/rancher.yaml, platform-operator/thirdparty/charts/rancher-backup/templates/deployment.yaml, platform-operator/thirdparty/charts/rancher-backup/tests/deployment_test.yaml, platform-operator/thirdparty/charts/rancher-backup/tests/pvc_test.yaml, platform-operator/thirdparty/charts/rancher-backup/tests/s3-secret_test.yaml, platform-operator/thirdparty/charts/rancher-backup/values.yaml, platform-operator/verrazzano-bom.json
Rancher backup operator 2.1.3 image and new charts
=> VZ-6804- Rancher backup operator 2.1.3

ci/verify-distribution/Jenkinsfile
=> Initial commit

platform-operator/controllers/verrazzano/component/mysqloperator/mysqloperator_component.go
Looks like the MySQL operator is not setting the ImagePullSecretKeyname, not sure if that is required, but trying that similar to how other components are setting it (setting like the MySQL component)
=> Fix MySQL operator issues with private registry test

ci/JenkinsfilePeriodicTests
User branches need to do a docker login on ghcr to pull private images down
=> fix user branch tarball generation from periodics

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.4 to 1.3.5
=> Updating development version from 1.3.4 to 1.3.5

pkg/capi/bootstrap_provider.go, pkg/capi/kind_cluster_manager.go, pkg/capi/no_cluster_manager.go, pkg/os/file.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, tools/vz/cmd/cluster/cluster.go, tools/vz/cmd/cluster/cluster_create.go, tools/vz/cmd/cluster/cluster_get_kubeconfig.go, tools/vz/cmd/cluster/cluster_test.go, tools/vz/pkg/constants/constants.go
=> Added vz cluster get-kubeconfig for CAPI

platform-operator/verrazzano-bom.json
=> VZ 6901: 1.3.5 image tags

tests/e2e/verify-install/bom-validator/bom_validator_test.go
Updated exclusion list to support upgrade from 1.3.4
Fixes VZ-5937
=> VZ-5937: Updated exclusion list to support upgrade from 1.3.4

pkg/capi/no_cluster_manager.go, tools/vz/cmd/cluster/cluster_get_kubeconfig.go, tools/vz/cmd/cluster/cluster_test.go
=> VZ CLI get-kubeconfig merges into existing kubeconfig

tools/vz/cmd/cluster/cluster_create.go, tools/vz/pkg/constants/constants.go
=> Cleanup help messages for VZ cluster commands

platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update release-1.3 to use WebLogic Operator 3.4.3
=> VZ-6938: update release-1.3 to use WebLogic Operator 3.4.3

LICENSE.txt
Update the date in LICENSE.txt file.
=> Update license copyright.

ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger
Disables upgrade stages in MC pipeline, replaced by upgrade-paths tests.
=> Disable upgrade stages in MC pipeline in periodic and triggered test suites

platform-operator/controllers/verrazzano/transform/merge.go, tests/e2e/update/opensearch/opensearch_nodegroup_test.go, tests/e2e/update/opensearch/opensearch_update.go
V1Alpha1 nodes are merged on conversion, eliminating the need for a duplicate check.
=> Dynamic Config Tests (OpenSearch)

platform-operator/verrazzano-bom.json
updates the console image version and SHA , that will enable UI test with increased timeout introduced in https://github.com/verrazzano/console/pull/215
=> update console image version

examples/ha/ha.yaml
The previous yaml does not build, this is the correct value for authProxy
=> Update authProxy field in HA yaml

platform-operator/verrazzano-bom.json
=> VZ-6787: Fix BOM validator test

release/docs/README_LITE.md
As per https://github.com/verrazzano/docs/pull/594, added 'Rancher Backup Operator v2.1.3' and 'Velero v1.8.1'
=> Added Component updates, impact from VZ-6988

platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component_test.go, platform-operator/controllers/verrazzano/component/opensearch/validation.go, platform-operator/controllers/verrazzano/component/opensearch/validation_test.go
open search v1beta1 validator and its unit test changes
=> VZ-6884 v1beta1 open search validator

platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component_test.go, platform-operator/controllers/verrazzano/component/opensearch/validation.go, platform-operator/controllers/verrazzano/component/opensearch/validation_test.go
Reverts verrazzano/verrazzano#4050
=> Revert "VZ-6884 v1beta1 open search validator"

platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
Update VMO helm chart versions to 1.3.5
=> Update VMO helm chart versions to 1.3.5

Jenkinsfile
=> NO-JIRA: fix push to ocir from main job

platform-operator/controllers/verrazzano/component/appoper/app_operator_component_test.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component_test.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go, platform-operator/controllers/verrazzano/component/common/vmi_test.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_test.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go, platform-operator/controllers/verrazzano/component/kiali/kiali_component_test.go, platform-operator/controllers/verrazzano/component/mysql/mysql_test.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component_test.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go, platform-operator/controllers/verrazzano/component/rancherbackup/rancher_backup_component_test.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component_context_test.go, platform-operator/controllers/verrazzano/component/velero/velero_operator_component_test.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_test.go, platform-operator/controllers/verrazzano/component/vmo/vmo_component_test.go, platform-operator/controllers/verrazzano/transform/merge.go, platform-operator/controllers/verrazzano/uninstall_test.go, platform-operator/controllers/verrazzano/upgrade_test.go, platform-operator/controllers/verrazzano/validator/ComponentValidatorImpl_test.go, platform-operator/main.go
Set component validators for V1beta1 so validator occurs.
=> Wire up v1beta1 validators

tests/e2e/verify-install/web/nginx_errors_test.go
This pull request fixes a regression caused by https://github.com/verrazzano/verrazzano/pull/3908.
=> Fix LRE test regression

release/docs/README_FULL.md, release/docs/README_LITE.md
=> VZ-6928: Add profiles to release docs

platform-operator/controllers/verrazzano/component/mysqloperator/mysqloperator_component.go, platform-operator/helm_config/charts/verrazzano/templates/thirdparty-networkpolicy.yaml, tests/e2e/security/netpol/network_policy_test.go
Fix intermittent install issue of MySQL statefulset not going ready
=> VZ-7033: Fix intermittent install issue of MySQL statefulset not going ready

platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/verrazzano-bom.json, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
upgrade Istio in VZ from 1.13 to 1.14.3
=> VZ-6762 Upgrade Istio to 1.14.3 

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.5 to 1.3.6
=> Updating development version from 1.3.5 to 1.3.6

platform-operator/controllers/verrazzano/component/istio/istio_component.go
=> Make Istio Envoy log message generic

release/scripts/verify_github_release.sh
Update SHA256 verification in verify_github_release.sh
=> Update SHA256 verification in verify_github_release.sh

platform-operator/verrazzano-bom.json
Update BOM images for v1.3.6 version update in release-1.3
=> VZ-7029: Update BOM images for v1.3.6 version update

platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/controller_test.go
=> VZ-7001 - Treat VZ status conditions as a map by condition type, not a list that we keep appending to

platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
VMO version needs to be bumped to 1.4.0
=> Update VMO to 1.4.0

tools/scripts/bom_utils.sh, tools/scripts/generate_image_list.sh, tools/scripts/list_package_versions.sh
Make gneerate_image_list.sh functional again
=> Fix some broken references in generate_image_list.sh

platform-operator/verrazzano-bom.json
=> Upstream rancher oracle/release/2.6.8

ci/examples/Jenkinsfile, tools/scripts/generate_image_list.sh
Image list was dropping the repo when there wasn't an override registry specified
=> fix image list generation

ci/chaos/Jenkinsfile, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/controller_test.go, tests/e2e/config/scripts/process_upgrade_yaml.sh
=> VZ-7001 fix -  Make the most recently updated status condition on the VZ resource always be the last one

ci/backup/JenkinsfileAlllBackupOKETest
=> VZ-7122: Disable mysql tests

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/internal/k8s/status/deployment_ready.go, platform-operator/internal/k8s/status/deployment_ready_test.go
=> VZ 7113: Wait for deployment to be ready by selectors (#4140)

platform-operator/verrazzano-bom.json
backport vmo changes from https://github.com/verrazzano/verrazzano/pull/4141
=> VZ-7002: backport vmo changes

ci/backup/JenkinsfileAlllBackupOKETest
Backport disabling mysql tests to 1.4
=> Backport disabling mysql tests to 1.4

platform-operator/controllers/verrazzano/component/registry/registry.go
=> VZ-7062: Sync registry getComponents func

platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx.go
Progress message update for pending IPs
=> VZ-5768 return progress message for pending IP address

platform-operator/verrazzano-bom.json
Update BOM to release-1.4 built images for console and VMO
=> Update BOM to release-1.4 built images for console and VMO

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Mask the text of password from log message
=> VZ-7125: Mask password text

release/builds/JenkinsfilePostPRT, release/builds/JenkinsfileScanReleaseBundle, release/scripts/get_release_artifacts.sh, release/scripts/scan_release_binaries.sh
Backports the change to include Verrazzano full distribution to the release pipelines, to release-1.4 branch
=> VZ-7130: Backport release automation changes include Verrazzano full distribution

ci/private-registry/Jenkinsfile, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh
Fixes the path in private-regsitry pipeline to use generated config from tarball for v1beta1
=> Fix path in private registry

ci/scripts/prepare_distribution_test_jenkins_at_environment.sh, platform-operator/manifests/profiles/v1beta1/base.yaml
…154)
* include all comps in their default state in base profile
* enable jaeger operator in pipeline
=> VZ-7129: BP 1.4

platform-operator/controllers/verrazzano/component/mysql/legacydb.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go, platform-operator/thirdparty/charts/mysql/templates/cluster_upgrade_job.yaml
PR to make the MySQL dump script idempotent. Cleans up the dump directory if the exec command did not run successfully
=> MySQL dump cleanup

pkg/k8sutil/k8sutil.go, platform-operator/controllers/verrazzano/component/common/test_utils.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/validator/ComponentValidatorImpl_test.go
webhook validation reports error if any of following components exists
- Istio
- Grafana
- Prometheus
=> VZ-6507 guard existing components

platform-operator/verrazzano-bom.json
=> VZ-7145: version update

pkg/k8sutil/k8sutil.go, platform-operator/controllers/verrazzano/component/common/test_utils.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/validator/ComponentValidatorImpl_test.go
add install-validation of existing OLCNE components
=> VZ-6507 validation of existing olcne components

ci/uninstall/JenkinsfileUninstallTest
Restore the uninstall chaos test.
=> Restore uninstall chaos test

platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
Remove override of GetDependencies() in Keycloak component
=> VZ-7133.  Fix Keycloak component dependencies

platform-operator/verrazzano-bom.json
Update mysql-operator version to 2.0.6
=> Update mysql-operator version to 2.0.6

.github/workflows/upstream-pull-request.yml
Trigger pull requests when upstream CI pushes changes to the Rancher branch.
=> adding GitHub action for generating automated pull requests for Rancher CI

.github/workflows/upstream-pull-request.yml
=> Added copyright

ci/dynamic-updates/Jenkinsfile, tests/e2e/pkg/common.go, tests/e2e/pkg/kubernetes.go, tests/e2e/update/apiconversion/apiconversion_suite_test.go, tests/e2e/update/apiconversion/apiconversion_test.go, tests/e2e/update/authproxy/authproxy_update_test.go, tests/e2e/update/fluentd/fluentd_update.go, tests/e2e/update/fluentd/fluentd_update_test.go, tests/e2e/update/fluentdextes/fluentdextes_test.go, tests/e2e/update/updater.go
This PR backports the e2e tests in dynamic updates job for changes introduced in API conversion for v1beta1 (#4181)
=> VZ-6784: Backport E2E Tests for API Conversion for changes in v1beta1

platform-operator/controllers/verrazzano/component/velero/velero_operator.go, platform-operator/controllers/verrazzano/component/velero/velero_operator_component.go, platform-operator/helm_config/overrides/velero-override-static-values.yaml, platform-operator/metricsexporter/metricsexporter_utils.go, tests/e2e/config/scripts/v1alpha1/install-verrazzano-kind.yaml, tests/e2e/config/scripts/v1beta1/install-verrazzano-kind.yaml
* VZ-7136: Initial commit
* VZ-7136: Enable velero in dev profile for tests
=> VZ-7136 - enable metrics map for velero (#4170)

platform-operator/verrazzano-bom.json
=> VZ-7145: version update (#4180)

platform-operator/verrazzano-bom.json
Fix typo in jaeger-operator version
=> Fix typo in jaeger-operator version

platform-operator/controllers/verrazzano/component/mysql/legacydb.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go
This PR checks if MySQL's primary key already exists before altering the table. Fixes an upgrade error found in 1.1.X and 1.2.X.
=> MySQL duplicate primary key check

platform-operator/thirdparty/charts/mysql-operator/Chart.yaml, platform-operator/thirdparty/charts/mysql-operator/templates/NOTES.txt
Update mysql-operator chart version to 2.0.6
=> Update mysql-operator chart version to 2.0.6

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go
Add client role view-users to verrazzano user, in the realm verrazzano-system.
=> VZ-7041: Add client role view-users to verrazzano user

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go
Apply Mike's fix for jaeger-operator image pull secrets
=> Apply Mike's fix for jaeger-operator image pull secrets

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go
Apply Mike's jaeger operator fix to master
=> Apply Mike's jaeger operator fix to master

platform-operator/verrazzano-bom.json
Cherry-picked from master.  Updated Dashboard with changes from QA testing.
=> updated Rancher image with dashboard

tests/e2e/verify-install/keycloak/keycloak_test.go
Update post upgrade expected PV's
=> Update pv's [temporary]

platform-operator/controllers/verrazzano/component/mysql/legacydb.go
=> Root priv update

platform-operator/controllers/verrazzano/component/networkpolicies/netpol_component_test.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol_test.go
First pass at unit tests for the new verrazzano-network-policies install component.
=> VZ-7149: Unit tests for verrazzano-network-policies install component

tests/e2e/verify-install/keycloak/keycloak_test.go
=> Temporary disable of PV check

platform-operator/verrazzano-bom.json
=> VZ-7168: Update velero and components to 1.9.1

platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi.go, platform-operator/controllers/verrazzano/component/verrazzano/vmi_test.go
Reverts verrazzano/verrazzano#4255
=> Revert "Remove Prometheus bits from Verrazzano install component"

platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_component.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns_test.go, platform-operator/internal/vzconfig/ingress.go
Reverts verrazzano/verrazzano#4224
=> Revert "VZ-6932: Validated length of environment name and dns suffix based on user's spec with a webhook"

tools/scripts/vz-registry-image-helper.sh
* Improve output and error reporting for helper script
* Catch podman login errors
=> Backport fix to vz-helper script output to release 1.3

platform-operator/verrazzano-bom.json
The new image has updated restic version of 0.13.1
=> VZ-7268: update new velero images

tools/scripts/vz-registry-image-helper.sh
* Improve output and error reporting for helper script
* Catch podman login errors
=> Backport fix to vz-helper script output to release 1.4

ci/ha/JenkinsfileRollingUpgrade
Temporarily disable console tests for HA pipeline
=> Disabling HA console test

release/scripts/create_github_release.sh
=> backport VZ-7274 to 1.4

ci/ha/JenkinsfileRollingUpgrade
Temporarily disable console tests for HA pipeline
=> Disable console test

CHANGES.md
Add CHANGES.md for new release note process.
Note that the link in the 1.4.0 release notes will be dead until those are published
=> Add CHANGES.md for new release note process

.github/workflows/upstream-pull-request.yml
added quotes on branch name for action push filter
=> added quotes on branch name for action push filter

platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml
Update chart version to 1.5.0 for charts that were not updated by the helper tool
=> update version to 1.5.0 for charts that were not updated by the helper tool

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.0 to 1.4.1
=> Updating development version from 1.4.0 to 1.4.1

make/quality.mk
=> Exit if linter is wrong version

ci/multicluster/Jenkinsfile
This reverts commit 3b57b74cb6acc7c7030ad9761fc8c2bdb132f991.
=> VZ-6520.  Revert backport of MC pipeline change

ci/JenkinsfilePeriodicTests
=> Removed extra double quotes

platform-operator/verrazzano-bom.json
update Prometheus images
* Prometheus
* VZ-6305 Prometheus-Operator
*  Node-exporter
=> update Prometheus images

platform-operator/verrazzano-bom.json, tests/e2e/opensearch/topology/topology_test.go
Pick up new image for containing this fix: https://github.com/verrazzano/verrazzano-monitoring-operator/pull/263
=> VZ-7190: backport OS fix

platform-operator/verrazzano-bom.json
=> Use VMO with logging enhancement changes

platform-operator/verrazzano-bom.json
=> VZ-7355: update keycloak image

platform-operator/verrazzano-bom.json
=> VZ-7357: update OSD image

ci/uninstall/Jenkinsfile
=> Added retry with timeout for 30 minutes

Jenkinsfile, Makefile
This pull request changes the Jenkinsfile to use the precommit make target.
=> VZ-7276: Change Jenkinsfile to use precommit make target

platform-operator/verrazzano-bom.json
=> Rancher Dashboard custom UI bug fixes

platform-operator/verrazzano-bom.json
=> VZ-7356: update nginx-ingress-controller image

CHANGES.md
Update changes.md for MySQL changes
=> Update changes.md for MySQL changes

CHANGES.md, platform-operator/Dockerfile
Updates kubectl in platform operator image, in release-1.4
=> VZ-6630: Backport updating kubectl version in platform operator image to release-1.4

platform-operator/verrazzano-bom.json
=> VZ-6555: update oam-kubernetes-runtime image

tools/vz/cmd/bugreport/bugreport_test.go
Commented assertions for the intermittently failing unit test of bug-report CLI
=> VZ-6779: Comment assertions for the intermittently failing unit test of bug-report CLI

platform-operator/Dockerfile
Updates kubectl in platform operator image, in release-1.3
=> VZ-6630: Backport updating kubectl version in platform operator image to release-1.3

platform-operator/verrazzano-bom.json
*  VZ-6306 Prometheus-adapter
*  VZ-6307 Alertmanager
*  VZ-6308 kube-state-metrics
*  VZ-6309 Pushgateway
=> VZ-6294 Correct image tagging:

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.6 to 1.3.7
=> Updating development version from 1.3.6 to 1.3.7

ci/ha/JenkinsfileRollingUpgrade
Increase install timeout of high availability environment
=> VZ-7334: Increase install timeout of HA

platform-operator/Dockerfile
Updates kubectl in platform operator image, in release-1.2
=> VZ-6630: Backport updating kubectl version in platform operator image to release-1.2

CHANGES.md, platform-operator/verrazzano-bom.json
=> VZ-6556: Update Velero version

CHANGES.md, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/main.go
Cleanup code and add clarity to concerns
=> VZ-7127 Secondary cleanup PR

tools/vz/cmd/uninstall/uninstall.go, tools/vz/pkg/constants/constants.go
Added deletion of MySQL install values webhook to VZ uninstall command code.
=> JIRA:VZ-7172 add mysql install values webhook deletion to uninstall

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/generic/Jenkinsfile, ci/generic/Jenkinsfile-singletarget, ci/ha/JenkinsfileRollingUpgrade, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/oke-ocidns/JenkinsfileDnsSweepTests, ci/olcne/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/uninstall/JenkinsfileUninstallSuite, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade/Jenkinsfile
Move to new label naming, and start using E3.Flex3 shapes as well.
=> VZ-6802 Move to new label naming, and start using E3.Flex3 shapes as well

examples/sock-shop/micronaut/sock-shop-comp.yaml
Update to Socks Shop Micronaut 1.3.0 release in Sock Shop examples
=> VZ-7444: Update to Socks Shop Micronaut 1.3.0 release

ci/scripts/save_tooling.sh, tools/vz/Makefile
Reverts verrazzano/verrazzano#4410
=> Revert "NO JIRA: change feature branch pipelines to only build/save vz CLI Linux amd64 binary"

platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/main.go
Remove registry mutex, and initialize registry once during main.go to avoid race conditions.
=> Remove registry mutex

examples/sock-shop/spring/sock-shop-comp.yaml
VZ-7459: Update to Socks Shop Spring 1.2.3 release in Sock Shop examples
=> VZ-7459: Update to Socks Shop Spring 1.2.3 release

platform-operator/thirdparty/charts/mysql-operator/crds/crd.yaml, platform-operator/thirdparty/charts/mysql/Chart.yaml, platform-operator/thirdparty/charts/mysql/templates/deployment_cluster.yaml, platform-operator/verrazzano-bom.json
=> VZ-7457: Upgrade mysql to version 8.0.31

platform-operator/controllers/verrazzano/component/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager_test.go, platform-operator/internal/vzconfig/ingress.go
=> VZ-6932: Webhook, unit tests, refactoring (#4389)

platform-operator/verrazzano-bom.json
Updating development version from 1.4.1 -> 1.4.2
=> VZ-7439 Update dev version

platform-operator/thirdparty/charts/mysql-operator/Chart.yaml, platform-operator/thirdparty/charts/mysql-operator/templates/NOTES.txt
Update mysql operator chart tags
=> VZ-7457: Update mysql operator chart values

examples/multicluster/sock-shop/sock-shop-comp.yaml, examples/sock-shop/helidon/sock-shop-comp.yaml, tests/testdata/test-applications/coherence/hello-coherence/hello-coherence-comp.yaml
VZ-7462: Update to Socks Shop Helidon 1.2.2 release in Sock Shop examples
=> VZ-7462: Update to Socks Shop Helidon 1.2.2 release

platform-operator/verrazzano-bom.json
Updates rancher and rancher-agent images in release-1.3
=> VZ-6629: Update rancher and rancher-agent images in release-1.3

platform-operator/controllers/verrazzano/uninstall.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/main.go
Puts health check behind a feature flag
=> Feature flag health check

tests/e2e/pkg/ha/pods.go
Wait for the Pod Ready condition to be true in addition to the container statuses.
=> VZ-7464.  Fix pod Ready wait

platform-operator/verrazzano-bom.json
Updates rancher and rancher-agent images in release-1.2
=> VZ-6629: Update rancher and rancher-agent images in release-1.2

platform-operator/verrazzano-bom.json
updates rancher image to remove custom dashboard from 1.3
=> update rancher image

ci/olcne/Jenkinsfile
Add overwrite=true for storageclass annotation in OCNE pipeline
=> Add overwrite=true for storageclass annotation in OCNE pipeline

tools/vz/cmd/helpers/vpo.go
Follow-up PR based on previous feedback
=> VZ-7481: Improve readability of wait for VPO timer

tools/psr/backend/metrics/collector.go, tools/psr/backend/metrics/server.go, tools/psr/backend/spi/worker.go, tools/psr/backend/workers/doc.go, tools/psr/backend/workers/example/worker.go, tools/psr/backend/workers/opensearch/loggen.go, tools/psr/backend/workmanager/manager.go, tools/psr/backend/workmanager/runner.go, tools/psr/manifests/charts/k8s/values.yaml, tools/psr/manifests/charts/oam/values.yaml
Initial commit for worker metrics support
- Add collector
- Implement MetricsProvider for runner
- Add Worker.Init function
=> VZ-7421 initial commit for worker metrics support

tools/psr/backend/metrics/collector.go, tools/psr/backend/metrics/server.go, tools/psr/backend/spi/worker.go, tools/psr/backend/workers/doc.go, tools/psr/backend/workers/example/worker.go, tools/psr/backend/workers/opensearch/loggen.go, tools/psr/backend/workmanager/manager.go, tools/psr/backend/workmanager/runner.go
Restructure metrics code and worker so that worker i immutable.  Metrics must be kept in mutable struct reference by worker.
=> VZ-7421 restructure metrics code

tools/psr/backend/metrics/collector.go, tools/psr/backend/metrics/constants.go, tools/psr/backend/metrics/server.go, tools/psr/backend/spi/worker.go, tools/psr/backend/workers/example/worker.go, tools/psr/backend/workers/opensearch/loggen.go, tools/psr/backend/workmanager/runner.go
Add go metrics collectors so that they are included with the PSR metrics.
Add WorkerDesc
Minor refactoring of names.
=> VZ=7421 PSR add go metrics

ci/scripts/chaos_test_ephemeral_storage.sh
fallback to the tier lookup when waiting for mysql pod to restart
=> fallback to tier=mysql lookup

ci/olcne/Jenkinsfile
Backport a fix to get the OCNE pipeline working again.
=> Add overwrite=true for storageclass annotation (#4462)

platform-operator/verrazzano-bom.json
Updated images for Rancher cherry-picked from master
=> cherry-pick Rancher and Rancher Dashboard image names from master

tests/e2e/ha/inplaceupgrade/in_place_upgrade_test.go
Wait for mysql-operator to be ready when the HA test recycles it
=> VZ-7490: Wait for mysql-operator to be ready when the HA test recycles it

application-operator/main.go, pkg/log/loginit.go, pkg/log/loginit_test.go, pkg/log/vzlog/vzlog.go, platform-operator/controllers/clusters/sync_rancher_clusters.go, platform-operator/controllers/verrazzano/controller.go, platform-operator/controllers/verrazzano/status/availability.go
Set health check logger to error level - required some refactors to the logger code.
=> VZ 7507: log level for health check

application-operator/apis/oam/v1alpha1/ingresstrait_types.go, platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_ingresstraits.yaml
Edit the IngressTrait descriptions in the generated API files.
=> edit IngressTrait descriptions

platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
Edits on the Verrazzano v1beta1 spec descriptions in the generated API files.
=> edit generated spec

platform-operator/verrazzano-bom.json
* Automated CI from Rancher v2.6.8-20221024184735-77e20c949
Co-authored-by: Verrazzano BOT <verrazzanobot@oracle.com>
(cherry picked from commit 1c7b3fd4853042efa56668c64c67de7177a874b3)
=> CI: Update Rancher image in BOM (#4479)

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
First pass edits on the Verrazzano v1alpha1 spec descriptions in the generated API files.
=> first pass edits

ci/ha/JenkinsfileRollingUpgrade, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml, platform-operator/internal/k8s/certificate/certificate.go, platform-operator/internal/k8s/certificate/certificate_test.go, platform-operator/main.go, platform-operator/scripts/wait4webhook.sh
Reverting the recent changes to allow webhook scaling to see if that fixes the LRE upgrade issue that was recently hit.
=> VZ-7467.  Revert webhook scaling updates

tools/psr/Makefile, tools/psr/README.md, tools/psr/backend/workmanager/runner.go
Update the README and Makefile
=> VZ-7533 update readme and Makefile

ci/multicluster/Jenkinsfile, tests/e2e/config/scripts/register_managed_cluster.sh, tests/e2e/multicluster/verify-rancher/rancher_test.go
=> VZ-6465 create e2e tests to verify the pushed Manifest 

tools/psr/backend/config/config.go, tools/psr/backend/metrics/server.go, tools/psr/manifests/charts/worker/templates/deployment.yaml, tools/psr/manifests/charts/worker/values.yaml, tools/psr/manifests/scenarios/opensearch/s1/description.txt, tools/psr/manifests/scenarios/opensearch/s1/getlogs-fast.yaml, tools/psr/manifests/scenarios/opensearch/s1/getlogs-slow.yaml, tools/psr/manifests/scenarios/opensearch/s1/loggen.yaml, tools/psr/manifests/usecases/opensearch/getlogs.yaml, tools/psr/manifests/usecases/opensearch/loggen.yaml
Cleanup some naming and change metrics port to 8080
Add psuedo-code for scenarios as a starting point
=> VZ-7533 cleanup some naming and change metrics port to 8080

tools/psr/backend/config/config.go, tools/psr/backend/config/config_test.go, tools/psr/backend/workmanager/manager.go, tools/psr/backend/workmanager/runner.go, tools/psr/manifests/charts/worker/templates/component.yaml, tools/psr/manifests/charts/worker/templates/deployment.yaml, tools/psr/manifests/charts/worker/values.yaml
Run a worker in multiple goroutines so that we can scale a pod vertically (scale-up)
=> VZ-7565 add worker threads (goroutines)

tools/psr/README.md, tools/psr/backend/workers/opensearch/getlogs/getlogs.go, tools/psr/backend/workers/opensearch/writelogs/writelogs.go, tools/psr/backend/workmanager/runner.go
Update metrics names and README
=> VZ-7565- update README and metrics names

platform-operator/verrazzano-bom.json
=> VZ-7356: update ingress-nginx image

platform-operator/verrazzano-bom.json
=> Update nginx-ingress images

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#4553
=> Revert "Update nginx-ingress images"

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests
Backport backend tests to release-1.4
=> Backport backend tests to release-1.4

platform-operator/verrazzano-bom.json
port of https://github.com/verrazzano/verrazzano/pull/4369/files to 1.3
=> VZ-7577: update oam kubernetes runtime version(1.3)

platform-operator/verrazzano-bom.json
port of https://github.com/verrazzano/verrazzano/pull/4347
=> VZ-7576: update OSD image (1.3)

application-operator/apis/app/v1alpha1/metricsbinding_types.go, application-operator/apis/app/v1alpha1/metricstemplates_types.go, application-operator/apis/clusters/v1alpha1/multicluster_common_types.go, application-operator/apis/clusters/v1alpha1/multiclusterapplicationconfiguration_types.go, application-operator/apis/clusters/v1alpha1/multiclustercomponent_types.go, application-operator/apis/clusters/v1alpha1/multiclusterconfigmap_types.go, application-operator/apis/clusters/v1alpha1/multiclustersecret_types.go, application-operator/apis/oam/v1alpha1/ingresstrait_types.go, application-operator/apis/oam/v1alpha1/loggingtrait_types.go, application-operator/apis/oam/v1alpha1/metricstrait_types.go, application-operator/apis/oam/v1alpha1/status_types.go, application-operator/apis/oam/v1alpha1/verrazzanocoherenceworkload_types.go, application-operator/apis/oam/v1alpha1/verrazzanoweblogicworkload_types.go, platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
=> edit generated API docs

application-operator/apis/app/v1alpha1/metricsbinding_types.go, application-operator/apis/app/v1alpha1/metricstemplates_types.go, application-operator/apis/clusters/v1alpha1/multicluster_common_types.go, application-operator/apis/clusters/v1alpha1/multiclusterapplicationconfiguration_types.go, application-operator/apis/clusters/v1alpha1/multiclustercomponent_types.go, application-operator/apis/clusters/v1alpha1/multiclusterconfigmap_types.go, application-operator/apis/clusters/v1alpha1/multiclustersecret_types.go, application-operator/apis/oam/v1alpha1/ingresstrait_types.go, application-operator/apis/oam/v1alpha1/loggingtrait_types.go, application-operator/apis/oam/v1alpha1/metricstrait_types.go, application-operator/apis/oam/v1alpha1/status_types.go, application-operator/apis/oam/v1alpha1/verrazzanocoherenceworkload_types.go, application-operator/apis/oam/v1alpha1/verrazzanoweblogicworkload_types.go, platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
Reverts verrazzano/verrazzano#4568 - build failed on master
=> Revert "edit generated API docs"

tools/psr/backend/config/common.go, tools/psr/backend/metrics/collector.go, tools/psr/backend/metrics/server.go, tools/psr/backend/workers/opensearch/getlogs/getlogs.go, tools/psr/backend/workers/opensearch/writelogs/writelogs.go, tools/psr/backend/workmanager/runner.go, tools/psr/backend/workmanager/runner_test.go, tools/psr/manifests/charts/worker/templates/appconfig.yaml
This PR refactors the instantiation of PSR worker and runner metrics into common code.
=> Move PSR metrics to common code

tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/uninstall/uninstall_test.go
Make CLI resilient to loosing stream output of uninstall log
=> VZ-7506: Make CLI resilient to loosing stream output of uninstall log

platform-operator/verrazzano-bom.json
Support dynamic PVC resize with the VMO if the underlying storage class allows it.
=> VMO PVC Resize (1.4)

platform-operator/verrazzano-bom.json
Support dynamic PVC resize with the VMO if the underlying storage class allows it.
=> VMO PVC Resize

pkg/profiles/merge.go, platform-operator/apis/verrazzano/testdata/dev/v1beta1.yaml, platform-operator/apis/verrazzano/testdata/fromallcomps/v1beta1.yaml, platform-operator/apis/verrazzano/testdata/fromha/v1beta1.yaml, platform-operator/apis/verrazzano/testdata/fromocneha/v1beta1.yaml, platform-operator/apis/verrazzano/testdata/managed-cluster/v1beta1.yaml, platform-operator/apis/verrazzano/v1alpha1/convert_to.go, platform-operator/apis/verrazzano/v1alpha1/convert_to_test.go, platform-operator/controllers/verrazzano/component/spi/component_context_permutations_test.go, platform-operator/controllers/verrazzano/component/spi/component_context_test.go, platform-operator/controllers/verrazzano/component/spi/testdata/prodNoStorageOpenSearchOverrides.yaml
=> VZ 7578: workaround OS nodes omitempty replicas

platform-operator/controllers/verrazzano/component/opensearch/vmi.go, platform-operator/controllers/verrazzano/component/opensearch/vmi_test.go
Honor default volume source for opensearch profile nodes.
=> VZ 7588: Prod no storage for opensearch

ci/upgrade-paths/Jenkinsfile
This PR fixes the race condition for verify registry tests in upgrade paths pipeline.
=> VZ-7391: Fix race condition for verify registry test

ci/backup/JenkinsfileAlllBackupKinDTest, ci/backup/JenkinsfileAlllBackupOKETest
The stage ensures all components were installed correctly before running subsequent tests
=> VZ-7590: Add stage for verify install

pkg/log/vzlog/vzlog_test.go
=> Add test cases for log pkg

pkg/bom/bom_test.go, pkg/bom/testdata/test_bom.json
UT coverage for pkg/bom increased from 67.96% to 82.52%
=> Enhance UT coverage

ci/chaos/Jenkinsfile
=> Corrected Kubernetes version to 1.24

tests/e2e/pkg/elasticsearch.go, tests/e2e/upgrade/post-upgrade/opensearch/opensearch_test.go, tests/e2e/upgrade/pre-upgrade/opensearch/opensearch_test.go
Reverts verrazzano/verrazzano#4577
=> Revert "VZ-7544: Verify the expected plugins are installed for OpenSearch"

platform-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/controllers/clusters/vmc_controller.go, platform-operator/controllers/clusters/vmc_controller_test.go, tests/e2e/config/scripts/deregister_managed_cluster.sh
Reverts verrazzano/verrazzano#4602
=> Revert "VZ-6468: Delete Rancher cluster when VMC is deleted"

platform-operator/internal/operatorinit/run_webhook.go
Initialize the component validators, which got whacked with the recent refactorings.
=> VZ-7467. Fix init component validators

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go, tests/e2e/pkg/rancher.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
Code is added to disable the first login page for VZ customer because currently the bootstrap admin password which shows on ui is not correct and this setting is created from rancher code itself , so to remove this better remove the first login page .
=> Add disablefirstlogin method

pkg/k8sutil/apply_yaml_test.go, pkg/k8sutil/k8sutil_test.go, pkg/k8sutil/platform_operator_utils.go, pkg/k8sutil/platform_operator_utils_test.go
UT cases added for pkg/k8utils
Previously, Coverage for this package was 43.89 %
Now, With this MR, coverage is around 81 %
=> VZ-7541: Increase coverage by adding more UTs for pkg/k8utils

platform-operator/verrazzano-bom.json
* Automated CI from Rancher v2.6.8-20221102162449-77e20c949
=> CI: Update Rancher image in BOM (#4530)

ci/multicluster/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade/Jenkinsfile, platform-operator/verrazzano-bom.json
Updates Rancher and Rancher Agent images, where a change is made in Rancher to pin the bundled system charts to a specific commit.
=> Update Rancher image containing the change to use bundles chart

platform-operator/controllers/verrazzano/component/helm/helm_component_test.go
Add unit test cases for helm component to increase test coverage.
Package coverage increased from 47.9% to 91.9%
=> VZ-7595: Add unit test cases for helm component

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go
VZ-7540 - Fix linter errors in the code comments which were added to fix the review comments.
=> VZ-7540 - Fix linter errors breaking the master build

platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_test.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_test.go
=> Add test cases for prometheus component

ci/uninstall/JenkinsfileUninstallTest
Move uninstall resiliency console test fix to master from 1.4
=> Move fix to master from 1.4

platform-operator/internal/k8s/certificate/certificate.go, platform-operator/internal/k8s/certificate/certificate_test.go, platform-operator/internal/operatorinit/run_webhook.go, platform-operator/internal/operatorinit/update_webhooks.go, platform-operator/internal/operatorinit/update_webhooks_test.go
Follow-up unit testing and refactoring for VZ-7467
- add more unit tests
- refactor webhook update funcs/tests into operatorinit package
=> VZ-7467.  Followup tasks

platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
Updates the version in the chart for monitoring operator
=> Update the version in the chart for monitoring operator

tools/psr/backend/workers/opensearch/getlogs/getlogs.go, tools/psr/backend/workers/opensearch/postlogs/postlogs.go, tools/psr/manifests/usecases/opensearch/postlogs.yaml
This change makes the POST worker number of logs to post and length of logs configurable through envvars
=> VZ-7535 POST logs using bulk

platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
Fixed the missing development version update changes in the charts.
=> Updating the development version from 1.4.1 to 1.4.2

tools/psr/psrctl/cmd/constants/constants.go, tools/psr/psrctl/cmd/list/list.go, tools/psr/psrctl/cmd/start/start.go, tools/psr/psrctl/cmd/stop/stop.go, tools/psr/psrctl/pkg/scenario/find.go, tools/psr/psrctl/pkg/scenario/manager.go
Add ability to run a scenario where the scenario manifest files are external (not in the PSR binary)
=> VZ-7647 PSR psrctl - start external scenario

CHANGES.md, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json, tests/e2e/multicluster/workloads/mccoherence/coherence_workload_mc_test.go
Updates coherence operator to v3.2.9
=> VZ-6760: Update coherence operator to v3.2.9

platform-operator/controllers/verrazzano/component/common/crds_test.go, platform-operator/controllers/verrazzano/component/common/namespace_test.go, platform-operator/controllers/verrazzano/component/common/overrides_test.go, platform-operator/controllers/verrazzano/component/common/pvc_test.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt_test.go, platform-operator/controllers/verrazzano/component/common/rancher_test.go
Introduced missing UTs for platform-operator/controllers/verrazzano/component/common phase 1 for this 
Coverage: 40% -> 60.4%
There will be a one more PR for phase 2 UTs soon
=> VZ-7596: Unit tests for component.common to increase coverage.

platform-operator/internal/vzconfig/args_test.go, platform-operator/internal/vzconfig/enabled_test.go
Increased coverage from 56.23% to 92.7%
=> VZ-7651: Increase unit test coverage for platform-operator.internal.vzconfig

platform-operator/controllers/verrazzano/component/coherence/coherence_component_test.go
=> VZ-7681-Rahul/increase coverage for coherance

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.7 to 1.3.8
=> Updating development version from 1.3.7 to 1.3.8

tools/psr/manifests/charts/worker/values.yaml
build/push PSR image and update helm values.yaml
=> PSR build/push PSR image and update helm values.yaml 

tools/psr/Makefile, tools/psr/psrctl/cmd/root/root.go
Adding psrctl version command to root
=> Adding back psrctl version command

platform-operator/helm_config/charts/verrazzano-cluster-operator/.helmignore, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/NOTES.txt, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/serviceaccount.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/values.yaml
Template helm chart for the Verrazzano Cluster Operator
=> VZ-7662 initialize the Helm chart for the Verrazzano Cluster Operator

pkg/helm/helmcli.go, platform-operator/controllers/verrazzano/component/kiali/kiali.go, platform-operator/controllers/verrazzano/component/kiali/kiali_test.go
(cherry picked from commit 07b77fc5e61d48788a615ae27bf6f97faa0fb127)
=> VZ-6767 store Kiali signing key as a secret (#4249)

pkg/k8s/ready/available.go, pkg/k8s/ready/available_test.go, platform-operator/apis/verrazzano/v1alpha1/convert_from.go, platform-operator/apis/verrazzano/v1alpha1/convert_to.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1alpha1/zz_generated.deepcopy.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/zz_generated.deepcopy.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/component/vmo/vmo_component.go, platform-operator/controllers/verrazzano/reconcile/install_test.go, platform-operator/controllers/verrazzano/status/availability.go, platform-operator/controllers/verrazzano/status/availability_test.go, platform-operator/controllers/verrazzano/status/health_checker.go, platform-operator/controllers/verrazzano/status/status_updater_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml, platform-operator/mocks/component_mock.go
Make component status availability a non-binary value.
=> VZ 7552: Availability is non-binary

CHANGES.md
=> VZ-7702: changelog update for cert-manager

application-operator/controllers/ingresstrait/ingresstrait_controller.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx.go
Reverts verrazzano/verrazzano#4666
=> Revert "Backport minor updates for 1.4.2"

platform-operator/verrazzano-bom.json
Updates nginx-ingress images in release-1.4
=> Update nginx-ingress images in release-1.4

platform-operator/verrazzano-bom.json
Updates nginx-ingress images in release-1.3
=> Update nginx-ingress images in release-1.3

application-operator/controllers/navigation/trait_test.go, application-operator/controllers/navigation/workload_test.go
Increased coverage from 68.05% to 94.6%
=> VZ-7732: Increase unit test coverage for application-operator.controllers.navigation

platform-operator/controllers/verrazzano/component/weblogic/weblogic_component_test.go
=> add unit test case for weblogic component

make/generate.mk
=> Exit make manifests on bad controller-gen version

pkg/k8sutil/apply_yaml_test.go, tools/psr/backend/config/config.go, tools/psr/backend/pkg/k8sclient/client.go, tools/psr/backend/pkg/opensearch/opensearch.go, tools/psr/backend/pkg/opensearch/update.go, tools/psr/backend/pkg/verrazzano/vzcr.go, tools/psr/backend/workers/opensearch/getlogs/getlogs.go, tools/psr/backend/workers/opensearch/scale/scale.go, tools/psr/backend/workers/opensearch/writelogs/writelogs.go, tools/psr/backend/workmanager/manager.go, tools/psr/backend/workmanager/runner.go, tools/psr/manifests/charts/worker/templates/clusterrolebinding.yaml, tools/psr/manifests/charts/worker/templates/serviceaccount.yaml, tools/psr/manifests/scenarios/opensearch/s1/usecase-overrides/writelogs.yaml, tools/psr/manifests/scenarios/opensearch/s2/usecase-overrides/getlogs-fast.yaml, tools/psr/manifests/scenarios/opensearch/s2/usecase-overrides/getlogs-slow.yaml, tools/psr/manifests/scenarios/opensearch/s2/usecase-overrides/writelogs.yaml, tools/psr/manifests/scenarios/opensearch/s3/usecase-overrides/writelogs-fast.yaml, tools/psr/manifests/usecases/opensearch/scale.yaml, tools/psr/manifests/usecases/opensearch/writelogs.yaml
Recommiting the PSR scale worker code.  I commented out the flaky unit tests and will follow up.
=> VZ-7440 scale recommit

platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go
Coverage for platform-operator.controllers.verrazzano.component.grafana increased from 70% to 90%
=> VZ-7682:Enhance UT coverage for Grafana component

tests/e2e/pkg/common.go, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
=> VZ-7684:derive envoy proxy image ref from bom in test(port of #4694)

tools/psr/backend/workers/opensearch/scale/scale.go, tools/psr/backend/workers/opensearch/scale/scale_test.go, tools/psr/manifests/scenarios/opensearch/s2/usecase-overrides/getlogs-slow.yaml, tools/psr/manifests/scenarios/opensearch/s2/usecase-overrides/writelogs.yaml, tools/psr/manifests/usecases/opensearch/scale.yaml, tools/psr/psrctl/pkg/scenario/manifest.go, tools/psr/psrctl/pkg/scenario/manifest_test.go
Unit tests for PSR scale
Fix misc scenario config
Remove empty manifest files
=> VZ-7440 PSR scale unit tests

application-operator/apis/oam/v1alpha1/metricstrait_types.go, platform-operator/helm_config/charts/verrazzano-application-operator/crds/oam.verrazzano.io_metricstraits.yaml
update ports docs in MetricsTraitSpec
=> VZ-7744 update ports docs in MetricsTraitSpec

platform-operator/controllers/verrazzano/component/kiali/kiali_component_test.go, platform-operator/controllers/verrazzano/component/kiali/kiali_test.go
Increased coverage from 71% to 86.3%
=> VZ-7754: Increase unit test coverage for Kiali component

tools/psr/psrctl/cmd/constants/constants.go, tools/psr/psrctl/cmd/explain/explain.go, tools/psr/psrctl/cmd/root/root.go, tools/psr/psrctl/cmd/stop/stop.go, tools/psr/psrctl/cmd/update/update.go, tools/psr/psrctl/pkg/scenario/find.go, tools/psr/psrctl/pkg/scenario/start.go, tools/psr/psrctl/pkg/scenario/types.go, tools/psr/psrctl/pkg/scenario/update.go
Implement the PSR CLI update command
=> VZ-7675 PSR CLI update command

ci/JenkinsfileTestTrigger
PR to update Push triggered pipeline with console param for no injection tests.
=> Add console param for no injection in Push triggered pipeline

platform-operator/internal/config/config_test.go
VZ 7757: Increase UT coverage to 97.5% from 47.5%
=> VZ 7757: Increase UT coverage for platform-operator/internal/config

tools/psr/backend/spi/worker.go, tools/psr/backend/workers/example/worker.go, tools/psr/backend/workers/http/get/get.go, tools/psr/backend/workers/opensearch/getlogs/getlogs.go, tools/psr/backend/workers/opensearch/postlogs/postlogs.go, tools/psr/backend/workers/opensearch/scale/scale.go, tools/psr/backend/workers/opensearch/writelogs/writelogs.go, tools/psr/backend/workmanager/manager.go, tools/psr/backend/workmanager/manager_test.go, tools/psr/backend/workmanager/runner.go, tools/psr/backend/workmanager/runner_test.go
Provides a contract for soft dependency checking for workers, with initial stubbed impls.
=> VZ-7468.  Add PreconditionsMet() in the PSR Worker SPI

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.3.8 to 1.3.9
=> Updating development version from 1.3.8 to 1.3.9

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.2 to 1.4.3
=> Updating development version from 1.4.2 to 1.4.3

platform-operator/controllers/verrazzano/component/mysql/mysql_component.go, platform-operator/controllers/verrazzano/component/mysql/mysql_test.go
=> VZ-7524: re-enable unit test TestRepairMySQLPodsWaitingReadinessGates

tests/e2e/verify-infra/restapi/rancher_url_test.go
The pull request fixes an intermittent failure in rancher_url_test.go when comparing UI logo settings.  The fix was to sanitize strings before comparing.
=> VZ-7791: fix intermittent failure in rancher_url_test.go

tests/e2e/pkg/test/framework/ginkgo_wrapper.go
Reverts verrazzano/verrazzano#4782
=> Revert "Register all test panics as failed tests"

tests/e2e/verify-infra/restapi/rancher_url_test.go
Add some logging to help debug test failure in rancher_url_test.go
=> VZ-7791: Add some logging to help debug test failure

platform-operator/apis/verrazzano/webhooks/common_test.go, platform-operator/apis/verrazzano/webhooks/mysql_backup_webhook_test.go, platform-operator/apis/verrazzano/webhooks/mysql_values_webhook_v1alpha1_test.go, platform-operator/apis/verrazzano/webhooks/mysql_values_webhook_v1beta1_test.go
Increased UT coverage for webhooks
=> VZ-7771: Increased UT for platform-operator/..../webhooks

platform-operator/controllers/verrazzano/component/spi/component_context_test.go
Coverage increased from 17.1% to 82.93%
=> Enhance UT coverage for spi component

ci/backup/JenkinsfileAlllBackupOKETest, tests/e2e/config/scripts/v1beta1/install-verrazzano-oke-backup-enabled.yaml
=> VZ-7793 - Improve Backup Up Test Pipeline

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go
Backport to release-1.4 branch
=> VZ-7772: Fix webhook for validating vz profile (#4802)

tests/e2e/pkg/test/framework/ginkgo_wrapper.go
=> Register metrics for panicked tests

ci/JenkinsfilePeriodicTests, ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileTrigger
The PR changes the dynamic config tests to run in 3 parallel test groups, modeled similarly to the upgrade resiliency tests
=> VZ-7492 - Split Dynamic Config Tests into multiple suites

application-operator/controllers/loggingtrait/loggingtrait_controller_helper.go, application-operator/controllers/loggingtrait/loggingtrait_controller_helper_test.go, application-operator/controllers/loggingtrait/loggingtrait_controller_test.go
=> VZ-7799: Increase unit test coverage for application-operator.controllers.loggingtrait

tools/scripts/k8s-dump-cluster.sh
Add dump of Rancher settings resource to cluster dump.
=> VZ-7791: Add dump of Rancher settings resource to cluster dump

tests/e2e/pkg/test/framework/ginkgo_wrapper.go
Reverts verrazzano/verrazzano#4791
=> Revert "Register metrics for panicked tests"

platform-operator/controllers/verrazzano/component/istio/app_restart.go
This PR backports a fix to user application rolling restarts during upgrade. Without these fixes, when upgrading to Verrazzano 1.4.2, all user applications are restarted even when they do not need to be restarted.
=> VZ-7156: Verrazzano upgrade rolling restart fix (release-1.4)

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
configure ui-brand setting in rancher install/upgrade
=> VZ-7832: configure ui-brand setting in rancher install

platform-operator/controllers/verrazzano/component/mysql/mysql_workarounds.go, platform-operator/controllers/verrazzano/component/mysql/mysql_workarounds_test.go
Additional changes based on review feedback of previous PR.
=> VZ-7796: Additional changes for uninstall workaround for MySQL pods stuck terminating 

platform-operator/verrazzano-bom.json
Updated Rancher Dashboard to match master branch.  Includes bug fixes and new dashboard images.
=> Cherry picked from master.  Updated dashboard images.

tests/e2e/backup/helpers/constants.go
=> VZ-7793: Reduce rancher user count to 1

cluster-operator/Makefile
=> Fix cluster operator unit-test make target

tools/psr/README.md
A few more updates to PSR README
=> PSR README updates

platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
porting https://github.com/verrazzano/verrazzano/pull/4831
=> VZ-7832: rancher ui-brand setting related changes

tools/scripts/generate_image_list.sh
Includes rancher images from verrazzano/rancher repository
=> VZ-7877: Include rancher images from verrazzano/rancher repository

tools/psr/backend/workmanager/runner.go
Add jitters to the PSR runner.
=> VZ-7804 add sleep jitters to PSR runner

release/builds/JenkinsfilePRT, release/builds/JenkinsfileSourceArchive, release/scripts/archive_source_prt.sh, release/scripts/download_source_prt.sh
This change adds a new Jenkinsfile to download the source from various repositories defined in an input properties file and creates an archive.
=> VZ-7875: Pipeline to download source files

tools/psr/manifests/scenarios/opensearch/s5/scenario.yaml
Restrict the PSR OpenSearch scale scenario to master tier for now.
=> Restrict the PSR OpenSearch scale scenario to master tier

release/Makefile, release/scripts/archive_source_prt.sh, release/scripts/download_source_prt.sh
Includes a Makefile target to archive the source code
=> VZ-7842: Makefile target to archive the source code

ci/JenkinsfilePeriodicTests, ci/scripts/update_last_clean_periodic_test.sh, release/builds/JenkinsfilePreRelease, release/scripts/get_release_artifacts.sh
Backport VZ-7789 to release 1.4
=> Backport VZ-7789 to release 1.4

application-operator/internal/operatorinit/run_operator.go, application-operator/internal/operatorinit/run_webhook.go, application-operator/main.go
Handle errors instead of continuing.
=> VZ 7919: Handle errors in app operator main

tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/pkg/analysis/internal/util/cluster/pods.go, tools/vz/pkg/analysis/main_test.go, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/deployments.json, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/events.json, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/helm-operation-d2p4w/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/helm-operation-dlhvn/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/helm-operation-gjfls/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/helm-operation-s5stv/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/helm-operation-xnktw/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/pods.json, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/rancher-649dc876b-dt67w/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/rancher-649dc876b-dwqjg/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/rancher-649dc876b-kdrb2/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/rancher-webhook-6958cfcddf-7wchz/logs.txt, tools/vz/pkg/analysis/test/cluster/testCattleSystempods/cluster-snapshot/cattle-system/services.json
Added some changes to get rid of logs of helm pods when rancher pods are working fine.
=> VZ-7484:Get rid of report on helm operation pods if rancher pods are working fine

platform-operator/helm_config/charts/verrazzano/templates/verrazzano-logging.yaml
=> VZ-7876: fix fluentd config to prevent duplication of logs in OS(1.3)

CHANGES.md, platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
=> VZ-7876: fix fluentd config to prevent duplication of logs in OS

platform-operator/apis/verrazzano/webhooks/mysql_values_webhook_v1alpha1.go, platform-operator/apis/verrazzano/webhooks/mysql_values_webhook_v1beta1.go, tests/e2e/verify-install/validators/component_validator_basic_test.go, tests/e2e/verify-install/validators/mysql_podspec_validator_test.go
Add some extra logging to debug, issue clean up code a bit.
- also improve validator tests error reporting
=> VZ-7851.  Improve validator tests error reporting, add some minimal logging to debug issue

pkg/constants/constants.go, platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml
=> Update the name for the Verrazzano Cluster Registrar user

platform-operator/controllers/verrazzano/component/rancher/rancher.go
=> Replace all dashes with spaces in RoleTemplate display name

pkg/controller/errors/errors.go, pkg/controller/errors/errors_test.go
Fixes formatting of retryable errors.
=> Format Retryable error

platform-operator/controllers/verrazzano/component/helm/helm_component.go
Clean up Helm Component secrets logging.
=> Helm Component secrets logging

application-operator/apis/oam/v1alpha1/ingresstrait_methods.go, application-operator/apis/oam/v1alpha1/loggingtrait_methods_test.go, application-operator/apis/oam/v1alpha1/metricstrait_methods.go, application-operator/apis/oam/v1alpha1/metricstrait_methods_test.go, application-operator/controllers/reconcileresults/reconcile_results.go, application-operator/controllers/reconcileresults/reconcile_results_test.go
Few code file were reverted, which brokes copyright changes, this will fix those.
=> fix copyright due to revert

tests/e2e/pkg/kubernetes.go, tests/e2e/update/env-dns-cm/env_dns_cert_update_test.go
=> Update the DNS Cert Update test to give more reliable feedback

platform-operator/controllers/verrazzano/component/appoper/app_operator_component.go, platform-operator/controllers/verrazzano/component/appoper/app_operator_component_test.go, platform-operator/controllers/verrazzano/component/oam/oam_component.go, platform-operator/controllers/verrazzano/component/oam/oam_component_test.go, platform-operator/controllers/verrazzano/component/vmo/vmo_component.go, platform-operator/controllers/verrazzano/component/vmo/vmo_component_test.go
Apply CRDs as part of PreInstall.
=> VZ 7901: PreInstall apply CRDs

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_metrics.go
Allow managed cluster registration when Prometheus is disabled.
=> VZ 7977: Managed cluster registration with Prometheus disabled

platform-operator/helm_config/charts/grafana/Chart.yaml, platform-operator/helm_config/charts/grafana/dashboards/coherence/alerts-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/cache-details-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/caches-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/coherence-dashboard-main.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/elastic-data-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/federation-details-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/federation-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/http-servers-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/kubernetes-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/machines-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/member-details-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/members-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/persistence-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/proxy-server-detail-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/proxy-servers-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/service-details-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/coherence/services-summary-dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/helidon/helidon_dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/system/opensearch_dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/system/system_dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/system/system_health_dashboard.json, platform-operator/helm_config/charts/grafana/dashboards/weblogic/weblogic_dashboard.json, platform-operator/helm_config/charts/grafana/templates/configmaps.yaml, platform-operator/helm_config/charts/grafana/templates/dashboard_provider.yml, platform-operator/helm_config/charts/grafana/values.yaml
=> VZ-7940 Add Grafana dashboard Helm chart - not yet used by Verrazzano

platform-operator/verrazzano-bom.json
Updates Keycloak 15.0.2 image in release-1.4
=> Update Keycloak 15.0.2 image in release-1.4

platform-operator/verrazzano-bom.json
Cherry pick CI: Update Rancher image in BOM (#4995)
=> Cherry pick CI: Update Rancher image in BOM (#4995)

platform-operator/verrazzano-bom.json
Updates Keycloak 15.0.2 image in release-1.3
=> Update Keycloak 15.0.2 image in release-1.3

platform-operator/verrazzano-bom.json
=> Scchen/update 1.4

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go
=> VZ-7641-test jaeger resources

CHANGES.md, platform-operator/verrazzano-bom.json
Updates Grafana to v7.5.17 in release-1.4
=> VZ-7935: Update Grafana v7.5.17 in release-1.4

platform-operator/verrazzano-bom.json
Updates OpenSearch image in release-1.4
=> VZ-7961: Update OpenSearch image in release-1.4

platform-operator/helm_config/overrides/prometheus-operator-values.yaml
=> VZ-7983 Add the kube-prometheus-stack dashboards to Grafana

platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml
Add pod security to the VPO init container that was previously missed.
=> VZ-8002 VPO pod security initcontainer

tools/vz/pkg/analysis/internal/util/cluster/analyzer_test.go
=> VZ-7643 Go formatting

CHANGES.md, platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
=> Include OS and OSD in 1.5 release notes and update 2.3 doc references

platform-operator/verrazzano-bom.json, tests/e2e/metrics/syscomponents/metrics_test.go
Reverts verrazzano/verrazzano#4993
=> Revert "VZ:7904: update VMO operator image to add default index patterns in OSD"

CHANGES.md
Component version updates for istio, jaeger and kiali
=> Component version updates for istio, jaeger and kiali

cluster-operator/controllers/rancher/rancher_cluster_controller.go, cluster-operator/controllers/vmc/vmc_controller.go, cluster-operator/internal/operatorinit/run_operator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/helm_config/charts/verrazzano-network-policies/templates/networkpolicy.yaml, platform-operator/thirdparty/manifests/prometheus-operator/vco_monitor.yaml
=> VZ-8067 Export metrics from the Cluster Operator

platform-operator/helm_config/charts/verrazzano-console/templates/console-deployment.yaml
Updates the console deployment to be in compliance with Verrazzano pod security standards
=> VZ-8054 Console pod security

platform-operator/verrazzano-bom.json, tests/e2e/metrics/syscomponents/metrics_test.go, tests/testdata/upgrade/opensearch-dashboards/old-index-patterns.txt, tests/testdata/upgrade/opensearch-dashboards/updated-index-patterns.txt
update VMO image to add default metrics.
=> VZ-7904: update VMO image to add default index patterns

platform-operator/controllers/verrazzano/component/grafanadashboards/dashboard_component.go, platform-operator/controllers/verrazzano/component/grafanadashboards/dashboards.go, platform-operator/controllers/verrazzano/component/grafanadashboards/dashboards_test.go, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/istio-extension-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/istio-mesh-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/istio-performance-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/istio-service-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/istio-workload-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Istio/pilot-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/templates/configmaps.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/values.yaml
=> VZ-7982 Implement the Istio dashboards in Grafana

tests/e2e/verify-install/security/pod_security_test.go, tests/e2e/verify-install/security/security_suite_test.go
This adds a pod security e2e test to confirm that pods are deploy with the correct pod security configuration
=> VZ-7888 pod security e2e tests

tools/vz/cmd/status/status.go, tools/vz/pkg/templates/templates.go
Noticed component availability was missing from VZ Status command.
=> Add availability to vz status

platform-operator/helm_config/overrides/prometheus-operator-values.yaml, tests/e2e/verify-install/security/pod_security_test.go
Adds pod security for alertmanager
=> VZ-8106 alertmanager pod security

platform-operator/helm_config/charts/verrazzano-monitoring-operator/values.yaml
=> update current year in recently updated file

.github/dependabot.yml
=> Add copyright

tools/vz/cmd/status/status.go, tools/vz/cmd/status/status_test.go
Fixes panic introduced by previous change of VZ status command
=> Handle nil instance for vz status

platform-operator/helm_config/overrides/prometheus-node-exporter-values.yaml, tests/e2e/verify-install/security/pod_security_test.go
This change adds pod security for node exporter. It also updates the tests to add the node exporter hostpath exception.
=> VZ-V8103 Node Exporter pod security

ci/JenkinsfilePeriodicTests
Add retry for verrazzano-ha-tests stage
=> VZ-6696: Add retry of verrazzano-ha-tests stage to periodics

.github/workflows/stale.yml
VZ-8167 Close Stale Issues and PRs
=> VZ-8167 Create stale.yml

platform-operator/helm_config/overrides/ingress-nginx-values.yaml, platform-operator/thirdparty/charts/ingress-nginx/templates/default-backend-deployment.yaml, platform-operator/thirdparty/charts/ingress-nginx/values.yaml, tests/e2e/verify-install/security/pod_security_test.go
Update NGINX pod security settings to conform with Verrazano standards.
=> VZ-8094, VZ-8096.  Pod security for NGINX

ci/JenkinsfilePeriodicTests
disable HA tests in periodic pipeline
=> VZ-6696: disable HA tests in periodic pipeline

tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/web.go
Reverts verrazzano/verrazzano#5117
=> Revert "VZ-8174: Resolve all v1alpha1 deprecated warnings in HA test run"

go.mod, go.sum, platform-operator/apis/verrazzano/testdata/fromopensearch/v1alpha1.yaml, platform-operator/apis/verrazzano/testdata/fromopensearch/v1beta1.yaml, platform-operator/apis/verrazzano/v1alpha1/convert_from.go, platform-operator/apis/verrazzano/v1alpha1/convert_to.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go, platform-operator/controllers/verrazzano/component/opensearch/vmi.go, platform-operator/helm_config/charts/verrazzano-monitoring-operator/crds/verrazzano.io_verrazzanomonitoringinstances_crd.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml, platform-operator/verrazzano-bom.json
Update VMO image to add default ISM policies
=> VZ_8120: update vmoimage to add default ISM policies

platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go
Add missing nil label check in labelNamespace function.
=> Add missing nil label check in labelNamespace

platform-operator/thirdparty/charts/mysql/Chart.yaml, platform-operator/thirdparty/charts/mysql/templates/deployment_cluster.yaml, tests/e2e/verify-install/security/pod_security_test.go
Change mysql innodbCluster template to add pod security.  There are certain capabilities that must remain.  Also fixdatadir container needs to run as root.
=> VZ-8099 mysql and mysql router pod security

platform-operator/helm_config/overrides/kiali-server-values.yaml, platform-operator/thirdparty/charts/kiali-server/templates/deployment.yaml, platform-operator/thirdparty/charts/kiali-server/values.yaml, tests/e2e/verify-install/security/pod_security_test.go
Pod Security and container security for Kiali.
=> VZ-8115: Pod Security and container security for Kiali

ci/JenkinsfilePeriodicTests
Re-enable HA tests in periodic pipeline
=> VZ-6696: Re-enable HA tests in periodic pipeline

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/system_health_dashboard.json, platform-operator/helm_config/overrides/kube-state-metrics-values.yaml
The System dashboard component list displays as a table and a new cluster section gives information on Verrazzano clusters and nodes.
=> VZ-7984 Update The System Dashboards to Improve Displays

tests/e2e/verify-install/security/pod_security_test.go
Ignore mysql- pods for now so that HA pipeline passes.
=> Fix for mysql pod security test

tests/e2e/pkg/argocd.go
Fixing the issue in the master branch caused by the recent merge of PR - https://github.com/verrazzano/verrazzano/pull/5107
=> Fixing the issue in master branch

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/system_health_dashboard.json, platform-operator/helm_config/overrides/kube-state-metrics-values.yaml
Reverts verrazzano/verrazzano#5120
=> Revert "VZ-7984 Update The System Dashboards to Improve Displays"

application-operator/controllers/containerizedworkload/containerizedworkload_controller.go, application-operator/controllers/containerizedworkload/containerizedworkload_controller_test.go, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano Application/verrazzano-application-dashboard.json, platform-operator/helm_config/overrides/prometheus-operator-values.yaml
=> VZ-8125 Dashboard imrpovements and ContainerizedWorkload Bug Fix

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/JVM/jvm-micrometer.json
=> VZ-7997 continued - add cluster filter to JVM micrometer Grafana dashboard

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
This pull request adds/updates the comments related to the Argo CD component in the vz install API.  These comments are the basis for the API reference document which were not consistent with the other components.
=> Update api reference comments for argo cd

CHANGES.md, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/system_health_dashboard.json
Updated the Verrazzano system health Grafana dashboard so that the Verrazzano cluster drop-down is consistent with other dashboards. Also updated the CHANGES.md file to include all of the recent changes we've made to Grafana dashboards.
=> Update system health Grafana dashboard, add Grafana info to CHANGES.md

CHANGES.md, platform-operator/helm_config/overrides/mysql-values.yaml, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/mysql-operator/Chart.yaml, platform-operator/thirdparty/charts/mysql-operator/crds/crd.yaml, platform-operator/thirdparty/charts/mysql-operator/templates/NOTES.txt, platform-operator/thirdparty/charts/mysql-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/mysql/Chart.yaml, platform-operator/thirdparty/charts/mysql/templates/deployment_cluster.yaml, platform-operator/thirdparty/charts/mysql/values.yaml, platform-operator/verrazzano-bom.json
Update the mysql-operator, mysql-server, and mysql-router images in the Verrazzano BOM.
=> VZ-8250,VZ-8251: Update MySQL images

platform-operator/helm_config/overrides/istio-cr.yaml, tests/e2e/verify-install/security/pod_security_test.go
VZ-8116: Security context for pods and containers in istio-system namespace.
=> VZ-8116: Security context for pods and containers in istio-system namespace

CHANGES.md, platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/verrazzano-bom.json
=> VZ-8220: Upgrade to Istio 1.15.3

platform-operator/verrazzano-bom.json
These are just image rebuilds to pick up the latest base OS image and system packages.
=> Upgrade more Prometheus images

application-operator/controllers/ingresstrait/ingresstrait_controller.go, application-operator/controllers/webhooks/project_authorization_policy.go, pkg/k8sutil/k8sutil_test.go, pkg/k8sutil/platform_operator_utils_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go
Fixed due to underlying mutex nested in istio AuthorizationPolicy.
=> VZ-8192: Fixed due to underlying mutex nested in istio AuthorizationPolicy

platform-operator/verrazzano-bom.json
=> VZ-8253 Update weblogic-monitoring-exporter to 2.1.1

platform-operator/verrazzano-bom.json
=> Update Rancher and Rancher agent image bases

platform-operator/verrazzano-bom.json
PR to uptake rebuilt image to fix CVEs
=> Updated cert-manager-component with rebuilt image to fix CVEs

platform-operator/verrazzano-bom.json
=> Update the base image of the Verrazzano Console

platform-operator/verrazzano-bom.json
=> Rebuild the base image for the Jaeger images

platform-operator/verrazzano-bom.json
=> Uptake newer Velero images which are rebuilt with an updated OS image

platform-operator/verrazzano-bom.json
=> Use new oam image

platform-operator/verrazzano-bom.json
=> Add Kiali and k8s-sidecar base image update

tests/e2e/grafana-db/grafana_test.go
This test had a single `Eventually` block that deleted the Grafana pod and immediately checked to see if the pod had restarted, and if it did not, the `Eventually` would rerun and the pod would be deleted again.
This fix separates the pod deletion from checking for the restarted pod so that the test does not continually delete the pod.
=> Fix bug in grafana db end-to-end test

platform-operator/verrazzano-bom.json
=> Uptake new version of Rancher backup-restore-operator with updated base image

platform-operator/verrazzano-bom.json
=> Update the base image for the keycloak and keycloak-oracle-theme images

platform-operator/verrazzano-bom.json
=> Uptake external-dns image with updated base image

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
=> Update to use WKO 3.4.5 and WME 2.1.1

platform-operator/verrazzano-bom.json
Updated the opensearch image with rebuilt image to resolve CVE fixes
=> Update opensearch with rebuilt images

platform-operator/verrazzano-bom.json
PR to update base image for grafana with rebuilt
=> Updated base image for grafana

platform-operator/verrazzano-bom.json
=> Update the pilot and proxy base images

platform-operator/verrazzano-bom.json
=> Updated base image for fluentd-kuberentes-daemonset

ci/kind/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/private-registry/Jenkinsfile, tests/e2e/ingress/console/console_ingress_test.go, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_suite_test.go, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-application.yaml
We have two separate tests for Console Ingress trait and Logging Trait tests which deploys the same ToDo list application. Also, we run tests of these apps in parallel, leading to instability and issues that are harder to debug. Therefore, this PR combines these apps and removes redundant stages from the Jenkins pipelines.
=> VZ-8025: PR to combine WebLogic Ingress trait and Logging Trait tests. 

THIRD_PARTY_LICENSES.txt, go.mod, go.sum
Uptake go-pluralize 0.2.0 in Verrazzano
=> VZ-8355: Uptake go-pluralize 0.2.0 in Verrazzano

tests/testdata/ingress/console/components.yaml
This PR updates example-todo app image for console ingress tests.
=> VZ-8025: Update example-todo image for console ingress tests 

platform-operator/verrazzano-bom.json
=> Update Jaeger ES Rollover image base image

platform-operator/helm_config/overrides/kiali-server-values.yaml
Restored the external_services section in kiali-server overrides.
=> VZ-8371: Kiali showing error connecting to Prometheus on the Graph screen

platform-operator/verrazzano-bom.json
=> VZ-8364 Update the shell image helm version

tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonmetrics/helidon_metrics_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/examples/todo/todo_list_test.go
Follow on PR to https://github.com/verrazzano/verrazzano/pull/5213
=> VZ-8073 Improve tests to explicitly confirm all application ingress artifacts ready Part 2

platform-operator/helm_config/overrides/coherence-values.yaml
VZ-8332: Update the overrides in coherence-values.yaml for securityContext
=> VZ-8332: Update the overrides in coherence-values.yaml for securityContext

platform-operator/verrazzano-bom.json
Update vmo image to add timestamp in default index patterns
=> VZ-8308: Update VMO image to add timestamp in default index patterns

examples/bobs-books/bobs-books-comp.yaml, examples/helidon-config/helidon-config-comp.yaml, examples/hello-helidon/hello-helidon-comp-service-template.yaml, examples/hello-helidon/hello-helidon-comp.yaml, examples/multicluster/hello-helidon/hello-helidon-comp.yaml, examples/springboot-app/springboot-comp.yaml
Use new example app images that run as non-root
=> VZ-8358 use new examples images

platform-operator/verrazzano-bom.json
Change OL 7-slim to 8-slim, 7.9 to 8
=> Upgrade Oracle Linux image tags

platform-operator/verrazzano-bom.json
=> Update the Rancher and Rancher-agent images

tests/e2e/upgrade/pre-upgrade/verify/verify_preupgrade_test.go
This pull request fixes an upgrade-resiliency test failure after updating to  gopkg.in/yaml.v3 v3.0.1.
=> Fix failure in upgrade-resiliency test caused by update to gopkg.in/yaml.v3 v3.0.1

platform-operator/verrazzano-bom.json, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/pkg/hello_helidon.go
=> VZ-8147: ManualScalerTrait fix

platform-operator/verrazzano-bom.json, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/pkg/hello_helidon.go
Reverts verrazzano/verrazzano#5151
=> Revert "VZ-8147: ManualScalerTrait fix"

examples/bobs-books/bobs-books-comp.yaml
Use the old Bobs Books images that are in OCR.  This fixes a bobby UI problem that we are seeing.
=> Use old Bobs Books images

ci/lre/Jenkinsfile
This change updates the LRE pipeline to access the cluster through the Rancher Proxy rather than through the bastion
=> VZ- 8353 LRE pipeline using Rancher Proxy

pkg/helm/helmcli.go, pkg/helm/helmcli_test.go
This PR introduces a bug fix in `helmcli.go` that allows the `runHelm` function to retry the `helm upgrade` commands. This bug fix was originally from 1fbe23a4a8e1ec2347240e19b17751f6ffceb4f8.
=> VZ-8335: retrying Helm upgrade commands

examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/sock-shop/spring/sock-shop-comp.yaml
Sockshop examples deployment yaml files changed to fix this issue
=> VZ-8498 - Sockshop images need to be built with USER 1000 (or some other non-root user)

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/resource_usage_detailed_dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/resource_usage_summary_dashboard.json
=> VZ-8119: Add resource usage dashboards

platform-operator/verrazzano-bom.json
Uptake of the new console image containing the addition of Argo CD URL in the console UI
=> Topic add argocd console

platform-operator/verrazzano-bom.json
=> Update Bom images for external-dns shell and oam

ci/lre/Jenkinsfile, platform-operator/controllers/verrazzano/component/rancher/rancher.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
Fixes a bug in the Racher verrazzano user GlobalRoleBinding test to make sure that the right user is selected.
=> Fix Rancher verrazzano user GRB test

platform-operator/verrazzano-bom.json
=> Update the cert-manager images in the bom

tools/psr/backend/pkg/weblogic/domain.go
Updated copyright year to fix failing master
=> Updated copyright year to fix failing master

platform-operator/controllers/verrazzano/component/keycloak/keycloak_component_test.go
The `TestReconcile` unit test in `keycloak_component_test.go` was failing if you ran it while having a local Kind cluster with Verrazzano installed. It was passing if you had no such local Kind clusters.
This PR fixes this unit test such that it passes regardless of your local Kind cluster. This PR also makes the original intent of this unit test a little clearer by renaming the test and updating comments.
=> Fix Keycloak TestReconcile Unit Test Failure

platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
This is to change the default number of shards per index in OpenSearch from 5 to 1.
=> VZ-8346: Change the default number of shards per index to 1

platform-operator/verrazzano-bom.json
This VMO adds dynamic discovery of Grafana dashboards for all namespaces.
=> Upgrade VMO image

platform-operator/verrazzano-bom.json
=> VZ-8564 Update the Keycloak image tag

platform-operator/verrazzano-bom.json
Cherrpicking fff5011a75f13b2d22cd1aaa50ea5e7990ceb493 from https://github.com/verrazzano/verrazzano/pull/5293
=> VZ-8359: Updating bunch of k8s.io/ packages to v0.25.2

pkg/bom/bom_test.go, pkg/bom/testdata/test_bom.json, pkg/bom/testdata/verrazzano-bom.json, platform-operator/apis/verrazzano/testdata/test_bom.json, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/controllers/verrazzano/component/vmo/vmo_test.go, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/helm_config/charts/verrazzano-monitoring-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/values.yaml, platform-operator/verrazzano-bom.json, tools/url_linter/ignore_urls.txt
=> Update VMO helm tags for OpenSearch and OpenSearchDashboards (#5295)

platform-operator/verrazzano-bom.json
=> Backport VZ-8564 update the Keycloak image tag 

platform-operator/controllers/verrazzano/component/argocd/argocd_component.go
Currently the argocd ingress does not get patched after upgrade. This fixes this and does a little rework of the argocd code.
=> VZ-8566: Fix ArgoCD Upgrade

CHANGES.md
Add release notes related to IngressTraits
=> IngressTrait related release notes 1.5

CHANGES.md
Add release notes related to IngressTraits
=> IngressTrait related release notes 1.4

CHANGES.md
Add release notes related to IngressTraits
=> IngressTrait related release notes

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.3 to 1.4.4
=> Updating development version from 1.4.3 to 1.4.4

platform-operator/verrazzano-bom.json
=> VZ:8147: Update new OAM Image

platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
=> Copyright check

platform-operator/verrazzano-bom.json
=> Update BOM with new cert-manager image

platform-operator/verrazzano-bom.json
=> VZ-8601 update the restic restore helper image for velero

pkg/bom/testdata/verrazzano-bom.json, platform-operator/apis/verrazzano/testdata/fromallcomps/v1alpha1.yaml, platform-operator/apis/verrazzano/testdata/fromallcomps/v1beta1.yaml, platform-operator/apis/verrazzano/testdata/toallcomps/v1alpha1.yaml, platform-operator/apis/verrazzano/testdata/toallcomps/v1beta1.yaml, platform-operator/controllers/verrazzano/component/authproxy/testdata/noImageNameTestBOM.json, platform-operator/controllers/verrazzano/component/authproxy/testdata/noImageVersionTestBOM.json, platform-operator/controllers/verrazzano/component/authproxy/testdata/noMetricsImageTestBOM.json, platform-operator/controllers/verrazzano/component/authproxy/testdata/noMetricsImageVersionTestBOM.json, platform-operator/controllers/verrazzano/component/fluentd/fluentd_component_test.go, platform-operator/verrazzano-bom.json, tools/vz/pkg/helpers/vzhelper.go
Updated Verrazzano version references to 1.5.0
=> Updated Verrazzano version to 1.5.0

platform-operator/verrazzano-bom.json
Updating images with new developer version
=> updating image versions

platform-operator/verrazzano-bom.json
(cherry picked from commit 757af76360b1ae88fc24705ae43c95a7a5191be2)
=> cert-manager image backport

platform-operator/verrazzano-bom.json
=> Uptake nginx-prometheus-exporter version to fix the CVE

platform-operator/verrazzano-bom.json
=> uptake image to fix CVE for nginx-promethues-exporter

platform-operator/verrazzano-bom.json
=> Update the Keycloak image tag for new build

ci/JenkinsfileBackendTests
=> fix jenkinsfile

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano Application/verrazzano-application-dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/resource_usage_detailed_dashboard.json, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/resource_usage_summary_dashboard.json
- Same layout for resource usage and application dashboards
- some fixes to application dashboard regarding legends
- Removed points from graph as the graph looked a bit messy on increasing the time range
=> VZ-8554: updated resource usage and application dashboard

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/jwt/helidon-svc/helidon_example_test.go, tests/e2e/jwt/helidon/helidon_example_test.go, tests/e2e/pkg/metrics.go, tests/e2e/workloads/weblogic/weblogic_workload_test.go
Reverts verrazzano/verrazzano#5142
=> Revert "VZ-7975: Check for scrape targets instead of every metric in tests"

ci/JenkinsfileBackendTests
Backport backend test jenkinsfile fixes to release-1.5
=> Backport backend test jenkinsfile fixes

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
Updated API comments so doc is generated with the correct punctuation.
=> Updates to comments so API doc is correct

platform-operator/verrazzano-bom.json
=> Pick up latest Rancher and dashboard

cluster-operator/controllers/vmc/argocd.go, cluster-operator/controllers/vmc/argocd_test.go, pkg/rancherutil/rancher_config.go
Backport VZ-8616 multicluster integration of Argo CD in VZ 1.5
=> VZ-8616: ArgoCD multicluster fixes backport to 1.5

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/thirdparty/charts/rancher-backup/values.yaml, platform-operator/thirdparty/charts/rancher/values.yaml, platform-operator/verrazzano-bom.json, tests/e2e/registry/registry_test.go
* Backport to update rancher images
=> VZ-8602 New images for the 1.5 release need to have names that are compliant with OCR (#5358)

tests/e2e/config/scripts/create_ocir_repositories.sh, tools/scripts/manage-ocir-repositories.sh
Cherrypick of rancher is_public fix
=> Btidd/ispublic (#5365)

platform-operator/Dockerfile
Remove system-tools from VPO image.  It is no longer used.
=> VZ-8575: Remove system-tools from VPO image

tests/e2e/registry/registry_test.go
Adding justification for the added logic to private registry tests
=> VZ-8629 Rancher image addition

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.0 to 1.6.0
=> Updating development version from 1.5.0 to 1.6.0

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.0 to 1.5.1
=> Updating development version from 1.5.0 to 1.5.1

platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml, platform-operator/scripts/wait4webhook.sh
After reverting there were copyright years that were changed to the wrong year. This PR is to correct those years
=> Correct copyright years from Git revert

CHANGES.md, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/WebLogic/weblogic_dashboard.json
=> VZ-7931 part-deux: Backport to 1.5

platform-operator/verrazzano-bom.json
Updating images to have new dev version
=> v1.6.0 images

platform-operator/verrazzano-bom.json
Updating images to have new dev version
=> v1.5.1 images

tests/e2e/upgrade/pre-upgrade/opensearch-dashboards/opensearch_dashboards_test.go, tests/testdata/upgrade/opensearch-dashboards/post-1.5-index-patterns.txt
=> do not create the extra index patterns that are created by default

ci/JenkinsfilePeriodicTests, ci/dynamic-updates/JenkinsfileUpdateDuringInstall
This is a backport of https://github.com/verrazzano/verrazzano/pull/5330.
This adds a new E2E testing pipeline `ci/dynamic-updates/JenkinsfileUpdateDuringInstall` to test VZ CR updates during install.
This also adds two calls to this pipeline into the periodic tests.
=> VZ-8243 backport: E2E test change VZ CR during install

tests/e2e/upgrade/pre-upgrade/opensearch-dashboards/opensearch_dashboards_test.go, tests/testdata/upgrade/opensearch-dashboards/post-1.5-index-patterns.txt
Backport Aditya's OSD test update to 1.5
=> Backport Aditya's OSD test fixes to 1.5

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzcapture_test.go
=> VZ-8680: Backport additional namespace logs to be captured using cli

ci/scan-results/Jenkinsfile
Disable cron for release-1.0 scan job
=> Disable cron for release-1.0 scan job

ci/scan-results/Jenkinsfile
Disable the scan cron for 1.2, periodics have been disabled for a while
=> Disable cron job for 1.2

ci/scan-results/Jenkinsfile
This disables the daily scan job cron from 1.1 (periodics were turned off a while ago)
=> Disable cron jobs for release-1.1

release/builds/JenkinsfileSourceArchive, release/scripts/archive_source_prt.sh, release/scripts/download_source_prt.sh
This PR fixed Jenkinsfile used to archive the source code, by using the verrazzano-images.txt from the release branch.
=> VZ-7747: Fix source code archival

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/thirdparty/manifests/rancher-cleanup/rancher-cleanup.yaml
Move rancher-cleanup job to verrazzano-install namespace
=> VZ-8691: Move rancher-cleanup job to verrazzano-install namespace

platform-operator/verrazzano-bom.json
Rancher Dashboard Fixes:
- Fixes Argo CD link name on home page.
- Fixes version string for What's New on home page.
=> Backport: Automated CI from Rancher v2.6.8-20230213180120-e07716258

CHANGES.md, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-external-svc.tpl, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-internal-svc.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
=> WKO 4.0.5 and WME 2.1.2

tools/scripts/generate_image_list.sh
=> VZ-8646 generate image list with correct repository name (#5420)

ci/chaos/Jenkinsfile
Fix chaos test failure of type “upgrade.failing.upgrade”
=> VZ-8746: Fix chaos test failure of type “upgrade.failing.upgrade”

platform-operator/verrazzano-bom.json
Upgrade Rancher image tags to pick up the latest Rancher and Rancher Agent images.
=> VZ-8702: Upgrade Rancher image tags

ci/chaos/Jenkinsfile
Back port chaos test fix to release-1.5
=> VZ-8746: Back port chaos test fix to release-1.5 branch

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml, platform-operator/internal/config/config.go, platform-operator/internal/config/config_test.go, platform-operator/internal/operatorinit/run_webhook.go, platform-operator/main.go, platform-operator/scripts/wait4webhook.sh
Added boolean param to disabled resource requirements warnings and subsequent logic to test and toggle when desired.
=> VZ-8248 Disabling resource requirements validation

platform-operator/controllers/verrazzano/reconcile/controller_test.go, platform-operator/controllers/verrazzano/reconcile/status.go
(cherry picked from commit c6630682137f60abef14722b80f8b832f3c1a7a8)
=> VZ-8755: Fix bug where argoCD URL doesn't get set in VZ CR (#5432)

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml, platform-operator/internal/config/config.go, platform-operator/internal/config/config_test.go, platform-operator/internal/operatorinit/run_webhook.go, platform-operator/main.go, platform-operator/scripts/wait4webhook.sh
* backport from Master to disable resource validating webhoooks
=> VZ-8248 Disabling resource requirements validation (#5396)

ci/chaos/JenkinsfileResiliencyTrigger
=> Disable 1.2 tests

ci/backup/JenkinsfileAlllBackupOKETest, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
Remove unsupported OKE versions from 1.4 tests
=> Remove unsupported OKE versions from 1.4 tests

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.1 to 1.5.2
=> Updating development version from 1.5.1 to 1.5.2

ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade/Jenkinsfile
=> VZ-8845: Back port the increased wait timeout for uninstall

platform-operator/verrazzano-bom.json
Updating image versions from 1.5.1 to 1.5.2
=> Updating image versions from 1.5.1 to 1.5.2

.github/workflows/upstream-pull-request.yml
Allows changes to notification list without changing the action definition.  
Removes hardcoded userids from the workflow definition.
=> replaced GitHub action userid list with repository variable

cluster-operator/controllers/vmc/rancher.go
This is a follow up PR for https://github.com/verrazzano/verrazzano/pull/5433 to update Logging level from error to Info
> Changes to rancher.go file to log as Info when no existing CRT found
=> VZ-7954: Update logging level

CHANGES.md
=> VZ-8357: Update CHANGES.md to include Rancher 2.7.1

ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
PR to exclude deprecated VZ releases.
=> Exclude deprecated release

CHANGES.md, pkg/semver/semver.go, tools/vz/cmd/helpers/command.go, tools/vz/cmd/helpers/command_test.go
Backport to release-1.5 of https://github.com/verrazzano/verrazzano/pull/5500
=> VZ:-8758: backport of vz CLI version checking changes to release-1.5

.gitignore, platform-operator/apis/verrazzano/webhooks/requirements_webhook_v1alpha1.go, platform-operator/apis/verrazzano/webhooks/requirements_webhook_v1alpha1_test.go, platform-operator/apis/verrazzano/webhooks/requirements_webhook_v1beta1.go, platform-operator/apis/verrazzano/webhooks/requirements_webhook_v1beta1_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/validatingwebhookconfiguration.yaml, platform-operator/internal/operatorinit/run_webhook.go, platform-operator/scripts/wait4webhook.sh
This PR fixes an invalid VPO validating webhook error when using the 1.4 vz CLI to upgrade from 1.5.0 to 1.5.1.
=> VZ-8820: Upgrades from 1.5.0 to 1.5.1 with vz CLI 1.4.n has an invalid VPO validating webhook error

platform-operator/apis/verrazzano/validators/validate.go
Fix webhook error to be more comprehensive.
=> VZ 8883: Upgrade webhook error (#5509)

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests
Use URL trigger to control the periodic and backend pipeline triggers
=> VZ-8764: Use URL trigger to control the periodic and backend pipeline triggers

tests/e2e/verify-infra/vmi/vmi_test.go
This pull request includes a change to not run tests that look for recent log record for the verrazzano-system index.  There are no recent log records so the test was failing.
=> Change to LRE to not run a verify-infra-vmi test

tools/vz/THIRD_PARTY_LICENSES.txt
=> VZ-8060 Add Third party license file for vz CLI code

ci/backup/JenkinsfileAlllBackupOKETest, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
Limit OKE regions in 1.4 to North America
=> Limit OKE regions

ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, platform-operator/scripts/install/k8s-dump-objects.sh, tests/e2e/config/scripts/install-metallb.sh, tests/e2e/pkg/test/clusterdump/clusterdump.go, tools/scripts/k8s-dump-cluster.sh
This PR includes a cherry-pick of the following commits:
0dfe9e8
c9e7f6c
=> Backport changes related to metallb speaker pod restarting during load

ci/backup/JenkinsfileAlllBackupOKETest, ci/dynamic-updates/JenkinsfileUpdateDuringInstall, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
Don't run tests outside of North America for 1.5
=> Don't run tests outside of North America for 1.5

ci/ha/JenkinsfileRollingUpgrade
HA tests need to limit OKE region to North America
=> Limit OKE regions for HA test to North America

ci/oci-integration/Jenkinsfile
Fix OKE version in 1.3 OCI integration test
=> Fix OCI integration test OKE version in release-1.3

tools/vz/cmd/bugreport/bugreport_test.go
The VZ CLI bug report unit test occasionally fails because of an assertion that some text exists in the bug report output. The assertion was temporarily removed until the root cause of the bug could be determined.
I ran the unit test using golang's race condition detection mechanism. It revealed a race condition accessing a byte buffer. Here's a snippet of the output:
```
$ go test -race -run TestBugReportDefaultReportFile ./tools/vz/cmd/bugreport
==================
WARNING: DATA RACE
Write at 0x00c00088c050 by goroutine 53:
bytes.(*Buffer).Write()
/usr/local/Cellar/go/1.19.2/libexec/src/bytes/buffer.go:167 +0x44
io.(*multiWriter).Write()
/usr/local/Cellar/go/1.19.2/libexec/src/io/multi.go:85 +0xb9
fmt.Fprintf()
/usr/local/Cellar/go/1.19.2/libexec/src/fmt/print.go:205 +0xb1 …
```
=> VZ-6779: Fix race condition, do not use bytes buffer for stdout and stderr
