verrazzano/verrazzano

ci/dynamic-updates/JenkinsfileTrigger, ci/dynamic-updates/JenkinsfileUpdateDuringInstall
This PR adds verify-install and verify-infra stages to the new `verrazzano-dynamic-config-install-tests` pipeline.
I added these verification tests, using `ci/dynamic-updates/Jenkinsfile` as a guideline:
- `verify-install`
- `verify-infra-restapi`
- `verify-infra-oam`
This PR also modifies `ci/dynamic-updates/JenkinsfileTrigger` to pass in required parameters into the `verrazzano-dynamic-config-install-tests` pipeline.
=> VZ-8243: Add Verify-install stages to dynamic-config-install-tests

platform-operator/verrazzano-bom.json
Backport Rancher image upgrade to release-1.5 branch. The Rancher dashboard tag is the same (release-1.5 compared with master) so this did not require rebuilding the Rancher image for 1.5.
=> VZ-8702: Upgrade Rancher image tags (#5427)

ci/uninstall/JenkinsfileUninstallTest
Increase timeout for uninstall resiliency tests suite, the new rancher-cleanup job is taking longer to uninstall Rancher.
=> VZ-8753: Increase timeout for uninstall resiliency tests suite

platform-operator/verrazzano-bom.json
Backport a couple of image updates to the release-1.5 branch.
=> Update BOM to use latest prometheus and alertmanager release builds (#5424)

ci/JenkinsfilePeriodicTests, ci/dynamic-updates/JenkinsfileUpdateDuringInstall
This is a backport of https://github.com/verrazzano/verrazzano/pull/5419 from master.
This adds `verify-install` and `verify-infra` tests to the `verrazzano-dynamic-config-install-tests` pipeline.
This also modifies the periodic tests pipeline to pass in the added parameters from these changes.
=> VZ-8243: Verify-install stage in verrazzano-dynamic-config-install-tests

platform-operator/verrazzano-bom.json
This PR removes deprecated k8s version v1.20 from BOM file.
=> VZ-8656:Removed deprecated k8s version v1.20 from BOM

ci/JenkinsfilePeriodicTests
https://github.com/verrazzano/verrazzano/pull/5430 introduced modifications to the periodics pipeline.
This aims to fix errors found there. The `prepare_jenkins_at_environment.sh` script was failing, complaining about not having all required environment variables set. I believe that `VERRAZZANO_OPERATOR_IMAGE` was set as empty when calling the new pipeline from periodics, causing the failures.
Other problems found were also fixed.
=> VZ-8243: fix parameters calling verrazzano-dynamic-config-install-tests in periodics

ci/oke-ocidns/JenkinsfileDnsSweepTests
This PR backports a fix for the JenkinsfileDnsSweepTests pipeline with incorrect job name.
=> VZ-8276: Fix DNS sweep tests pipeline (#5356)

platform-operator/verrazzano-bom.json
This PR backports the change to remove deprecated k8s version v1.20 from BOM file.
=> VZ-8656: Removed deprecated k8s version v1.20 from BOM

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/examples/Jenkinsfile, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/test-examples/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade-paths/JenkinsfileTestTriggerPatchRelease, ci/upgrade/Jenkinsfile
This switches the release-1.3 jobs from using labels provisioned by the Jenkins OCI to using labels provisioned by the Jenkins Agent Operator.
=> Switch release 1.3 to use the JAO

platform-operator/verrazzano-bom.json
Flip the VMO image to fix:
- VZ-8707: Change OS master node's PVC ownerRef to VMI to fix upgrade when Sts gets randomly nuked by VMO post component upgrade.
- VZ-8763: Modify plugin install logic to fail only the master node in case of install failure.
=> VZ-8707 VZ-8763: latest VMO tag to fix upgrade and plugin bugs

CHANGES.md, platform-operator/verrazzano-bom.json
Flip the VMO image to fix:
- VZ-8707: Change OS master node's PVC ownerRef to VMI to fix upgrade when Sts gets randomly nuked by VMO post component upgrade.
- VZ-8763: Modify plugin install logic to fail only the master node in case of install failure.
=> VZ-8707 VZ-8763: flip VMO image containing bug fixes in 1.5

ci/dynamic-updates/JenkinsfileUpdateDuringInstall
This removes a reference to branches owned by Mark in `ci/dynamic-updates/JenkinsfileUpdateDuringInstall`.
=> VZ-8243: remove reference to Mark in JenkinsfileUpdateDuringInstall

cluster-operator/controllers/vmc/rancher.go, cluster-operator/controllers/vmc/sync_manifest_secret.go, cluster-operator/controllers/vmc/vmc_controller_test.go, pkg/httputil/httputil_test.go
- Changes to rancher.go to get the existing CRT token before creating one
=> VZ-7954: Fix to stop recreating cluster registration tokens

ci/dynamic-updates/JenkinsfileTrigger, ci/dynamic-updates/JenkinsfileUpdateDuringInstall
This is a backport of https://github.com/verrazzano/verrazzano/pull/5330 and https://github.com/verrazzano/verrazzano/pull/5419.
This adds a new E2E testing pipeline verrazzano-dynamic-config-install-tests (`ci/dynamic-updates/JenkinsfileUpdateDuringInstall`) to test VZ CR updates during install.
This new pipeline is then called twice by verrazzano-dynamic-config-suite (`ci/dynamic-updates/JenkinsfileTrigger`).
=> VZ-8243 backport: E2E test change VZ CR during install

tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/constants/constants.go
Looking at failed pipelines that included VZ bug-report cluster snapshots, I noticed that the cluster operator logs were missing. This PR adds them.
=> Add verrazzano-cluster-operator pod logs to VZ bug-report

Jenkinsfile, JenkinsfileCopyrightTest, ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests, ci/JenkinsfileTestTrigger, ci/backup/JenkinsfileAlllBackupOKETest, ci/chaos/Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger, ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileUpdateDuringInstall, ci/examples/Jenkinsfile, ci/generic/Jenkinsfile, ci/generic/Jenkinsfile-singletarget, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/olcne/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/test-examples/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallSuite, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, ci/upgrade/Jenkinsfile
This switches the release-1.4 jobs from using labels provisioned by the Jenkins OCI to using labels provisioned by the Jenkins Agent Operator.
=> Switch release 1.4 to use the JAO

platform-operator/controllers/verrazzano/reconcile/install.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/install_component_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component_test.go, platform-operator/controllers/verrazzano/reconcile/upgrade.go, platform-operator/controllers/verrazzano/reconcile/upgrade_component.go, platform-operator/controllers/verrazzano/reconcile/upgrade_test.go
This changes modifies the installSingleComponent state machine to allow component uninstall. It also combines the componentTrackerContexts into one type with unique fields for the install upgrade and uninstall. This PR is a iteration on https://github.com/verrazzano/verrazzano/pull/5315
=> VZ-8648 Allow component disable

platform-operator/thirdparty/charts/ingress-nginx/templates/controller-hpa.yaml, platform-operator/thirdparty/charts/ingress-nginx/templates/default-backend-hpa.yaml, platform-operator/thirdparty/charts/keycloak/templates/hpa.yaml
HorizontalPodAutoscaler for versions autoscaling/v2beta2 and autoscaling/v1beta1  is deprecated in v1.23+. Therefore this PR migrates the affected charts to autoscaling/v2 from k8s 1.23 version.
=> VZ-8784: Update HorizontalPodAutoscaler charts to support k8s 1.25

platform-operator/thirdparty/charts/cert-manager/templates/cainjector-psp-clusterrole.yaml, platform-operator/thirdparty/charts/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/cert-manager/templates/cainjector-psp.yaml, platform-operator/thirdparty/charts/cert-manager/templates/psp-clusterrole.yaml, platform-operator/thirdparty/charts/cert-manager/templates/psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/cert-manager/templates/psp.yaml, platform-operator/thirdparty/charts/cert-manager/templates/startupapicheck-psp-clusterrole.yaml, platform-operator/thirdparty/charts/cert-manager/templates/startupapicheck-psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/cert-manager/templates/startupapicheck-psp.yaml, platform-operator/thirdparty/charts/cert-manager/templates/webhook-psp-clusterrole.yaml, platform-operator/thirdparty/charts/cert-manager/templates/webhook-psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/cert-manager/templates/webhook-psp.yaml, platform-operator/thirdparty/charts/external-dns/templates/psp.yaml, platform-operator/thirdparty/charts/ingress-nginx/templates/controller-role.yaml, platform-operator/thirdparty/charts/ingress-nginx/templates/default-backend-role.yaml, platform-operator/thirdparty/charts/ingress-nginx/templates/default-backend-rolebinding.yaml, platform-operator/thirdparty/charts/jaegertracing/jaeger-operator/templates/psp.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/podsecuritypolicy.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/psp-clusterrole.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-adapter/templates/psp.yaml, platform-operator/thirdparty/charts/rancher-backup/templates/hardened.yaml, platform-operator/thirdparty/charts/rancher-backup/templates/psp.yaml
PodSecurityPolicy has been removed in k8s 1.25 version. Therefore updating the  affected helm charts to make sure podSecurityPolicy is not created during helm upgrade or installation on k8s 1.25
=> VZ-8618: Update helm charts to disable psp for k8s 1.25

platform-operator/thirdparty/charts/argo-cd/templates/argocd-application-controller/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/argocd-applicationset/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/argocd-notifications/bots/slack/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/argocd-notifications/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/argocd-repo-server/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/argocd-server/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/dex/pdb.yaml, platform-operator/thirdparty/charts/argo-cd/templates/redis/pdb.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/alertmanager/podDisruptionBudget.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/podDisruptionBudget.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/thanos-ruler/podDisruptionBudget.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-adapter/templates/pdb.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-pushgateway/templates/pdb.yaml
PodDisruptionBudget for the policy/v1beta1 API version is not supported in k8s v1.25. So the existing manifests should be migrated to policy/v1 API version. Therefore, this PR will use the appropriate API version based on the underlying k8s version. 
Source: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
=> VZ-8212: Update helm charts to enable k8s 1.25 support for PodDisruptionBudget

platform-operator/verrazzano-bom.json
VZ-8700, VZ-8701: Upgrade kiali and kube-state-metrics images
Cherry pick image updates from release-1.5 branch.
=> Upgrade kiali and kube-state-metrics images (#5441)

platform-operator/verrazzano-bom.json
This PR updates the following images
1. Keycloak image contains the change to upgrade Wildfly Elytron module
2. VMO, NGINX ingress and External DNS images include the change to update golang.org/x/net and golang.org/x/text
=> VZ-8518: Update Keycloak, VMO, NGINX ingress and External DNS images

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go
This PR includes the changes to the prometheus component files
> Conditionally check/update ingresses for prometheus based on NGINX enabled/disabled to make prometheus a-la-carte
=> VZ-8153: Making prometheus a-la-carte and remove dependency on NGINX and Authproxy

cluster-operator/controllers/vmc/vmc_controller.go
This would cycle with errors if managed cluster prometheus is disabled.
=> Only register prometheus keycloak client if set by managed cluster

cluster-operator/controllers/vmc/rancher.go
This is a follow up PR for https://github.com/verrazzano/verrazzano/pull/5433 to update Logging level from error to Info
> Changes to rancher.go file to log as Info when no existing CRT found
=> VZ-7954: Update logging level (#5491)

application-operator/Makefile, cluster-operator/Makefile, platform-operator/Makefile
At some point `make mock-gen` stopped working. Running it produces errors similar to this:
```
$ make mock-gen
mockgen -destination=mocks/component_mock.go -package=mocks -copyright_file=hack/boilerplate.go.txt github.com/verrazzano/verrazzano/platform-operator/controllers/verrazzano/component/spi ComponentContext,ComponentInfo,ComponentInstaller,ComponentUpgrader,Component
prog.go:12:2: cannot find package "github.com/verrazzano/verrazzano/vendor/github.com/golang/mock/mockgen/model" in:
/go/src/github.com/verrazzano/verrazzano/vendor/github.com/golang/mock/mockgen/model
prog.go:12:2: cannot find package "github.com/verrazzano/verrazzano/vendor/github.com/golang/mock/mockgen/model" in:
/go/src/github.com/verrazzano/verrazzano/vendor/github.com/golang/mock/mockgen/model
prog.go:12:2: no …
```
=> Fix mockgen commands in Makefiles

application-operator/Makefile, cluster-operator/Makefile, platform-operator/Makefile
Backport of fix to the mock-gen commands in the operator Makefiles on the release-1.5 branch.
See https://github.com/verrazzano/verrazzano/pull/5495 for details.
=> Fix mockgen commands (#5495) (release-1.5)

platform-operator/apis/verrazzano/validators/validate.go
Updates the webhook error on upgrade to be more user friendly.
=> VZ 8883: Upgrade webhook error

platform-operator/verrazzano-bom.json
The BFS pipeline for the release build of Thanos v0.28.0 is now functional. This PR replaces the image tag in the BOM with the official release build.
=> Use release build of thanos v0.28.0 in bom

platform-operator/constants/constants.go, platform-operator/controllers/verrazzano/component/common/ingress.go, platform-operator/controllers/verrazzano/component/common/ingress_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/controllers/verrazzano/vzinstance/verrazzano_instance_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/prometheus.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/values.yaml
- Adds an optional Thanos sidecar to the Prometheus
- Adds ingress to the installation of Prometheus if Thanos sidecar is enabled
- Updates helm overrides to allow default sidecar configuration
**Local testing:**
- Installed with and without the sidecar value set to make sure nothing was installed
- Installed with the sidecar value set and removed it to see if the sidecar became disabled
- Installed with the disabled value and changed it to the sidecar to see if the sidecar got added
=> VZ-8711 Add sidecar implementation to the Prometheus instance

ci/JenkinsfileTestTrigger, ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go
Backport the below fix for release-1.5:
Whenever a new commit is merged, an upgrade job is triggered with the latest release version for master. The latest release version remains constant irrespective of the branch.
Ex: For release-1.4, the latest release should be 1.3.8. However, it still populates 1.5.1.
This PR retrieves the latest release based on the development version of the current branch to resolve the above issue.
=> VZ-8879: Fix upgrade path job with appropriate latest version based on the current branch

ci/dynamic-updates/JenkinsfileUpdateDuringInstall, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/install_test.go
Changes:
- This PR removes the `sleep` command in ci/dynamic-updates/JenkinsfileUpdateDuringInstall.
- The bug described in VZ-8748 is fixed by adding code in `installSingleComponent` in install_component.go.
- A unit test is added in install_test.go.
Before these changes, the `installSingleComponent` function did not check for config changes once the component was already in state `compStateInstallEnd`. The bug fix adds this check and restarts the component to pre-install if appropriate.
=> VZ-8748: Check for Config Changes in compStateInstallEnd State

cluster-operator/controllers/vmc/jaeger.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
Fixes override namespace used with Jaeger.
=> VZ 8850: Use override namespace

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests
When FORCE parameter is enabled, do not mark the build as failed when the up-to-date failed condition is true.
=> VZ-8764: Use URL trigger to control the periodic and backend pipeline triggers

tools/vz/cmd/bugreport/bugreport_test.go
This PR disables an assertion in a unit test for bug-report. The assertion will be enabled once the intermittent failure is addressed.
=> Disable an assertion in bug-report unit test, which fails intermittently

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, tests/e2e/config/scripts/wait-for-verrazzano-install.sh
Rancher uninstall was getting conflict errors when removing finalizers from clusterroles, but the errors were being ignored so the clusterroles were not getting deleted.  Change the code to bubble the error up the stack so reconcile is called again.  Also add more logging/
Change the install timeout to 45 min for OCI DNS.  The install was taking 33-34 min because of Let's Encrypt being slow and the tests failed.
=> VZ-8357 handle Rancher unistall update conflict

platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/install_test.go
https://github.com/verrazzano/verrazzano/pull/5514 had a few uncaught things related to code cleanliness that could be fixed.
There is a debugging print statement in a unit test that should not be there, and an unused parameter in the `restartComponentInstallFromEndState` function.
=> VZ-8748: Cleanup code for config change checks in compStateInstallEnd state

ci/uninstall/Jenkinsfile, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, tests/e2e/config/scripts/wait-for-verrazzano-install.sh
This is a cherry-pick of https://github.com/verrazzano/verrazzano/commit/a02ed14dcbc6d741f1af5085ce32765c9214632e
Rancher uninstall was getting conflict errors when removing finalizers from clusterroles, but the errors were being ignored so the clusterroles were not getting deleted. Change the code to bubble the error up the stack so reconcile is called again. Also add more logging/
Change the install timeout to 45 min for OCI DNS.  The install was taking 33-34 min because of Let's Encrypt being slow and the tests failed.  Do the same for the install phase of uninstall pipeline.
=> VZ-8357 handle Rancher unistall update conflict 

ci/dynamic-updates/JenkinsfileUpdateDuringInstall
(Partial) backport of https://github.com/verrazzano/verrazzano/pull/5514.
Removes the `sleep` command in the "Verify Install" stage of ci/dynamic-updates/JenkinsfileUpdateDuringInstall.
=> VZ-8748: Remove sleep from dynamic-config-install tests

platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/apis/verrazzano/v1beta1/validate.go
Changes to validate.go files for v1alpha and v1beta1 because, the copyright checker detects changes to this files which is causing the failure
=> Follow up PR for revert PR to update copyright year

tools/vz/Makefile
* Added help for all make targets
```
Usage:
make <target>
help                       Display this help.
go-build                   build the CLI for multiple architecture and platforms
build-cli                  build the CLI for current system and architecture
cli                        install the CLI
```
* Also added a new target `build-cli` that creates a binary in localpath
=> VZ-8981: Add new make file targets for vz cli

platform-operator/helm_config/overrides/prometheus-operator-values.yaml, platform-operator/helm_config/overrides/thanos-values.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/prometheus.yaml
Out of the box, the Thanos components include some pod and container security context settings. This PR adds more settings to make the pods and containers more secure, and makes the security configuration consistent with other Verrazzano components.
To verify the changes, I ran the pod security e2e test which reports missing security context on pods and containers on a cluster with Thanos installed (including the Prometheus sidecar). After these changes, the test passes. I also ran an internal diagnostic tool against the verrazzano-monitoring namespace, and it reported no issues.
I ran one additional validation by labeling the verrazzano-monitoring namespace with `"pod-security.kubernetes.io/enforce"=restricted`. That also reported no issues.
=> Additional pod and container security context settings for Thanos components

platform-operator/apis/verrazzano/v1alpha1/validate.go, platform-operator/apis/verrazzano/v1beta1/validate.go
Changes to update the log message to include none keyword when user provides invalid entry for profile name
> Changes to v1alpha/validate.go
> Changes to v1beta1/validate.go
=> log message fix to include none keyword

platform-operator/controllers/verrazzano/component/registry/registry.go, platform-operator/controllers/verrazzano/reconcile/install_component.go
Backporting vz-8921 VPO logs when dependency already met
=> Backport vz-8921 vpo logs when dependency already met (#5591)

tests/e2e/multicluster/verify-jaeger/hotrod/jaeger_hotrod_mc_test.go
The MC test failed because the Jaeger pod wasn't ready after 5 minutes, it was ready around 6 minutes after the OAM app was created.  Extend the timeout from 5 min to 10 min so that this doesn't fail, the failure has happened a few times.
=> MC test, extend Jaeger pod wait timeout

examples/ha/ha-oci-ccm.yaml, pkg/yaml/expand.go, pkg/yaml/replace_merge_test.go, platform-operator/apis/verrazzano/testdata/fromistioaffinityargs/v1alpha1.yaml, platform-operator/apis/verrazzano/testdata/fromistioaffinityargs/v1beta1.yaml, platform-operator/controllers/verrazzano/component/spi/component_context_permutations_test.go, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, tests/e2e/config/scripts/create_oke_cluster.sh, tests/e2e/config/scripts/create_oke_multi_cluster.sh, tests/e2e/update/nginxistio/nginxistio_test.go, tools/vz/cmd/install/install_test.go, tools/vz/pkg/analysis/test/cluster/ingress-lb-limit/cluster-snapshot/ingress-nginx/services.json, tools/vz/pkg/analysis/test/cluster/problem-pods-install/cluster-snapshot/ingress-nginx/services.json, tools/vz/pkg/analysis/test/cluster/problem-pods-install/cluster-snapshot/verrazzano-resources.json
This PR changes the annotations on all Verrazzano services currently using fixed-shape LBs to use the flexible shape instead. This is due to OCI deprecating fixed-shape LBs in May 2023.
=> Backport VZ-7460 Move to Flexible Load Balancer Usages

application-operator/controllers/ingresstrait/ingresstrait_controller.go, application-operator/controllers/ingresstrait/ingresstrait_controller_test.go
Fix a problem where every host from the IngressTrait was being added to every VirtualService.  There should be a VirtualService for every IngressTrait rule, and the VS hosts should only have the hosts that are in the rule.
=> VZ-8999 correctly configure Gateway and VirtuaService for multiple IngressTraits and multiple hosts

tests/e2e/pkg/kubernetes.go
The  tests logs have many "Failed to get .." errors when a resource is not found, which is a normal response during the life cycle of tests.  This is very confusing in the logs since it distracts from real problems.  This PR removes that logging.
=> VZ-9062 testing - don't log "Failed to get .." errors when resouce not found

ci/JenkinsfilePeriodicTests, ci/scripts/build_distribution.sh
This PR renames an outdated helper script to reflect what it is doing more accurately. `build-distribution.sh` calls `generate_vz_distribution.sh`, which subsequently builds and pushes the full release distribution to object store.
=> VZ-6947 Periodic pipeline updates Pt. 1

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/templates/networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano/templates/authorizationpolicy.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml, platform-operator/verrazzano-bom.json, tests/e2e/verify-install/verrazzano/verrazzano_test.go
This PR uptakes the latest NGINX ingress controller image that supports gRPC ingresses. It also modifies the AuthProxy configuration as follows:
1. Change the Lua code that creates backend monitoring endpoints to accept a protocol. "grpc" is passed for gRPC backends.
2. Add a server entry that listens on a new port and proxies gRPC traffic.
There are also associated changes to the AuthProxy deployment, service, network, and auth policies for the new port.
This PR also uptakes the latest Thanos image that supports basic auth.
I tested this by installing in a local cluster, and modifying the Thanos Query config to talk to the sidecar through the ingress controller. I verified that all gRPC traffic is being proxied correctly.
=> VZ-8973: Support gRPC traffic through NGINX ingress and AuthProxy

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, pkg/constants/constants.go, platform-operator/constants/constants.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component_test.go, platform-operator/controllers/verrazzano/vzinstance/verrazzano_instance.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
=> VZ-8713 - subtask VZ-8984 - Add thanosHost to VMC status and populate it from managed cluster (from query store API ingress) 

ci/kind/Jenkinsfile
This pull request moves the "logging trait Helidon workload' test from the 3rd parallel stage to the 2nd parallel stage.  This is a workaround for intermittent failure of this test.
=> Move "logging trait Helidon workload" test to different stage

CHANGES.md, platform-operator/helm_config/overrides/cert-manager-values.yaml, platform-operator/thirdparty/charts/cert-manager/values.yaml
In cert-manager 1.9.1, `startupapicheck` job is enabled by default and pulls an image quay.io/jetstack/cert-manager-ctl:v1.9.1 which we don't distribute and hence will cause issues in air-gapped installs. This PR to disable this job till we start distributing the image.
=> VZ-9096: Disable startupapicheck in cert-manager

platform-operator/constants/constants.go, platform-operator/controllers/configmaps/components/controller.go, platform-operator/controllers/configmaps/components/controller_test.go, platform-operator/controllers/configmaps/components/dev_helm_component.go
This change adds upgrade and uninstall lifecycle operations for the dev component controller. It also adds a finalizer to the configmap that is cleaned up during uninstall.
=> VZ-7916 Add Upgrade and Uninstall for dev component controller

tests/e2e/multicluster/multicluster_helper.go, tests/e2e/update/certac/certac_test.go, tests/e2e/update/certmc/certmc_test.go
The cert manager test suites for admin and managed clusters fail intermittently at different places. This is for the initial set of fixes and log troubleshooting information when Verrazzano custom resource (CR) is not ready.
I will be keeping the ticket open even after the PR is merged to monitor these intermittent failing tests.
=> VZ-9085: TestFailure: verify-cert-manager-update

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
This reintroduces the fix from https://github.com/verrazzano/verrazzano/pull/5627 into the `anders/rancher-master` branch.
=> Reintroduce "Skip OCI Node driver activation aamitra/rancher phase1" to rancher-master

platform-operator/verrazzano-bom.json, tests/testdata/jaeger/hotrod/hotrod-tracing-comp.yaml, tests/testdata/jaeger/hotrod/multicluster/hotrod-tracing-comp.yaml
Refreshes component images, after updating golang.org/x/net and golang.org/x/text
=> Refresh component images in release-1.5, after updating golang.org/x/net and golang.org/x/text

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go, platform-operator/helm_config/overrides/thanos-values.yaml, platform-operator/thirdparty/charts/thanos/templates/verrazzano/usersecret.yaml, platform-operator/verrazzano-bom.json
**Changes**:
1. Add a secret to the Thanos Helm chart that generates a password for the verrazzano-thanos-internal user.
2. Create a Keycloak user for verrazzano-thanos-internal.
3. Mount the secret in the Thanos Query container as environment variables.
**Tests**:
1. Installed in a local cluster with Thanos enabled, verified that the secret and Keycloak user are created, and that the Thanos Query container has the secret env vars set, tested through the ingress to verify that basic auth works.
2. Upgrade the installation to validate that the existing verrazzano-thanos-internal password in the secret is not changed.
3. Installed in a local cluster with Thanos disabled, verified that the Keycloak user is not created.
=> VZ-9108: Configure basic auth in Thanos Query

pkg/vzcr/enabled.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go
Fixes a bug in the `MonitorChanges` override in a subset of the Prometheus components that is preventing them from being disabled by removing them from the CR when a `none` profile is deployed.
This affects:
* prometheusAdapter
* kubeStateMetrics
* prometheusPushgateway
* prometheusNodeExporter
If you enable these after deploying a `none` profile:
```
  profile: none
  components:
    kubeStateMetrics:
      enabled: true
    prometheus:
      enabled: true
    prometheusOperator:
      enabled: true
    prometheusAdapter:
      enabled: true
    prometheusNodeExporter:
      enabled: true
    prometheusPushgateway:
      enabled: true
```
and the disable them by removing them from the CR:
```
 profile: none
  components:
    prometheus:
      enabled: true
    prometheusOperator:
      …
```
=> VZ-9137.  Fix MonitorChanges checks in some of the prometheus stack components

tools/vz/cmd/bugreport/bugreport.go, tools/vz/pkg/constants/constants.go
- bug report temp file generations on default cases to avoid report generation failure if report file already exists
- bug report generation on every run
- bug report file naming format changes to vz-bug-report-datetime-XXXX.tar.gz where datetime = yyyymmddhhmmss
=> VZ-8861 bug report changes

ci/a-la-carte/Jenkinsfile
This PR have the changes to alacarte Jenkins file to add support for cluster dump on failure
=> VZ-7915: Follow up PR to update a-la-carte pipeline

ci/a-la-carte/Jenkinsfile, tests/e2e/config/scripts/wait-for-verrazzano-install.sh
Adds the `verify-infra/vmi` tests to the post-app-stack install stage for the a-la-carte pipeline.
This also modifies the `wait-for-verrazzano-install.sh` script to check the VZ CR state before checking install condition.  The ability to to do a 
```
kubectl wait --for=condition
```
seems to be broken.  I will open a bug for that behavior, but this tweak should allow the test pipeline to behave as expected.
=> VZ-9172.  Add VMI tests to a-la-carte pipeline

platform-operator/helm_config/overrides/thanos-values.yaml
This also makes the sidecar endpoint consistent with the Store Gateway endpoint (using DNS discovery).
=> Use DNS discovery for Thanos sidecar endpoint

platform-operator/constants/constants.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/controller_test.go
(Adds watch for Thanos internal user secret, and re-reconcile Keycloak so that it picks up that user if Thanos is enabled post VZ install)
=> VZ-9103 Fix issue where managed cluster connection from Thanos query fails when Thanos is enabled after VZ install

platform-operator/controllers/verrazzano/component/thanos/thanos_test.go, platform-operator/verrazzano-bom.json
I tested this new Thanos image in a local cluster and it seems to behave as expected.
I also fixed the unit test to remove the hardcoded version in the override check so we don't have to update the unit test whenever the image version changes.
=> VZ-8943: Uptake Thanos v0.30.2

platform-operator/Dockerfile
Updated the rpm to istio-istioctl-1.15.3-2.el8.  Scan results indicate the Helm CVEs associated with v.3.9.2 are resolved.
=> JIRA: VZ-8334 update istioctl rpm to version with Helm CVE fix (update to v3.10.3)

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
This change installs latest version of Trivy and Grype scanner for daily scan job, and sets the installed directory ahead of everything in the PATH.
=> VZ-9109: Install latest version of Trivy and Grype scanner for daily scan job

application-operator/mcagent/mcagent.go, cluster-operator/controllers/vmc/argocd.go, cluster-operator/controllers/vmc/argocd_test.go, cluster-operator/controllers/vmc/push_manifest_objects.go, cluster-operator/controllers/vmc/sync_manifest_secret.go, cluster-operator/controllers/vmc/sync_prometheus.go, cluster-operator/controllers/vmc/sync_thanos.go, cluster-operator/controllers/vmc/sync_thanos_test.go, cluster-operator/controllers/vmc/vmc_controller.go, cluster-operator/controllers/vmc/vmc_controller_test.go, cluster-operator/internal/operatorinit/run_operator.go, cluster-operator/main.go, pkg/constants/constants.go, pkg/rancherutil/rancher_config.go, pkg/rancherutil/rancher_config_test.go, platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
**Changes**
- Add a cluster label to the managed cluster store targets for selection
- Change the update and create process to factor in labels
- Add an ingress host flag to override the Rancher API calls for running in IDE
- Update and add unit tests to test new update and delete process
**Testing**
- Run a multicluster setup in kind
- Turn on and off the Thanos component on the managed cluster
- Turn on and off the Thanos component on the admin cluster
- Make sure that the Thanos query store configmap gets modified correctly
- Make sure that the Prometheus additional configs get modified correctly
- Deregister and make sure both Thanos and Prometheus targets get cleaned up
=> VZ-8892 Update the Thanos VMC sync to remove Prometheus federation

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
This change installs latest version of Trivy and Grype scanner for daily scan job for release-1.3, and sets the installed directory ahead of everything in the PATH.
=> VZ-9109: Install latest version of Trivy and Grype scanner for daily scan job in release-1.3

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
This change installs latest version of Trivy and Grype scanner for daily scan job for release-1.4, and sets the installed directory ahead of everything in the PATH.
=> VZ-9109: Install latest version of Trivy and Grype scanner for daily scan job in release-1.4

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
This change installs latest version of Trivy and Grype scanner for daily scan job for release-1.5, and sets the installed directory ahead of everything in the PATH.
=> VZ-9109: Install latest version of Trivy and Grype scanner for daily scan job in release-1.5

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go, platform-operator/thirdparty/charts/rancher/templates/deployment.yaml
This pull request moves the patching of the MKNOD capability for the Rancher deployment from Go code to the Rancher helm chart.  With this change, the Rancher pods don't restart when patching the Rancher deployment.
=> Move patching of adding MKNOD capabilty to the Rancher helm chart

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/verrazzano-bom.json
This pull request removes the activation of the Rancher oci driver and updates Rancher images in the BOM.
Installation testing verified that install was no longer failing with:
```
Failed getting OCI Driver: nodedrivers.management.cattle.io \"oci\" not found
```
=> VZ-9081: Remove activate of odi driver and update rancher image

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
This PR sets the latest Grype and Trivy to PATH, ahead of all other entries, so that the daily scan always uses the latest version of these scanners.
=> Fix the issue with PATH variable in daily scanning job, release-1.3

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
This PR sets the latest Grype and Trivy to PATH, ahead of all other entries, so that the daily scan always uses the latest version of these scanners.
=> VZ-9109: Fix the issue with PATH variable in daily scanning job

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
This PR sets the latest Grype and Trivy to PATH, ahead of all other entries, so that the daily scan always uses the latest version of these scanners.
=> VZ-9109: Fix the issue with PATH variable in daily scanning job, release-1.5

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
This PR sets the latest Grype and Trivy to PATH, ahead of all other entries, so that the daily scan always uses the latest version of these scanners.
=> VZ-9109: Fix the issue with PATH variable in daily scanning job, release-1.4

tools/scripts/k8s-dump-cluster.sh
There was a typo error when creating the cluster snapshot using the k8-dump-cluster.sh because of a syntax issue.
This will fix the syntax issue.
=> Update k8s-dump-cluster.sh to handle the syntax issue while capturing the dump in CI pipeline.

platform-operator/controllers/verrazzano/component/common/vmi.go, platform-operator/controllers/verrazzano/component/grafana/grafana.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component_test.go, platform-operator/controllers/verrazzano/component/grafana/grafana_test.go, platform-operator/controllers/verrazzano/component/grafana/vmi.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component.go, platform-operator/thirdparty/charts/thanos/templates/verrazzano/authorizationpolicy.yaml, platform-operator/thirdparty/charts/thanos/templates/verrazzano/networkpolicy.yaml, platform-operator/thirdparty/manifests/grafana/datasources-configmap.yaml
This PR adds Thanos to the list of configured datasources in Grafana. If Thanos Query Frontend is enabled, Thanos is added to the Grafana datasources list and Thanos is set as the default datasource. Dashboards will then fetch metrics from Thanos. If Thanos Query Frontend is not enabled but Prometheus is enabled, Prometheus will be the only configured datasource.
To test, I installed in a local cluster with the following configurations and validated the datasources in Grafana:
- Thanos component enabled, Thanos Query Frontend enabled, Prometheus enabled
- Thanos component enabled, Thanos Query Frontend disabled, Prometheus enabled
- Thanos disabled, Prometheus enabled
- Thanos disabled, Prometheus disabled
I ran the same scenarios but upgrading from Verrazzano 1.5.2 and confirmed the …
=> VZ-8840: Grafana datasource support for Thanos

ci/JenkinsfileBackendTests
This PR addes the cron schedule to the backend tests to trigger the job every Friday. The job will not be validated against last stable commit.
=> Add a cron schedule to run backend tests every Friday 

platform-operator/verrazzano-bom.json
This PR updates latest rancher and rancher-agent images which has the follow change:
- Replaces rancher charts upstream repo with the Verrazzano rancher charts BFS repo.
=> VZ-8964: Uptake latest rancher 2.7.1 bfs images

platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
Added missing pattern for jaeger-operator.
Example:  fluentd parsing error 
`
2023-04-03 19:02:03 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data '1.6805485233680496e+09\tINFO\tdetecting orphaned deployments.'" location=nil tag="kubernetes.var.log.containers.jaeger-operator-548956957-7pdb6_verrazzano-monitoring_jaeger-operator-d086bdeffc49bc12106b08060909a02a89a8ec56b086b244ab7c8c37a4f60607.log" time=2023-04-03 19:02:03.734614128 +0000 record={"stream"=>"stderr", "flags"=>"F", "log"=>"1.6805485233680496e+09\tINFO\tdetecting orphaned deployments.", "docker"=>{"container_id"=>"d086bdeffc49bc12106b08060909a02a89a8ec56b086b244ab7c8c37a4f60607"}, "kubernetes"=>{"container_name"=>"jaeger-operator", …
=> VZ-9232: Fix Jaeger configuration in Fluentd

pkg/k8sutil/apply_yaml.go, pkg/k8sutil/apply_yaml_test.go, pkg/kubectlutil/kubectl_util.go, pkg/kubectlutil/kubectlutil_test.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/test/helpers/kubectl.go
Set the kubectl.kubernetes.io/last-applied-configuration annotation when doing install or upgrade using vz cli for correct merge calculation of Kubernetes resources.
This will allow us to use any combination of install & upgrade using either kubectl or vz cli.
=> VZ-8551: VPO status Init:CrashLoopBackOff after applying operator.yaml

platform-operator/verrazzano-bom.json
Refreshes the Keycloak 20.0.1 image built with SnakeYAML v2.0 in https://github.com/verrazzano/keycloak/pull/10
=> VZ-9275: Update Keycloak image with SnakeYAML upgraded to v2.0, release-1.5

platform-operator/verrazzano-bom.json
Refreshes the Keycloak 20.0.1 image built with SnakeYAML v2.0 in https://github.com/verrazzano/keycloak/pull/10
=> VZ-9275: Update Keycloak image with SnakeYAML upgraded to v2.0

platform-operator/verrazzano-bom.json
Update VMO image to add annotations proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' to OS/OSD pods.
This annotation adds hooks to delay application startup until the pod proxy is ready to accept traffic, mitigating some startup race conditions
=> VZ-9210: Update VMO image

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano Monitoring/thanos_overview.json
I'm putting this new dashboard in the existing "Verrazzano Monitoring" Grafana folder. That folder contains all of the kube-prometheus-stack dashboards, including a Prometheus dashboard, so it seemed like the best place to put this Thanos dashboard.
I tested by installing in a local cluster and loading the dashboard. Note that the Thanos ServiceMonitors are not yet enabled, so this dashboard shows no data. Once the monitors are enabled I may need to tweak the dashboard based on testing with actual Thanos metrics.
=> VZ-9248: Add Grafana dashboard for Thanos

platform-operator/verrazzano-bom.json
Added annotations proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' to OS/OSD pods.
This annotation adds hooks to delay application startup until the pod proxy is ready to accept traffic, mitigating some startup race conditions
=> VZ-9210: Backport PR update vmo image to fix the bug by adding annotation to OS/OSD pods to add hooks to delay application startup to release 1.5

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_test.go, cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, cluster-operator/controllers/vmc/sync_thanos.go, cluster-operator/controllers/vmc/sync_thanos_test.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
Per API Review, updating the Thanos Query Store field in the VMC status.
I tested locally in a multicluster environment and verified that the Thanos host gets set in the VMC status and that the endpoint shows as healthy in the Thanos Query store list on the admin cluster.
Example VMC status snippet:
```
Prometheus Host:          prometheus.vmi.system.default...
Rancher Registration:
Cluster ID:        c-cqb45
Message:           Registration of managed cluster completed successfully for cluster managed1 with ID c-cqb45
Status:            Completed
State:               Active
Thanos Query Store:  query-store.default...
```
=> Rename Thanos Query Store host field in VMC status

application-operator/mcagent/mcagent_test.go, pkg/constants/constants.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/thanos/thanos.go, platform-operator/controllers/verrazzano/component/thanos/thanos_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml, platform-operator/helm_config/overrides/thanos-values.yaml, platform-operator/thirdparty/charts/thanos/templates/query/ingress-grpc.yaml, tests/e2e/pkg/metrics.go, tests/e2e/scripts/install/install_test.go, tests/e2e/verify-install/thanos/thanos_test.go
This is an alteration to the Thanos Query store Ingress name
**Testing**
Install multicluster verrazzano and verify that the ingress is updated and the managed cluster is scraped from the new ingress name.
=> Update the Thanos Query Store Ingress name

platform-operator/verrazzano-bom.json
Refreshes the Keycloak 15.0.2 image built with SnakeYAML v2.0 in https://github.com/verrazzano/keycloak/pull/11
=> VZ-9292: Update Keycloak image with SnakeYAML upgraded to v2.0 in release-1.4

platform-operator/verrazzano-bom.json
Refreshes the Keycloak 15.0.2 image built with SnakeYAML v2.0 in https://github.com/verrazzano/keycloak/pull/11
=> VZ-9292: Update Keycloak image with SnakeYAML upgraded to v2.0 in release-1.3

ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, tests/e2e/config/scripts/configure_thanos_storegateway_install.sh, tests/e2e/verify-install/thanos/thanos_test.go
This PR adds an end-to-end test for the Thanos Store Gateway to the Kind acceptance tests. If an environment variable to enable the test is set, the script creates a secret with the Thanos storage provider configuration and updates the VZ CR to enable the Store Gateway and point to the config secret. I enabled the flag in the main Kind AT pipeline.
I tested by running the test against a cluster with and without the Thanos Store Gateway enabled and confirmed that it checked for the running Store Gateway pod as needed.
Note that if the Store Gateway cannot mount the secret or if the secret contents don't pass minimal validation, the Store Gateway pod will go into CrashLoopBackoff and the test will fail, so the check for running (and ready) Store Gateway pod seems sufficient.
=> VZ-9280: E2E test for Thanos Store Gateway

platform-operator/controllers/verrazzano/component/thanos/thanos_component.go, platform-operator/thirdparty/charts/thanos/templates/alert-rule/absent_rules.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/compaction.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/query.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/receive.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/replicate.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/ruler.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/sidecar.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/store_gateway.yml, platform-operator/thirdparty/charts/thanos/templates/bucketweb/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/compactor/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/prometheusrule.yaml, platform-operator/thirdparty/charts/thanos/templates/query-frontend/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/query/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/receive-distributor/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/receive/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/ruler/servicemonitor.yaml, platform-operator/thirdparty/charts/thanos/templates/storegateway/servicemonitor.yaml
This PR adds a capabilities check for the monitoring CRD so that the Thanos install or call to get computed Helm values from the Thanos component do not fail if the CRD does not exist in the cluster. This avoids errors in the VPO log during install time. As long as the Prometheus Operator is enabled the errors are benign and would eventually resolve, but this cleans things up so the error condition is avoided.
I also added a dependency to the Thanos component on the Prometheus Operator component so that, if the Prometheus Operator is enabled, it will be installed first and thus install the monitoring CRD.
=> Add CRD capability check to Thanos ServiceMonitor and PrometheusRule Helm templates

tests/e2e/verify-infra/vmi/vmi_test.go
Adds a test to ensure that the proper datasource is enabled in Grafana using the API.
=> VZ-9282 Check for Grafana datasource in VMI test

tests/e2e/examples/bobsbooks/bobs_books_test.go, tests/e2e/examples/helidon/helidon_example_test.go, tests/e2e/examples/helidonconfig/helidon_config_test.go, tests/e2e/examples/helidonmetrics/helidon_metrics_test.go, tests/e2e/examples/socks/sock_shop_example_test.go, tests/e2e/examples/springboot/springboot_test.go, tests/e2e/examples/todo/todo_list_test.go, tests/e2e/jaeger/system/jaeger_system_test.go, tests/e2e/jwt/helidon-svc/helidon_example_test.go, tests/e2e/jwt/helidon/helidon_example_test.go, tests/e2e/metrics/deploymetrics/deploymetrics_test.go, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/multicluster/examples/helidon-deprecated/helidon_example_test.go, tests/e2e/multicluster/examples/helidon/helidon_example_test.go, tests/e2e/multicluster/examples/sock-shop/sock_shop_example_test.go, tests/e2e/multicluster/examples/todo-list/todo_list_example_test.go, tests/e2e/multicluster/verify-jaeger/system/jaeger_system_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/multicluster/workloads/mccoherence/coherence_workload_mc_test.go, tests/e2e/multicluster/workloads/mcweblogic/weblogic_workload_mc_test.go, tests/e2e/pkg/metrics.go, tests/e2e/update/certmc/certmc_test.go, tests/e2e/update/dnsmc/dnsmc_test.go, tests/e2e/update/jaeger/jaeger_update_test.go, tests/e2e/workloads/coherence/coherence_workload_test.go, tests/e2e/workloads/weblogic-cluster/weblogic_workload_test.go, tests/e2e/workloads/weblogic/weblogic_workload_test.go, tools/psr/tests/scenarios/opensearch/s1/opensearch_s1_test.go, tools/psr/tests/scenarios/opensearch/s2/opensearch_s2_test.go
Update to a function call. This prevents the annoyance of adding the metrics kubeconfig to the kubeconfig list and makes the default a lot simpler. It also extends the list to add as many extra kubeconfigs as needed.
=> Update metrics test function to accept extra kubeconfigs

platform-operator/helm_config/overrides/thanos-values.yaml
Causes deduplication in Thanos based on the verrazzano_cluster label. 
**Testing**
Install multicluster Thanos and make sure that deduplication acts on the verrazzano_cluster label on the admin cluster.
=> Add the replica label for deduplication in Thanos

platform-operator/thirdparty/charts/thanos/templates/verrazzano/authorizationpolicy.yaml
This makes the Authorization Policies specifically select the correct pods for Thanos. These values are derived from the helm chart and are hard coded into the deployments.
**Testing**
Deploy Thanos and expect that the authorization policies allow traffic from all sources to the correct pods.
=> Make the Thanos authorization policies more specific

ci/upgrade-paths/Jenkinsfile, tests/e2e/upgrade/pre-upgrade/verify-upgrade-required/verify_upgrade_required_test.go
Attempt to resolve a timing issue in the upgrade-paths tests in the `verify-upgrade-required` stage
- Add a `rollout-status` check on the webhook deployment
- Wrap the code to get the VZ instance in an `Eventually` assertion
=> No Bug.  Make verify-upgrade-required tests more resilient

ci/a-la-carte/Jenkinsfile, tests/e2e/update/a-la-carte/a_la_carte_suite_test.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
This change updates the a la carte pipeline to use ginkgo to perform updates instead of the Jenkinsfile. It also adds the cluster management stage.
=> VZ-7914: a la carte pipeline updates with ginkgo

CHANGES.md, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go
This change adds the Prometheus a la carte CHANGES.md entry, and also fixes a bug in the postuninstall hook that deletes the legacy ingress
=> Prometheus a la carte doc changes and postuninstall bug fix

pkg/helm/helmcli.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go
Fix the `helmcli.Upgrade()` to honor the `wait` parameter using the newly-incorporated Helm API.
- use `wait=false` for `HelmComponent.Upgrade()`, as using `wait=true` causes upgrade timeouts
- Existing component ready checks should ensure when components are finished upgrading
Previous releases used `wait=true` for upgrades, but it seems like the new API will cause timeouts.  It also seems that we've been running with `wait=false` since use of the Helm API was introduced, so it should be safe.
=> Honor wait parameter to helmcli.Upgrade()

tests/e2e/config/scripts/configure_thanos_storegateway_install.sh
The e2e security tests failed in the dev LRE environment because the LRE has long-term storage enabled on the Prometheus Thanos Sidecar. The test for long-term storage only enabled storage on the Store Gateway, which is why we didn't catch the LRE issue in our e2e testing.
This PR enables storage on the Thanos Sidecar so we catch any future problems related to Sidecar storage.
=> Enable storage on Prometheus Thanos Sidecar when enabling Store Gateway for testing

platform-operator/capi/.cluster-api/clusterctl.yaml, platform-operator/controllers/verrazzano/component/capi/capi_component.go
This pull request includes the following changes to the experimental CAPI component:
1. Include image overrides for the oci infra provider and core provider
2. Use provider default namespaces
3. Don't install the kubeadm providers by default
=> VZ-9371: CAPI experimental component updates

tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/upgrade/upgrade_test.go
Example cases that should not automatically run analyze or bug report 
- Invoking vz uninstall when vz is not installed 
- Invoking vz install, uninstall, upgrade with incorrect CLI arguments 
- Invoking vz install with multiple versions 
- Invoking vz install when an install has already started 
Example cases that SHOULD automatically run analyze or bug report 
- timeout after waiting for install, uninstall, upgrade to complete 
- timeout after waiting for platform operator 
- failing to create the vz install resource
=> VZ-9366 VZ CLI should not automatically call bug report and analyze upon certain failures 

platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go
In versions 1.5.x and prior, we did not support disabling an already enabled component in the VZ CR. These four Prometheus components did not have validators that would immediately error on updating the VZ CR:
- Push Gateway
- Adapter
- Node Exporter
- Kube State Metrics
As a result, the VPO would go through an entire reconcile and the net result is a no-op. This PR adds validators so that we fail the VZ CR update and notify the user.
I performed a local test by applying a VZ CR that had the four components enabled, waited for the install to complete, then attempted to disable the four components. As expected the update failed immediately with the following message:
```
Error from server ([Disabling component prometheusAdapter is not allowed, Disabling component kubeStateMetrics is not …
```
=> VZ-8749: Add update validators for Prometheus components

platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component.go, platform-operator/controllers/verrazzano/component/prometheus/adapter/promadapter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component.go, platform-operator/controllers/verrazzano/component/prometheus/kubestatemetrics/kubestatemetrics_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go
Cherry pick of release-1.5 fix to add update validators to the Prometheus components.
See https://github.com/verrazzano/verrazzano/pull/5840 for details.
=> VZ-8749: Add update validators for Prometheus components (release-1.4)

platform-operator/controllers/verrazzano/component/capi/capi.go
Enabling experimental CAPI features at bootup
https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html
=> VZ-9476: enable experimental capi features

platform-operator/verrazzano-bom.json
updated OSD image to upgrade Node version in OSD 2.3 to version 14.21.1.
=> Karak/vz 8694 fix CVE in osd release 1.5(Backport to 1.5)

platform-operator/verrazzano-bom.json
updated OSD image to upgrade Node version in OSD 2.3 to version 14.21.1.
=> VZ-8694: fix CVE in OSD 2.3 by upgrading Node version

platform-operator/verrazzano-bom.json
This change updates Keycloak 15.0.2 image built with the change https://github.com/verrazzano/keycloak/pull/12
=> VZ-8718: Update Keycloak 15.0.2 image with Apache CXF runtime WS security and STS core v3.4.10

platform-operator/verrazzano-bom.json
This change updates Keycloak 15.0.2 image built with the change https://github.com/verrazzano/keycloak/pull/12
=> VZ-8718: Update Keycloak 15.0.2 image with Apache CXF runtime WS security and STS core v3.4.10, in release-1.4

platform-operator/verrazzano-bom.json
bump node version to 14.21.3 in OSD 2.3 to fix CVE
=> VZ-9458: bump node version to 14.21.3 (backport to 1.5)

platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/values.yaml
To add seLinuxOptions to get it overridden in case selinux is enforcing.
There will be no values passed to it by default. But customer can override these if they want to provide seLinuxOptions in case seLinux is enforcing.
=> VZ-9434: add seLinuxOptions in Fluentd Daemonset

platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/values.yaml
To add seLinuxOptions to get it overridden in case selinux is enforcing.  
There will be no values passed to it by default. But customer can override these if they want to provide seLinuxOptions in case seLinux is enforcing.
=> VZ-9434: BackPort: Add seLinuxOptions in Fluentd Daemonset Helm chart (#5875)

platform-operator/verrazzano-bom.json
This PR updates VZ release-1.5 with new version of additional rancher images such as rancher-kubectl, backup and restore operator, fleet, and fleet-agent.
=> VZ-9306: PR to update new version of additional rancher images for VZ release-1.5

tests/e2e/verify-distribution/verifydistribution/verify_distribution_test.go
Use Gomega matchers to improve the output of the `verify-distribution` tests.
=> Improve output of verify-distribution tests

platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/nginx/nginx_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
Revert this PR and investigate MC and uninstall failures.
=> Revert: VZ-5060 add streaming directives to nginx configuration to address websocket errors in Rancher console

platform-operator/controllers/verrazzano/component/certmanagerconfig/certmanager_config_component.go, platform-operator/controllers/verrazzano/component/certmanagerocidns/certmanagerocidns_component.go, tests/e2e/verify-distribution/verifydistribution/verify_distribution_test.go
Set `InstallBeforeUpgrade=true` for new OCI DNS CM webhook solver, to allow it to spin up during upgrade from an earlier release.
Also remove the min-version hooks on the cert-manager-config and webhook components.
=> VZ-9459.  Allow install-before-upgrade for OCI DNS CM webhook

platform-operator/metricsexporter/metricsexporter_test.go
The metricsexporter_utils `Init` function calls other functions that result in a goroutine being spawned. There are two unit tests in metricsexporter_test and they both called that `Init` function. Because `Init` spawns a goroutine and it was being called twice, there was a race condition that caused an intermittent panic.
I fixed the race condition by changing the unit tests to call `Init` from an `init` function, so that it will only be called once. I verified the race condition no longer exists with `go test -race`.
=> Fix race condition in unit test

platform-operator/helm_config/charts/verrazzano/values.yaml
Enable AuthorizationPolicy for Jaeger Operator component when the component is enabled
=> VZ-9208: AuthorizationPolicy Missing for Jaeger Traces to be transmitted

platform-operator/controllers/verrazzano/component/capi/capi_component.go, platform-operator/controllers/verrazzano/component/capi/capi_component_test.go
This pull request adds a check to disallow disabling the CAPI component if enabled.
=> VZ-9503: disallow disable of capi component if enabled

platform-operator/controllers/verrazzano/component/common/externaldns.go
Prefix/postfix newline chars to the `compartment` field when we add it to the OCI DNS secret on copy.
=> Prefix compartment ID with newline when copying the OCI DNS secret

platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
Backport a fix to prepend/append newlines to the compartment ID field we add when copying the OCI DNS secret
=> Backport newline fix to release-1.5

platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
Backport a fix to prepend/append newlines to the compartment ID field we add when copying the OCI DNS secret
=> Backport newline fix to release-1.3

platform-operator/controllers/verrazzano/component/externaldns/external_dns.go
Backport a fix to prepend/append newlines to the compartment ID field we add when copying the OCI DNS secret
=> Backport newline fix to release-1.4

platform-operator/controllers/verrazzano/component/capi/capi_component.go, platform-operator/controllers/verrazzano/component/capi/capi_component_test.go
This pull request is to change uninstall of the CAPI component to only delete providers we installed instead of all providers.
=> Only delete CAPI providers we installed

platform-operator/verrazzano-bom.json
Updated OCI DNS webhook image built using CM 1.9.1 API.
=> VZ-9459.  Update OCI DNS webhook image updated to CM 1.9.1

platform-operator/controllers/verrazzano/component/istio/istio_install_test.go, platform-operator/controllers/verrazzano/secret/image_pull_secret.go, platform-operator/controllers/verrazzano/secret/image_pull_secret_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml
The current public doc instructions for installing from a private registry state that the VPO image must be public (i.e. pullable without credentials). This PR fixes that so the VPO image can be private.
The VPO already copies the `verrazzano-container-registry` secret from the default namespace (if it exists) to all target namespaces when installing components. This PR enables the VPO to also look for the secret in the `verrazzano-install` namespace if the secret does not exist in the default namespace.
Once this is merged, the public documentation will be updated to instruct the user to create the `verrazzano-container-registry` secret in the `verrazzan-install` namespace instead of the default namespace. We will also remove the instructions on making the VPO image public.
Once this is …
=> VZ-9531: Support installing VPO image from private registry with credentials

platform-operator/verrazzano-bom.json
This PR updates Keycloak image, built with the change https://github.com/verrazzano/keycloak/pull/16
=> VZ-8810: Update Keycloak 15.0.2 built with Kafka client v3.4.0

platform-operator/verrazzano-bom.json
This PR updates Keycloak image, built with the change https://github.com/verrazzano/keycloak/pull/16
=> Update Keycloak image with Kafka client updated to v3.4.0, in release-1.3

ci/chaos/Jenkinsfile, ci/ha/JenkinsfileRollingUpgrade, ci/lre/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/olcne/Jenkinsfile, ci/scripts/install_verrazzano.sh, ci/scripts/prepare_jenkins_at_environment.sh, ci/scripts/prepare_kind_cluster_dns_pipeline.sh, ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade-paths/Jenkinsfile, tools/vz/cmd/helpers/command.go, tools/vz/cmd/helpers/command_test.go, tools/vz/cmd/helpers/vpo_test.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/pkg/constants/constants.go
=> VZ-9482 - Add --manifests flag to VZ CLI in order to be able to run it in air gapped environment without downloading VPO manifests

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Installing with the VZ CLI showed messages that look like this:
```
info Component Keycloak successfully created the %!s(MISSING) rolevz_api_access
```
This PR fixes the log statement.
=> Fix bug in Keycloak log message

platform-operator/verrazzano-bom.json
update OS image to bump Netty to 4.1.86.Final
=> VZ-9580: update OS image to bump Netty to 4.1.86.Final

platform-operator/verrazzano-bom.json
Update OS image to bump Netty to 4.1.86.Final
=> VZ-9580: Backport to release-1.5: Update OS image to bump Netty to 4.1.86.Final 

platform-operator/verrazzano-bom.json
VZ-9578: bump Netty to 4.1.86.Final in OS 1.2.3
=> VZ-9578: bump Netty to 4.1.86.Final in OS 1.2.3

ci/lre/Jenkinsfile
This pull request bumps the LRE upgrade timeout to 45m.  There have a been a few upgrades that have taken longer than the default timeout of 30m.  The pipeline was failing even though upgrade was eventually successful.
=> Bump the LRE upgrade timeout

ci/scripts/prepare_distribution_test_jenkins_at_environment.sh
This pull request enables the capi component install for private registry tests.
=> Enable capi component install for private registry tests

ci/JenkinsfilePeriodicTests
This fixes the following error:
`The parameter 'RUN_TESTS' did not have the type expected by verrazzano-distributions-testing » master. Converting to Boolean Parameter.`
=> Declare env variable as a boolean in periodics

ci/JenkinsfilePeriodicTests
This fixes the following error:
`The parameter 'RUN_TESTS' did not have the type expected by verrazzano-distributions-testing » master. Converting to Boolean Parameter.`
=> CI update to use Boolean param (#5971)

platform-operator/thirdparty/charts/thanos/templates/verrazzano/networkpolicy.yaml
While I was doing manual testing of the Prometheus Operator upgrade, I noticed that Prometheus was not able to scrape metrics from the Thanos Istio proxy containers in the Query and Query Frontend pods. My test cluster had Calico enabled.
The problem was the NetworkPolicy resources were blocking access to the Istio proxy metrics ports in those pods. I have made the following changes to the Thanos NetworkPolicies:
- Updated the Query and Query Frontend policies to add a label match selector on the component. Without this, the policies were selecting all Thanos pods.
- Updated the Query and Query Frontend policies to include the Istio proxy metrics port.
I tested by installing in cluster with Calico enabled and validated that the scrape targets for the Thanos and Istio proxy containers in …
=> Thanos Istio proxy container Prometheus scrape fix

Jenkinsfile, ci/private-registry/Jenkinsfile, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh
**Changes**
- Use the VZ CLI in the private registry tests
- Fix the verrazzano pipeline to run the private registry tests
- Fix the lite distribution for the private registry tests
=> VZ-9552 Use the CLI in the private registry tests

platform-operator/thirdparty/charts/kiali-server/templates/rolebinding.yaml
Prior to this change, the post VZ installation update of the kiali-server helm chart value `deployment.view_only_mode` fails as it tries to change the roleRef which is immutable. This change tries to create a new clusterrolebinding based on the view_only_mode configuration.
=> VZ-9010 Support for updation of kiali-server helm value view_only_mode

platform-operator/verrazzano-bom.json
This PR updates the following component images in verrazzano-bom.json
1. Keycloak 20.0.1 image is built with the change https://github.com/verrazzano/keycloak/pull/17
2. Other images are rebuilt with the base image, to get the latest packages.
=> Update Keycloak, refresh few component images

platform-operator/controllers/verrazzano/component/argocd/argocd_postinstall.go
Tne verrazzano argocd component must not overwrite policy.csv, but rather add the `g, verrazzano-admins, role:admin` policy if it is missing.
=> VZ-9644 verrazzano argocd component must not overwrite policy.csv

platform-operator/verrazzano-bom.json
This PR updates the following component images in verrazzano-bom.json
1. Keycloak 20.0.1 image is built with the change https://github.com/verrazzano/keycloak/pull/17
2. Created release-1.5 branch for keycloak-oracle-theme and the image is built from that branch
3. Other images are rebuilt with the base image, to get the latest packages.
=> Update Keycloak, refresh few component images in release-1.5

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
This pull request fixes a link in the API docs which was changed in the reorg of docs.
=> Fix doc link for api doc

platform-operator/controllers/verrazzano/component/certmanager/common/acme_utils.go, platform-operator/controllers/verrazzano/component/certmanager/common/validate.go, platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config.go, platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config_component.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_component.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_component_test.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_test.go, platform-operator/helm_config/charts/verrazzano-cert-manager-ocidns-webhook/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-cert-manager-ocidns-webhook/templates/rbac.yaml, platform-operator/helm_config/charts/verrazzano-cert-manager-ocidns-webhook/values.yaml, tests/e2e/pkg/kubernetes.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go
Run the Verrazzano OCI DNS solver webhook in the `verrazzano-system` namespace
- give it permission to read secrets in the Cert-Manager `clusterResourceNamespace` (e.g., the OCI DNS auth secret)
- modify the RBAC permissions to allow Cert-Manager to discover and invoke the webhook APIService
- turn off Istio injection for the deployment
- Add E2E tests cases for external-dns and the webhook deployments if they are enabled
Other changes:
- Modify `IsEnabled` to check that the webhook is deployed IFF CM is enabled, OCI DNS is configured, and ACME is configured
- align validation functions on v1alpha1 API for now.
=> VZ-9645.  Use verrazzano-system namespace for OCI DNS webhook

tests/e2e/verify-install/kubernetes/kubernetes_test.go
Revert new test cases for external-dns and OCI DNS webhook deployments, the tests do not account for upgrade scenario and are breaking LRE.
=> Disable new install checks for external-dns and the CM OCI DNS webhook

platform-operator/controllers/verrazzano/component/certmanager/ocidns/append_overrides_test.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_component.go, platform-operator/helm_config/charts/verrazzano-cert-manager-ocidns-webhook/templates/rbac.yaml, platform-operator/helm_config/charts/verrazzano-cert-manager-ocidns-webhook/values.yaml
Updates the RBAC for the OCI DNS Auth webhook to scope access to secrets in the Cert-Manager `clusterResourceNamespace` to only what is required/configured by Verrazzano.
=> VZ-9702.  Limit OCI DNS webhook secrets access to configured auth secret

platform-operator/controllers/verrazzano/component/argocd/argocd_postinstall.go, platform-operator/controllers/verrazzano/component/argocd/argocd_postinstall_test.go
Tne verrazzano Argo CD component must not overwrite policy.csv, but rather add the g, verrazzano-admins, role:admin policy if it is missing.
This is a cherry-pick from master
=> VZ-9644  verrazzano argocd component must not overwrite policy.csv

CHANGES.md
Add release note
"Fixed Argo CD bug to allow the policy.csv field in the argocd-rbac-cm ConfigMap to be overridden."
=> VS-9644 Add Argo CD release note

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go
This pull request fixes the install of vz on a CAPI cluster which was failing with the error:
```
admission webhook "install.verrazzano.io.v1beta1" denied the request: found existing namespace tigera-operator not created by Verrazzano
```
=> VZ-9711: don't check for tigera-operator Rancher namespaces during install/uninstall

cluster-operator/controllers/vmc/argocd.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/clusterrole.yaml
Reverts verrazzano/verrazzano#6015
=> Revert "VZ-9712 - Make ArgoCD cluster registration and Rancher manifest pushes work on managed cluster with 'none' profile."

platform-operator/verrazzano-bom.json
Tested in a local cluster, and the Oracle theme is rendered on the login screen as expected.
=> Uptake latest keycloak-oracle-theme build (release-1.5)

platform-operator/verrazzano-bom.json
Updates Keycloak image built with the change https://github.com/verrazzano/keycloak/pull/20
=> VZ-9219: Uptake Keycloak 15.0.2 built with netty.io v4.1.86.Final in release-1.4

platform-operator/verrazzano-bom.json
Updates Keycloak image built with the change https://github.com/verrazzano/keycloak/pull/20
=> VZ-9219: Uptake Keycloak 15.0.2 built with netty.io v4.1.86.Final in release-1.3

platform-operator/verrazzano-bom.json
Refreshes components built from source in verrazzano-bom.json for 1.5. Except the images built from ingress-nginx repository, all other images are built with the same commit. There is a change which is compatible with release-1.5 in ingress-nginx, so used the latest source for the same.
=> VZ-8902: Refresh component images in release-1.5

tests/e2e/config/scripts/v1beta1/install-verrazzano-ocne.yaml
This pull request fixes invalid vz yaml being user during an OCNE acceptance test.  This was caught because the vz cli now validates the vz yaml.
=> VZ-9863: Fix incorrect vz yaml

platform-operator/controllers/verrazzano/component/certmanager/common/validate.go, platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config.go, platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config_component.go, platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config_test.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_component.go, platform-operator/controllers/verrazzano/component/certmanager/ocidns/certmanagerocidns_component_test.go
Removes earlier attempts to base decisions around the webhook deployment and issuer configuration based on the availability of CertManager CRDs, in favor of the new component APIs.
=> Remove CRD checks in CM components in favor of component checks

tests/e2e/update/a-la-carte/a_la_carte_test.go
The a-la-carte tests have been updated to use an externally-installed Cert-Manager, meaning that it is installed outside of the Verrazzano install, and the `certManager` component is disabled.
With the introduction of the `clusterIssuer` Component users will now have to explicitly enable that for the "app-stack" (minimal configuration to allow ingress) to work.  This change enabled the `clusterIssuer` component going forward.
=> Enable ClusterIssuer component for app stack stage in a-la-carte tests

platform-operator/verrazzano-bom.json
Updates NGINX ingress, Keycloak and other images in release-1.5
=> VZ-8902: Update NGINX ingress, Keycloak and other images in release-1.5

platform-operator/controllers/verrazzano/component/certmanager/config/certmanager_config_test.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt_test.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go, platform-operator/controllers/verrazzano/component/spi/component_context.go, platform-operator/main.go
Update components in the VPO to use the new clusterIssuer component for certificates configuration.  This largely consists of the Rancher code which sometimes needs to set up additional CA bundles to communicate with other components internally and remote managed clusters.
The `ComponentContext.EffectiveCR` is used to organize the other VPO components around the certificate issuer configuration using the new `ClusterIssuerComponent`.  That change was introduced in an earlier PR.  When the `EffectiveCR` is computed, the existing `CertManager` configuration is merged into the `ClusterIssuerComponent` configuration.  This prevents component code from having to switch between the `CertManagerComponent.Certificate` field and the `ClusterIssuerComponent`, and preserves  backwards compatibility …
=> VZ-9847.  Align remaining VPO components on new CertManager APIs

platform-operator/helm_config/charts/verrazzano-cluster-agent/.helmignore, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/templates/clusterrole.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/templates/clusterrolebinding.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/templates/serviceaccount.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/values.yaml, platform-operator/thirdparty/charts/mysql/templates/deployment_cluster.yaml
**Changes**
- Added a Helm chart that deploys the Verrazzano cluster agent
- This change is ineffectual to the program, but provides scaffolding for future updates
**Testing**
- Deploy a minimal multicluster setup with a stripped back managed cluster Verrazzano CR
- Apply this helm chart with the correct image override
- Test managed cluster registration and make sure the MC Agent populates the metrics endpoint
=> VZ-9839 Create the Verrazzano Cluster Agent Helm chart

platform-operator/verrazzano-bom.json
This updates the webhook image name to the new image built from the github repo.
=> Update cert manager ocidns webhook image

pkg/helm/helmcli.go, pkg/helm/helmcli_test.go, platform-operator/controllers/verrazzano/healthcheck/status_updater.go, platform-operator/controllers/verrazzano/reconcile/status.go
Implementing similar functionality to PR https://github.com/verrazzano/verrazzano/pull/6095 for the Release 1.5 branch
=> VZ-9788 Backport limiting number of helm releases and updating component generation when upgrade complete

CHANGES.md, platform-operator/verrazzano-bom.json
Note that no Helm chart upgrade is needed because Prometheus is deployed by the Prometheus Operator which is installed via the kube-prometheus-stack Helm chart, and that chart was upgraded very recently.
=> VZ-9864: Uptake Prometheus 2.44.0

platform-operator/verrazzano-bom.json, tests/testdata/jaeger/hotrod/hotrod-tracing-comp.yaml, tests/testdata/jaeger/hotrod/multicluster/hotrod-tracing-comp.yaml
This change refreshes component images in release-1.4. In some cases, there are issues in the build pipelines to build the components with the same commit, so those components are built with the latest commit after going through the list of changes.
=> VZ-8902: Refresh component images in release-1.4

ci/oke-ocidns/JenknsfileDnsKind
fix typo that was in ci/oke-ocidns/JenknsfileDnsKind
=> fix typo that was in ci/oke-ocidns/JenknsfileDnsKind

pkg/k8s/ready/certificates.go, pkg/k8s/ready/certificates_test.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go
The VPO currently does checks on Certificate status when the CertManager component is enabled; however this breaks when using a customer-managed Cert-Manager instance.
Additionally, the Prometheus Operator uses Cert-Manager certs if it is available, however it can no longer rely on checking if the Verrazzano `certManager` component is enabled.
In both cases we shift to using the `clusterIssuer` component to check for these behaviors.  The `clusterIssuer` is what unifies both cases, the Verrazzano-managed and customer-managed Cert-Manager instances.
Also fixes up related unit tests.
Manually verified the behavior in the debugger for the customer-managed CM case, and examined the VPO logs for the default case.
=> VZ-9633.  Cert ready-checks, Prom Operator webhook certs with customer-managed CertManager

CHANGES.md, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/Chart.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/README.md, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/NOTES.txt, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/_helpers.tpl, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/deployment.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/podsecuritypolicy.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/psp-clusterrole.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/role.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/rolebinding.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/service.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/serviceaccount.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/servicemonitor.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/templates/verticalpodautoscaler.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-state-metrics/values.yaml, platform-operator/verrazzano-bom.json
This PR upgrades the kube-state-metrics image to version 2.8.2 and also upgrades the kube-state-metrics Helm chart to 5.6.4.
Note that the new Helm chart splits the registry from the repository and thus requires a new Helm key in the BOM for the registry. This same change was made to the Prometheus Operator images when upgrading the kube-prometheus-stack Helm chart recently.
=> VZ-9833: Uptake kube-state-metrics 2.8.2 and Helm chart 5.6.4

ci/a-la-carte/Jenkinsfile, ci/scripts/install_third_party_components.sh, tests/e2e/update/a-la-carte/a_la_carte_suite_test.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
This change makes the cluster issuer namespace configurable in the a-la-carte pipeline, but defaults it to my-cert-manager. It also changes the namespace for the third party cert-manager to my-cert-manager.
=> Make cluster issuer namespace configurable in a-la-carte pipeline

ci/multicluster/Jenkinsfile
This PR moves the `verify-argocd` stage to after we update the DNS zone and rootCA cert on the managed cluster. This makes sure that our multicluster tests support ArgoCD after certs have been updated.
=> VZ-8933 Verify rootCA update works for ArgoCD

platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/manifests/profiles/v1beta1/none.yaml
I found a couple of new components that were not added to the `none` profile for `v1beta1`.  
I added those, and updated the unit test to also check the `v1beta1` effective CR to catch these in the future.
=> Fix v1beta1 none profile

pkg/constants/constants.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go
Currently, when the Verrazzano self-signed CA bundle expires, Cert-Manager properly rotates the CA and leaf certificates, but the copy of the CA bundle used by Rancher does not get updated. This may be applicable even when using a custom private CA. This PR tries to address this issue by making VPO to synchronize CA in `tls-ca` Rancher secret with that of in `verrazzano-tls` secret whenever there is an update to `verrazzano-tls` secret. It also restarts Rancher POD when there is an update to `tls-ca` Rancher secret  to get the secret reflected in the POD.
=> VZ-9761 Synchronize Rancher TLS CA with Verrazzano TLS

platform-operator/controllers/verrazzano/component/argocd/argocd_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/common/acme_utils.go, platform-operator/controllers/verrazzano/component/certmanager/common/acme_utils_test.go, platform-operator/controllers/verrazzano/component/certmanager/common/config_test.go, platform-operator/controllers/verrazzano/component/certmanager/common/crdchecks.go, platform-operator/controllers/verrazzano/component/certmanager/common/crdchecks_test.go, platform-operator/controllers/verrazzano/component/certmanager/constants/constants.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component_test.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/validate_issuer.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/validate_issuer_test.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/webhook_oci_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go, platform-operator/controllers/verrazzano/component/kiali/kiali_component.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go, platform-operator/controllers/verrazzano/transform/convert_certificate.go, platform-operator/controllers/verrazzano/validator/ComponentValidatorImpl_test.go, tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go, tests/e2e/verify-infra/vmi/vmi_test.go
Introduces some additional validators for some new cases for the new Cert-Manager component suite.
If the ClusterIssuer is enabled, and the Verrazzano `certManager` component is disabled:
- validate that the `clusterResourceNamespace` exists
- validate that Cert-Manager CRDs are present in the cluster
The above are only checked for the case where the Verrazzano `certManager` component is disabled; in that case, if the `clusterIssuer` is enabled we expect Cert-Manager types and the expected namespace to be active.
Other changes:
- refactor some common CM component constants into a `platform-operator/controllers/verrazzano/components/certmanager/constants` package to avoid import cycles
- Update the corresponding components and e2e tests for the above change
- Update the …
=> VZ-9889.  Updated validators for customer-managed Cert-Manager

platform-operator/verrazzano-bom.json, tests/testdata/grafana/grafana-mysql.yaml
This change updates BOM with the correct image name for backup-restore-operator.
=> VZ-9939: Update backup restore operator image in BOM

ci/chaos/JenkinsfileResiliencyTrigger, ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease, tests/e2e/upgrade/pre-upgrade/verify/verify_preupgrade_test.go
Also, the following changes are done:
- Fix the logic in parsing `excludeReleaseTags` in the `derive_upgrade_version.go` code.
- Update the `derive_upgrade_version.go` code to handle the case where there are no more than two minor versions supported for the upgrade. 
- Do not run the VMI prometheus pre-upgrade tests for versions greater than or equal to vz 1.4 as VMI prometheus support has been moved to Prometheus operator in 1.4.
=> VZ-9942 VZ-9721 Exclude VZ 1.3 release from upgrade testing

platform-operator/verrazzano-bom.json
This PR is to pick the Rancher images that has a fix to the rancher agent image path when using private registry. See https://github.com/verrazzano/rancher/pull/105 for details.
=> VZ-9672 Update Rancher images

ci/JenkinsfilePeriodicTests
Fix periodics to not run prerelease validation when DRY_RUN=TRUE
=> VZ-9933 Periodics Dry Run will fail in Release Candidate Validation Checks

platform-operator/verrazzano-bom.json
This PR is to pickup the new Rancher images that has a fix to the rancher agent image path when using private registry. See https://github.com/verrazzano/rancher/pull/106 for details.
=> VZ-9672 Update Rancher images (#6161)

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go, platform-operator/main.go
Currently the K8S version validation is in the webhook init, and does an os.Exit, which causes the VPO to go into crash loop backoff when the K8S version is unsupported. 
Instead, we are now allowing the VPO to come up if it can, even in an unsupported version, and performing the validation at VZ install time in the webhook's ValidateCreate/ValidateUpdate.
=> VZ-9199 - move Kubernetes version validation to the VPO webhook create/update validation

platform-operator/capi/control-plane-ocne/v0.1.0/control-plane-components.yaml, platform-operator/verrazzano-bom.json
This pull request picks up a new control plane ocne provider that has the remaining VPO helm chart install changes and a ocnecp API change to enable a private registry.
=> VZ-9912: pickup latest ocne providers with VPO changes and updated ocnecp API change

platform-operator/verrazzano-bom.json
This PR is to pick up the new Rancher images that has a change to host the OKE driver on Rancher server and activate it from the same. See  https://github.com/verrazzano/rancher/pull/108 for details.
=> VZ-9923 Uptake new Rancher images

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
fix space issue in chart path of fluent operator in comments
=> fix space issue in chart path of fluent operator in comments

platform-operator/verrazzano-bom.json
Take new OCNE Driver, UI versions that support installation and upgrade of Verrazzano, as well as module naming conventions for `oci-ccm`.
=> New OCNE Driver, UI

platform-operator/verrazzano-bom.json
A previous change implemented the simplified API
https://github.com/verrazzano/cluster-api-provider-ocne/pull/19
where API was updated if input was simple.
This PR will prevent the API from getting updated and just update necessary configurations for bootstrap functionality
=> VZ-10007: Update CAPI with simplified api change

platform-operator/helm_config/charts/fluentbit-opensearch-output/templates/application-clusteroutput.yaml, platform-operator/helm_config/charts/fluentbit-opensearch-output/templates/system-clusteroutput.yaml
This PR is to fix mapping conflict with OS index template with labels such that data gets ingested properly.
=> replace dots with underscore in opensearch output

CHANGES.md
Fixes up the 1.5.4 release notes section, and uses `Fixes` header where appropriate.
=> VZ-10012.  Make release notes consistent with other lines

platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluent-operator-deployment.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-fluentBit.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml
Add Pod Security for Fluent Operator and Fluentbit pods.
- No container level security context for Fluentbit. As it is missing in fluentbit CRD in flunet Operator Helmchart.
- kept running Fluentbit as root user because it requires write access to the directory /fluent-bit/etc/tail that has write access to root only.
=> VZ-10041: Add Pod Security for Fluent Operator

pkg/vzcr/enabled.go, pkg/vzcr/enabled_test.go, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go
=> VZ-9919 - VMO does not need to be enabled when Prometheus is enabled e.g. managed clusters

CHANGES.md
=> VZ-10058: Rancher Partner charts and RKE2 removed from VZ Rancher 2.7.3

platform-operator/internal/operatorinit/versions.go
Fixed bug where VPO restarted when first creating the verrazzano-meta cm.
=> VZ-10070: fix bug where VPO restarted when first creating the verrazzano-meta cm

ci/uninstall/JenkinsfileUninstallTest, pkg/vzcr/enabled.go, pkg/vzcr/enabled_test.go, tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/uninstall/verifycrds/verify_crds_suite_test.go, tests/e2e/uninstall/verifycrds/verify_crds_test.go, tests/e2e/verify-install/kubernetes/kubernetes_test.go
=> VZ-9919 - VMO does not need to be enabled when Prometheus is enabled e.g. managed clusters, plus uninstall-resiliency-test fix

platform-operator/thirdparty/charts/rancher/templates/deployment.yaml
Additional permissions are required on some systems fork processes.
=> VZ 10085: Permissions for rancher pod

platform-operator/verrazzano-bom.json
Updates version for nginx-ingress-controller and kube-webhook-certgen images in release-1.6
=> Fix version of nginx-ingress-controller and kube-webhook-certgen images in BOM, release-1.6

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides_test.go
=> VZ-9965: Fix clusterAPI component to use REGISTRY environment variable for global override

platform-operator/verrazzano-bom.json
Takes up the latest Rancher image that fixes the `rancher-agent` image path when a managed cluster is imported via the Rancher UI in an air-gapped/private-registry env.
For details see https://github.com/verrazzano/rancher/pull/113.
=> VZ-10122.  Update rancher images for air-gap multi-cluster fix

platform-operator/capi/bootstrap-ocne/v1.6.1/bootstrap-components.yaml, platform-operator/capi/cluster-api/v1.4.2/core-components.yaml, platform-operator/capi/control-plane-ocne/v1.6.1/control-plane-components.yaml
this is not a functionality change, but a change to maintain parity
=> VZ-10037: update internal CAPI templates with image tags from bom.

platform-operator/controllers/verrazzano/healthcheck/availability.go, platform-operator/controllers/verrazzano/healthcheck/availability_test.go
When a component is uninstalled, its state in the VZ CR status shows as uninstalled but the availability field still showed available. This PR fixes the bug. Also, the metrics for components were never updated once a component is disabled, so that is also fixed.
I tested this in a local cluster by:
1. Installed the stock dev profile
2. Confirmed the VZ CR status showed the right number of available/total components
3. Viewed the Grafana System Health dashboard and confirmed the component statuses were correct
4. Modified the VZ CR and disabled the kubeStateMetrics component
5. Once the update completed, confirmed that the VZ CR status showed kubeStateMetrics as uninstalled and unavailable, and that the available/total components was correct
6. Viewed the Grafana System Health dashboard …
=> VZ-10117: Fix component availability reporting for uninstalled components

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go
If CAPI init is called by VPO ClusterAPI component before cert manager validating webhook is ready, then the CAPI init  code will install old cert manager.
When the VPO CAPI component does an install, it calls CAPI init to initialize the CAPI resources.   The CAPI init code tries to create cert-manager test resources, and if it cannot, it installs cert-manager using different images and charts.  The problem is that the VPO certManager component installs cert manager, but doesn't wait for the cert-manager-webhook validatingwebhook to have the caBundle bundle.  Until that happens, you will get a webhook error when trying to create a cert manager resource.
The temp solution is to make ClusterAPI component depend on the certManagerClusterIssuer component to be ready, since …
=> VZ-10137 capi init must not be called until cert-manager resources can be created.

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go
Install ClusterAPI before upgrade because it is now enabled by default and Rancher won't upgrade until ClusterAPI pods are ready.
=> VZ-10158 install ClusterAPI before upgrade

tools/vz/pkg/bugreport/reportgen.go
This pull request removes prerequisite checks that were generating the following misleading warning when running **vz analyze**:
Warning: minimum required ephemeral storage is 100G but the ephemeral storage on node 10.196.3.107 is 34.262890849G
These checks had been removed from v1.6 but not v1.5
=> Remove prerequisite checks

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go
Install ClusterAPI component before upgrade, since Rancher will hang if CAPI is enabled but not installed.
=> VZ-10158 install capi before upgrade (#6314)

ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileTrigger, ci/scripts/install_third_party_components.sh, ci/scripts/prepare_jenkins_at_environment.sh, tests/e2e/security/netpol/network_policy_test.go, tests/e2e/update/env-dns-cm/env_dns_cert_update_test.go, tests/e2e/verify-infra/vmi/vmi_test.go
This adds external cert-manager as an option to the dynamic update pipeline. It also includes it as a configuration of the dynamic updates suite that runs from the periodics.
=> VZ-9994 Add optional external cert-manager to dynamic update pipeline

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
=> VZ-10180: Fix initialization of ociocne driver on upgrade (forward port from release-1.6)

application-operator/apis/clusters/v1alpha1/verrazzanoproject_types.go, platform-operator/helm_config/charts/verrazzano-cluster-agent/crds/clusters.verrazzano.io_verrazzanoprojects.yaml
This pull request fixes a network policies link in the API docs.
=> Fix network policies link in API docs

tools/vz/cmd/uninstall/uninstall.go
The default value for the VZ uninstall prompt should be "no" to match the behavior of the command.
=> Fix the default value prompt for VZ uninstall command

platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Handle LetsEncrypt/prod default case for rancher
- Fix Rancher Helm value override for default LE/prod scenario
- Do not create tls-ca-additional when LE staging is not in play
- add/update related unit tests
Not a strict backport per-se, but a re-implementation using the CM APIs.
=> VZ-9959.  Backport fix to release-1.5

platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/validate_issuer.go, platform-operator/controllers/verrazzano/component/common/acme_utils.go, platform-operator/controllers/verrazzano/component/common/acme_utils_test.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt.go, platform-operator/controllers/verrazzano/component/common/rancher_letsencrypt_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Handle LetsEncrypt/prod default case for rancher 
- Fix Rancher Helm value override for default LE/prod scenario
- Do not create tls-ca-additional when LE staging is not in play
- refactor LE utils from cert-manager common to component common
- add/update related unit tests
=> VZ-9959.  Backport to release-1.6 (#6333)

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/resource_usage_summary_dashboard.json
The PV expression was failing if the OS pods restarted because there would be a duplicate pod name. This new expression sums across the values we do not use to select (like pod name). This prevents an error in the Grafana dashboards if the pods restart.
=> VZ-10076 fix the PV Grafana expression to adapt to multiple replicas

ci/multicluster/Jenkinsfile, examples/multicluster/managed-clusters/minimal-prometheus.yaml, examples/multicluster/managed-clusters/minimal-thanos.yaml
=> VZ-10104 Enable kube-state-metrics and node-exporter in minimal managed cluster profiles that have monitoring

platform-operator/verrazzano-bom.json
These latest Rancher images contain a bug fix for the Rancher cleanup image when using a private registry and a fix to return additional cloud credential fields in the OCI handler.
=> VZ-10131: Uptake latest Rancher images

platform-operator/verrazzano-bom.json
Backport Rancher 2.7.3 image uptake to release-1.6 branch.
=> VZ-10131: Uptake latest Rancher images (#6357)

ci/a-la-carte/Jenkinsfile, ci/scripts/wait-for-namespace-not-exist.sh, pkg/k8s/ready/deployment_ready.go, pkg/k8s/resource/resource.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component.go
Fix uninstall of none profile. Part of the problem was that uninstall was failing since certain CRDs were not installed. Handle that case in the resource.go file.
Also added tests to a la cart to uninstall, re-install none, then uninstall again.
=> VZ-10206 fix uninstall none profile 

platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall_test.go
=> VZ-10107 - Change the Rancher cattle-system namespace's verrazzano.io/namespace label to equal the namespace name, to match network policy

platform-operator/controllers/verrazzano/component/rancher/rancher_postinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall_test.go
=> VZ-10107 - Change the Rancher cattle-system namespace's verrazzano.io/namespace label to equal the namespace name, to match network policy 

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
This pull request fixes the upgrade of the clusterAPI component when going from a version without clusterAPI (1.5.3) to a version with clusterAPI (1.6.0).  The upgrade was first installing clusterAPI deployments and then later upgrading clusterAPI components which resulted in the clusterAPI components getting redeployed.
With this fix the clusterAPI deployments are not redeployed.
=> VZ-10215: fix upgrade of clusterAPI component

platform-operator/controllers/verrazzano/healthcheck/availability.go, platform-operator/controllers/verrazzano/healthcheck/availability_test.go
Backport of fix to availability reporting in the Verrazzano CR status to the release-1.5 branch.
See https://github.com/verrazzano/verrazzano/pull/6305 for details.
=> VZ-10117: Fix component availability reporting for uninstalled components (release-1.5)

platform-operator/controllers/verrazzano/component/appoper/app_operator_component.go, platform-operator/controllers/verrazzano/component/appoper/app_operator_component_test.go
**Changes**
- Ignore the VMC list if no kind error is returned from the list request
**Testing**
- Install 1.5.3 with the cluster operator disabled
- Upgrade to this branch and verify that upgrade completes
=> VZ-10183 Ignore VMC list if the CRD does not exist

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, tools/vz/Makefile, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/helpers/scheme.go, tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzcapture_capi.go, tools/vz/pkg/helpers/vzcapture_test.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/test/helpers/fake_cmd_context.go
VZ-10218: Add snapshot of CAPI resources to vz bug-report
=> VZ-10218: Add snapshot of CAPI resources to vz bug-report back port to release-1.6

ci/ha/JenkinsfileRollingUpgrade, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go, platform-operator/main.go
This PR fixes the HA pipeline in the release-1.5 periodic tests. There are two changes:
1. Adjust the OKE versions in the Jenkinsfile
2. Backport a change to the way the Kubernetes version is checked
=> Fix release-1.5 HA pipeline

ci/kind/Jenkinsfile
The timeout is 90 minutes on master and release-1.6, and the release-1.5 periodics have some timeouts for Kind tests because they usually take right around 1 hour to complete, so bumping this timeout so it aligns with other branches.
=> Increase timeout from 60 to 90 minutes for Kind pipeline

platform-operator/controllers/verrazzano/component/argocd/argocd.go, platform-operator/controllers/verrazzano/component/argocd/argocd_component.go, platform-operator/controllers/verrazzano/component/argocd/argocd_test.go, platform-operator/controllers/verrazzano/component/common/argocd.go
Uninstall does not clean up the argocd resources that get created when an app gets deployed. If a user chooses to configure an app with a finalizer, that will stop the deletion of the argocd namespace and cause uninstall to fail. This change removes the finalizer and deletes the application, applicationset, and appproject argocd resources in the argo postuninstall step.
=> VZ-10181 cleanup argocd during uninstall

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go, platform-operator/controllers/verrazzano/reconcile/controller_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, platform-operator/controllers/verrazzano/reconcile/uninstall_test.go, platform-operator/verrazzano-bom.json
- Ensure that cattle-system namespace and its resources aren't deleted during VZ uninstall if the cluster is Rancher container driver/OCNE provisioned
- Some simplification of Rancher post-uninstall cleanup logic
MC and uninstall resiliency pipelines were run in addition to standard pipelines and manual functional testing with provisioned cluster.
=> VZ-10217 check if Rancher driver provisioned before deleting cattle-system and resources

platform-operator/helm_config/overrides/kube-state-metrics-values.yaml, platform-operator/helm_config/overrides/prometheus-operator-values.yaml
**Changes**
- Add the verrazzano_cluster label for CAPI, Thanos, Fluentbit, and Fluent Operator
**Testing**
- Install on a local cluster and make sure the metrics get propagated to the Grafana Verrazzano Resource Usage dashboard
=> VZ-10129 Add verrazzano_component metrics label for new components

platform-operator/verrazzano-bom.json
Uptake new Rancher image for resolving system-library syncing errors seen in the Rancher logs. See https://github.com/verrazzano/rancher/pull/122 for details.
=> VZ-10243 Uptake new Rancher image

platform-operator/verrazzano-bom.json
Backport of PR #6446 to release-1.6 to uptake new Rancher image for resolving system-library syncing errors seen in the Rancher logs. See https://github.com/verrazzano/rancher/pull/122 for details.
=> VZ-10243 Uptake new Rancher image (#6446)

platform-operator/verrazzano-bom.json
Updates nginx-ingress images built with the change https://github.com/verrazzano/ingress-nginx/pull/7
=> VZ-8902: Update NGINX ingress images in release-1.6

tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/helpers/vzhelper.go
This pull request includes changes to always capture the CAPI resources during vz analysis/bug-report.
Also, fixed a bug where the verrazzano-install namespace was not being included in the analysis.
=> VZ-10278: always capture CAPI resources

application-operator/mcagent/mcagent_cluster_secrets.go, application-operator/mcagent/mcagent_cluster_secrets_test.go
=> MC Agent should sync its local cluster CA to the admin cluster even if the local CA is empty (#6442), and unit test (#6453)

platform-operator/verrazzano-bom.json
New OCNE capi image with following details:
Private registry fix (do not override crio) and status condition string typo.
Branch name : release/1.6
Version String : v1.6.1
Verrazzano Module commit: 15c5f4d37de4f486deb07234bcccac2d91053b36
Verrazzano Module branch: release/1.6
Verrazzano Module tag: v1.6.1-20230712221459-5a4801d6
OCNE Docker image tag : v1.6.1-20230713001831-abc04fb
=> Update OCNE capi provider with registry and status condition change

platform-operator/verrazzano-bom.json
Updates nginx-ingress images built with the change https://github.com/verrazzano/ingress-nginx/pull/8
=> VZ-8902: Update NGINX ingress images in release-1.5

cluster-operator/controllers/vmc/sync_prometheus.go, cluster-operator/controllers/vmc/vmc_controller_test.go
Fixes an issue setting up remote scrape targets on an admin cluster where the managed cluster CA bundle is empty (as is the case with certs issued by trusted CAs).  
At present we're unconditionally setting the CA bundle which for the empty bundle case causes a scrape error for Prometheus, similar to what's shown below:
```
Get "[https://prometheus.vmi.system.xxx.xxx.xxx:443/federate?match%5B%5D=%7B__name__%3D~%22..%2A%22%7D](https://prometheus.vmi.system.xxx.xxx.xxx.io/federate?match%5B%5D=%7B__name__%3D~%22..%2A%22%7D)": unable to load specified CA cert /etc/prometheus/managed-cluster-ca-certs/ca-mgd1-oke2: open /etc/prometheus/managed-cluster-ca-certs/ca-mgd1-oke2: no such file or directory
```
This change
- uses the managed cluster path inside `newScrapeConfig` when setting it …
=> VZ-10310.  Fix managed cluster scrape with production certs

tests/testdata/grafana/grafana-mysql.yaml
This PR fixes the BOM validation failure in release-1.4, by using the image from the BOM in the test script.
=> Use mysql-server:8.0.32 in test file to fix BOM validation failure

tests/e2e/clusterapi/capi/capi_test.go
CAPI status condition changed from `VerrazzanoPlatformOperatorDeployDeployed` to `VerrazzanoPlatformOperatorDeployed`
=> VZ-10318: update status constant to check

ci/JenkinsfilePeriodicTests
VERSIONED_IMAGES_FILENAME was missing field annotation in the backport
=> VERSIONED_IMAGES_FILENAME was missing field annotation in the backport

release/docs/README_FULL.html, release/docs/README_FULL.md, release/docs/README_LITE.md
As per [VZ-9735](https://jira.oraclecorp.com/jira/browse/VZ-9735) Documentation Archive page is no longer needed, this PR removes and replaces links to the Documentation Archive page.
=> replace link to archive page

platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
**Changes**
- The is ready check uses label selectors to make sure the deployments for Istio are ready
**Testing**
- Deploy a cluster with egress gateway disabled and verify the readiness check works
- Deploy a cluster with all enabled and verify the readiness check works
=> VZ-10265 Check enabled istio deployments by label for readiness and availability check

application-operator/mcagent/mcagent_cluster_secrets_test.go
Backport, just unit tests as related problem does not exist it seems in release-1.5.  Unit test should help ensure we don't introduce the problem in 1.5.
=> Backport MC Agent sync of empty CA from release-1.6

tools/vz/cmd/helpers/command.go, tools/vz/cmd/helpers/command_test.go, tools/vz/cmd/upgrade/upgrade_test.go
Backport of the bug fix to release-1.6. See #6539 for details.
=> VZ-10346: Do not require --version when --manifests is used with vz upgrade in air-gapped environment (#6539) (release-1.6)

tools/vz/cmd/helpers/command.go, tools/vz/cmd/helpers/command_test.go, tools/vz/cmd/upgrade/upgrade_test.go
Backport of the bug fix to release-1.5. See #6539 for details.
=> VZ-10346: Do not require --version when --manifests is used with vz upgrade in air-gapped environment (#6539) (release-1.5)

cluster-operator/controllers/rancher/rancher_cluster_controller.go, cluster-operator/controllers/rancher/rancher_cluster_controller_test.go
=> When deleting a VMC in the Rancher cluster controller, ignore not found error.

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go
This PR fixes the issue with CAPI Upgrade to skip applying upgrade options when upgrade options are empty.
=> Do not apply upgrade options when it is false

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Info message, once per minute on failure to get the Keycloak pod
=> Info message, once per minute on failure to get the Keycloak pod

pkg/k8sutil/k8sutil.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go
When Verrazzano is updated to change between private CA configurations, the secret ` cattle-system/tls-ca` will be updated with the new private CA, but the Rancher pods will not be rotated to pick it up as the deployment remains unchanged.  This will cause SSO errors logging into Rancher via Keycloak until the pods are rotated to pick up the bundle change.
With this change, immediately after running Helm in the `Install()` and `Upgrade()` methods we
- compare the contents of the `cacerts` `Settings` object used by Rancher with the data in `cattle-system/tls-ca`
- if they are different, and a rolling update of the `cattle-system/rancher` deployment is not already in progress, start a rolling restart of the Rancher deployment to pick up the new value
Other changes:
- Adds an override of the …
=> VZ-10035.  Roll rancher pods on update if cacerts is out of sync

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides_test.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go
This PR backports a fix to upgrade the cluster API controller images if they are older.
=> VZ-10226: Upgrade cluster API controller images if they are outdated. 

platform-operator/verrazzano-bom.json
port from https://github.com/verrazzano/verrazzano/pull/6530 , images created from oracle/release/1.7.1
=> VZ-10301: update cert-manager images

tests/e2e/config/scripts/v1alpha1/install-verrazzano-kind.yaml, tests/e2e/config/scripts/v1beta1/install-verrazzano-kind.yaml, tests/e2e/scripts/install/install_test.go, tests/e2e/verify-install/security/pod_security_test.go
- Enables Alertmanager in kind test for UI verification
- [SecurityContext.Privileged](https://pkg.go.dev/k8s.io/api@v0.27.4/core/v1#SecurityContext) is false by default if not specified, made corresponding change in tests/e2e/verify-install/security/pod_security_test.go
=> VZ-10277: Enable Alertmanager UI tests

pkg/k8sutil/k8sutil.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Backport 50a329cd5f41d64eae995bb6b5336f226666084d from `release-1.5` branch.
=> VZ-10035.  Backport rancher restart to 1.4

ci/tools/derive_upgrade_version.go, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR backports the below fixes to release-1.6:
- Fixes derive versions go tool to accurately derive interim and install version for upgrade resiliency pipeline.
- Fixes release branches to skip upgrade job from tip of release to master since this is done in master branch. 
- Removed the exclude release versions logic  from Jenkinsfile and implemented in go tool to handle edge cases such as Major releases and easier maintenance. 
- Refactored the upgrade minor release pipeline to use derive versions go tool to compute release tags after excluding the out of support releases.
=> VZ-10350: Backport to 1.6 fixes for derive versions and upgrade jobs

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml, platform-operator/thirdparty/charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-clusterinput-metrics.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-output-prometheus-exporter.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml, platform-operator/thirdparty/manifests/prometheus-operator/fluentbit_monitor.yaml, platform-operator/verrazzano-bom.json
- Service Monitor added for fluentbit
- FluentOperator chart update to support prometheus exporter input/output plugin.
- Enabled  prometheus exporter input/output plugin in Fluent-operator Override.
=> VZ-9920: Add prometheus metrics for fluentbit

tests/e2e/verify-none-profile/none_profile_test.go
This PR have the changes to update the allowedNameSpaces list and update the verify-none-profile tests to report the list of all not allowed namespaces
=> VZ-10307: Follow up PR to update allowedNamespaces and update tests

Jenkinsfile, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml
This edit makes it so the release_versions.sh script is run under the compliance and quality control tests as part of the default Verrazzano job. I ran a test with an incorrect chart version and correct chart versions and it displayed the intended behavior. I
=> VZ-10410 Validate the Helm Charts For First Party Components

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/verrazzano-bom.json, tests/e2e/verify-infra/restapi/rancher_url_test.go
Tune the Rancher setting kubeconfig-default-token-ttl-minutes in accordance with the Keycloak setting. Also, update Rancher image.
=> VZ-10244 Change the default value of Rancher setting

platform-operator/controllers/verrazzano/component/thanos/thanos.go, platform-operator/controllers/verrazzano/component/thanos/thanos_test.go, platform-operator/thirdparty/charts/thanos/templates/ruler/statefulset.yaml, tests/e2e/config/scripts/configure_thanos_install_storage.sh, tests/e2e/pkg/thanos.go, tests/e2e/verify-install/thanos/thanos_test.go
**Changes**
- Add the prometheus config reloader to the Thanos Ruler
- Mount the Prometheus Rule configmap
- Add e2e test to verify that the rules are properly loaded into Thanos Ruler
**Testing**
- Install by minimally enabling the Thanos ruler
- Verify the rules are populated in the Ruler UI.
=> VZ-10143 Add the Prometheus rules to the Thanos Ruler

platform-operator/controllers/verrazzano/component/common/helm.go, platform-operator/controllers/verrazzano/component/common/helm_test.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol_component.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol_component_test.go
=> VZ-10418 - disassociate cattle-cluster-agent network policy from the VZ Helm chart during upgrade, since that's now in Rancher.

platform-operator/controllers/verrazzano/component/thanos/thanos.go, platform-operator/controllers/verrazzano/component/thanos/thanos_test.go, platform-operator/helm_config/overrides/thanos-values.yaml, platform-operator/thirdparty/charts/thanos/templates/verrazzano/authorizationpolicy.yaml, platform-operator/thirdparty/charts/thanos/templates/verrazzano/networkpolicy.yaml
**Changes**
- add the reload command to the prometheus config reloader so that it picks up rule changes
- alertmanager is outside of the mesh, so send http requests to the service endpoint
- Allow query to access the storeAPI of Thanos Ruler
- Allow Prometheus to scrape metrics from Thanos Ruler
**Testing**
- Install Verrazzano from this branch
- Change a rule and make sure it gets updated in Ruler
- Check the Ruler and Query pod logs to make sure no communication errors are happening
- Check the Ruler and Query consoles to make sure all rules/targets are available
=> Tweak the Ruler integration to fix communication issues

ci/clusterAPI/JenkinsfileCAPI, tests/e2e/clusterapi/capi/helpers.go, tests/e2e/clusterapi/capi/oci.go, tests/e2e/clusterapi/capi/prerequisites.go, tests/e2e/clusterapi/capi/variables.go, tests/e2e/clusterapi/ocne-driver/environment.go
cherry-pick 8967000
cherry-pick 54416d6
- CAPI pipeline changes for K8s 1.26
- OCNE Driver pipeline changes for OCNE metadata configmap check
=> VZ-10467 k8s1 26 pipeline backport

tests/e2e/clusterapi/ocne-driver/environment.go
Similar fix to https://github.com/verrazzano/verrazzano/pull/6673 in the OCNE cluster driver tests.
Fixes an error in test code logic when obtaining versions for OCNE and Verrazzano.
=> OCNE Cluster Driver Tests: fix the check for obtaining OCNE & Verrazzano versions

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go
This PR fixes the info log to show up only if the image is outdated.
=> Fix and reduce the mislelading log noise

go.mod, go.sum, platform-operator/experimental/module-integration/component-handler/installupdate/install_update_handler.go
When a module is reconciling and gets and error, update the module condition with the error message so that it is visible to the user.
This allows you to see errors that happen during lifecycle.  For example:
```
verrazzano-install   cert-manager               2.0.0-1+64b89a57   True    Successfully installed Module `cert-manager` as Helm release `cert-manager/cert-manager`
verrazzano-install   cert-manager-webhook-oci                      False   OCI DNS not configured
verrazzano-install   cluster-api                2.0.0-1+64b89a57   True    Successfully installed Module `cluster-api` as Helm release `verrazzano-capi/cluster-api`
```
=> VZ-10451 write error message to module condition

platform-operator/metricsexporter/metricsexporter_utils.go
Changed the log when component is not found from "Errorf" to "Oncef" to stop spamming
=> VZ-10390: metricsexporter spamming errors in the dev lre

ci/olcne/Jenkinsfile
Five worker nodes did not help too much on stability but increase the time of Create OCNE cluster.
- The time of Create OCNE cluster reduced to 20~25 mins (from 40mins).
- Decrease the probability of "Create OCNE cluster failed with the intermittent yum repo issue".
=> WORKER_NODE_COUNT=2

CHANGES.md, THIRD_PARTY_LICENSES.txt, cluster-operator/controllers/vmc/sync_thanos.go, go.mod, go.sum, pkg/k8s/webhook/webhook.go, pkg/k8s/webhook/webhook_test.go, platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/repos/ol8-olcne15.repo, platform-operator/repos/ol8-olcne17.repo, platform-operator/verrazzano-bom.json
Upgrade to Istio 1.17.2.
Additional updates:
- Updated istio client apis (go.mod) and third party licenses text file
- Upgraded to kubectl 1.26.6 in verrazzano-platform-operator dockerfile.
- Deleting mutating webhook istio-revision-tag-default on preupgrade due to conflicting errors (error code IST0139) with MutatingWebhookConfiguration istio-sidecar-injector on Verrazzano upgrade (upgrading Istio from v1.15.3 to v1.17.2)
```
[2023-07-24T19:11:03.707Z] 2023-07-24T19:11:02.694Z info Failed running istioctl command /usr/local/bin/istioctl install -y -f /verrazzano/platform-operator/helm_config/overrides/istio-cr.yaml -f /tmp/istio-782601928.yaml -f /tmp/istio-1150836344.yaml --set values.pilot.image=ghcr.io/verrazzano/pilot:1.17.2-20230627214838-887ef0a0 --set …
```
=> VZ-9661: Upgrade to Istio 1.17.2

go.mod, go.sum, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/webhook_oci_component.go, platform-operator/controllers/verrazzano/component/clusteragent/cluster_agent_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/console/console_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/nginx/nginx_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/experimental/module-integration/controllers/verrazzano/reconciler.go, platform-operator/internal/operatorinit/run_operator.go, platform-operator/mocks/component_mock.go
Add component GetWatchDescriptors method.  This is needed to allow components to specify the resources that they want to watch, along with the predicate.
Pass the component WatchDescriptors to the controller manager when creating Module controllers
Minor cleanup of Verrazzano reconcile
=> VZ-10451 add component GetWatchDescriptors method

pkg/controller/errors/errors.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/upgrade_component.go
This PR has code fixes to handle Kubernetes API server errors such as "server unavailability due to load" and "too many requests" during installation, pre-install, pre-upgrade, and upgrading of a Verrazzano component.
=> VZ-10226: Handle K8s API errors to reduce log noise 

platform-operator/thirdparty/charts/thanos/templates/verrazzano/authorizationpolicy.yaml
The Thanos Ruler auth policy had a bad namespace for one of the rules, which prevented Thanos Query from accessing the Ruler store API.
=> Fix Thanos Ruler auth policy

platform-operator/controllers/verrazzano/namespacewatch/namespace_watcher.go, platform-operator/controllers/verrazzano/namespacewatch/namespace_watcher_test.go, platform-operator/controllers/verrazzano/namespacewatch/rancher_utils.go
This PR fixes the issue where namespaces are annotated appropriately to the cluster in a multi-cluster scenario. Also refactored the unit tests to reduce code smells.
=> VZ-10120: Append cluster names to the annotation

platform-operator/helm_config/overrides/prometheus-operator-values.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/servicemonitorThanosSidecar.yaml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/absent_rules.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/compaction.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/query.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/receive.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/ruler.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/sidecar.yml, platform-operator/thirdparty/charts/thanos/templates/alert-rule/store_gateway.yml
**Changes**
- Added conditions to if statements for component level alerts to make sure that component has been enabled
- tweaked a few alerts to make sure they were properly firing (or properly inactive)
**Testing**
- Installed on cluster and enabled/disabled components to make sure their alerts were properly turned on and off
=> VZ-10496 Only deploy Prometheus Rules for enabled components

platform-operator/controllers/verrazzano/component/spi/testdata/basicNoneMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/noneCertManagerOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/noneESArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/noneKeycloakInstallArgsStorageOverride.yaml, platform-operator/manifests/profiles/v1alpha1/none.yaml, platform-operator/manifests/profiles/v1beta1/none.yaml
This PR have the changes to remove the dns entries from the None profile because the dns component doesn't have the enabled field and it wipes out the config from base.yaml
=> VZ-10531: None profile bug-fix for error "Invalid OCI DNS configuration"

platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
During VZ install, the OpenSearch component logs `Component opensearch is waiting for statefulset verrazzano-system/vmi-system-es-master to exist` even when OpenSearch is disabled. This log message comes from the call to `DoStatefulSetsExist`, inside OpenSearch's `doesOSExist` function.
This PR changes the OpenSearch's `doesOSExist` function to log only when erroring, modeled similar to several other components' `IsInstalled` checks.
=> VZ-10386: Fix Opensearch IsInstalled() logs

ci/ocne-cluster-driver/Jenkinsfile, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_suite_test.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go
Backport https://github.com/verrazzano/verrazzano/pull/6754.
Introduces a boolean flag to only run 1 of the cluster creation tests in the OCNE cluster driver tests.
=> OCNE Cluster Driver Tests - Single Cluster Creation

platform-operator/controllers/verrazzano/reconcile/controller_test.go, platform-operator/controllers/verrazzano/reconcile/install_test.go, platform-operator/controllers/verrazzano/reconcile/upgrade_test.go
The metricsexporter_utils `Init` function calls other functions that result in a goroutine being spawned. There were multiple unit tests that called the `Init` function. Because Init spawns a goroutine and it was being called multiple times, there was a race condition that caused an intermittent panic.
I fixed the race condition by changing the unit tests to call `metricsexporter.Init` from an `init` function in the test package, and removed all of the other calls to `Init`, so that it will only be called once. I verified the race condition no longer exists with `go test -race`.
=> Fix race condition, metricsexporter.Init() needs to be called once

platform-operator/experimental/module-integration/component-handler/migration/migration.go
Requeue was being returned by accident when so the reconciler did not continue.
=> VZ-10451 fix migration bug

platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/install_component_test.go
While testing new VPO Prometheus alert rules, I discovered a problem with the VPO reconcile error metric. The main problem with the metric was that the component install code was eating errors in most cases. The result was that the error metric was rarely being incremented and reconcile errors were severely undercounted.
To fix the problem, the component install code now bubbles up errors. This allows the reconcile function to check for errors and then increment the error counter.
I tested this by forcing reconcile errors with a bad VZ CR (after deleting the validating webhook) and confirmed that the error metric now accurately reflects the number of reconcile errors.
=> VZ-10547: Fix VPO reconcile error metric

CHANGES.md, platform-operator/helm_config/overrides/kiali-server-values.yaml, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/kiali-server/Chart.yaml, platform-operator/thirdparty/charts/kiali-server/templates/_helpers.tpl, platform-operator/thirdparty/charts/kiali-server/templates/deployment.yaml, platform-operator/thirdparty/charts/kiali-server/templates/oauth.yaml, platform-operator/thirdparty/charts/kiali-server/templates/role-controlplane.yaml, platform-operator/thirdparty/charts/kiali-server/templates/rolebinding.yaml, platform-operator/thirdparty/charts/kiali-server/templates/service.yaml, platform-operator/thirdparty/charts/kiali-server/values.yaml, platform-operator/verrazzano-bom.json
- After copying the Kiali Helm chart 1.66.1 to `kiali-server` folder, restored the custom changes done as part of the following PRs:
- - https://github.com/verrazzano/verrazzano/pull/5132
- - https://github.com/verrazzano/verrazzano/pull/5975
- Added "KIA0501" to `kiali_feature_flags.validations.ignore` override to fix the wrongly reported Istio config error for default PeerAuthentication in istio-system namespace
=> VZ-9693 Update Kiali version to 1.66.1

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
The location of the branding logo images changed in Rancher 2.7.5.  These changes support locating those images in the old and new locations.
=> VZ-10561: support old and new locations for Rancher branding images

CHANGES.md, platform-operator/helm_config/overrides/kiali-server-values.yaml, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/kiali-server/Chart.yaml, platform-operator/thirdparty/charts/kiali-server/templates/_helpers.tpl, platform-operator/thirdparty/charts/kiali-server/templates/deployment.yaml, platform-operator/thirdparty/charts/kiali-server/templates/oauth.yaml, platform-operator/thirdparty/charts/kiali-server/templates/role-controlplane.yaml, platform-operator/thirdparty/charts/kiali-server/templates/rolebinding.yaml, platform-operator/thirdparty/charts/kiali-server/templates/service.yaml, platform-operator/thirdparty/charts/kiali-server/values.yaml, platform-operator/verrazzano-bom.json
This PR is to backport https://github.com/verrazzano/verrazzano/pull/6772 to release-1.6 branch.
=> VZ-9693 Update Kiali version to 1.66.1 (#6772)

.verrazzano-development-version, Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger
This ticket adds an additional stage to the verrazzano job, which checks that the current verrazzano development version does not match a release version. If this check fails on master, or a release branch, it sends a slack message to the release owners, but does not fail the test. This ticket also adds an additional stage to the release job to the upgrade resiliency job. On this job, it is the same logic, as the Verrazzano job, except that the job will not only send a slack message to the release owners if the check fails, the job will also fail outright.
=> VZ-10488 Add Check To VZ Job to See If VZ Helper Was Ran

cluster-operator/controllers/vmc/sync_agent_secret.go, cluster-operator/controllers/vmc/sync_registration_secret.go, cluster-operator/controllers/vmc/sync_registration_secret_test.go, cluster-operator/controllers/vmc/vmc_controller_test.go, platform-operator/controllers/verrazzano/component/common/rancher.go
Updates the source of truth for additional CA certs for the multicluster Rancher proxy requests.
=> Add certificate to the Rancher requests

platform-operator/verrazzano-bom.json
Updated VZ Bom for the Fluentd-kuberenetes-daemonset image tag
=> VZ-10365:Fluentd Daemonset Image Too Large Bom Update (#6786)

cluster-operator/controllers/vmc/vmc_controller.go, cluster-operator/controllers/vmc/vmc_controller_test.go
The VMC reconcile error metric was not being incremented correctly. Any errors during reconciliation were being ignored and the success metric was incremented in all cases.
=> Fix verrazzano-cluster-operator VMC reconcile error metric counting

CHANGES.md
As Kiali v1.66.1 support has been added in VZ 1.6.4 release, updated `CHANGES.md` accordingly.
=> VZ-9693 Update CHANGES.md for Kiali 1.66.1 support

tests/e2e/clusterapi/capi/helpers.go
This fix is specific to the CAPI pipeline
=> VZ-10596: Add component health to display

platform-operator/controllers/verrazzano/component/istio/istio_component.go
**Changes**
- Enable the status update of Istio Reconciled resources through an istioctl override
**Testing**
- Install Verrazzano and make sure Istio resources have statuses
- Install an example app and make sure we can wait for resources to be reconciled by monitoring their statuses
Source for the overrides: https://istio.io/latest/docs/ops/configuration/mesh/config-resource-ready/
=> VZ-3261 Add override to update Istio resources' status

platform-operator/experimental/controllers/integration/cascade/reconciler.go, platform-operator/experimental/controllers/integration/single/reconciler.go, platform-operator/experimental/controllers/module/component-handler/delete/delete_handler.go, platform-operator/experimental/controllers/module/component-handler/installupdate/install_update_handler.go, platform-operator/experimental/controllers/module/component-handler/upgrade/upgrade_handler.go, platform-operator/experimental/controllers/verrazzano/delete.go
1. Delete helm integration release when module is deleted.  Also, create cascaded event  if needed when delete occurs.
2. Optimize module delete to check if module exists before proceeding.
3. Create event for delete and upgrade in the module handlers.
=> VZ-10451 delete helm integration release when module is deleted

cluster-operator/controllers/vmc/vmc_controller.go, cluster-operator/controllers/vmc/vmc_controller_test.go
Backport verrazzano-cluster-operator VMC reconcile error metric fix to release-1.6. See #6790.
=> Fix verrazzano-cluster-operator VMC reconcile error metric counting (release-1.6)

platform-operator/experimental/controllers/module/component-handler/installupdate/install_update_handler.go
Fix the module component handler to always requeue if there is a pre-install error.  This was causing Jaeger install to fail.
=> VZ-1045 pre-install must requeue if error

tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzcapture_test.go, tools/vz/pkg/helpers/vzsanitize.go
This PR introduces changes to aggregate hostnames (DNSNames and IPAddresses) from cert-manager certificates into a map. Additionally, any occurrences of these hostnames are sanitized and replaced with their hashed values
=> VZ-10327: Targetted hostnames should be obfuscated

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/verrazzano/rules/verrazzano-application-operator.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/verrazzano/rules/verrazzano-cluster-operator.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/verrazzano/rules/verrazzano-monitoring-operator.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/verrazzano/rules/verrazzano-platform-operator.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/values.yaml
This PR adds Verrazzano-specific Prometheus rules (alerting and recording). Currently alerting is configured for the following operators: verrazzano-platform-operator, verrazzano-application-operator, verrazzano-cluster-operator, and the verrazzano-monitoring-operator.
The rules are installed via the kube-prometheus-stack helm chart. Rules are only created if the corresponding components are enabled in the Verrazzano custom resource.
I tested rule creation by starting with a "none" profile and then enabled the operators one by one. To test the alerting rules, I scaled down deployments, modified deployments to reference invalid images, and forced resource reconciliations to fail. I observed the pending alerts in Thanos Ruler and verified that alerts are eventually sent to Alertmanager. I …
=> VZ-10547: Add Verrazzano-specific Prometheus rules

release/scripts/get_ocir_scan_results.sh
use --is-latest-only true to cut down the results we are fetching to the latest set.
This brings master scan job from taking 12 hours down to 30 minutes and generating the same results
=> Scan job optimization 

platform-operator/verrazzano-bom.json
Ingress-nginx-controller img tag bom update for release 1.6
=> VZ-10576: ingress-nginx-controller image size too large

platform-operator/controllers/verrazzano/component/authproxy/modules_integration.go, platform-operator/controllers/verrazzano/component/authproxy/modules_integration_test.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/modules_integration.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/modules_integration_test.go, platform-operator/controllers/verrazzano/component/externaldns/modules_integration.go, platform-operator/controllers/verrazzano/component/externaldns/modules_integration_test.go, platform-operator/controllers/verrazzano/component/nginx/modules_integration.go, platform-operator/controllers/verrazzano/component/nginx/modules_integration_test.go
Add GetModuleConfigAsHelmValues impls and unit tests for remaining layer 0 components
- authproxy
- webhook OCI
- external-dns
- nginx
The approach is to map the parts of the Verrazzano CR that are used by each component to an internal (at present unused by the components) Helm value/structure, `verrazzano.module.spec`.  At present these aren't used by the components, but are used to leverage k8s to optimize the reconciles of individual components and only reconcile a module when the parts of the configuration it's interested in have changed.
The mappings do *NOT* generally include the following from the Verrazzano CR:
* The `enabled` flag for the component, as enabled/disabled state is implicit by the existence or deletion of the Module CR
* The `overrides` section for the component, …
=> VZ-10598.  Additional config generation impls for modules integration

tests/e2e/update/a-la-carte/a_la_carte_test.go, tests/e2e/verify-infra/vmi/vmi_test.go
Backport of Fix VMI test ingress check (#6762). This fixes the issue where the vmi suite doesn't run most of the specs.
=> Backport vmi test fix to 1.6

platform-operator/experimental/controllers/verrazzano/reconciler.go
Previous PR put owner UID in annotations instead of labels.  Use labels since we may want to select using this UID in the future.
=> VZ-10702 move VZ owner UID to labels from annotations

application-operator/mcagent/mcagent_cluster_secrets.go, application-operator/mcagent/mcagent_cluster_secrets_test.go, application-operator/mcagent/testdata/no-clusterca-vmc.yaml
=> Fix bug to tolerate the absence of the VMC caSecret field

application-operator/mcagent/mcagent_cluster_secrets.go, application-operator/mcagent/mcagent_cluster_secrets_test.go, application-operator/mcagent/testdata/no-clusterca-vmc.yaml
=> Fix bug to tolerate the absence of the VMC caSecret field (#6856)

tests/e2e/verify-infra/vmi/vmi_test.go, tests/e2e/verify-install/promstack/promstack_test.go
Backport PR: https://github.com/verrazzano/verrazzano/pull/6839
=> Backport VZ-10638: Increase timeout for verify-install/promstack and verify-infra/vmi in alacarte pipeline

platform-operator/experimental/controllers/verrazzano/reconciler.go, platform-operator/experimental/controllers/verrazzano/reconciler_test.go, platform-operator/experimental/controllers/verrazzano/testdata/test_bom.json
Short-circuit reconcile of new controller if an upgrade is required but not yet started.  This is the case where
* The VPO has been updated
* The VZ CR spec has not been set to the version in the updated BOM
An upgrade is deemed required when
* the Spec.Version field is NOT empty and is less than the BOM version
* the Spec.Version field is empty, and the Status.Version is less than the BOM version
=> VZ-10616.  New controller must not reconcile if upgrade is required but not active

tests/e2e/multicluster/multicluster_helper.go
Increase timeout to 10 minutes, it was 5 min.  A test failed because VZ CR took 8 min to become ready after and update.
=> Increase timeout for vz cr readiness check

tests/e2e/multicluster/multicluster_helper.go
Increase the VZ CR ready wait to 10 min since last test failure took 8 min to be ready;.
=> Test fix - bump vzready wait for 1.6

tests/e2e/multicluster/multicluster_helper.go
Increase the VZ CR ready wait to 10 min since last test failure took 8 min to be ready;.
=> Test fix - bump vz ready wait for 1.5

authproxy/Makefile, authproxy/main.go, authproxy/src/proxy/proxy.go, authproxy/src/proxy/proxy_test.go
**Changes**
- Implement a local API proxy that will forward API requests with the leading path `/clusters/local`
**Testing**
- build image and use as a deployment in a Kubernetes cluster
- execute localhost requests on the pod with a bearer token and make sure they get properly forwarded to the API server
=> VZ-10627 Create a local API proxy

platform-operator/thirdparty/charts/rancher/Chart.yaml, platform-operator/thirdparty/charts/rancher/templates/deployment.yaml, platform-operator/thirdparty/charts/rancher/values.yaml
This PR gives users more control over the Rancher pod affinity, topologySpreadConstraints, and nodeSelector configuration in the pod spec. Updates are to the Rancher deployment pod spec, and preserve the existing behavior unless the user specifies overrides in the Verrazzano custom resource.
For affinity settings, the user can override the entire `affinity` section of the pod spec, or override `nodeAffinity`, `podAffinity`, and `podAntiAffinity` individually.
I tested various combinations of overrides. One example:
```
apiVersion: install.verrazzano.io/v1beta1
kind: Verrazzano
metadata:
name: rancher-test
spec:
profile: none
environmentName: default
components:
ingressNGINX:
enabled: true
certManager:
enabled: true
rancher:
enabled: true
overrides:
- values:
nodeAffinity: …
```
=> VZ-10757: Rancher Helm chart enhancement

ci/upgrade-paths/Jenkinsfile, tests/e2e/upgrade/pre-upgrade/verify-upgrade-required/verify_upgrade_required_test.go
Cherry-pick 4900793025ace7a41737eae88022bfa3cff0e05e
Add eventually around getting Verrazzano CR
Wait until webhook pod rolls out.
=> VZ-10752 Make verify-upgrade-required tests more resilient (#5792)

tests/e2e/upgrade/pre-upgrade/verify-upgrade-required/verify_upgrade_required_test.go
Add eventually around getting Verrazzano CR
=> VZ-10752 Make verify-upgrade-required tests more resilient

ci/kind/Jenkinsfile
The console tests intermittently fails in the new-kind-acceptance tests with Grafana DB because the grafana-db tests deletes the grafana pods (and expects the pods to come back up) so the pages become inaccessible temporarily.
Since both the console and grafana-db tests are run parallely, this creates a sort of race condition between the tests. 
The PR is to run the console tests as a separate stage in the pipeline.
=> VZ-10635: Run console test in a separate stage in kind-acceptance test

pkg/helm/helmcli.go, pkg/helm/helmcli_test.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/reconcile/fake_component_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall_test.go, platform-operator/controllers/verrazzano/reconcile/upgrade_test.go, platform-operator/mocks/component_mock.go
Backport to `release-1.6`, fix issues with orphaned resources when the VPO is restarted during uninstall. Particularly Helm-based components can get into a state where the release exists in the cluster but is stuck in an uninstalling state.
See https://github.com/verrazzano/verrazzano/pull/6893 for original PR description.
=> VZ-10667, VZ-10766.   Backport to release-1.6

platform-operator/verrazzano-bom.json
Reduced console image from 926MB to 402MB.
=> Vz-10767: Console Image Too Large

platform-operator/verrazzano-bom.json
Two of the Verrazzano operator components had old versions. Updated so they are all 2.0 now.
=> Fix a couple of versions in BOM

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR removes deprecated VZ versions 1.2, and 1.3 from upgrade tests.
=> VZ-10770: Remove 1.2, 1.3 deprecated vz versions from  upgrade tests

authproxy/main.go, authproxy/src/config/config.go, authproxy/src/config/config_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/authproxy-oidc-config.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml
This PR adds OIDC configuration to Auth Proxy v2. Configuration is stored in a secret and mounted into the Auth Proxy pod. A watcher checks for updates to the secret data and automatically reloads the values when changes are detected.
The configuration currently allows for an issuer URL and a client id. We can extend this as needed.
=> VZ-10788: Add OIDC config to Auth Proxy v2

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR removes deprecated VZ releases v1.2.x and v1.3.x from release-1.4 upgrade jobs.
=> VZ-10770: Remove deprecated VZ releases from release-1.4 upgrade jobs

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-ingress.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/templates/networkpolicy.yaml
**Changes**
- Update the network policy to allow ingress traffic to the new authproxy port
- Add cluster path to the ingress to forward to the new authproxy
**Testing**
- Deploy in cluster and access the API server through the ingress
=> VZ-10626 Add the ingress path for the new authproxy

platform-operator/helm_config/charts/verrazzano-platform-operator/templates/mutatingWebHookConfiguration.yaml
Making the more restrictive to only get triggered by cron jobs that are created by mysql operator, current behavior is any cron job triggers this webhook, and the cron job fails because of some validation inside mysql operator. Currently, jager operator creates a cron job `es-index-cleaner ` to clean the indices periodically, but this tiggers the mysql webhook which shoudn't be the case, this PR fixes that.
=> VZ-10388: Fix mysql webhook config to make it more restrictive.

pkg/helm/helmcli.go, pkg/helm/helmcli_test.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component_test.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/reconcile/fake_component_test.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component.go, platform-operator/controllers/verrazzano/reconcile/uninstall_test.go, platform-operator/controllers/verrazzano/reconcile/upgrade_test.go, platform-operator/mocks/component_mock.go
Backports fix for VZ-10766 to `release-1.5`.  Required some changes in the impl since releases < 1.6.x use the Helm CLI.
=> VZ-10766, VZ-10667.  Backport to release-1.5

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go
This changes fixes a problem where Rancher finalizer will prevent CAPI RBAC resources from deleting before they get recreated during upgrade. This had the effect of the CAPI RBAC resources that got upgraded being permanently removed from the cluster during upgrade.
=> VZ-10404 Delete CAPI RBAC resources before upgrade

CHANGES.md, pkg/k8s/webhook/webhook.go, pkg/k8s/webhook/webhook_test.go, platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/verrazzano-bom.json
Uptake Istio 1.15.7 in release-1.5
Additional updates:
Cherry-picking https://github.com/verrazzano/verrazzano/pull/6391/commits/95d31251a039ced92c6450e65ebb792fb6dc318b to avoid error Deleting mutating webhook istio-revision-tag-default on preupgrade due to conflicting errors (error code IST0139) with MutatingWebhookConfiguration istio-sidecar-injector on Verrazzano upgrade - upgrading Verrazzano v1.4.6 (Istio v1.14.3) to release-1.5 (Istio v1.15.7)
```
{"level":"info","@timestamp":"2023-08-24T18:32:12.847Z","caller":"istio/istioctl.go:128","message":"Failed running istioctl command /usr/local/bin/istioctl install -y -f /verrazzano/platform-operator/helm_config/overrides/istio-cr.yaml -f /tmp/istio-3956802907.yaml -f /tmp/istio-706172992.yaml --set …
```
=> VZ-10583: Uptake Istio 1.15.7 in release-1.5

platform-operator/verrazzano-bom.json
Backport from #6886. Reduced console image from 926MB to 402MB.
=> Vz-10767: Console Image Too Large 

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/install.go, platform-operator/controllers/verrazzano/reconcile/install_test.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
At the end of a VZ reconcile force all VZ component status fields to align `lastReconciledGeneration` with the CR generation.  This behavior is guarded by the `ModuleIntegration` flag in the VPO.
This largely addresses the module integration case where each VZ CR reconcile may not cause an individual module to reconcile (if the Module CR update is a no-op), the VZ CR status for the component should reflect that it was processed.
Each module will still track it's own generation independently.
=> VZ-10809.  Module integration only, force VZ CR status fields to align with last reconciled generation after successful install/update

platform-operator/experimental/controllers/module/component-handler/common/handler_utils.go, platform-operator/experimental/controllers/module/component-handler/delete/delete_handler.go, platform-operator/experimental/controllers/module/component-handler/installupdate/install_update_handler.go, platform-operator/experimental/controllers/module/component-handler/upgrade/upgrade_handler.go
Write deps and errors to ready condition for upgrade and uninstall.  This allows you to see what is going on during module reconcile without looking at the logs.
=> VZ-10544 write deps and errors to Module ready condition for upgrade and uninstall

platform-operator/controllers/verrazzano/component/certmanager/webhookoci/modules_integration.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/modules_integration_test.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/webhook_oci_component.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/webhook_oci_component_test.go
Add PostUpgrade() to copy the OCI auth secret if necessary during upgrade
- Add/update unit tests
- remove some dead code
=> VZ-10809.  Fix cert-manager-webhook-oci upgrade

cluster-operator/controllers/capi/capi_cluster_controller.go, cluster-operator/controllers/capi/capi_cluster_controller_test.go, cluster-operator/internal/operatorinit/run_operator.go, cluster-operator/main.go, platform-operator/verrazzano-bom.json
- Maintained command line arg/feature flag but "reversed" the semantics
- Changed state names for clarity
- pickup kontainer driver via Rancher that labels CAPI cluster instances created by Rancher
=> VZ-10570 Enable by default CAPI cluster controller in cluster operator

platform-operator/controllers/verrazzano/reconcile/controller.go
The code to update component generation was clearing the status version.  Fix it not to pass in the version.
=> VZ-10544 VPI-Module: fix bug where vz status version was being deleted

tests/e2e/jwt/helidon/helidon_example_test.go
Fix JWT e2e test by pointing the correct ApplicationConfiguration that contains the AuthorizationPolicy.
Also, change the order of hitting the Helidon endpoint in JWT e2e.
=> VZ-10704: Fix JWT e2e test by pointing the correct ApplicationConfiguration that contains the AuthorizationPolicy.

tests/e2e/jwt/helidon/helidon_example_test.go
* Fix JWT e2e test
* In JWT e2e, first access the endpoint with token and then without token
=> VZ-10704: Fix JWT e2e test by pointing the correct ApplicationConfig in release 1.5

tests/e2e/jwt/helidon/helidon_example_test.go
* Fix JWT e2e test
* In JWT e2e, first access the endpoint with token and then without token
=> VZ-10704: Fix JWT e2e test by pointing the correct ApplicationConfig in 1.4

tests/e2e/jwt/helidon/helidon_example_test.go
* Fix JWT e2e test
* In JWT e2e, first access the endpoint with token and then without token
=> VZ-10704: Fix JWT e2e test by pointing the correct ApplicationConfig in release-1.6

cluster-operator/controllers/capi/capi_cluster_controller.go, cluster-operator/controllers/capi/capi_cluster_controller_test.go, cluster-operator/controllers/vmc/rancher.go, cluster-operator/controllers/vmc/sync_manifest_secret.go, cluster-operator/controllers/vmc/vmc_controller_test.go, cluster-operator/internal/operatorinit/run_operator.go, cluster-operator/internal/operatorinit/run_operator_test.go, cluster-operator/main.go, pkg/controller/requeue.go, pkg/k8sutil/apply_yaml.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml, platform-operator/verrazzano-bom.json
Backport the two commits to enable the CAPI cluster controller in the cluster operator to process cluster instances and register them with Rancher (when available)
=> VZ-10472, VZ-1057 Backport capi cluster controller to release 1.6

platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/install.go
Fixes the code that sync up the reconciled generation state with the VZ generation post-install/update to honor the `monitorOverrides` flag
* Move `forceSyncComponentReconciledGeneration` to `install.go`
* Move call to inside the `!preUpgrade` check in the install state machine
* Update the `lastReconciledGeneration` for a comp IFF it is in `Ready` state **and** `monitorOverrides` is true
* Removes the modules feature-gate guard to run in all cases
=> VZ-10868.  Respect `monitorOverrides` flag on components for module status updates

authproxy/src/config/config.go, authproxy/src/config/config_test.go, authproxy/src/proxy/proxy.go, pkg/constants/constants.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_test.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/authproxy-oidc-config.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml, tests/e2e/verify-install/keycloak/keycloak_test.go
This PR includes:
1. Adding a new `oidcExternalURL` configuration field to the Auth Proxy v2 secret and Helm chart. The value is the externally accessible OIDC provider URL.
2. Renamed the `oidcIssuerURL` configuration field to `oidcServiceURL`. The value is the in-cluster URL to access the OIDC provider.
3. Implemented Helm overrides in the authproxy component that set `oidcServiceURL` and `oidcExternalURL` appropriately.
4. Refactoring to use a constant for the Verrazzano OIDC system realm.
After installing in a cluster, the OIDC config secret has these values for the URLs:
```
oidcExternalURL: https://keycloak.default.172.18.0.230.nip.io/auth/realms/verrazzano-system
oidcServiceURL: http://keycloak-http.keycloak.svc.cluster.local/auth/realms/verrazzano-system
```
=> VZ-10836: Updates to Auth Proxy v2 configuration

tests/e2e/pkg/kubernetes.go, tests/e2e/pkg/update/updater.go, tests/e2e/upgrade/pre-upgrade/verify-upgrade-required/verify_upgrade_required_test.go
Another PR to convert the tests under `tests/e2e` to use Verrazzano version `v1beta1` when talking to the Kubernetes API server.
This is not necessarily comprehensive, and more PRs can follow if needed. This PR gets rid of the existing `v1alpha1` deprecation logs from the Kind acceptance tests and the dynamic configuration suite, at minimum.
This PR uses the helper functions from `pkg/k8s/verrazzano/talk_to_k8s_api.go` to replace instances of using Verrazzano `v1alpha1` talking to the K8s API server.
=> VZ-6573: Coverting E2E tests to v1beta1

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
This pull request fixes a bug where the WLS cluster resource was not being updated when the component containing a VerrazzanoWeblogicWorkload was updated for a cluster.
E2E test will be updated in a followup pull request.
=> VZ-10856: Fix bug where WLS cluster resource was not being updated

platform-operator/controllers/secrets/verrazzano_tls_secret.go
Initialize the logger in the new `reconcileVerrazzanoCABundleCopies` to avoid an NPE under some circumstances.
=> VZ-10529.  Fix NPE in secrets controller 

platform-operator/controllers/secrets/verrazzano_tls_secret.go
- Initialize the logger in the new reconcileVerrazzanoCABundleCopies to avoid an NPE
=> VZ-10529.  Backport to release-1.6

platform-operator/experimental/controllers/verrazzano/overrides.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
Update the new controller to use the user overrides for a component directly from the un-merged "actual" Verrazzano CR.  The
=> VZ-10868.  Use the actual CR values to compute user module overrides 

platform-operator/controllers/verrazzano/component/thanos/module_integration.go, platform-operator/controllers/verrazzano/component/thanos/module_integration_test.go
This changes adds dns, nginx, and environment fields to the the Thanos valuesConfig. This will cause the Thanos module to do an update when any of those VZ CR fields are updated so the Thanos ingress can get properly updated.
=> VZ-10802 add DNS field to the Thanos module values

pkg/helm/helmcli.go, platform-operator/controllers/verrazzano/component/mysql/mysql.go, tests/e2e/update/overrides/overrides_helper_test.go, tests/e2e/update/overrides/overrides_test.go
Ensure that the `tls.useSelfSigned=true` Helm value is set during both install and updates; throttle Helm error messages and display the error message as well.
Also disables for the time being the e2e tests that validate `monitorChanges=false` behavior, to be re-evaluated later in the Epic.
=> VZ-10868.  Fix mysql update with Modules, throttle/improve Helm error messages

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update Verrazzano to use WKO 4.1.2 and WME 2.1.5.
=> WebLogic Kubernetes Operator 4.1.2 and WebLogic Monitoring Exporter 2.1.5

ci/chaos/Jenkinsfile
This change repairs the upgrade resiliency tests so that they test what they say they are supposed to. Currently, 4 of the 6 tests perform the upgrade before they are supposed to and thus the resiliency aspect is not tested. This is because the test was modified to call vz install instead of applying the operator.yaml.
=> Fix upgrade resiliency tests

platform-operator/controllers/verrazzano/component/argocd/module_integration.go, platform-operator/controllers/verrazzano/component/authproxy/module_integration.go, platform-operator/controllers/verrazzano/component/clusteragent/module_integration.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/jaeger/operator/module_integration.go, platform-operator/controllers/verrazzano/component/keycloak/module_integration.go, platform-operator/controllers/verrazzano/component/mysql/mysql_component.go, platform-operator/controllers/verrazzano/component/mysqloperator/mysqloperator_component.go, platform-operator/controllers/verrazzano/component/networkpolicies/module_integration.go, platform-operator/controllers/verrazzano/component/thanos/module_integration.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component.go, platform-operator/experimental/controllers/verrazzano/custom/namespace.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
Fix a-la-cart for VPO-modules
1. Istio post-install and post-upgrade must call RestartComponents
2. Istio post-install and post-upgrade must add istio inject label to certain namespaces.
3. Use common CreateNamespace function
=> VZ-10706 fix VPO-module a-la-cart tests

platform-operator/controllers/verrazzano/component/console/console_component.go, platform-operator/verrazzano-bom.json
update image from  https://github.com/verrazzano/console/pull/285, also fixes `ImagePullSecretKeyname` to use the default. global pull secret as the template does not have `imagePullSecrets` of its own
=> VZ-10903: update console image and fix imagePullSecrets

platform-operator/experimental/controllers/module/component-handler/migration/migration.go, platform-operator/experimental/controllers/verrazzano/module.go
Fix VMO migration where VMO.IsEnabled returns false for 1.5 -> 1.6 upgrade, even though VMO is installed.
=> VZ-10706 fix VMO migration

CHANGES.md, platform-operator/thirdparty/charts/thanos/Chart.yaml, platform-operator/verrazzano-bom.json
Uptake Thanos v032.2. This new version of Thanos includes support for OKE Workload Identities.
This does not require a newer version of the Thanos Helm chart but we should update the chart in a future PR.
=> VZ-10125: Uptake Thanos v0.32.2

CHANGES.md, platform-operator/thirdparty/charts/thanos/Chart.yaml, platform-operator/verrazzano-bom.json
Backport of Thanos v0.32.2 uptake to release-1.6 branch. See #7019 for details.
=> VZ-10125: Uptake Thanos v0.32.2 (release-1.6)

cluster-operator/controllers/vmc/argocd.go, cluster-operator/controllers/vmc/argocd_test.go
In this PR, additional labels to to a managed cluster can be added to an ArgoCD Secret and not be overwritten. A unit test related to this PR is also committed and it has clean runs in the pipeline.
=> Fix to Add Additional Labels To Managed Cluster ArgoCD Secret

platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
Revert the Istio post-install and post-upgrade component restart logic to what is was before modules were introduced.
=> VZ-10706 istio restart - revert non-module component restart logic

.gitignore, Jenkinsfile, ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go, tests/e2e/config/scripts/create-github-token-secret.sh, tests/e2e/pkg/kubernetes.go
Fixes:
- VZ-10679 Cluster API version overrides not working correctly. Downgrading and upgrading CAPI providers via version overrides will start working again. (reverting #7011)
- VZ-10753 rate limit for github api when clusterAPI component enabled with version overrides
- VZ-10443 Automated test for OCNE version configurability
=> VZ-10679 Cluster API version overrides not working correctly.

application-operator/controllers/wlsworkload/weblogicworkload_controller.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, platform-operator/helm_config/charts/verrazzano-application-operator/templates/clusterrole.yaml
This PR is to update the WebLogic Workload Controller to support a new feature for WebLogic Kubernetes Operator 4.1 in relation to Domain on PV type WebLogic Domains.
=> VZ-10780 Update to WebLogic Workload Controller to support WKO 4.1 feature initializeDomainOnPV

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_webhook.go, cluster-operator/controllers/capi/capi_cluster_controller.go, cluster-operator/controllers/capi/capi_cluster_controller_test.go, cluster-operator/controllers/capi/rancher.go, cluster-operator/controllers/capi/verrazzano.go, cluster-operator/controllers/vmc/sync_registration_secret.go, cluster-operator/internal/operatorinit/run_operator.go, pkg/k8sutil/apply_yaml.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml
- Refactored CAPI cluster controller to process either Rancher or VZ registration
- Created VZ registration code
- Some modifications to existing VMC/MC code
=> VZ-10925 Register CAPI clusters with Verrazzano when Rancher is not enabled/installed

ci/kind/Jenkinsfile, ci/scripts/run_console_tests.sh, platform-operator/controllers/verrazzano/component/common/namespace.go, platform-operator/controllers/verrazzano/component/dex/dex.go, platform-operator/controllers/verrazzano/component/dex/dex_component.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol_component_test.go, platform-operator/controllers/verrazzano/component/networkpolicies/netpol_values.go, platform-operator/helm_config/charts/verrazzano-network-policies/templates/thirdparty-networkpolicy.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/values.yaml, platform-operator/helm_config/overrides/dex-values.yaml, platform-operator/internal/k8s/namespace/namespace.go, platform-operator/internal/k8s/namespace/namespace_test.go, tests/e2e/security/netpol/network_policy_test.go, tests/e2e/verify-install/security/pod_security_test.go
This change enables istio pod injection in verrazzano-auth namespace where Dex is installed. It defines the network policy for Dex, adds required tests. 
There are few additional changes done for pipeline and e2e tests.
1. The console tests, which are written with Keycloak as the ODIC provider is disabled from Kind AT when Dex is enabled. Otherwise, console tests fail after long time and the job aborts with timeout.This change will be removed once the tests are fixed. The intention is to run other tests in Kind AT without the job being aborted as the console tests run forever 
2. This change enables pod security test for namespace verrazzano-auth.
=> VZ-10917: Network policy for Dex

platform-operator/experimental/controllers/module/component-handler/common/vzcomponent_status.go, platform-operator/experimental/controllers/verrazzano/module.go, platform-operator/experimental/controllers/verrazzano/overrides.go, platform-operator/experimental/controllers/verrazzano/reconciler.go, platform-operator/experimental/controllers/verrazzano/vzstatus.go
Modules reconciler change to fix VZ reconciing status on updates.  Sets the status for the VZ CR to Reconciling/InstallStarted when
* the module Spec changes on `CreateOrUpdate`
* any Secret or Configmap overrides that cause a change to the target copy in `verrazzano-install`
* Remove the code in the module handlers that tweaks the VZ CR State
Reconciling completes when the `postWork` finishes successfully.
=> VZ-10807. Fix CAPI overrides tests with modules

platform-operator/experimental/controllers/module/component-handler/upgrade/upgrade_handler.go
Fix module shim "IsWorkNeeded" method for upgrade.  Compare the spec version to the status version.  This bug was causing the VZ to never reach upgrade complete
=> VZ-10706 VPO-modules fix 1.4 upgrade

tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go
Update the CAPI overrides e2e test to wait until the `lastReconciledGeneration` for the component matches the VZ CR generation.  This is to fix the race condition when modules are enabled where the update finishes before the test can get into the wait for `Reconciling` status, and blocks there until timeout.
Also tried to improve error reporting on failure.
=> VZ-10807.  CAPI overrides test update

ci/uninstall/JenkinsfileUninstallSuite
Parameterize the install loop count on the Jenkins wrapper for the uninstall resiliency, and set the default to 3 to cut down on execution times.  Typically any issues will be uncovered within that number of runs.
=> Parameterize Uninstall resiliency suite loop count, set default to 3 loops

platform-operator/verrazzano-bom.json
This change backports https://github.com/verrazzano/verrazzano/pull/7072 and https://github.com/verrazzano/verrazzano/pull/7077 to release-1.6
=> VZ-10568, VZ-10275: Update ArgoCD, Redis and Keycloak images in release-1.6

platform-operator/verrazzano-bom.json
This change -
1. Refreshes rancher-fleet, rancher-fleet-agent and rancher-gitjob images in release-1.6
2. Backports https://github.com/verrazzano/verrazzano/pull/7077 and https://github.com/verrazzano/verrazzano/pull/7072 to release-1.6
=> VZ-10568, VZ-10275: Update ArgoCD, Redis, Keycloak and Rancher additional images in release-1.5

ci/uninstall/JenkinsfileUninstallTest, tools/scripts/k8s-dump-cluster.sh
Modify the cluster snapshot to add `roles` to the full cluster dump, and format the `helm ls` json output.
Clean up and fix the cluster dumps in the pipeline.  Test and install/uninstall snapshots are captured in `test-cluster-snapshots` in the build artifacts.
=> Uninstall resiliency pipeline cluster dump fixes

ci/uninstall/JenkinsfileUninstallSuite
Add params to uninstall resiliency suite for DUMP_K8S_CLUSTER_ON_SUCCESS and CAPTURE_FULL_CLUSTER to pass down into each pipeline run spawned.
=> Add params to uninstall resiliency suite for cluster dump options

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
This:
- fixes issue where one or more null result entries are included for Trivy JSON Results, these will not prevent CVE results from being seen (original issue)
- Will skip converting Trivy JSON to csv if there are no Results at all
- Added param to allow user branches to test the scan without uploading it TEST_RUN, defaults to that for user branches, master/release-* ignore that and always upload
=> vz-11038 Some Trivy JSON not handled correctly when converting to CSV

platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager_test.go, platform-operator/experimental/controllers/module/component-handler/delete/delete_handler.go
- Have Cert-Manager component clean up leader-election resources in kube-system on uninstall and wait for them to be deleted successfully
- Have the new delete handler use Exists() instead of IsInstalled() as trigger to do delete work
=> VZ-10805.  Fix CM on uninstall with modules enabled

platform-operator/internal/config/config_test.go
This adds a check to the VPO Config unit test to make sure that modules are on by default.
=> Ensure module integration is on by default

platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager.go
Log CM cleanup errors using throttled logger and return RetryableError 
- also convert resource-delete verification message to debug
=> VZ-10805.  Log CM cleanup errors using throttled logger

ci/upgrade-paths/Jenkinsfile
Backports https://github.com/verrazzano/verrazzano/pull/7081 to release-1.5
=> VZ-11022: Fix upgrade-paths pipeline to capture cluster dump on success in release-1.5

ci/upgrade-paths/Jenkinsfile
Backports https://github.com/verrazzano/verrazzano/pull/7081 to release-1.6
=> VZ-11022: Fix upgrade-paths pipeline to capture cluster dump on success in release-1.6

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, platform-operator/Dockerfile, platform-operator/Makefile, platform-operator/experimental/controllers/module/component-handler/common/handler_utils.go, platform-operator/experimental/controllers/verrazzano/module.go, platform-operator/internal/config/config.go, platform-operator/internal/config/config_test.go, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json, tools/scripts/generate_catalog.sh
This change changes the internal modules versions in the catalog to match the Verrazzano version. The catalog is generated  at build time similar to the how the bom is generated. This change also moved the catalog into the manifests directory.
=> VZ-10840 change internal module versions to match Verrazzano version

pkg/k8s/resource/resource.go, platform-operator/experimental/controllers/verrazzano/custom/namespace.go
Remove finalizer when deleting namespace.  Rancher adds finalizers which prevents namespaces from being deleted.
=> VZ-1105 remove finalizer when deleting namespace

go.sum, platform-operator/controllers/verrazzano/component/common/opensearch_operator.go, platform-operator/controllers/verrazzano/component/common/opensearch_operator_test.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component_test.go, platform-operator/thirdparty/charts/opensearch-operator/templates/verrazzano/opensearch-securityconfig-secret.yaml, platform-operator/thirdparty/manifests/opensearch-operator/opensearch-securityconfig.yaml
Config.yml and internal_users.yml need to be strategically merged during the upgrade and pre-install. We need this kind of strategic merge because helm merge doesn't take care of our use case and will simply override the changes done by the user.
=> VZ-9535: Merge config.yml and internal_users.yml from the secret and the helm config.

platform-operator/controllers/verrazzano/component/authproxy/authproxy.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_values.go, platform-operator/controllers/verrazzano/component/authproxy/module_integration.go, platform-operator/controllers/verrazzano/component/authproxy/module_integration_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml
Remove DNS config mappings from authproxy in favor of Module watches
- refactor Promethes Operator component name/namespace into common package to avoid import cycles
=> VZ-11085.  Remove DNS config mappings from authproxy in favor of Module watches

platform-operator/experimental/controllers/verrazzano/reconciler.go, platform-operator/internal/operatorinit/run_operator.go
Set max concurrent module controllers to 50.  We currently have 40+ components and more are being added.
Add comments.
=> VZ-11051 set max concurrent module controllers to 50

ci/cron/JenkinsfileBackend
The backend tests are supposed to run once a week.
The cron is supposed to be a fallback in case the URL trigger misses triggering there weekly, and should also only be weekly
=> Cron for backend tests only should be firing off weekly

CHANGES.md, platform-operator/thirdparty/charts/rancher/Chart.yaml, platform-operator/thirdparty/charts/rancher/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-10861: Back port uptake of Rancher 2.7.6 to release-1.6

Jenkinsfile, ci/private-registry/Jenkinsfile
This PR contains the changes to main verrazzano jenkinsfile and private-registry Jenkinsfile to upgrade the jenkins label to use the label for JAO
=> VZ-8815: Migrate vz jenkins and private-registry jenkins jobs  to JAO

platform-operator/verrazzano-bom.json
=> VZ-11084: Back port uptake of new gitjob image to release-1.6

CHANGES.md, platform-operator/verrazzano-bom.json
Note that this image is part of the Auth Proxy component so there is no separate module catalog entry, and there is no Helm chart (this is part of the Auth Proxy Helm chart).
=> VZ-11124: Uptake NGINX Prometheus Exporter v0.11.0

platform-operator/controllers/verrazzano/component/authproxy/module_integration.go, platform-operator/controllers/verrazzano/component/certmanager/certmanager/module_integration.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/module_integration.go, platform-operator/controllers/verrazzano/component/certmanager/webhookoci/module_integration.go, platform-operator/controllers/verrazzano/component/fluentd/module_integration.go, platform-operator/controllers/verrazzano/component/fluentd/module_integration_test.go, platform-operator/controllers/verrazzano/component/grafana/module_integration.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/module_integration.go, platform-operator/controllers/verrazzano/component/istio/module_integration_test.go, platform-operator/controllers/verrazzano/component/jaeger/operator/module_integration.go, platform-operator/controllers/verrazzano/component/mysql/module_integration.go, platform-operator/controllers/verrazzano/component/nginx/module_integration.go, platform-operator/controllers/verrazzano/component/opensearch/module_integration.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/module_integration.go, platform-operator/controllers/verrazzano/component/rancher/module_integration.go
Some general cleanup of modules config mappings
- Return nil from `GetModuleConfigAsHelmValues` from components if derived config is empty
- Map Istio, MySQL config more directly to v1alpha1 API
- add more unit tests/cases around the modules integration code where needed
=> VZ-11085.  Clean up module integration

application-operator/mcagent/mcagent.go, application-operator/mcagent/mcagent_syncer.go, application-operator/mcagent/mcagent_test.go
Follow-up to https://github.com/verrazzano/verrazzano/pull/7116.
Addresses the previous comments made:
- Initialize the `Syncer` to contain a `DiscoveryClient`
- Account for the case that there are 0 `verrazzanos` on the workload cluster
=> VZ-11008: Follow-up to cleanup VMC extensions for K8s and VZ versions

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7141 to release-1.5
=> VZ-10841: Update Keycloak image with bouncy castle libraries from v1.74, release-1.5

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7141 to release-1.6
=> VZ-10841: Update Keycloak image with bouncy castle libraries from v1.74, release-1.6

platform-operator/helm_config/overrides/prometheus-pushgateway-values.yaml
In the previous version of the Prometheus Pushgateway Helm chart, the default behavior was to add a release label to all resources. In this latest version of the chart, that behavior changed and the release label is no longer added. In order to get the Prometheus Operator to pick up the ServiceMonitor, I had added a `release: prometheus-operator` label to the ServiceMonitor (using overrides).
This PR changes the label to `release: prometheus-pushgateway` to replicate the previous behavior. The selector in the Prometheus CR is configured to pick up ServiceMonitors with that release label value as well.
=> Change ServiceMonitor release label

pkg/controller/errors/errors.go, platform-operator/controllers/verrazzano/controller/reconciler.go, platform-operator/metricsexporter/metricsexporter.go
This PR wires in metrics to the Verrazzano controller. These are the same metric/name/titles used in the legacy controller. There are also changes related to logging of some errors.
=> First pass of adding metrics to Verrazzano controller

platform-operator/controllers/verrazzano/component/opensearchoperator/module_integration.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component_test.go, tests/e2e/update/env-dns-cm/env_dns_cert_update_test.go
Updates the opensearchOperator component to address dynamic changes to DNS
- change CertManager dependencies to ClusterIssuer (which transitively depends on CertManager)
- Change watches for opensearchOperator to trigger on ClusterIssuer install/update, in case we are using a customer-managed Cert-Manager
- Fix e2e test to check for the VZ self-signed issuer to be cleaned up
=> VZ-10825.  Opensearch operator dynamic config fixes

ci/ha/JenkinsfileRollingUpgrade
Updates the default Kubernetes version in HA pipeline to v1.25.4. The pipeline attempts to upgrade the Kubernetes version, so the default version is not set to the highest supported one.
=> Fix the default Kubernetes version in HA pipeline

ci/JenkinsfilePeriodicTests
Turn off OCI Integration test, OKE version no longer supported
=> Turn off OCI Integration test, OKE version no longer supported

CHANGES.md, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component.go, platform-operator/controllers/verrazzano/component/prometheus/nodeexporter/nodeexporter_component_test.go, platform-operator/helm_config/overrides/prometheus-node-exporter-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/Chart.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/README.md, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/NOTES.txt, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/_helpers.tpl, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/clusterrole.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/clusterrolebinding.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/daemonset.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/endpoints.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/extra-manifests.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/networkpolicy.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/podmonitor.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/psp-clusterrole.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/psp.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/rbac-configmap.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/service.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/serviceaccount.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/servicemonitor.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/templates/verticalpodautoscaler.yaml, platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/values.yaml, platform-operator/verrazzano-bom.json, tests/e2e/security/netpol/network_policy_test.go
This PR includes the following:
1. Upgrades the Prometheus Node Exporter image to v1.6.1. Both the BOM and modules catalog have been updated.
2. Upgrades the Promethues Node Exporter Helm chart to v4.32.1.
3. A component implementation of PreUpgrade for Node Exporter that removes the previously installed daemonset. The new Helm chart is incompatible with previous versions and requires the daemonset to be removed, otherwise the upgrade fails because it tries to patch an immutable field in the daemonset.
I tested in a local cluster, both install and an upgrade from 1.6.7 and verified that Node Exporter metrics are scraped correctly.
=> VZ-11142: Uptake Prometheus Node Exporter v1.6.1

ci/oke-ocidns/Jenkinsfile
Disable Bob's Books and Socks examples in OCI DNS backend tests due to intermittent failures
=> VZ-11196. Disable intermittently failing OCI DNS backend example tests

go.mod, go.sum
Upgrade Gabs library to latest release (2.7.0).
=> VZ-11185: Upgrade Gabs library

ci/ha/JenkinsfileRollingUpgrade
Backport https://github.com/verrazzano/verrazzano/pull/7204 to release-1.6
=> Fix the default Kubernetes version in HA pipeline, release-1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
This is needed so that the Prometheus Operator component will pick up the change and get upgraded
=> VZ-11175 update the prometheus operator version

platform-operator/controllers/verrazzano/controller/module.go
If a component monitorChanges field is false then don't update the Module CR.
=> VZ-11168 handle monitorChanges field

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7230 to release-1.6
=> VZ-11100: Update Keycloak image built with validation that redirect URI is http(s), release-1.6

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7230 to release-1.5
=> VZ-11100: Update Keycloak image built with validation that redirect URI is http(s), release-1.5

platform-operator/verrazzano-bom.json, release/scripts/check_image_tags.sh
This PR adds Jaeger image tag checking to the compliance script. All of the Jaeger images (except for the jaeger-operator image) in the BOM should have the same tag. This check will fail the compliance checks if there is a tag mismatch.
=> Add Jaeger images to image tag compliance check

ci/upgrade-paths/Jenkinsfile, tests/e2e/upgrade/pre-upgrade/verify-upgrade-required/verify_upgrade_required_test.go
This PR updates the "verify upgrade required" test in the upgrade paths pipeline to remove an obsolete version check that would fail intermittently. Since we no longer test upgrades from version 1.3.x, the version check is no longer necessary.
I also re-enabled the test in the Jenkinsfile.
=> VZ-11186: Update "verify upgrade required" test

cluster-operator/controllers/quickcreate/controller/controller.go, cluster-operator/controllers/quickcreate/ociocne/ociocne_controller.go, cluster-operator/controllers/quickcreate/oke/oke_controller.go
Follow up PR to ensure quickcreate namespaces are always the same as the parent object
=> Force quickcreate namespaces

ci/lre/Jenkinsfile
These commands use the Rancher proxy to generate a new kubeconfig for each run. This avoids having a stale kubeconfig.
=> Update the LRE Jenkisfile to regenerate the Kubeconfig

go.mod, go.sum
We have been using the Prometheus Operator image version 0.64.1 for some time, but the go.mod was still using the older 0.59.1 version of the code to get types for things like ServiceMonitors. This PR upgrades the go.mod version to use the newer version of the library.
=> Upgrade prometheus-operator lib version in go.mod

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go
On applying a VZ CR with clusterAPI URL overrides, this will correctly update:
- the clusterctl yaml in VPO pod
- the k8s deployments in `verrazzano-capi` namespace to run the correct images
```
apiVersion: install.verrazzano.io/v1beta1
kind: Verrazzano
metadata:
name: my-verrazzano
spec:
profile: dev
components:
clusterAPI:
enabled: true
overrides:
- values:
defaultProviders:
ocneControlPlane:
url: https://github.com/verrazzano/cluster-api-provider-ocne/releases/v1.6.1/control-plane-components.yaml
ocneBootstrap:
url: https://github.com/verrazzano/cluster-api-provider-ocne/releases/v1.6.1/bootstrap-components.yaml
core:
url: https://github.com/verrazzano/cluster-api/releases/v1.4.2/core-components.yaml
oci:
url: https://github.com/oracle/cluster-api-provider-oci/releases/v0.11.1/infrastru …
```
=> VZ-11250: Cluster API URL overrides not working

platform-operator/controllers/verrazzano/controller/reconciler.go
For upgrades within the `master` branch, the `isUpgradeRequired()` check in the new controller is returning a false-negative allowing the controller to reconcile and set the new BOM version in the status field.    This only affects upgrades between VPO versions within the master branch where the `pre-release` and `build` fields are set.
This is happening because the `IsLessThan()` method is checking `CompareTo() < 0`, and when the `m.m.p` versions are equal but the `pre-release` and/or `build` fields are not equal, `CompareTo` always returns a value > 0.
The `CheckUpgradeRequired` code in the webhook validator uses `bomVersion.IsGreatherThan(installedVersion)`, so using that for the status field comparison to the BOM value fixes it.  `IsGreaterThan` will return `true` if the `m.m.p` …
=> VZ-11248.  VZ controller incorrectly updates VZ status version when build/pre-release fields are set

ci/oke-ocidns/Jenkinsfile, tests/e2e/examples/bobsbooks/bobs_books_test.go
Bob's book test has been failing to get this logging index intermittently. The log fields are too narrow and only match with one specific log if it happens to appear. Widening the index pattern should provide the same check without failing intermittently.
=> VZ-11196 Remove the narrow fields fromt the Opensearch index pattern

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Removed temporary work around that was always returning "true" for IsIstioAPI.  The fix required for this function to work was to add an annotation in the Kiali deployment.  That annotation is already in master, release-1.6 and release-1.7 branches.
=> VZ-11003: Uptake Kiali image with original logic of IsIstioAPI restored

tools/vz/cmd/helpers/vpo.go, tools/vz/cmd/helpers/vpo_test.go, tools/vz/cmd/install/install.go, tools/vz/cmd/upgrade/upgrade.go
e.g. of where this is an issue - if you upgrade VZ but specify an invalid version, the upgrade doesn't take place because new operator cannot be downloaded, but the existing VPO and webhook are deleted anyway, which leaves the cluster in a state that is undesirable.
=> VZ-10571 - VZ CLI should delete existing VPO deployment only after the new one has been successfully located.

application-operator/controllers/metricstrait/metricstrait_controller_test.go, application-operator/controllers/metricstrait/workloads.go
=> VZ-10800: Avoid restart of OAM application pods while adding metrics labels/annotations

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/controllers/module/component-handler/delete/delete_handler.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/common/vmi.go
First pass at fixing uninstall when VZ CR is deleted during install.  
1. Handle general case of CRD not installed, just ignore that error.   
2. Ignore CAPI not found error 
3. Fix webhook to allow update to CR during delete.  This was preventing uninstall from continuing.
=> VZ-11269 fix uninstall when VZ CR is deleted during install

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/controllers/module/component-handler/delete/delete_handler.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/common/vmi.go
cherry-pick of https://github.com/verrazzano/verrazzano/commit/8d33093a913f60a2c5dd064293a911d2231bddd2
First pass at fixing uninstall when VZ CR is deleted during install.
Handle general case of CRD not installed, just ignore that error.
Ignore CAPI not found error
Fix webhook to allow update to CR during delete. This was preventing uninstall from continuing.
=> VZ-11269 fix uninstall when VZ CR is deleted during install 

authproxy/internal/httputil/httputil.go, authproxy/internal/httputil/httputil_test.go, authproxy/internal/testutil/testauth/authenticator.go, authproxy/src/apiserver/apiserver.go, authproxy/src/auth/auth.go, authproxy/src/auth/auth_test.go, authproxy/src/auth/login.go, authproxy/src/auth/login_test.go, authproxy/src/auth/token.go, authproxy/src/auth/token_test.go, authproxy/src/auth/types.go, authproxy/src/cookie/cookie.go, authproxy/src/cookie/cookie_test.go, authproxy/src/proxy/proxy.go, authproxy/src/proxy/proxy_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml
This PR includes the following changes to Auth Proxy v2:
- Implement oauth callback handler
- Validates state
- Exchanges the oauth one-time use code for a token and validates the token
- Add HTTP client support for proxies (facilitates local debugging)
- Improved HTTP client management
- We were creating a retryable client but it wasn't actually being used
- Also consolidated creation of HTTP clients to eliminate recreating them unnecessarily
- Lots more unit tests
=> Auth Proxy v2 enhancements

cluster-operator/controllers/vmc/update_status.go, cluster-operator/controllers/vmc/update_status_test.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml
Updates the `status.kubernetes.version` field of the VMC in the case that the VMC represents a ClusterAPI cluster where Verrazzano is not installed.
Before this PR, the verrazzano cluster agent already updates this field of the VMC, but only for workload clusters with Verrazzano installed. This PR is being made since it is possible to retrieve the K8s version from the CAPI CRs even without VZ.
=> VZ-11247: Update VMC status K8s version for CAPI clusters without VZ

platform-operator/controllers/verrazzano/component/argocd/argocd_postinstall.go, platform-operator/controllers/verrazzano/component/argocd/module_integration.go
Fixes ArgoCD to work with Let's Encrypt Staging certs. 
Also verified (manually)
- Switching back and forth between self-signed and LE staging configurations
- Renewing the self-signed CA cert is picked up by Argo and other services
- Let's encrypt production works with Argo
=> VZ-9709.  Fix ArgoCD private CA integration

platform-operator/controllers/verrazzano/component/fluentoperator/fluentoperator_component.go, platform-operator/internal/config/config.go, tests/e2e/config/scripts/v1alpha1/install-vz-prod-kind-upgrade.yaml
Apply fluent-bit crds as part of fluent-operator PreUpgrade to fix a bug with operator where helm upgrade fails to update CRDs since v2.2.0.
=> VZ-11288: apply fluent-bit crds as part of preUpgrade

platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
Change the order in Opensearch statefulsetReady function to make sure OS health API gets called only once all replicas are available for Opensearch.
=> change the order of check for Opensearch ready state

platform-operator/controllers/verrazzano/component/opensearch/opensearch.go, platform-operator/controllers/verrazzano/component/opensearchoperator/pvc.go
* change the order of check for Opensearch ready state
* add retry to check OS health
=> change the order of check for Opensearch ready state (#7360)

pkg/k8s/ready/deployment_ready.go
=> VZ-11241 - Add a log message to indicate when deployment.spec.replicas is 0 during install/upgrade

platform-operator/controllers/verrazzano/component/argocd/module_integration.go
Add module update watches for NGINX, `clusterIssuer` to `argoCD`, fixes dynamic config tests.
=> VZ-9709.  Fix DNS updates for ArgoCD

pkg/k8s/ready/deployment_ready.go
=> VZ-11241 - Add a log message to indicate when deployment.spec.replicas is 0 during install/upgrade (#7356)

tests/e2e/update/opensearch/opensearch_update.go
Fix opensearch update e2e by appending the node pool instead of just adding.
=> backport fx to 1.7: Fix opensearch update e2e

tests/e2e/multicluster/verify-cluster-sync/cluster_sync_test.go
This is a forward port of the fixes to the release-1.7 branch.  Although less common in the master branch there are some instances where the Rancher HTTP retry mechanism extends the test duration past the configured timeout.
=> VZ-11236 modify retry mechanism to accommodate test timeouts

ci/JenkinsfileTestTrigger, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
release-1.7 backports of #7395 and #7406
=> VZ-11204: VZ-11304: uptake Coherence 3.3.1 and run coherence workload tests by default

ci/upgrade-paths/Jenkinsfile, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, tests/e2e/multicluster/verify-cluster-sync/cluster_sync_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go, tools/scripts/k8s-dump-cluster.sh
- delete RKE2 feature during upgrades
- Update retry mechanism during testing to accommodate test timeouts
- Disable consistently failing rancher url test for the time being
=> VZ-11362, VZ-11418 add code to delete RKE2 feature pre upgrade and some test updates

go.mod, go.sum, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates NGINX, external-dns and oam-kubernetes-runtime images built with Go v1.20.10, by the following PRs
1. https://github.com/verrazzano/ingress-nginx/pull/13
2. https://github.com/verrazzano/external-dns/pull/3
3. https://github.com/verrazzano/oam-kubernetes-runtime/pull/6
=> VZ-11376: Update NGINX, external-dns and oam-kubernetes-runtime images built with Go v1.20.10

go.mod, go.sum, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates NGINX, external-dns and oam-kubernetes-runtime images in release-1.7, built with Go v1.20.10 in the PRs
1. https://github.com/verrazzano/ingress-nginx/pull/13
2. https://github.com/verrazzano/external-dns/pull/3
3. https://github.com/verrazzano/oam-kubernetes-runtime/pull/6
=> VZ-11376: Update NGINX, external-dns and oam-kubernetes-runtime images built with Go v1.20.10, in release-1.7

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates cert-manager and node-exporter images, built with Go v1.20.10
=> VZ-11376: Update cert-manager and node-exporter images, built with Go v1.20.10

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates cert-manager and node-exporter images, built with Go v1.20.10, in release-1.7
=> VZ-11376: Update cert-manager and node-exporter images built with Go v1.20.10, release-1.7

ci/JenkinsfilePeriodicTests, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR contains changes that remove redundant Jenkins jobs that are not used by Verrazzano customers.
=> VZ-11395: Remove redundant Jenkins jobs

platform-operator/Dockerfile
Distroless base includes glibc and openssl but is smaller and has a reduced CVE surface area compared to OL 8-slim. The VPO does require a shell and several utilities to function, including curl, and their associated shared libs.
=> VZ-11427: Update VPO Dockerfile to use distroless base image

platform-operator/verrazzano-bom.json
This uptakes the new VMO image that is based on the distroless static image.
=> VZ-11454: Uptake distroless-based VMO image

cluster-operator/Dockerfile, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11457 - Switch the Verrazzano cluster operator image to use the ol8-static image as its base image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11448: Pick up Jaeger images built using golang 1.20.10

platform-operator/verrazzano-bom.json
=> VZ-11448: Back port uptake of Jaeger images built with golang 1.20.10 to release-1.5 branch

platform-operator/verrazzano-bom.json
=> VZ-11448: Back port uptake of Jaeger images built with golang 1.20.10 to release-1.6 branch

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11448: Back port uptake of Jaeger images built with golang 1.20.10 to release-1.7 branch

platform-operator/capi/infrastructure-oci/v0.13.0/infrastructure-components.yaml, platform-operator/capi/infrastructure-oci/v0.13.0/metadata.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
cherry pick e89f48c
* VZ-11465: New OCI drivers
* VZ-11465 : Increment CAPI pre-release version
=> VZ-11465 backport new OCI CAPI controller

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11482 uptake CAPI OCNE image with golang 1.20

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates kube-state-metrics v2.10.0 built with Go 1.20.10
=> VZ-11451: Update kube-state-metrics v2.10.0 built with Go 1.20.10

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates kube-state-metrics v2.10.0 built with Go 1.20.10 in release-1.7
=> VZ-11451: Update kube-state-metrics v2.10.0 built with Go 1.20.10 in release-1.7

platform-operator/verrazzano-bom.json
Updates kube-state-metrics v2.8.2 built with Go 1.20.10 in release-1.6
=> VZ-11451: Update kube-state-metrics v2.8.2 built with Go 1.20.10 in release-1.6

platform-operator/verrazzano-bom.json
Updates kube-state-metrics v2.6.0 built with Go 1.20.10, in release-1.5
=> VZ-11451: Update kube-state-metrics v2.6.0 built with Go 1.20.10, in release-1.5

ci/oke-ocidns/JenknsfileDnsKind
Backport the fix to have the DNS kind sweep tests use the JAO label to 1.7 (older releases are already ok)
=> use JAO labels BP 1.7

platform-operator/verrazzano-bom.json
Updates node-exporter image built using Go 1.20.10 in release-1.6
=> VZ-11451: Update node-exporter image built using Go 1.20.10 in release-1.6

platform-operator/verrazzano-bom.json
Updates node-exporter image built using Go 1.20.10 in release-1.5
=> VZ-11451: Update node-exporter image built using Go 1.20.10 in release-1.5

platform-operator/verrazzano-bom.json
Updates NGINX v1.3.1 images built using Go 1.20.10, from the change https://github.com/verrazzano/ingress-nginx/pull/15
=> VZ-11451: Update NGINX v1.3.1 images built using Go 1.20.10 in release-1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates latest NGINX images built with the changes from https://github.com/verrazzano/ingress-nginx/pull/16
=> VZ-11451: Update NGINX images, built from oracle/release/1.7.1 branch

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7476 to release-1.6
=> VZ-11451: Update NGINX images, in release-1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7476 to release-1.7
=> VZ-11451: Update NGINX images, in release-1.7

platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
Back port fix for removing keycloak pod ephemeral fix.  The logic is no longer required, and could cause a tight loop of deleting a keycloak pod to occur.
=> VZ-11206 remove keycloak pod ephemeral fix (#7233)

cluster-operator/controllers/vmc/push_manifest_objects.go, cluster-operator/controllers/vmc/push_manifest_objects_test.go, cluster-operator/controllers/vmc/rancher.go, cluster-operator/controllers/vmc/vmc_controller_test.go
This is expected to fix the intermittent failure in verify-cluster-sync in MC test pipeline.
=> VZ-11455 - don't try to check for VZ namespace or push manifest objects if cluster is not active in Rancher.

cluster-operator/controllers/vmc/push_manifest_objects_test.go, cluster-operator/controllers/vmc/rancher.go, cluster-operator/controllers/vmc/vmc_controller_test.go
This is expected to fix the intermittent failure in verify-cluster-sync in MC test pipeline.
=> VZ-11455 - don't try to check for VZ namespace or push manifest objects if cluster is not active in Rancher. #7508

platform-operator/verrazzano-bom.json
Updates nginx-prometheus-exporter image built using Go 1.20.10
=> VZ-11528: Update nginx-prometheus-exporter image

platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7521 to release-1.7
=> VZ-11528: Update nginx-prometheus-exporter image in release-1.7

platform-operator/verrazzano-bom.json
Updates nginx-prometheus-exporter image built using Go 1.20.10
=> VZ-11528: Update nginx-prometheus-exporter v0.10.0 image in release-1.6

platform-operator/verrazzano-bom.json
Updates nginx-prometheus-exporter image built using Go 1.20.10
=> VZ-11528: Update nginx-prometheus-exporter v0.10.0 image in release-1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11504: Pick up rancher images built with golang 1.20 version of dapper

tools/url_linter/ignore_urls.txt
microservices url is dead now, archived today. Ignore for now
=> microservices url is dead now, archived today. Ignore for now

ci/periodic/JenkinsfileDistributions
Don't send image size increase slack alert by default.
=> VZ-11551: don't send image size increase slack alert by default

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
git cherry-pick 8b450310cd41477940a3e2fc1ed61241aa49d8e7
=> VZ-11565: Uptake Rancher images and components built with golang 1.20.12 - back port to release-1.7

platform-operator/verrazzano-bom.json
=> VZ-11565: Uptake Rancher images and components built with golang 1.20.12 to release-1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update Velero and Kiali images built with golang 1.20.12 in the Verrazzano bom.
=> VZ-11599: VZ-11605:  Update Velero and Kiali images built with golang 1.20.12

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11599: VZ-11605: Update Velero and Kiali images built with golang 1.20.12  (#7584)

platform-operator/verrazzano-bom.json
=> VZ-11599: VZ-11605: Update Velero and Kiali images built with golang 1.20.12 (#7584)

CHANGES.md, examples/bobs-books/bobs-books-comp.yaml, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11604: Update coherence-operator to 3.3.2 on release-1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates cert-manager, kube-state-metrics, external-dns, prometheus-node-exporter images, built with Go 1.20.12
=> VZ-11614: Update component images, built with Go 1.20.12

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Backports https://github.com/verrazzano/verrazzano/pull/7599 to release-1.7
=> VZ-11614: Update component images built with Go 1.20.12, in release-1.7

platform-operator/verrazzano-bom.json
=> VZ-11405: Update VMO image tag(fix Golang to 1.20.10 in VMO)

platform-operator/verrazzano-bom.json
Updates component images built with Go 1.20.12, in release-1.6
=> VZ-11614: Update component images built with Go 1.20.12, in release-1.6

platform-operator/verrazzano-bom.json
Updates component images built with Go 1.20.12, in release-1.5
=> VZ-11614: Update component images built with Go 1.20.12, in release-1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update jaeger images built with golang 1.20.12
=> VZ-11615: Update jaeger images built with golang 1.20.12

go.mod, go.sum, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Refreshes nginx-prometheus-exporter and oam-kubernetes-runtime images built with Go 1.20.12, in release-1.7
=> VZ-11614: Refresh nginx-prometheus-exporter and oam-kubernetes-runtime images in release-1.7

go.mod, go.sum, platform-operator/verrazzano-bom.json
Refreshes nginx-prometheus-exporter and oam-kubernetes-runtime images in release-1.5, built using Go 1.20.12
=> VZ-11614: Refresh nginx-prometheus-exporter and oam-kubernetes-runtime images in release-1.5

release/builds/JenkinsfileReleaseExistingCandidate
This is a backport to release-1.5 of a fix to a bug that prevented patch releases with a .0 from being released.
=> Edit regex logic so it supports releases with .0 (#7631)

platform-operator/verrazzano-bom.json
=> VZ-11621: Update VMO image tag for golang 1.20.12 in release-1.7

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates ArgoCD v2.8.3 image, built with Go 1.20.12
=> VZ-11614: Update ArgoCD image, built with Go 1.20.12

platform-operator/verrazzano-bom.json
Updates NGINX v1.3.1 and ArgoCD images built with Go 1.20.12, in release-1.5
=> VZ-11614: Update NGINX and ArgoCD images built with Go 1.20.12, in release-1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates NGINX v1.7.1 and ArgoCD images, built with Go 1.20.12 in release-1.7
=> VZ-11614: Update NGINX and ArgoCD images built with Go 1.20.12 in release-1.7

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/export/oam/oam.go, tools/vz/cmd/install/install.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go, tools/vz/pkg/analysis/internal/util/report/report.go
This commit adds the CLI version as first output to all of the commands in the cmd folder, except for the version command.
=> First pass of adding version of CLI output to commands

tools/vz/pkg/analysis/internal/util/report/report.go
This commit includes a minor fix for VZ-11647. This fix for VZ-11647 is already included in the backports to release-1.6 and release-1.7
=> Minor fix for VZ-11647

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates Dex image built using Go 1.20.12
=> VZ-11614: Update Dex image built using Go 1.20.12

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates Dex image built using Go 1.20.12, in release-1.7
=> VZ-11614: Update Dex image built using Go 1.20.12, in release-1.7

tools/vz/pkg/helpers/vzsanitize.go
There was a analysis tool bug where every redacted value within a single file would be assigned the same hash value. This fixes that bug.
Also adds a "REDACTED-" prefix to every redacted value.
=> VZ-11656: Analysis tool - ensure all redacted values have a unique hash

platform-operator/verrazzano-bom.json
=> VZ-11621: Update VMO image tag for golang to 1.20.12 in VMO release-1.5

tools/scripts/k8s-dump-cluster.sh
This adds the ability to limit the capture to a single namespace rather than a full cluster dump.
This can be useful at times if we need to have someone gather more information than what the vz capture/bug-report provides, but we only need the details from a specific namespace.
-n single-namespace
=> backport dump tweaks to 1.7

tools/scripts/k8s-dump-cluster.sh
This adds the ability to limit the capture to a single namespace rather than a full cluster dump.
This can be useful at times if we need to have someone gather more information than what the vz capture/bug-report provides, but we only need the details from a specific namespace.
-n single-namespace
=> backport dump tweaks to 1.6

tools/scripts/k8s-dump-cluster.sh
This adds the ability to limit the capture to a single namespace rather than a full cluster dump.
This can be useful at times if we need to have someone gather more information than what the vz capture/bug-report provides, but we only need the details from a specific namespace.
-n single-namespace
=> backport dump tweaks to 1.5

tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
- Add regex rule for OPCIDs
- Introduce pre & post processing for regex values
- Rehaul unit testing to prevent incorrect parsing
- Improve existing test cases to test for unwanted sanitation
This MR improves on the existing sanitation technique by allowing values to be modified before and after hashing. The new technique enables the sanitation of otherwise difficult fields such as OPCIDs. Furthermore, this MR introduces a regex rule for OPCIDs.
=> VZ-7846 Improve cli bug report sanitation

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh
There is some issue with the logic which attempts to scan matching releases for a given release branch. This change allows the build to succeed when the job fails to download the BOM file for all the releases, as as workaround for now.
=> Workaround to resolve issue with daily scan job for release branches

tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/install/install.go, tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/constants/constants.go
Changes grab pod logs as expected with --include-logs flag without the need of explicitly using --include-namespaces for individual namespaces
=> vz-11649 Have --include-logs flag grab pod logs without needing --include-namespaces

tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/install/install.go, tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/constants/constants.go
Get pod logs from namespaces being captured with the --include-logs flag
=> vz-11649 --include-logs flag grab pod logs without needing --include-namespaces 

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
Introduces the `--redacted-values-file` flag to the VZ bug report CLI command.
If users provide the flag, the redaction mapping CSV file will be created using the code provided by https://github.com/verrazzano/verrazzano/pull/7678.
=> VZ-11670: --redacted-values-file flag for vz bug-report

tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/sanitize/sanitize.go, tools/vz/cmd/sanitize/sanitize_test.go
Introduces the `--redacted-values-file` flag to the `vz sanitize` command.
Closely related to https://github.com/verrazzano/verrazzano/pull/7720, which did the same for `vz bug-report`.
Also adds some unit tests for this flag, for both commands.
=> VZ-11670: add --redacted-values-file flag to the vz sanitize command

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
This PR upgrades Redis from 7.0.12 to 7.0.15. Redis is a component of ArgoCD.
Note there are no Helm chart updates required for this patch release upgrade.
=> VZ-11673: Uptake Redis 7.0.15

CHANGES.md, platform-operator/verrazzano-bom.json
Backport of Redis 7.0.15 to release-1.6 branch. See https://github.com/verrazzano/verrazzano/pull/7739.
=> VZ-11673: Uptake Redis 7.0.15 (release-1.6)

CHANGES.md, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Backport of Redis 7.0.15 to release-1.7 branch. See #7739.
=> VZ-11673: Uptake Redis 7.0.15 (release-1.7)

tools/vz/cmd/bugreport/bugreport.go
Reworks the default behavior of bug-report to call analyze when AutoBugReport instead of always calling analyze and then bug-report
=> vz 11724 - bug report takes 2 cluster-snapshots

tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/sanitize/sanitize.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzhelper.go
Upon failed `vz` CLI commands, an automatic bug report is created by the `AutoBugReport` function.
The PR creates a redacted values file along with every automatic bug report. If a bug report has the name `vz-bug-report-datetime-xxxx.tar.gz`, the redacted values file is created as `vz-bug-report-datetime-xxxx-sensitive-do-not-share-redaction-map.csv`.
Also updates unit tests to check for the existence of the redacted values file.
=> VZ-11675: Include the redaction map file with auto bug report

tools/vz/cmd/bugreport/bugreport_test.go
Expands unit test to check if file created while capturing previous pod logs is actually captured
=> vz-11752 followup task to create testBugReportFailedPods scenario

ci/JenkinsfilePeriodicTests
On a retry job unstable and success are not being called at all.
I moved the logic to be done directly after the build of examples, if that individual build resulted in success we copy the images.txt
=> VZ-11734 Move logic as unstable was never called

tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/pkg/internal/util/log/log.go
The `TestBugReportGetPreviousLogs` unit test had a problem with flagging a pod as problematic when it shouldn't have been.
This PR
- fixes the above problem by adding a condition to the Pod named `second-istio-pod` in the fake cluster
- adds a check for the problem in the unit test
- cleans up code (i.e. define constants, fix typos)
=> VZ-11772: Fix TestBugReportGetPreviousLogs unit test

tools/vz/pkg/helpers/vzcapture_test.go
Introduces unit tests that validate the analysis tool's ability to capture `VerrazzanoProjects` and `VerrazzanoManagedClusters`.
Also renames the following unit test: `TestCaptureMultiClusterResources` -> `TestCaptureMultiClusterOAMResources`
=> VZ-8679: unit tests for capture VZProjects and VMCs

ci/backup/JenkinsfileAlllBackupOKETest, ci/clusterAPI/JenkinsfileCAPI, ci/clusterAPI/JenkinsfileCAPIQC, ci/ha/JenkinsfileRollingUpgrade, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/ocne-cluster-driver/Jenkinsfile, ci/oke-capi-cluster-driver/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/olcne/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
- Cleanup SSH key usages, switch the ones that setup tunnels to use ephemeral keys.
- Unrelated to ssh keys, the OL7 yum repo removed terraform, so get it from an archive repo for now
=> Cleanup cluster creation key usages

ci/JenkinsfilePeriodicTests, ci/a-la-carte/JenkensfileALaCarteTriggered, ci/a-la-carte/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, pkg/certs/letsencrypt.go, pkg/certs/letsencrypt_test.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer.go, tests/e2e/pkg/acme_ca_certs.go, tests/e2e/pkg/web.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
In this PR, I disable the ACME staging tests in the oci-dns tests and in the a-la-carte tests.
=> OLCNE-6488: Disable ACME Staging Tests In Pipeline

platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go
Fix a bug where the cert was being renewed every day or so.  This caused the OpenSearch Dashboard console to require a new login.  The fix changes the code so that it only renews the cert if the current time is later than the renewal time.  In reality when that happens cert-manager operator will automatically renew the cert, but just in case it doesn't the VPO will do it.  So the cert only gets renewed every few months now.
=> VZ-11894 cert renewal fix

platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go
Fix a bug where the cert was being renewed every day or so. This caused the OpenSearch Dashboard console to require a new login. The fix changes the code so that it only renews the cert if the current time is later than the renewal time. In reality when that happens cert-manager operator will automatically renew the cert, but just in case it doesn't the VPO will do it. So the cert only gets renewed every few months now.
=> VZ-11894 cert renewal fix for release-1.6

platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go
Fix a bug where the cert was being renewed every day or so. This caused the OpenSearch Dashboard console to require a new login. The fix changes the code so that it only renews the cert if the current time is later than the renewal time. In reality when that happens cert-manager operator will automatically renew the cert, but just in case it doesn't the VPO will do it. So the cert only gets renewed every few months now.
=> VZ-11894 cert renewal fix for release-1.7

tests/e2e/clusterapi/oke-capi-driver/environment.go
Kubernetes 1.26.2 is no longer supported by OKE
=> VZ-11897 Update OKE version

examples/bobs-books/bobs-books-comp.yaml, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml
Reverts verrazzano/verrazzano#7847
This change was not needed and causes problems in the private registry and air-gap testing.
=> Revert "Always pull the weblogic:12.2.1.4 image rather than getting it from t…"

platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go
Fix a bug where the cert was being renewed every day or so. This caused the OpenSearch Dashboard console to require a new login. The fix changes the code so that it only renews the cert if the current time is later than the renewal time. In reality when that happens cert-manager operator will automatically renew the cert, but just in case it doesn't the VPO will do it. So the cert only gets renewed every few months now.
=> VZ-11894 cert renewal fix for release-1.6.10
