platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml
=> NO JIRA, fix chart versions in 1.4.4 release

ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest
=> VZ-8946 Update timeouts for uninstall resiliency (#5560)

platform-operator/scripts/wait4webhook.sh
Add logging to wait4webhook.sh so we can get error details when it fails.
=> VZ-8959 add logging to wait4webhook.sh

ci/backup/JenkinsfileAlllBackupOKETest, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
Use US regions only for OKE for release-1.5
=>  use US regions only for OKE

platform-operator/scripts/wait4webhook.sh
Fix a typo that causes script to fail if it doesn't get a curl success the first time.
=> VZ-8959 fix wait4webhook.sh typo

platform-operator/scripts/wait4webhook.sh
=> VZ-8959 fix typo in wait4webhook.sh

platform-operator/scripts/wait4webhook.sh
wait4webhook.sh typo fix along with -vvv for maximum verbosity in case there is an error.
=> VZ-8959 wait4webhook.sh typo fix

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component.go
Small change to fix the availability check and improve the comments in the Verrazzano API
=> VZ-8895 Update the availability check and improve comments

Makefile
Makefile `help` hadn't been updated in a while
=> Add help tags to makefile

tools/scripts/k8s-dump-cluster.sh
=> fix go mod issue

.verrazzano-development-version
=> Developer version

platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.2 to 1.5.3
=> Updating development version from 1.5.2 to 1.5.3

platform-operator/controllers/verrazzano/reconcile/install_component.go
Wrapped logging statement in conditional to avoid logging during install
=> VZ-8920 Reset VPO log from logging during install

platform-operator/verrazzano-bom.json
Updating image versions 1.5.2 -> 1.5.3
=> Updating BOM images

platform-operator/constants/constants.go, platform-operator/controllers/configmaps/components/controller.go, platform-operator/controllers/configmaps/components/controller_test.go, platform-operator/controllers/configmaps/components/dev_helm_component.go
Change dev component configmap controller to look at configmap labels
=> V-7916 dev component controller using labels

ci/kind/Jenkinsfile
=> Backport move logging trait Helidon workload stage (#5638)

platform-operator/verrazzano-bom.json, tests/e2e/pkg/elasticsearch.go, tests/e2e/upgrade/post-upgrade/opensearch/opensearch_test.go, tests/e2e/upgrade/pre-upgrade/opensearch/opensearch_test.go
update OS/OSD Image to add Alerting plugin
=> VZ-8725: update OS/OSD Image to add Alerting plugin

pkg/helm/helmcli_test.go
The test was attempting to test thread safety but isn't quite achieving the goal.
=> JIRA: VZ-9134 remove intermittently failing helm unit test

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
=> vz-8849-Updating urls in vz API

tools/scripts/k8s-dump-cluster.sh
=> VZ:8957: Enhanced condition to handle vz build and handle checksum mismatch

platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Update Coherence Operator to 3.2.10
=> VZ- 9151 - Update Coherence Operator to 3.2.10

tools/vz/cmd/bugreport/bugreport.go
FIx master build issue for my PR 9003
=> gofmt issue for 9003 PR

tests/e2e/metrics/syscomponents/metrics_test.go, tests/e2e/pkg/metrics.go
**Changes**
- Add test to the metrics suite to make sure Thanos metrics can be queried
=> VZ-9159 Add tests to verify that Thanos metrics can be queried

ci/JenkinsfilePeriodicTests, ci/periodic/JenkinsfileDistributions, ci/scripts/build_distribution.sh, ci/scripts/update_last_clean_periodic_test.sh
Backporting commits to reorganize periodics test pipeline
=> VZ-9076 Old ephemeral zip files are cleaned up after the pipeline runs

ci/chaos/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/olcne/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade/Jenkinsfile, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/uninstall/uninstall_test.go
Changed vz uninstall to by default display a prompt before uninstall
=> vz-9106 vz cli prompt before uninstall

tools/vz/pkg/bugreport/reportgen.go
- vpo web hook logs are included to vz bug report
=> VZ-9188 vpo web hook logs included to vz bug report

platform-operator/verrazzano-bom.json
Uptake latest build of rancher phase-1 image
=> VZ-9031: Uptake new Rancher phase-1 image

ci/JenkinsfilePeriodicTests, ci/periodic/JenkinsfileDistributions
Backport commit [VZ-6947 Parallelize private registry tests in the periodics pipeline](https://github.com/verrazzano/verrazzano/commit/e510ec954859c38c4083bd540f3f130daa0426c4)
=> VZ-6947 Parallelize private registry tests in the periodics pipeline

ci/scripts/update_last_clean_periodic_test.sh
Fixing periodics to copy resources instead of pushing
=> VZ-9075 Parallelize private registry tests in the periodics pipeline

cluster-operator/controllers/vmc/jaeger.go, cluster-operator/controllers/vmc/sync_registration_secret.go
VMC registration is now aware of opensearch component enable/disable
=> VZ 9260: VMC registration can complete if opensearch disabled

platform-operator/verrazzano-bom.json
Picking up a new Rancher build with the fix for VZ-9202
=> pickup new rancher build

tests/e2e/pkg/update/updater.go, tests/e2e/update/opensearch/opensearch_plugin_test.go, tests/e2e/update/opensearch/opensearch_update.go
=> (VZ-8972):add code for e2e for plugin update

platform-operator/verrazzano-bom.json, tests/e2e/pkg/elasticsearch.go, tests/e2e/upgrade/post-upgrade/opensearch/opensearch_test.go, tests/e2e/upgrade/pre-upgrade/opensearch/opensearch_test.go
- update os image to include alerting plugin
=> Backport: VZ-8725: update os image to include alerting plugin

ci/upgrade-paths/Jenkinsfile
This is a follow-up to PR #5732. This is for the automated testing to use any combination of install & upgrade using either kubectl or vz cli.
=> VZ-8551: VPO status Init:CrashLoopBackOff after applying operator.yaml

platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/opensearch-operator/CHANGELOG.md, platform-operator/thirdparty/charts/opensearch-operator/Chart.yaml, platform-operator/thirdparty/charts/opensearch-operator/README.md, platform-operator/thirdparty/charts/opensearch-operator/templates/OpensearchRole-crd.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/OpensearchUser-crd.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/OpensearchUserRoleBinding-crd.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/_helpers.tpl, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-controller-manager-deployment.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-controller-manager-metrics-service-svc.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-controller-manager-sa.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-leader-election-role-role.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-leader-election-rolebinding-rb.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-manager-config-cm.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-manager-role-cr.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-manager-rolebinding-crb.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-metrics-reader-cr.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-proxy-role-cr.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearch-operator-proxy-rolebinding-crb.yaml, platform-operator/thirdparty/charts/opensearch-operator/templates/opensearchclusters.opensearch.opster.io-crd.yaml, platform-operator/thirdparty/charts/opensearch-operator/values.yaml
Added opster opensearch-operator charts
=> VZ-9116-1: Add opensearch-operator charts

CHANGES.md, platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
=> WebLogic Kubernetes Operator 4.0.6 and WebLogic MonitoringExporter 2.1.3

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
=> WebLogic Kubernetes Operator 3.4.7 and WebLogic Monitoring Exporter 2.1.3

platform-operator/helm_config/overrides/thanos-values.yaml, platform-operator/thirdparty/charts/thanos/templates/query/ingress-grpc.yaml
Small change to fix the helm value exposed for the query store ingress
**Testing**
Install and verify an ingress gets created with the correct name and URL.
=> Fix the helm value name for the query store ingress

platform-operator/verrazzano-bom.json
=> VZ-9281 - Pick up console version that has Thanos Selenium tests

platform-operator/thirdparty/charts/thanos/templates/verrazzano/authorizationpolicy.yaml
This reverts commit 8c7f029dd0dd5fd2d644df48a55796934ecb243d.
=> Revert "Make the Thanos authorization policies more specific (#5788)"

platform-operator/controllers/verrazzano/component/thanos/thanos_component.go, platform-operator/controllers/verrazzano/component/thanos/thanos_component_test.go
=> Thanos component overrides IsAvailable to check only enabled subcomponents, so that it reports availability correctly in the VZ resource

CHANGES.md
=> Add Thanos to CHANGES.md for release notes

platform-operator/verrazzano-bom.json
=> VZ-9220: Fix OS data node PVC resize through VZ CR

platform-operator/verrazzano-bom.json
=> VZ-9220: Fix data node PVC resize bp

platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml
Set node name in fluentd environment variable K8S_NODE_NAME
=> VZ:8689 Set node name in fluentd (#5815)

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#5820
=> Revert "VZ-9205: Pickup new rancher image with cloud cred changes"

cluster-operator/controllers/vmc/jaeger.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_component.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/verrazzano-bom.json
Backport of ingress bug install issue and a few other issues
=> VZ-9326 ingress bug backport

platform-operator/verrazzano-bom.json
=> VZ-9205 cloud creds retest

ci/JenkinsfileTestTrigger, ci/upgrade-paths/Jenkinsfile, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
Reverts verrazzano/verrazzano#5823
=> Revert "VZ-8970 Include stable release candidate for all active release in Up…"

CHANGES.md
Added CHANGES.md entry for VZ-9326
=> Add VZ-9326 to CHANGES.md

platform-operator/capi/.cluster-api/clusterctl.yaml, platform-operator/capi/bootstrap-ocne/v0.1.0/bootstrap-components.yaml, platform-operator/capi/control-plane-ocne/v0.1.0/control-plane-components.yaml, tests/e2e/config/scripts/v1beta1/install-verrazzano-kind.yaml
* New API changes 
* Enable CAPI in kind acceptance tests
=> VZ-9474: CAPI enhancements

platform-operator/verrazzano-bom.json
=> Update new rancher image using OCI APIs

ci/JenkinsfilePeriodicTests
=> VZ-9478: Disable 1.21 tests on master

ci/scripts/install_calico.sh
=> VZ-7679 Fix download Calico part to set CALICO_HOME correctly

ci/scripts/install_calico.sh
Missed to update the copyright as part of https://github.com/verrazzano/verrazzano/pull/5862
=> VZ-7679 Fix copyright update

platform-operator/capi/.cluster-api/clusterctl.yaml
=> VZ-9507: Update latest capi and ocne controller image

tests/e2e/capi/ocne-driver/ocne_cluster_driver_suite_test.go, tests/e2e/capi/ocne-driver/ocne_cluster_driver_test.go, tests/e2e/pkg/kubernetes.go
=> VZ-9038: Added variables & template

tests/e2e/capi/ocne-driver/ocne_cluster_driver_test.go
=> VZ-9038: Added create CAPI template

platform-operator/verrazzano-bom.json
=> VZ-9313: Update OS image

platform-operator/verrazzano-bom.json
=> VZ-9313: Update OS image bp

tests/e2e/upgrade/post-upgrade/verify/verify_restart_test.go
Fixes a test bug that was causing the verify restart test to fail
=> Fix issue with verify restart test

platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/nginx/nginx_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
Add streaming directives to nginx configuration to address WSS related errors in Rancher console
=> JIRA: VZ-5060 Introduce streaming snippet annotation to Rancher ingress only once

ci/ocne-cluster-driver/Jenkinsfile, tests/e2e/capi/ocne-driver/ocne_cluster_driver_suite_test.go, tests/e2e/capi/ocne-driver/ocne_cluster_driver_test.go
=> updated for security

release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh, release/scripts/scan_bom_images.sh
This change backports https://github.com/verrazzano/verrazzano/pull/5906 to release-1.3
=> VZ-9506: Fix the consolidated report generated from daily scanning job, release-1.3

release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh, release/scripts/scan_bom_images.sh
This change backports https://github.com/verrazzano/verrazzano/pull/5906 to release-1.4
=> VZ-9506: Fix the consolidated report generated from daily scanning job, release-1.4

release/scripts/generate_vulnerability_report.sh, release/scripts/get_ocir_scan_results.sh, release/scripts/scan_bom_images.sh
This change backports https://github.com/verrazzano/verrazzano/pull/5906 to release-1.5
=> VZ-9506: Fix the consolidated report generated from daily scanning job, release-1.5

platform-operator/verrazzano-bom.json
Update to the fleet and gitjob images that have the fixes necessary for fleet to work.
Currently running through a series of pipelines to ensure no unexpected side effects.  Will merge post successful tests.
=> JIRA: VZ-7896 Update fleet and gitjob images

ci/periodic/JenkinsfileDistributions, ci/private-registry/Jenkinsfile, ci/scripts/create_kind_clusters.sh, ci/scripts/generate_vz_distribution.sh, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh, tests/e2e/config/scripts/create_kind_cluster.sh, tests/e2e/config/scripts/create_ocir_repositories.sh, tests/e2e/config/scripts/install-metallb.sh, tests/e2e/config/scripts/kind-config-ci-calico-private-registry.yaml, tests/e2e/pkg/test/framework/metrics/ginkgo_metrics.go
**Changes**
- Push the source Tar and example images to the OCI bucket in the build distribution stage
- Update the Private registry test to use local resources in an air gap environment
- Fix test creation scripts that were unable to run in air gap environment
- Modified cluster installation steps to work in air gap environment
- modified ginkgo test metrics output to halt for air gap tests
=> VZ-9429 Run Private Registry test in an air gap environment

platform-operator/helm_config/charts/verrazzano/values.yaml
Enable AuthorizationPolicy for Jaeger Operator component when the component is enabled
Cherry-picking #5894
=> VZ-9208: AuthorizationPolicy Missing for Jaeger Traces to be transmitted

platform-operator/controllers/verrazzano/component/istio/istio_install_test.go, platform-operator/controllers/verrazzano/secret/image_pull_secret.go, platform-operator/controllers/verrazzano/secret/image_pull_secret_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml
Backport of https://github.com/verrazzano/verrazzano/pull/5925 to release-1.5
=> VZ-9531: Support installing VPO image from private registry with credentials

platform-operator/controllers/verrazzano/component/nginx/nginx.go, platform-operator/controllers/verrazzano/component/nginx/nginx_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
Reverts verrazzano/verrazzano#5909
=> Revert "JIRA: VZ-5060 Introduce streaming snippet annotation to Rancher ingress only once"

platform-operator/scripts/install/create_oci_config_secret.sh
A fix was backported from master to fix a case where the API key had no newline, but the script in older lines is creating the secret in a way that still breaks when we copy it.
This backports the script changes from master so the API key is last, and when the `compartment` field is added by the VPO code the newline workaround will work.
=> Backport script to create OCI DNS secret to fix pipeline runs

ci/periodic/JenkinsfileDistributions, ci/private-registry/Jenkinsfile, ci/scripts/create_kind_clusters.sh, ci/scripts/generate_vz_distribution.sh, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh, tests/e2e/config/scripts/create_kind_cluster.sh, tests/e2e/config/scripts/create_ocir_repositories.sh, tests/e2e/config/scripts/install-metallb.sh, tests/e2e/config/scripts/kind-config-ci-calico-private-registry.yaml, tests/e2e/pkg/test/framework/metrics/ginkgo_metrics.go
**Changes**
- Push the source Tar and example images to the OCI bucket in the build distribution stage
- Update the Private registry test to use local resources in an air gap environment
- Fix test creation scripts that were unable to run in air gap environment
- Modified cluster installation steps to work in air gap environment
- modified ginkgo test metrics output to halt for air gap tests
=> VZ-9543  Run Private Registry test in an air gap environment

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.3 to 1.5.4
=> Updating development version from 1.5.3 to 1.5.4

platform-operator/verrazzano-bom.json
=> Picking up new image versions

Makefile, tools/charts-manager/vcm/README.md, tools/charts-manager/vcm/cmd/diff/diff.go, tools/charts-manager/vcm/cmd/diff/diff_test.go, tools/charts-manager/vcm/cmd/helpers/command.go, tools/charts-manager/vcm/cmd/helpers/command_test.go, tools/charts-manager/vcm/cmd/patch/patch.go, tools/charts-manager/vcm/cmd/patch/patch_test.go, tools/charts-manager/vcm/cmd/pull/pull.go, tools/charts-manager/vcm/cmd/pull/pull_test.go, tools/charts-manager/vcm/cmd/root/root.go, tools/charts-manager/vcm/cmd/root/root_test.go, tools/charts-manager/vcm/main.go, tools/charts-manager/vcm/pkg/constants/constants.go, tools/charts-manager/vcm/pkg/fs/fs.go, tools/charts-manager/vcm/pkg/fs/fs_test.go, tools/charts-manager/vcm/pkg/helm/helm.go, tools/charts-manager/vcm/pkg/helm/helm_test.go, tools/charts-manager/vcm/pkg/test/helpers.go, tools/charts-manager/vcm/tests/pkg/fakes/fakes.go, tools/charts-manager/vcm/tests/pkg/helpers/helpers.go
=> VZ-9241: chart manager cli

examples/bobs-books/README.md, examples/helidon-config/README.md, examples/hello-helidon/README.md, examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md, examples/multicluster/sock-shop/README.md, examples/multicluster/todo-list/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md
Fix doc URLs to reference new examples location
=> Fix doc URLs to reference new examples location

ci/private-registry/Jenkinsfile, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh
**Changes**
- uninstall in the private registry pipeline with the vz cli
- reinstate the verify uninstall
=> VZ-9552 fix the uninstall code for the private registry tests

examples/bobs-books/README.md, examples/helidon-config/README.md, examples/hello-helidon/README.md, examples/multicluster/README.md, examples/multicluster/hello-helidon/README.md, examples/multicluster/sock-shop/README.md, examples/multicluster/todo-list/README.md, examples/sock-shop/README.md, examples/springboot-app/README.md, examples/todo-list/README.md
This PR backports https://github.com/verrazzano/verrazzano/pull/5979 to release-1.5
=> Fix reference to doc samples in release-1.5

platform-operator/verrazzano-bom.json
=> VZ-9734: Uptake new rancher image with metadata change

platform-operator/verrazzano-bom.json
=> VZ-9676: Backport changes: fluentd image with updating dependencies 

ci/tools/derive_upgrade_version.go, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR excludes upgrade release versions based on Verrazzano development versio
=> VZ-9660: Exclude upgrade release versions based on Verrazzano dev version

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
…sion (#6018)
This PR backports a commit from master to exclude upgrade releases versions based on Verrazzano dev version and minor versions in exclude params.
=> VZ-9660: PR to exclude upgrade release versions based on Verrazzano dev version

Makefile, ci/scripts/check_if_clean_after_generate.sh, go.mod, go.sum, pkg/k8sutil/yaml_util.go, pkg/k8sutil/yaml_util_test.go
=> Remove unintended direct dependency on gopkg.in/yaml.v2

platform-operator/verrazzano-bom.json
Fixes the following bugs:
- regression in rancher-ui
- updating rancher updates custom drivers
=> Updating rancher image: fixes bugs

platform-operator/verrazzano-bom.json
=> VZ-9673: Update new Rancher image for release-1.5

Jenkinsfile, ci/private-registry/Jenkinsfile, ci/scripts/prepare_distribution_test_jenkins_at_environment.sh
**Changes**
- Use the VZ CLI to install and uninstall
- Make the test public for lite distributions
=> Update the 1.5 Private registry tests 

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#6028
=> Revert "Updating rancher image: fixes bugs"

ci/private-registry/Jenkinsfile
backport runner handling for private registry to 1.5, use local OCIR for runner image, use runner and OCIR registry in same region: PHX for Lite and FRA for Full
=> backport runner handling for private registry to 1.5

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests, ci/lre/Jenkinsfile
Add alerting for pipeline owners for periodics, backend, and LRE
=> Add alerting for pipeline owners for periodics, backend, and LRE

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/verrazzano-bom.json
- OKE Kontainer driver is built in to rancher, always active
- New Rancher-UI version with compartment tree fix
- custom drivers are auto updated during rancher upgrade.
=> Rancher Image update

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests, ci/lre/Jenkinsfile
=> Backport owner alerts to 1.5

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests, ci/lre/Jenkinsfile
=> backport owner alerts to 1.4

platform-operator/verrazzano-bom.json
=> VZ:8842 backport fluentd image version

platform-operator/verrazzano-bom.json
=> VZ-8842: Updated Fluentd image build

platform-operator/verrazzano-bom.json
**Changes**
- Update the MySQL server image
=> Update the MySQL server image to 8.0.33

ci/ha/JenkinsfileRollingUpgrade, tests/e2e/ha/inplaceupgrade/in_place_upgrade_test.go
=> VZ-9762: Increase timeout for upgrade of control plane

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR fixes the backend tests that fixes upgrading from tip of release branches to master.
=> VZ-9764: Fix backend tests to upgrade tip of release to master. 

ci/JenkinsfilePeriodicTests, ci/chaos/JenkinsfileResiliencyTrigger, ci/scan-results/Jenkinsfile
Disable release-1.3 cron schedules
=> Disable release-1.3 cron schedules

ci/ha/JenkinsfileRollingUpgrade
=> VZ-9762: Increase timeout for running ginkgo tests

ci/ha/JenkinsfileRollingUpgrade
=> VZ-9862: Increase timeout of ginkgo tests for HA pipeline

platform-operator/verrazzano-bom.json
These are dormant changes that will be utilized in the future by the Rancher build.
=> VZ-9768: Add some Rancher build parameters to the BOM

CHANGES.md, release/docs/README_FULL.html, release/docs/README_FULL.md, release/docs/README_LITE.md
=> Fix documentation links that are broken due to doc reorganization

platform-operator/verrazzano-bom.json
Refreshes components built from source in verrazzano-bom.json
=> VZ-8902: Refresh component images

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR fixes backend job to upgrade from tip of release to master branch.
=> Fix to upgrade from tip of release to master branch. 

platform-operator/verrazzano-bom.json
=> VZ-9879: Pickup new capi images

platform-operator/verrazzano-bom.json
update OS/OSD image to include notification plugins.
=> VZ-9221: update OS/OSD image to include notification plugins

platform-operator/verrazzano-bom.json
Updates NGINX ingress, Keycloak and other images
=> VZ-8902: Update NGINX ingress, Keycloak and other images

platform-operator/verrazzano-bom.json
update OS/OSD image to include notification plugin in release-1.5
=> VZ-9221: backport notification plugin in OS/OSD to release-1.5

platform-operator/capi/bootstrap-ocne/v0.1.0/bootstrap-components.yaml, platform-operator/capi/control-plane-ocne/v0.1.0/control-plane-components.yaml, platform-operator/verrazzano-bom.json
=> VZ-9867: Update CAPI manifests and yamls

platform-operator/thirdparty/charts/README.md, platform-operator/thirdparty/charts/mysql-operator/Chart.yaml, platform-operator/thirdparty/charts/mysql-operator/README.md, platform-operator/thirdparty/charts/mysql-operator/templates/NOTES.txt, platform-operator/thirdparty/charts/mysql-operator/values.yaml, platform-operator/thirdparty/charts/mysql/Chart.yaml, platform-operator/thirdparty/charts/mysql/README.md, platform-operator/thirdparty/charts/mysql/templates/deployment_cluster.yaml, platform-operator/verrazzano-bom.json
**Changes**
Updated the chart and operator image version to the next patch version to fix an upgrade issue
=> Update the MySQL chart to fix the upgrade issue from 8.0.30 to 8.0.33

application-operator/internal/operatorinit/run_cluster_agent.go, application-operator/internal/operatorinit/run_operator.go, application-operator/main.go, platform-operator/controllers/verrazzano/component/clusteragent/cluster_agent.go, platform-operator/controllers/verrazzano/component/clusteragent/cluster_agent_component_test.go, platform-operator/controllers/verrazzano/component/clusteragent/cluster_agent_test.go, platform-operator/verrazzano-bom.json
=> VZ-9840 Follow up items - create a BOM entry for verrazzano-cluster-agent, some refactoring

platform-operator/verrazzano-bom.json
This PR refreshes component images, to uptake latest packages from the base image
=> Refresh component images, to uptake latest packages from the base image

ci/scripts/create_kind_clusters.sh, tests/e2e/config/scripts/create_kind_cluster.sh, tests/e2e/config/scripts/kind-config-calico.yaml, tests/e2e/config/scripts/kind-config-ci-calico-private-registry.yaml, tests/e2e/config/scripts/kind-config-ci-calico.yaml, tests/e2e/config/scripts/kind-config-ci.yaml, tests/e2e/config/scripts/kind-config.yaml
=> backport: New kindset Images

ci/lre/Jenkinsfile
LRE job needed to pull down the CLI for capturing and analyzing failures
=> VZ-9922 Pull down the CLI for capturing and analyzing cluster

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Cleanup unsupported rancher resources post-upgrade: NodeDrivers, Rancher CAPI ValidatingWebhookConfiguration
=> cleanup rancher resources post-upgrade

pkg/constants/constants.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go
PR to backport https://github.com/verrazzano/verrazzano/pull/6122 to 1.5 release.
=> VZ-9761 Synchronize Rancher TLS CA with Verrazzano TLS (#6122)

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
=> Fix up VMC API doc comments

cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
=> Fix relative path in VMC doc

platform-operator/verrazzano-bom.json
Pick up module api changes with new CAPI images
=> VZ-9960: module name change

ci/JenkinsfilePeriodicTests
Fix periodics to not run prerelease validation when DRY_RUN=TRUE
=> VZ-9933 Only check for last clean when running tests (#6152)

platform-operator/verrazzano-bom.json
=> VZ-9976: Update CAPI images with dac override

platform-operator/verrazzano-bom.json
=> VZ-9986: Updated new fluentd image with dependencies

platform-operator/helm_config/overrides/fluent-operator-values.yaml
=> populate k8s labels and annotations in logs with fluentbit

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
This pull request fixes broken doc links in the verrazzano APIs.
=> VZ-9880: Fix broken doc links in APIs

platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
Added an extra multi field with correct type for few values in the OS index template.
=> VZ-9453: Add multi field with correct type in OS index template

platform-operator/thirdparty/manifests/fluent-operator/fluentbit-config-configmap.yaml
=> Update index template in fluent-bit

CHANGES.md
To update changes.md to include ingress-nginx-controller v1.7.1
=> VZ-9602: Follow up PR to update changes.md to include ingress-nginx-controller v1.7.1

platform-operator/controllers/verrazzano/component/fluentoperator/fluentoperator.go, platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-fluentBit.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/verrazzano/fluentbit-systemd-filter-parser.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/verrazzano/fluentbit-tail-filter-parser.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml
Pass convey cluster name as environment variable to FluentOperator to add the label in logs
=> VZ-9983: Pass cluster name as environment variable to FluentOperator

tests/e2e/multicluster/verify-resources/verify_resources_test.go
Fixing revert issues with 9316, fixing copyright year
=> Updated copyright year

platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-clusterinput-systemd.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml
disable systemd filter for fluentbit to get all systemd logs
=> VZ-9985: disable systemd filter for fluentbit to get all systemd logs

platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
Adds a couple of unit tests for `AppendOverrides` for Custom CA cases.
=> Add some unit tests for additional AppendOverrides cases

pkg/rancherutil/rancher_config.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall_test.go
Backports fix for Rancher SSO using a custom CA to release 1.5.
- also adds a unit test
=> VZ-10012.  Backport of fix for VZ-9882 to release 1.5

CHANGES.md
Add release notes for VZ-8873 and VZ-9882.
- customer-managed CM
- Rancher SSO using a customer-provided CA
=> VZ-8873, VZ-9882.  Add release notes for Customer-managed CM and VZ-9882 fix

CHANGES.md, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall.go, platform-operator/controllers/verrazzano/component/rancher/rancher_preinstall_test.go
Backports the fix for custom-CA login using Rancher SSO to release 1.4.
=> VZ-10012. Backport fix for VZ-9882 to release-1.4

platform-operator/verrazzano-bom.json
=> VZ-10038 module op tigera fix

ci/JenkinsfilePeriodicTests
Fix periodics to not run prerelease validation when DRY_RUN=TRUE
=> Only check for last clean when running tests (#6152)

platform-operator/verrazzano-bom.json
Co-authored-by: Verrazzano BOT <verrazzanobot@oracle.com>
(cherry picked from commit 046b6f2c3c040521de2ee953bed10a53e9acdaa3)
=> Automated CI from Rancher v2.7.3-20230613150408-cfcd49258 (#6224)

CHANGES.md
Rancher Partner charts and RKE2 charts removed from VZ Rancher 2.7.3
=> VZ-10058: Rancher Partner charts and RKE2 charts removed from VZ Rancher 2.7.3

platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluent-operator-deployment.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-fluentBit.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml
add pod security to fluentoperator.
=> Backport to release-1.6: add pod security to fluentoperator

ci/uninstall/JenkinsfileUninstallTest, tests/e2e/uninstall/verifycrds/verify_crds_suite_test.go, tests/e2e/uninstall/verifycrds/verify_crds_test.go
=> VZ-9919 - fix test failure in uninstall-resiliency-tests where it was checking for VMO CRD in managed cluster profile.

ci/multicluster/Jenkinsfile, tests/e2e/config/scripts/multicluster_edit_vz.sh, tests/e2e/config/scripts/v1alpha1/install-verrazzano-minimal.yaml, tests/e2e/config/scripts/v1beta1/install-verrazzano-minimal.yaml, tests/e2e/multicluster/verify-register/verify_register_suite_test.go, tests/e2e/multicluster/verify-register/verify_register_test.go, tests/e2e/pkg/kubernetes.go
**Changes**
- Add the minimal managed cluster to the Multicluster pipeline
- Update the verify register test to support the existing minimal managed cluster configuration
=> VZ-9843 Add the minimal managed cluster to the Multicluster tests

platform-operator/verrazzano-bom.json
=> VZ module operator image v0.1.0-20230614174158-ace2936f

platform-operator/verrazzano-bom.json
=> Backport of vz module operator image v0.1.0-20230614174158-ace2936f (#6246)

CHANGES.md
=> VZ-9970: Update release note to mention API change for OS Node

platform-operator/verrazzano-bom.json
Cherry pick 0ca73a554f562b06d6fbf2a62161be22c88b63ad
=> OCNE Driver v0.10.0 (#6243)

platform-operator/thirdparty/charts/rancher/templates/deployment.yaml
=> VZ 10085: Permissions for rancher pod (#6252)

tests/e2e/uninstall/verifycrds/verify_crds_test.go
=> VZ-10086 VZ-9919 - fix VMO CRD verification test (unexpected CRD error when VMO is enabled)

ci/JenkinsfileBackendTests, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR fixes the broken upgrade job from tip of release branches to master.
=> VZ-10072: Fix upgrade from tip of release branches to master

platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml
=> fix fluentbit-opensearch-output chart version

platform-operator/verrazzano-bom.json
Fixes two issues:
- Display name not updated during edits
- Cloud credential drop down reset during updates
=> VZ-10087: OCNE UI 2.7.2-7

platform-operator/verrazzano-bom.json
Updates version of cluster-operator and application-operator in BOM
=> Update version of cluster-operator and application-operator in BOM

platform-operator/helm_config/overrides/fluent-operator-values.yaml, platform-operator/thirdparty/charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/fluentbit-fluentBit.yaml, platform-operator/thirdparty/charts/fluent-operator/values.yaml, platform-operator/verrazzano-bom.json
Add container level security context to fluentbit container.
=> VZ:10047 update security context of fluentbit container

CHANGES.md
=> fix Changes.md for 1.6

platform-operator/verrazzano-bom.json
Updates version for nginx-ingress-controller and kube-webhook-certgen images
=> Fix version of nginx-ingress-controller and kube-webhook-certgen images in BOM

ci/JenkinsfilePeriodicTests, ci/scripts/update_last_clean_periodic_test.sh, release/builds/JenkinsfileForceCandidate
Backport VZ-9834 and VZ-8201 to 1.5
=> Backport VZ-9834 and VZ-8201 to 1.5

platform-operator/verrazzano-bom.json
=> VZ-10118: new module op change

platform-operator/verrazzano-bom.json
=> VZ-10118 module op image backport

platform-operator/helm_config/charts/verrazzano-network-policies/templates/thirdparty-networkpolicy.yaml
=> fix istio netpol for fluentoperator

platform-operator/helm_config/charts/verrazzano-network-policies/templates/thirdparty-networkpolicy.yaml
=> fix indentation for networkpolicy

ci/scripts/get_branch_scan_results.sh
Fix scanning for release-* branches when they are first cut and do not have a release yet.
=> VZ-10116 apply fix from 1.6 to master

platform-operator/controllers/verrazzano/component/fluentbitosoutput/fluentopensearchoutput_component_test.go, platform-operator/controllers/verrazzano/component/fluentoperator/fluentoperator_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/spi/component_context_test.go, platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devKeycloakInstallArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESStorageArgsMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodNoStorageOpenSearchOverrides.yaml, platform-operator/manifests/profiles/v1alpha1/dev.yaml, platform-operator/manifests/profiles/v1alpha1/prod.yaml, platform-operator/manifests/profiles/v1beta1/dev.yaml, platform-operator/manifests/profiles/v1beta1/prod.yaml
Enable capi for prod and dev profiles by default.
=> Enable capi for prod and dev profiles - release 1.6

ci/dynamic-updates/JenkinsfileTrigger
This PR removes an extra comma that was causing periodic failure for dynamic config suite.
=> Fix dynamic config suite failure.

release/builds/JenkinsfileReleaseExistingCandidate
images.txt needs to be copied into place backport to 1.4
=> images.txt needs to be copied into place backport to 1.4

release/builds/JenkinsfileReleaseExistingCandidate
images.txt needs to be copied into place backport to 1.5
=> images.txt needs to be copied into place backport to 1.5

release/builds/JenkinsfileReleaseExistingCandidate
images.txt needs to be copied into place forward merge to master
=> images.txt needs to be copied into place forward merge to master

platform-operator/controllers/verrazzano/component/fluentbitosoutput/fluentopensearchoutput_component_test.go, platform-operator/controllers/verrazzano/component/fluentoperator/fluentoperator_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/spi/component_context_test.go, platform-operator/controllers/verrazzano/component/spi/testdata/basicDevMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/basicProdMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devAllDisabledMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devCertManagerOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devESArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devKeycloakInstallArgsStorageOverride.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/devOCIOverrideMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodESStorageArgsMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodFluentdOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodIngressIstioOverridesMerged.yaml, platform-operator/controllers/verrazzano/component/spi/testdata/prodNoStorageOpenSearchOverrides.yaml, platform-operator/manifests/profiles/v1alpha1/dev.yaml, platform-operator/manifests/profiles/v1alpha1/prod.yaml, platform-operator/manifests/profiles/v1beta1/dev.yaml, platform-operator/manifests/profiles/v1beta1/prod.yaml
Enable ClusterAPI component for prod and dev profiles.
=> Enable ClusterAPI component for prod and dev profiles

tests/e2e/verify-install/clusterapi/clusterapi_test.go
Clustapi test doesn't work with CAPI enabled.  Disable it for now.
=> VZ-10162 disable clusterapi test

tests/e2e/verify-install/clusterapi/capi_suite_test.go
=> VZ-0162 disable clusterapi test - fix build

ci/backup/JenkinsfileAlllBackupOKETest, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
remove unsupported OKE versions
=> remove unsupported OKE versions

platform-operator/verrazzano-bom.json
=> VZ-10173- Fix for control plane shape selection in rancherUI

platform-operator/thirdparty/charts/fluent-operator/templates/verrazzano/fluentbit-add-timestamp-lua.yaml, platform-operator/thirdparty/charts/fluent-operator/templates/verrazzano/fluentbit-output-filter.yaml
format the output timestamp to add timezone offset
=> VZ-10099: format the output timestamp to add timezone offset

ci/multicluster/Jenkinsfile, examples/multicluster/managed-clusters/minimal-prometheus.yaml, examples/multicluster/managed-clusters/minimal-thanos.yaml
=> VZ-10104 Enable kube-state-metrics in minimal managed cluster profiles with monitoring.

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
=> VZ-10180: Fix initialization of ociocne driver on upgrade

examples/multicluster/managed-clusters/minimal-prometheus.yaml, examples/multicluster/managed-clusters/minimal-thanos.yaml
=> VZ-10104 Enable node exporter in minimal managed cluster examples

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR fixes the typo release-1* to make it more generic for future major releases
=> Fix typo to support major releases

platform-operator/verrazzano-bom.json
Non-blocking OCNE cluster create to support timely deletions of OCNE clusters.
=> VZ 10175: OCNE Cluster deletion

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides_test.go
Set `VERRAZZANO_CLUSTER_API_DIR` env var to your cluster-api directory to use.
=> Install CAPI running VPO locally

platform-operator/verrazzano-bom.json
Downgrade the MySQL image version.
=> Backport the downgrade of the MySQL server version

tests/e2e/verify-install/clusterapi/capi_suite_test.go, tests/e2e/verify-install/clusterapi/clusterapi_test.go
=> VZ-10162: Reinstate kontainerdriver end-to-end test

ci/dynamic-updates/Jenkinsfile
This changes fixes a method too large exception in the dynamic config pipeline by moving  code from the main pipeline to separate functions.
=> Fix dynamic config pipeline error

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.0 to 1.6.1
=> Updating development version from 1.6.0 to 1.6.1

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.0 to 2.0.0
=> Updating development version from 1.6.0 to 2.0.0

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Reverts verrazzano/verrazzano#6356
=> Revert "Updating development version from 1.6.0 to 2.0.0"

tests/e2e/verify-install/clusterapi/capi_suite_test.go, tests/e2e/verify-install/clusterapi/clusterapi_test.go
=> VZ-10162: Reinstate end-to-end test for kontainerengines

tests/e2e/verify-install/clusterapi/clusterapi_test.go
Temporary disable of test while resolving a pipeline issue
=> VZ-10230: Temporary skip of test for kontainerdriver being active

tests/e2e/verify-install/clusterapi/clusterapi_test.go
=> VZ-10230: Temporary skip of kontainerdriver test for activated (#6375)

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
Backport of #6381 to release-1.6 branch
=> VZ-10215: fix upgrade of clusterAPI component (#6381)

platform-operator/verrazzano-bom.json
=> Update verrazzano-bom.json with new fluentbit image

platform-operator/controllers/verrazzano/component/common/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go, tests/e2e/verify-install/clusterapi/clusterapi_test.go, tools/scripts/k8s-dump-cluster.sh
Resolve issue of kontainerdrivers not being able to download when there is a change to the dns domain.
=> VZ-10230: Update kontainerdriver URL when common-name changes

platform-operator/verrazzano-bom.json
Backport Rancher 2.7.3 image uptake to release-1.5 branch.
=> VZ-10131: Uptake latest Rancher images (release-1.5)

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Update Coherence Operator to 3.2.11
=> VZ-10242 - Update Coherence Operator to 3.2.11

release/builds/JenkinsfileForceCandidate
* Adding pre-release validation
=> VZ-10203 Adding pre-release validation to force job (#6402)

platform-operator/controllers/verrazzano/component/argocd/argocd.go, platform-operator/controllers/verrazzano/component/argocd/argocd_component.go, platform-operator/controllers/verrazzano/component/argocd/argocd_test.go, platform-operator/controllers/verrazzano/component/common/argocd.go
Backport of https://github.com/verrazzano/verrazzano/commit/e2ccce6a2a72e8f9992d96d18341a058f2304641
=> VZ-10181 backport argocd resource cleanup to 1.6

platform-operator/controllers/verrazzano/component/argocd/argocd.go, platform-operator/controllers/verrazzano/component/argocd/argocd_component.go, platform-operator/controllers/verrazzano/component/argocd/argocd_test.go, platform-operator/controllers/verrazzano/component/common/argocd.go
Backport of https://github.com/verrazzano/verrazzano/commit/e2ccce6a2a72e8f9992d96d18341a058f2304641
=> VZ-10181 backport argocd resource cleanup to 1.5

platform-operator/verrazzano-bom.json
=> Update verrazzano-bom.json with new image of fluentbit

platform-operator/controllers/verrazzano/component/rancher/rancher_uninstall.go
This PR removes repeated background messages:
- Refactors messages from progress to once.
=> VZ-10197: Cleanup uninstall log

tools/vz/cmd/analyze/analyze.go, tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/kontainerdrivers_test.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/test/cluster/kontainerdrivers/drivers-not-ready/cluster-snapshot/default/kontainerdriver.json, tools/vz/pkg/analysis/test/cluster/kontainerdrivers/drivers-ready/cluster-snapshot/default/kontainerdriver.json, tools/vz/pkg/helpers/vzcapture_capi.go
=> VZ-10276: add analyze of KontainerDriver resources (#6434)

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, tests/e2e/clusterapi/capi-overrides/capi_overrides_suite_test.go, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go, tests/e2e/pkg/clusterapi/clusterapi.go, tests/e2e/verify-install/clusterapi/clusterapi_test.go
Cherry pick from master branch
=> VZ-10112 - Add end-to-end test for clusterAPI overrides (#6433)

ci/JenkinsfilePeriodicTests, ci/kind/Jenkinsfile, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go
Back port from master to release-1.6
=> VZ-10112 - Add clusterAPI end-to-end test to a pipeline (#6444)

application-operator/mcagent/mcagent_cluster_secrets.go
=> MC Agent should sync its local cluster CA to the admin cluster even if the local CA is empty

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/helpers/command.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go
Invalidating the install process when missing the filename flag on `vz install VZ_CR.yaml`
=> vz-10001 cli should validate commands

application-operator/mcagent/mcagent_cluster_secrets_test.go
=> Add unit test for syncLocalClusterCAs in MC Agent

ci/periodic/JenkinsfileDistributions, release/builds/JenkinsfilePostPRT, release/builds/JenkinsfileScanReleaseBundle, release/scripts/scan_release_binaries.sh
=> Backport VZ-8838 to 1.4

ci/periodic/JenkinsfileDistributions, release/builds/JenkinsfilePostPRT, release/builds/JenkinsfileScanReleaseBundle, release/scripts/scan_release_binaries.sh
=> Backport VZ-8838 to 1.5

ci/periodic/JenkinsfileDistributions, release/builds/JenkinsfilePostPRT, release/builds/JenkinsfileScanReleaseBundle, release/scripts/scan_release_binaries.sh
=> Backport VZ-8838 to 1.6

tools/vz/pkg/bugreport/reportgen.go, tools/vz/pkg/helpers/vzhelper.go
Cherry pick of #6455 for release-1.6
=> VZ-10278: always capture CAPI resources (#6455)

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/helpers/command.go, tools/vz/cmd/install/install.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go
* added logic to validate cli commands
=> vz-10001 cli should validate commands (#6395)

ci/clusterAPI/JenkinsfileCAPI, tests/e2e/backup/helpers/common_helper.go, tests/e2e/clusterapi/capi/capiModels.go, tests/e2e/clusterapi/capi/capiTestInterface.go, tests/e2e/clusterapi/capi/capi_suite_test.go, tests/e2e/clusterapi/capi/capi_test.go, tests/e2e/clusterapi/capi/helpers.go, tests/e2e/clusterapi/capi/oci.go, tests/e2e/clusterapi/capi/prerequisites.go, tests/e2e/clusterapi/capi/templates/cluster-template-addons-new-vcn-securitylist.yaml, tests/e2e/clusterapi/capi/templates/cluster-template-addons-new-vcn.yaml, tests/e2e/clusterapi/capi/templates/cluster-template-addons.yaml, tests/e2e/clusterapi/capi/templates/cluster-template-verrazzano-resource.yaml, tests/e2e/clusterapi/capi/templates/ocnecontrolplanemoduledisabled.yaml, tests/e2e/clusterapi/capi/templates/ocnecontrolplanemoduleenabled.yaml, tests/e2e/clusterapi/capi/utils.go, tests/e2e/clusterapi/capi/variables.go, tests/e2e/config/scripts/v1beta1/install-verrazzano-kind-clusterAPI-enabled.yaml, tests/e2e/pkg/common.go
* VZ-9977: OCNE CAPI e2e tests with new VCN and VZ verify install
cherry-pick c9346f3
=> VZ-9977 backport capi automation pipeline changes

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/test/cluster/clusters/clusters-not-ready/cluster-snapshot/default/cluster.json, tools/vz/pkg/analysis/test/cluster/clusters/clusters-ready/cluster-snapshot/default/cluster.json, tools/vz/pkg/helpers/vzcapture_capi.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
cherry-pick changes from master
=> VZ-10280: back port analyze of rancher clusters to release-1.6

cluster-operator/controllers/vmc/sync_prometheus.go, cluster-operator/controllers/vmc/vmc_controller_test.go
=> VZ-10310.  Fix managed cluster scrape with production certs (#6451)

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/internal/util/files/files.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/test/cluster/cluster-api-clusters/clusters-not-ready/cluster-snapshot/c-nctzd/cluster.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api-clusters/clusters-ready/cluster-snapshot/c-nctzd/cluster.cluster.x-k8s.io.json
=> VZ-10278: add checking of cluster-api cluster resources to vz analyze (#6487)

ci/JenkinsfilePeriodicTests
=> VZ-9977: Add CAPI pipeline to periodic

ci/JenkinsfilePeriodicTests
=> VZ-9977 backport capi automation to periodics 

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/cluster_resource_utilization_dashboard.json
**Changes**
- Created a cluster resource utilization dashboard with Used, Max, and Percentage values for:
- CPU, Memory, and Storage
**Testing**
- Install a KinD multicluster and OKE cluster
- Verify that for each cluster, the metrics accurately reflect the cluster values
=> VZ-10130 Add the cluster resource utilization dashboard

platform-operator/verrazzano-bom.json
=> Promote OCNE updates

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano System/cluster_resource_utilization_dashboard.json
**Changes**
- Created a cluster resource utilization dashboard with Used, Max, and Percentage values for:
- CPU, Memory, and Storage
**Testing**
- Install a KinD multicluster and OKE cluster
- Verify that for each cluster, the metrics accurately reflect the cluster values
=> VZ-10130 Add the cluster resource utilization dashboard 

platform-operator/verrazzano-bom.json
- Service LB annotations for managed profile
=> VZ-10325: Update rancher image

platform-operator/verrazzano-bom.json
=> VZ-10325: Update rancher image (#6505)

platform-operator/helm_config/charts/fluentbit-opensearch-output/values.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
=> VZ:10026: Add configuration for argocd in fluentd and fluentbit (#6473)

release/builds/JenkinsfilePostPRT
=> remove empty stage

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/clusters/clusters-not-ready/cluster-snapshot/bundle.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/clusters/clusters-not-ready/cluster-snapshot/bundledeployment.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/clusters/clusters-ready/cluster-snapshot/bundle.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/clusters/clusters-ready/cluster-snapshot/bundledeployment.fleet.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
=> VZ-10281: Add analyze of Rancher bundle resources

platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component_test.go
**Changes**
- The is ready check uses label selectors to make sure the deployments for Istio are ready
**Testing**
- Deploy a cluster with egress gateway disabled and verify the readiness check works
- Deploy a cluster with all enabled and verify the readiness check works
=> VZ-10265 Check enabled istio deployments by label for readiness and availability check

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.1 to 1.6.2
=> Updating development version from 1.6.1 to 1.6.2

cluster-operator/controllers/vmc/argocd.go, cluster-operator/controllers/vmc/argocd_test.go, cluster-operator/controllers/vmc/testdata/bodyfortokentest.json, pkg/rancherutil/rancher_config.go, pkg/rancherutil/rancher_config_test.go, pkg/rancherutil/testdata/bodyfortokentest.json
=> Gfaeillo/vz 10005 (#6503)

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterregistration.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/bundledeployment.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/cluster.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/clustergroup.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/clusterregistration.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/bundledeployment.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/cluster.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/clustergroup.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/clusterregistration.fleet.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
cherry-pick 95e0c2d3ff31680c632766225ddd2f7226f5420e
=> VZ-10281: Back port analyze of clustergroups, clusterregistration and fleet clusters 

cluster-operator/controllers/vmc/argocd.go, cluster-operator/controllers/vmc/argocd_test.go, cluster-operator/controllers/vmc/testdata/bodyfortokentest.json, pkg/rancherutil/rancher_config.go, pkg/rancherutil/rancher_config_test.go, pkg/rancherutil/testdata/bodyfortokentest.json
Make changes for unit test for ArgoCD Bug
=> VZ-10005 Fix For ArgoCD Bug Where Unnecessary Rancher Tokens Were Being Created (#6503)

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterregistration.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/nodes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/node.management.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/node.management.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
=> VZ-10281:  vz analysis of Rancher node resources (#6548)

platform-operator/verrazzano-bom.json
Updates NGINX and OAM Kubernetes Runtime in release-1.4
=> VZ-8902: Update images for NGINX and OAM Kubernetes Runtime

platform-operator/verrazzano-bom.json
=> VZ-10301: Update cert-manager images to fix issues with image format

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogapps.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/app.catalog.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/gitrepo.fleet.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/app.catalog.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/gitrepo.fleet.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
=> VZ-10281: Add analyze of app and gitrepo resources - back port to 1.6

ci/JenkinsfilePeriodicTests, ci/ocne-cluster-driver/Jenkinsfile, tests/e2e/clusterapi/ocne-driver/environment.go, tests/e2e/clusterapi/ocne-driver/helpers.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_suite_test.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go, tests/e2e/clusterapi/ocne-driver/structs.go, tests/e2e/clusterapi/ocne-driver/variables.go, tests/e2e/pkg/common.go, tests/e2e/pkg/kubernetes.go
Backport of commits 5f3f04c2d133e9f8f45c1ca7cd7a7c967896f788 and 3206ff26ecc95c42d1a2d40e2413c89ef2cafe3e.
Automated tests for the OCNE Cluster Driver, covering the cases of cluster creation and basic cluster deletion.
=> VZ-9038: OCNE Driver Cluster Creation Tests

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managedcharts.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/namespaced/managedchart.management.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/namespaced/managedchart.management.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
=> VZ-10281: add checking of rancher managedChart resource

platform-operator/verrazzano-bom.json
=> VZ-10301: update cert-manager images

platform-operator/internal/monitor/monitor_test.go
The unit tests in question were using a channel to wait for a result to be available from a background operation. That test code was not working as intended and caused intermittent test failures. Here is how the test can fail:
1. The monitor `Run` function calls the operation
2. The operation runs and returns, the defer results in a value getting written to the "finished" channel
3. Before `Run` writes the operation result to the result channel, the unit test reads from the "finished" channel and is unblocked
4. The unit test calls `CheckResult` but because `Run` has not yet written the result to the result channel, `CheckResult` returns an error and the test expectations fail
There is no way to do this with a channel without modifying the monitor code itself. This PR replaces a …
=> Fix test, blocking channel not working as intended

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogapps.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterregistration.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitjobs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managedcharts.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/nodes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go, tools/vz/pkg/analysis/test/cluster/rancher/clusters-not-ready/cluster-snapshot/namespaced/gitjob.gitjob.cattle.io.json, tools/vz/pkg/analysis/test/cluster/rancher/clusters-ready/cluster-snapshot/namespaced/gitjob.gitjob.cattle.io.json, tools/vz/pkg/helpers/vzcapture_rancher.go
=> VZ-10281: Add analyze for gitjob

tests/e2e/clusterapi/ocne-driver/environment.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go
Fail ocne driver test suite if required environment variables are not set
=> Fail ocne driver test suite if required environment variables are not set

platform-operator/internal/monitor/monitor_test.go
Port unit test fix from release-1.6. See #6567 for details.
=> Fix test, blocking channel not working as intended (#6567)

platform-operator/internal/monitor/monitor_test.go
Backport unit test fix to release-1.5. See #6567 for details.
=> Fix test, blocking channel not working as intended (#6567) (release-1.5)

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides_test.go, platform-operator/controllers/verrazzano/testdata/test_bom_host_port.json
Backports https://github.com/verrazzano/verrazzano/pull/6555 to release-1.6
=> VZ-10362: Process the Cluster API image overrides when the image contains the port number, release-1.6

ci/periodic/JenkinsfileDistributions, ci/scripts/generate_vz_distribution.sh
=> Add image sizes output to distributions job

ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go
This PR fixes deriving latest release version, and edge cases for install and interim versions. Also, refactors the code for better maintainability.
=> VZ-9955: Refactor and fix derive versions for latest, install, and minor release versions. 

ci/periodic/JenkinsfileDistributions, ci/scripts/generate_vz_distribution.sh
=> backport image sizes to 1.5

ci/periodic/JenkinsfileDistributions, ci/scripts/generate_vz_distribution.sh
=> backport image sizes to 1.6

platform-operator/helm_config/charts/verrazzano-network-policies/templates/thirdparty-networkpolicy.yaml
=> VZ-10139: Add Thanos Compactor and Ruler to Istiod network policy

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.2 to 1.6.3
=> Updating development version from 1.6.2 to 1.6.3

ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, platform-operator/helm_config/charts/verrazzano-network-policies/templates/thirdparty-networkpolicy.yaml, tests/e2e/config/scripts/configure_thanos_storegateway_install.sh, tests/e2e/verify-install/thanos/thanos_test.go
=> VZ-10139 - add e2e test to make sure Thanos compactor comes up when enabled.

ci/upgrade-paths/Jenkinsfile, pkg/test/keycloakutil/keycloakutil.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go, platform-operator/controllers/verrazzano/reconcile/install_test.go, platform-operator/controllers/verrazzano/reconcile/upgrade_test.go, platform-operator/helm_config/charts/verrazzano-cluster-operator/templates/clusterrole.yaml
Backports https://github.com/verrazzano/verrazzano/pull/6513 to release-1.5
=> VZ-8082: Check whether Keycloak pod is ready before connecting to the running container, in release-1.5

ci/scripts/generate_vz_distribution.sh
Sort the image size list by image size and remove duplicates
=> Sort by image size and remove duplicates

ci/upgrade-paths/Jenkinsfile, pkg/test/keycloakutil/keycloakutil.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak.go, platform-operator/controllers/verrazzano/component/keycloak/keycloak_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/component/rancher/rancher_test.go
Backports https://github.com/verrazzano/verrazzano/pull/6513 to release-1.4
=> VZ-8082: Check whether Keycloak pod is ready before connecting to the running container, in release-1.4

ci/scripts/generate_vz_distribution.sh
backport sort by image size to 1.6
=> backport sort by image size to 1.6

ci/scripts/generate_vz_distribution.sh
backport sort by image size to 1.5
=> backport sort by image size to 1.5

tools/vz/pkg/analysis/internal/util/cluster/rancher.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogapps.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterregistration.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitjobs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managedcharts.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/nodes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher_test.go
=> fix analysis if namespaced rancher resources (#6611)

tools/vz/pkg/analysis/internal/util/cluster/clusterapi.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/common.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/machine.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/machinedeployment.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/ocicluster.infrastructure.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/ocimachine.infrastructure.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/ocneconfig.bootstrap.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/ocnecontrolplane.controlplane.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/machine.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/machinedeployment.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/ocicluster.infrastructure.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/ocimachine.infrastructure.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/ocneconfig.bootstrap.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/ocnecontrolplane.controlplane.cluster.x-k8s.io.json
=> VZ-10369: Add analysis of cluster-api resources (#6612)

tests/e2e/clusterapi/ocne-driver/helpers.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go
Validation tests for OCNE cluster driver deletion
=> VZ-9467: Validation tests for OCNE cluster driver deletion

tools/vz/pkg/analysis/internal/util/cluster/clusterapi.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/clusterresourceset.addons.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/machineset.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/clusterresourceset.addons.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/machineset.cluster.x-k8s.io.json
This pull request adds analysis of capi resources machinesets and clusterresourcesets to vz analyze.
=> VZ-10369: Add additional capi resources to vz analyze

tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitjobs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managedcharts.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/nodes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go
=> VZ-10168 - Improve formatting of vz analyze rancher and clusterapi

tools/vz/pkg/analysis/internal/util/cluster/clusterapi.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/clusterresourceset.addons.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-not-ready/cluster-snapshot/namespaced/machineset.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/clusterresourceset.addons.cluster.x-k8s.io.json, tools/vz/pkg/analysis/test/cluster/cluster-api/clusters-ready/cluster-snapshot/namespaced/machineset.cluster.x-k8s.io.json
=> VZ-10369: Add additional capi resources to vz analyze (#6623)

tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundledeployments.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/bundles.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/catalogs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clustergroups.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/clusterrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/fleetclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitjobs.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/gitrepos.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/kontainerdrivers.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managedcharts.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/managementclusters.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/nodes.go, tools/vz/pkg/analysis/internal/util/cluster/rancher/provisioningclusters.go
=> VZ-10168 - Improve formatting of vz analyze rancher and clusterapi (#6627)

tests/e2e/verify-none-profile/none_profile_test.go
=> VZ-10307: Backport Follow up PR to update allowedNamespaces and update tests

platform-operator/controllers/verrazzano/component/common/namespace.go, platform-operator/controllers/verrazzano/component/common/namespace_test.go
Backport PR to merge into release branch
=> VZ-10205: Backport changes to conditionally install unnecessary namespaces #6618

ci/ocne-cluster-driver/Jenkinsfile, tests/e2e/backup/helpers/common_helper.go, tests/e2e/clusterapi/ocne-driver/helpers.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go, tests/e2e/clusterapi/ocne-driver/structs.go
Adds one update test for the OCNE cluster driver.
Code refactoring to make adding more update test cases easier and reduce code repetition.
=> VZ-9466: Update test for OCNE cluster driver

ci/JenkinsfileBackendTests
vz-10357 add OKE examples into backend tests
=> vz-10357 add OKE examples into backend tests

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go, platform-operator/apis/verrazzano/webhooks/common.go
Provided logic to update VZ install with failed pods
=> vz 9480 validating webhook rejects updates

platform-operator/verrazzano-bom.json
Fluentbit operator image updated to the latest version.
=> Update fluent-operator image 

tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go
Change doc refs for cluster api resource issues found with vz analyze.
=> VZ-10369: Change doc refs for cluster api resource issues

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go
=> VZ-9481 Fix ingress issues

tests/e2e/clusterapi/ocne-driver/environment.go
=> Fix check for OCNE configmap

ci/clusterAPI/JenkinsfileCAPI, tests/e2e/clusterapi/capi/helpers.go, tests/e2e/clusterapi/capi/oci.go, tests/e2e/clusterapi/capi/prerequisites.go, tests/e2e/clusterapi/capi/variables.go
=> VZ-10467: Update CAPI pipeline for k8s1-26 behaviour change

tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusterresourcesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/clusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinedeployments.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/machinesets.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ociclusters.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocimachines.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocneconfigs.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi/ocnecontrolplanes.go, tools/vz/pkg/analysis/internal/util/cluster/clusterapi_test.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go
=> VZ-10369: Change doc refs for cluster api resource issues (#6665)

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install.go, platform-operator/controllers/verrazzano/component/rancher/rancher_install_test.go
=> VZ-10358: remove system-library catalog during rancher post upgrade

platform-operator/helm_config/charts/verrazzano-grafana-dashboards/dashboards/Verrazzano Monitoring/thanos_overview.json
**Changes**
- Added the Ruler as a supported component
- Update some of the inaccurate queries to more properly reflect the status
**Testing**
- Install the Grafana Dashboard with all Thanos components and make sure the queries render correctly
Images from the Dashboard:
=> VZ-10148 Update the Thanos Grafana dashboard for the new components

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go, platform-operator/apis/verrazzano/webhooks/common.go
Introduced changes to verify Verrazzano Platform Operator is singleton
=> vz-9480 validating webhook rejects updates

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.6 to 1.4.7
=> Updating development version from 1.4.6 to 1.4.7

platform-operator/verrazzano-bom.json
=> Update BOM Images For 1.4.7

ci/a-la-carte/Jenkinsfile, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go
=> Clean up Jaeger ingress during uninstall, increase uninstall timeout for a-la-carte tests

platform-operator/verrazzano-bom.json
Update To Correct BOM Images for 1.4.7
=> Update correct BOM Images for 1.4.7

platform-operator/verrazzano-bom.json
=> VZ-10467: update rancher image with kontainer driver change

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
=> Updating development version from 1.5.4 to 1.5.5

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go
* Added logic to reinstall VPO with failed pods
=> Backport 9480 release 1.4

platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1alpha1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_webhook_test.go, platform-operator/apis/verrazzano/validators/validate.go, platform-operator/apis/verrazzano/validators/validate_test.go, platform-operator/apis/verrazzano/webhooks/common.go
* Added logic to reinstall VPO with failed pods
=> vz-9480 validating webhook rejects updates (#6678)

platform-operator/helm_config/overrides/thanos-values.yaml
=> Enable the Prometheus rules that are part of the Thanos Helm chart.

platform-operator/metricsexporter/metricsexporter_utils.go
=> VZ-10390: metricsexporter spamming errors in the dev lre (#6677)

platform-operator/verrazzano-bom.json
fix parser issue in fluent-operator by cherrypicking the fix from master
=> VZ-9988: fix parser issue in fluent-operator(cherry-picked)

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.5 to 1.5.6
=> Updating development version from 1.5.5 to 1.5.6

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.3 to 1.6.4
=> Updating development version from 1.6.3 to 1.6.4

platform-operator/verrazzano-bom.json
Add correct versioning for top level components
=> Add correct versioning for top level components

platform-operator/verrazzano-bom.json
Update BOM Images After 1.5.5 Release
=> Update BOM images After 1.5.5 Release

platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#6710
=> Revert "Update BOM images After 1.5.5 Release"

CHANGES.md, THIRD_PARTY_LICENSES.txt, cluster-operator/controllers/vmc/sync_thanos.go, go.mod, go.sum, pkg/k8s/webhook/webhook.go, pkg/k8s/webhook/webhook_test.go, platform-operator/Dockerfile, platform-operator/controllers/verrazzano/component/coherence/coherence_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/rancherbackup/testdata/test-bom.json, platform-operator/helm_config/overrides/istio-cr.yaml, platform-operator/repos/ol8-olcne17.repo, platform-operator/verrazzano-bom.json
=> VZ-9661: Upgrade to Istio 1.17.2

platform-operator/verrazzano-bom.json
Updating BOM After 1.5.5 Release
=> Updating BOM After 1.5.5 Release

platform-operator/controllers/verrazzano/reconcile/install.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, platform-operator/controllers/verrazzano/reconcile/uninstall_component.go, platform-operator/controllers/verrazzano/reconcile/upgrade.go, platform-operator/controllers/verrazzano/reconcile/upgrade_component.go
Suppress repeated install component message by using Once() in logger
=> vz-10214 repeated installing components message

ci/cron/Jenkinsfile, ci/cron/JenkinsfileBackend
Using correct .txt file for trigger
=> VZ-10259 Updating OS file used

THIRD_PARTY_LICENSES.txt, go.mod, tests/e2e/clusterapi/ocne-driver/environment.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go, tests/e2e/clusterapi/ocne-driver/structs.go
=> VZ-10445: Automated test for OCNE cluster upgrade

ci/JenkinsfileBackendTests, ci/JenkinsfilePeriodicTests, ci/cron/Jenkinsfile, ci/cron/JenkinsfileBackend
=>  VZ-10259 URL Trigger is not working as we expect (#6672)

platform-operator/controllers/configmaps/overrides/controller.go, platform-operator/controllers/controller_utils.go, platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/controller_test.go
=> Fix panic issue causing due to logger

tools/scripts/generate_operator_yaml.sh
Fixes an unbound variable in generate_operator_yaml.sh
=> Fix generate_operator_yaml script bug

platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator.go, platform-operator/controllers/verrazzano/component/prometheus/operator/promoperator_test.go, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/prometheus/prometheus.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/values.yaml
=> Attempt to switch off the Alertmanager integration for Prometheus

examples/sock-shop/helidon/sock-shop-comp.yaml, examples/sock-shop/micronaut/sock-shop-comp.yaml, examples/sock-shop/spring/sock-shop-comp.yaml
=> VZ-10464 - SockShop release updates - Helidon 2.0.1, Spring 1.3, Micronaut 2.1.1

ci/ocne-cluster-driver/Jenkinsfile, tests/e2e/clusterapi/ocne-driver/helpers.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_suite_test.go, tests/e2e/clusterapi/ocne-driver/ocne_cluster_driver_test.go
This removes all cluster creation test cases except for 1 bare minimum case. This is a temporary measure to help fix the recent test failures.
=> OCNE Cluster Driver Tests - Single Cluster Creation

platform-operator/verrazzano-bom.json
=> VZ-10506: Update fluentbit image with reduced size

platform-operator/verrazzano-bom.json
Update fluentbit image with reduced size
=> VZ-10506: Update fluentbit image with reduced size (#6769)

platform-operator/verrazzano-bom.json
Cherry pick from master branch
=> VZ-10551: Update rancher image to get OKE kontainer driver 1.8.4 (#6761)

platform-operator/controllers/controller_utils.go
=> VZ-10641:fixed noise in config map creation

platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, platform-operator/controllers/verrazzano/testdata/test_bom_additional_rancher.json
=> VZ-7895: Handle test case where BOM image names have suffixes for Rancher additional images

platform-operator/controllers/verrazzano/component/rancher/rancher.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component.go, platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go
Back port these changes from master to release-1.6
=> VZ-10561: support old and new locations for Rancher branding images (backport)

platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/install_component.go, platform-operator/controllers/verrazzano/reconcile/install_component_test.go
Backport of VPO reconcile error metric fix to release-1.6. See #6775 for details.
=> Fix VPO reconcile error metric (#6775) (release-1.6)

Jenkinsfile, ci/chaos/JenkinsfileResiliencyTrigger
VZ-10488 Add Check To VZ Job and Upgrade Resiliency Job to See If VZ Helper Was Ran
=> VZ-10488 Add Check To VZ Job to See If VZ Helper Was Ran (#6776)

platform-operator/verrazzano-bom.json
=> VZ-10533: Update Istio 1.14.3 images

tests/e2e/clusterapi/capi/helpers.go
=> VZ-10596 vz capi health backport

CHANGES.md
=> VZ-3261 Add changes note for the Istio status update

platform-operator/capi/bootstrap-ocne/v1.7.0/bootstrap-components.yaml, platform-operator/capi/control-plane-ocne/v1.7.0/control-plane-components.yaml, platform-operator/verrazzano-bom.json
* VZ-10569: Support for cluster class
cherry-pick 8d94ab7
=> VZ-10569 cluster class support (#6807)

platform-operator/experimental/controllers/module/component-handler/installupdate/install_update_handler.go
Add 2 more checks for error to return a requeue.
=> VZ-10451 return requeue if error in install handler

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.4 to 1.6.5
=> Updating development version from 1.6.4 to 1.6.5

ci/scan-results/JenkinsfileUpload
Sends slack alert to defined owners when uploading a scan result fails
=> VZ-10424: Send slack alert when uploading a scan result fails

ci/JenkinsfileBackendTests
This PR increases the number of parallel jobs to avoid timeout error.
=> Increase the number of parallel jobs

ci/olcne/Jenkinsfile, ci/scripts/ocne_delete_lb_subnet.sh, ci/scripts/ocne_ociccm.sh
change the terraform to https://github.com/oracle-terraform-modules/terraform-oci-ocne/
=> acceptance test on OCNE

go.mod, go.sum, platform-operator/controllers/verrazzano/component/certmanager/certmanager/certmanager_component.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/common/watch/watch.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/experimental/controllers/integration/cascade/manager.go, platform-operator/experimental/controllers/integration/cascade/reconciler.go, platform-operator/experimental/controllers/integration/single/manager.go, platform-operator/experimental/controllers/integration/single/reconciler.go, platform-operator/experimental/controllers/module/component-handler/common/handler_utils.go, platform-operator/experimental/controllers/module/component-handler/common/vzcomponent_status.go, platform-operator/experimental/controllers/module/component-handler/delete/delete_handler.go, platform-operator/experimental/controllers/module/component-handler/factory/factory.go, platform-operator/experimental/controllers/module/component-handler/installupdate/install_update_handler.go, platform-operator/experimental/controllers/module/component-handler/migration/migration.go, platform-operator/experimental/controllers/module/component-handler/upgrade/upgrade_handler.go, platform-operator/experimental/controllers/verrazzano/finalizer.go, platform-operator/experimental/controllers/verrazzano/manager.go, platform-operator/experimental/controllers/verrazzano/reconciler.go, platform-operator/experimental/controllers/verrazzano/watcher.go, platform-operator/internal/operatorinit/run_operator.go, platform-operator/mocks/component_mock.go
Set the controller MaxConcurrentReconcile to 30 so that the module controllers run in parallel.
=> VZ-10544 run module controllers in parallel

platform-operator/controllers/verrazzano/component/common/vmi.go, platform-operator/controllers/verrazzano/component/mysql/mysql_component.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component_test.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component_test.go, platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component_test.go
=> VZ-10414: Verrazzano CR webhook should allow for empty volume fields

CHANGES.md
Update CHANGES.md to include information on Thanos Ruler and Compactor, and Prometheus rules.
=> Add Thanos and Prometheus rule info

ci/clusterAPI/JenkinsfileCAPI, tests/e2e/clusterapi/capi/capiModels.go, tests/e2e/clusterapi/capi/capiTestInterface.go, tests/e2e/clusterapi/capi/capi_test.go, tests/e2e/clusterapi/capi/helpers.go, tests/e2e/clusterapi/capi/templates/cluster-template-addons.yaml, tests/e2e/clusterapi/capi/templates/cluster-template-cluster-class.yaml, tests/e2e/clusterapi/capi/templates/ocnecontrolplanemoduledisabled.yaml, tests/e2e/clusterapi/capi/templates/ocnecontrolplanemoduleenabled.yaml, tests/e2e/clusterapi/capi/variables.go
=> VZ-10601 cluster class pipeline

platform-operator/verrazzano-bom.json
=> VZ-10439: Back port uptake of Rancher 2.7.5 dashboard

release/scripts/get_ocir_scan_results.sh
backport scan use latest tweak to 1.5
=> backport scan use latest tweak to 1.5

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml
Add annotation to authrpoxy deployment to automatically pick AuthProxy config.
=> VZ-10494: Add annotation to authrpoxy deployment to automatically pick configuration

platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml
Add annotation to authrpoxy deployment to automatically pick config
=> VZ-10494: Add annotation to authrpoxy deployment to automatically pick config

application-operator/controllers/webhooks/appconfig_defaulter.go, tests/e2e/verify-infra/vmi/vmi_test.go
- Increase timeout from 1min to 3min
- Change VAO webhook logs to avoid conflict in OS
=> Increase timeout for verify-vmi test

tests/e2e/config/scripts/v1beta1/install-verrazzano-ocne.yaml
Cherry pick of https://github.com/verrazzano/verrazzano/commit/1d07c1821105e4fb61d945762ae6d79e8f436e85
=> VZ-9863: Fix incorrect vz yaml (#6085)

platform-operator/constants/constants.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
Create a module label with the owning VZ CR
=> VZ-10702 add VZ cr owner id to module label

CHANGES.md, platform-operator/Dockerfile, platform-operator/verrazzano-bom.json
Uptake Istio 1.15.7 in release-1.5
=> VZ-10583: Uptake Istio 1.15.7 in release-1.5

CHANGES.md, platform-operator/Dockerfile, platform-operator/verrazzano-bom.json
This reverts commit 37fa574fd2e3462d6639002aac350a3fe7f4aed7.
Reverting #6848
=> Revert "VZ-10583: Uptake Istio 1.15.7 in release-1.5 (#6848)"

authproxy/Dockerfile, authproxy/Makefile, authproxy/PROJECT, authproxy/README.md, authproxy/main.go
**Changes**
- Add new directory for the Authproxy
- Create boilerplate files for the initial setup of the Authproxy
=> VZ-10647 create boilerplate files for the Authproxy

tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/e2e/pkg/common.go
Add additional check during pod lookup to identify whether pod is misconfigured with "bad" IP address
=> VZ-10637: add check for bad IP

ci/kind/Jenkinsfile, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/e2e/pkg/common.go
Backport of change in master plus enabling full cluster dumps for failed tests (in case the issue manifests)
=> backport test changes and enable full cluster dump on test failures

platform-operator/thirdparty/charts/rancher/Chart.yaml, platform-operator/thirdparty/charts/rancher/templates/deployment.yaml, platform-operator/thirdparty/charts/rancher/values.yaml
Backport of Rancher Helm chart enhancement to release-1.6. See #6880 for details.
=> VZ-10757: Rancher Helm chart enhancement (#6880) (release-1.6)

authproxy/src/proxy/proxy.go
=> Outline of work in authproxy's proxy.go

ci/kind/Jenkinsfile
=> VZ-10635: Run console test in a separate stage in kind-acceptance test bp

platform-operator/Makefile, platform-operator/verrazzano-bom.json, tools/scripts/generate_bom.sh
Adds Auth Proxy to the BOM, updates the BOM generation script to replace the Auth Proxy image and tag placeholders with the actual values.
=> VZ-10649: Add new Auth Proxy image to BOM

platform-operator/controllers/verrazzano/reconcile/controller.go, platform-operator/controllers/verrazzano/reconcile/controller_context.go, platform-operator/controllers/verrazzano/reconcile/install.go, platform-operator/controllers/verrazzano/reconcile/uninstall.go, platform-operator/controllers/verrazzano/reconcile/upgrade.go, platform-operator/experimental/controllers/verrazzano/finalizer.go, platform-operator/experimental/controllers/verrazzano/reconciler.go
Change the way the controllers are synced to eliminate gaps.
=> VZ-10544 sync controllers

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.7 to 1.4.8
=> Updating development version from 1.4.7 to 1.4.8

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.6 to 1.5.7
=> Updating development version from 1.5.6 to 1.5.7

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.5 to 1.6.6
=> Updating development version from 1.6.5 to 1.6.6

go.mod, go.sum
Use new module packge to prevent concurrent reconcile of same resource.
=> VZ-10544 use new module package to prevent concurrent reconcile

authproxy/src/cors/cors.go, authproxy/src/cors/cors_test.go, authproxy/src/proxy/proxy.go, authproxy/src/proxy/proxy_test.go
=> VZ-10782 - add CORS handling to auth proxy v2

platform-operator/verrazzano-bom.json
=> Update BOM to 1.4.8

platform-operator/verrazzano-bom.json
=> VZ-10471: Update vmo image

ci/kind/Jenkinsfile, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go
=> VZ-10679: Cluster API version overrides not working correctly (#6878)

ci/kind/Jenkinsfile, tests/e2e/pkg/common.go
Separate the test into its own stage to avoid resource contention.
=> VZ-10637 run weblogic trait test separately to avoid resource contention (backport to release-1.5)

authproxy/main.go, authproxy/src/config/config.go, authproxy/src/config/config_test.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/authproxy-oidc-config.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml
Updated original PR and removed unit test code that's flakey until a permanent fix is implemented. See original PR #6915.
=> VZ-10788: Add OIDC config to Auth Proxy v2

ci/kind/Jenkinsfile, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/e2e/pkg/common.go
Move test to address resource contention issues
=> VZ-10637 move weblogic ingress trait to separate stage (release-1.6 backport)

pkg/helm/helmcli.go, pkg/helm/helmcli_test.go, platform-operator/controllers/verrazzano/component/authproxy/authproxy_component_test.go, platform-operator/controllers/verrazzano/component/fluentd/fluentd_component_test.go, platform-operator/controllers/verrazzano/component/grafana/grafana_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component.go, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/controllers/verrazzano/component/istio/istio_install.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/registry/registry_test.go, platform-operator/controllers/verrazzano/component/spi/component.go, platform-operator/controllers/verrazzano/component/vmo/vmo_component_test.go, platform-operator/controllers/verrazzano/fake_component_test.go, platform-operator/controllers/verrazzano/uninstall_component.go, platform-operator/controllers/verrazzano/upgrade_test.go, platform-operator/mocks/component_mock.go
Backports fix for VZ-10766 to release-1.4 (based of release-1.5 backport).
=> VZ-10766, VZ-10667.  Backport to release-1.4

ci/kind/Jenkinsfile, tests/e2e/loggingtrait/weblogicworkload/weblogic_loggingtrait_test.go, tests/e2e/pkg/common.go
Some logging improvements and running the failing test separately
=> VZ-10637 backport test fix to release 1.4

authproxy/main.go, authproxy/src/auth/authstub.go, authproxy/src/proxy/proxy.go, authproxy/src/proxy/proxy_test.go, go.mod, go.sum, pkg/httputil/httputil.go, tests/e2e/pkg/web.go
**Changes**
- Add support for watch
- Add support for kubectl integration
- Add scaffolding for OIDC client integration
**Testing**
- Install on cluster and see if API requests can be made using kubectl through the authproxy
=> VZ-10630 Add watch support and OIDC integration scaffolding

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go
=> Revert VZ 10404

ci/kind/Jenkinsfile
Reducing test failures due to resource contention by adopting the same approach as other release branches
=> VZ-10637 redistribute tests in 1.4 release branch to align more closely with other release branches

platform-operator/controllers/secrets/install_override_secret.go, platform-operator/controllers/secrets/secrets_controller.go, platform-operator/controllers/secrets/secrets_controller_test.go, platform-operator/controllers/secrets/verrazzano_tls_secret.go, platform-operator/controllers/secrets/verrazzano_tls_secret_test.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer.go
Cherry picked fix from master branch
=> VZ-10529: Self-signed CA Certificate Expiry Causes Upgrade to Hang

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go
Original commit 81802cf4 was reverted but I think this problem ended up not being caused by my commit and the problematic commit was reverted as well. This commit should be good to go back in
=> VZ-10404 Remerge CAPI fix after revert

platform-operator/thirdparty/charts/prometheus-community/prometheus-node-exporter/values.yaml, platform-operator/thirdparty/charts/rancher-backup/templates/hardened.yaml, platform-operator/thirdparty/charts/rancher-backup/templates/psp.yaml, platform-operator/thirdparty/charts/rancher-backup/values.yaml
=> VZ-10758: Set prometheus-node-exporter and rancher-backer PSP default to false

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
=> VZ-10856: Fix bug where WLS cluster resource was not being updated

authproxy/main.go, authproxy/src/auth/authstub.go, authproxy/src/proxy/proxy.go, authproxy/src/proxy/proxy_test.go
=> VZ-10783 - move authproxy v2 authentication to an interface

platform-operator/controllers/verrazzano/component/argocd/module_integration.go, platform-operator/controllers/verrazzano/component/argocd/module_integration_test.go
Add config mapping for ArgoCD to pick up changes in nginx/dns/certs.
=> VZ-10868.  Add ArgoCD configuration hooks for changes in DNS/certs/ingress

pkg/controller/requeue.go
=> fix requeue revert copyright

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.6 to 1.6.7
=> Updating development version from 1.6.6 to 1.6.7

examples/bobs-books/bobs-books-comp.yaml
=> VZ-10580 - Update Coherence version in bobs-books example

platform-operator/verrazzano-bom.json
=> Update BOM to 1.6.7

tools/scripts/k8s-dump-cluster.sh
Dumps module resources to `verrazzano-modules.json` in the full cluster dump.
=> VZ-10876.  Add module resources to the cluster dump

tests/e2e/update/overrides/overrides_helper_test.go, tests/e2e/update/overrides/overrides_test.go
Had to disable the other part of the `monitorChanges=false` overrides test case for the modules work.
=> VZ-10868.  Fix disabled overrides test

tests/e2e/workloads/weblogic-cluster/weblogic_workload_test.go, tests/testdata/test-applications/weblogic/hello-weblogic/hello-wls-cluster-comp-update.yaml
=> VZ-10856: Update weblogic-cluster workload example to test increasing cluster replicas

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update WebLogic Kubernetes Operator to 4.0.9 and WebLogic Monitoring Exporter to 2.1.5.
=> WebLogic Kubernetes Operator 4.0.9 and WebLogic Monitoring Exporter 2.1.5

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update Verrazzano to use WKO 4.1.2 and WME 2.1.5.
=> WebLogic Kubernetes Operator 4.1.2 and WebLogic Monitoring Exporter 2.1.5

platform-operator/verrazzano-bom.json
Update opensearch image tag in BOM
=> VZ-10655: Opensearch Image tag Bom update

platform-operator/verrazzano-bom.json
BP for VZ-10655: Opensearch Image tag Bom update #6993
=> VZ-10655: Opensearch Image tag Bom update #6993

platform-operator/helm_config/overrides/dex-values.yaml, platform-operator/verrazzano-bom.json
=> VZ-10914: verrazzano theme changes

cluster-operator/apis/clusters/v1alpha1/common_webhook.go, cluster-operator/apis/clusters/v1alpha1/common_webhook_test.go, cluster-operator/apis/clusters/v1alpha1/ocneoci_types.go, cluster-operator/apis/clusters/v1alpha1/ocneoci_webhook.go, cluster-operator/apis/clusters/v1alpha1/oke_types.go, cluster-operator/apis/clusters/v1alpha1/oke_webhook.go, cluster-operator/apis/clusters/v1alpha1/oke_webhook_test.go, cluster-operator/apis/clusters/v1alpha1/quickcreate_types.go, cluster-operator/apis/clusters/v1alpha1/testdata/okequickcreate_invalid.yaml, cluster-operator/apis/clusters/v1alpha1/testdata/okequickcreate_valid.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_ocneociquickcreates.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_okequickcreates.yaml
Implement webhooks for OKE Quick Create clusters.
=> VZ 10653: OKE Quick Create Webhooks

cluster-operator/controllers/quickcreate/ociocne/template/addons/addons.goyaml, cluster-operator/main.go
- Enable the quick create controllers by default
- allow using instance principal for ocne clusters
=> Enable quick create controllers

authproxy/main.go, platform-operator/helm_config/charts/verrazzano-authproxy/templates/authproxy-oidc-config.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-ingress.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/values.yaml, platform-operator/helm_config/charts/verrazzano/templates/authorizationpolicy.yaml, platform-operator/helm_config/charts/verrazzano/values.yaml
=> Add a flag to enable installing the auth proxy v2 container and ingress (disabled by default)

cluster-operator/controllers/quickcreate/controller/controller.go, cluster-operator/controllers/quickcreate/ociocne/ociocne_controller.go, cluster-operator/controllers/quickcreate/ociocne/ociocne_controller_test.go, cluster-operator/controllers/quickcreate/oke/oke_controller.go, cluster-operator/controllers/quickcreate/oke/oke_controller_test.go, cluster-operator/internal/operatorinit/run_operator.go
Add resource loggers for quick create controllers.
=> Quick Create resource loggers

.gitignore, Jenkinsfile, ci/kind/Jenkinsfile, ci/scripts/prepare_jenkins_at_environment.sh, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/templates/deployment.yaml, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go, tests/e2e/config/scripts/create-github-token-secret.sh, tests/e2e/pkg/kubernetes.go
=> VZ-10679 Cluster API version overrides not working correctly. (#7031)

CHANGES.md
add release notes for quick create
=> Quick Create release notes

platform-operator/verrazzano-bom.json
update OS/OSD and VMO image to include security plugin
=> VZ-8191: VZ-8190: update OS/OSD and VMO image to include security image

application-operator/controllers/wlsworkload/weblogicworkload_controller.go
Cleanup of VZ-10780 code to remove unneeded code path
=> VZ-10780 code cleanup

go.mod, go.sum, platform-operator/experimental/controllers/verrazzano/vzstatus.go
Use new module package that logs action done, like installing.
=> VZ-10706 use new module package that logs action done

platform-operator/controllers/verrazzano/component/dex/module_integration.go, platform-operator/controllers/verrazzano/component/dex/module_integration_test.go
Initial Dex module integration hooks.
=> VZ-10968.  Dex module integration

ci/backup/JenkinsfileAlllBackupKinDTest, ci/chaos/Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileUpdateDuringInstall, ci/generic/Jenkinsfile, ci/generic/Jenkinsfile-singletarget, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/psr/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/test-examples/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade-paths/Jenkinsfile
This PR contains changes to move over jenkins jobs under verrazzano dir to JAO
=> VZ-8815: Migrate remaining jenkins jobs over to JAO 

tools/vz/cmd/helpers/vpo.go
In this PR, filtering is added to the VZ CLI, so unnecessary output is not displayed to the user.
=> Refine Output in VZ CLI

cluster-operator/controllers/vmc/vmc_controller.go, cluster-operator/controllers/vmc/vmc_controller_test.go
implements https://github.com/verrazzano/verrazzano/pull/7049#discussion_r1327185689
=> VZ-10969: namespace not required while fetching namespace object

platform-operator/verrazzano-bom.json
pdate OSD image to include reporting plugin
=> Update OSD image to include reporting plugin

release/scripts/scan_release_binaries.sh
=> vz-10832 Fix the scan summary handling

release/scripts/scan_release_binaries.sh
=> Backport VZ-10832 to 1.6

release/scripts/scan_release_binaries.sh
=> Backport VZ-10832 to 1.5

release/scripts/scan_release_binaries.sh
=> Backport VZ-10832 to 1.4

platform-operator/verrazzano-bom.json
Refreshes ArgoCD and Redis images
=> VZ-10568: Refresh ArgoCD and Redis images

platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
=> VZ-8158: fix queries for Kubernetes/Persistent Volume grafana dashboard

tools/vz/cmd/helpers/vpo.go
Add additional filtering for modules
=> Add additional filtering for modules

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
backport Trivy scan handling fix to 1.6
=> VZ-11038 backport to 1.6

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
backport Trivy scan handling fix to 1.5
=> VZ-11038 backport to 1.5

ci/scan-results/Jenkinsfile, release/scripts/scan_bom_images.sh
backport Trivy scan handling fix to 1.4
=> VZ-11038 backport to 1.4

Jenkinsfile, platform-operator/controllers/verrazzano/component/helm/helm_component_test.go, platform-operator/helm_config/charts/verrazzano-platform-operator/values.yaml, platform-operator/internal/config/config.go
Enable the module integration feature so it is on by default.
=> VZ-10706 enable module integration by default

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh
BP for VZ-10850 Build automation that notifies when image sizes have increased (https://github.com/verrazzano/verrazzano/pull/7057)
=> VZ-10850 Build automation that notifies when image sizes have increased (#7057)

application-operator/controllers/ingresstrait/ingresstrait_controller_test.go, application-operator/controllers/navigation/unstructured_test.go, application-operator/controllers/navigation/workload_test.go, application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go, application-operator/internal/operatorinit/run_webhook.go
Just a few cleanup tasks completed from a SonarCloud perspective.
=> NO JIRA - SonarCloud Cleanup

ci/JenkinsfilePeriodicTests
Move HA tests to wait:false to ignore them for now until issues triaged
=> Move HA tests to wait:false to ignore them for now until issues triaged

ci/JenkinsfilePeriodicTests
=> Quarantine HA tests in master

ci/JenkinsfilePeriodicTests
=> Quarantine HA tests in 1.6

ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileUpdateDuringInstall, ci/kind/Jenkinsfile, ci/uninstall/Jenkinsfile
Turn off messages for ci channel
=> Turn off messages for ci channel

tests/e2e/pkg/names.go, tests/e2e/pkg/oci/compute.go, tests/e2e/pkg/oci/containerengine.go, tests/e2e/quickcreate/context.go, tests/e2e/quickcreate/oci.go, tests/e2e/quickcreate/quickcreate_suite_test.go, tests/e2e/quickcreate/quickcreate_test.go, tests/e2e/quickcreate/templates/ociclusteridentity.goyaml, tests/e2e/quickcreate/templates/ocneoci.goyaml, tests/e2e/quickcreate/templates/oke.goyaml
Add test suite for quick create clusters. OKE and OCNEOCI are included. The suite was written in such a way that other quick create types could be added in the future.
=> VZ 10913: Quick Create Test Suite

platform-operator/verrazzano-bom.json
=> VZ-10458: update redis version

platform-operator/verrazzano-bom.json
=> VZ-10458: update redis (#7104)

platform-operator/helm_config/charts/verrazzano-fluentd/templates/daemonset.yaml
=> VZ-11118: Add annotation to fluentd dameonset to automatically pick configuration

platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go, platform-operator/apis/verrazzano/v1beta1/verrazzano_types.go
=> VZ-11099 update the Install Override comments for API generation

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.7 to 1.6.8
=> Updating development version from 1.6.7 to 1.6.8

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.5.7 to 1.5.8
=> Updating development version from 1.5.7 to 1.5.8

.verrazzano-development-version, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.4.8 to 1.4.9
=> Updating development version from 1.4.8 to 1.4.9

platform-operator/verrazzano-bom.json
=> Update BOM to 1.5.8

platform-operator/verrazzano-bom.json
=> Update BOM to 1.6.8

platform-operator/verrazzano-bom.json
=> Update BOM to 1.4.9

ci/cron/JenkinsfileBackend
=> Fix backend test cron 1.6

ci/cron/JenkinsfileBackend
=> Fix backend test cron 1.5

ci/cron/JenkinsfileBackend
=> Fix backend test cron 1.4

platform-operator/verrazzano-bom.json
update VMO, OS and OSD image to disable the security plugins.
=> Update VMO, OS and OSD images to latest version

cluster-operator/apis/clusters/v1alpha1/oke_webhook.go, cluster-operator/controllers/quickcreate/oke/template/cluster/cluster.goyaml, cluster-operator/controllers/quickcreate/oke/template/nodes/nodes.goyaml
OKE Quick Create with NPN requires pod subnet.
=> Quick Create with NPN

platform-operator/verrazzano-bom.json
update VMO, OS, OSD to latest version to disable the security plugins.
=> update VMO, OS, OSD to latest version

cluster-operator/controllers/quickcreate/oke/template/cluster/cluster.goyaml
Resolves issues with OKE Quick Create VCN
=> Quick Create OKE VCN Fixes

platform-operator/verrazzano-bom.json
Refresh images using latest Oracle Linux image.
=> VZ-11084: Refresh Rancher images for release-1.5

platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component.go, platform-operator/controllers/verrazzano/component/prometheus/pushgateway/pushgateway_component_test.go
This PR fixes an upgrade bug where Prometheus Pushgateway failed to upgrade to the latest from a previous release. This bug was introduced when the Pushgateway Helm chart was upgraded recently.
The problem is that the Helm chart is incompatible with previous versions of the chart. The Pushgateway deployment needs to be deleted prior to running Helm upgrade, otherwise the Helm upgrade fails with an error stating that an attempt is being made to update an immutable field in the deployment.
I tested this by installing 1.6.7 with Prometheus Pushgateway enabled, and then upgrading. I verified that the upgrade completes and that metrics are correctly scraped from Pushgateway.
=> Fix Prometheus Pushgateway upgrade bug

tests/e2e/config/scripts/looping-test/verify_uninstall.sh
=> Fix copyright failure due to a revert

platform-operator/verrazzano-bom.json
=> VZ-9875: update component images

platform-operator/verrazzano-bom.json
=> VZ-11162: Refresh component images

pkg/k8s/ready/statefulset_ready.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch.go, platform-operator/controllers/verrazzano/controller/reconciler.go, tools/psr/backend/pkg/opensearch/opensearch.go
=> update condition for opensearch ready

tests/e2e/backup/helpers/common_helper.go
=> VZ-10825: Fix OS backup tests

platform-operator/controllers/verrazzano/controller/reconciler.go, platform-operator/internal/operatorinit/run_operator.go
=> Added Verrazzano Component Resource Metrics to the new controller

platform-operator/controllers/verrazzano/controller/reconciler.go, platform-operator/internal/operatorinit/run_operator.go
=> Fix Null Pointer Exception 

platform-operator/controllers/verrazzano/controller/reconciler.go
=> Remove call to metric error 

CHANGES.md, platform-operator/verrazzano-bom.json
**Changes**
- Update the Alertmanager Image
**Testing**
- Install on a local cluster and verify that rules get transferred and UI is accessible
=> VZ-11175 Update Alertmanager Image version

platform-operator/helm_config/charts/verrazzano-fluentd/templates/fluentd-config-configmap.yaml
=> VZ-11193: change buffer_over_flow action to throw exception

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> sync catalog with bom

tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzsanitize.go
This PR contains the changes to wrap up the KnownHostNames map with mutex locks to avoid concurrent access on the map
=> Added synchronization while accessing map of hostnames

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
PR to uptake new Rancher image that consists of new OKE CAPI Kontainer engine driver.
=> Uptake new Rancher image

ci/JenkinsfilePeriodicTests, ci/oke-capi-cluster-driver/Jenkinsfile, tests/e2e/clusterapi/oke-capi-driver/environment.go, tests/e2e/clusterapi/oke-capi-driver/helpers.go, tests/e2e/clusterapi/oke-capi-driver/oke_cluster_driver_suite_test.go, tests/e2e/clusterapi/oke-capi-driver/oke_cluster_driver_test.go, tests/e2e/clusterapi/oke-capi-driver/structs.go
Add OKE CAPI cluster driver tests and invoke them from periodic pipeline.
=> VZ-10610 Add OKE CAPI cluster driver tests

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Rancher OKE Node Image API

platform-operator/Dockerfile, platform-operator/capi/addon-verrazzano/v1.0.0/addon-components.yaml, platform-operator/capi/addon-verrazzano/v1.0.0/metadata.yaml, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component_test.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides_test.go, platform-operator/controllers/verrazzano/testdata/test_bom.json, platform-operator/controllers/verrazzano/testdata/test_bom_host_port.json, platform-operator/verrazzano-bom.json, tests/e2e/config/scripts/looping-test/verify_uninstall.sh
This pull request updates the cluster-api component to handle the install/upgrade/uninstall of the capi verrazzano addon.
=> VZ-10979: Add install/upgrade/uninstall for capi verrazzano addon

pkg/istio/istioctl.go, pkg/istio/istioctl_test.go
istioctl uninstall graduated from experimental
=> VZ-10984: Istio 1.19.0

ci/backup/JenkinsfileAlllBackupOKETest, ci/chaos/Jenkinsfile, ci/examples/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/olcne/Jenkinsfile, ci/rolebased/Jenkinsfile
=> Turn off CI messages

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 2.0.0 to 1.7.0
=> Updating development version from 2.0.0 to 1.7.0

platform-operator/capi/addon-verrazzano/v1.0.0/addon-components.yaml, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_component.go, platform-operator/verrazzano-bom.json, tests/e2e/config/scripts/looping-test/verify_uninstall.sh
This pull request picks the latest yaml for the capi verrazzzano addon.
=> VZ-11257:  Pickup latest updates to capi verrazzano addon

application-operator/controllers/metricstrait/metricstrait_controller_test.go, platform-operator/constants/constants.go, platform-operator/controllers/verrazzano/catalog/catalog_test.go, platform-operator/controllers/verrazzano/component/dex/dex_component.go, tests/e2e/quickcreate/quickcreate_test.go, tests/e2e/verify-infra/restapi/rancher_url_test.go, tests/e2e/verify-install/dex/dex_test.go
=> Needs to pull release-1.7

platform-operator/verrazzano-bom.json
=> Update VMO and Console BOM Image Tags

platform-operator/controllers/verrazzano/component/common/prometheus.go
Change some more detailed logging messages to debug to avoid polluting the logs and the CLI
=> Convert some verbose logging to Debug

platform-operator/controllers/verrazzano/component/clusterapi/clusterapi.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_overrides.go, platform-operator/controllers/verrazzano/component/clusterapi/clusterapi_test.go, tests/e2e/clusterapi/capi-overrides/capi_overrides_test.go
=> VZ-11250: Cluster API URL overrides not working (#7268)

platform-operator/controllers/integration/opensearch/opensearch.go
=> VZ-11256: Modify OS ready check from configuring policy logic

platform-operator/controllers/integration/opensearch/opensearch.go
=> VZ-11256: Fix ready logic for OS backport to release 1.7

platform-operator/helm_config/overrides/kiali-server-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/kiali-server/Chart.yaml, platform-operator/thirdparty/charts/kiali-server/templates/deployment.yaml, platform-operator/thirdparty/charts/kiali-server/templates/oauth.yaml, platform-operator/thirdparty/charts/kiali-server/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11263: Back port Kiali 1.73.0 to release-1.7

ci/uninstall/JenkinsfileUninstallTest
=> Add echo for Verrazzano_Operator_Image to give info on Uninstall Failures

platform-operator/controllers/verrazzano/component/common/opensearch_operator.go, platform-operator/controllers/verrazzano/component/common/opensearch_operator_test.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/legacyOS_test.go, platform-operator/controllers/verrazzano/component/opensearchoperator/module_integration.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component_test.go, platform-operator/controllers/verrazzano/component/opensearchoperator/pvc.go, platform-operator/thirdparty/manifests/opensearch-operator/opensearch_cluster_cr.yaml
=> VZ-11244: Fix opensearchOperator PV migration failure on upgrade

cluster-operator/controllers/quickcreate/oke/template/cluster/cluster.goyaml, cluster-operator/controllers/quickcreate/oke/template/nodes/nodes.goyaml
- provide NSG rules for Flannel CNI
- use defaults for NPN
=> OKE Quick Create VCN Fixes

cluster-operator/controllers/quickcreate/oke/template/cluster/cluster.goyaml, cluster-operator/controllers/quickcreate/oke/template/nodes/nodes.goyaml
=> OKE Quick Create VCN Fixes (#7298)

platform-operator/controllers/verrazzano/component/common/opensearch_operator.go, platform-operator/controllers/verrazzano/component/common/opensearch_operator_test.go, platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go, platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/legacyOS_test.go, platform-operator/controllers/verrazzano/component/opensearchoperator/module_integration.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component.go, platform-operator/controllers/verrazzano/component/opensearchoperator/opensearchoperator_component_test.go, platform-operator/controllers/verrazzano/component/opensearchoperator/pvc.go, platform-operator/thirdparty/manifests/opensearch-operator/opensearch_cluster_cr.yaml
=> VZ-11244: Fix opensearchOperator PV migration failure on upgrade bp

ci/clusterAPI/JenkinsfileCAPI
- build checks on availability of NLB prior to cluster creation and will abort if no NLB becomes available in 15 minutes
- build description updated with clear indication of resource issue
- regions in which build is run have been limited to those with larger quotas of NLB
=> VZ-11198 Modify CAPI Jenkins build script to more clearly indicate resource issues

cluster-operator/controllers/quickcreate/oke/template/cluster/cluster.goyaml
Add LoadBalancer SecList for OKE QuickCreate
=> LB SecList for OKE QuickCreate

platform-operator/controllers/verrazzano/component/common/opensearch_operator.go
=> Fix OpenSearch nodepool scaling

platform-operator/controllers/verrazzano/component/common/opensearch_operator.go
=>  Fix OpenSearch nodepool scaling

platform-operator/controllers/integration/opensearch/reconciler.go
=> VZ-11275: Create template before configuring ISM policies (#7312)

tools/vz/cmd/helpers/vpo.go, tools/vz/cmd/helpers/vpo_test.go, tools/vz/cmd/install/install.go, tools/vz/cmd/upgrade/upgrade.go
=> VZ-10571 - VZ CLI should delete existing VPO deployment only after the new one has been successfully located. (#7320)

CHANGES.md
=> Add v1.6.8 updates to changes.md

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh, ci/scripts/generate_vz_distribution.sh
BP for Raagwadh/VZ-11040: Image Size increase alerts (#7171)
=> Raagwadh/VZ-11040: Image Size increase alerts (#7171)

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh
BP of  Raagwadh/vz-11040 Add Ons (https://github.com/verrazzano/verrazzano/pull/7282)
=> Raagwadh/VZ-11040 add ons BP for 1.7

ci/scripts/check_image_sizes.sh
=> VZ-11040 fix newfoundimage.txt Bug

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11277 - Update Coherence Operator to 3.3.0

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Cherry-pick of #7334 to release-1.7
=> VZ-11277 - Update Coherence Operator to 3.3.0 (#7334)

platform-operator/thirdparty/manifests/opensearch-operator/opensearch_cluster_cr.yaml, tests/e2e/verify-infra/restapi/vmi_urls_test.go
=> Increase timeout for verify-infra urls test

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#7334
=> Revert "VZ-11277 - Update Coherence Operator to 3.3.0"

platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#7335
=> Revert "VZ-11277 - Update Coherence Operator to 3.3.0 (#7334)"

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.8 to 1.6.9
=> Updating development version from 1.6.8 to 1.6.9

platform-operator/verrazzano-bom.json
=> Update BOM to 1.6.9

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Backport rancher-ui tag update (#7343)

tests/e2e/quickcreate/quickcreate_test.go
This PR updates minimum VZ version.
=> VZ-10514: Update minimum VZ version

ci/clusterAPI/JenkinsfileCAPIQC, pkg/k8s/resource/resource_util.go, tests/e2e/pkg/common.go, tests/e2e/quickcreate/addonmodels.go, tests/e2e/quickcreate/context.go, tests/e2e/quickcreate/quickcreate_test.go, tests/e2e/quickcreate/templates/verrazzanofleet-mc-profile.goyaml, tests/e2e/quickcreate/templates/verrazzanofleet-none-profile.goyaml
This PR backports verrazzanofleet addon e2e tests to release-1.7.
=> VZ-10514: Backport vz fleet addon e2e tests to release-1.7

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Update rancher tag to include VZ-11287

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Backport VZ-11287 make pod subnet required to master 

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh
=> Raagwadh/VZ-11265: Update ImageSize alert and Baseline settings (#7354) 

platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/prometheus-community/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml, platform-operator/verrazzano-bom.json
=> VZ-8159: Fix kubelet Grafana dashboard (#7349)

platform-operator/controllers/verrazzano/component/fluentoperator/fluentoperator_component.go, platform-operator/internal/config/config.go
=> VZ-11288: apply fluent-bit crds as part of preUpgrade (#7364)

platform-operator/controllers/verrazzano/component/opensearchoperator/pvc.go
Reduce error frequency for PVC deletion
=> Reduce error frequency for PVC deletion  error in OS

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Update opensearch operator image

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh
=> Raagwadh/VZ-11265: Update ImageSize alert and Baseline settings (#7354)

platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_mc.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go, platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component_test.go
Jaeger Cleanup Pre-upgrade
---------
Co-authored-by: Zaid A <zaid.abdulrehman85@gmail.com
=> Cleanup Jaeger pre-upgrade (#7378)

tests/e2e/update/opensearch/opensearch_update.go
Fix opensearch update e2e by appending the node pool instead of just adding.
=> Fix openserch e2e

tests/e2e/update/opensearch/opensearch_update.go
avoid removing nodes in aftersuite
=> avoid removing nodes in aftersuite to fix opensearch e2e

tests/e2e/update/opensearch/opensearch_update.go
=> avoid removing nodes in aftersuite

CHANGES.md
Add release note for 1.7.1 to release-1.7 changes file.
=> VZ-9709.  Add 1.7.1 release note

CHANGES.md
Port release notes for 9709 to master
=> VZ-9709.  Add 1.7.1 release note (#7386)

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.7.0 to 1.7.1
=> Updating development version from 1.7.0 to 1.7.1

platform-operator/verrazzano-bom.json
Update versions to 1.7.1 in the BOM
=> Update versions to 1.7.1 in the BOM

tests/e2e/logging/opensearch/opensearch_mappings_test.go, tests/e2e/logging/opensearch/opensearch_retention_policy_test.go, tests/e2e/logging/opensearch/opensearch_rollover_policy_test.go
=> Add data stream check for opensearch-logging e2e test

ci/chaos/JenkinsfileResiliencyTrigger, ci/cron/Jenkinsfile, ci/cron/JenkinsfileBackend, ci/lre/Jenkinsfile, ci/scan-results/Jenkinsfile, ci/uninstall/JenkinsfileUninstallSuite
This disables the release-1.4 cron schedules and automation
=> Disable 1.4 automation

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update VZ 1.5 to use WKO 4.0.10 and WME 2.1.8.
=> WebLogic Kubernetes Operator 4.0.10 and WebLogic Monitoring Exporter 2.1.8

CHANGES.md, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/templates/_operator-dep.tpl, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update VZ 1.7 to use WKO 4.1.4 and WME 2.1.8
=> WebLogic Kubernetes Operator 4.1.4 and WebLogic Monitoring Exporter 2.1.8

platform-operator/manifests/catalog/catalog.yaml
=> Correct catalog entry after update to WKO 4.1.4

tests/e2e/config/scripts/create_ocir_repositories.sh
=> Backport VZ-11129 to 1.7

tests/e2e/config/scripts/create_ocir_repositories.sh
=> Backport VZ-11129 to 1.5

tests/e2e/config/scripts/create_ocir_repositories.sh
=> Backport VZ-11129 to 1.6

ci/ocne-cluster-driver/Jenkinsfile, ci/oke-capi-cluster-driver/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/olcne/Jenkinsfile, ci/uninstall/Jenkinsfile
=> VZ 11312: Ensure Jenkins jobs specify a label

ci/JenkinsfilePeriodicTests, ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR removes the redundant jobs from the periodic.
=> VZ-11395: Remove redundant jobs from the periodic

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR removes the upgrade job from release to tip of the master branch.
=> VZ-11395: Remove upgrade job from release to master branch

ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
This PR removes the upgrade job - tip of release to master branch.
=> VZ-11395: Remove upgrade job from tip of release to master branch. 

platform-operator/capi/infrastructure-oci/v0.13.0/infrastructure-components.yaml, platform-operator/capi/infrastructure-oci/v0.13.0/metadata.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11465 - Pick up new CAPI OCI controllers

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11459 update the nginx images for the distroless base

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Changes the base image of External DNS to the static distroless image
=> VZ-11466 Change the base image for External DNS to distroless static image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11481 Use the distroless Fluent Operator image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11482: backport capi ocne golang change to 1.7

platform-operator/verrazzano-bom.json
=> VZ-11482: backport capi ocne golang change to 1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11488: New capi addon image and catalog update

ci/oke-ocidns/JenknsfileDnsKind
DNS sweep tests for kind need to use JAO labels
=> Use the JAO labels

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11472 add the opensearch operator distroless image

ci/periodic/JenkinsfileDistributions, ci/scripts/check_image_sizes.sh
This pull request adds the archiving of the image size increase file. The name of the file was also renamed from results.txt to image-increases.txt.
=> archive image-increases.txt

Jenkinsfile, THIRD_PARTY_LICENSES.txt, application-operator/tools.go, cluster-operator/controllers/rancher/rancher_cluster_controller.go, cluster-operator/controllers/vmc/vmc_controller.go, go.mod, go.sum, make/quality.mk, pkg/os/shell.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_component.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer_test.go, platform-operator/controllers/verrazzano/component/dex/dex_test.go, platform-operator/controllers/verrazzano/component/externaldns/external_dns.go, platform-operator/controllers/verrazzano/component/istio/istio_component.go, platform-operator/controllers/verrazzano/component/istio/jaeger_test.go, platform-operator/tools.go, tools/vz/cmd/helpers/operator_yaml.go, tools/vz/cmd/helpers/vpo.go, tools/vz/pkg/analysis/main_test.go
=> VZ-11406: Go 1.20 support

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ 14486: Kiali update

platform-operator/verrazzano-bom.json
=> VZ 11486: Kiali patch

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ 14486: Kiali update (#7486)

CHANGES.md, platform-operator/Makefile, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ 11487: Istio 1.19.3 (#7472)

platform-operator/verrazzano-bom.json
=> VZ 11487: Istio patch

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update Velero images built with Golang 1.20-10
=> VZ-11485: Update Velero images built with Golang 1.20-10

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.9 to 1.6.10
=> Updating development version from 1.6.9 to 1.6.10

platform-operator/verrazzano-bom.json
=> Update BOM to 1.6.10

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update Velero images built with Golang 1.20-10
=> VZ-11485: Update Velero images built with Golang 1.20-10 (#7500)

ci/a-la-carte/Jenkinsfile, ci/backup/JenkinsfileAlllBackupOKETest, ci/clusterAPI/JenkinsfileCAPI, ci/clusterAPI/JenkinsfileCAPIQC, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/ocne-cluster-driver/Jenkinsfile, ci/oke-capi-cluster-driver/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/oke-ocidns/JenknsfileDnsKind, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
=> VZ-11517: Remove Frankfurt from all Jenkinsfiles except private registry tests

ci/a-la-carte/Jenkinsfile, ci/backup/JenkinsfileAlllBackupOKETest, ci/clusterAPI/JenkinsfileCAPI, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/ocne-cluster-driver/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/oke-ocidns/JenknsfileDnsKind, ci/uninstall/Jenkinsfile, ci/upgrade-paths/Jenkinsfile
=> VZ-11517: Remove Frankfurt from all Jenkinsfiles except the private registry tests

ci/oke-ocidns/JenknsfileDnsKind
=> VZ-11517: Remove Frankfurt from all test pipelines except private registry

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11503: Pick up Rancher images built with golang 1.20.10 on master branch

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Distroless image for the Keycloak Oracle Theme
=> VZ-11509 add the keycloak oracle theme distroless image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> update opensearh operator image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ 11526: Rancher paginates OCI requests

tools/url_linter/ignore_urls.txt
=> backport dead url ignore to 1.5

tools/url_linter/ignore_urls.txt
=> backport dead url ignore to 1.6.9

tools/url_linter/ignore_urls.txt
=> backport dead url ignore to 1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11528: Update Dex and ArgoCD images

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates Dex and ArgoCD images in release-1.7
=> VZ-11528: Update Dex and ArgoCD images in release-1.7

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> update thanos version

platform-operator/verrazzano-bom.json
=> update thanos image

ci/periodic/JenkinsfileDistributions
Don't send image size increase slack alert by default
=> VZ-11551: don't send image size increase slack alert by default

platform-operator/verrazzano-bom.json
Updates ArgoCD image in release-1.5
=> VZ-11528: Update ArgoCD image in release-1.5

platform-operator/verrazzano-bom.json
Updates ArgoCD image in release-1.6
=> VZ-11528: Update ArgoCD image in release-1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11552 - Update Coherence Operator to 3.3.2

ci/periodic/JenkinsfileDistributions
Backport change to not send image size alert by default to release-1.6.9
=> Backport change to not send image size alert by default

CHANGES.md, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/export/export.go, tools/vz/cmd/export/oam/oam.go, tools/vz/cmd/helpers/cmd_context.go, tools/vz/cmd/root/root.go, tools/vz/cmd/root/root_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzhelper.go
Back port changes to add "export oam" to the "vz cli"
=> VZ-11550: Add "export oam" to the CLI (#7559)

CHANGES.md, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/export/export.go, tools/vz/cmd/export/oam/oam.go, tools/vz/cmd/helpers/cmd_context.go, tools/vz/cmd/root/root.go, tools/vz/cmd/root/root_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzhelper.go, tools/vz/test/helpers/fake_cmd_context.go
=> VZ-11550: Back port "vz export oam" to release-1.6

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11595: update capi ocne and addon

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11595-update capi ocne and addon (#7568)

release/builds/JenkinsfileReleaseExistingCandidate
=> backport vz-11545 to 1.7

release/builds/JenkinsfileReleaseExistingCandidate
=> backport vz-11545 to 1.5

release/builds/JenkinsfileReleaseExistingCandidate
=> backport vz-11545 to 1.6

CHANGES.md, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11604: Update Coherence Operator to 3.3.2 on release-1.7

CHANGES.md, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11604: Uptake Coherence Operator 3.3.2 on release-1.6

CHANGES.md, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
=> VZ-11604: Update to coherence-operator 3.3.2 on release-1.5

CHANGES.md, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#7585
=> Revert "VZ-11604: Update to coherence-operator 3.3.2 on release-1.5"

CHANGES.md, platform-operator/helm_config/overrides/coherence-values.yaml, platform-operator/thirdparty/charts/coherence-operator/Chart.yaml, platform-operator/thirdparty/charts/coherence-operator/README.md, platform-operator/thirdparty/charts/coherence-operator/templates/deployment.yaml, platform-operator/thirdparty/charts/coherence-operator/templates/rbac.yaml, platform-operator/thirdparty/charts/coherence-operator/values.yaml, platform-operator/verrazzano-bom.json
Reverts verrazzano/verrazzano#7571
=> Revert "VZ-11604: Uptake Coherence Operator 3.3.2 on release-1.6"

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> update opensearchoperator image built with 1.20.12

platform-operator/controllers/verrazzano/component/thanos/thanos_test.go, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11415: New Version of prom operator

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
This PR uptakes latest backup and restore operator from BFS.
=> VZ-11495: Uptake latest backup and restore operator. 

platform-operator/controllers/verrazzano/catalog/catalog_test.go, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11554: New version of fluent-bit

platform-operator/verrazzano-bom.json
This PR uptakes latest backup and restore operator with Golang version update to v1.20.12
=> VZ-11495: Uptake latest backup and restore operator.  (#7594)

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update jaeger images built with golang 1.20.12.
=> VZ-11615: Update jaeger images built with golang 1.20.12

platform-operator/verrazzano-bom.json
Update jaeger images built with 1.20.12.
=> VZ-11615: Update jaeger images built with 1.20.12

tools/vz/cmd/export/oam/oam.go
The incorrect group/version was being set for ManualScalarTrait, and it was not being excluded from the output.
=> Fix vz oam export handling of ManualScalerTrait

tools/vz/cmd/export/oam/oam.go
=> Fix vz oam export handling of ManualScalerTrait (#7595) - back port to release-1.7

tools/vz/cmd/export/oam/oam.go
=> Fix vz oam export handling of ManualScalerTrait (#7595) - back port to release-1.6

ci/chaos/JenkinsfileResiliencyTrigger, ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go
This PR derives version tags based on dev version.
=> VZ-11508: Derive version tags specific to release branches. 

ci/chaos/JenkinsfileResiliencyTrigger, ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go
This PR fixes the upgrade resiliency pipeline by deriving appropriate versions for the interim and install release.
=> VZ-11508: Fix upgrade resiliency pipeline for 1.5

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update istio images built with golang 1.20.12.
=> VZ-11626: Update istio images built with golang 1.20.12

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11449: Update some of the Rancher images (back port to release-1.7)

ci/chaos/JenkinsfileResiliencyTrigger, ci/tools/derive_upgrade_version.go, ci/tools/derive_upgrade_version_test.go
This PR fixes the copyright issue.
=> VZ-11508: Fix copyright

platform-operator/verrazzano-bom.json
=> VZ-11621: Update VMO image tag

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.10 to 1.6.11
=> Updating development version from 1.6.10 to 1.6.11

platform-operator/verrazzano-bom.json
=> Update BOM for 1.6.11

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update Thanos Image in BOM and catalogue
=> Update Thanos (golang-1.20.12) image

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update Thanos image with Golang-1.20.12
=> Update Thanos image with Golang-1.20.12

platform-operator/Makefile, platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Update istio images with backport of https://github.com/envoyproxy/envoy/pull/30807.
=> VZ-11637: Update istio images with backport of https://github.com/envoyproxy/envoy/pull/30807

release/builds/JenkinsfileReleaseExistingCandidate
Edit regex logic so it supports releases with .10
=> Edit regex logic so it supports releases with .10

release/builds/JenkinsfileReleaseExistingCandidate
=> Fix current year of copyright

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
Updates NGINX images built using Go 1.20.12
=> VZ-11614: Update NGINX images built using Go 1.20.12

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> Update fluent operator image with go 1.20.12

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/export/oam/oam.go, tools/vz/cmd/install/install.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go, tools/vz/pkg/analysis/internal/util/report/report.go
These changes backport VZ-11647 to release-1.7.
=> Backport VZ-11647 to release-1.7 

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11415: Update prometheus stack images

tools/vz/pkg/helpers/vzsanitize.go
Backport https://github.com/verrazzano/verrazzano/pull/7651
=> VZ-11656: Analysis tool - ensure all redacted values have a unique hash

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/networking.go, tools/vz/pkg/analysis/internal/util/cluster/networking_test.go, tools/vz/pkg/analysis/internal/util/files/parse_install_log.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdle/cluster-snapshot/istio-system/testIstioPodName/logs.txt, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdle/verrazzano-resources.json, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdleIssueOccursInTwoPods/cluster-snapshot/istio-system/testIstioPodName/logs.txt, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdleIssueOccursInTwoPods/cluster-snapshot/istio-system/testIstioPodNameTwo/logs.txt, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdleIssueOccursInTwoPods/verrazzano-resources.json, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdleNotOccurring/cluster-snapshot/istio-system/testIstioPodName/logs.txt, tools/vz/pkg/analysis/test/cluster/testTCPKeepIdleNotOccurring/verrazzano-resources.json
* First pass of adding version of CLI output to commands
* Remove version output from version command
* Update copyright
* Work in progress on detecting networking issues
* Saving changes
* Inital first pass of detecting TCP Keep Idle Issues
* Have initial unit tests working, added a helper function to parse non-VZ produced logs, used feedback from unit tests to tweak on codes
* Update unit test cases, fix more bugs in code as a result of unit tests
* Remove old work on VZ -11647 from this commit
* Respond to initial feedback
* Remove print line through debugging
* Fix typo of occurred
* Respond to gofmt lint
* Further respond to lint
* Fix copyright
* Further fix copyrights, fix other instances of misspellings of occurred, and make summary clearer
* Further commit changes to files that …
=> VZ-11648: Add TCP Keep Idle Issue Detection To Analysis Tool  (#7657)

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/install/install.go, tools/vz/cmd/status/status.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/cmd/upgrade/upgrade.go, tools/vz/cmd/version/version.go, tools/vz/pkg/analysis/internal/util/report/report.go
This change back ports VZ-11647 to the release-1.6 branch
=> Backport VZ-11647

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, release/scripts/scan_bom_images.sh
Fix daily scanning job to handle multiple backslash characters in the description.
=> VZ-11659: Fix daily scanning job to handle multiple backslash characters in the description

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, release/scripts/scan_bom_images.sh
Backports https://github.com/verrazzano/verrazzano/pull/7665 to release-1.7
=> VZ-11659: Escape characters starting with multiple backslash characters in scan report, release-1.7

ci/scan-results/Jenkinsfile, ci/scripts/get_branch_scan_results.sh, release/scripts/scan_bom_images.sh
Backports https://github.com/verrazzano/verrazzano/pull/7665 to release-1.5
=> VZ-11659: Escape characters starting with multiple backslash characters in scan report, release-1.5

ci/scripts/get_branch_scan_results.sh
Ports https://github.com/verrazzano/verrazzano/pull/7679 to master
=> Workaround to resolve issue with daily scan job for release branches

ci/scripts/get_branch_scan_results.sh
Ports https://github.com/verrazzano/verrazzano/pull/7679 to release-1.5
=> Workaround to resolve issue with daily scan job for release branches, in release-1.5

Jenkinsfile, ci/JenkinsfileBackendTests, ci/backup/JenkinsfileAlllBackupKinDTest, ci/backup/JenkinsfileAlllBackupOKETest, ci/chaos/Jenkinsfile, ci/dynamic-updates/Jenkinsfile, ci/dynamic-updates/JenkinsfileUpdateDuringInstall, ci/examples/Jenkinsfile, ci/generic/Jenkinsfile, ci/generic/Jenkinsfile-singletarget, ci/ha/JenkinsfileRollingUpgrade, ci/kind/Jenkinsfile, ci/multicluster/Jenkinsfile, ci/multiplatform/Jenkinsfile, ci/no-injection/Jenkinsfile, ci/oci-integration/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, ci/oke-ocidns/JenknsfileDnsKind, ci/olcne/Jenkinsfile, ci/private-registry/Jenkinsfile, ci/rolebased/Jenkinsfile, ci/scripts/metric_del.sh, ci/scripts/metric_emit.sh, ci/uninstall/Jenkinsfile, ci/uninstall/JenkinsfileUninstallTest, ci/upgrade-paths/Jenkinsfile, ci/vz-analyze/Jenkinsfile, tests/e2e/pkg/test/framework/ginkgo_wrapper_util.go, tests/e2e/pkg/test/framework/ginkgo_wrapper_util_test.go
=> backport VZ-11667 to 1.5

tools/psr/backend/config/config.go, tools/psr/backend/workers/echo/client/echoclient.go, tools/psr/backend/workmanager/manager.go, tools/psr/manifests/charts/worker/templates/component.yaml, tools/psr/manifests/charts/worker/templates/deployment.yaml, tools/psr/manifests/charts/worker/values.yaml, tools/psr/manifests/scenarios/echo-client/s1/scenario.yaml, tools/psr/manifests/scenarios/echo-client/s1/worker-overrides/echo.yaml, tools/psr/manifests/scenarios/opensearch/s5/scenario.yaml, tools/psr/manifests/scenarios/opensearch/s6/scenario.yaml, tools/psr/manifests/scenarios/opensearch/s8/scenario.yaml, tools/psr/manifests/scenarios/opensearch/s9/scenario.yaml, tools/psr/manifests/scenarios/weblogic/s1/scenario.yaml, tools/psr/manifests/scenarios/weblogic/s3/scenario.yaml, tools/psr/manifests/worker-config/echo/echo-client.yaml
The echo client runs in the cluster and sends packs to the echo server (in the Istio mesh) via the Istio ingressgateway.
This has no affect on the main Verrazzano product.
=> PSR tool echo client used to stress test HTTP/TCP connections

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11415:added new version of pushgateway

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ:11415: New version of grafana

platform-operator/manifests/catalog/catalog.yaml, platform-operator/verrazzano-bom.json
=> VZ-11415:new version of grafana

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/analyze/analyze_test.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/uninstall/uninstall.go, tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/analyzer_test.go, tools/vz/pkg/analysis/main.go, tools/vz/pkg/analysis/main_test.go
This PR fixes the inconsistent logging behavior where certain errors were not logged to stderr and errors were  logged to stdout.
=> VZ-10308: Fix inconsistent error logging behavior

tools/vz/cmd/analyze/analyze_test.go
=> Add copyright for analyze_test_file for backport

tests/e2e/verify-analyze-tool/image/image_test.go, tests/e2e/verify-analyze-tool/node/node_test.go, tests/e2e/verify-analyze-tool/pod/pod_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
=> VZ-11651: Analysis tool redacted values mapping

tools/vz/cmd/install/install.go, tools/vz/pkg/analysis/internal/util/cluster/install.go, tools/vz/pkg/analysis/internal/util/report/action.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/main_test.go, tools/vz/pkg/analysis/test/cluster/blockstorage-limitexceeded/cluster-snapshot/keycloak/events.json, tools/vz/pkg/analysis/test/cluster/blockstorage-limitexceeded/cluster-snapshot/verrazzano-resources.json
BP for VZ-9083: VZ analyze should be able to detect PV LimitExceeded issues (#7703)
=> BP for VZ-9083: VZ analyze should be able to detect PV LimitExceeded issues (#7703)

CHANGES.md, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json
Update to use WebLogic Kubernetes Operator 4.1.8 and WebLogic Monitoring Exporter 2.1.9.
=> WKO 4.1.8 and WME 2.1.9

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/certificates.go, tools/vz/pkg/analysis/internal/util/cluster/deployments_test.go, tools/vz/pkg/analysis/internal/util/cluster/events.go, tools/vz/pkg/analysis/internal/util/cluster/install.go, tools/vz/pkg/analysis/internal/util/cluster/pods.go, tools/vz/pkg/analysis/internal/util/cluster/verrazzano.go, tools/vz/pkg/analysis/internal/util/files/files.go, tools/vz/pkg/analysis/internal/util/files/files_test.go, tools/vz/pkg/analysis/internal/util/files/text.go, tools/vz/pkg/analysis/internal/util/files/text_test.go, tools/vz/pkg/analysis/internal/util/json/json.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/internal/util/report/issue_test.go, tools/vz/pkg/analysis/internal/util/report/report.go
This PR changes some of the function names in the analysis tool to more accurately describe how they behave. This involved refactoring the analysis tool code and associated unit tests.
=> VZ-11699: Refactor Analysis Tool Code To Remove Unclear Function Names 

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/certificates.go, tools/vz/pkg/analysis/internal/util/cluster/deployments_test.go, tools/vz/pkg/analysis/internal/util/cluster/events.go, tools/vz/pkg/analysis/internal/util/cluster/install.go, tools/vz/pkg/analysis/internal/util/cluster/pods.go, tools/vz/pkg/analysis/internal/util/cluster/verrazzano.go, tools/vz/pkg/analysis/internal/util/files/files.go, tools/vz/pkg/analysis/internal/util/files/files_test.go, tools/vz/pkg/analysis/internal/util/files/text.go, tools/vz/pkg/analysis/internal/util/files/text_test.go, tools/vz/pkg/analysis/internal/util/json/json.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/internal/util/report/issue_test.go, tools/vz/pkg/analysis/internal/util/report/report.go
Reverts verrazzano/verrazzano#7719
=> Revert "VZ-11699: Refactor Analysis Tool Code To Remove Unclear Function Names "

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/certificates.go, tools/vz/pkg/analysis/internal/util/cluster/deployments_test.go, tools/vz/pkg/analysis/internal/util/cluster/events.go, tools/vz/pkg/analysis/internal/util/cluster/install.go, tools/vz/pkg/analysis/internal/util/cluster/namespaces.go, tools/vz/pkg/analysis/internal/util/cluster/pods.go, tools/vz/pkg/analysis/internal/util/cluster/verrazzano.go, tools/vz/pkg/analysis/internal/util/files/files.go, tools/vz/pkg/analysis/internal/util/files/files_test.go, tools/vz/pkg/analysis/internal/util/files/text.go, tools/vz/pkg/analysis/internal/util/files/text_test.go, tools/vz/pkg/analysis/internal/util/json/json.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/internal/util/report/issue_test.go, tools/vz/pkg/analysis/internal/util/report/report.go
* Change unclear function names and refactor
* Further refactor
* Further fix refactoring
* Fix copyright:
* Respond to Marco's comments
* Address merging issues
* Fix build issue in namespaces.go file
=> VZ-11699: Merge With Current Build Of Master To Address VZ-11699 (#7724)

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
Backport https://github.com/verrazzano/verrazzano/pull/7720
=> VZ-11670: --redacted-values-file flag for vz bug-report

tools/vz/pkg/analysis/internal/util/cluster/analyzer.go, tools/vz/pkg/analysis/internal/util/cluster/deployments_test.go, tools/vz/pkg/analysis/internal/util/cluster/events.go, tools/vz/pkg/analysis/internal/util/cluster/install.go, tools/vz/pkg/analysis/internal/util/cluster/pods.go, tools/vz/pkg/analysis/internal/util/cluster/verrazzano.go, tools/vz/pkg/analysis/internal/util/files/files.go, tools/vz/pkg/analysis/internal/util/files/files_test.go, tools/vz/pkg/analysis/internal/util/files/text.go, tools/vz/pkg/analysis/internal/util/files/text_test.go, tools/vz/pkg/analysis/internal/util/json/json.go, tools/vz/pkg/analysis/internal/util/report/issue.go, tools/vz/pkg/analysis/internal/util/report/issue_test.go, tools/vz/pkg/analysis/internal/util/report/report.go
=> BP VZ-11699 to release-1.6 (#7724)

tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/sanitize/sanitize.go, tools/vz/cmd/sanitize/sanitize_test.go
Backport https://github.com/verrazzano/verrazzano/pull/7735
=> VZ-11670:  add --redacted-values-file flag to the vz sanitize command 

tools/vz/cmd/analyze/analyze.go, tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/sanitize/sanitize.go, tools/vz/cmd/sanitize/sanitize_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
Backport https://github.com/verrazzano/verrazzano/pull/7720 and https://github.com/verrazzano/verrazzano/pull/7735
=> VZ-11670: --redacted-values-file flag for vz bug-report and sanitize

tools/vz/pkg/helpers/vzsanitize.go, tools/vz/pkg/helpers/vzsanitize_test.go
* create branch
* Added preliminary version of ssh regex
* Improved regex to include ecdsa
* rename variables
* updated variable definitions for clarity
=> VZ-11660 Improve SSH Key Redaction (#7710)

tools/vz/cmd/bugreport/bugreport.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/sanitize/sanitize.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/pkg/constants/constants.go, tools/vz/pkg/helpers/vzhelper.go
Backport https://github.com/verrazzano/verrazzano/pull/7748 and https://github.com/verrazzano/verrazzano/pull/7747
=> VZ-11675, VZ-11724: Auto bug report 2 cluster snapshots and redaction file

tools/vz/cmd/bugreport/bugreport_test.go
=> Add strings import in

ci/JenkinsfilePeriodicTests
=> Backport VZ-11734 to 1.7

ci/JenkinsfilePeriodicTests
=> Backport VZ-11734 to 1.6

ci/JenkinsfilePeriodicTests
=> BP fix for VZ-11734 to 1.7

ci/JenkinsfilePeriodicTests
=> BP fix for VZ-11734 to 1.6

tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/pkg/internal/util/log/log.go
Backport https://github.com/verrazzano/verrazzano/pull/7764
=> VZ-11772: Fix TestBugReportGetPreviousLogs unit test

tools/vz/cmd/analyze/analyze_test.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/helpers/cmd_context_test.go, tools/vz/cmd/helpers/command_test.go, tools/vz/cmd/helpers/vpo_test.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/root/root_test.go, tools/vz/cmd/sanitize/sanitize_test.go, tools/vz/cmd/status/status_test.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/cmd/version/version_test.go, tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/test/helpers/fake_cmd_context.go
Backport VZ-11703 to release-1.6
=> Backport VZ-11703 to release-1.6: Refactor CLI Test Code (#7760)

tools/vz/cmd/analyze/analyze_test.go, tools/vz/cmd/bugreport/bugreport_test.go, tools/vz/cmd/helpers/cmd_context_test.go, tools/vz/cmd/helpers/command_test.go, tools/vz/cmd/helpers/vpo_test.go, tools/vz/cmd/install/install_test.go, tools/vz/cmd/install/state_test.go, tools/vz/cmd/root/root_test.go, tools/vz/cmd/sanitize/sanitize_test.go, tools/vz/cmd/status/status_test.go, tools/vz/cmd/uninstall/uninstall_test.go, tools/vz/cmd/upgrade/upgrade_test.go, tools/vz/cmd/version/version_test.go, tools/vz/pkg/helpers/vzcapture.go, tools/vz/pkg/helpers/vzsanitize.go, tools/vz/test/helpers/fake_cmd_context.go
Backport VZ-11703 to release-1.7
=> Backport VZ-11703 to release-1.7: Refactor CLI Test Code (#7760)

ci/cron/Jenkinsfile, ci/cron/JenkinsfileBackend, ci/scan-results/Jenkinsfile
=> Disable crons for release-1.5

tools/vz/pkg/helpers/vzcapture.go
Adds additional check to verify if the appropriate number of components for app config are created
=> VZ-11694:verify if the appropriate number of components for app config are created

tools/vz/pkg/helpers/vzcapture_test.go
Backport https://github.com/verrazzano/verrazzano/pull/7781
=> VZ-8679: unit tests for capture VZProjects and VMCs

ci/tools/derive_upgrade_version_test.go
This PR fixes copyright by updating the year to 2024.
=> Fix Copyright issue

tools/vz/pkg/helpers/vzcapture.go
Removes "Capturing Capturing Time In RFC 3339 Format  ..." from the bug-report.out and other minor issues
=> vz-11712 Addresses bug-report minor issues

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.7.1 to 1.7.2
=> Updating development version from 1.7.1 to 1.7.2

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.11 to 1.6.12
=> Updating development version from 1.6.11 to 1.6.12

release/scripts/scan_bom_images.sh
=> Add in sed to clean javascript CVE message that causes parser errors

ci/JenkinsfilePeriodicTests, ci/a-la-carte/JenkensfileALaCarteTriggered, ci/a-la-carte/Jenkinsfile, ci/oke-ocidns/Jenkinsfile, pkg/certs/letsencrypt.go, pkg/certs/letsencrypt_test.go, platform-operator/controllers/verrazzano/component/certmanager/issuer/cluster_issuer.go, tests/e2e/pkg/acme_ca_certs.go, tests/e2e/pkg/web.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
Backport of .OLCNE-6488: Disable ACME Staging Tests In Pipeline (#7805)
=> OLCNE-6488: Disable ACME Staging Tests In Pipeline (#7805)

ci/JenkinsfilePeriodicTests, ci/a-la-carte/JenkensfileALaCarteTriggered, tests/e2e/pkg/acme_ca_certs.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
Add Staging Root CA to trust stores
=> Add Staging Cert

ci/JenkinsfilePeriodicTests, ci/a-la-carte/JenkensfileALaCarteTriggered, tests/e2e/pkg/acme_ca_certs.go, tests/e2e/update/a-la-carte/a_la_carte_test.go
BP of Add Staging Cert (#7812)
=> Add Staging Cert (#7812)

ci/clusterAPI/JenkinsfileCAPI
The ephemeral key change broke the CAPI kind tests, fix that
=> Fix CAPI kind tests

ci/clusterAPI/JenkinsfileCAPI
=> BP of CAPI test fix to 1.7

ci/clusterAPI/JenkinsfileCAPI
=> BP of CAPI test fix to 1.6

CHANGES.md
Update release-1.6 release notes
=> Update release-1.6 release notes

CHANGES.md
Update release-1.7 release notes for cert fix
=>  Update release-1.7 release notes

CHANGES.md
Update release notes for cert fix
=> Update release notes 

CHANGES.md, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json, tests/testdata/ingress/console/components.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-components.yaml
=> Ryan wko 4.2.5 and new example-todo image with jq added

CHANGES.md, examples/multicluster/todo-list/todo-list-components.yaml, examples/todo-list/todo-list-components.yaml, platform-operator/manifests/catalog/catalog.yaml, platform-operator/thirdparty/charts/weblogic-operator/Chart.yaml, platform-operator/thirdparty/charts/weblogic-operator/values.yaml, platform-operator/verrazzano-bom.json, tests/testdata/ingress/console/components.yaml, tests/testdata/loggingtrait/weblogicworkload/weblogic-logging-components.yaml
Backport WKO 4.2.5, WME 2.2.0, and todo test jq to 1.7
=> Backport WKO 4.2.5, WME 2.2.0, and todo test jq to 1.7

THIRD_PARTY_LICENSES.txt
=> Incorporate license update for GoLang 1.21.12

THIRD_PARTY_LICENSES.txt
=> Backport golang license update from BA to 1.7

Jenkinsfile, THIRD_PARTY_LICENSES.txt, go.mod, go.sum, platform-operator/controllers/verrazzano/reconcile/uninstall_test.go
This was not included in the BFS refresh pass unit test issue that needed to be addressed
=> GoLang 1.21.12 update backport to 1.6

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.7.2 to 1.7.3
=> Updating development version from 1.7.2 to 1.7.3

.verrazzano-development-version, platform-operator/helm_config/charts/fluentbit-opensearch-output/Chart.yaml, platform-operator/helm_config/charts/verrazzano-application-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-authproxy/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-agent/Chart.yaml, platform-operator/helm_config/charts/verrazzano-cluster-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-console/Chart.yaml, platform-operator/helm_config/charts/verrazzano-fluentd/Chart.yaml, platform-operator/helm_config/charts/verrazzano-grafana-dashboards/Chart.yaml, platform-operator/helm_config/charts/verrazzano-monitoring-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano-network-policies/Chart.yaml, platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml, platform-operator/helm_config/charts/verrazzano/Chart.yaml
Updating development version from 1.6.12 to 1.6.13
=> Updating development version from 1.6.12 to 1.6.13
